### ISSUE TITLE
Projection to other times fail in Maxent when model is calibrated using a mask

### ISSUE THREAD

**Issue by nnbuainain** [biomodhub/biomod2#10]
Hi,

When I try to project my model to the other times, the output is a raster with value 1 for all cells. I calibrated my model clipping all variables with a custom mask. Projection to the present works fine but to the past does not work. I wonder if this could be related to the use of a mask to clip the environmental variables. I've used the same mask to project models using maxent directly and it also worked fine. When I plot the stack of environmental variables they all look ok. 

I appreciate any guidance or clues of what's going on.

best, 

----------

This is how  set up the model:

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = ENV,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                     PA.nb.rep=1,
                                     PA.nb.absences=30000,
                                     #PA.strategy="disk",
                                     PA.strategy="sre",
                                     #PA.dist.min=50000,
                                     #PA.dist.max=1000000
                                     PA.sre.quant=0.005
)

This is how I ran the model:

myBiomodModelOutPA <- BIOMOD_Modeling(
  myBiomodData,
  models='MAXENT.Phillips',
  models.options = myBiomodOption,
  NbRunEval=5,
  DataSplit=70, 
  VarImport=1, 
  models.eval.meth = c('ROC','TSS'),
  SaveObj = TRUE,
  rescal.all.models = TRUE,
  modeling.id = paste(myRespName,"user",sep=""))

How I projected to the present

myBiomodProjPA <- BIOMOD_Projection(
  modeling.output = myBiomodModelOutPA,
  new.env = ENV,
  proj.name = 'current',
  selected.models = get_built_models(myBiomodModelOutPA), value=TRUE,
  compress = 'xz',
  clamping.mask = T)

How I projected to the past

myBiomodLIGProjPA <- BIOMOD_Projection(
  modeling.output = myBiomodModelOutPA,
  new.env = ENV.LIG,
  proj.name = 'LIG',
  selected.models = 'all',
  compress = 'xz',
  clamping.mask = TRUE)

This is how I built my environmental space using the masks.

bio2<-raster("bio_2.tif")
ext.user<-extent(env.shape)
bio2<-crop(bio2,ext.user)
arr.r<-rasterize(arremonshp, bio2)

list.WCfiles<-list.files("./", ".tif")

WC.all<-stack()
for(i in 1:length(list.WCfiles)){
  ri<-crop(raster(list.WCfiles[i]),ext.user)
  ri<-ri*arr.r
  WC.all<-addLayer(WC.all,ri)  
}

WC.mask<-WC.all[[1]]
WC.mask[WC.all[[1]] >= minValue(WC.all[[1]])] <- 1

ENV<-stack(WC.all)

all.mask<-WC.mask

ENV<-ENV * all.mask

**Comment by Farewe** [comment]
Hello @nnbuainain,

I think it would help the devs to solve the issue if you provided more information: the exact error message that you have, and also details about your versions (R, biomod2, OS).

**Comment by nnbuainain** [comment]
I'm using R 3.6.1 on R studio 1.2.1335. Biomod2 3.3-7.1 and MacOS High Sierra 10.13.6.

**Comment by Farewe** [comment]
Please also add the error message. It's very difficult to troubleshoot something without knowing the actual error.

**Comment by nnbuainain** [comment]
Sorry about that. There is no error message. Everything runs fine, but the result is just a flat raster.

**Comment by DamienGeorges** [comment]
Are you sure your current and future environmental raster stack are on the same scales ?
Do they have the same layer names?

`summary(ENV)`
`summary(WC.all)`
