### ISSUE TITLE
Model selection in `BIOMOD_EnsembleForecasting`

### ISSUE THREAD

**Issue by basille** [biomodhub/biomod2#100]
Debugging another part of my code, I found out that `BIOMOD_EnsembleForecasting()` makes a call to `.BIOMOD_EnsembleForecasting.check.args()`, which in turn [calls](https://github.com/biomodhub/biomod2/blob/a6dd92c8b0f1843de76f0662d236904c5e6efdc0/R/BIOMOD_EnsembleForecasting.R#L488):

```
    needed_pred <- get_needed_models(bm.em, models.chosen = models.chosen)  
```

However, the function `get_needed_models()` [expects](https://github.com/biomodhub/biomod2/blob/8121c59da91e3c1f27f08768549279774bed144d/R/biomod2_classes_3.R#L1015-L1026) a `selected.models` argument, making the aforementioned call moot.

**Comment by rpatin** [comment]
Hello @basille 
Thanks for pointing out the code incoherence. We made a series of corrections following our investigations and thanks to that `BIOMOD_EnsembleForecasting` should avoid reprojecting all models multiple time !
