### ISSUE TITLE
Can't build some models using only one predictor

### ISSUE THREAD

**Issue by pabloriul** [biomodhub/biomod2#102]
Dear Maya,

I can't get a model using only one predictor for MAXENT.Phillips, MAXENT.Phillips.2 and GBM. Tried using the GuloGulo example as follows:

**First attempt was subsetting the stack for one raster**

myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')

myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

myExpl <- myExpl[[1]]

**Second attempt was loading only one raster**

myFiles <- paste0('external/bioclim/current/bio3.grd')

myExpl <- raster(system.file(myFiles, package = 'biomod2'))

**Third attempt was stacking the single file**

myFiles <- paste0('external/bioclim/current/bio3.grd')

myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

**Maxent models returns** 

Model=MAXENT.Phillips (maxnet)
	> MAXENT.Phillips modeling...Error in apply(pdata, 1, function(rr) !any(apply(ndata, 1, function(r) identical(r,  : 
  dim(X) must have a positive length
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found

**GBM models returns** 

> GBM modeling...CV: 1 
Error in x[i.train, , drop = TRUE][i, , drop = FALSE] : 
  incorrect number of dimensions
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found

In both cases they can't find model.bm.

Do you have any idea whats going on?

Thank you

Pablo Riul

**Comment by pabloriul** [comment]
Dear Rémi,

Thank you very much for your quick reply! Its working fine now.

Cheers,

Pablo

**Comment by rpatin** [comment]
`maxnet` was updated so installation can now be done directly from their official repo:
`devtools::install_github("mrmaxent/maxnet")`
