### ISSUE TITLE
Question with BIOMOD_RangeSize results

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#105]
Hi,biomod2 team:
I met a question about biomod rangesize,why $Compt.By.Models is 0 or NA?
SRC_current_ssp245_2030 <- BIOMOD_RangeSize(bee_bin_proj_current, bee_bin_proj_ssp245_2030)
> SRC_current_ssp245_2030
$Compt.By.Models
      Loss Stable0 Stable1 Gain PercLoss PercGain SpeciesRangeChange CurrentRangeSize FutureRangeSize.NoDisp
ca      0       0       0    0      NaN      NaN                NaN                0                      0
wm    0       0       0    0      NaN      NaN                NaN                0                      0 

Thank you

**Comment by rpatin** [comment]
Hello @chenyongpeng1,
Did your models `bee_bin_proj_current` and `bee_bin_proj_ssp245_2030` actually projected non-zeros distribution ?
Judging just from your range-size comparison, 0 are calculated for column `Loss`, `Stable0`, `Stable1`, `Gain` as there are no Presence/Absence that could be compared. `NaN` are displayed as division by 0 occurs.
Could you check that: 
1. both models predicted actual distributions (maybe you can show us both outputs distributions)
2. that they were both predicted with the same CRS (coordinate reference system). Else BIOMOD function will struggle in comparing both distribution as coordinates will differ between projections.
Let us know if something is unclear.
Cheers,
Rémi

**Comment by chenyongpeng1** [comment]
Thank you very much!
 best wishes,chen
