### ISSUE TITLE
Independent Evaluation in BIOMOD2 and selection of Pseudo absences.

### ISSUE THREAD

**Issue by kjirsten-c** [biomodhub/biomod2#112]
Hi Maya and community,

I am adding some independent validation data (by splitting my dataset) and so will be using the three eval. arguments in the BIOMOD_FormattingData function. I have used NA values to represent background points (I do not have absences) and 1 to represent presence values (the user-identified strategy, I use point data instead of rasters). I have checked to be sure that no other columns contain NAs, however I get the following error message: 

> Pseudo absences used will be user defined ones !
      ! NAs have been automatically removed from Evaluation dataError in .BIOMOD_FormatingData.check.args(resp.name, resp.var, expl.var,  : 
  Evaluation response data must have both presences and absences

But the absences must be NA (which represents indeterminate background points) and here it seems the function has removed my NA values which were a part of the model format. 

Note that without the independent validation arguments, and instead using cross-validation, the model works fine and I do not get this error. Given that the independent data is just a subset of the main dataframe and is in the same structure, this seems like a bug, unless you have any ideas for a solution?

Thank you!
Kjirsten

**Comment by MayaGueguen** [comment]
Hello Kjirsten,

Thank you for reporting :pray: 
Here are some precisions that might not be clear in the documentation files : 

- here, your evaluation data is not really _independent_, as you split your dataset in 2. Note that, into the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, you can define with the `data.split.perc` and `nb.rep` arguments the splitting of your dataset into calibration and validation dataset, and this a certain number of times. `eval.` arguments within the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) are meant to give, as a supplement to this splitting phase at the modeling step, a completely different dataset that will be used only for predictions and evaluation of your built models.

- if you dispose of such independent evaluation data, as said above, it will be used only for predictions and evaluation of your built models, meaning that it will not deal with background points, as your occurence data (`eval.resp.var`) will only be used for calculating evaluation metrics. And to do so, it requires 0 and 1 values. Note that, even when using pseudo-absences with presence-only, these pseudo-absences points are considered as "absence points" for calculating evaluation metrics.
If you're not satisfied with such method, you can also use the [BIOMOD_PresenceOnly](https://biomodhub.github.io/biomod2/reference/BIOMOD_PresenceOnly.html) function after the modeling steps, which will compute 2 evaluation metrics more adequate for presence-only data.

Hope it helps,
Maya

**Comment by kjirsten-c** [comment]
Hi Maya, 

This solved the problem. Thanks again!

Kjirsten
