### ISSUE TITLE
modified the color in the maps using bm_PlotRangeSize function

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#113]
HI，biomod2 team：
   How I modified the color in the maps using _bm_PlotRangeSize_, the loss is white, which makes it impossible for me to see clearly。
  my code is following：
![image](https://user-images.githubusercontent.com/104480028/195547188-5702a8fa-16d7-477a-b3c6-684f5d2e6064.png)

```
CurrentProj_EM <- stack("apis.melifera/proj_Current/individual_projections/apis.melifera_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData.gri")

FutureProj_EMssp126_2050 <- stack("apis.mellifera/proj_2050_ssp126/individual_projections/apis.melifera_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData.gri")
myBiomodRangeSize_ssp126_2050 <- BIOMOD_RangeSize(proj.current = CurrentProj_EM, proj.future = FutureProj_EMssp126_2050)
myBiomodRangeSize_ssp126_2050$Compt.By.Models
gg_ssp126_2050 = bm_PlotRangeSize(bm.range = myBiomodRangeSize_ssp126_2050,
                                  do.count = TRUE,
                                  do.perc = TRUE,
                                  do.maps = TRUE,
                                  do.mean = TRUE,
                                  do.plot = TRUE,
                                  row.names = c("Species"))
```
looking forward to your reply！
Best wishes,chen

**Comment by MayaGueguen** [comment]
Hello Chen,

Thank you for posting :pray: 
The [bm_PlotRangeSize](https://biomodhub.github.io/biomod2/reference/bm_PlotRangeSize.html) function is not optimum, and trying to do a lot of things at once...
It is on our todo-list to try and make it more functional.
In the meantime, please notice that this plot is only representing the map contained into your `myBiomodRangeSize_ssp126_2050$Diff.By.Pixel` object. Hence, you can plot it directly, and change plot characteristics by yourself. Find below some examples : 
```
## Basic plot
plot(myBiomodRangeSize$Diff.By.Pixel)

## Basic plot changing colors
plot(myBiomodRangeSize$Diff.By.Pixel, col = c("brown", "goldenrod1", "grey", "chartreuse3"))

## Basic plot changing colors and labels
plot(myBiomodRangeSize$Diff.By.Pixel
     , col = c("brown", "goldenrod1", "grey", "chartreuse3")
     , legend.width = 1, legend.shrink = 0.75
     , axis.args = list(at = seq(-2, 1, 1), labels = c("Loss", "Stable1", "Stable0", "Gain")))
```
![image](https://user-images.githubusercontent.com/16795576/195570301-5aef21fb-2515-4f55-92c7-e5433519593d.png)

Hope it helps,
Maya

**Comment by chenyongpeng1** [comment]
Great！It help a lot！
Thank you for your time and help again！
