### ISSUE TITLE
ssues to run the updated biomod2 4.1

### ISSUE THREAD

**Issue by GuillaumeHD1** [biomodhub/biomod2#114]
Dear all
I hope my email finds you well.
Please, I am writing to request the Vignettes of the updated package biomod2 4.1.
Since this morning, I have tried to run my old script but am getting several errors.
Specifically, when I ran ## the individual models ----

**ProLau_models <-
  BIOMOD_Modeling(
    bm.format = ProLau_data,
    models = c("GLM", "GBM", "RF"),
    bm.options = ProLau_opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = 3,
    [modeling.id](http://modeling.id/) = 'demo1'
    )**

Error.....

**Evaluating Model stuff...
Model=Generalised Boosting Regression
2500 maximum different trees and  3  Fold Cross-Validation
> GBM modeling...Loaded gbm 2.1.8
CV: 1
CV: 2
CV: 3

Evaluating Model stuff...
Model=Breiman and Cutler's random forests for classification and regression
> RF modeling...Error in { : task 1 failed - "`...` must be empty.
x Problematic argument:
* call = error_call"**

I need your help to fix this issue.

Thanks

**Comment by rpatin** [comment]
Dear Guillaume,
Thank you for reporting !
Unfortunately, the previous vignette cannot be used with the new biomod2 version.
You can find the up-to-date vignette on the github website for biomod2 : https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html
Please, let us know if you still have problems running the vignette.
Rémi

**Comment by GuillaumeHD1** [comment]
Thank you dear rpatin,
I met the same error. Can you help me to fix my specific issue based on my code?

**Comment by GuillaumeHD1** [comment]
Dear rpatin,
- Yes I have tried the example of the vignette.
- First of all, I am running the model using the ensemble approach.
- I have imported all the data (occurrence and environmental layers).
- I have successfully formatted the data with pseudo absences:
ProLau_data <-
  BIOMOD_FormatingData( 
    resp.var = ProLau_occ['speciesname'],
    resp.xy = ProLau_occ[, c("Longitude","Latitude")],
    expl.var = bioclim_ZA_sub,
    resp.name = "speciesname",
    PA.nb.rep = 2,
    PA.nb.absences = 500,
    PA.strategy = 'random'
  )

- I have successfully defined individual models options using this code:
ProLau_opt <-
  BIOMOD_ModelingOptions(
    GLM = list(type = 'quadratic', interaction.level = 1),
    GBM = list(n.trees = 1000),
    RF = list(ntree = 500)
    )

- Now, the issues are when I wanted to run the individual models ----
ProLau_models <-
  BIOMOD_Modeling(
    bm.format = ProLau_data,
    models = c("GLM", "GBM", "RF"),
    bm.options = ProLau_opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = 3,
    modeling.id = 'demo1',
    do.full.models = FALSE
    )

Here are the errors I have met:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...

Creating suitable Workdir...

			! Weights where automatically defined for Ricinodendron.heudelotii_PA1 to rise a 0.5 prevalence !
			! Weights where automatically defined for Ricinodendron.heudelotii_PA2 to rise a 0.5 prevalence !


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= speciesname Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 3  environmental variables ( bio3 bio12 soil_sndppt_sd3_m )
Number of evaluation repetitions : 2
Models selected : GLM GBM RF 

Total number of model runs: 12 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=- Run :  Ricinodendron.heudelotii_PA1 


-=-=-=--=-=-=- speciesname _PA1_RUN1 

Model=GLM ( quadratic with order 1 interaction level )
	Stepwise procedure using AIC criteria
	> GLM modeling...
	Automatic formula generation...
	selected formula : speciesname  ~ bio12 + I(bio12^2) + bio3 + I(bio3^2) + 
    I(soil_sndppt_sd3_m^2) + soil_sndppt_sd3_m + bio12:soil_sndppt_sd3_m + 
    bio3:soil_sndppt_sd3_m
<environment: 0x000002421b7e5718>

	Evaluating Model stuff...
Model=Generalised Boosting Regression 
	 1000 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...
	Evaluating Model stuff...
Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...Error in { : task 1 failed - "`...` must be empty.
x Problematic argument:
* call = error_call"
In addition: Warning message:
executing %dopar% sequentially: no parallel backend registered 
> 


Thanks

**Comment by rpatin** [comment]
Dear Guillaume,
Could you also provide us with the output of:
1. `ProLau_data`
that will provide a summary of your data.

As well as:

2. `plot(ProLau_data)`

This will help identify whether the error comes from the data in itself or from the modeling afterward.
Thanks,
Rémi

**Comment by GuillaumeHD1** [comment]
Dear Rémi,
Hereby are the output of :
**1. ProLau_data**
> ProLau_data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data.PA -=-=-=-=-=-=-=-=-=-=-=-=-=
dir.name =  .
sp.name =  speciesname
	 188 presences,  0 true absences and  998 undefined points in dataset
	 3 explanatory variables
      bio3         bio12      soil_sndppt_sd3_m
 Min.   :574   Min.   : 624   Min.   : 38.00   
 1st Qu.:644   1st Qu.: 988   1st Qu.: 52.00   
 Median :675   Median :1048   Median : 59.00   
 Mean   :670   Mean   :1023   Mean   : 59.83   
 3rd Qu.:711   3rd Qu.:1082   3rd Qu.: 67.00   
 Max.   :744   Max.   :1272   Max.   :128.00   
 2 Pseudo Absences dataset available ( PA1 PA2 ) with  499 absences in each (true abs + pseudo abs)


**2. plot(ProLau_data)**
[Rplot.zip](https://github.com/biomodhub/biomod2/files/9808943/Rplot.zip)

**Comment by rpatin** [comment]
Dear Guillaume,
Thank you for the information.  Sorry I still do not understand the error you encounter so I will be asking more questions ...
The plot of the data show:
1. Only 1 presence instead of 188.
2. Far less than 500 pseudo-absences.
Not sure why the (2) would occur. However the (1) may happen if you provided presence point that all falls in the same grid cell. Are your presence points supposed to be distributed over all the map ? Or is it expected that they should be restricted to a very small area ?

Also, could you provide more information on the environmental layers that you use : 
- what are their resolution ?
- could you show a plot for the different layer ?

Additionally there is another issue that I do not understand:
- you ask for 500 pseudo-absences but only get 499 in each dataset ? Is it a discrepancy that you often see ?

Rémi

**Comment by GuillaumeHD1** [comment]
Dear Rémi,
Hereby are the dataframe:
> summary(ProLau_occ)
   Longitude        Latitude     Ricinodendron.heudelotii
 Min.   :1.959   Min.   :6.676   Min.   :1               
 1st Qu.:2.046   1st Qu.:6.964   1st Qu.:1               
 Median :2.490   Median :7.408   Median :1               
 Mean   :2.362   Mean   :7.773   Mean   :1               
 3rd Qu.:2.659   3rd Qu.:8.943   3rd Qu.:1               
 Max.   :2.705   Max.   :8.993   Max.   :1 

> head(ProLau_occ)
  Longitude Latitude Ricinodendron.heudelotii
1  2.044694 8.942472                        1
2  2.045111 8.943083                        1
3  2.045111 8.943222                        1
4  2.045028 8.943111                        1
5  2.045944 8.942917                        1
6  2.045111 8.943000                        1

The species has a restrictive distribution (in two climatic regions)

The environmental layers are corrects. Resolution : 30S

1. I would like to ask if my data format is correct.
2. I have already run the models with the old version of Biomod2 (with the same data). I got all the results without trouble.
3. I currently need to check some outputs but I am meeting the issues of the updated version.

**Comment by rpatin** [comment]
Dear Guillaume,
Thanks for sending the data, it was much easier to work on the issue.
I could not however reproduce the issue, maybe you are working with a slightly older version of `biomod2` that have been bugfixed since then.
- Could you send us the output of `sessionInfo()` on a R session on which you see the bug ? This will help us identify which version you are using.
- If you are not using the latest version, can you try again after upgrading to the newest version ? 
`devtools::install_github("biomodhub/biomod2")`

Rémi
