### ISSUE TITLE
extract by algorithm for ensemble model?

### ISSUE THREAD

**Issue by CatherineBuckland** [biomodhub/biomod2#115]
Hi Maya and biomod2 team, 
I have run the BIOMOD_Modeling using a range of algorithms, which I've then ensembled. But I'm also keen to run BIOMOD_EnsembleModeling by subset of algorithm to compare. 
I've seen on a previous thread that you can't use: models.chosen = 'RF', and that something was mentioned about using the get_built_models function? How do I use this and integrate it into the BIOMOD_EnsembleModeling function so that I can take a subset of the models produced from BIOMOD_Modeling and produce new ensembles by algorithm for comparison?
Many thanks for all your help. 
Catherine

**Comment by CatherineBuckland** [comment]
Hi Rémi, 
Many thanks for all that information and super quick reply - much appreciated!
I have successfully used your first option, using: em.by = c('algo')
When I go to then plug this into ensemble forecasting however, I have an error message at the end. 

> myBiomodEF_current_algo <- BIOMOD_EnsembleForecasting( 
+   myBiomodEM_current_algo, 
+   bm.proj = myBiomodProj_current,
+   binary.meth = 'TSS',
+   output.format = ".img")

-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=

Creating suitable Workdir...

	> Projecting TS.FINAL_EMcvByTSS_RF_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_RF_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_RF_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_RF_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_MAXENT.Phillips_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_MAXENT.Phillips_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_MAXENT.Phillips_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_MAXENT.Phillips_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_GBM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_GBM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_GBM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_GBM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_ANN_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_ANN_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_ANN_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_ANN_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_GLM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_GLM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_GLM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_GLM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_MARS_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_MARS_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_MARS_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_MARS_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_GAM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_GAM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_GAM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_GAM_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_CTA_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_CTA_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_CTA_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_CTA_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByTSS_SRE_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByTSS_SRE_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMcvByROC_SRE_mergedRun_mergedData ...
		Writing projection on hard drive...
	> Projecting TS.FINAL_EMwmeanByROC_SRE_mergedRun_mergedData ...Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'newdata' in selecting a method for function 'predict2': invalid layer names

Any advice on how I can get this to successfully end and write the files to hard drive would be much appreciated. 
Thanks again, 
Catherine

**Comment by rpatin** [comment]
Hi Catherine,
Luckily, I think I encountered and fixed the exact same bug yesterday. 
Can you try with the newest github version ?
Thanks,
Rémi

**Comment by CatherineBuckland** [comment]
Hi Rémi, 

Thanks for your reply and glad you found the same issue. 
Unfortunately I have tried with the latest github version, but I'm still getting the same error message:
> Projecting TS.FINAL_EMwmeanByROC_SRE_mergedRun_mergedData ...Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'newdata' in selecting a method for function 'predict2': invalid layer names

Please let me know if you have any other suggestions / thoughts on how to fix. 
Many thanks, Catherine

**Comment by rpatin** [comment]
Hi Catherine,
Thank you for the update and sorry it did not work.

I think I finally understand what is happening, you're trying to do  an ensemble model with weighted mean based on ROC for all your SRE models (among other models). Unfortunately, SRE cannot be used by the ensemble model weighted by ROC (AUC cannot be properly calculated with SRE models). Therefore the function tries to build an ensemble with no models and fails, thus preventing the modeling to finish. 

By chance, we were working on that this morning and just updated a bugfix for that. If you try with the updated `biomod2` version from github you should be able to run your code (I know I already promised that) without issues. The model in question will still fail but you may access the results from the other models.

Alternatively you could omit the SRE from your ensemble models, or use alternative metrics to select and weight your models (such as TSS instead of ROC).

Feel free to ask if you need additional information or encounter further problems!
Rémi
