### ISSUE TITLE
Checking variable contribution

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#116]
Hi all,

Is there anyother way to check the contribution of each variable, regardless of the model algorithm use, or get_variables_importance() is the only way? Asking because I have seen [studies](https://natureconservation.pensoft.net/articles.php?id=12235) with MaxEnt where they used the get_variables_importance() and a method using jackknife and the results are not quite the same. The study I checked, for instance, mentions the percent contribution and the permutation importance and I believe biomod2's get_variables_importance() refers to the latter. I just wonder if there is other another way to assess the variable contribution using this package, but if there isn't, there isn't :)

Thank you very much.

Luis

**Comment by luispedrosantiago** [comment]
Hi Rémi,
Thanks a lot for getting back to me.
So, do you think I could potentially, somehow, use the MaxEnt model files created by biomod2 on the MaxEnt software itself to conduct jacknife?

Thanks,
Luis

**Comment by rpatin** [comment]
Hi Luis,
Unfortunately we do not have much experience with the MaxEnt software so we do not know whether that would be possible or not.
Rémi
