### ISSUE TITLE
Error in if (ncol(moa) == 1) return(moa[, 1]) else return(moa) :    argument is of length zero

### ISSUE THREAD

**Issue by BErfanian** [biomodhub/biomod2#12]
Hi, 
Thanks for your exceptionally good package, 
When I want to use committee.averaginng in `BIOMOD_EnsembleModeling` and my `eval.metric` is `'ROC'`, I've got the following error: 
`Error in if (ncol(moa) == 1) return(moa[, 1]) else return(moa) : 
  argument is of length zero`

However, the code works for `prob.mean.weight = T` and `committee.averaging = F`.

Here is my code:
ProLau_models <- BIOMOD_Modeling(
  data = ProLau_data, #Data
  models = c("GLM", "GBM", "RF", "GAM",
    "MAXENT.Phillips"
    ), #Models
  models.options = ProLau_opt,
  NbRunEval = 10, #number of replication
  DataSplit = 70, #split for validation
  Prevalence = 0.5,
  models.eval.meth = c('TSS','ROC'),
  VarImport = 3,
  do.full.models = F,
  SaveObj = TRUE,
  modeling.id = paste(myRespName,"FinalModeling",sep=""))

ProLau_ensemble_models <- BIOMOD_EnsembleModeling(
  modeling.output = ProLau_models,
  em.by = 'all', #'PA_dataset+repet'
  eval.metric = c(#"TSS",
    "ROC"
                  ),
  eval.metric.quality.threshold = 0.7,#c(0.99,0.99),
  models.eval.meth = c("KAPPA", "TSS", "ROC"),
  prob.mean = FALSE,
  prob.cv = F,
  committee.averaging = T,
  prob.median = F,
  prob.mean.weight = F, 
  prob.mean.weight.decay ='proportional',
  VarImport = 0#3for real works)

Thanks for your help!

**Comment by DamienGeorges** [comment]
Thanks!
I think the issue here comes from the eval.metric.quality threshold. Is reducing it (even setting it to 0 for a try) make any amelioration?
