### ISSUE TITLE
 some questions on geographical range

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#120]
Hi Maya,
     My research scope is global, but I used biomod2 to predict that the Arctic and Greenland will appear in large numbers in the future, which seriously violates the ecological scope of my species. How should I deal with it? Or how can I set parameters to exclude the Arctic and Greenland?

I tried to set the geographical range, but this is not a complete map. Can you provide some valuable suggestions?
`myExplFuture_ssp245_2030 <- stack(c(ssp245_2030_bio_1,ssp245_2030_bio_3,ssp245_2030_bio_2 ,ssp245_2030_bio_8,ssp245_2030_bio_9,
                                    ssp245_2030_bio_12,ssp245_2030_bio_14,ssp245_2030_bio_15,ssp245_2030_bio_18,ssp245_2030_bio_19,elev))
**_e <- extent(x = c(-180, 180,-65, 75))_**
myExplFuture_ssp245_2030 <-crop(myExplFuture_ssp245_2030,e)
myExplFuture_ssp245_2030<-stack(myExplFuture_ssp245_2030)`

thank you very much ,yongpeng

**Comment by MayaGueguen** [comment]
Hello there,

If I understood well, you're modelling a species at the global scale, but you predict in the future this species within Artic and Greenland. And you feel that this is not correct ecologically for this species.

Here are some suggestions : 

1. _Maybe the modelisation is correct_... and the actual climatic niche of your species will indeed be situated in these areas in the future. If this is unlikely, maybe your set of variables is not representing correctly the actual conditions required by your species ?
2. _You're positive this is unlikely_ and here are some points you might work on, that depend mainly on how you define your modelling area and your absence points : 

- _You want to remove Artic and Greenland from your simulation map._
Here are some links to maps containing world countries ID :
https://public.opendatasoft.com/explore/dataset/world-administrative-boundaries/export/
https://www.igismap.com/download-world-shapefile-free-country-borders-continents/
https://hub.arcgis.com/datasets/esri::world-countries-generalized

- _You want to keep those areas, and you use real absence points :_ 
perhaps make sure you have absence points in these extrem areas

- _You want to keep those areas, and you use pseudo-absence points :_  
select pseudo-absences using the `disk` method within the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html), and defining a maximum distance (with the `PA.dist.max` argument) from presence points to sample randomly pseudo-absences


Hope it helps,
Maya
