### ISSUE TITLE
Speed up `BIOMOD_EnsembleForecasting()`

### ISSUE THREAD

**Issue by basille** [biomodhub/biomod2#122]
Following my earlier issue (#121), I'm now focusing on `BIOMOD_EnsembleForecasting()`, which also takes a lot of time. My call is rather simple:

```r
acps_biomod_futur_ensemble <- BIOMOD_EnsembleForecasting(
    bm.em = acps_biomod_ensemble,
    bm.proj = acps_biomod_futur,
    nb.cpu = 7    
)
```

where `acps_biomod_ensemble` is the outcome of `BIOMOD_EnsembleModeling()` on my previous `acps_biomod_models` object (from `BIOMOD_Modeling()`), and `acps_biomod_futur` is the result of `BIOMOD_Projection()` on a future raster.

I'm wondering whether this could be optimized, from a user perspective: are there arguments that would substantially speed up the process? In particular, I only see one CPU being used during the computation of the call, despite asking for 7 of them (and having 8 available on this computer) — basically the same pattern as for `BIOMOD_Modeling()` mentioned in the other issue. I see from [here](https://github.com/biomodhub/biomod2/issues/66#issuecomment-1148560821) that both functions should in effect apply the number of CPUs.

Thanks in advance for any suggestion!

---

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] biomod2_4.1-2

…
```

**Comment by rpatin** [comment]
Hi Mathieu,
Unfortunately there are not much that can be done from a user perspective.
The function uses the `nb.cpu` argument only when the user provide `new.env` argument, in which case the function requires projecting all the individual models (which is generally the limiting factor for this function). Here you give the function the projected individual model (`acps_biomod_futur`) and further parallelization have not been implemented yet.
We could imagine projecting ensemble models in parallel, but I cannot make promise on that feature.
Rémi

**Comment by basille** [comment]
OK, thanks @rpatin for this answer too. So to make sure I understand correctly, if I'm not necessarily interested in individual projections, I could bypass `BIOMOD_Projection()` (which does use `new.env`) and directly run `BIOMOD_EnsembleForecasting()` using `new.env`? That would actually run faster to get the Ensemble projection? (NB: Individual models are actually checked on the current environment, but I don't need individual projections on future environments)

I guess that would make sense, but I admit I started to be pretty lost in the actual `biomod2` process here…

**Comment by rpatin** [comment]
Indeed you could bypass `BIOMOD_Projection()`, although the results would be exactly the same in nature and in speed. `BIOMOD_EnsembleForecasting()` requires the projection of each individual models on `new.env` (to calculate the mean of your models projections for instance) so:
1. either you do `BIOMOD_Projection` yourself and give `BIOMOD_EnsembleForecasting()` the results of your projection.
2. or you give `BIOMOD_EnsembleForecasting` the arg `new.env` but then it will internally call `BIOMOD_Projection` with the same call that you would have done in option (1).
 
The only differences is that when running `BIOMOD_Projection` yourself you could access the projection of individual models (which you do not care here for future projections). But calculations will be the same in both cases. 
I hope the `biomod2` process for that part is clearer now. If not feel free to ask, it is easy to get lost ...

**Comment by basille** [comment]
Thanks @rpatin for the clarification. In short, both approaches would result in the same outcome, except for the clutter in my environment (and the fact that I can no longer control for individual projections). In terms of memory used (RAM), do you think that would change anything? I'd be keeping more objects with the first approach, but since they are created anyway using the second approach…

**Comment by basille** [comment]
Thanks for the quick answer. Running several algorithms at the scale of Europe does indeed use a lot of memory, but I think it is expected. I did not try to load objects directly from disk yet — I guess I'd need to look into `load_stored_object()`.

I'm closing the thread as my points have been answered.
