### ISSUE TITLE
level.plot command

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#123]
I am a university student in Oldenburg, Germany. At the moment I am studying species distribution and I am learning with the book 'Habitat suitability and distribution models: with applications in R'. They use the biomod2 package for R. They often use the 'level.plot' function. But with the biomod2 version I am using  now (4.1-2), my R tells me, that this function does not exist. Is there a newer Version of the 'level.plot' function and does it have another name? Or how can I use the 'level.plot' function? The Code i am using is this:

library(biomod2)
 
mammals_data <- read.csv("tabular/species/mammals_and_bioclim_table.csv", row.names=1)
head(mammals_data)

pred_BIOCLIM = sre(Response = mammals_data$VulpesVulpes, 
                   Explanatory = mammals_data[,c("bio3", "bio7", "bio11", "bio12")], 
                   NewData = mammals_data[,c("bio3", "bio7", "bio11", "bio12")], 
                   Quant = 0)

pred_BIOCLIM_025 = sre(Response = mammals_data$VulpesVulpes, 
                   Explanatory = mammals_data[,c("bio3", "bio7", "bio11", "bio12")], 
                   NewData = mammals_data[,c("bio3",  "bio7", "bio11", "bio12")], 
                   Quant = 0.025)

pred_BIOCLIM_05 = sre(Response = mammals_data$VulpesVulpes, 
                   Explanatory = mammals_data[,c("bio3",  "bio7", "bio11", "bio12")], 
                   NewData = mammals_data[,c("bio3",  "bio7", "bio11", "bio12")], 
                   Quant = 0.05)

par(mfrow=c(2,2))
level.plot(mammals_data$VulpesVulpes, 
           XY=mammals_data[,c("X_WGS84", "Y_WGS84")], 
           color.gradient = "grey", 
           cex=0.3,show.scale=F, 
           title="Original data")

level.plot(pred_BIOCLIM, 
           XY=mammals_data[,c("X_WGS84", "Y_WGS84")], 
           color.gradient = "grey", 
           cex=0.3,show.scale=F, 
           title="BIOCLIM 100%")

level.plot(pred_BIOCLIM_025, 
           XY=mammals_data[,c("X_WGS84", "Y_WGS84")], 
           color.gradient = "grey", 
           cex=0.3,show.scale=F, 
           title="BIOCLIM 97.5%")

level.plot(pred_BIOCLIM_05, 
           XY=mammals_data[,c("X_WGS84", "Y_WGS84")], 
           color.gradient = "grey", 
           cex=0.3,show.scale=F, 
           title="BIOCLIM 95%")
par(mfrow=c(1,1))

**Comment by MayaGueguen** [comment]
Hello Ben, 

Yes, there has been some changes when moving from 3.5-1 to 4.1-2.
Indeed, the `level.plot` function is not available anymore and has been passed to internal functions.
But you can find below an adaptation of your code example with the new version :)

```
library(biomod2)
library(raster)

# Load species occurrences (6 species available)
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)
head(DataSpecies)

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
myFiles <- paste0('external/bioclim/current/bio', c(3, 7, 11, 12), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

# Reclassify occurrences into raster format
myResp.v <- as.numeric(DataSpecies[, 'VulpesVulpes'])
myRespXY <- DataSpecies[which(myResp == 1), c('X_WGS84', 'Y_WGS84')]
myResp <- reclassify(subset(myExpl, 1, drop = TRUE), c(-Inf, Inf, 0))
myResp[cellFromXY(myResp, myRespXY)] <- 1

# Compute SRE models
pred_BIOCLIM = bm_SRE(resp.var = myResp,
                      expl.var = myExpl,
                      new.env = myExpl,
                      quant = 0)
pred_BIOCLIM_025 = bm_SRE(resp.var = myResp,
                      expl.var = myExpl,
                      new.env = myExpl,
                      quant = 0.025)
pred_BIOCLIM_05 = bm_SRE(resp.var = myResp,
                      expl.var = myExpl,
                      new.env = myExpl,
                      quant = 0.05)
pred_stack = stack(pred_BIOCLIM, pred_BIOCLIM_025, pred_BIOCLIM_05)
plot(pred_stack)
```

Hope it helps, and please do not hesitate if you encounter other mismatches you would like to enlight.
Maya
