### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = names_models)

### ISSUE THREAD

**Issue by lpittet92** [biomodhub/biomod2#125]
Hi,

I am getting always the same error while using BIOMOD_ensembleModeling(). Here is my code and the error message I get.

"#### Ensemble models
# Model ensemble models

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.9),
                                      var.import = 3,
                                      metric.eval = c('TSS', 'ROC','KAPPA'),
                                      prob.mean = TRUE,
                                      prob.median = FALSE,
                                      prob.cv = FALSE,
                                      prob.ci = FALSE,
                                      prob.ci.alpha = 0.05,
                                      committee.averaging = FALSE,
                                      prob.mean.weight = FALSE,
                                      #prob.mean.weight.decay = 'proportional'
                                      )"

Error: 
"-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
   > Evaluation & Weighting methods summary :
      TSS over 0.9

  > mergedAlgo_mergedRun_mergedData ensemble modeling
   ! Additional projection required for ensemble models merging several pseudo-absence dataset...
-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=
(...)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   > Mean of probabilities ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 

  |======================================================================| 100%
**Error in `colnames<-`(`*tmp*`, value = names_models) : 
  attempt to set 'colnames' on an object with less than two dimensions
Calls: BIOMOD_EnsembleModeling -> .transform_outputs_list.em -> colnames<-**
Execution halted"

I used the same code on Rstudio and it worked. Now I am running the code as a script on a compute cluster and I get this error. Am I missing a package ?

Thank you in advance for your help.

Cheers,

Loïc

**Comment by rpatin** [comment]
Hi Loïc,
Thank you for reporting :pray: 
I suspect the bug stems from the fact that current `biomod2` version does not support a call to `BIOMOD_EnsembleModeling` for only one ensemble model. We had prepared a bugfix in a development version that have not been released yet.
To solve your bug on the cluster you can thus:

1. Always ask for more than one ensemble model (you can later ignore the result for the second model if you are not interested by it): 

```
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
models.chosen = 'all',
em.by = 'all',
metric.select = c('TSS'),
metric.select.thresh = c(0.9),
var.import = 3,
metric.eval = c('TSS', 'ROC','KAPPA'),
prob.mean = TRUE,
prob.median = TRUE,
prob.cv = FALSE,
prob.ci = FALSE,
prob.ci.alpha = 0.05,
committee.averaging = FALSE,
prob.mean.weight = FALSE,
#prob.mean.weight.decay = 'proportional'
)"
```

2. Install the development version on the cluster: `devtools::install_github("biomodhub/biomod2", ref = "terraVersion")`. Feel free to let use know if you encounter bug with this version.


Also, if your code works on your personal computer (on Rstudio) but not on a computer cluster I would suspect that the version of `biomod2` installed is different between both machine. You can access the package version by running `sessionInfo()`. It may also be that you asked for more than one ensemble model on your personal computer and thus did not encounter the bug.
Sorry for all the inconvenience and feel free to let us know if that does not solve your issue. 
Cheers,
Rémi

**Comment by lpittet92** [comment]
Salut Rémi,

Well, I have checked the script on my personal computer and it is exactly the same. I also asked for the prob.mean only and the biomod2 version is also the same... The only thing that change is the R version (4.1.1 on the cluster where it is not working, 4.2.1 on my own computer). Do you think the R version may be the problem ?

I will try now again with prob.median = TRUE. 

Otherwise, I tried to install the dev tools version of biomod2 that you referred to but it is not working, here is the message error:

"Error in .BIOMOD_FormatingData.check.args(resp.name, resp.var, expl.var,  : 
  No Absences were given and no Pseudo-Absences were given or configured, at least one of those option is required.
Calls: BIOMOD_FormatingData -> .BIOMOD_FormatingData.check.args"

The code is however exactly the same as before.

Thank you for your quick help, the package is otherwise amazing :)

Cheers,

Loïc

**Comment by rpatin** [comment]
Salut Loïc,

- I do not think the R version may be the problem, this seems like an internal problem to `biomod2`. Also note that we are not always rigorous with `biomod2` version number so the version may differ slightly between your computer and the cluster, despite `sessionInfo()` showing the same number. Sorry for that. Although I do not see why it would cause a discrepancy between both settings.

- The error you encounter with the new version is linked with a new check that ensure that your data have both presence and absences or pseudo-absences. It is thus expected that you did not encounter it before, but I am surprised that your models were running before. Could you:
  1. share the code you used to call `BIOMOD_FormatingData()` with the development version.
  2. share output summary of `myBiomodData` (the output of `BIOMOD_FormatingData()`) and  `myBiomodModelOut` that you ran with the old version (and that were running without errors I suppose).
  
Cheers,
Rémi

**Comment by rpatin** [comment]
Hi Loïc,
Thank you for the update, and happy that your problem is solved!
The problem that you encountered when using the development version likely comes from the following lines:

```R
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)

myBiomodData

svg("myBiomodData.svg")
plot(myBiomodData)
dev.off()
```

That should be commented out. Indeed you try to define a `myBiomodData` but with only presence (no absences, no pseudo-absences), which cannot be used in a model, hence the new error. But as you do not use this object and you later define and use `myBiomodData.r` with random pseudo-absences the rest of your modelisation should work as well as before. 

Cheers,
Rémi
