### ISSUE TITLE
TSS binary transformation and TSS Filtered Transformation not working

### ISSUE THREAD

**Issue by janinepdasilva** [biomodhub/biomod2#128]
Hi all,

I've recently updated the biomod2 package and I'm using the BIOMOD_EnsembleForecasting() function but I cannot use  the metric.filter or metric binary argumetns because the following messages pop up:
Warning messages:
1: In .BIOMOD_EnsembleForecasting.check.args(bm.em, bm.proj, proj.name,  :
  TSS Binary Transformation were switched off because no corresponding evaluation method found
2: In .BIOMOD_EnsembleForecasting.check.args(bm.em, bm.proj, proj.name,  :
  TSS Filtered Transformation were switched off because no corresponding evaluation method found

These functions were working perflectly before the update, so I don't know what I am missing here.

Here's my complete code

myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    bm.options = myBiomodOption,
                                    models = c('GLM', 'GAM', 'RF', 'GBM'),
                                    nb.rep = 10, 
                                    data.split.perc = 70,
                                    var.import =  3,
                                    prevalence = 0.5,
                                    metric.eval = c("TSS", "ROC"), 
                                    save.output = TRUE,
                                    scale.models = TRUE,
                                    do.full.models = FALSE,
                                    modeling.id = paste(myRespName,"iberia_modeling", sep = ""))

myBiomodProj <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  new.env = proj_env,
  proj.name = 'current',
  models.chosen = 'all',
  metric.binary = 'TSS',
  metric.filter = 'TSS',
  compress = 'xz',
  build.clamping.mask = TRUE
  )

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = 0.7, # since some species auc are naturally low
                                      metric.eval = c('KAPPA', 'TSS', 'ROC'),
                                      prob.mean = TRUE,
                                      prob.median = TRUE,
                                      prob.cv = TRUE,
                                      prob.ci = F,
                                      #prob.ci.alpha = 0.05,
                                      #committee.averaging = TRUE,
                                      prob.mean.weight = TRUE,
                                      prob.mean.weight.decay = 'proportional',
                                      var.import = 3)

myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             bm.proj = myBiomodProj,
                                             #metric.filter = 'TSS',
                                             metric.binary = 'TSS')

Hope someone can help me.

Cheers

**Comment by rpatin** [comment]
Hi @janinepdasilva,
Thank you for reporting :pray: 
I just pushed a correction for the bug you encountered. Could you update to the github version and try again the ensemble forecasting ?

```
library(devtools)
devtools::install_github("biomodhub/biomod2")
```

Please let me know if that does not solve your issue.
Cheers,
Rémi

**Comment by janinepdasilva** [comment]
Hi @rpatin 
Thank you so much for fixing the bug. I was not able to test it because now I cannot run the BIOMOD_EnsembleModeling() function.  Yesterday it was working.
The following error pops up:
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c("ROC"),
                                      metric.select.thresh = 0.7,
                                      metric.eval = c('KAPPA', 'TSS', 'ROC'),
                                      prob.mean = TRUE,
                                      prob.median = F,
                                      prob.cv = TRUE,
                                      prob.ci = F,
                                      #prob.ci.alpha = 0.05,
                                      #committee.averaging = TRUE,
                                      prob.mean.weight = TRUE,
                                      prob.mean.weight.decay = 'proportional',
                                      var.import = 3)

> Error in .fun_testIfInherits(TRUE, "bm.model", bm.model, c("biomod2_model",  : 
  
bm.model must be a 'biomod2_model', 'nnet', 'rpart', 'fda', 'gam', 'glm', 'lm', 'gbm', 'mars' or 'randomForest' object

**Comment by rpatin** [comment]
Hi @janinepdasilva,
I think the error is occurring during calculations of variable importance but I have no clue as to why that would occur (and nothing changed around that recently as far as I know). Could you send me the object `myBiomodModelOut` so that I can explore the error further ?
Rémi

**Comment by janinepdasilva** [comment]
Hi @rpatin 

Thank you so much. I've managed to make it work, although i have no clue how I did it. If it comes up again, I'll send you the object.

Not directly related to the specific issue of this thread, but maybe you could help me. After running

BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
bm.proj = myBiomodProj,
metric.filter = 'TSS',
metric.binary = 'TSS')

I get the binary and filtered projections files from the ensemble model in the proj folder (e.g. proj_current/proj_current_MMAR_ensemble_TSSfilt.RData), however I have not been able to extract the prediction values to a data frame using get_predictions(). 
I was used to just load the RData file and then merge it to other data frames. In this case I think maybe I'm just misunderstanding something. Note that I'm working only with dataframes, so I need the predictions to be in that format so I can bind them to an ID column and then use them in GIS.

Thank you again

**Comment by rpatin** [comment]
Hi @janinepdasilva,
Great that it worked out then.
I clearly see your problem, it is already on our to-do list. But for now it is not possible to get binary (or filtered) transformation directly with `get_predictions`, you indeed have to load them from the disk.
When you load the .RData, is it in a `data.frame` format then ?
Rémi

**Comment by janinepdasilva** [comment]
Hi @rpatin 

Well, it would be perfect if it was a data.frame. When I load the .RData, it is Large list format. A huge list in my case actually. I can't figure out how to sort that list to get the columns with predicitons that I can then directly merge to my other ID data.frame, as I've been doing until now. I can send you the .RData file maybe? I just don't know how because I'm new around here :)

Cheers

**Comment by janinepdasilva** [comment]
Just to be clear, previously the the update I got a matrix when I loaded de .RData file, with the exact 3 columns that I needed (i.e. EMmean, EMcv and EMwmean) 💯

**Comment by rpatin** [comment]
Hi @janinepdasilva,
Indeed it would be easier to help your if I can see the object. You should be able to drag a file in the message zone I think. Otherwise you can send it by e-mail (remi.patin@univ-grenoble-alpes.fr). I think there should be a function within the package to transform nicely the object into a data.frame.
Rémi

**Comment by janinepdasilva** [comment]
It seems that the file type is not supported, so I'll send it by e-mail.
Thank you so much for all you help
Janine

**Comment by rpatin** [comment]
Hi Janine,
Thank you for the mail.
Actually the object you sent is a matrix and you should be able to convert it to a `data.frame` with `as.data.frame(proj_current_MMAR_ensemble_TSSbin)`. Note that in the object you sent there are no column for `EMcv`, although it is likely because binary projection cannot be calculated for `EMcv` models that only measure uncertainty in projection among invidual models.
Feel free to let us know if something is unclear or if you encounter further problem with importing object resulting from binary transformation.
Rémi

**Comment by janinepdasilva** [comment]
I am really sorry, I sent you the binary calculation instead of the filtered calculation that is what's actually causing the problem. I will send the right file.

**Comment by rpatin** [comment]
Thanks you for the new file.

There is indeed a bug when exporting filtered calculations with `BIOMOD_EnsembleForecasting()` and I fear the object you have generated will not be easily converted and you will have to re-run the forecasting.

Hopefully this bug have already been corrected but that was done on the unreleased development branch (among with many other changes).  You can install it with the following command: `devtools::install_github("biomodhub/biomod2", ref = "terra_update")`.

_Please not that you may have to re-run `BIOMOD_EnsembleModeling` due to the changes implemented in this branch_

I hope this will solve your issue and if not, please let us know.
Cheers,
Rémi

**Comment by janinepdasilva** [comment]
Hi @rpatin 
Everything seems to be working now.
Thank you so much
Cheers
