### ISSUE TITLE
BIOMOD_Projection error

### ISSUE THREAD

**Issue by willright28** [biomodhub/biomod2#129]
Hi all,

I Have an issue with using the function BIOMOD_Projection, my package version is 3.5.1.
The error message said "Error in x@layers[[subset]] : subscript out of bounds". My variable contains 5 continuous factors and 1 categorical factor(0/1), so I checked the order or names in both the modeling and project steps but cannot find a mismatch. 
Please let me attach the material I used and help me find any solutions, thanks in advance!

[project_error.zip](https://github.com/biomodhub/biomod2/files/9970119/project_error.zip)

**Comment by rpatin** [comment]
Hi @willright28,
Thank you for reporting :pray:
Unfortunately your bugs concern the old version of `biomod2` so I will be of limited help if you keep working with it. There is indeed a bug with the clamping mask in that version. 
- If you want to continue working with version 3.5.1 then I suggest that you do not use clamping mask:
```
myBiomodProj <- BIOMOD_Projection(
  modeling.output = myBiomodModelOut,
  new.env = myExpl_proj,
  proj.name = 'current', 
  selected.models = 'all', 
  binary.meth = 'TSS', 
  compress = 'gzip', 
  build.clamping.mask = FALSE, 
  output.format = '.grd',
  do.stack=T)
```

_(Please note that argument name is `build.clampling.mask` and not `clamping.mask`)_

- Else you can also start using the new version of `biomod2` by installing either the CRAN release (`install.packages('biomod2')`)  or the github release (`devtools::install_github('biomodhub/biomod2')`). You can find guidelines here: https://biomodhub.github.io/biomod2/index.html and we will then be able to help you here and fix the bugs you may encounter.

Cheers,
Rémi

**Comment by willright28** [comment]
Hi @rpatin ，
Many thanks for your kind and quick answer! It's solved my problem and I am about to try the new version.

Thanks!🙏
