### ISSUE TITLE
Estimation of memory required

### ISSUE THREAD

**Issue by lpittet92** [biomodhub/biomod2#131]
Hi,

I woud like to know if there is a way to estimate the memory required ? I am using 7 raster layers with a very high resolution and trying to compute 64 models. 

My analysis keep crashing when doing single model projections. The issue seems to be related to the memory available ( I asked for 1 TB, 16 cpu).

Thank you in advance,

Loïc

**Comment by Farewe** [comment]
Hello there, 

Loïc, there was a function in the raster package to test if a raster can be processed in memory: `canProcessInMemory()`. Note that in terra (the "second" version of raster in R), it may have changed and you will have to check by yourself how it is done now.
Normally this function is only for internal purposes, but applying it on your raster can help you see if the raster as a whole can be processed on your computer memory. If it cannot be processed in memory, then the raster will do the operations by splitting them down into multiple operations, reading/writing portions of your raster on temporary files on the hard drive. 

It can lead to issues if, for example, your hard drive is full (a 1Tb drive may not be enough if a lot of stuff is already saved on it, or if your rasters have a very fine resolution), or if you have permission issues on the temporary files. Sometimes when R crashes, the temporary files of raster are not deleted and it can rapidly fill your hard drive. 

In raster, you can check the temporary directory with `raster::rasterOptions()$tmpdir`. Inspect it (and the other folders with similar names), and if you see lots of files you should probably delete them to free some drive space. Again, I do not know how this works in the package terra, so you would have to check how Robert Hijmans changed it in this new version.

In raster, you can also change the temporary directory by setting it with 
`rasterOptions(tmpdir="path") `

This way, you can point to an external hard drive of larger capacity.

A few notes:
 - a SSD-type drive is far better than a HDD-type drive in terms of performance. Using a HDD will slow down the process by a hugher factors (several hundreds)
 - if you use an external drive, you should use a fast one, i.e. at least usb 3/3.1/3.2. You have to consider all aspects of how the data is processed in your computer: RAM speed, transfer speed, read speed on the drive that has the data, read/write speed on the drive that has the temporary folder, write speed on the drive that will host the final file.
 - if you always run into a crash when you try your projection, you should split it into smaller units until you manage to run it once. Then progressively increase the complexity of your run until you see where it fails. Monitor your resources as Maia said when it fails: memory, hard drive, etc.  When you know the problem, try to find a solution, either hardware (upgrade - but be careful, maybe your data requirements are beyond computing capacities at reasonable prices, in which case it would be better to run it on a cluster if you can have access to one) or by adapting your protocol (coarsen resolution, reduce number of runs, project only one model, split the work into smaller tasks and merge them on your own later, cut your raster into smaller units and project each one of them separately then merge them later, etc.)


Cheers
Boris

**Comment by lpittet92** [comment]
H, 

You guys are amazing, always answering so fast. I am already running my analyses on a cluster. I have managed to build single and ensemble models, this is not the problem. I think my only problem is that I asked for 1 TB and this is not enough. I will try to ask for 1,5 TB and see if it works. 

Here is the error message I get:

"	> Projecting S.alpina_PA4_RUN2_GBM ...
	> Projecting S.alpina_PA4_RUN3_GBM ...
	> Projecting S.alpina_PA4_Full_GBM ...
	> Projecting S.alpina_PA4_RUN1_GBM ...Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 306152634
Calls: BIOMOD_PresenceOnly ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>
In addition: Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 1, 7, 9, 13 did not deliver results, all values of the jobs will be affected
Execution halted
============ Job Information ===================================================
Submitted: 2022-11-11T09:33:24
Started: 2022-11-11T10:00:04
Ended: 2022-11-12T05:30:50
Elapsed: 1171 min, Limit: 2880 min, Difference: 1709 min
CPUs: 16, Nodes: 1
============= ProfiT-HPC =======================================================
To generate the ProfiT-HPC text report, run the following command
profit-hpc 13972622
================================================================================
slurmstepd: error: Detected 4 oom-kill event(s) in StepId=13972622.batch. Some of your processes may have been killed by the cgroup out-of-memory handler."

So it is at the very end of the Projections, which probably means that 1,5 TB will then be enough !

Best regards,

Loïc

**Comment by MayaGueguen** [comment]
Hello Loïc,

Thank you for you feedback :pray: always appreciated !

It seems however that you have an error coming out when projecting your first GBM model, coming from the call to the `BIOMOD_PresenceOnly` function : 
```
> Projecting S.alpina_PA4_RUN1_GBM ...
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : 
arguments imply differing number of rows: 0, 306152634
Calls: BIOMOD_PresenceOnly ... as.data.frame -> as.data.frame.list -> do.call ->
```
Could you please send me your code, and ideally the data used to call this particular function so I can try and explore replicate the issue ?

Thanks in advance
Maya

**Comment by lpittet92** [comment]
[Biomod2_S_alpina_R.txt](https://github.com/biomodhub/biomod2/files/10002139/Biomod2_S_alpina_R.txt)

Hi,

Here is the whole code I am using. For the data it is probably a bit more difficult. Don't you think that the error comes in actual fact from a memory issue as suggested by the cluster itself:
`in StepId=13972622.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.`

I ran the exact same script with low resolution layers and it worked perfectly.

Loïc

**Comment by MayaGueguen** [comment]
Thank you for the code :pray: 

It seems to me that `BIOMOD_PresenceOnly` is causing an error, causing then the cluster to crash at some point.
As I'm more able to help you fix a biomod2 issue than an issue coming from your cluster that I do not have access to, I'd like to check first the potential biomod2 issue :) 

If you could send me the `.RData` objects corresponding to your `myBiomodModelOut` (the `S.alpina/S.alpina.1xxxxxxxx4.models.out` object in that case), `myBiomodEM` and `myExpl` objects, it would be fantastic.



Concerning the load of a `BIOMOD.models.out` object, you can use the `load` function, but then the object will have a different name within your R environment (here most likely `S.alpina.1xxxxxxxx4`)...
So the right way in your case to do it would be : 
```
myBiomodModelOut <- get(load("S.alpina/S.alpina.1xxxxxxxx4.models.out"))
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE)
```


Maya

**Comment by lpittet92** [comment]
Hi,

Could you please give me an email address so that I can share a drive with you with my data ?

Thanks 

Loïc

**Comment by MayaGueguen** [comment]
Hello Loïc,

Thank you for your code and data :pray: 
I ran the following extract of code to try and reproduce your error : 
```
myBiomodModelOut = get(load("S.alpina/S.alpina.1668159324.models.out"))
myBiomodEM = get(load("S.alpina/S.alpina.1668159324.ensemble.models.out"))

bio1c <- raster('../current/bio1lzw_CHELSA__35a-ts-mean.tiff')
bio2c <- raster('../current/bio2lzw_CHELSA__35a-ts-mean.tiff')
bio3c <- raster('../current/bio3lzw_CHELSA__35a-ts-mean.tiff')
bio14c <- raster('../current/bio14lzw_CHELSA__35a-ts-mean.tiff')
ext <- extent(2700000, 6100000, 1900000, 3200000)
bio1cc <- crop(bio1c, ext)
bio2cc <- crop(bio2c, ext)
bio3cc <- crop(bio3c, ext)
bio14cc <- crop(bio14c, ext)
myExpl <-raster::stack(bio1cc, bio2cc, bio3cc, bio14cc)


myBiomodPObd <- BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut
                 , bm.em = myBiomodEM, bg.env = getValues(myExpl))
```

Hence, mea culpa, it is indeed running fine, and there is no error coming from the [BIOMOD_PresenceOnly](https://biomodhub.github.io/biomod2/reference/BIOMOD_PresenceOnly.html) function.
My computer has 8 cores, and 64Go of RAM memory. It ran (_well, still is running, did 43 projections over 64 in like 15 hours_) on 1 core taking around 30Go of the memory. So theoretically, if you are really asking for 16 cores, you should need around 16 * 30 = 480 Go of memory to run 16 projections at the same time.

But here are some questions : 

- I'm a bit surprised that you can have access to 1To of RAM memory on 16 cores, even on a cluster. Are you positive it is really RAM and physical memory space your asking for ? or is it really the amount you are given ?
- in your message error, there is also :
```
 In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 1, 7, 9, 13 did not deliver results, all values of the jobs will be affected
```
Where are you using `mclapply` ? As you already asked for `nb.cpu = 16` when calling the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, if you are adding a supplementary parallelisation over through the `mclapply` function, that might be the reason why you are exceeding the resources you asked for.


Finally, as I said, it is running on my computer of 8 cores and 64Go RAM memory. Without parallelisation, indeed, but still in a reasonable amount of time. You might consider simply reducing the number of cores over which you parallelise your code, which would allow the memory not to be saturated.


Hope it helps !
Maya

**Comment by lpittet92** [comment]
Hi Maya,


Thank you for your feedback. Well I have to admit that I have no clue what I asked for... I never learned anything about computers and I just tried things...


Maybe you can help me one more time with this issue 😃


Here is the script I am running:


#SBATCH -o Biomod2_S_alpina.txt
#SBATCH -p fat+
#SBATCH --mem=1TB
#SBATCH -c 16
#SBATCH -t 48:00:00
#SBATCH -C scratch

module load r/4.1.1
module load gdal/3.4.1
module load cmake/3.21.4

Rscript Biomod2_S_alpina.R


And the option we can choose are here: https://docs.gwdg.de/doku.php?id=en:services:application_services:high_performance_computing:running_jobs_slurm


I am aware that I am basically asking you to do it for me... but I have no idea what options to choose or define and you will probably get it in 5 minutes...


Thanks again


Msc. Loïc Pittet

University of Goettingen
Albrecht-von-Haller Institute for Plant Sciences
Department of Systematic Botany
Untere Karspuele 2
37073 Goettingen
Germany
________________________________
De : MayaGueguen ***@***.***>
Envoyé : mercredi 16 novembre 2022 09:38:59
À : biomodhub/biomod2
Cc : Pittet, Loic; Author
Objet : Re: [biomodhub/biomod2] Estimation of memory required (Issue #131)


Hello Loïc,

Thank you for your code and data 🙏
I ran the following extract of code to try and reproduce your error :

myBiomodModelOut = get(load("S.alpina/S.alpina.1668159324.models.out"))

myBiomodEM = get(load("S.alpina/S.alpina.1668159324.ensemble.models.out"))



bio1c <- raster('../current/bio1lzw_CHELSA__35a-ts-mean.tiff')

bio2c <- raster('../current/bio2lzw_CHELSA__35a-ts-mean.tiff')

bio3c <- raster('../current/bio3lzw_CHELSA__35a-ts-mean.tiff')

bio14c <- raster('../current/bio14lzw_CHELSA__35a-ts-mean.tiff')

ext <- extent(2700000, 6100000, 1900000, 3200000)

bio1cc <- crop(bio1c, ext)

bio2cc <- crop(bio2c, ext)

bio3cc <- crop(bio3c, ext)

bio14cc <- crop(bio14c, ext)

myExpl <-raster::stack(bio1cc, bio2cc, bio3cc, bio14cc)





myBiomodPObd <- BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut

                 , bm.em = myBiomodEM, bg.env = getValues(myExpl))



Hence, mea culpa, it is indeed running fine, and there is no error coming from the BIOMOD_PresenceOnly<https://biomodhub.github.io/biomod2/reference/BIOMOD_PresenceOnly.html> function.
My computer has 8 cores, and 64Go of RAM memory. It ran (well, still is running, did 43 projections over 64 in like 15 hours) on 1 core taking around 30Go of the memory. So theoretically, if you are really asking for 16 cores, you should need around 16 * 30 = 480 Go of memory to run 16 projections at the same time.

But here are some questions :

  *   I'm a bit surprised that you can have access to 1To of RAM memory on 16 cores, even on a cluster. Are you positive it is really RAM and physical memory space your asking for ? or is it really the amount you are given ?
  *   in your message error, there is also :

 In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :

  scheduled cores 1, 7, 9, 13 did not deliver results, all values of the jobs will be affected



Where are you using mclapply ? As you already asked for nb.cpu = 16 when calling the BIOMOD_Modeling<https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html> function, if you are adding a supplementary parallelisation over through the mclapply function, that might be the reason why you are exceeding the resources you asked for.

Finally, as I said, it is running on my computer of 8 cores and 64Go RAM memory. Without parallelisation, indeed, but still in a reasonable amount of time. You might consider simply reducing the number of cores over which you parallelise your code, which would allow the memory not to be saturated.

Hope it helps !
Maya

**Comment by MayaGueguen** [comment]
Huuum I'm not a specialist of this cluster but maybe you can try like that, if you want to keep with a parallelised code version : 
```
#SBATCH -o Biomod2_S_alpina.txt
#SBATCH -p fat
#SBATCH -t 48:00:00
#SBATCH -C scratch
```
But you should consider lowering the `nb.cpu` parameter within your biomod2 functions not to have too many projections running at the same time.

Otherwise, I guess you could go for without internal parallelisation (setting `nb.cpu = 1`) : 
```
#SBATCH -o Biomod2_S_alpina.txt
#SBATCH -p medium
#SBATCH -t 48:00:00
#SBATCH -C scratch
```

But again, I might be missing some understanding here ...

Maya

**Comment by MayaGueguen** [comment]
Hello,

I did let it run, but you did not provide me with all your environmental variables, so it crashes because of that at some point...

Maya
