### ISSUE TITLE
ensemble model about binary

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#134]
Hello, I cannot export binary img output results when making ensemble model predictions. My results are continuous, but I can run well with the original version.

This is the result of using the new version of biomod package:

![image](https://user-images.githubusercontent.com/104480028/202121574-6153d1e5-4dab-4028-aa57-46169e84d959.png)

This is my original result:
![image](https://user-images.githubusercontent.com/104480028/202121770-53e6d03e-21c6-4fc0-9de1-bdcacad43a8a.png)
Thank you so much
cheer,chen

**Comment by chenyongpeng1** [comment]
So,the new version of biomod package can not reported the Ensemble TSSbin?
and my Code can be listed as follws.
```
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.r,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    models = c('GLM', 'GBM',  'CTA', 'ANN', 'SRE',  'RF', 'MAXENT.Phillips', 'MAXENT.Phillips.2' ),
                                    nb.rep = 2,
                                    data.split.perc = 80,
                                    # data.split.table = myBiomodCV,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC'),
                                    nb.cpu = 8,
                                    do.full.models = FALSE,
                                    seed.val = 123)

# Model ensemble models
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      #em.by = "algo",
                                      # models.chosen = c('GuloGulo_PA1_RUN1_GLM','GuloGulo_PA1_RUN1_RF','GuloGulo_PA1_RUN1_GBM'),
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.7),
                                      var.import = 3,
                                      metric.eval = c('TSS', 'ROC'),
                                      prob.mean = F,
                                      prob.median = F,
                                      prob.cv = TRUE,
                                      prob.ci = F,
                                  
                                      #prob.ci.alpha = 0.05,
                                      committee.averaging = TRUE,
                                      prob.mean.weight = TRUE)
                                      #prob.mean.weight.decay = 'proportional')

myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'TSS',
                                  #metric.filter = 'all',
                                  output.format = ".img",
                                  binary=TRUE,
                                  build.clamping.mask = F)
myBiomodProj
#plot(myBiomodProj)

# Project ensemble models (from single projections)
myBiomodEMProj <-  BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             bm.proj = myBiomodProj,
                                             output.format = ".img",
                                             models.chosen = 'all',
                                             metric.binary = 'TSS',
                                             binary=TRUE)
                                            # metric.filter = 'all',


```

Looking fowaid to your reply,Thanks a lot!

cheers,chen

**Comment by rpatin** [comment]
Hi Chen,
Thank you for reporting :pray:
Here are a few answers and questions:
- Could you tell us which version of `biomod2` are you using ? You can get it with `packageVersion('biomod2)`
- There have been no major changes about the behaviour of `BIOMOD_EnsembleForecasting` in the recent update of `biomod2` and on my end the last two version have similar behaviour.
- However note that there is an argument `do.stack` that controls whether projection (and among them binary projection) should be stacked and saved together in your folder `proj_current` or saved separately in your folder `proj_current/individual_projections`. 
  - When you set `do.stack = TRUE` the projection should only be saved in  `proj_current`  (and you should find your binary projection in the folder, stacked alltogether). 
  - Alternatively if you want to have individual binary projection in the `proj_current/individual_projections` folder you can set `do.stack = FALSE`.
- Additionally it may happen that your stacked projection would require too much RAM, then the package will automatically switched to `do.stack = FALSE`

_I did however note that when setting `do.stack = TRUE` the function still save individual ensemble model projection in the folder `proj_current/individual_projections` although it should only save them as stacked projection in `proj_current`. We will work on that in the future_

Cheers, 
Rémi

**Comment by chenyongpeng1** [comment]
Hi,Rémi,
  My version of biomod2 is 4.1.2,and I tried to use 4.1.3, it could not esist the binary model results.
Now，With your help, I have run out the tssbin results of the ENSEMBLE model by using do. Stack=T, thank you for your help

![image](https://user-images.githubusercontent.com/104480028/202170606-fbef6330-687c-4486-be97-3895352f0813.png)

Cheers，chen
