### ISSUE TITLE
Cannot get binary map of ensemble model

### ISSUE THREAD

**Issue by conanyao** [biomodhub/biomod2#135]
Hi,

I used the old version of biomod2 and I can get binary map of ensemble model by setting the binary metric. But in version 4.1-2, I got an warning 
_"Warning message:
In .BIOMOD_EnsembleForecasting.check.args(bm.em, bm.proj, proj.name,  :
  TSS Binary Transformation were switched off because no corresponding evaluation method found"_. And I only got 'xxx_ensemble.grd' and 'xxx_ensemble.gri' files.

My codes are below:

    BiomodModelOut <- BIOMOD_Modeling(bm.format = BiomodData,
                                      models = c('GLM', 'GBM', 'RF', 'MAXENT.Phillips'),
                                      bm.options = ModOptions,
                                      data.split.table = DataSplitTable,
                                      nb.rep = 2,
                                      var.import = 2, 
                                      metric.eval = c('TSS', 'ROC'),
                                      weights = NULL,
                                      save.output = TRUE,
                                      scale.models = TRUE,  
                                      do.full.models = FALSE,
                                      nb.cpu = 2,
                                      modeling.id = s_list[i])

    proj_current <- BIOMOD_Projection(bm.mod = BiomodModelOut,
                                      models.chosen = 'all',
                                      new.env = envars,
                                      new.env.xy = NULL,
                                      proj.name = paste('current', s_list[i], sep = '_'),
                                      metric.binary = c('TSS', 'ROC'),
                                      metric.filter = NULL,
                                      build.clamping.mask = T,
                                      nb.cpu = 2,
                                      compress = 'xz')

    EnsMod <- BIOMOD_EnsembleModeling(bm.mod = BiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS', 'ROC'),
                                      metric.select.thresh = c(0.7, 0.8),
                                      metric.eval = c('KAPPA','TSS', 'ROC'),
                                      var.import = 2,
                                      prob.mean = F, 
                                      prob.median = F, 
                                      committee.averaging = F,
                                      prob.mean.weight = TRUE,  
                                      prob.mean.weight.decay = 'proportional',
                                      prob.cv = TRUE, 
                                      prob.ci = TRUE,  
                                      prob.ci.alpha = 0.05)

    ensemble_proj_current <- BIOMOD_EnsembleForecasting(bm.em = EnsMod,
                                                        bm.proj = proj_current,
                                                        metric.binary = "TSS", 
                                                        proj.name = paste('ensemble', s_list[i], sep = '_'),
                                                        models.chosen = "all",
                                                        metric.filter = NULL)

Has it happened to anyone else? And how did you solve it?

Many thanks in advance,

Muyao

**Comment by conanyao** [comment]
Hi Rémi,

Thank you for the reply. I used 'GuloGulo' data which is in the system file to test my codes and got the same error with the Stable version (4.1-2). I will let you know if the error disappear in the development version.

Many thanks,
Muyao

**Comment by chenyongpeng1** [comment]
hi，I encountered the same problem. There is also no binary model in my model.
Warning message:
In .BIOMOD_EnsembleForecasting.check.args(bm.em, bm.proj, proj.name,  :
  TSS Binary Transformation were switched off because no corresponding evaluation method found

**Comment by chenyongpeng1** [comment]
> Building clamping mask
Error in h(simpleError(msg, call)) : 
  在为'bm_BinaryTransformation'函数选择方法时评估'data'参数出了错: invalid layer names 
In addition: Warning message:
In .local(x, ...) : invalid layer names omitted

**Comment by rpatin** [comment]
Hi Muyao,
Even with GuloGulo data and the stable version I did not manage to reproduce the issue.
Could you share the full code you used with GuloGulo data: from when you load GuloGulo data to when you project the ensemble model ? That way I may be able to understand whether the error stems from the package or the function call.
Thanks in advance,
Rémi

**Comment by rpatin** [comment]
Hi Chen,
It seems your error is slightly different, you have an error about `invalid layer names` that Muyao is not encountering. Could you please open a separate issue and share the code you used that generated the error ? (From loading the data to calling `BIOMOD_EnsembleForecasting`)
Thanks in advance
Rémi

**Comment by conanyao** [comment]
Hi Rémi,

I rerun the codes with the stable version, the warning did appear but I still cannot find binary files. I paste the codes for 'GuloGulo'. 

_# Load species occurrences (6 species available)
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)
head(DataSpecies)
# Select the name of the studied species
myRespName <- 'GuloGulo'
# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])
# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]
# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12) 
myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

# Format Data with true absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)
# Create default modeling options
myBiomodOptions <- BIOMOD_ModelingOptions()
# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id = 'AllModels',
                                    models = c('RF', 'GLM'),
                                    bm.options = myBiomodOptions,
                                    nb.rep = 2,
                                    data.split.perc = 80,
                                    metric.eval = c('TSS','ROC'),
                                    var.import = 3,
                                    do.full.models = FALSE,
                                    seed.val = 42)
# Project single models
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE)

# Model ensemble models
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.7),
                                      metric.eval = c('TSS', 'ROC'),
                                      var.import = 3,
                                      prob.mean = TRUE,
                                      prob.median = FALSE,
                                      prob.cv = FALSE,
                                      prob.ci = FALSE,
                                      prob.ci.alpha = 0.05,
                                      committee.averaging = TRUE,
                                      prob.mean.weight = FALSE,
                                      prob.mean.weight.decay = 'proportional',
                                      seed.val = 42)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')_

Another thing I would like to mention is I tried to use the development version of biomod2, but I cannot import 'myFile' at the beginning. When I removed biomod2 (development version) and install it again by using install.packages("biomod2", dependencies = TRUE), I can get the binary files.  But if I quit R studio and run the codes in a new session. I still cannot have the binary files. That's weird. 

Many thanks in advance,

Muyao

**Comment by rpatin** [comment]
Hi Muyao,

First, with the development version of `biomod2` (v.4.2-1 available on github) you cannot import the files for GuloGulo as you were doing before. We have changed data storage for a more standard procedure. The new code to load the data would be as follow:
```
library(biomod2)
library(terra)

# Load species occurrences (6 species available)
data("DataSpecies")
head(DataSpecies)

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
data("bioclim_current")
myExpl <- rast(bioclim_current)
```

Then, back to your issue. First I will try to summarize what you've been doing. Please correct me if I misunderstood something.
1. When you removed `biomod2` development version and installed the package from CRAN (with `install.packages`):
  - you ran the code and _did not_ get any warning (_I am not sure about the warnings_)
  - you found the binary projection under folder `GuloGulo/proj_CurrentEM/`
2. Then you quit Rstudio and open it again:
  - you run the same code and _did_ get warnings (_I am not sure about the warnings_)
  - you cannot find the binary projection
 
On my computer, your code combined with GuloGulo data is always working, so I suspect there may be an issue of library version in your computer. 

Could you:
1. Open Rstudio
2. Re-install biomod2 : `remove.packages('biomod2'); install.packages('biomod2')
3. Confirm that in this session the code above is working without warnings and you _can find_ the binary projections
4. Tell me the results of `find.package("biomod2")` as well as `sessionInfo()`
5. Quit Rstudio and re-open it
6. Confirm that in such situation the code is working with warnings and you _cannot find_ the binary projections
7. Tell me the results of `find.package("biomod2")` as well as `sessionInfo()`

Thanks in advance and sorry for the inconvenience,
Cheers,
Rémi

**Comment by conanyao** [comment]
Hi Rémi,
I followed your steps, the first run I got as below:
_> find.package("biomod2")
[1] "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/biomod2"
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] biomod2_4.1-2 raster_3.6-3  sp_1.5-1     

loaded via a namespace (and not attached):
 [1] gbm_2.1.8.1            tidyselect_1.2.0       terra_1.6-41           reshape2_1.4.4        
 [5] splines_4.1.2          lattice_0.20-45        colorspace_2.0-3       vctrs_0.5.1           
 [9] generics_0.1.3         mgcv_1.8-41            utf8_1.2.2             survival_3.4-0        
[13] rlang_1.0.6            pillar_1.8.1           withr_2.5.0            glue_1.6.2            
[17] DBI_1.1.3              plotmo_3.6.2           foreach_1.5.2          lifecycle_1.0.3       
[21] plyr_1.8.8             stringr_1.4.1          mda_0.5-3              munsell_0.5.0         
[25] gtable_0.3.1           codetools_0.2-18       maxnet_0.1.4           class_7.3-20          
[29] fansi_1.0.3            Rcpp_1.0.9             scales_1.2.1           plotrix_3.8-2         
[33] abind_1.4-5            TeachingDemos_2.12     ggplot2_3.4.0          stringi_1.7.8         
[37] dplyr_1.0.10           grid_4.1.2             rgdal_1.6-2            cli_3.4.1             
[41] tools_4.1.2            magrittr_2.0.3         PresenceAbsence_1.1.10 tibble_3.1.8          
[45] randomForest_4.7-1.1   Formula_1.2-4          pkgconfig_2.0.3        MASS_7.3-58.1         
[49] Matrix_1.5-1           data.table_1.14.6      pROC_1.18.0            assertthat_0.2.1      
[53] reshape_0.8.9          rstudioapi_0.14        iterators_1.0.14       rpart_4.1.19          
[57] earth_5.3.1            R6_2.5.1               nlme_3.1-160           nnet_7.3-18           
[61] compiler_4.1.2_        
then, I quit R studio and re-open it, the results of find.package("biomod2") as well as sessionInfo() are below:
> find.package("biomod2")
[1] "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/biomod2"
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] biomod2_4.1-2 raster_3.6-3  sp_1.5-1     

loaded via a namespace (and not attached):
 [1] gbm_2.1.8.1            tidyselect_1.2.0       terra_1.6-41           reshape2_1.4.4        
 [5] splines_4.1.2          lattice_0.20-45        colorspace_2.0-3       vctrs_0.5.1           
 [9] generics_0.1.3         mgcv_1.8-41            utf8_1.2.2             survival_3.4-0        
[13] rlang_1.0.6            pillar_1.8.1           withr_2.5.0            glue_1.6.2            
[17] DBI_1.1.3              plotmo_3.6.2           foreach_1.5.2          lifecycle_1.0.3       
[21] plyr_1.8.8             mda_0.5-3              stringr_1.4.1          munsell_0.5.0         
[25] gtable_0.3.1           codetools_0.2-18       maxnet_0.1.4           class_7.3-20          
[29] fansi_1.0.3            Rcpp_1.0.9             scales_1.2.1           plotrix_3.8-2         
[33] abind_1.4-5            TeachingDemos_2.12     ggplot2_3.4.0          stringi_1.7.8         
[37] dplyr_1.0.10           grid_4.1.2             rgdal_1.6-2            cli_3.4.1             
[41] tools_4.1.2            magrittr_2.0.3         PresenceAbsence_1.1.10 tibble_3.1.8          
[45] randomForest_4.7-1.1   Formula_1.2-4          pkgconfig_2.0.3        MASS_7.3-58.1         
[49] Matrix_1.5-1           data.table_1.14.6      pROC_1.18.0            assertthat_0.2.1      
[53] reshape_0.8.9          rstudioapi_0.14        iterators_1.0.14       rpart_4.1.19          
[57] earth_5.3.1            R6_2.5.1               nlme_3.1-160           nnet_7.3-18           
[61] compiler_4.1.2        

I did not get warnings when using BIOMOD_EnsembleForecasting() in these two runs, but a warning after BIOMOD_Modeling (Warning message:
executing %dopar% sequentially: no parallel backend registered ).

Best,

Muyao

**Comment by conanyao** [comment]
Unfortunately, I cannot find the binary files in these two runs. 
Best,
Muyao

**Comment by rpatin** [comment]
Hi Muyao,
I think I got the problem, sorry I was a bit slow to connect everything.
So you are working with version 4.1-2 on CRAN and you are asking for binary/filtered projection for >1 metric. Unfortunately this is actually bugged in the stable version. Fortunately it have been fixed since then.
So you can:
1. Stay with version (4.1-2) but give only one value for argument `metric.select` in `BIOMOD_EnsembleForecasting`.
2. Alternatively update to current github version (4.2-1) with `install_github('biomodhub/biomod2')` _(remember you have to use `data()` if you want to load GuloGulo data - but for your own code this should not matter)_

I believe you already tried version `4.2-1` but only with GuloGulo data and got stuck at the data loading ? 

Please let me know if something is unclear or if that does not solve your problem,
Best,
Rémi

**Comment by conanyao** [comment]
Hi Rémi,

Thank you for the explanation. 

Do you mean metric.select in BIOMOD_EnsembleModeling or metric.binary in BIOMOD_EnsembleForecasting? I cannot find metric.select in BIOMOD_EnsembleForecasting.
And I can get warnings after BIOMOD_EnsembleForecasting function. I am sorry I misspoke earlier.
The warning will disappear when metric.binary = 'all'. And it will appear when metric.binary = 'TSS' (or 'ROC').

Best,

Muyao

**Comment by rpatin** [comment]
Hi Muyao, 
Sorry I mixed up argument names.
You can:
1. Use only one metric in `metric.select` in `BIOMOD_EnsembleModeling`. But then you have to redo the ensemble modeling if you want to have results for the other metrics
2. Or use two (or more) metric in`metric.select` in `BIOMOD_EnsembleModeling` but then use only one metric in `metric.binary` (and respectively `metric.filter`) in `BIOMOD_EnsembleForecasting`.

In summary, no matter what you do in `BIOMOD_EnsembleModeling`, there must be only one metric for `metric.binary` and `metric.filter` in `BIOMOD_EnsembleForecasting` (at least with version 4.1-2 or older - if you update to github version it should not matter)

Sorry about the warning I am not sure which warning you see and in which condition, I got confused with all possibilities we spoke about. So you get a warning when:
- you run `BIOMOD_EnsembleModeling` _(with argument `metric.select` set to which value ?)_
- then when you use this results with `BIOMOD_EnsembleForecasting` and you get a warning _(which one?)_ when you use `metric.select = 'TSS'` (or ROC) but not with `metric.select = 'all'`
Is that it ?

Best,
Rémi

**Comment by rpatin** [comment]
Hi Muyao,
Thank you for the update and the precision, I could indeed reproduce your issue and found a bug related to that. I pushed a commit for that but it is on the current github version (`4.2-1`), for which this should not be an issue to ask for multiple binary/filtered transformation.

Concerning the question this is indeed the general idea. Remember that you can get thresholds that maximize your evaluation metrics with `get_evaluation(myBiomodEM, as.data.frame = TRUE)`, in the column `cutoff`.
You  can also use the function `bm_BinaryTransformation` from the package:
```
my_threshold <- c(0.7,0.8,0.75) # from the evaluation
ensb <- bm_BinaryTransformation(ensp, threshold = my_threshold, do.filtering = FALSE)
```
You need to give either one threshold (same for all layers) or as many threshold as layers. And you can do filtered transformation as well if you set `do.filtering = TRUE`.

Best,
Rémi

**Comment by conanyao** [comment]
Hi Rémi,

Thank you so much for your kind help. I revised my codes accordingly.

Best,

Muyao
