### ISSUE TITLE
some errors  about new version 

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#136]
hi，biomod team
I tried to use the latest version of biomod, but I found a series of problems.
```
library(devtools)
devtools::install_github('rspatial/terra')
devtools::install_github('biomodhub/biomod2')
```
1. When I was working on the ensemble model, it could display the current forecast very well. However, when ensembling with ssp126 - 2030, my iensemble map only shows the upper half, missing a large part.
![image](https://user-images.githubusercontent.com/104480028/202647568-3cabbe0e-1a88-408f-a77d-22a7a64124c4.png)

2. I cannot use the plot function when conducting pseudo distribution points

Error in x$. self$finalize() : attempt to apply non-function

3. When I am plotting (myExpl), there will be many“” Assigning a new crs Use 'project' to transform a SpatRaster to a new crs“”
 Thank you for your help！
cheers，chen

**Comment by MayaGueguen** [comment]
Hello Chen,

Thank you for installing the last biomod2 version :pray: 

Here are some comments : 

- The message `Error in x$. self$finalize() : attempt to apply non-function` is not a real error. It is a message randomly printed by the `terra` package, with no real impact on what you are actually doing, and that should disappear in the future when `terra` maintainers will fix that.

- `Assigning a new crs Use 'project' to transform a SpatRaster to a new crs` might be shown as well if the CRS projection is not well defined within your `myExpl` object.

- As for the plotting, this is not an error of the package rather than a result of your modelisation. Plus, it seems that you are representing a binary maps (only 0 or 1 values), with the color scale setting _white_ for 1 values so you are not seeing them.

Hope it helps,
Maya

**Comment by chenyongpeng1** [comment]
Thank you for your reply, but unfortunately, in my integration model (non binary), only cv can display all graphics, and all other graphics are half. This problem does not occur in my original version. Thanks again, my figure is as follows
![image](https://user-images.githubusercontent.com/104480028/202668028-970411a4-b421-4b20-8070-6641361567fd.png)

**Comment by MayaGueguen** [comment]
For me to be able to help you figure out if there is or not a problem coming from the modeling, I need you to give me more informations to understand and / or reproduce the _potentially bad_ behavior of the package : 

- what your data looks like ?
- what is your code ?
- do you have any warnings / error messages occuring at one step of the simulation ?

**Comment by chenyongpeng1** [comment]
Hello, thank you for your patience and help.

My data: only occurrent distribution points

Environmental variables: bioclim climate data, and land classification variables

My code is as follows
`setwd("E:/apis_11.17")
library(biomod2)
#library(terra)
library(ggplot2)
library(gridExtra)
library(raster)
library(rgdal)
library(rasterVis)
library(lattice)
library(sp)
library(spThin)
library(maptools) # Vector data management (sp)
library(raster) # Raster data management
library(rgdal) # Geospatial Data Abstraction Library
library(rgbif) # One of many GBIF access points (Global Biodiversity Information Facility)
library(maps) # Easy access to basic map layers
library(ggpubr)
library(dplyr)
library("sp")
library("rgdal")
library("fuzzySim")

DataSpecies <- read.csv('apis.csv')
myRespName <- 'apis'
myResp <- as.numeric(DataSpecies[, myRespName])
myRespXY <- DataSpecies[, c( 'longitude','latitude')]



bio_1 <-raster("bioclim/bio_1.tif")
bio_2 <-raster("bioclim/bio_2.tif")
bio_3 <-raster("bioclim/bio_3.tif")
bio_4 <-raster("bioclim/bio_4.tif")
bio_5 <-raster("bioclim/bio_5.tif")
bio_6 <-raster("bioclim/bio_6.tif")
bio_7 <-raster("bioclim/bio_7.tif")
bio_8 <-raster("bioclim/bio_8.tif")
bio_9 <-raster("bioclim/bio_9.tif")
bio_10 <-raster("bioclim/bio_10.tif")
bio_11 <-raster("bioclim/bio_11.tif")
bio_12 <-raster("bioclim/bio_12.tif")
bio_13 <-raster("bioclim/bio_13.tif")
bio_14 <-raster("bioclim/bio_14.tif")
bio_15 <-raster("bioclim/bio_15.tif")
bio_16 <-raster("bioclim/bio_16.tif")
bio_17 <-raster("bioclim/bio_17.tif")
bio_18 <-raster("bioclim/bio_18.tif")
bio_19 <-raster("bioclim/bio_19.tif")
elev<-raster("bioclim/elev.tif")

land_use<-raster("bioclim//land_use.tif")
extent(land_use) <- extent(bio_1)
land_use <- projectRaster(land_use,bio_1,method = 'ngb')

myExpl <- stack(c(bio_1,bio_3,bio_2,bio_8,bio_9,bio_12,bio_14,bio_15,bio_18,bio_19,land_use,elev))
sf::st_crs("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
plot(myExpl)

myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 3,
                                       PA.nb.absences = 10000,
                                       PA.strategy = 'random')


plot(myBiomodData.r)

bm_DefaultModelingOptions()

myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodOptions



# Create the different validation datasets

myBiomodCV <- BIOMOD_CrossValidation(bm.format = myBiomodData.r)
head(myBiomodCV)

# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.r,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    models = c('GLM', 'GBM', 'GAM', 'CTA', 'ANN', 'SRE', 'FDA',  'RF', 'MAXENT.Phillips.2'),
                                    nb.rep = 2,
                                    data.split.perc = 80,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC'),
                                    nb.cpu = 40,
                                    do.full.models = FALSE,
                                    seed.val = 123)


myBiomodModelOut

# Get evaluation scores & variables importance
myBiomodModelEval<-get_evaluations(myBiomodModelOut)
get_variables_importance(myBiomodModelOut, as.data.frame = TRUE)
dimnames(myBiomodModelEval)
write.csv(myBiomodModelEval,file = "./myBiomodModelEval_145.csv")
# KAPPA=myBiomodModelEval["KAPPA","Testing.data",,,]
# write.csv(KAPPA,"./KAPPA_145.CSV")
ROC=myBiomodModelEval["ROC","Testing.data",,,]
write.csv(ROC,"./ROC_145.CSV")
TSS=myBiomodModelEval["TSS","Testing.data",,,]
write.csv(TSS,"./TSS_145.CSV")
varimportan=get_variables_importance(myBiomodModelOut)
write.csv(varimportan,"./varimportan_20.csv")         

# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodModelOut)
bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'run'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'algo'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'dataset'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'expl.var', 'dataset'))
# Represent response curves
bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'min')
bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                      models.chosen = get_built_models(myBiomodModelOut)[3],
                      fixed.var = 'median',
                      do.bivariate = TRUE)


#### Ensemble models

# Model ensemble models
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.7),
                                      var.import = 3,
                                      metric.eval = c('TSS', 'ROC'),
                                      prob.mean = TRUE,
                                      prob.median = TRUE,
                                      prob.cv = TRUE,
                                      prob.ci = TRUE,
                                      prob.ci.alpha = 0.05,
                                      committee.averaging = TRUE,
                                      prob.mean.weight = TRUE,
                                      prob.mean.weight.decay = 'proportional')

myBiomodEM

# Get evaluation scores & variables importance
myBiomodModelEval<-get_evaluations(myBiomodEM, as.data.frame = TRUE)


get_variables_importance(myBiomodEM, as.data.frame = TRUE)
# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodEM, group.by = 'model')
bm_PlotEvalBoxplot(bm.out = myBiomodEM, group.by = c('model', 'model'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('expl.var', 'model', 'model'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('expl.var', 'model', 'dataset'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('model', 'expl.var', 'dataset'))
# Represent response curves
bm_PlotResponseCurves(bm.out = myBiomodEM, 
                      models.chosen = get_built_models(myBiomodEM)[c(1, 6, 7)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = myBiomodEM, 
                      models.chosen = get_built_models(myBiomodEM)[c(1, 6, 7)],
                      fixed.var = 'min')
bm_PlotResponseCurves(bm.out = myBiomodEM, 
                      models.chosen = get_built_models(myBiomodEM)[7],
                      fixed.var = 'median',
                      do.bivariate = TRUE)




myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'TSS',
                                  metric.filter = 'all',
                                  output.format = ".img",
                                  binary=TRUE,
                                  do.stack=TRUE,
                                  build.clamping.mask = T)
myBiomodProj


# Project ensemble models (from single projections)
myBiomodEMProj <-  BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                              bm.proj = myBiomodProj,
                                              output.format = ".img",
                                              models.chosen = 'all',
                                              metric.binary = 'TSS',
                                              do.stack=TRUE,
                                              metric.filter = 'TSS',
                                              binary=TRUE)




myBiomodEMProj

plot(myBiomodEMProj)

##################################                    ################################
#                                 ssp 126  2030
##################################                    ################################
ssp126_2030_bio_1 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_1.tif")
ssp126_2030_bio_2 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_2.tif")
ssp126_2030_bio_3 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_3.tif")
ssp126_2030_bio_8 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_8.tif")
ssp126_2030_bio_9 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_9.tif")
ssp126_2030_bio_12 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_12.tif")
ssp126_2030_bio_14 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_14.tif")
ssp126_2030_bio_15 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_15.tif")
ssp126_2030_bio_18 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_18.tif")
ssp126_2030_bio_19 <-raster("E:/Apis_9.28/2030_ssp126_ensemble/bio_19.tif")
myExplFuture_ssp126_2030 <- stack(c(ssp126_2030_bio_1,ssp126_2030_bio_3,ssp126_2030_bio_2 ,ssp126_2030_bio_8,ssp126_2030_bio_9,
                                    ssp126_2030_bio_12,ssp126_2030_bio_14,ssp126_2030_bio_15,ssp126_2030_bio_18,ssp126_2030_bio_19,land_use,elev))


sf::st_crs("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

plot(myExplFuture_ssp126_2030)
# Project onto future conditions

myBiomodProjectionFuture_ssp126_2030 <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                                          proj.name = '2030_ssp126',
                                                          new.env = myExplFuture_ssp126_2030,
                                                          models.chosen = 'all',
                                                          metric.binary = 'TSS',
                                                          metric.filter = 'TSS',
                                                          output.format = ".img",
                                                          binary=TRUE,
                                                          do.stack=TRUE,
                                                          build.clamping.mask = TRUE)
myBiomodProjectionFuture_ssp126_2030
myBiomodEMProj_ssp126_2030 <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                                         bm.proj = myBiomodProjectionFuture_ssp126_2030,
                                                         models.chosen = 'all',
                                                         metric.binary = 'TSS',
                                                         output.format = ".img",
                                                         do.stack=TRUE,
                                                         metric.select.thresh = c(0.7),
                                                         metric.filter = 'TSS')

myBiomodEMProj_ssp126_2030
plot(myBiomodEMProj_ssp126_2030)
# Load current and future binary projections

CurrentProj1 <- stack("E:/apis_11.17/apis/proj_Current/proj_Current_apis_ensemble_TSSbin.img")

FutureProj_EMssp126_2030 <- stack("apis/proj_2030_ssp126/proj_2030_ssp126_apis_ensemble_TSSbin.img")
FutureProj_EMssp126_2030<-FutureProj_EMssp126_2030$layer.3


myBiomodRangeSize_EM_ssp126_2030 <- BIOMOD_RangeSize(proj.current = CurrentProj1, proj.future = FutureProj_EMssp126_2030)
myBiomodRangeSize_EM_ssp126_2030$Compt.By.Models

write.csv(myBiomodRangeSize_EM_ssp126_2030$Compt,file = "./myBiomodRangeSize_ssp126_2030.csv")

writeRaster(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel,file = "./myBiomodRangeSize_ssp126_2030.tif",overwrite=T)

## Basic plot
plot(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel)

## Basic plot changing colors
plot(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel, col = c("brown", "green", "grey", "chartreuse3"))

## Basic plot changing colors and labels
plot(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel, 
     col = c("brown", "goldenrod1", "grey", "chartreuse3"),
     legend.width = 1,
     legend.shrink = 0.7,
     axis.args = list(at = seq(-2,1, 1), 
                      margin = 0.1,
                      labels = c("Loss","Stable1","Stable0","Gain")))
plot(myBiomodEMProj_ssp126_2030)
`
Thanks again，chen
cheers

**Comment by chenyongpeng1** [comment]
And you can see my new result，I can not find the error！
![image](https://user-images.githubusercontent.com/104480028/202695122-e45d33dd-1863-443e-b582-45fae71a4304.png)

**Comment by MayaGueguen** [comment]
Well, if there is no error, not sure I can be of much help...

I don't know how your results looked like before, but when running a new simulation, it means that several things changed : 

- your selection of pseudo-absence points
- the calibration and validation lines used in each single model

which can then change : 

- the evaluation of single models,
- the selection of these single models to be used to build ensemble models,
- and finally the predictions.

All of these reasons can lead to new results.

Maya

**Comment by chenyongpeng1** [comment]
OK, thank you very much. I think I should understand what you mean. I'll try to finish it.

chen
