### ISSUE TITLE
How can I use different amounts of pseudo-absence points in each algorithm?

### ISSUE THREAD

**Issue by Oliveira-D-R** [biomodhub/biomod2#138]
Hello guys!

How can I use different amounts of pseudo-absence points in each algorithm?

For example, how can I use 50000 pseudo-absences for models generated by Maxent and 100 for models using Bioclim.

I thank you for all.

**Comment by rpatin** [comment]
Hello @Oliveira-D-R 
Unfortunately you cannot do that yet with `biomod2`. it is on our long-term to-do list but we did not have time to implement it yet.
If you are not interested by ensemble models you can still run two separate modeling: one for Maxent and one for Bioclim with different number of pseudo absences and compare evaluation metrics or predictions.
Cheers,
Rémi

**Comment by Oliveira-D-R** [comment]
Hello @rpatin 
I see
It's really a pity. I will be looking forward to this update. Thank you very much for answering.
