### ISSUE TITLE
An error in output layer of RF model

### ISSUE THREAD

**Issue by momeni133** [biomodhub/biomod2#14]
Hello everyone,
I am using Biomod2 to estimate the potential distribution of a species.
Imagine that my study area has 1000*1000 pixels and I have 7 environmental variables with value for all the pixels (without any NAs).
When I estimate the distribution using MaxEnt or GBM, the output layer has value for all the 1000*1000 pixels and these values ranging from 0 to 1000.
When I estimate the distribution using RF (by using exactly the same data), the output layer has value for around 70% of pixels and the remaining pixels are all NA!
I have two questions:
1- I expect the values of the prediction layer to range between 0-1 but as I mentioned before in the case of MaxEnt and GBM the values ranging from 0 to 1000. I don't understand why?
2- Why when I use RF, in the prediction layer many pixels are NA?

Thanks

**Comment by DamienGeorges** [comment]
Hi,

For the 1-1000 scale this is a trick to save some space on the hard drive storing projections (integers lighter than floating numbers) then to come back on a prob scale you just have to devide it by 1000.

For the NA's this is wiered.. Are this NA's area correlated with a special value in one of our predictors (e.g. not trained value?)

**Comment by DamienGeorges** [comment]
Do you have a reproducible example?

**Comment by momeni133** [comment]
Thanks Damien,
The NAs are not correlated with any of the predictors.
Is that ok with you if I send the example to you by email?
Thanks again.

**Comment by momeni133** [comment]
Hi Damien,
I sent the code and all the data to your email address.
Thanks a lot

**Comment by DamienGeorges** [comment]
Sure! Please do.
