### ISSUE TITLE
Memory problem with MAXENT.Phillips and MAXENT.Phillips.2 for big dataset predictions

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#140]
Hi, 

Currently i use R4.2.2 and Biomod 4.1.2/4.1.3. Both MAXENT.Phillips and MAXENT.Phillips.2 need quite large Memory size using these new versions in my predictions using114GB dataset of environmental variables. It costs normally more than 100GB Memory, and up to 504GB (99% Memory) when projecting in my workstation with  512GB Memory and 700GB virtual Memory, whilst GBM only cost 2GB Memory running exactly the same data. And no map has been projected successfully although costing even much longer time than GBM.  Since its memory cost is keeping 99% for a while, i do not think it work this time too. It has not happened before when using old version for predictions with even much larger dataset. And there is no memory problem with my small dataset using the now version 4.1.2/4.1.3. 

BTW, may i ask which threshold Biomod2 uses to build ROC binaries? Is it the threshold of mximum sum of sensitivity and specificity?  If so, how to get the threshold and corresponding sensitivity and specificity written out? 

Best, 
Rui

**Comment by rpatin** [comment]
Hi Rui,
Thank you for reporting :pray:

1. Concerning the memory issue, I just wanted some precisions. Can you confirm that:
- `MAXENT.Phillips` is saturating your disk space ?
- Does `MAXENT.Phillips.2` also have the same issue ?
- Is your RAM saturated at some points ?

We are aware of an issue with `MAXENT.Phillips` storing many large files on the disk and have a fix scheduled for that.
Also note that algorithm are very different in their memory efficiency (especially virtual memory) and we have limited control on that as we just call the algorithm. So indeed `gbm` may be more efficient memory-wise than the other one.

2. Concerning the threshold question. For ROC binaries it will be the threshold maximizing AUC for a given model (likely to be different among models). If you want the threshold chosen for binaries to maximize the sum of sensitivity and specificity you need to ask for TSS binaries.

All threshold can be obtained with `get_evaluations(myBiomodModelOut, as.data.frame = TRUE)` with `myBiomodModelOut` being the output of `BIOMOD_Modeling()`.
You then get something like that:
```
                     Model.name            Algo  Run Dataset Eval.metric Testing.data Cutoff Sensitivity Specificity
1  MAXENT.Phillips_RUN1_AllData MAXENT.Phillips RUN1 AllData       KAPPA        0.644  237.0      81.720      83.065
2  MAXENT.Phillips_RUN1_AllData MAXENT.Phillips RUN1 AllData         ROC        0.864  235.5      81.720      83.065
3  MAXENT.Phillips_RUN1_AllData MAXENT.Phillips RUN1 AllData         TSS        0.648  237.0      81.720      83.065
```
And you can find threshold in the column `cutoff`. Here thresholds are between 0 and 1000 and must be divided by 1000 if you want the threshold between 0 and 1.

Feel free to let me know if something is unclear.
Best,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi,
Thanks very much for your quick reply.
No it is not about the disk space. It is about the RAM.
In my predictions with 114GB environmental variables, both MAXENT.Phillips and MAXENT.Phillips.2 saturated my 128 GB  RAM space, with no map created successfully in the end.
 MAXENT.Phillips.2 finally predicted successfully using 512GB RAM workstation.  But it costed normally more than 100GB RAM, and up to 504GB (99% RAM) during projection using my workstation which has 512GB RAM and 700GB virtual Memory. Such huge RAM costing has not happened before when using old version of MAXENT.Phillips, Biomod2 and R for predictions with even much larger dataset. But if i run the old version MAXENT.Phillips using Biomod 4.1.2/4.1.3 and R4.2.2, the error happens.
The code： ``myBiomodModelOut<-BIOMOD_Modeling(bm.format = myBiomodData, bm.options = myBiomodOptions,models=c('MAXENT.Phillips'), data.split.table = myBiomodCV,  prevalence=0.5, var.import=1, metric.eval=c('TSS', 'KAPPA', 'ROC'),  do.full.models=FALSE, modeling.id=paste(myRespName, "FirstModeling", sep=""), seed.val = 42, nb.cpu = 8) ``

Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Parallelisation with `foreach` is not available for Windows. Sorry.
2: executing %dopar% sequentially: no parallel backend registered 
3: In system(command = maxent.cmd, wait = TRUE, intern = TRUE, ignore.stdout = FALSE,  :
  running command 'java -mx512m -jar D:/PAPER9/LP_KD5KM/CV5_mxOld/maxent.jar environmentallayers="./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/Back_swd.csv" samplesfile="./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/Sp_swd.csv" projectionlayers="./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/Predictions/Pred_swd.csv" outputdirectory="./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs" outputformat=logistic  redoifexists visible=FALSE linear=TRUE quadratic=TRUE product=TRUE threshold=TRUE hinge=TRUE lq2lqptthreshold=80 l2lqthreshold=10 hingethreshold=15 beta_threshold=-1 beta_categorical=-1 beta_lqp=-1 beta_hinge=-1 betamultiplier=1 defaultprevalence=0.5 autorun nowarnings notooltips noaddsamplestobackground' had status 1
4: In file(file, "rt") :
  cannot open file './SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/SP_AllData_RUN1_Pred_swd.csv': No such file or directory

 Getting predictor contributions...Error in file(fname, "r") : cannot open the connection
In addition: Warning messages:
1: In system(command = maxent.command, wait = TRUE, intern = TRUE) :
  running command 'java -mx512m -cp "D:/PAPER9/LP_KD5KM/CV5_mxOld/maxent.jar" density.Project "" "./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/Predictions/Pred_swdBis_75543.csv" "./SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/projMaxent.asc" doclamp=false visible=false autorun nowarnings notooltips' had status 1
2: In file(fname, "r") :
  cannot open file './SP/models/SPFirstModeling/SP_AllData_RUN1_MAXENT.Phillips_outputs/projMaxent.asc': No such file or directory
Error in { : task 1 failed - "Unable to make model prediction"


I just sent the old version MAXENT.jar to your email box too. 

Best,
Ruiju

**Comment by rpatin** [comment]
Hi Ruiju,
Thanks for the update. 
So if it is all about RAM, I have some answers:
- Both `MAXENT.Phillips` and `MAXENT.Phillips2` method to predict on a new raster require converting your raster into a `data.frame`.
  - for `MAXENT.Phillips` it is because we are limited in how we can interact with `maxent.jar` and for predicting an already existing model we did not manage to circumvent that strategy.
  - for `MAXENT.Phillips2`, I must admit that I do not why it is done like, probably because it was working otherwise but it could be worth a check.

What I am trying to explain is that converting your whole environmental data into data.frame is very costly memory-wise (in RAM)  compared to prediction directly using a raster (and managing env. data chunk by chunk - which is why other methods such as `gbm` are much more memory-efficient).

Concerning the error, I am sorry, but I got lost in your explanations. You were trying to say that _before_ you were able to run predictions on much larger dataset. Do you mean:
- with old `maxent.jar` ?
- with old version of `biomod2` ?  version 3.5.1 which was on CRAN until last month ?
- or both (old `maxent.jar` and old version of `biomod2`) ?

In any case I think the error you posted is due to the old version of `maxent.jar` that is not supported by current `biomod2` version.

In general we will be trying to improve support for large dataset although it is a long-term work and we cannot do promises with  a time-frame. Meanwhile you can also crop your raster in several part, predict on each part and merge predictions. I know this is not ideal but I am afraid we may have no other short-term solutions to offer.

Best,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi,

Many thanks for your help!

Yes, biomod2 3.1.5 does better in RAM costing of MAXENT predictions in my case using more than 100GB variables. It costed about maximum 50 GB RAM, rather than 500GB RAM as biomod 2 4.1.2 costed.  

Currently, i am using biomod2 3.5.1.
I need to create the predictive tif files of both continuous maps and TSS binaries. But only continous TIFs of predictive maps were given, although the TSS binary map proj_current1_SP_TSSbin.img was also created. May i ask if we can directly output  TIFs of TSS binary of each single prediction as well?
The code used as below, 
**myBiomodModelOut<-BIOMOD_Modeling(myBiomodData, models=c('RF','GBM'), models.options=myBiomodOption, DataSplitTable=myBiomodCV, Prevalence=0.5, VarImport=3, models.eval.meth=c('TSS', 'KAPPA', 'ROC'), SaveObj=TRUE, rescal.all.models=TRUE, do.full.models=FALSE, modeling.id=paste(myRespName, "FirstModeling", sep=""))
myBiomodModelOut
myBiomodProj<-BIOMOD_Projection(modeling.output=myBiomodModelOut, new.env=myExpl, proj.name='current1',selected.models='all',binary.meth='TSS',  binary=TRUE, compress='xz',clamping.mask=F, output.format='.img',nb.cpu=16,do.stack=TRUE)
myBiomodProj 
xx <- get_predictions(myBiomodProj)
dir.create("2070biotiff_proj2", showWarnings = F)
writeRaster(xx, format = 'GTiff', filename = "2070biotiff_proj2/proj_TEST", bylayer=T, suffix='names', overwrite = T)**


And how can i creat ensemble model of Coefficient of variation of Probabilities only by TSS, not by TSS, by ROC and by KAPPA as all?  
The code i used as below, 
**myBiomodEM <- BIOMOD_EnsembleModeling(
modeling.output = myBiomodModelOut,
chosen.models = "all",
em.by = 'algo',
#eval.metric = "TSS",
#eval.metric.quality.threshold = NULL,
models.eval.meth = c('TSS','ROC'),
prob.mean = FALSE,
prob.cv = TRUE,
prob.ci = FALSE,
prob.ci.alpha = 0.05,
prob.median = FALSE,
committee.averaging = FALSE,
prob.mean.weight = FALSE,
prob.mean.weight.decay = 'proportional')
myBiomodEM
myBiomodEMProj <-  BIOMOD_EnsembleForecasting(projection.output = myBiomodProj,EM.output = myBiomodEM,
                                             models.chosen = 'all',metric.binary='TSS',
                                             binary=TRUE,do.stack=TRUE)
myBiomodEMProj 
xx <- get_predictions(myBiomodEMProj )
dir.create("2070biotiff_proj4", showWarnings = F)
writeRaster(xx, format = 'GTiff', filename = "2070biotiff_proj4/proj_EM", bylayer=T, suffix='names' , overwrite = T)**

Many thanks in advance!
Best, 
Ruiju

**Comment by tongruiju** [comment]
Hi Rémi,
Thanks a lot and looking forward for the improvement.

About binary projection, I actually have the same problem when using biomod2 4.1-2.
I need to create the predictive tif files of both continuous maps and TSS binaries for each individal prediction. But only continous TIFs of predictive maps were given, although the TSS binary map proj_current1_SP_TSSbin.gri was also created. May i ask if we can directly output TIFs of TSS binary of each single prediction as well?
The code used as below,
**myBiomodModelOut<-BIOMOD_Modeling(bm.format = myBiomodData, bm.options = myBiomodOptions,models=c('GBM','RF'), data.split.table = myBiomodCV,  prevalence=0.5, var.import=3, metric.eval=c('TSS', 'KAPPA', 'ROC'),  do.full.models=FALSE, modeling.id=paste(myRespName, "FirstModeling", sep=""), seed.val = 84, nb.cpu = 16) 
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,proj.name = 'Current',new.env = myExpl,models.chosen = 'all',metric.binary = 'TSS', binary=TRUE, build.clamping.mask = FALSE, compress='xz',nb.cpu=16,do.stack=TRUE)
myBiomodProj
xx <- get_predictions(myBiomodProj)
dir.create("2070biotiff_proj", showWarnings = F)
writeRaster(xx, format = 'GTiff', filename = "2070biotiff_proj/proj_TEST", bylayer=T, suffix='names', overwrite = T)**


And how can i creat ensemble model of Coefficient of variation of Probabilities only by TSS, not by TSS, by ROC and by KAPPA as all, since it is time-consuming to project these files.
The code i used as below,
**myBiomodEM <- BIOMOD_EnsembleModeling(
bm.mod = myBiomodModelOut,,
models.chosen = "all",
em.by = "algo",
metric.select = "all",
metric.select.thresh = NULL,
metric.select.table = NULL,
metric.eval = c("TSS", "ROC"),
var.import = 3,
prob.mean = FALSE,
prob.median = FALSE,
prob.cv = TRUE,
prob.ci = FALSE,
prob.ci.alpha = 0.05,
committee.averaging = FALSE,
prob.mean.weight = FALSE,
prob.mean.weight.decay = "proportional",
nb.cpu = 16)
myBiomodEMProj <-  BIOMOD_EnsembleForecasting(
bm.em=myBiomodEM,
bm.proj = myBiomodProj,
models.chosen = "all",
metric.binary = "TSS",
binary=TRUE,do.stack=TRUE,
nb.cpu = 16)
xx <- get_predictions(myBiomodEMProj )
dir.create("2070biotiff_proj1", showWarnings = F)
writeRaster(xx, format = 'GTiff', filename = "2070biotiff_proj1/proj_EM", bylayer=T, suffix='names' , overwrite = T)**

Best,
Ruiju

**Comment by rpatin** [comment]
Hi Ruiju,

1. Concerning the output of maps for individual binary transformation in `BIOMOD_Projection`
    - In general that would be done by using `do.stack = FALSE` in `BIOMOD_Projection`. Although right now there is an issue with it in the CRAN 4.1-2 version. It is however working with the current github version (4.2-1) that you can use with `devtools::install_github('biomodhub/biomod2')`.
    - Alternatively, with your current output, you can also read the file binary map _proj_current1_SP_TSSbin.img_ with `stack("binary map proj_current1_SP_TSSbin.img")` and save each layer of the raster as separate file for each model.
    - Note that right now it is not possible to use '.tif' format within biomod2 but the next upcoming release (4.2-2) should allow such file format.

2. Concerning the computation of ensemble model only for one evaluation metric, you have two solutions depending on your need:
    - In `BIOMOD_EnsembleModeling` you can set argument `metric.select = 'TSS'` and then you will obtain only model calculated based on TSS and `BIOMOD_EnsembleForecasting` will only project the TSS model
    - In `BIOMOD_EnsembleForecasting`  you can use argument `models.chosen` to select the model you want to project. You can have the list of possible model name with `get_built_models(myBiomodEM)`.

Please let me know if something is unclear.
Best,
Rémi

**Comment by rpatin** [comment]
Hi Ruiju,
I just updated the current github version with a commit reproducing old 3.5.1 behaviour for `maxent`. If you try it that should greatly reduce the memory issues that you encountered and likely be on par with version 3.5.1.
Please let us know if you have feedback on those changes.
Best,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi,
Thanks very much. It works now. The MAXENT.Phillips prediction using Biomod 2 4.2-1 costs ~32GB RAM for my 114GB data.

But it seems still something wrong with MAXENT.Phillips modeling. The error often happens in projection "Error in { : task 2 failed - "object 'overwrite' not found"".
My code as following:
" myBiomodModelOut<-BIOMOD_Modeling(bm.format = myBiomodData, bm.options = myBiomodOptions,models=c('GBM','MAXENT.Phillips'), data.split.table = myBiomodCV, prevalence=0.5, var.import=3, metric.eval=c('TSS', 'KAPPA', 'ROC'), do.full.models=FALSE, modeling.id=paste(myRespName, "FirstModeling", sep=""), seed.val = 84, nb.cpu = 16)
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,proj.name = 'Current',new.env = myExpl,models.chosen = 'all',metric.binary = 'TSS', binary=TRUE, build.clamping.mask = FALSE, compress='xz',output.format = ".img",nb.cpu=16,do.stack=FALSE,overwrite=TRUE)"

Best,
Ruiju

**Comment by rpatin** [comment]
Hi Ruiju,
Happy to know it's working well - or at least that the memory issue is somewhat solved.

Concerning the error, I did a fix shortly after the one for maxent that should have corrected that error. Can you confirm that you encounter the error with the current github version ? I pushed the commit related to that on the 2nd of december if I remember well.
If you still have the error with current version I will investigate what is happening and hopefully fix it quickly.
Best,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi,


Yes, the biomod2 4.2-1 i am using currently should be the new version. I installed it at last Sunday December 4th using Github version. It run successfully at last Sunday. But it does not work now because of the error i reported.

Many thanks,

Ruiju













At 2022-12-06 23:33:58, "rpatin" ***@***.***> wrote:

Hi Ruiju,
Happy to know it's working well - or at least that the memory issue is somewhat solved.

Concerning the error, I did a fix shortly after the one for maxent that should have corrected that error. Can you confirm that you encounter the error with the current github version ? I pushed the commit related to that on the 2nd of december if I remember well.
If you still have the error with current version I will investigate what is happening and hopefully fix it quickly.
Best,
Rémi

**Comment by rpatin** [comment]
Hi Ruiju,
Thank you for the confirmation. I just pushed another commit that should fix your problem. Can you try with current version ?
Thanks in advance,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi,
Not at all. Thanks very much for you always trying to help.
Sorry, another error happened before now comes back again,
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,proj.name = 'Current',new.env = myExpl,models.chosen = 'all',metric.binary = 'TSS', binary=TRUE, build.clamping.mask = FALSE, compress='xz',output.format = ".img",nb.cpu=16,do.stack=FALSE)

-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=

> Projecting SP_AllData_RUN1_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN1_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN1_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN2_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN2_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN2_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN3_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN3_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN3_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN4_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN4_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN4_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN5_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN5_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN5_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN6_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN6_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN6_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN7_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN7_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN7_RF ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN8_MAXENT.Phillips ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN8_GBM ...
Writing projection on hard drive...
> Projecting SP_AllData_RUN8_RF ...
Writing projection on hard drive...Error in { : 
  task 1 failed - "[writeRaster] file exists. You can use 'overwrite=TRUE' to overwrite it"
In addition: Warning message:
In BIOMOD_Projection(bm.mod = myBiomodModelOut, proj.name = "Current",  :
  Parallelisation with `foreach` is not available for Windows. Sorry.


Best,
Ruiju





















在 2022-12-08 17:07:21，"rpatin" ***@***.***> 写道：

Hi Ruiju,
Sorry for the inconvenience, it should be fixed by now if you reinstall (again...) from github. I know I already said that in the past but hopefully this should be the last one.
Still in case I'm wrong, please let us know,
Best,
Rémi

**Comment by rpatin** [comment]
Hi Ruiju,
I think I missed the `do.stack = FALSE` in your examples ... Can you try with the bugfix I just pushed ? Thank you for your patience and understanding :pray: 
Best,
Rémi

**Comment by tongruiju** [comment]
Hi Rémi, 
Yes, it works now. 
Fully thanks for your help!!!

Best wishes, 
Ruiju
