### ISSUE TITLE
confidence intervals for ensemble models

### ISSUE THREAD

**Issue by ingridgarfeltpaulsen** [biomodhub/biomod2#146]
Hey,

I'm currently making an ensemble response curve out of the values derived from response.plot2() function but I have problems understanding the confidence intervals. 

From the response.plot2() function I get four different ensemble outputs and I interpret them like this:
summer.9vars_EM**mean**ByTSS_mergedAlgo_Full_PA1 – mean of probabilities
"summer.9vars_EM**ciInf**ByTSS_mergedAlgo_Full_PA1" – lower confidence level?
summer.9vars_EM**ciSup**ByTSS_mergedAlgo_Full_PA1 – upper confidence level?
summer.9vars_EM**cv**ByTSS_mergedAlgo_Full_PA1 – coefficient of variation

What I don't understand is that the the predictive value ciSup is often below the mean of probabilities and the predictive value for ciInf is often 0. Am I interpreting the ciSup and ciInf wrongly or is there something wrong with my ensemble model?

Code used to generate the ensemble model:

myBiomodEM <- BIOMOD_EnsembleModeling(
  modeling.output = biomod_models_out,
  chosen.models = chosen_models, 
  em.by = 'PA_dataset+repet', 
  eval.metric = c("TSS"),
  eval.metric.quality.threshold = c(0.0), # we dont want to use this statistic anyhow
  prob.mean = TRUE,
  prob.cv = TRUE
  prob.ci = TRUE
  prob.ci.alpha = 0.05,
  VarImport = 3
  prob.median = FALSE,
  committee.averaging = FALSE,
  prob.mean.weight = FALSE, 
  prob.mean.weight.decay = 'proportional') #the relative importance of weights from TSS scores. Attributed weights are proportional to evaluation scores

#re-load ensemble models summer
ensemble_9vars_summer <- get(load("summer.9vars/summer.9vars.1666690970ensemble.models.out"))
ensemble_9vars_summer <- BIOMOD_LoadModels(ensemble_9vars_summer)

vars9_summer_resp <- biomod2::response.plot2(models = ensemble_9vars_summer,
                                        Data = get_formal_data(summer9vars,'expl.var'),
                                        show.variables= get_formal_data(summer9vars,'expl.var.names'),
                                        do.bivariate = FALSE,
                                        fixed.var.metric = 'median',
                                        col = c("blue", "red"),
                                        legend = TRUE,
                                        data_species = get_formal_data(summer9vars,'resp.var'))

I am using an older version of biomod (3.5.1) but I can't redo all my models because it takes very long so I still hope I can get som help on this issue!

Thank you,

Ingrid

**Comment by rpatin** [comment]
Hi Ingrid,
Thank you for reporting :pray: 
Unfortunately we cannot do much support for this old version, sorry for the inconvenience.

Your interpretation of the ciSup and ciInf is correct and it is expected to have the median (and most likely the mean as well) in between. 

If that is not the case, something may have gone wrong. How many algorithm are you using ? Mean and CI calculations may not be ideal when ensemble models are calculated over small sets of models. 
Best,
Rémi
