### ISSUE TITLE
BIOMOD_Modeling - invalid connection

### ISSUE THREAD

**Issue by sempergnarus** [biomodhub/biomod2#150]
I tuned random forest and maxent but I am having this error in both during BIOMOD_Modeling and probably in others too (in bimod4.1-2) which I could not figure out.  

Error in summary.connection(connection) : invalid connection

any suggestions

![image](https://user-images.githubusercontent.com/80183402/207738785-c3087b0d-2ae3-4b00-a0f9-e58d7f0d87a4.png)

**Comment by rpatin** [comment]
Hello @sempergnarus,
Thank you for reporting :pray: 
My best guess would be that it is an error linked to parallel computation that occurred in `BIOMOD_Tuning` (see [this issue](https://stackoverflow.com/questions/64519640/error-in-summary-connectionconnection-invalid-connection) ). I suppose `BIOMOD_Tuning` was called with parallel computation activated ?

Thus, could you try the solution they proposed? 
```
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
unregister_dopar()
```
This should unregister the parallel cluster and hopefully allow you to do a proper call to `BIOMOD_Modeling`
If not please let us know.
Best,
Rémi

**Comment by sempergnarus** [comment]
Yes, this code worked perfectly! Thank you so much!
