### ISSUE TITLE
biomod2 vs dismo maxent response curve

### ISSUE THREAD

**Issue by akamolphat** [biomodhub/biomod2#151]
Dear authors of biomod2,

I have been playing around with the biomod2 and dismo R package. I ran maxent in both packages using the same testing and validation dataset. I used the same maxent.jar file to run, and I think I used the same settings (feature classes = LQP, betamultiplier = 1). The calculated ROC were similar (to 2 decimal places) but not identical, and the projections were somewhat similar. However, the response curves were quite different. I was wondering if there are any particular settings that are different in dismo vs biomod2.

The output format from dismo was set to logistic (as to cloglog).

The ROC, response curves and the projections of my 5 cross-validation dataset can be found attached. The cross validation datasets in the PDF files are in the same order. I have also tried this with feature classes = L, betamultiplier = 1 and similar differences are also observed.

What could be the reason for this difference? Are there any other differences in the settings in biomod2 vs dismo? Is this to do with how the response curves are produced in biomod2 vs dismo?

I used dismo version 1.3.9 and biomod2 version 3.5.1. The maxent version used is maxent version 3.4.3. The codes were executed in R version 4.2.1. 

Yours sincerely,
Kamolphat Atsawawaranunt

[dismo_maxent_logv2.pdf](https://github.com/biomodhub/biomod2/files/10232968/dismo_maxent_logv2.pdf)
[biomod2_maxentv2.pdf](https://github.com/biomodhub/biomod2/files/10232967/biomod2_maxentv2.pdf)

**Comment by rpatin** [comment]
Dear Kamolphat,
Thank you for reporting :pray: 
I think there may be several points that could make the difference here:
1. both packages produce response curve for each variables, by varying the value for the current variable while keeping all other variables to a constant values. By default for the constant values of other variables, `biomod2` uses the *mean*, while `dismo` uses the *median* of its distribution. Given that your response curves are not that different in shape and mostly have different level, I would definitely try to fix the same parameter (e.g. `dismo::response(x, at = "mean")`)
2. There are a lot of paremeters for `maxent`. Did you make sure to fix all of them to similar values between `biomod2` and `dismo`. Each parameter that you do not fix will be set to a default value that may differ between `biomod2` and `dismo`
For `biomod2` you can access default modeling options for `maxent` with:

```
myOptions <- BIOMOD_ModelingOptions()
myOptions@MAXENT.Phillips
```

Point 1. could explain why response variables seems different
Point 2. could explain slight differences in AUC/ROC or model projection (which I believed is also the case, although it was hard to evaluate without a proper raster comparison)

Let us know if that explain the difference you observe. 
Best regards,
Rémi

**Comment by akamolphat** [comment]
Dear Rémi,

Thank you so much for your explanation. I checked and it is not point 1 that is causing the response curves to be different. I am mostly curious about the difference for log_pop_dens which has a slightly different shape as it levels off in dismo but not in biomod2.

Please find a reproducible code and the input attached. The codes are in .txt file as I cannot upload .R files. You will have to alter the path2maxent object to match the path to maxent on the local computer.

Yours sincerely,
Kamolphat Atsawawaranunt (A)

[Reproducible_codes.txt](https://github.com/biomodhub/biomod2/files/10242222/Reproducible_codes.txt)
[data_fold1.csv](https://github.com/biomodhub/biomod2/files/10242218/data_fold1.csv)

**Comment by rpatin** [comment]
Dear Kamolphat,
I tried to run your code with current CRAN version of `biomod2` and here is what I obtain:
1. With `biomod 4.1-2`
![image](https://user-images.githubusercontent.com/8982316/208054022-ff71d7f0-30cc-4ca7-a354-fa0411746e6e.png)

2. With `dismo`
![image](https://user-images.githubusercontent.com/8982316/208054412-b4eca882-b309-4640-8c66-1b899dc5b196.png)

Response curve for `log_pop_dens`  are very similar in shape to my eye, when you account for the difference in x-scale. There are still slight difference in the level they achieve. For other variables response curves are also quite similar in shape if not in level as well. 

I would however like to point out that in your example most of the variability in your projection is attributed to the variable `gdd5`. You can see that if you calculate `biomod2` variable importance with argument `varimport = 3` in `BIOMOD_Modeling` and then use `get_variable_importance(myBiomodModelOut)`. Alternatively, you can also check your spatial projection that should be very similar to a map of `gdd5`.

And for `gdd5`, response curves are always highly similar. When fitting models there are often some randomness (which you can control by setting the seed) so if you run two model sequentially, results are likely to be slightly different, unless you can fix the same seed (in R `set.seed(42)` for instance). Here I suppose this is what you see and you are more likely to see those small random differences occur for variables that are not very important in the model.

I hope this is clear enough. If not feel free to ask further questions.
Best regards,
Rémi
