### ISSUE TITLE
Accessing raw response curve data--biomod run in parallel

### ISSUE THREAD

**Issue by tobioke** [biomodhub/biomod2#154]
Hi there,

I'm running biomod in parallel and I wish to access the raw data for response curves for both individual and ensemble models. This was straightforward in the old  version. For instance, to extract response curve data for a GLM run and a subset of my  climate data in the older version, I simply did the following steps: 

`tt =load("D:/../Species_PA1_RUN1_GLM")`                            ##load single model
```
## convert rasterstack to dataframe
var = as.data.frame(myExpl, xy = T) %>%  ## convert raster stack into dataframe 
 drop_na()   
``` 

`resp_data = response.plot2(tt, var, show.variables = c("bio17", "bio9", "organic_15"), plot = F)`            ## obtain response curve data

The problem is `response.plot2` is now deprecated and replaced with `bm_PlotResponseCurves` but the latter function does not seem to take the same input as the `response.plot2` function as suggested by the error message that was returned:

`Error in .fun_testIfInherits(TRUE, "bm.out", bm.out, c("BIOMOD.models.out",  : 
bm.out must be a 'BIOMOD.models.out' or 'BIOMOD.ensemble.models.out' object`

I looked at both the biomod manual and the vignette to understand the new  function but they were not helpful.  I was wondering if you have a tip for obtaining the data from folder, especially when biomod was run in parallel, where the outputs normally got written to a folder. 

Thanks,

Tobi

**Comment by MayaGueguen** [comment]
Hello Tobi,

Thanks for reporting :pray: 
As you have noticed, the [bm_PlotResponseCurves](https://biomodhub.github.io/biomod2/reference/bm_PlotResponseCurves.html) replaces now the previous `response.plot2` function.
It may come with a few differences in the arguments, but globally it works the same : 
- you must provide a `bm.out` object, obtained from the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function
- if you wish to use the same explanatory variables than the ones used at the modeling step, it is not necessary for you to provide it again to the function
- it returns a `list` object, containing both the plot and the `data.frame` containing predicted values to produce the plot

In your case, you do not need to provide your `var` data, but your `tt` object must be the R object obtained from the modeling step with [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function (_might be something like `Species.AllModels.models.out` in your folder_).

**However, please notice that it might not work with modeling objects obtained from previous `biomod2` versions. We apologize for that.** 

Also, it does not change a thing whether `biomod2` has been run in parallel or not, it should not change the results' presence in your modelisation folder.

Hope it helps, and do not hesitate if you have further questions.
Maya

**Comment by tobioke** [comment]
Hi Maya,

Thanks for your response. I neglected to mention that I tried all the `.out` files in the output folders following the error message (and now following your instruction here) but the error message persists. Also, there is no such file as `Species.AllModels.models.out` in any of my folders. 

There are two` .out `in the main folder and only one of them  `Species.SpeciesBIOMOD.ensemble.models.out` seems to contain any relevant data. But this file also returns the same error message when fed into the function as you described. I have attached the file here. 

At this point, I'm suspecting that there might be a bug in the `bm_PlotResponseCurves` function. 

To be sure that I have the correct `.out` file,  can you tell in what subfolder precisely the output of `BIOMOD_modeling` (the relevant `bm.out`) would have been written? I don't think the folder structure in `biomod2` has changed from the previous version.

Thanks,

Tobi
[Species.SpeciesBIOMOD.ensemble.models.zip](https://github.com/biomodhub/biomod2/files/10339557/Species.SpeciesBIOMOD.ensemble.models.zip)

**Comment by tobioke** [comment]
Hi Maya,

Please ignore the above. It turns out that I was not feeding in the `.out ` files correctly.  I can now obtain the response curves. But I only need to access the raw data that are being used to make the response curves. Setting `plot = F` works for retrieving raw data in the previous version. So, I set `do.plot = F`  but did not return the data. Do you have any tips for retrieving the raw data?

Thanks,

Tobi

**Comment by MayaGueguen** [comment]
Hello Tobi,

Good to hear that progress is being made !
The function is supposed to return in any case the table containing the data used to make the response curves, whether `do.plot` is set to `TRUE` or `FALSE`.. For example : 
```
res_plot <- bm_PlotResponseCurves(myModelOut)
str(res_plot)
```
`res_plot` should be a `list` containing two elements : `tab` and `plot`.
Do you get any error or warning message ?

Maya

**Comment by tobioke** [comment]
Hi Maya,

I indeed had a list with two elements and I'm now able to retrieve the table. The confusion was when I tried to subset a list that was generated by biomod earlier, I got an error that suggests that the general approach for subsetting a list was not applicable to biomod-derived list. So, I sort of assumed that biomod was self-contained in all cases. 

Thanks for your help.

Tobi
