### ISSUE TITLE
Random forest 'sampsize' argument in modelling options does not match randomForest documentation 

### ISSUE THREAD

**Issue by cwaldock1** [biomodhub/biomod2#155]
Hello, 

I want to fit downsampled random forests (sensu Valavi et al. 2021), so should ensure the randomForests for classification within biomod2 are fitted with the sampsize parameter. For classification this should have one value for each strata (i.e., sample size for 0s and sample size for 1s input as a vector of length 2). Trying this in BIOMOD_ModelingOptions using:

BIOMOD_ModelingOptions(RF = list(do.classif = TRUE,
                                                    ntree = 1000,
                                                    mtry = 'default',
                                                    sampsize = c("1" = sum(training$occ==1), "0" = sum(training$occ==1)),
                                                    nodesize = 1,
                                                    maxnodes = NULL))

gives the following warning:
In if (objValue < 0 | objValue%%1 != 0) { :
  the condition has length > 1 and only the first element will be used

It shows that only the first element of the custom sampsize vector is passed to the new modelling arguments. In the randomForest package it is only in the regression case that one sample size is needed, for classification randomForest needs two. So, i'm unsure whether the custom sampsize is implemented as expected inside the biomod2 functions once BIOMOD_Modeling is run. 

Thanks for any assistance :) 

Cheers,
Conor

**Comment by cwaldock1** [comment]
Hi Maya, 

Thanks for the quick response. I re-ran my code with the update, which now doesn't throw an error, great! However, when I check the modelling options given, the random forest still has a vector of length 1 for the sampsize argument. If using the randomForest package it should be a vector of 2, so i'm still not 100% sure if the internal randomForest fitted by biomod2 will take the argument as in the native package, and therefore perform the down-sampled RF?

This is how the return from modelling options looks: 
RF = list( do.classif = TRUE,
           ntree = 1000,
           mtry = 'default',
           sampsize = 819, ### here I think it should be a vector of length 2 (one for presence one for absence)
           nodesize = 1,
           maxnodes = NULL)

Many thanks for your assistance. 

Conor

**Comment by cwaldock1** [comment]
As some additional information if its helpful, here is how the downsampled random forests are fitted from Valavi et al (https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1486)

```

prNum <- as.numeric(table(training$occ)["1"]) # number of presences
bgNum <- as.numeric(table(training$occ)["0"]) # number of backgrounds 

# the sample size in each class; the same as presence number 
smpsize <- c("0" = prNum, "1" = prNum)

rf_downsample <- randomForest(formula = occ ~., 
                                                      data = training, 
                                                      ntree = 1000, 
                                                      sampsize = smpsize, 
                                                      replace = TRUE) 

```

Cheers!
Conor

**Comment by MayaGueguen** [comment]
Hello Conor,

I'm very sorry I'm getting back to you so late.
Did you manage to run your code as you wanted in the end ?
I checked, for the print of the `BIOMOD_ModelingOptions` function, showing only one value for the `sampsize` argument, it was just a rendering problem, there were 2 values registered into the object (_you can check btw with the little code below_). I just pushed the correction for that onto the github folder.
```
MO = BIOMOD_ModelingOptions(RF = list(do.classif = TRUE,
ntree = 1000,
mtry = 'default',
sampsize = c("1" = sum(training$occ==1), "0" = sum(training$occ==1)),
nodesize = 1,
maxnodes = NULL))

MO$RF
```

Also, for information, we are planning in the coming months to re-think the way options are given to the models, so it can be a bit more general and linked to the functions and packages called. Let's hope it will get things smoother !

Maya

**Comment by cwaldock1** [comment]
Hi Maya, 

Thanks for the update. Actually because my scripts were written using 4.2-1 and didnt work properly for 4.2-2 yet (other functions gave errors in my set up of biomod2), so I reverted back to 4.2-1. I will have a play around in the coming weeks with 4.2-2 to see if this issue is fixed for me.  Thanks for your help.

Conor
