### ISSUE TITLE
How to select multiple thresholds for multiple metric.select in BIOMOD_EnsembleModeling?

### ISSUE THREAD

**Issue by LorenzoBernicchi** [biomodhub/biomod2#156]
Hello everyone,
I am fairly new to R and especially to biomod2 and I am diving into the incredible adventure of using it for my master thesis!

I would like to know if is it possible to select a given threshold for a given metric within the Ensemble modeling function. I want to use all the single models with values of ROC and TSS higher than 0.7 and 0.5, respectively. 

I hope I have made myself clear enough, and I hope you can help me!

Thank you so much in advance, I wish you a great day and weekend.

**Comment by MayaGueguen** [comment]
Hello Lorenzo,

Welcome in `biomod2` then ! :wave: 

Unfortunately, for now, filtering through evaluation metric of single models to build ensemble models only works for one metric at a time. Meaning that you can provide 2 or more filtering metrics to the `metric.select` parameter, and as many corresponding values to the `metric.select.thresh` parameter, but it will then build you 2 or more ensemble models, each one using one of the metric provided to select the single models to keep.

For example, in your case, if you set something like : 
```
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('ROC', 'TSS')
                                      metric.select.thresh = c(0.7, 0.5),
                                      metric.eval = c('TSS', 'ROC'),
                                      var.import = 3,
                                      prob.mean = TRUE,
                                      prob.median = FALSE,
                                      prob.cv = FALSE,
                                      prob.ci = FALSE,
                                      prob.ci.alpha = 0.05,
                                      committee.averaging = TRUE,
                                      prob.mean.weight = FALSE,
                                      prob.mean.weight.decay = 'proportional',
                                      seed.val = 42)
```
it will give you 2 ensemble models, one built with single models with ROC > 0.7, and one built with single models with TSS > 0.5.

Hope it's clearer now, and sorry that it is not possible to combine filtering metrics :grimacing: .
Maya
