### ISSUE TITLE
Number of knots in MAXENT.Phillips

### ISSUE THREAD

**Issue by akamolphat** [biomodhub/biomod2#157]
Dear biomod2 team,

I was wondering if there is a way to define the number of knots for the threshold and hinge feature class in MaxEnt ran in biomod2.

Yours sincerely,
Kamolphat Atsawawaranunt

**Comment by MayaGueguen** [comment]
Hello Kamolphat,

All optional parameters of `biomod2` single models can be find and modified through the [BIOMOD_ModelingOptions](https://biomodhub.github.io/biomod2/reference/BIOMOD_ModelingOptions.html) function (see MAXENT.Phillips part).
I'm not very familiar with MAXENT parameters, but if it is not listed within this documentation, it means that it cannot be modified through `biomod2` for now.

Hope it helps,
Maya
