### ISSUE TITLE
Installation fails to get appropriate terra version

### ISSUE THREAD

**Issue by rpatin** [biomodhub/biomod2#159]
hello @rpatin 
i have a similar issue while trying to install the development version of biomod2. i used the devtools::install_github("biomodhub/biomod2", dependencies = TRUE) code but the package is not being installed. the warning begins with a message to install Rtools and indicates something about not being able to copy a file to some location. 

I'm running R as administrator and the documents folder (where the packages are installed into) is having full access permission. i wanted the development version as i ran into the 'TSS binary files not being created' which was fixed in this version. 
![image](https://user-images.githubusercontent.com/122000479/210710433-b66a626d-b12e-44b8-9726-00f59e947869.png)

please help,
best
Sandeep

_Originally posted by @sandeepB055 in https://github.com/biomodhub/biomod2/issues/137#issuecomment-1371809140_

**Comment by sandeepB055** [comment]
![image](https://user-images.githubusercontent.com/122000479/211756572-c212498c-7c5f-4644-84a5-a4914105c519.png)

@rpatin  this is the error message I'm getting when i tried the tips you mentioned. 
    what do i do?

**Comment by rpatin** [comment]
Hello @sandeepB055,
1. You have the following warning:
> Rtools is required to build R packages, but is not currently installed.

Thus, could you try to install Rtools (https://cran.r-project.org/bin/windows/Rtools/ - choose the version depending on your R version)

2. You have a second warning:
> package 'biomod2' is in use and will not be installed

Can you try to clean your environment first and detach the package with:
```
rm(list = ls()) # clean the environment
detach("package:biomod2", unload=TRUE)  
```

3. Next time, it would be great if you could copy-paste your error message rather than sending screenshot. It is both easier for us to have the text message (instead of having to write text again for google search for instance) and for other people to have the issue correctly referenced (people would be able to search for their error and find this issue, which is not posssible with an image)

Best,
Rémi
