### ISSUE TITLE
ascii grid conversion issue with maxent

### ISSUE THREAD

**Issue by DamienGeorges** [biomodhub/biomod2#16]
From Sebastian Kirchhof:

Hi, 
Here is what caused the error:
I entered grd files in biomod2 (for GLM, GAM, MAXENT.Phillips). In order to use
maxent, biomod2 converts them from grd to ascii - this process resulted in ascii
that were of slightly different extent then the input grd, but only for the grd
that were not from bioclim (in my case "croppedPETseason.grd",
"croppedPETcold.grd", "croppedPETwet.grd") .
I.e. instead of extent 33, 45, 3, 16 they changed to
33.000000001,45,3.00000000001,16 - that way they could not get stacked which
resulted in the error.
I now use only Maxent GUI.
Best, Sebi

**Comment by DamienGeorges** [comment]
Thanks for reporting! I will try to find a trick to prevent this strange beahviour. 
Damien

**Comment by chenqh0618** [comment]
hello, I got the same problem now.

maybe it could be solved by set a default format of ascii, as ascii is required for MaxEnt.
I tried `rasterOption(format="ascii")`, but it didn't work and cannot change the default format within the package.

Best, Chen
