### ISSUE TITLE
[rast] SRS do not match 

### ISSUE THREAD

**Issue by marianamurakami** [biomodhub/biomod2#162]
Hi!

When I run:
 myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                    proj.name = 'Current',
                                    new.env = myExpl,
                                    selected.models = 'all',
                                    metric.binary = 'all',
                                    metric.filter = 'all', 
                                    build.clamping.mask = TRUE)

I have this warning:
[rast] SRS do not match 

I am bit confuse, since I don't believe I have input any other srs than the one from myExpl object (the same I used to create myBiomodModelOut).

I believe I should make sure that there is not a mismatch between model srs and projection srs, but I am not sure about how to do it.

Can someone help me with that one, please?

**Comment by rpatin** [comment]
Hi @marianamurakami,
Thank you for reporting :pray: 

This should be a safe warning related to the internal code (I get the same warning when running `BIOMOD_Projection`).  I'll try to investigate what generates the warning but this should not be an issue for your results.

You can still check that your output have the same projection that your input:
```
rast::crs(myExpl, proj = TRUE)
rast::crs(get_predictions(myBiomodProj), proj = TRUE)
```
should both return the same projection.

Cheers,
Rémi

**Comment by marianamurakami** [comment]
Thank you very much for the reply, Rémi

Indeed both of them returned the same projection.

Thanks
and thanks all the team for biomod2, I love it xD
