### ISSUE TITLE
Error using BIOMOD_EnsembleModeling  em.by = 'all'

### ISSUE THREAD

**Issue by AidanJTM** [biomodhub/biomod2#163]
Hello,

I have been using biomod2 to model the distribution of great crested newts using presence and pseudo absence data. Since I updated the biomod2 package and adapted my code to include updates in of 25 October 2022 I have been having trouble getting the  BIOMOD_EnsembleModeling function to work when the em.by setting is set to ‘all’, ‘algo’ or  ‘PA_dataset+algo’ (it works fine with other em.by settings e.g. ‘PA_dataset’). 
 
I get a warning: 
 
mergedAlgo_mergedRun_mergedData ensemble modeling
   ! Additional projection required for ensemble models merging several pseudo-absence dataset...
 
And error message:
 
Error in { : 
  task 1 failed - "error in evaluating the argument 'obj' in selecting a method for function 'get_predictions': task 2 failed - "Argument eta must be a nonempty numeric vector""
 
Does anyone know what might be causing this error?
I can get the example in the biomod2 BIOMOD_EnsembleModeling vignette to work fine but that uses presence absence data so I was wondering if I was missing something out when using it with presence pseudo absence data.

Below I have included my code for BIOMOD_Modeling and BIOMOD_EnsembleModeling  after my updates. I would be very grateful if anyone could take a quick look to see if there is anything obvious that could be causing this problem.

#import presence/absence data

myResp_data` <- read.csv("pres100m_2017rare400_Kent_29112022.csv")
attach(myResp_data)
head(myResp_data)
myRespName <- "GCN"
myResp<-as.numeric(myResp_data[,myRespName])
myRespXY<- myResp_data[c("coords.x1","coords.x2")] 
 
 
#format data
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
expl.var = myExpl1,
resp.xy = myRespXY,
resp.name = myRespName,
PA.nb.rep = 1, 
PA.nb.absences = 10000,
PA.strategy = 'random')
 
myBiomodOptions <- BIOMOD_ModelingOptions()

myBiomodModelOut <- BIOMOD_Modeling(
  myBiomodData,
  modeling.id = 'AllModels',
  models = c("GAM", "GLM", "MARS", "GBM",  "FDA", "MAXENT.Phillips.2"), 
  bm.options = myBiomodOption,
  nb.rep=1,  
  data.split.perc=70, 
  weights=NULL,
  var.import=1,
  metric.eval = c("ROC", "TSS"),
  save.output = TRUE,
scale.models = TRUE,
  do.progress = TRUE)
 
 
 
myBiomodEM <- BIOMOD_EnsembleModeling(
  myBiomodModelOut,
  em.by = 'all',
  models.chosen = grep('Full',get_built_models(myBiomodModelOut), value = T),
  metric.select = c("ROC", "TSS"),# could only get model to work by including TSS as well
  metric.select.thresh = c(0.79,0.6),
  metric.eval = c("KAPPA", "TSS", "ROC"),
  prob.mean = T,
  prob.cv = F,
  prob.ci = F,
  prob.ci.alpha = 0.05,
  prob.median = F,
  committee.averaging = F,
  prob.mean.weight = F,
  prob.mean.weight.decay = 'proportional',
  var.import = 1)

Thanks,

Aidan

**Comment by rpatin** [comment]
Hello Aidan,
Thank you for reporting :pray: 
When you ask for a ensemble models with `em.by = 'PA_dataset+algo'`, `BIOMOD_EnsembleModeling` will build ensemble models for each combination of pseudo-absences dataset (`PA_dataset`) and model (`algo`, e.g. GLM, GAM, etc...). As you asked for only one cross-validation dataset (`nb.rep = 1` in `BIOMOD_Modeling`) only one model will be selected for each ensemble. This has two consequences:
- You are not really building ensemble models as the results is always the corresponding single model
- `biomod2` version 4.1-2 that you are likely using from CRAN is quite buggy when handling ensemble models with a single model and can crash easily (hence the bugs you encounter)

Now that it is said, you can:
- update `biomod2` to version `4.2-2` that was just published on CRAN. That way you should encounter less bugs related to ensemble models. (`install.packages('biomod2')`)
- build ensemble models that merge more than 1 model at a time (e.g. using `em.by = 'all'` - which is the same as `em.by = 'PA_dataset'`  as you have only one pseudo-absence dataset in your example)
- use more pseudo-absences dataset (`PA.nb.rep = 3` in `BIOMOD_FormatingData`) and/or crossvalidation dataset (`nb.rep = 3` in  `BIOMOD_Modeling`), to allow for ensemble models when `em.by = 'algo'` or `em.by = 'PA_dataset+algo'`. But it depends what you are looking for.

Feel free to let us know if something is still unclear or if you encounter further bugs.

Cheers,
Rémi
