### ISSUE TITLE
Error in BIOMOD_Modeling(myBiomodData, models = c("MARS", "GBM", "GAM",  :    unused arguments

### ISSUE THREAD

**Issue by Friepei** [biomodhub/biomod2#164]
Hello, 

I have troubles with biomod2 since I installed version 4.2.2
I used to be able to run my SDM and suddenly it gives me this error message:

Error in BIOMOD_Modeling(myBiomodData, models = c("MARS", "GBM", "GAM",  : 
  unused arguments (NbRunEval = 0, DataSplit = 80, Yweights = NULL, Prevalence = NULL, VarImport = 5, models.eval.meth = c("KAPPA", "TSS", "ROC"), SaveObj = TRUE, rescal.all.models = FALSE)

This is the script:
mySDMModel <- BIOMOD_Modeling(myBiomodData, 
                           models = c("MARS","GBM","GAM","MARS","CTA","ANN","SRE","FDA","RF","MAXENT.Phillips","MAXENT.Phillips.2"), 
                           NbRunEval = 3, 
                           do.full.models = FALSE,    
                           DataSplit = 80, 
                           Yweights = NULL, 
                           Prevalence = NULL,
                           VarImport = 5,     
                           models.eval.meth = c("KAPPA", "TSS", "ROC"),    #"AUC_PR" ?
                           SaveObj = TRUE,
                           rescal.all.models = FALSE,
                           modeling.id = "mySDMModel"
)

Could someone help me identify the problem?

**Comment by rpatin** [comment]
Hello @Friepei,
Thank you for reporting :pray: and sorry that the update caused you troubles.
There was a huge update that was made available last year on github and last november on CRAN, which changed quite a lot of argument name. You can find a standard `biomod2` workflow on the [website](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) which should help you when you get argument error.

Concerning your call to `BIOMOD_Modeling` the up-to-date argument would be:
```
mySDMModel <- BIOMOD_Modeling(myBiomodData,
                              models = c("MARS","GBM","GAM","MARS","CTA","ANN","SRE","FDA","RF","MAXENT","MAXNET"), # MAXENT.Phillips -> MAXENT ; MAXENT.Phillips.2 -> MAXNET
                              nb.rep = 3, # new name for NbRunEval
                              do.full.models = FALSE,
                              data.split.perc = 80, # new name for DataSplit
                              weights = NULL, # new name for Yweights
                              prevalence = NULL, # new name for Prevalence
                              var.import = 5, # new name for VarImport
                              metric.eval = c("KAPPA", "TSS", "ROC"), # new name for models.eval.meth
                              save.output = TRUE, # new name for SaveObj - although the argument isn't used yet
                              scale.models = FALSE, # new name for rescal.all.models 
                              modeling.id = "mySDMModel"
)
```

Cheers,
Rémi

**Comment by Friepei** [comment]
Hello Remi,

Thank you so much for your help.
I used the new script and the original error disappeared.
However, now i have the problem that I cannot built an Ensemble Model.
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.7),
                                      var.import = 3,
                                      metric.eval = c('TSS', 'ROC'),
                                      )
It gives the error that all models have failed but when i look at the
evaluation of the single models, most of them are above 0.9 for both TSS
and ROC.

Is there something wrong with my script?

Cheers,
Fredi



Am Di., 17. Jan. 2023 um 10:02 Uhr schrieb rpatin ***@***.***

**Comment by rpatin** [comment]
Hello Fredi,
Happy that your original error disappeared :+1:
Concerning the failed `BIOMOD_EnsembleModeling`, nothing looks wrong in the script. Could you copy-paste the console output with the error ? Ideally could you also send the output of `show(myBiomodModelOut)` ? 
Cheers,
Rémi

**Comment by Friepei** [comment]
Hello Remi,

Tahnk you for your help.
Here is the output:


> show(myBiomodModelOut)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Modeling folder : .

Species modeled : Hippocampus

Modeling id : AllModels

Considered variables : Bathy Cvel DO LB Phy Sub


Computed Models :  Hippocampus_PA1_allRun_GLM Hippocampus_PA1_allRun_GBM
Hippocampus_PA1_allRun_GAM Hippocampus_PA1_allRun_CTA
Hippocampus_PA1_allRun_ANN Hippocampus_PA1_allRun_SRE
Hippocampus_PA1_allRun_FDA Hippocampus_PA1_allRun_MARS
Hippocampus_PA1_allRun_RF Hippocampus_PA1_allRun_MAXNET


Failed Models :  none




> myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,+                                       models.chosen = 'all',+                                       em.by = 'all',+                                       metric.select = c('TSS'),+                                       metric.select.thresh = c(0.7),+                                       var.import = 3,+                                       metric.eval = c('TSS', 'ROC'),+                                       )
-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
! setting em.algo to its default value c('prob.mean')
   > Evaluation & Weighting methods summary :
      TSS over 0.7


     !! Ensemble Model mergedData_mergedRun_mergedAlgo selected by TSS
have no model selected and will fail.
     !! Please make sure this is intended or review your selection
metrics and threshold.

  > mergedData_mergedRun_mergedAlgo ensemble modeling
   ! No models kept due to threshold filtering... Ensemble Modeling will fail!
   ! Note :  Hippocampus_prob.meanByTSS_mergedData_mergedRun_mergedAlgo failed!

! All models failed




Am Do., 26. Jan. 2023 um 10:05 Uhr schrieb rpatin ***@***.***

**Comment by rpatin** [comment]
Hello Fredi,
It happen that you ran a model without cross-validation which we did not handle well in `BIOMOD_EnsembleModeling`.
This is now fixed so if you update to current github version, your code should now run without problem:
`devtools::install_github('biomodhub/biomod2')`
If not, please let us know what error you encounter.
Cheers,
Rémi

**Comment by Friepei** [comment]
Thank you so much!
It worked!
Anyhow, do you recommend to do a cross validation?
I have few presences (300) and a slight sample bias

Am Fr., 27. Jan. 2023 um 13:51 Uhr schrieb rpatin ***@***.***

**Comment by rpatin** [comment]
Hello Fredi,
Happy that it worked !

It is generally advised to have some kind of independent model evaluation, as evaluating the model on the same data that it was trained with will likely bias the evaluation. Best practice would be to have an independent (i.e. sampled independently) dataset of presence/absence to do the evaluation, however it is a rare situation. When such dataset are not available, you can split your own dataset to do cross-validation. Evaluation metrics from cross-validation dataset are more reliable than the one calculated on the training dataset.

If you feel that your model may suffer from the randomness of the cross-validation, you can also repet the splitting and train several model. This will give you an idea of the consistency of your evaluation and you can also imagine combining your models in a single ensemble model.

Hope this helps, and feel free to ask if you have additional questions.
Best,
Rémi
