### ISSUE TITLE
Fixed variables in bm_PlotResponseCurves()

### ISSUE THREAD

**Issue by Farewe** [biomodhub/biomod2#167]
Hello biomod team,

I have noticed in the new version of the response curve function that there is no more mention of using an argument "data_species", and the help files do not say how the fixed variables are calculated exactly. Are they calculated over the environmental values where the species is present, or over all environmental values in the input data?

[Looking at the code, it seems that the calculation is done over the species presence cells.](https://github.com/biomodhub/biomod2/blob/b468f9502ffd3e04b98df6f804aec1679c534972/R/bm_PlotResponseCurves.R#L202) Is this correct? If so, I would suggest to mention it in the help file (this is critical info to understand the curves!!).

**Comment by rpatin** [comment]
Hello Boris,
The documentation is indeed a bit scarce on the topic, sorry for the inconvenience :pray:  
When you do not give argument `data_species` to `bm_PlotResponseCurves`, then it is fixed to 1 for all data (in internal function `.bm_PlotResponseCurves.check.args`). So by default the fixed variables are calculated over all the environmental values available:
- over all presences and absences if you do not give argument `new.env`
- over all data present in argument `new.env` (all raster cells or all data.frame lines)

If you give argument `data_species` to `bm_PlotResponseCurves` (which you can, it will then only select the 1. I think however that the argument could be deleted as if you want to have mean/median/etc calculated only over your presences it is still possible when you give argument `new.env`. We will discuss that for later version.

I hope this is clearer now ?
Best regards,
Rémi

**Comment by Farewe** [comment]
Hi Rémi,

thanks for your answer. I tried to play with the data_species argument (without using `new.env`) but it did not change the shapes of curves at all.
I think it would be a great option to be able to specify that you want the mean/median calculated over presences only without using `new.env`. 

For example if your species has only 100 presences and if you decide to use a very large number of background points (e.g. 50000), then the calculation of the mean/median will tend towards the value over the entire study area, whereas if calculated on species presences, it may have a very different value capturing regional average/median (e.g., imagine a mountain species or an endemic species in Europe).

If I decide to use `new.env`, and for example provide a raster stack in input, how should `data.species` look like? A vector of presences over all cells of the study area? Or a matrix specifying coordinates of species presence points?

Cheers
Boris

**Comment by rpatin** [comment]
Hello Boris,
Happy to help!
With Gulo gulo example I have no problem using argument `data_species`:

1. with `data_species` set to 1 for every data (calculation over both presence and absence) - same as default behaviour.

```
myResponseCurve <- bm_PlotResponseCurves(myBiomodModelOut, 
                                         models.chosen = "GuloGulo_allData_RUN2_RF",
                                         fixed.Var = "mean",
                                         do.bivariate = FALSE,
                                         do.plot = TRUE,
                                         do.progress = FALSE, 
                                         data_species = rep(1, length(myResp)))
```
gives
![image](https://user-images.githubusercontent.com/8982316/213667192-4e4bb7b6-4d85-497d-9a1e-e0d6529572b0.png)

2. with `data_species` set to 1 only for presences (calculation of mean/median, etc... only on presences)
```
myResponseCurve <- bm_PlotResponseCurves(myBiomodModelOut, 
                                         models.chosen = "GuloGulo_allData_RUN2_RF",
                                         fixed.Var = "mean",
                                         do.bivariate = FALSE,
                                         do.plot = TRUE,
                                         do.progress = FALSE,
                                         data_species = myResp)
```
now gives:
![image](https://user-images.githubusercontent.com/8982316/213667160-d7f5d6a7-ac92-40cf-87ae-2c0addc6e636.png)


I you want to provide `new.env`, you can:

1. give a `data.frame` and  calculation will happen on all row
2. give a `data.frame` as well as argument `data_species` and then calculation of mean and median will happen only for cells selected by `data_species` (see example 2 above)
3. give a `raster/SpatRaster` and mean and median calculation will happen with all cells 
4. Right now you cannot give a `raster` and have mean/median calculation on a limited number of cells. For such case I would suggest to extract all data (or a random sample of sufficient size ) from the `raster` and add data for presence points. That way you can give a `data.frame` with all environmental values but allow the mean/median calculation to occurs only on presences by giving argument `data_species`.

These behaviour may change in the future to facilitate the calculation of mean/median only for a specific number of cells (typically presences) but for now I think that there are many options to play with, even though it may require some user intervention.

I hope the answer is clear. If not feel free to ask for examples for instance.
Cheers,
Rémi

**Comment by Farewe** [comment]
Ok I got it, I wrote `data.species` mechanically whereas the correct argument is `data_species`. 

Thank you, this small change is very important, it changes dramatically the curves!!
