### ISSUE TITLE
BIOMOD_PresenceOnly crashing at the end of a run

### ISSUE THREAD

**Issue by yucheols** [biomodhub/biomod2#169]
Hello!

I'm using the latest version of biomod2 (v4.2.2) installed from CRAN, and I've encountered an odd behavior of the function
"BIOMOD_PresenceOnly" when computing presence-only metrics of my model output

I used the following code:

 myMod_po <- BIOMOD_PresenceOnly(bm.mod = myModel,
                                                                bg.env = envs,
                                                                perc = 0.9,
                                                                save.output = T)

The object envs is in SpatRaster format as required, and the function ran all the way to the end just fine and the sign 
=-=-= DONE -=-=-= popped up on the console. But the run didn't end there and continued to run quite a bit longer, until finally  terminating with the following error message:

Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'resp/.BIOMOD_DATA/1674073255/presenceonly.evaluation_resp', probable reason 'No such file or directory'

Here, "resp" is the name I used for "resp.name" in BIOMOD_FormattingData
I wonder what could be causing this to happen?

Thanks for your help!
Yucheol

**Comment by rpatin** [comment]
Hello Yucheol,
Thank you for reporting :pray: 
And sorry that the communication from `BIOMOD_PresenceOnly` is slightly misleading. The first `=-=-= DONE -=-=-=` is linked to a call to `BIOMOD_Projection` that is needed when you provide `new.env`. If you do not have a second `=-=-= DONE -=-=-=`, then the proper calculation of Boyce Index and MPA have likely failed (or the saving of its output).

- Could you check whether folder `resp/.BIOMOD_DATA/1674073255` exists or not ?
- What code did you use to call  `BIOMOD_Modeling` ?
- What was the output of `BIOMOD_Modeling ? `show(myBiomodModelOut)`

Cheers,
Rémi

**Comment by yucheols** [comment]
Thank you for the quick response!
To answer your questions:

1) Yes, the folder exists containing other files (e.g., calib,lines, formated.input.data, etc)
2) I used the following code to call BIOMOD_Modeling
   
   okor_mod <- BIOMOD_Modeling(bm.format = myData,
                            models = c('GAM', 'GBM', 'SRE', 'FDA', 'RF', 'MAXENT'),
                            bm.options = myOptions,
                            data.split.table = cv.table,
                            prevalence = 0.5,
                            metric.eval = c('KAPPA', 'ROC', 'TSS'),
                            var.import = 5,
                            save.output = T,
                            do.progress = T)

3) The model output properly showed the path to a modeling folder, species modeled,
modeling ID, variables considered, names of all the computed models, and failed models (which there was none).
The modeling output looks alright. But I can send you the screenshot if you need it. I re-ran the model after flagging this issue. Everything's the same except I've changed names for several objects used for modeling.

That being said, I cannot find the file name mentioned in the error message in the folder (resp/.BIOMOD_DATA/1674073255)
But the folder itself is there.

Cheers,
Yucheol

**Comment by rpatin** [comment]
Thank you for the additional information :pray: 
Unfortunately I have no clue what might go wrong in `BIOMOD_PresenceOnly` (unless that it is not a big surprise as the function is quite unstable).
Would it be possible to have a look with your data and code so that I can reproduce the error and debug it more easily ?
Here is my mail: remi.patin@univ-grenoble-alpes.fr.
Thanks in advance,
Cheers,
Rémi

**Comment by yucheols** [comment]
Hello! I've been out of town for a few days and couldn't use my laptop. Sorry for the late response!
I'll organize my data and code and send it your way soon.

One other question: for this particular trial I used a set of target group background points sampled from a kernel density raster
representing the spatial sampling effort. This was initially for a different trial involving only Maxent, but I used it for the biomod trial. I included it as a "user.defined" pseudoabsences (since I didnt want to use the default random sampling method). When I printed out the formatted data, the background points were included as "true absences" (as they should be; although they are not in reality).

Could this be the reason for the crash? i.e. biomod2 recognizing this approach as presence-absence instead of presence-only (thus cannot calculate presence-only metrics)?

Best,
Yucheol

**Comment by rpatin** [comment]
Hello Yucheol,
Thank you for the update.
It could indeed have been an issue with 'user.defined' pseudo-absences. However I could not reproduce such issue on my end (`BIOMOD_PresenceOnly` based on a `BIOMOD_Modeling` output with user-defined pseudo-absences was working well)
However, I wonder how you defined your pseudo-absences. Could you share the code you used for `BIOMOD_FormatingData`. In particular, did argument `resp.var` had only 1 and NA ? If you filled in `resp.var` with 1 and 0, then the code will consider it as true absences. When using pseudo-absences (be it user defined or not), `BIOMOD_FormatingData` should not tell you about true absences but only `undefined points in dataset`.
Best,
Rémi

**Comment by yucheols** [comment]
Hi Remi,
I checked my code again and indeed I have made a mistake when preparing my PA table. I corrected it and now the output from BIOMOD_FormattingData is correctly showing that I have undefined points instead of true absences.
I'm running the model again at the moment. I'll let you know how it went!

Cheers,
Yucheol
