### ISSUE TITLE
check presence-data partitions in user.defined sampling strategy

### ISSUE THREAD

**Issue by gsilvaarias** [biomodhub/biomod2#17]
Hello everyone,

I am using Biomod2 to generate an SDM for a species with ~900 presence records.
I tried to generate the pseudoabsences with disk strategy but is too time-consuming. To solve that, I input a data.frame with my own sampled points to the `BIOMOD_FormatingData` function.
``` R
hali_data <- BIOMOD_FormatingData(resp.var = df_hali$hali,  ### 1 for presence and NA for pseudoabsences
                                  expl.var = b_sub,  ### raster stack of explanatory variables
                                  resp.xy = df_hali[,2:3],  ### coordinates presences and pseudoabsences
                                  resp.name = 'hali',
                                  PA.nb.rep = 5,  ### pseudoabsences sets
                                  PA.strategy = 'user.defined',
                                  PA.table = df_hali[,13:ncol(df_hali)])  ### TRUE/FALSE colums indicating which records use in each PA run
```
I also want to perform several evaluation runs using the arguments `NbRunEval` and `DataSplit` of the  `BIOMOD_Modeling` function. 
``` R
hali_models <- BIOMOD_Modeling(hali_data,
                               models = c('GLM','GAM','GBM','CTA','MARS','RF','MAXENT.Phillips'),
                               models.options = myBiomodOption,
                               NbRunEval = 5, DataSplit = 75, 
                               Prevalence = 0.5, VarImport = 10, models.eval.meth = c('TSS', 'ROC'), SaveObj=TRUE,
                               rescal.all.models = TRUE, do.full.models = FALSE, modeling.id = 'hali')
```
The modelling seems to be running ok and the `BIOMOD_Modeling` function is splitting the data.
I just want to find a way to check with detail the five sets presence data splitting. Where exactly Can I find this setting in any of the BIOMOD objects?

Thank you in advance.
Gustavo

**Comment by DamienGeorges** [comment]
The function `get_calib_lines()` should let you access this info.

`get_calib_lines` return an `array` (or a `data.frame`) having the same dimension than the output of `get_predictions()`. All lines containing `TRUE` have been used to calibrate the model, `FALSE` to evaluate the model, `NA` are not used

Hope that helps,
Damien

**Comment by gsilvaarias** [comment]
Hi,
many thanks. It helped.
