### ISSUE TITLE
Random Forest and sampsize

### ISSUE THREAD

**Issue by Oliveira-D-R** [biomodhub/biomod2#172]
I have some doubts about how to implement the down-sampling technique suggested by Valavi et al (https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1486) in Random Forest with Biomod.

I know that the technique consists of making the pseudo-absence number equal to the presence number. This must be changed in the "sampsize" option. But I'm not sure what value exactly to put in that argument.

Assuming I have 1000 occurrences of a species. Should I put the number 1000 in the "sampsize" argument? If I am working with a division in which 70% of these points are used as training and another 30% as testing, should I put the number 700 in "sampsize"?

I appreciate the attention of the whole team!

**Comment by rpatin** [comment]
Hi @Oliveira-D-R

I think the correct way would be to provide `sampsize = c(700,700)` if you want `randomForest` to sample 700 absences and 700 presences (i.e. all of the presences once accounting for cross-validation)

If you want e.g. 1000 absences and 700 presences you would need to provide `sampsize = c(1000,700)`

Cheers,
Rémi

**Comment by Oliveira-D-R** [comment]
Hello! @rpatin
Thanks for the answer!

**Comment by kostask84** [comment]
Hi @rpatin,

Sorry in advance if this is trivial, but in the BIOMOD_ModelingOptions function, regarding RF and the sampsize argument, is replacement = TRUE, as in the default option of the randomForest  function from the randomForest R package? If not, how can I change this so as to be completely in line with Valavi et al. (2021)? 

Thank you in advance for your time!

**Comment by rpatin** [comment]
Hi @kostask84,
As you can see by running `BIOMOD_ModelingOptions()`, the default modeling options that we use for `randomForest` are:
```
RF = list( do.classif = TRUE,
           ntree = 500,
           mtry = 'default',
           sampsize = NULL,
           nodesize = 5,
           maxnodes = NULL)
```

Additionally, the call we do to `randomForest` is the following: 
```
randomForest(formula = bm_MakeFormula(resp.name = resp_name
                                                          , expl.var = head(Data)
                                                          , type = 'simple'
                                                          , interaction.level = 0),
                                 data = Data[calib.lines, ],
                                 ntree = bm.options@RF$ntree, =
                                 importance = FALSE,
                                 norm.votes = TRUE,
                                 strata = factor(c(0, 1)),
                                 sampsize = unlist(ifelse(!is.null(bm.options@RF$sampsize), list(bm.options@RF$sampsize),  nrow(Data[calib.lines, ]))),
                                 nodesize = bm.options@RF$nodesize,
                                 maxnodes = bm.options@RF$maxnodes)
```

As you can see argument `replace` is not provided so it will use `randomForest` default value, i.e. `replace = TRUE`.
Best,
Rémi

**Comment by kostask84** [comment]
Hi @rpatin, thank you so much for your answer and for the clarification!

**Comment by BRamiroSanchez** [comment]
Hi @rpatin 

I'm also trying to implement RF down-sample following best guidelines by Valavi et al. (2021), with a user-defined k-fold spatial block cross-validation strategy. I have built my own CV.user.table for cross-validation using the blockCV R package. To match the resulting object from blockCV::cv_spatial() with the "calib.lines" object from biomod, I have made sure to rename the column names accordingly (i.e., "_allData_RUNx") . 

When I try to run biomod_Modeling() with the modified RF down-sample options, I get an error error regarding the sampsize argument:

-=-=-=--=-=-=- cluster1_allData_RUN4_RF 

Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...Error in randomForest.default(m, y, ...) : 
  sampsize can not be larger than class frequency
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found

My guess, after reading this thread and thread #267, is that I might not be specifying the correct number of samples (too many) after having split my data into folds for cross-validation. My intention is to always downsample to the minimum of presence/absence available in the k-fold. Below is an extract of my code:

# 4. k-fold CV data preparation
cur.blocks <- blockCV::cv_spatial(x = pa_data,
                      column = "Observed", # the response column
                      r = env_rasters,
                      k = 4,
                      size = blocksize, # size of the blocks in metres
                      hexagon = TRUE,
                      selection = "random", # random blocks-to-fold
                      iteration = 100, # find evenly dispersed folds
                      biomod2 = TRUE) # also create folds for biomod2

colnames(cur.blocks$biomod_table) <-  paste0("_allData","_RUN", 1:nb.of.folds) #nb.of.folds=4

# E.g. output from one fold data allocation
# train_0 train_1 test_0 test_1
# 1      95     219     33     63
# 2     102     200     26     82
# 3      76     209     52     73
# 4     111     218     17     64
# Please use cv_plot function to plot each fold.

head(cur.blocks)
     _allData_RUN1 _allData_RUN2 _allData_RUN3 _allData_RUN4
[1,]          TRUE         FALSE          TRUE          TRUE
[2,]          TRUE         FALSE          TRUE          TRUE
[3,]          TRUE         FALSE          TRUE          TRUE
[4,]          TRUE         FALSE          TRUE          TRUE
[5,]          TRUE         FALSE          TRUE          TRUE
[6,]          TRUE         FALSE          TRUE          TRUE

# 5. Biomod data preparation
run.data <- BIOMOD_FormatingData(resp.var = P.points, 
                                 expl.var = calib.env.data,
                                 resp.name = sp, 
                                 resp.xy = coorxy,
                                 PA.nb.rep = runs.PA, # runs.PA = 0 (I have presence-absence data)
                                 PA.nb.absences = nb.PA, # nb.PA = 0 (I have presence-absence data)
                                 PA.strategy = NULL,# Strategy of pseudoabsences selection
                                 PA.user.table = PA.table) # PA.table = NULL (I have presence-absence data)

# 6. Models calibration 
# Load cross-validation blocks
cur.blocks <- readRDS(paste0(initial.wd, "/data/", sp, "_blocks.RDS"))

model.runs <- BIOMOD_Modeling(bm.format = run.data, 
                              models =  c("GLM", "ANN","MARS", "GBM","FDA","RF","MAXNET"),
                              CV.strategy = "user.defined",
                              CV.user.table = cur.blocks,  # For the k-fold CV. Table generated in script no.8
                              var.import = 3, 
                              metric.eval = c("TSS", "ROC"), 
                              CV.do.full.models = FALSE, 
                              prevalence = NULL, 
                              scale.models = FALSE,
                              bm.options = BIOMOD_ModelingOptions(
                                GLM = list(myFormula = as.formula(paste(sp, "~" , paste(paste("poly(", colnames(run.data@data.env.var), ",2)", sep=""),
                                                                                        collapse = "+"), sep=""))
                                ),
                                GAM = list(algo= "GAM_mgcv",
                                           type = 's_smoother',
                                           method = "REML",  # recommended: might be the default already in gam
                                           k = 20
                                ),
                                GBM = list(n.trees = 50,
                                           bag.fraction = 0.75),
                                RF = list(myFormula = as.formula(as.factor(sp) ~ .),
                                          do.classif = TRUE,
                                          ntree = 1000,
                                          mtry = "default",
                                          sampsize =  c("0" = min(as.numeric(table(run.data@data.species))), "1" = min(as.numeric(table(run.data@data.species)))),
                                          replace = TRUE)
                              )
)


How could I specify in the sampsize argument the fact that the "total data" to calculate the minimum of 0/1 should actually be in relation to how the data is distributed in each fold? Currently, as the sampsize argument is, it doesn't take into account the data in each fold.

Thank you so much in advance for any help.

Kind regards,
Berta
