### ISSUE TITLE
bm_PlotEvalMean giving undefined colums selected error 

### ISSUE THREAD

**Issue by sandeepB055** [biomodhub/biomod2#173]
the function is giving undefined columns selected error only when i used group.by value as "model"

code used:
**bm_PlotEvalMean(bm.out = ProLau_models,
                metric.eval = c("ROC","TSS"), group.by = "model")**

Error in `[.data.frame`(scores, , group.by) : undefined columns selected

_algo, run, datase_t options seem to work fine and returns a graph as well.

**Comment by rpatin** [comment]
Hello @sandeepB055,
Thank you for reporting :pray: 
Can you give a bit more information on your error:
- what type of object is `ProLau_models` ?
- can you share a summary of `show(ProLau_models)` ?
- which version of `biomod2` are you currently using ?
Cheers,
Rémi
