### ISSUE TITLE
Changes in the output of get_evaluation

### ISSUE THREAD

**Issue by PaoloPatrizio** [biomodhub/biomod2#174]
Hello, 

once I run: 
```
# 3. Computing the models
myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = c('GLM', "ANN", "MAXENT", "RF"),
                                    bm.options = myBiomodOption,  # default (omitted)
                                    nb.rep=10,
                                    data.split.perc=70,
                                    weights=NULL,
                                    var.import=0,
                                    metric.eval = c('TSS', 'ROC', 'KAPPA', 'POD', 'FAR'),
                                    save.output = TRUE,
                                    scale.models = TRUE,
                                    do.full.models=FALSE)

###Models evaluations
myBiomodModelEval <- get_evaluations(myBiomodModelOut)
```
`get_evaluations` returns a table which has, above others, the following columns: "validation" and "evaluation". As I wasn't able to find any documentation explaining what this two columns represent, I'm wondering if the "validation" column in biomod2 4.2-2 (which I'm using) is equal to the "Testing.data" column in previous versions (when some of the original data is used for validation) and what "evaluation" stands for and also why it returns "NA" in that case.

Thanks for your help!

**Comment by rpatin** [comment]
Hello @PaoloPatrizio 
Thank you for reporting :pray: 
Indeed the output of get_evaluation have changed to have a more consistent behaviour.
It now always return three columns:
- calibration (metric calculated over the data used for the fit)
- validation (metric calculated over the cross-validation data - part of the original data that was not used in the fit)
- evaluation (metric calculated over the independent dataset that can be given to `BIOMOD_FormatingData`

The former column `Testing.data` generally contained what is now the `validation` column (but could contain metric calculated over `calibration` data in some situations). 

In the new behaviour the column for independent evaluation is always shown even when you did not provide such kind of data, hence the NA in your situation.

I hope this is clear now. If not, feel free to ask.

We will make sure to update the documentation in the next version, thank you for noticing.
Cheers,
Rémi
