### ISSUE TITLE
BIOMOD_Projection failing

### ISSUE THREAD

**Issue by marianamurakami** [biomodhub/biomod2#175]
Hi!

I am having issues to completely run my code. I believe it has to do with "BIOMOD_Projection" or "BIOMOD_EnsembleForecasting" as, as far as I could notice, these were the last steps taken (I am more prone to think it was BIOMOD_Projection) before error messages (with 16gb RAM computer I got an error message about not having enough RAM memory)/sessions failed (with 64gb RAM cluster the sessions fails).

Today the session failed after or during this step:
![image](https://user-images.githubusercontent.com/71078509/216994353-6840fb5a-a843-4d6d-b38f-77bdbb02739b.png)

Here is the code I am using:

  # Select the studied species
  myRespDF <- epif[,c(2,3,15)]
  
  myResp <- myRespDF[,3]
  myRespName <- "acianthera hygrophila"
  
  
  # Get corresponding XY coordinates
  myRespXY <- myRespDF[, c('LONG_X', 'LAT_Y')]

 # Current conditions
  myExpl <- 
    raster::stack(c(
      bio02 = 'bio02_2010.tif',
      bio03 = 'bio03_2010.tif',
      bio08 = 'bio08_2010.tif',
      bio09 = 'bio09_2010.tif',
      bio12 = 'bio12_2010.tif',
      bio13 = 'bio13_2010.tif',
      bio19 = 'bio19_2010.tif'))
  myExpl <- terra::rast(myExpl)
  
# Load environmental variables 126 2040
  myExplFuture126_2040 <- 
    raster::stack(c(
      bio02 = 'ssp126_meanbio02_2040.tif',
      bio03 = 'ssp126_meanbio03_2040.tif',
      bio08 = 'ssp126_meanbio08_2040.tif',
      bio09 = 'ssp126_meanbio09_2040.tif',
      bio12 = 'ssp126_meanbio12_2040.tif',
      bio13 = 'ssp126_meanbio13_2040.tif',
      bio19 = 'ssp126_meanbio19_2040.tif'))
  myExplFuture126_2040 <- terra::rast(myExplFuture126_2040)  

 #### PREPARE DATA AND PARAMETERS ####
 myBiomodData <- 
    BIOMOD_FormatingData(
      resp.name = myRespName,
      resp.var = myResp,
      expl.var = myExpl,
      resp.xy = myRespXY,
      PA.nb.rep = 12, #number of sets (repetitions) of pseudo-absence points that will be drawn = 12
      PA.nb.absences = 516, #set 3x presence points
      PA.strategy = 'random',
      filter.raster = TRUE
    )

  #### PARAMETERIZE MODELING OPTIONS ####
library(doParallel)
  cl <- makeCluster(8)
  doParallel::registerDoParallel(cl)
  
  # "GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "RF", "MAXENT"
  bm.tuning <- BIOMOD_Tuning(bm.format = myBiomodData, models = c("GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "RF", "MAXENT"), ME.env = myExpl, ME.n.bg = ncell(myExpl), ME.metric = 'AICc')
  
  stopCluster(cl)

# Get tuned modeling options
  myBiomodOptions <- bm.tuning$models.options
  
  
  #### RUN THE MODELS ####
  
  # Model single models
  
  myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                      bm.options = myBiomodOptions,
                                      modeling.id = myRespName,
                                      models = c("GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "RF", "MAXENT"),
                                      nb.rep = 10, #switch to 10 - number of runs
                                      data.split.perc = 80,
                                      # data.split.table = myBiomodCV,
                                      var.import = 3, #number of permutations to be done for each variable to estimate variable importance; switch to 3
                                      metric.eval = c('TSS','ROC'),
                                      nb.cpu = 8,
                                      do.full.models = FALSE, #whether models calibrated and evaluated over the whole dataset should be computed or not
                                      do.progress = T)

 #### ENSEMBLING ####
  
  # Model ensemble models
  
  myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                        models.chosen = "all",
                                        em.by = 'all',
                                        metric.select = c('TSS'), #only models with a tss higher than 0.7 will be in the ensemble
                                        metric.select.thresh = c(0.7),
                                        var.import = 3, #number of permutations
                                        metric.eval = c('TSS', 'ROC'),
                                        prob.mean = TRUE,
                                        prob.median = TRUE,
                                        prob.cv = TRUE, # coefficient of variantion: variability among models
                                        prob.ci = TRUE,
                                        prob.ci.alpha = 0.05, # use evaluation methods over this alpha
                                        committee.averaging = TRUE,
                                        nb.cpu = 8,
                                        prob.mean.weight = TRUE)

#### MAKING PROJECTIONS ####
  
  # Project single models
  
  myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                    proj.name = 'Current',
                                    new.env = myExpl,
                                    selected.models = 'all',
                                    metric.binary = 'all', #transform prediction values into binary values based on models evaluation scores obtained with the BIOMOD_Modeling function. Must be among all (same evaluation metrics than those of bm.mod)
                                    metric.filter = 'all', 
                                    build.clamping.mask = TRUE,
                                    nb.cpu = 4)
                                    # output.format='.grd') # A clamping mask is a binary raster layer that indicates which cells in the new environmental space are "clamped" to the presence/absence records used to train the model.
  
  
  # Project ensemble models (from single projections)
  myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                               bm.proj = myBiomodProj,
                                               selected.models = "all",
                                               metric.binary = 'all',
                                               nb.cpu = 4,
                                               metric.filter = 'all')

# Project ensemble models (building single projections)
  
  myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                               proj.name = 'CurrentEM',
                                               new.env = myExpl,
                                               selected.models = "all",
                                               metric.binary = 'all',
                                               nb.cpu = 4,
                                               metric.filter = 'all')

 #### FUTURE: COMPARE RANGE SIZES ####
  
  ##### SSP126
  # ssp126 2040: Project onto future conditions
  myBiomodProjectionFuture126_2040 <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                                        proj.name = 'Future126_2040',
                                                        new.env = myExplFuture126_2040,
                                                        models.chosen = 'all',
                                                        metric.binary = 'all',
                                                        nb.cpu = 4,
                                                        # output.format='.grd',
                                                        build.clamping.mask = TRUE)

# Load current and future binary projections
  CurrentProj <- terra::rast("acianthera.hygrophila/proj_Current/proj_Current_acianthera.hygrophila_TSSbin.tif")
  FutureProj126_2040 <- terra::rast("acianthera.hygrophila/proj_Future126_2040/proj_Future126_2040_acianthera.hygrophila_TSSbin.tif")

# Compute differences
  myBiomodRangeSize126_2040 <- BIOMOD_RangeSize(proj.current = CurrentProj, proj.future = FutureProj126_2040)

Any clues about what I am doing wrong?

Thanks in advance

Mariana

**Comment by yuliaUU** [comment]
It looks like it is not biomod2 issue: i can see that your Renvironment is using 37.5GiB of data  - so i think your PC cant handle so much data:?

**Comment by marianamurakami** [comment]
Hi Yulia

Thanks for your reply

It was a 64gb ram memory PC

I am not really familiar with this type of analysis, would you know the average computer specs I should be looking for?

Computer science folks told me it is an optimisation issue rather than hardware limitations, that's why I thought there was something wrong with the code or the function.

Any clues are welcome

**Comment by yuliaUU** [comment]
Yes, that is interesting that it cant run... have you tried first to run a code just upto the point when you do projections?
and then separately you can load your myBiomodModelOut and myBiomodEM using `[BIOMOD_LoadModels()](https://biomodhub.github.io/biomod2/reference/BIOMOD_LoadModels.html)`and do all the projections after?

**Comment by yuliaUU** [comment]
i would also suggest to use data frames rather then rasters: i think they occupy less space

**Comment by marianamurakami** [comment]
Hi Yulia

Thanks again for your help.

I was working on it throughout he week.

One thing I could do in order to run get the binary projections was ignore the step where I would project individual models and go straight to ensemble projection. I'm not sure if I could do it, but as anyway I was planning to use the ensemble of the models I thought it would be ok.

Also I am using lower resolution rasters and using rm() whenever it is possible.

Now I have a different issue: 
When the range size is calculated I have only zeros for the Stable1 (number of pixels where the spp is in the current and remains in the future conditions)

When I run it with the Gulo climatic data (just replacing the occurrences) it does not happen.

I have checked the crs of both current and future rasters and it seems to be the same.

Any clue?

**Comment by rpatin** [comment]
Hi Mariana,
So did the whole workflow worked better when lowering the resolution or did you still have memory issues ?

If I understood well:
1. when you project your ensemble model with current and future climatic data and compare the range size, you find no Stable1 pixel ?
2. when you project your ensemble model with your current climatic data and the climatic data from the Gulo gulo examples, then you find some Stable1 pixel ?

This can happen, because the climatic data we used in `biomod2` are rather old extraction of old RCP at horizon 2080. I would guess they are more than 10 years old, so climatic projection may have changed. To follow that lead, you would need to compare the climatic variables distribution the most important for your species (which you can get with `get_variables_importance`) for both future climate.

Additionally, did you look at the binary projection of your ensemble model ? (Both in current and future climate) to check that both distribution indeed do not match at all.

Cheers,
Rémi

**Comment by marianamurakami** [comment]
![acianthera_bin](https://user-images.githubusercontent.com/71078509/220098220-fe80bb43-9010-489c-8b4d-825ba334e611.png)

**Comment by rpatin** [comment]
I suppose on the left it is the binary projection with Gulo gulo climate data ?
And on the right the binary projection with your climate data ?

**Comment by rpatin** [comment]
I suppose on the left you have projection with your climate data under current climate. And on the right, projection under future climate.
What strikes me the most is that you have a very different distribution of 0, restricted to the south. I suppose this is due to the clamping mask. The clamping mask remove projection when environmental data are outside the range of the value used for fitting the models. I suppose it is an indication that some of the variables in the future climate are outside of the range used for the fit. If those are important variables it will be difficult to make predictions (you are likely extrapolating wildly), if those are secondary variables, then the clamping mask is too strict. I would suggest to try without using `build_clamping_mask = TRUE` and setting it to `FALSE` instead. At least for understanding what is happening right now.

**Comment by marianamurakami** [comment]
Sorry Remi
The green one is the current distribution and the grey one is the future one, both with 'my' climatic data (not Gullo).

I am testing again with a totally different species (I figured out that the species I was using may have a bias)

In the meanwhile, am I ok to skip the individual models projection and only run the ensemble ones instead?

**Comment by rpatin** [comment]
Hi Marianna, 
Thank you for the update. Then I suspect that there is a variable important for this species that is predicted outside the observed range (used for the fit) and that cause the species to be absent. You should look at the environmental variables affecting the most the predictions of your ensemble models. 

Then, once you have identified one or two important variables you should look at their distribution over the raster you use in current and future condition. And I would expect distributions to be different for future conditions between `biomod2` old RCP data and the SSP you are using. 

Do you see that also for other time horizon ?
Cheers,
Rémi

**Comment by marianamurakami** [comment]
The results I just showed you are from a species from which I had already predicted to be climatic displaced in the future (by climatic niche projections, if that makes sense), so I believe it 'matches' this projection.

I'll update you as soon as the analysis for the other species (not predicted as climatic displaced) finishes.

Thank you very much for all your help and for biomod2, it is great!

**Comment by marianamurakami** [comment]
Perfect!

**Comment by marianamurakami** [comment]
Hi Remi

I still have the same output with a different species (this one was not expected to have its climatic niche displaced):
these are the plots for:
 CurrentProj <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
  FutureProj <- get_predictions(myBiomodProjectionFuture, metric.binary = "TSS")
  x11()
  plot(CurrentProj)
  plot(FutureProj)
  
![image](https://user-images.githubusercontent.com/71078509/220284344-0b057f4b-98c8-4d47-aa77-71e85cc9d1dd.png)
  
  
This is the full code I used:
  library(biomod2)
  library(ggplot2)
  library(gridExtra)
  library(rasterVis)
  library(ecospat)
  library(dplyr)
  library(terra)
  
  
  ##### LOAD DATASET AND VARIABLES ####
  
  # Load species occurrences
  setwd('Documents/Chapter3-10')
  
  epif <- read.csv('vriesea_carinata.csv')
  # epif <- epif[,-1]
  
  epif$Pres <- 1
  
  # Select the studied species
  myRespDF <- epif[,c(8,7,14)]
  
  myResp <- myRespDF[,3]
  myRespName <- "vriesea carinata"
  
  
  # Get corresponding XY coordinates
  myRespXY <- myRespDF[, c('LONG_X', 'LAT_Y')]
  
  
  ### Load environmental variables for current and future conditions
  
  # Current conditions
  myExpl <- 
    raster::stack(c(
      bio02 = 'bio02_2010.tif',
      bio03 = 'bio03_2010.tif',
      bio08 = 'bio08_2010.tif',
      bio09 = 'bio09_2010.tif',
      bio12 = 'bio12_2010.tif',
      bio13 = 'bio13_2010.tif',
      bio19 = 'bio19_2010.tif'))
  myExpl <- terra::rast(myExpl)
  names(myExpl) <- c("bio02", "bio03", "bio08", 'bio09', 'bio12', 'bio13', 'bio19')
  names(myExpl)
  
  # Load environmental variables 126 2040
  myExplFuture126_2040 <- 
    raster::stack(c(
      bio02 = 'ssp126_meanbio02_2040.tif',
      bio03 = 'ssp126_meanbio03_2040.tif',
      bio08 = 'ssp126_meanbio08_2040.tif',
      bio09 = 'ssp126_meanbio09_2040.tif',
      bio12 = 'ssp126_meanbio12_2040.tif',
      bio13 = 'ssp126_meanbio13_2040.tif',
      bio19 = 'ssp126_meanbio19_2040.tif'))
  myExplFuture126_2040 <- terra::rast(myExplFuture126_2040)
  names(myExplFuture126_2040)
  names(myExplFuture126_2040) <- c("bio02", "bio03", "bio08")
  
    #### PREPARE DATA AND PARAMETERS ####
  
  setwd("Loop_outputs/") #set the folder where the outputs will be stored
  gc()
  
  
  # Format Data with true absences and create pseudo absences (3x the presence points)
  
  # Transform true absences into potential pseudo-absences
  myResp.PA <- ifelse(myResp == 1, 1, NA)
  
  # Format Data with pseudo-absences : random method
  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences = 1000,
                                       PA.strategy = 'random',
                                       filter.raster = T)
  
  myBiomodData
  plot(myBiomodData)  
  
  
  library(doParallel)
  cl <- makeCluster(8)
  doParallel::registerDoParallel(cl)
  
  time.seq <- system.time(
    bm.tuning <- BIOMOD_Tuning(models = c("GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "RF"), bm.format = myBiomodData, ME.env = myExpl, ME.n.bg = ncell(myExpl))
  )
  
  stopCluster(cl)
  
  myBiomodOptions <- bm.tuning$models.options
  
  
  DataSplitTable <- BIOMOD_CrossValidation(bm.format = myBiomodData,
                                           k = 2,
                                           nb.rep = 2,
                                           do.full.models = FALSE)
  
  myBiomodCV <- DataSplitTable
  head(myBiomodCV)
  
  
  # Model single models
  myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                      bm.options = myBiomodOptions,
                                      modeling.id = 'AllModels',
                                      nb.rep = 1,
                                      data.split.perc = 80,
                                      data.split.table = myBiomodCV,
                                      var.import = 3,
                                      metric.eval = c('TSS','ROC'),
                                      do.full.models = FALSE,
                                      nb.cpu = 8)
  # seed.val = 123)
  # nb.cpu = 8)
  myBiomodModelOut
  
  
  
  # Model ensemble models
  myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                        models.chosen = 'all',
                                        em.by = 'all',
                                        metric.select = c('TSS'),
                                        metric.select.thresh = c(0.7),
                                        var.import = 3,
                                        metric.eval = c('TSS', 'ROC'),
                                        em.algo = c('EMmean', 'EMcv', 'EMci', 'EMmedian', 'EMca', 'EMwmean'),
                                        EMci.alpha = 0.05,
                                        nb.cpu = 8)
  myBiomodEM
  
  
  # Project ensemble models (building single projections)
  myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                               proj.name = 'CurrentEM',
                                               new.env = myExpl,
                                               models.chosen = 'all',
                                               metric.binary = 'all',
                                               metric.filter = 'all',
                                               buid.clamping.mask=F,
                                               nb.cpu = 8)
  myBiomodEMProj
  plot(myBiomodEMProj)
  
  
  # Project onto future conditions
  myBiomodProjectionFuture <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                                         proj.name = 'Future',
                                                         new.env = myExplFuture126_2040,
                                                         models.chosen = 'all',
                                                         metric.binary = 'TSS',
                                                         build.clamping.mask = F,
                                                         nb.cpu = 8)
  plot(myBiomodEMProj)
  plot(myBiomodProjectionFuture)
  
  # Load current and future binary projections
  CurrentProj <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
  FutureProj <- get_predictions(myBiomodProjectionFuture, metric.binary = "TSS")
  x11()
  plot(CurrentProj)
  plot(FutureProj)
  
  # Compute differences
  myBiomodRangeSize <- BIOMOD_RangeSize(proj.current = CurrentProj, 
                                        proj.future = FutureProj)

**Comment by rpatin** [comment]
Hi Mariana,
Everything looks fine in the code. As I said before, I would suspect out-of-range prediction for an important variable.
Did you look at variable importance and response curves ? As well as temporal change in environmental conditions for the variable(s) of importance ? I can have a look if you want and if you share the data (you already have my mail).

**Comment by rpatin** [comment]
Hi Mariana,
And thank you for the additional information :pray: 
The problem here is likely because future condition for bio02 are way out of the range of current condition:
[env_changes.pdf](https://github.com/biomodhub/biomod2/files/10803013/env_changes.pdf)
Any model will have troubles predicting future distribution, when the future condition are nowhere near the current observed values.
Cheers,
Rémi
