### ISSUE TITLE
Errors in biomodhub.github.io

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#176]
I was running example in https://biomodhub.github.io/biomod2/

And the following lines gave errors:

1. `Error in .local(obj, ...) : unused argument (as.data.frame = TRUE)`
```
# Get evaluation scores & variables importance
get_variables_importance(myBiomodModelOut, as.data.frame = TRUE)
```
same for
```
# Get evaluation scores & variables importance
get_evaluations(myBiomodEM, as.data.frame = TRUE)
get_variables_importance(myBiomodEM, as.data.frame = TRUE)
```

Error message :  `Error in .local(obj, ...) : unused argument (as.data.frame = TRUE)`
I just removed teh argument and it worked

2. Error in .fun_testIfIn(TRUE, paste0("group.by[", i, "]"), group.by[i],  :

```
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'dataset'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'expl.var', 'dataset'))
```

this gives error: `Error in .fun_testIfIn(TRUE, paste0("group.by[", i, "]"), group.by[i],  : group.by[3] must be 'full.name', 'PA', 'run', 'algo' or 'expl.var `

same here:
```

# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodEM, group.by = 'model')
bm_PlotEvalBoxplot(bm.out = myBiomodEM, group.by = c('model', 'model'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('expl.var', 'model', 'model'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('expl.var', 'model', 'dataset'))
bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('model', 'expl.var', 'dataset'))
```

none of the functions work

3. No existing objects :file does not exist: GuloGulo/proj_Current/proj_Current_GuloGulo_TSSbin.grd

```
CurrentProj <- rast(here::here("GuloGulo/proj_Current/proj_Current_GuloGulo_TSSbin.grd"))
FutureProj <- rast(here::here("GuloGulo/proj_Future/proj_Future_GuloGulo_TSSbin.grd"))
```
Gives error: file does not exist: GuloGulo/proj_Current/proj_Current_GuloGulo_TSSbin.grd

I think the end should be .tif and not .grd

**Comment by rpatin** [comment]
Hi @yuliaUU,
Thank you for reporting and noticing the errors on the website :pray: 
We have likely missed updating the website to the new `biomod2` version...
Thanks to your remark, the tutorial is now corrected and should be working fine. If not feel free to let us know.
Cheers,
Rémi

**Comment by yuliaUU** [comment]
thanks a lot for all the work on this package!
