### ISSUE TITLE
BIOMOD_Projection uses more CPU than allowed

### ISSUE THREAD

**Issue by CarbonEd14** [biomodhub/biomod2#177]
Hi/Bonjour,

First, I would like to thank the authors for this amazing package.
I have encountered a weird problem: biomod2 seems to use way more many CPU than allowed during the projection.
As you can see below, I've set the numbers of CPU to 10.
`
CopAci_models_proj_current <- BIOMOD_Projection(
  bm.mod = CopAci_models,
  proj.name = "current",
  new.env = myExplCopAci,
  new.env.xy = NULL,
  models.chosen = "all",
  metric.binary = "TSS",
  metric.filter = NULL,
  compress = TRUE,
  nb.cpu = 10,
  build.clamping.mask = FALSE)
`
However, when looking at `htop`, biomod2 seems to be using more than 30 CPUs (we have 50 CPUs, 1 CPU = 100%), my username ends with **esn.**
![image](https://user-images.githubusercontent.com/25350320/217452912-8a908e90-54e7-4400-8942-2ec7b85837e4.png)

I've even removed the clamping mask process in order to use less power but it's still an enormous amount of CPU. 

If you have any ideas on how to effectively prevent biomod2 from using more than the chosen number of CPUs, I would really appreciate! I don't want to mess with the other analyzes of my lab. 

Thank you so much

**Comment by rpatin** [comment]
Bonjour,
Thank you for reporting :pray:

In `biomod2` you can parallelize computation by using argument `nb.cpu`, as you have done. In your example this makes `BIOMOD_Projection` project 10 models simultaneously (one model per CPU allocated).

In addition to that, there are implicit parallel computation that may be involved within the function called by `biomod2` making each of the 10 parallel process call additional cores. It may be through BLAS/LAPACK library for matrix computation, predict function that have been optimized for the different types of models involved ... But `biomod2` have no control over this kind of parallelization (and do not pass them any argument regarding that).

I would think that this is the reason behind what you observe. And unfortunately I have no good advice on how to reduce CPU usage in such situations (apart from decreasing `nb.cpu`). There may be system command or environmental variables that may limits CPU use by a R process (and sub-process), however after a quick check I did not see easy solution using that, but feel free to share the solution if you manage to make something working.

Hope this helps,
Bonne journée,
Rémi

**Comment by CarbonEd14** [comment]
Hey,

Thanks for the quick reply, now it's more clear. 
I have reduced the number of models from 10 to 6 and it seems much better now
