### ISSUE TITLE
How to move biomod2 folder with losing links? 

### ISSUE THREAD

**Issue by cwaldock1** [biomodhub/biomod2#178]
Hello, 

Is there a simple way to move the whole folder generated by a model run for a given species and then 'reassign' all the links to the models? I am trying to read in ensemble.model.out objects but get errors for the links. I found the link slots but it seemed a bit of a hack to reassign these, is there already a built in function?

Thanks again for a really useful package!

Best,
Conor

**Comment by MayaGueguen** [comment]
Hello Conor,

All links in `biomod2` objects are built from the folder where you launch your scripts at first.
Let's say your skeleton directories looks like this :
```
Documents/
   Work1/
   Work2/
   Work3/
```
And you ran your simulation within `Work3` for your Alpha species, then all links should be like `./Alpha/Alpha.mod.final.models.out` (so it is relative path, starting from the `Work3` folder). Meaning that you should be able to move all your `Alpha` folder within `Work1`, the link would remain unchanged, and the only condition would be to now run your commands from this `Work1` folder.

There is an additional parameter `dir.name` within the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function, corresponding to the initialization of all those links, defined by default to `.` meaning that all paths will be relative to the folder where you run your commands.

But there is at the time no function allowing you to redefine _a posteriori_ all the links of all objects of a simulation folder, so be careful if you define an absolute path within this parameter.

Hope it helps,
Maya
