### ISSUE TITLE
BIOMOD_ModelingOptions: MAXENT.Phillips.2 argument missing?

### ISSUE THREAD

**Issue by AnoukGlad** [biomodhub/biomod2#18]
Dear all, 

I step in an issue in the BIOMOD_modelingOptions. I wanted to use the new MAXENT.Philips.2 for my models, and I would like to custom some parameters. However the argument seem to be missing in the function. You will find below a reproducible example of  the error. 

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
 [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spdplyr_0.4.0 dplyr_0.8.5   maxnet_0.1.2  biomod2_3.4.6 raster_3.1-5  sp_1.4-2     

loaded via a namespace (and not attached):
 [1] nlme_3.1-147          lubridate_1.7.9       doParallel_1.0.15     RColorBrewer_1.1-2    tools_3.6.3           backports_1.1.7      
 [7] rgdal_1.4-8           R6_2.4.1              rpart_4.1-15          mgcv_1.8-31           spbabel_0.5.1         colorspace_1.4-1     
[13] nnet_7.3-14           withr_2.2.0           gbm_2.1.5             tidyselect_1.1.0      gridExtra_2.3         leaflet_2.0.3        
[19] compiler_3.6.3        mda_0.5               glmnet_4.0-2          cli_2.0.2             scales_1.1.1          checkmate_2.0.0      
[25] hexbin_1.28.1         randomForest_4.6-14   plotmo_3.5.7          PresenceAbsence_1.1.9 stringr_1.4.0         digest_0.6.25        
[31] dismo_1.1-4           jpeg_0.1-8.1          pkgconfig_2.0.3       htmltools_0.4.0       plotrix_3.7-8         htmlwidgets_1.5.1    
[37] rlang_0.4.6           rstudioapi_0.11       shape_1.4.4           generics_0.0.2        zoo_1.8-8             crosstalk_1.1.0.1    
[43] ModelMetrics_1.2.2.2  magrittr_1.5          Formula_1.2-3         Matrix_1.2-18         Rcpp_1.0.4.6          munsell_0.5.0        
[49] fansi_0.4.1           abind_1.4-5           lifecycle_0.2.0       stringi_1.4.6         pROC_1.16.2           MASS_7.3-51.6        
[55] plyr_1.8.6            recipes_0.1.12        grid_3.6.3            parallel_3.6.3        earth_5.1.2           crayon_1.3.4         
[61] rasterVis_0.48        lattice_0.20-41       splines_3.6.3         knitr_1.28            pillar_1.4.4          reshape2_1.4.4       
[67] codetools_0.2-16      stats4_3.6.3          glue_1.4.1            latticeExtra_0.6-29   data.table_1.12.8     png_0.1-7            
[73] vctrs_0.3.0           foreach_1.5.0         gtable_0.3.0          purrr_0.3.4           tidyr_1.0.3           reshape_0.8.8        
[79] assertthat_0.2.1      ggplot2_3.3.0         TeachingDemos_2.12    xfun_0.14             gower_0.2.1           prodlim_2019.11.13   
[85] class_7.3-17          survival_3.1-12       viridisLite_0.3.0     timeDate_3043.102     tibble_3.0.1          iterators_1.0.12     
[91] lava_1.6.7            ellipsis_0.3.1        caret_6.0-86          ENMeval_0.3.0         ipred_0.9-9    

DataSpecies <- read.csv(system.file("external/species/mammals_table.csv",
package="biomod2"))

myRespName <- 'GuloGulo'
# the presence/absences data for our species
myResp <- as.numeric(DataSpecies[,myRespName])
# the XY coordinates of species data
myRespXY <- DataSpecies[,c("X_WGS84","Y_WGS84")]
# load the environmental raster layers (could be .img, ArcGIS
# rasters or any supported format by the raster package)
# Environmental variables extracted from Worldclim (bio_3, bio_4,
# bio_7, bio_11 & bio_12)
myExpl = stack( system.file( "external/bioclim/current/bio3.grd",
package="biomod2"),
system.file( "external/bioclim/current/bio4.grd",
package="biomod2"),
system.file( "external/bioclim/current/bio7.grd",
package="biomod2"),
system.file( "external/bioclim/current/bio11.grd",
package="biomod2"),
system.file( "external/bioclim/current/bio12.grd",
package="biomod2"))

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
expl.var = myExpl,
resp.xy = myRespXY,
resp.name = myRespName)

 options_models<- BIOMOD_ModelingOptions(
  MAXENT.Phillips=list(path_to_maxent.jar = '/home/cistude',
               memory_allocated = 512,
               background_data_dir = 'default',
               maximumbackground = 'default',
               maximumiterations = 200,
               visible = FALSE,
               linear = TRUE,
               quadratic = TRUE,
               product = TRUE,
               threshold = TRUE,
               hinge = TRUE,
               lq2lqptthreshold = 80,
               l2lqthreshold = 10,
               hingethreshold = 15,
               beta_threshold = -1,
               beta_categorical = -1,
               beta_lqp = -1,
               beta_hinge = -1,
               betamultiplier = 1,
               defaultprevalence = 0.5), 
    MAXENT.Phillips.2 = 
   list(
     myFormula = NULL,
     regmult = 1,
     regfun =  maxnet.default.regularization
   ))

Error in BIOMOD_ModelingOptions(MAXENT.Phillips = list(path_to_maxent.jar = "/home/cistude",  : 
  argument inutilisé (MAXENT.Phillips.2 = list(myFormula = NULL, regmult = 1, regfun = maxnet.default.regularization))

If I do : 

showClass("BIOMOD.Model.Options")

I get the following where MAXENT.Phillips.2 option is present

Class "BIOMOD.Model.Options" [package "biomod2"]

Slots:
                                                                                                                                    
Name:                GLM               GBM               GAM               CTA               ANN               SRE               FDA
Class:              list              list              list              list              list              list              list
                                                                              
Name:               MARS                RF   MAXENT.Phillips MAXENT.Phillips.2
Class:              list              list              list              list

And if I do 
Print_Default_ModelingOptions()
 I get the following where MAXENT.Phillips.2 option is present

 Defaut modeling options. copy, change what you want paste it as arg to BIOMOD_ModelingOptions

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  'BIOMOD.Model.Options'  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

GLM = list( type = 'quadratic',
            interaction.level = 0,
            myFormula = NULL,
            test = 'AIC',
            family = binomial(link = 'logit'),
            mustart = 0.5,
            control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE) ),

GBM = list( distribution = 'bernoulli',
            n.trees = 2500,
            interaction.depth = 7,
            n.minobsinnode = 5,
            shrinkage = 0.001,
            bag.fraction = 0.5,
            train.fraction = 1,
            cv.folds = 3,
            keep.data = FALSE,
            verbose = FALSE,
            perf.method = 'cv',
            n.cores = 1),

GAM = list( algo = 'GAM_mgcv',
            type = 's_smoother',
            k = -1,
            interaction.level = 0,
            myFormula = NULL,
            family = binomial(link = 'logit'),
            method = 'GCV.Cp',
            optimizer = c('outer','newton'),
            select = FALSE,
            knots = NULL,
            paraPen = NULL,
            control = list(nthreads = 1, irls.reg = 0, epsilon = 1e-07, maxit = 200, trace = FALSE, mgcv.tol = 1e-07, mgcv.half = 15
, rank.tol = 1.49011611938477e-08, nlm = list(ndigit=7, gradtol=1e-06, stepmax=2, steptol=1e-04, iterlim=200, check.analyticals=0)
, optim = list(factr=1e+07), newton = list(conv.tol=1e-06, maxNstep=5, maxSstep=2, maxHalf=30, use.svd=0), outerPIsteps = 0, idLinksBases = TRUE
, scalePenalty = TRUE, efs.lspmax = 15, efs.tol = 0.1, keepData = FALSE, scale.est = fletcher, edge.correct = FALSE) ),

CTA = list( method = 'class',
            parms = 'default',
            cost = NULL,
            control = list(xval = 5, minbucket = 5, minsplit = 5, cp = 0.001, maxdepth = 25) ),

ANN = list( NbCV = 5,
            size = NULL,
            decay = NULL,
            rang = 0.1,
            maxit = 200),

SRE = list( quant = 0.025),

FDA = list( method = 'mars',
            add_args = NULL),

MARS = list( type = 'simple',
             interaction.level = 0,
             myFormula = NULL,
             nk = NULL,
             penalty = 2,
             thresh = 0.001,
             nprune = NULL,
             pmethod = 'backward'),

RF = list( do.classif = TRUE,
           ntree = 500,
           mtry = 'default',
           nodesize = 5,
           maxnodes = NULL),

MAXENT.Phillips = list( path_to_maxent.jar = '/home/cistude',
               memory_allocated = 512,
               background_data_dir = 'default',
               maximumbackground = 'default',
               maximumiterations = 200,
               visible = FALSE,
               linear = TRUE,
               quadratic = TRUE,
               product = TRUE,
               threshold = TRUE,
               hinge = TRUE,
               lq2lqptthreshold = 80,
               l2lqthreshold = 10,
               hingethreshold = 15,
               beta_threshold = -1,
               beta_categorical = -1,
               beta_lqp = -1,
               beta_hinge = -1,
               betamultiplier = 1,
               defaultprevalence = 0.5),

 MAXENT.Phillips.2 = 
   list(
     myFormula = NULL,
     regmult = 1,
     regfun = <function>
   )
)

This argument  MAXENT.Phillips.2 is also describe in https://www.rdocumentation.org/packages/biomod2/versions/3.4.6/topics/BIOMOD.Model.Options-class

However, the argument seems to be missing in the function: 

BIOMOD_ModelingOptions

function (GLM = NULL, GBM = NULL, GAM = NULL, CTA = NULL, ANN = NULL, 
    SRE = NULL, FDA = NULL, MARS = NULL, RF = NULL, MAXENT.Phillips = NULL) 

The creation of models when no specifics options are set for  MAXENT.Phillips.2 works prefectly well with my data.

Thank you a lot for your help, 

Anouk Glad

**Comment by DamienGeorges** [comment]
Hi,
As you mentioned MAXENT.Phillips.2 is still uder development phase and only default options are supported so far.
I hope to find time to implement model tuning for this algo in a near future.
I let this issue open then.

Damien

**Comment by AnoukGlad** [comment]
Thanks for your response, I am looking forward this new option in the next version of Biomod2.
