### ISSUE TITLE
Model Evaluation for presence only models

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#180]
Hi,

Sorry if this is a stupid question, but I am not sure why I get a different evaluation metrics for presence only (PO) model with use of pseudo-absences(PA). I thought since the PO such a SRE wont be affected by the PA choice:

Here is a code to reproduce what I see:
```
library(biomod2)
library(terra)
library(tidyverse)
# Load species occurrences (6 species available)
data("DataSpecies")

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
data("bioclim_current")
myExpl <- rast(bioclim_current)

#Transform true absences into potential pseudo-absences
myResp.PA <- ifelse(myResp == 1, 1, NA)
# Format Data with pseudo-absences : random method
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences =1000,
                                       PA.strategy = 'random')

myBiomodOption <- BIOMOD_ModelingOptions(SRE = list(quant = 0.05))

myBiomodModelOut <- BIOMOD_Modeling(
  myBiomodData,
  models = "SRE",
  bm.options = myBiomodOption,
  nb.rep = 2,
  data.split.perc = 70,
  weights = NULL,
  var.import = 0,
  metric.eval = c('ROC', 'TSS'),
  save.output = TRUE,
  scale.models = FALSE,
  do.full.models = TRUE
)

# Evaluate models with Boyce index and MPA
myBiomodPO <- BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut)
myBiomodPO |>  filter(metric.eval=="ROC")

```
what I see is the following output:
![image](https://user-images.githubusercontent.com/54612866/218176378-3004ca5b-6d94-4a11-bfb7-421df355b789.png)

I would expect all evaluation metrics be the same, but this is not the case here for the same run since SRE is a presence only model: thus choice of PA should not affect it at all.

**Comment by yuliaUU** [comment]
also noticed that output of `myBiomodPO` is identical to Presence -absence model evaluation:
```
myBiomodModelEval <- get_evaluations(myBiomodModelOut)
myBiomodModelEval|>  filter(metric.eval=="ROC")
```
![image](https://user-images.githubusercontent.com/54612866/218178605-c2982e3c-1fa7-4c2c-b2cd-c8026e0820bc.png)

**Comment by rpatin** [comment]
Hi @yuliaUU,
Thank you for reporting :pray: 
- `BIOMOD_PresenceOnly` calculates evaluation metrics using only presence data, such as the Boyce Index and MPA. It outputs a table with both Presence-Absence evaluation metric (previously calculated ROC, TSS ...) and Presence-Only evaluation metric (Boyce Index and MPA). If you filter the table only for ROC, it is expected to give the same results as `get_evaluations`
- `SRE` are indeed models that use only presence for model fit. In `biomod2` they are however given absences or set of pseudo-absences that are used only for evaluation (to calculate the ROC for instance). And the different pseudo-absences dataset will change the ROC evaluation metric despite the `SRE` models being identical as they are based on the same presences. If you show the Presence-Only evaluation metric you should however see identical Boyce Index between PA1_RUN1 and PA2_RUN2, as those metric do not use the PA dataset.

Hope this helps,
Rémi

**Comment by yuliaUU** [comment]
Oh ! I see! thank you a lot for detailed explanations!

**Comment by yuliaUU** [comment]
`BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut)` I don't see any column with Boyce Index?
```

> colnames(myBiomodPO)
 [1] "full.name"   "PA"          "run"         "algo"        "metric.eval" "cutoff"      "sensitivity"
 [8] "specificity" "calibration" "validation"  "evaluation" 
```

**Comment by yuliaUU** [comment]
the Boyce metrics are close but not identical 
![image](https://user-images.githubusercontent.com/54612866/218517853-0829511c-bf5a-4711-91f4-1b3231720b24.png)

**Comment by rpatin** [comment]
Hi @yuliaUU 
Sorry I answered too fast last time. As repetition (RUN1 & RUN2) involve different cross-validation dataset it is expected that all metrics are different, as the presence data involved in calibration & validation will be different.
Even between PA1_RUN1 and PA2_RUN1 you should have different presence selected in calibration and validation dataset.

**Comment by yuliaUU** [comment]
Interesting! I thought when I specify `data.split.perc = 70,` it generates identical datasets for RUN1 or any PA version or modelling algorithm. At least it was like that it previous biomod version. is there a way to make it fixed (e.g. between PA1_RUN1 and PA2_RUN1 I want to have same datasets for calibration and validation). otherwise I cant really compare the model performance since it is tested on completely different dataset .

**Comment by rpatin** [comment]
Actually, when you specify cross-validation table with `data.split.table` argument in `BIOMOD_Modeling`, the cross-validation table are identical between pseudo-absences dataset. This is something that will be improved in the next `biomod2` version but for now you can use it as it is. You just have to prepare the cross-validation manually with `BIOMOD_CrossValidation`.

However, note that despite the different calibration/validation dataset PA1_RUN1 and PA2_RUN2 are still based on the same presences. Thus, they should have many presences in common so your comparison is still valid, although it also account for the randomness of selecting only 70% of your presences for the fit.
