### ISSUE TITLE
Error while triggering BIOMOD_Modeling: "Error in { : task 1 failed - "object 'expl_var_names' not found"

### ISSUE THREAD

**Issue by rahulkgour** [biomodhub/biomod2#182]
## We have generated CV folds, using `cv_spatial` through blockCV package first.
scv1 <- cv_spatial(
  x = pa_data,
  column = "occ", # the response column (binary or multi-class)
  r = rasters,
  k = 5, # number of folds
  size = 1000, # size of the blocks in metres
  selection = "random", # random blocks-to-fold
  iteration = 50, # find evenly dispersed folds
  progress = FALSE, # trun off progress bar
  biomod2 = TRUE, # also create folds for biomod2
  raster_colors = terrain.colors(10, rev = TRUE) # options from cv_plot for a better colour contrast
) 

# Now using `blockCV` in `biomod2` package
library(biomod2)
DataSpecies <- points
myRespName <- "occ"
myResp <- as.numeric(DataSpecies[,myRespName])
myRespXY <- DataSpecies[,c("x","y")]
RasterValues <- terra::extract(rasters, pa_data, df = TRUE, ID = FALSE)

# 1. Formatting Data
myResp.PA <- ifelse(myResp == 1, 1, NA)
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                     expl.var = RasterValues,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                      PA.nb.rep = 1,
                                      PA.nb.absences = 1000,
                                      PA.strategy = 'random',
                                      na.rm = TRUE)

# 2. Defining the folds for DataSplitTable
DataSplitTable <- scv1$biomod_table

# 3. Defining Models Options using default options.
myBiomodOption <- BIOMOD_ModelingOptions()

# 4. Model fitting
myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = c('GLM','MARS','MAXENT'),
                                    bm.options = myBiomodOption,
                                    data.split.table = DataSplitTable, # blocking folds
                                    var.import = 0,
                                    metric.eval = c('ROC'),
                                    do.full.models = TRUE,
                                    modeling.id="test")

### **I am pasting the whole output below which is copied from console:**

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Checking Models arguments...

! User defined data-split table was given -> nb.rep, data.split.perc and do.full.models argument will be ignored
Creating suitable Workdir...

	> Automatic weights creation to rise a 0.5 prevalence

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= occ Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 11  environmental variables ( ID diffNDVI dist_road dist_settle precip temp twi vappres windspeed aspect slope )
Number of evaluation repetitions : 5
Models selected : GLM MARS MAXENT 

Total number of model runs: 15 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

-=-=-=- Run :  occ_allData 

-=-=-=--=-=-=- occ_allData_RUN1 
**Warning in .bm_RunModel.check.args(model, Data, bm.options, calib.lines,  :
  occ GLM was switched off because of no both presences and absences data given
Warning in .bm_RunModel.check.args(model, Data, bm.options, calib.lines,  :
  occ MARS was switched off because of no both presences and absences data given
Warning in .bm_RunModel.check.args(model, Data, bm.options, calib.lines,  :
  occ MAXENT was switched off because of no both presences and absences data given
Error in { : task 1 failed - "object 'expl_var_names' not found"**

**Comment by rahulkgour** [comment]
Dear Rémi @rpatin,

We are actually stuck because of this error, earlier with the old version of bimod2 package - we were able to produce results. Due to requirement change we we are running the things again, but we are facing show stopper as mentioned in the earlier message. Can you please look into it, as we need to finish our analysis soon.

Thanks in advance.
Regards,
Rahul

**Comment by rpatin** [comment]
Dear Rahul,
Thank you for reporting and sorry for the inconvenience :pray: 

It seems that your models crashed because the Cross-validation table did not leave presences or absences in some of the dataset.

Could you send some additional information to check this idea:
- What is the output of `show(myBiomodData)` ?
- What is the output of the following commands: (none of them should show zeros in any cells)
```
table(DataSplitTable[,1], points$occ)
table(DataSplitTable[,2], points$occ)
table(DataSplitTable[,3], points$occ)
table(DataSplitTable[,4], points$occ)
table(DataSplitTable[,5], points$occ)
```

In case your cross-validation looks ok (all of the table have no zero), it will be easier for me to help you if you can send me the code and data that you are using (remi.patin@univ-grenoble-alpes.fr) so that I can reproduce your error.

Best regards,
Rémi

**Comment by rahulkgour** [comment]
Dear Rémi @rpatin,
Thanks for your quick response, really appreciate.

Please find the asked information below:

- **Output of show(myBiomodData)**

> show(myBiomodData)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  occ

	 293 presences,  0 true absences and  0 undefined points in dataset


	 11 explanatory variables

       ID         diffNDVI          dist_road         dist_settle         precip     
 Min.   :  1   Min.   :-0.04547   Min.   :   3.751   Min.   :   0.0   Min.   :138.7  
 1st Qu.: 74   1st Qu.: 0.19329   1st Qu.: 169.810   1st Qu.: 861.3   1st Qu.:145.6  
 Median :147   Median : 0.28578   Median : 392.424   Median :1435.5   Median :153.6  
 Mean   :147   Mean   : 0.25785   Mean   : 497.607   Mean   :1596.3   Mean   :153.4  
 3rd Qu.:220   3rd Qu.: 0.33279   3rd Qu.: 720.727   3rd Qu.:2191.0   3rd Qu.:158.2  
 Max.   :293   Max.   : 0.39638   Max.   :1726.802   Max.   :5430.6   Max.   :187.6  
      temp            twi            vappres        windspeed         aspect      
 Min.   :23.32   Min.   : 4.576   Min.   :1.836   Min.   :1.535   Min.   : 11.58  
 1st Qu.:24.10   1st Qu.: 6.164   1st Qu.:1.907   1st Qu.:1.588   1st Qu.: 97.07  
 Median :24.39   Median : 6.814   Median :1.923   Median :1.610   Median :165.42  
 Mean   :24.37   Mean   : 6.970   Mean   :1.924   Mean   :1.609   Mean   :173.20  
 3rd Qu.:24.66   3rd Qu.: 7.620   3rd Qu.:1.941   3rd Qu.:1.633   3rd Qu.:252.38  
 Max.   :25.53   Max.   :12.514   Max.   :1.993   Max.   :1.679   Max.   :341.93  
     slope        
 Min.   : 0.9758  
 1st Qu.: 2.9204  
 Median : 5.1227  
 Mean   : 6.7761  
 3rd Qu.: 9.0027  
 Max.   :26.3905 


- **Output of the following commands**

table(DataSplitTable[,1], points$occ)
table(DataSplitTable[,2], points$occ)
table(DataSplitTable[,3], points$occ)
table(DataSplitTable[,4], points$occ)
table(DataSplitTable[,5], points$occ)

> table(DataSplitTable[,1], points$occ)
       
          1
  FALSE  60
  TRUE  233
> table(DataSplitTable[,2], points$occ)
       
          1
  FALSE  57
  TRUE  236
> table(DataSplitTable[,3], points$occ)
       
          1
  FALSE  58
  TRUE  235
> table(DataSplitTable[,4], points$occ)
       
          1
  FALSE  58
  TRUE  235
> table(DataSplitTable[,5], points$occ)
       
          1
  FALSE  60
  TRUE  233


I can see there are no zero values, let me know if I need to share the data including explanatory variables to your email.

**Comment by rpatin** [comment]
Dear Rahul,
Thank you for the additional information, code and data :pray: 
The issue here is that you have only presence data and the models needs to have either absences or pseudo-absences.
You can see that when you see the summary of `BIOMOD_FormatingData`:
`293 presences,  0 true absences and  0 undefined points in dataset`
This indicates that the dataset have only presences, no absences and no pseudo-absences.
Additionally, running `BIOMOD_FormatingData` should have had the following message:
```
   > random pseudo absences selection
Unsupported case yet!
   ! PA selection not done
```
Indicating that the pseudo-absence selection was not done.

The issue is that you gave `BIOMOD_FormatingData` only presences and no `NA` so there are no option to sample pseudo-absences. 

Alternatively you can give to `BIOMOD_FormatingData`, the argument `expl.var` as a `RasterStack` (or `SpatRaster`), for instance the object `rasters` that you defined. With that the function will be able to sample pseudo-absences. However, you then need to define your cross-validation _after_ sampling the pseudo-absences. Here is what it would look like:

```
# Step 1. Define pseudo absences

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                     expl.var = rasters,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                     PA.nb.rep = 1,
                                     PA.nb.absences = 1000,
                                     PA.strategy = 'random',
                                     na.rm = TRUE)

show(myBiomodData)

# Step 2. Extract presence+pseudo-absence from biomod.formated.data object
myPoints <- cbind(myBiomodData@data.species, myBiomodData@coord)
colnames(myPoints) <- c("occ","x","y")
pa_data <- sf::st_as_sf(myPoints, coords = c("x", "y"), crs = 4326)

# Step 3. run crossvalidation
scv1 <- cv_spatial(
  x = pa_data,
  column = "occ", # the response column (binary or multi-class)
  r = rasters,
  k = 5, # number of folds
  size = 1000, # size of the blocks in meters
  selection = "random", # random blocks-to-fold
  iteration = 50, # find evenly dispersed folds
  progress = FALSE, # turn off progress bar
  biomod2 = TRUE, # also create folds for biomod2
  raster_colors = terrain.colors(10, rev = TRUE) # options from cv_plot for a better colour contrast
)


DataSplitTable <- scv1$biomod_table
myBiomodOption <- BIOMOD_ModelingOptions()



# Step 4. Model fitting

myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = c('GLM','MARS','MAXENT'),
                                    bm.options = myBiomodOption,
                                    data.split.table = DataSplitTable, # blocking folds
                                    var.import = 0,
                                    metric.eval = c('ROC'),
                                    do.full.models = TRUE,
                                    modeling.id = "test")
```

You can check with `show(myBiomodData)` that your formated data have both presence and absence.
However note that this may be more complicated if you want to have several pseudo-absence dataset.
Also note that in the future we will likely provide function to facilitate step 2, improve the error system to alert you when no absences are present in your data and also work on our cross-validation method.

Best regards,
Rémi

**Comment by rahulkgour** [comment]
Dear Rémi @rpatin,

We are really grateful for your help and timely support. Thank you so much, now I can see the code running without any error.

I think, we can close this ticket.

Thanks and regards,
Rahul

**Comment by rahulkgour** [comment]
Dear Rémi @rpatin,

While projecting the model we are getting the below error.

> file.proj <- paste0(myRespName, "/proj_Current/", myRespName, ".Current.projection.out") 
> if (file.exists(file.proj)) {
  myBiomodProj <- get(load(file.proj))
} else {
BIOMOD_models_proj_current <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
proj.name = 'Current',
new.env = rasters,
models.chosen = 'all')
}

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Building clamping mask

	> Projecting occ_PA1_RUN1_GLM ...
	> Projecting occ_PA1_RUN1_MARS ...
	> Projecting occ_PA1_RUN1_MAXENT ...
	> Projecting occ_PA1_RUN2_GLM ...
	> Projecting occ_PA1_RUN2_MARS ...
	> Projecting occ_PA1_RUN2_MAXENT ...
	> Projecting occ_PA1_RUN3_GLM ...
	> Projecting occ_PA1_RUN3_MARS ...
	> Projecting occ_PA1_RUN3_MAXENT ...
	> Projecting occ_PA1_RUN4_GLM ...
	> Projecting occ_PA1_RUN4_MARS ...
	> Projecting occ_PA1_RUN4_MAXENT ...
	> Projecting occ_PA1_RUN5_GLM ...
	> Projecting occ_PA1_RUN5_MARS ...
	> Projecting occ_PA1_RUN5_MAXENT ...
**Error in { :
task 1 failed - "no applicable method for 'predict' applied to an object of class "SpatRaster""**
