### ISSUE TITLE
Parallelization issue with projecting 

### ISSUE THREAD

**Issue by ellalewi547** [biomodhub/biomod2#183]
Hello, I am attempting to project individual models on a new environment. 
The projection has run the first two repetitions RUN1 PA1 GLM and GAM. However it has stopped loading after these two even though it says that its still loading. When I have stopped the model from running, it has come up with this message: 
2: In BIOMOD_Projection(bm.mod = myBiomodModelOut, new.env = myExpl2,  :
  Parallelisation with `foreach` is not available for Windows. Sorry.

Do you know what this suggests? 

I have 138GB of storage left?

**Comment by MayaGueguen** [comment]
Hello Ella,

The warning just indicates you that the projection have not been parallelized and have been run one after another.

As for why the projection stop : 
- 138GB is the size of your storage, it indicates how much space you have to store the data you will produce
- but what is of interest here for you is the size of your RAM, meaning memory your computer can have access to when processing calculation. _For example, on my computer, I have 64GB of RAM, which is quite fine._ 
 
Most of the time, projections fail when you do not have enough RAM memory : your map must me too large ie your resolution too high. You can try to reproject your maps onto a broader resolution and see if it works.
You can also check while the projection is running how much of your computer resources you are using with the Windows Task Manager, to see how much of your RAM you are using.

Hope it helps,
Maya

**Comment by ellalewi547** [comment]
Hi Maya, thank you for getting back to me so quickly. 
I have cut down the projection area to alot smaller so I can run the model. 
Thank you!
