### ISSUE TITLE
Error while invoking BIOMOD_Projection: Error in { : task 1 failed - "no applicable method for 'predict' applied to an object of class "SpatRaster""

### ISSUE THREAD

**Issue by rahulkgour** [biomodhub/biomod2#184]
Dear Rémi @rpatin,

While projecting the model we are getting the below error.

file.proj <- paste0(myRespName, "/proj_Current/", myRespName, ".Current.projection.out")
if (file.exists(file.proj)) {
myBiomodProj <- get(load(file.proj))
} else {
BIOMOD_models_proj_current <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
proj.name = 'Current',
new.env = rasters,
models.chosen = 'all')
}
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> Building clamping mask

> Projecting occ_PA1_RUN1_GLM ...
> Projecting occ_PA1_RUN1_MARS ...
> Projecting occ_PA1_RUN1_MAXENT ...
> Projecting occ_PA1_RUN2_GLM ...
> Projecting occ_PA1_RUN2_MARS ...
> Projecting occ_PA1_RUN2_MAXENT ...
> Projecting occ_PA1_RUN3_GLM ...
> Projecting occ_PA1_RUN3_MARS ...
> Projecting occ_PA1_RUN3_MAXENT ...
> Projecting occ_PA1_RUN4_GLM ...
> Projecting occ_PA1_RUN4_MARS ...
> Projecting occ_PA1_RUN4_MAXENT ...
> Projecting occ_PA1_RUN5_GLM ...
> Projecting occ_PA1_RUN5_MARS ...
> Projecting occ_PA1_RUN5_MAXENT ...

**Error in { :
task 1 failed - "no applicable method for 'predict' applied to an object of class "SpatRaster""**

**Comment by rahulkgour** [comment]
I did try the function with below code as well, unfortunately I can still see the same error.

> BIOMOD_models_proj_current <- 
  BIOMOD_Projection(
    bm.mod = myBiomodModelOut,
    new.env = rasters,
    proj.name = "Current",
    binary.meth = "ROC",
    output.format = ".img",
    do.stack = FALSE,
    build.clamping.mask = FALSE
  )


Even I also converted the raster stack 'rasters' into a SpatRaster using 'terra::rast()' function and tried for new.env argument, but in that case as well I received the same error.

**Comment by rahulkgour** [comment]
Dear Rémi @rpatin,

I would like to have your help in rectifying this issue, we are yet to finish our trail run to get ensemble models. But we are stuck during projection stage. 

Thanks in advance,
Rahul

**Comment by MayaGueguen** [comment]
Hello Rahul,

Thank you for reporting :pray: 
Here is a kind reminder :sun_with_face: We are trying our best to maintain and improve `biomod2`, while answering in the best way we can all the related issues. Be sure that we are reading all messages, but we have other attributions and projects to work on, and we try to answer as fast as we can :) 

Thanks in advance,
Maya

**Comment by rpatin** [comment]
Dear Rahul,
Unfortunately, I did not manage to reproduce the issue yet.
Could you share the output of:
1. `sessionInfo()`
2. `show(myBiomodModelOut)`
Can you also share the script you are using ? (from data preparation to model projection ?)
Best,
Rémi

**Comment by rahulkgour** [comment]
Dear Rémi,

Thanks for your reply.

I have pasted the output below for:

**1. `sessionInfo()`**

> R version 4.2.2 (2022-10-31)
> Platform: aarch64-apple-darwin20 (64-bit)
> Running under: macOS Ventura 13.2
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] biomod2_4.2-2    rasterVis_0.51.5 lattice_0.20-45  raster_3.6-14    sp_1.6-0        
>  [6] gridExtra_2.3    ggplot2_3.4.0    tmap_3.3-3       terra_1.7-3      sf_1.0-9        
> [11] blockCV_3.0-1   
> 
> loaded via a namespace (and not attached):
>   [1] backports_1.4.1        lwgeom_0.2-11          plyr_1.8.8            
>   [4] splines_4.2.2          crosstalk_1.2.0        listenv_0.9.0         
>   [7] leaflet_2.1.1          usethis_2.1.6          digest_0.6.31         
>  [10] foreach_1.5.2          htmltools_0.5.4        earth_5.3.2           
>  [13] fansi_1.0.4            magrittr_2.0.3         checkmate_2.1.0       
>  [16] memoise_2.0.1          remotes_2.4.2          recipes_1.0.4         
>  [19] globals_0.16.2         gower_1.0.1            hardhat_1.2.0         
>  [22] timechange_0.2.0       prettyunits_1.1.1      jpeg_0.1-10           
>  [25] colorspace_2.1-0       leafem_0.2.0           dplyr_1.1.0           
>  [28] rgdal_1.6-4            callr_3.7.3            crayon_1.5.2          
>  [31] hexbin_1.28.2          survival_3.4-0         zoo_1.8-11            
>  [34] iterators_1.0.14       glue_1.6.2             stars_0.6-0           
>  [37] PresenceAbsence_1.1.11 gtable_0.3.1           ipred_0.9-13          
>  [40] pkgbuild_1.4.0         future.apply_1.10.0    abind_1.4-5           
>  [43] scales_1.2.1           DBI_1.1.3              miniUI_0.1.1.1        
>  [46] Rcpp_1.0.10            plotrix_3.8-2          viridisLite_0.4.1     
>  [49] xtable_1.8-4           units_0.8-1            proxy_0.4-27          
>  [52] Formula_1.2-4          stats4_4.2.2           intervals_0.15.2      
>  [55] lava_1.7.1             prodlim_2019.11.13     profvis_0.3.7         
>  [58] dismo_1.3-9            htmlwidgets_1.6.1      RColorBrewer_1.1-3    
>  [61] wk_0.7.1               ellipsis_0.3.2         farver_2.1.1          
>  [64] XML_3.99-0.13          urlchecker_1.0.1       pkgconfig_2.0.3       
>  [67] reshape_0.8.9          nnet_7.3-18            deldir_1.0-6          
>  [70] utf8_1.2.3             caret_6.0-93           labeling_0.4.2        
>  [73] tmaptools_3.1-1        tidyselect_1.2.0       rlang_1.0.6           
>  [76] reshape2_1.4.4         later_1.3.0            munsell_0.5.0         
>  [79] TeachingDemos_2.12     tools_4.2.2            cachem_1.0.6          
>  [82] cli_3.6.0              generics_0.1.3         devtools_2.4.5        
>  [85] stringr_1.5.0          fastmap_1.1.0          maxnet_0.1.4          
>  [88] leafsync_0.1.0         ModelMetrics_1.2.2.2   processx_3.8.0        
>  [91] fs_1.6.1               s2_1.1.2               purrr_1.0.1           
>  [94] randomForest_4.7-1.1   future_1.31.0          nlme_3.1-160          
>  [97] mime_0.12              compiler_4.2.2         rstudioapi_0.14       
> [100] png_0.1-8              ENMeval_2.0.4          e1071_1.7-13          
> [103] tibble_3.1.8           stringi_1.7.12         plotmo_3.6.2          
> [106] ps_1.7.2               Matrix_1.5-1           classInt_0.4-8        
> [109] gbm_2.1.8.1            vctrs_0.5.2            pillar_1.8.1          
> [112] lifecycle_1.0.3        data.table_1.14.6      httpuv_1.6.8          
> [115] R6_2.5.1               latticeExtra_0.6-30    promises_1.2.0.1      
> [118] renv_0.16.0            KernSmooth_2.23-20     parallelly_1.34.0     
> [121] sessioninfo_1.2.2      codetools_0.2-18       dichromat_2.0-0.1     
> [124] MASS_7.3-58.1          pkgload_1.3.2          withr_2.5.0           
> [127] mgcv_1.8-41            parallel_4.2.2         grid_4.2.2            
> [130] rpart_4.1.19           timeDate_4022.108      tidyr_1.3.0           
> [133] class_7.3-20           mda_0.5-3              pROC_1.18.0           
> [136] base64enc_0.1-3        shiny_1.7.4            lubridate_1.9.1       
> [139] interp_1.1-3
> 



**2. `show(myBiomodModelOut)`**

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> Modeling folder : .
> 
> Species modeled : occ
> 
> Modeling id : test
> 
> Considered variables : diffNDVI dist_road dist_settle precip temp twi vappres windspeed 
> aspect slope
> 
> 
> Computed Models :  occ_PA1_RUN1_GLM occ_PA1_RUN1_MARS occ_PA1_RUN1_MAXENT 
> occ_PA1_RUN2_GLM occ_PA1_RUN2_MARS occ_PA1_RUN2_MAXENT occ_PA1_RUN3_GLM occ_PA1_RUN3_MARS 
> occ_PA1_RUN3_MAXENT occ_PA1_RUN4_GLM occ_PA1_RUN4_MARS occ_PA1_RUN4_MAXENT 
> occ_PA1_RUN5_GLM occ_PA1_RUN5_MARS occ_PA1_RUN5_MAXENT
> 
> 
> Failed Models :  none

--------------------------------------------------------------------------------------------------------------------------

**The script which I am using for this test run is same which you had provided me yesterday at** issue https://github.com/biomodhub/biomod2/issues/182

Pasting the same below:

```
# loading the libraries
library(biomod2)
library(blockCV)
library(sf) # working with spatial vector data
library(terra) # working with spatial raster data

# loading raster data
rasters <- stack(diff_ndvi, dist_road, dist_settlement, 
                 precipitation, temperature, twi,
                 vapour_pressure, wind_speed, aspect, slope)

points <- read.csv(file.choose())


# We convert the `data.frame` to `sf` as follows:
pa_data <- sf::st_as_sf(points, coords = c("x", "y"), crs = 4326)


### Using `blockCV` in `biomod2` package
# species occurrences
DataSpecies <- points
# the name of studied species
myRespName <- "occ"
# the presence/absences data for our species
myResp <- as.numeric(DataSpecies[,myRespName])
# the XY coordinates of species data
myRespXY <- DataSpecies[,c("x","y")]
# extract the raster values for the species points as a dataframe
RasterValues <- terra::extract(rasters, pa_data, df = TRUE, ID = FALSE)
myResp.PA <- ifelse(myResp == 1, 1, NA)


# Step 1. Defining pseudo absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                     expl.var = rasters,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                     PA.nb.rep = 1,
                                     PA.nb.absences = 1000,
                                     PA.strategy = 'random',
                                     na.rm = TRUE)

# Step 2. Presence+pseudo-absence from biomod.formated.data object
myPoints <- cbind(myBiomodData@data.species, myBiomodData@coord)
colnames(myPoints) <- c("occ","x","y")
pa_data <- sf::st_as_sf(myPoints, coords = c("x", "y"), crs = 4326)

# Step 3. Run crossvalidation
###### Generating block CV folds
# Here, we generate two CV strategy, one k-fold CV using `cv_spatial` 
scv1 <- cv_spatial(
  x = pa_data,
  column = "occ", # the response column (binary or multi-class)
  r = rasters,
  k = 5, # number of folds
  size = 1000, # size of the blocks in meters
  selection = "random", # random blocks-to-fold
  iteration = 50, # find evenly dispersed folds
  progress = FALSE, # turn off progress bar
  biomod2 = TRUE, # also create folds for biomod2
  raster_colors = terrain.colors(10, rev = TRUE) # options from cv_plot for a better colour contrast
)

DataSplitTable <- scv1$biomod_table
myBiomodOption <- BIOMOD_ModelingOptions()


# Step 4. Model fitting
myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = c('GLM','MARS','MAXENT'),
                                    bm.options = myBiomodOption,
                                    data.split.table = DataSplitTable, # blocking folds
                                    var.import = 0,
                                    metric.eval = c('ROC'),
                                    do.full.models = TRUE,
                                    modeling.id = "test")


# Step 5. Ensemble models
BIOMOD_ensemble_models <- 
  BIOMOD_EnsembleModeling(
    bm.mod = myBiomodModelOut,
    models.chosen = 'all',
    em.by = 'all',
    metric.select = 'ROC',
    metric.select.thresh = 0.7,
    metric.eval = c('ROC'),
    em.algo = c('EMmean', 'EMwmean'),
    EMci.alpha = 0.05,
    EMwmean.decay = 'proportional')


# Step 6. Models projections
# Project single models
file.proj <- paste0(myRespName, "/proj_Current/", myRespName, ".Current.projection.out") 
if (file.exists(file.proj)) {
  myBiomodProj <- get(load(file.proj))
} else {
BIOMOD_models_proj_current <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
proj.name = 'Current',
new.env = rasters,
models.chosen = 'all')
}

# I have tried below code also, but getting same error, even tried new.env with SpatRaster. I converted the raster stack 'rasters' to a SpatRaster through terra::rast() function.
# BIOMOD_models_proj_current <- BIOMOD_Projection(
#                                 bm.mod = myBiomodModelOut,
#                                 proj.name = 'Current',
#                                 new.env = rasters,
#                                 models.chosen = 'all',
#                                 metric.binary = 'all',
#                                 metric.filter = 'all',
#                                 build.clamping.mask = TRUE)

BIOMOD_models_proj_current
plot(BIOMOD_models_proj_current)


# Project Ensemble models
myBiomodEF <- BIOMOD_EnsembleForecasting(
                        bm.em = BIOMOD_ensemble_models,
                        bm.proj = BIOMOD_models_proj_current,
                        models.chosen = 'all',
                        metric.binary = 'all',
                        metric.filter = 'all'
                        )

myBiomodEF
plot(myBiomodEF)
```


Thanks & regards,
Rahul

**Comment by rpatin** [comment]
Dear Rahul,
Unfortunately, I still cannot reproduce the error. 
I have several lead for now (although none are satisfying):
- maybe it is an obscure issue with `doParallel`. Can you try running:
```
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list = ls(name = env), pos = env)
}
unregister_dopar()
```
Before running `BIOMOD_Projection` ?

- Else it might be a problem with Mac. I will try running the code on Mac tomorrow morning. Meanwhile, if you can I would suggest to try your code on other operating system.

- it might be an issue between Mac and MAXENT (or just MAXENT) can you try to disable Maxent to see whether the code runs or not ?

Best,
Rémi

**Comment by rahulkgour** [comment]
Dear Rémi,

I have ran the given things as you suggested, sadly I can still see the error.

- I have ran the below code just before running the `BIOMOD_Porjection`

```
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list = ls(name = env), pos = env)
}
unregister_dopar()

```

```
BIOMOD_models_proj_current <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                                   proj.name = 'Current',
                                                   new.env = rasters,
                                                   models.chosen = 'all')
```

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> 	> Building clamping mask
> 
> 	> Projecting occ_PA1_RUN1_GLM ...
> 	> Projecting occ_PA1_RUN1_MARS ...
> 	> Projecting occ_PA1_RUN1_MAXENT ...
> 	> Projecting occ_PA1_RUN2_GLM ...
> 	> Projecting occ_PA1_RUN2_MARS ...
> 	> Projecting occ_PA1_RUN2_MAXENT ...
> 	> Projecting occ_PA1_RUN3_GLM ...
> 	> Projecting occ_PA1_RUN3_MARS ...
> 	> Projecting occ_PA1_RUN3_MAXENT ...
> 	> Projecting occ_PA1_RUN4_GLM ...
> 	> Projecting occ_PA1_RUN4_MARS ...
> 	> Projecting occ_PA1_RUN4_MAXENT ...
> 	> Projecting occ_PA1_RUN5_GLM ...
> 	> Projecting occ_PA1_RUN5_MARS ...
> 	> Projecting occ_PA1_RUN5_MAXENT ...Error in { : 
>   task 1 failed - "no applicable method for 'predict' applied to an object of class "SpatRaster""
> In addition: Warning message:
> executing %dopar% sequentially: no parallel backend registered 

---------------------------------------------------------

- Then I disabled the Maxent and ran the whole code again from the beginning, we still received the small error.

Output for the `BIOMOD_Projection` while disabling the Maxent.

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> 	> Building clamping mask
> 
> 	> Projecting occ_PA1_RUN1_GLM ...
> 	> Projecting occ_PA1_RUN1_MARS ...
> 	> Projecting occ_PA1_RUN2_GLM ...
> 	> Projecting occ_PA1_RUN2_MARS ...
> 	> Projecting occ_PA1_RUN3_GLM ...
> 	> Projecting occ_PA1_RUN3_MARS ...
> 	> Projecting occ_PA1_RUN4_GLM ...
> 	> Projecting occ_PA1_RUN4_MARS ...
> 	> Projecting occ_PA1_RUN5_GLM ...
> 	> Projecting occ_PA1_RUN5_MARS ...
> Error in { :
> task 1 failed - "no applicable method for 'predict' applied to an object of class "SpatRaster""

---------------------------------------------------------

- Currently we don't have any other Operating system handy with us to test this issue. :-( But we can wait for you to run this on Mac tomorrow morning to reproduce the error.

Thanks & regards,
Rahul

**Comment by rpatin** [comment]
Dear Rahul,
I still have no clue what is happening and I could not try it on Mac, the machine I was planning to use had an old version and I could not install R/Rstudio.
Right now I still have one lead left. I slightly modified the package code to make explicit reference to `terra::predict` method for `SpatRaster`. You can install this version with the following command (please do the installation with a new R session with no objects or packages loaded):
`devtools::install_github('biomodhub/biomod2', ref = 'terra_predict')`
Let me know if that changes something for you or not.
Best,
Rémi

**Comment by rahulkgour** [comment]
Dear Rémi,

Thank you so much for your time and prompt responses.

I have installed the latest version in the same manner as you mentioned above.

I glad to say that we don't see that error now. I am really thankful for your effort.
But there is a warning message associated with the run.
> Warning messages:
> 1: executing %dopar% sequentially: no parallel backend registered 
> 2: [rast] SRS do not match 

And on a side note, when I am trying to plot the ensemble projection we are facing error, though its not a show stopper for us, as we can fetch the raster and use it in any GIS software to plot. But wanted to update in case if it's an easy fix.
`plot(myBiomodEF)`
> Error in .plot.BIOMOD.projection.out.check.args(x, coord = coord, plot.output = plot.output,  : missing coordinates to plot with a data.frame. Either give argument `coord` to plot or argument `new.env.xy` to BIOMOD_Projection

Thanks again,
Rahul

**Comment by rpatin** [comment]
Dear Rahul,
Glad that it finally worked out, although I do not have a long-term solution for the problem yet.

Concerning the warnings you see:
1. the code is written to allow parallelization when asked for it. Thus, when you do not use parallel computing you see this harmless warning.
2. our handling of raster projection is a bit sloppy so we do not define the projection of the new raster that we create (i.e. the clamping mask. So when combining internal raster (without projection) with data raster (with projection) the warning appears about projection not matching. Again it is harmless as all raster have the same projection and extent.

Concerning the error:
You provided `new.env` as a `data.frame`. In order to plot the projection you need to provide the coordinates either directly to the plot function (with arg `coord`) or indirectly when using `BIOMOD_Projection` (with arg `new.env.xy`). The plot function cannot guess the coordinates of the new environment.

Best,
Rémi

**Comment by rahulkgour** [comment]
Thank you Rémi for your help, it worked, thanks a lot.

Regards,
Rahul
