### ISSUE TITLE
Plot Response Curves for multiple BIOMOD.models.out

### ISSUE THREAD

**Issue by Jmillot34** [biomodhub/biomod2#185]
Hi, 

I am using BIOMOD functions in a loop to compute GAM, GLM and RF for different combinations of variables. 
As a result, I obtain BIOMOD.models.out in different folders and I wanted to combine them and plot all the response curves in one plot. I am not sure that bm_PlotResponseCurves can be used for this task. 

Otherwise, if I want to customize my own response curve, is there a method to extract the information required from each BIOMOD model? 

When I use the get_prediction function, I obtain only values for GLM and not GAM and I am not very sure of the type of data provided by this function. 

Hope that my issue is enough clear

Thank you very much in advance for your help!

**Comment by rpatin** [comment]
Hi @Jmillot34,
Thank you for reporting :pray: 

1. Concerning the plot of response curve for multiple model, you can extract the data.frame used by `bm_PlotResponseCurves`. Here is how to do it:
```
myResponseCurve <- bm_PlotResponseCurves(myBiomodModelOut, 
                                               models.chosen = "all",
                                               fixed.Var = "mean",
                                               do.bivariate = FALSE,
                                               do.plot = FALSE,
                                               do.progress = FALSE)

ggdat <- myResponseCurve$tab
```

Then you can do the same for the other model and combine the data.frame as you want.

If you want to reproduce the graphic from `bm_PlotResponseCurve` (for a single model - but you can adjust as you want for multiple one, given the adjustment to the combine data.frame)
```
    ggplot(ggdat, aes(x = expl.val, y = pred.val, color = pred.name)) +
      geom_line() +
      facet_wrap(~expl.name, scales = "free_x") +
      xlab("") +
      ylab("") +
      theme(legend.title = element_blank()
            , legend.key = element_rect(fill = "white")
            , legend.position = "bottom"
            , axis.text.x = element_text(angle = 45, hjust = 1))
```

2. Concerning the issue with `get_predictions` function returning only values for _glm_, can you share:
- the output of `show(myBiomodModelOut)` (the `BIOMOD.models.out` object)
- the call you did to `get_predictions`.

`get_predictions` retrieve the different model prediction from `biomod2` objects. Depending the type of objects used with `get_predictions`, predictions are calculated on different environmental variables:
- when using `get_predictions` on the output of `BIOMOD_Modeling` or `BIOMOD_EnsembleModeling`, predictions are made on the environmental data used for model fit.
- when using `get_predictions` on the output of `BIOMOD_Projection` or `BIOMOD_EnsembleForecasting`, predictions are made on the environmental data provided as `new.env` to the projection function.
I hope this is clearer now. If not, feel free to ask additional questions.

Cheers,
Rémi

**Comment by Jmillot34** [comment]
Hi Rémi, 
it is very clear now, thanks a lot for this detailed response. 

About the "get_prediction" function, it was a personal mistake, so I fix it. 

I have another question about another subject.
Maybe I should open a new discussion but I try to ask my question here  : 

In  BIOMOD_ModelingOptions {biomod2}, for GLM I can specify BIC as a criterion used to compute the Stepwise procedure but for GAM can I change this parameter as well ? And if not, how the stepwise procedure is done for GAM in BIOMOD2 ? 

Can you in general explain how stepwise procedure is done? For each run, BIOMOD select the best combination of variable according to the lowest BIC? Why is never the same combination between different runs? 

Thanks you very much for your precious help Rémi

**Comment by Jmillot34** [comment]
Thanks a lot Rémi ! 
Very clear response as usual !

Concerning the particular stepwise procedure, I wanted to try the BIC criterion as for GLM but AIC provides a similar result I guess.
