### ISSUE TITLE
Error with 'get_variables_importance(BIOMOD_ensemble_models)'

### ISSUE THREAD

**Issue by rahulkgour** [biomodhub/biomod2#187]
Hi,

We can see error for variable importance function though we are getting proper output with other response curve functions like bm_PlotResponseCurves etc.

```
myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = c('RF'),
                                    bm.options = myBiomodOption,
                                    data.split.table = DataSplitTable, # blocking folds
                                    var.import = 3,
                                    metric.eval = c('TSS'),
                                    do.full.models = TRUE,
                                    modeling.id = "test")

```

```
BIOMOD_ensemble_models <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                                  models.chosen = 'all',
                                                  em.by = 'all',
                                                  metric.select = 'TSS',
                                                  metric.select.thresh = 0.3,
                                                  metric.eval = c('TSS'),
                                                  em.algo = c('EMmean', 'EMwmean'),
                                                  EMci.alpha = 0.05,
                                                  EMwmean.decay = 'proportional')
```

Output of `BIOMOD_ensemble_models` is:

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
>    ! all models available will be included in ensemble.modeling
>    > Evaluation & Weighting methods summary :
>       TSS over 0.3
> 
> 
>   > mergedData_mergedRun_mergedAlgo ensemble modeling
>    > Mean of probabilities by TSS ...
> 			Evaluating Model stuff...
> 		  original models scores =  0.411 0.413 0.396 0.414
> 		  final models weights =  0.252 0.253 0.242 0.253
>    > Probabilities weighting mean by TSS ...
> 			Evaluating Model stuff...
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

`get_evaluations(BIOMOD_ensemble_models)`

>                                          full.name merged.by.PA merged.by.run
> 1  occ_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun
> 2 occ_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun
>   merged.by.algo filtered.by    algo metric.eval cutoff sensitivity specificity
> 1     mergedAlgo         TSS  EMmean         TSS    357      99.317      97.796
> 2     mergedAlgo         TSS EMwmean         TSS    357      99.317      97.796
>   calibration validation evaluation
> 1       0.971         NA         NA
> 2       0.971         NA         NA

`get_variables_importance(BIOMOD_ensemble_models)`

> Error in { : task 1 failed - "argument of length 0"
> In addition: Warning message:
> In .local(obj, ...) : No link provided for this object

thanks & regards,
Rahul

**Comment by rpatin** [comment]
Hi Rahul,
Thank you for reporting and providing clear informations about your problem :pray: 

It appears that you did not ask `BIOMOD_EnsembleModeling` to evaluate variable importance so `get_variables_importance` cannot work properly:
```
BIOMOD_ensemble_models <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                                  models.chosen = 'all',
                                                  em.by = 'all',
                                                  metric.select = 'TSS',
                                                  metric.select.thresh = 0.3,
                                                  metric.eval = c('TSS'),
                                                  em.algo = c('EMmean', 'EMwmean'),
                                                  EMci.alpha = 0.05,
                                                  EMwmean.decay = 'proportional',
                                                  var.import = 3
)
```

When you do not provide argument `var.import` it is set by default to 0. And providing it to `BIOMOD_Modeling` is independent of what `BIOMOD_EnsembleModeling` will do.
Hope this is clearer now.
Regards,
Rémi

**Comment by rahulkgour** [comment]
Thank you Rémi for the clarification, I was considering that `BIOMOD_EnsembleModeling` is dependent on `BIOMOD_Modeling` especially for argument `var.import`.

Regards,
Rahul
