### ISSUE TITLE
Error with installation of rJava: LoadLibrary failure: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by sempergnarus** [biomodhub/biomod2#189]
Hello, my operating system is windows 11. I downloaded both 32-bit and 64-bit java after the error but nothing is changed. I need rJava to be able to use maxent in biomod2. I tried to install rJava but got these errors. Please help.

install.packages("rJava") WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/ Installing package into ‘C:/Users/Ersan/AppData/Local/R/win-library/4.2’ (as ‘lib’ is unspecified) trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/rJava_1.0-6.zip' Content type 'application/zip' length 1245703 bytes (1.2 MB) downloaded 1.2 MB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in C:\Users\Ersan\AppData\Local\Temp\RtmpULJHwE\downloaded_packages

library(rJava) Error: package or namespace load failed for ‘rJava’: .onLoad failed in loadNamespace() for 'rJava', details: call: inDL(x, as.logical(local), as.logical(now), ...) error: unable to load shared object 'C:/Users/Ersan/AppData/Local/R/win-library/4.2/rJava/libs/x64/rJava.dll': LoadLibrary failure: %1 is not a valid Win32 application.

**Comment by rpatin** [comment]
Hello @sempergnarus 
Thank you for reporting :pray: 
You had the following warnings:
```
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding: https://cran.rstudio.com/bin/windows/Rtools/
```
Hence, I would suggest that you install Rtools and then proceed to install `rJava`.
Cheers,
Rémi

**Comment by sempergnarus** [comment]
Hi Rémi,

I tried that right now, but I got the same error again: Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Ersan/AppData/Local/R/win-library/4.2/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
