### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JintaoSHOU** [biomodhub/biomod2#19]
Hi, all, cloud I plot numeric  value using response.plot2 with RandomForeset

But i get this error
"Error in predict.randomForest(get_formal_model(object), as.data.frame(newdata[not_na_rows,  : 
  'prob' or 'vote' not meaningful for regression"

Should I change some arguments in response.plot2?

**Comment by DamienGeorges** [comment]
Hi,

Could you send me a reproducible example and a copy of your sessionInfo() output?

Thanks,
Damien

**Comment by DamienGeorges** [comment]
no feedback.. I close this ticket.. feel free to re-open if you are still facing the issue
