### ISSUE TITLE
[rast] SRS do not match

### ISSUE THREAD

**Issue by Supervegito16** [biomodhub/biomod2#194]
Hi there,
I am trying to run Ensemble modelling for my species
**Ensemble model**
`ProLau_ensemble_models <- BIOMOD_EnsembleModeling(bm.mod = ProLau_models,
                                                  em.by = 'all',
                                                  metric.select = 'TSS',
                                                  metric.select.thresh = 0.8,
                                                  metric.eval = c('TSS','ROC'),
                                                  prob.mean = FALSE,
                                                  prob.cv = TRUE, 
                                                  committee.averaging = TRUE,
                                                  prob.mean.weight = TRUE,
                                                  var.import = 2)`

**Current projections**

`ProLau_ensemble_models_proj_current <- BIOMOD_EnsembleForecasting(bm.em = ProLau_ensemble_models,
                                                                  bm.proj = ProLau_models_proj_current,
                                                                  proj.name = "current",
                                                                  models.chosen = 'all',
                                                                  metric.binary = "TSS",
                                                                  output.format = ".img",
                                                                  do.stack = FALSE)`

My question is
When I try to run current projections I get the following error

`Warning messages:
1: [rast] SRS do not match 
2: Too large for int: nan (GDAL error 1) 
3: Too large for int: nan (GDAL error 1) `

I initially thought the warning is due my raster not warping correctly but on checking everything seems fine. I was modelling for a large area so I reduced the area to less than a quarter but still the warning message occurs. Moreover, when I try to plot the **ProLau_ensemble_models_proj_current** I get the following error

`Error in .plot.BIOMOD.projection.out.check.args(x, coord = coord, plot.output = plot.output,  : 
  missing coordinates to plot with a data.frame. Either give argument `coord` to plot or argument `new.env.xy` to BIOMOD_Projection`

I am sorry I am new to modelling in R and can't figure out these errors. Any help would be appreciated. I am attaching a reprex for reference
[reprex_biomod.csv](https://github.com/biomodhub/biomod2/files/10846536/reprex_biomod.csv)
[elevation.zip](https://github.com/biomodhub/biomod2/files/10846541/elevation.zip)

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for reporting :pray: 
You can check this issue here about the same warning and error : https://github.com/biomodhub/biomod2/issues/184#issuecomment-1434251340 :blush: 

Please do not hesitate if you have further questions.
Maya

**Comment by Supervegito16** [comment]
Hi Maya,
Thank you for the prompt reply. As you indicated, i went through the thread. Seems like they faced a similar problem with `plot(ProLau_ensemble_models_proj_current`

I want ensemble to predict on the rasters I have already supplied. Am i missing something here? Do I need to provide new rasters with different location? I am unsure as to how to write the code properly for it. Please help me out

**Comment by MayaGueguen** [comment]
Hello,

I don't know how you provided first your data to the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function : was it a `rasterStack` ? a `data.frame` ?

Following what Rémi said in the issue I sent you : 

> You provided new.env as a data.frame. In order to plot the projection you need to provide the coordinates either directly to the plot function (with arg coord) or indirectly when using BIOMOD_Projection (with arg new.env.xy). The plot function cannot guess the coordinates of the new environment.

It seems that you provided a `data.frame`. Then if you want to plot it, you are missing the coordinates, that you can provide in two ways, mentioned above.

Maya

**Comment by Supervegito16** [comment]
Hi,

`ProLau_data <- 
  BIOMOD_FormatingData(
    resp.var = ProLau_occ1['HM'],
    resp.xy = ProLau_occ1[, c('Long', 'Lat')],
    expl.var = rasters,
    resp.name = "HM",
    PA.nb.rep = 2,
    PA.nb.absences = 300,
    PA.strategy = 'random',
    filter.raster = TRUE
  )
`
This is how my BIOMOD_FormatingData was. ProLau_occ1 is a dataframe yes. Its a presence only file. Should I put the same file again while plotting?

**Comment by Supervegito16** [comment]
Thank you so much Maya. It worked. I even tried putting my raster file in `new.env `and it worked. Thank you once again for all the help
