### ISSUE TITLE
Variable Significance

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#195]
Hi all!

Is there a way to assert variable significance when using MaxEnt? Or is Variable Importance the only way to look at their contribution?

Thanks!

Luis

**Comment by MayaGueguen** [comment]
Hello Luis,

Variable importance is currently the only way implemented in `biomod2` to assert variable importance, whatever the model.
Maybe there is another to take that into account in MAXENT but then you will have to run MAXENT on your own, and not through `biomod2` package.

Maya
