### ISSUE TITLE
Error when MAXENT is generating its own background data from explanatory variable rasters

### ISSUE THREAD

**Issue by suicmezburak** [biomodhub/biomod2#196]
Hello there,
While modeling, for other algorithms, I have produced pseudo absence data using BIOMOD_FormatingData, but for maxent I want to generate 10000 background data instead of this pseudo absence data and use it instead.

So I tried to create background data with below code
```
## Define individual models options
modeloption <- BIOMOD_ModelingOptions(
  MAXENT = list( path_to_maxent.jar = "C:/Users/Hp/Desktop/sdm_data/maxent",
                 memory_allocated = 2048,
                 background_data_dir = "C:/Users/Hp/Desktop/sdm_data/maxent/background_data", #my explanatory variables are here as ".asc"
                 maximumbackground = 10000
  )
)
```

then I ran the model for testing
```
`quercus_model_output <- 
  BIOMOD_Modeling(
    bm.format = quercus_data,
    bm.options = modeloption,
    modeling.id = "all_Models",
    models = c("MAXENT"),
    nb.rep = 1, 
    data.split.perc = 80,
    metric.eval = c("TSS", "ROC"),
    var.import = 3,
    save.output = TRUE,
    do.full.models = FALSE
  )
```

This code gives an error.
```
Model=MAXENT
	> MAXENT modeling...
		Creating Maxent Temp Proj Data...
*** Error in MAXENT, more info available in ./Quercus/models/all_Models/Quercus_PA1_RUN1_MAXENT_outputs/maxent.stderr
*** inherits(g.pred,'try-error')
   ! Note :  Quercus_PA1_RUN1_MAXENT failed!

! All models failed

This is whats written on "maxent.stderr" file
Warning: Unused field bio5 in Sp_swd.csv
Warning: Unused field bio7 in Sp_swd.csv
Warning: Unused field bio8 in Sp_swd.csv
Warning: Unused field bio11 in Sp_swd.csv
Warning: Unused field bio15 in Sp_swd.csv
Warning: Unused field bio16 in Sp_swd.csv
Warning: Unused field bio17 in Sp_swd.csv
Error: Error projecting
```

When "background_data_dir" and "maximumbackground" are removed from the models options, maxent uses the pseudo absence data I generated and works fine.

I don't know if I have given useful information for you to help, I am not very professional in this matter.
Thanks in advance.

**Comment by MayaGueguen** [comment]
Hello Burak,

Thank you for reporting :pray: 
For now, it is not possible indeed to run models with different sets of pseudo-absences, but this is something that we are working on. 
_Actually, it is already almost ready into the devel branch, if you would like to test it, you can by installing it with :_
```
library(devtools)
devtools::install_github("biomodhub/biomod2", ref = "devel_current")
```
Otherwise, why don't you create a new [BIOMOD.formated.data](https://biomodhub.github.io/biomod2/reference/BIOMOD.formated.data.html) object with the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) specific to your MAXENT modelling (ie containing 10000 new pseudo absences points) ?

Maya

**Comment by MayaGueguen** [comment]
Unfortunately, the `maximumbackground` parameter does not work at the time, so you cannot use that.
Which leaves you with 2 options : 
1. either you create 2 [BIOMOD.formated.data](https://biomodhub.github.io/biomod2/reference/BIOMOD.formated.data.html) objects, with different number of pseudo-absences, and you run 2 times the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, one for all your models except MAXENT, and one for MAXENT only.
_This is the main option, as `biomod2` currently cannot run single models with different pseudo-absences datasets at the same time._
2. or you try and install the devel version, which still cannot use the `maximumbackground` parameter in MAXENT, but allows the production of different sets of pseudo-absences within one single [BIOMOD.formated.data](https://biomodhub.github.io/biomod2/reference/BIOMOD.formated.data.html) object through the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function.
_But as this is a "release to come", I cannot provide you a lot of help support on this one, so maybe it is best for you to go with option 1. and wait for the release_

Maya

**Comment by suicmezburak** [comment]
Thank you for your time and valuable suggestions.
