### ISSUE TITLE
Problem running Project single model

### ISSUE THREAD

**Issue by DelphineChabanne** [biomodhub/biomod2#197]
Hi,

Since the new version of Biomod2, I am having issues getting the single model projection working and get the following error message:
```
"Error in { : task 1 failed - "NULL value passed as symbol address"
```

Here is my current code for the single model projection in case it is useful. All previous steps are similar to the example.

```
 myBiomodProj__KWS_Summer2022<-BIOMOD_Projection(bm.mod = myBiomodModelOut_KWS_Summer2022, 
                                                new.env=myExpl_KWS_Summer2022, 
                                                proj.name='Projection_KWS_Summer2022', 
                                                models.chosen = 'all', 
                                                metric.binary='all') 
                                                compress='xz', 
                                                build.clamping.mask=FALSE, 
                                                nb.cpu =4,
                                                output.format='.grd')
```

Many thanks in advance for your help.

Delphine

**Comment by rpatin** [comment]
Hi Delphine,
It is potentially related to this issue https://github.com/biomodhub/biomod2/issues/149.

- Do you load the package `foreach` directly in your code ? (e.g. with `library(foreach)`) ?
 If that is the case, you should remove `library(foreach)` from your code and try again once you restarted R.

- Alternatively can you try running `BIOMOD_Projection` without parallelization. i.e. by setting `nb.cpu = 1` and closing the already open cluster (either by restarting R/RStudio or by using the following code)

  _Code to close the cluster:_
 ```
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
unregister_dopar()
```

- If none of that helps understanding your issue, could you share a bit more information ? e.g.:
  - the output of `show(myBiomodData)`  
  - the output of `show(myBiomodModelOut_KWS_Summer2022)`  
  - what type of object is `myExpl_KWS_Summer2022`
  - what does  `BIOMOD_Projection` tells you before the error ?

Cheers,
Rémi

**Comment by DelphineChabanne** [comment]
Hi Remi,

No, I don't load the package foreach but using the code you provided to 'close the cluster' did the trick prior to using the BiomodProjection function.

Thank you. 
Delphine
