### ISSUE TITLE
Question: An possibility to add confidence interval while generating response curves in the latest version of biomod package.

### ISSUE THREAD

**Issue by rahulkgour** [biomodhub/biomod2#198]
Hi Rémi,

Its more like a question: An possibility to add confidence  interval while generating response curves.

Code which we are using for the ensemble pred.name `EMwmeanByTSS_mergedData_mergedRun_mergedAlgo`

```
bm_PlotResponseCurves(bm.out = BIOMOD_ensemble_models, 
                      models.chosen = get_built_models(BIOMOD_ensemble_models)[2],
                      fixed.var = 'mean')
```

Thanks in advance!
Rahul

**Comment by rpatin** [comment]
Hi Rahul,
Can you elaborate on which confidence interval you are talking about ?
- If that is the confidence interval of each individual model response curve (e.g. confidence interval, for GBM, RUN1, PA1), then it is not possible and would require heavy development to be able to predict such uncertainty in response curve (besides the fact that with all the different model algorithm, uncertainty in predictions is likely handled differently)
- If that is the confidence interval of a group of model response curve (e.g. confidence interval for the response of all model built with GBM (from RUN1 to RUN10 and PA1 to PA10 for instance), I invite you to read issue https://github.com/biomodhub/biomod2/issues/192 where Maya propose a solution.
Best,
Rémi

**Comment by rahulkgour** [comment]
Hi Rémi,

Thanks for your detailed response.

Actually we wanted to have the confidence interval of combining all the response curves generated while building the models under the set of algorithms which we have given during modeling, in our case we provided six algos `models = c('ANN', 'MARS', 'GBM', 'GLM', 'RF', 'MAXENT')`.

Hope I am clear now with my query.

Thanks again,
Rahul

**Comment by rahulkgour** [comment]
Hi Rémi,

I have tried the second point which you mentioned, but I am facing error in middle of the code.

```
tmp.mean = foreach(tabi = tmp.split, .combine = "rbind") %do%
  {
    res = unique(tabi[, c("id", "expl.name", "expl.val")])
    res$pred.val = mean(tabi$pred.val)
    res$conf.inf = ci_mean(tabi$pred.val)$interval[1]
    res$conf.sup = ci_mean(tabi$pred.val)$interval[2]
    return(res)
  }
```

> Error in { : task 97 failed - "replacement has 1 row, data has 0"

I am not able to rectify this error.

Thanks and regards,
Rahul

**Comment by rahulkgour** [comment]
I tried adding new column in `tmp.mean` object with `<- NA` first before calculating `ci_mean`, but it didn't work.

**Comment by rahulkgour** [comment]
Hi Rémi,

Sorry for the so many messages, actually it worked after a small modification.

```
tmp.mean = foreach(tabi = tmp.split, .combine = "rbind") %do%
  {
    if(nrow(tabi) == 0){
      return(NULL) # Return NULL if tabi has no rows
    }
    
    res = unique(tabi[, c("id", "expl.name", "expl.val")])
    res$pred.val = mean(tabi$pred.val)
    res$conf.inf = ci_mean(tabi$pred.val)$interval[1]
    res$conf.sup = ci_mean(tabi$pred.val)$interval[2]
    return(res)
  }
```
Thanks & regards,
Rahul
