### ISSUE TITLE
Projection outputs for GLMs; some runs provide odd uniform suitability output?

### ISSUE THREAD

**Issue by jmmccar** [biomodhub/biomod2#199]
Hi all,

I am wondering if anyone else has run into this issue when projecting their models forward in time under alternate climate scenarios. For some reason, some of the model runs produce uniform results across geographic space while others seem to run just fine. I have checked that all inputs for my original models & projections align in the necessary ways. I'm unsure if perhaps this is an issue of environmental variables being out of range with regard to how I fit my initial model? 

Are there other ways to individually evaluate projected runs so I can better see what is happening inside of the process? Any ideas on paths forward would be very much appreciated!

(And as a note, I do get more of the 'normal' runs when I increase 'nb.rep' in the original model)

![image](https://user-images.githubusercontent.com/44001107/223235229-998164c9-26f8-45fe-8bff-51d524df441a.png)

**Comment by MayaGueguen** [comment]
Hello Jenneca,

Could you share a bit more information about your dataset please ?
For example, the `print` of your `BIOMOD.formated.data` object obtained from the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function ? _To see how many presences you have._
What are the commands you used to run the single models (with the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function) ? _To see which models you ask for, how you split your data, etc._

Also, if you used the parameter `build.clamping.mask = TRUE` within the [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function, it will not change the results you get, but produce a map indicating the areas where you have many variables out of their calibration range, ie where predictions will be uncertains.
If you built this map, could you also share it ?

Thanks in advance,
Maya

**Comment by jmmccar** [comment]
Hi Maya,

Thank you for the reply & apologies, I should have included some of this basic info with my initial post! I feel like the answer is probably looking me right in the face but I just keep glossing over it somehow...

The output from `BIOMOD.formated.data`:
![image](https://user-images.githubusercontent.com/44001107/223806066-85795149-9917-4dd5-88ef-20b1a9a9e697.png)

The BIOMOD_Modeling code (currently a low number of nb.rep just so I can run it easily while I troubleshoot)
`BIOMOD_Modeling(Pk_data_dsk,
                models=c('GLM'),
                bm.options = myBiomodOption_dsk, 
                nb.rep = 3, 
                var.import = 10, 
                data.split.perc = 70, 
                metric.eval = c("TSS", "ROC"), 
                do.full.models = T, modeling.id = "dsk1"
                )`

And here is the clamping mask from the projection (run on environment model was built on; it looks a bit different on the western edge because I have adjusted the extent since I posted the initial question):
![image](https://user-images.githubusercontent.com/44001107/223807414-c5f6c2b3-c614-4335-94eb-64ec8faa1720.png)

I have also run this same model on an absence dataset built outside of the BIOMOD2 package (created using a kernal density surface) & the same thing happens; while most runs look as expected, some produce that uniform result.

**Comment by MayaGueguen** [comment]
Hello Jenn,

Thank you for the additional information 🙏 
I'm wondering if it might come from the fact that in some sets you might be "saturating" your whole map with your presences + pseudo-absences.
Could you give me the resolution of your map, as well as the number of pixel within it ? And the plot of your `BIOMOD.formated.data` object ?

Thanks in advance,
Maya

**Comment by jmmccar** [comment]
Thanks again for the reply Maya!

My `res` is `[1] 490.8114 490.8114`
The total pixels in the map are `[1] 17888`

Here's the plot of the `BIOMOD.formated.data`
![image](https://user-images.githubusercontent.com/44001107/224401279-00487a16-90eb-4325-aa53-4f2c34405fe5.png)


(It could well be that it's oversaturated - I hadn't split my data into training/validation datasets yet because I wanted to troubleshoot this issue, but I didn't even consider it might be causing the issue! I will definitely try reducing the occurrence dataset this weekend & let you know if that helps)

**Comment by jmmccar** [comment]
Hi again,

It took me longer to post this update than I had planned! I have tested running the models on several occ/abs datasets now. The problem persists for datasets of all sizes (whether occurrences are 2000 or 150), so I suppose it must not be an issue of saturation. It also isn't impacted by the spread of the absences/their min or max distance from occurrences. I'm wracking my brain trying to figure out what could be happening here. 

What is interesting is that these strange runs seem to occur more when projecting under certain climate scenarios than others.

**Comment by rpatin** [comment]
Hello Jenn,
I think there may be two interacting issues:
1. You work at a fine scale resolution (500m), with quite dense presences, meaning that your presences are really clumped in the environmental space. 
2. You use only `glm` as model, which cannot handle complex responses.

Separately both points are generally not a problem. However, taken together, I think what you see here is the inability of the `glm` to fit a response curve with clumped presences distribution. Hence I would try using model allowing more complex response curves: `GAM`, `RF`, `GBM`, ...
Best,
Rémi

**Comment by jmmccar** [comment]
Hi Remi,

Thank you so much for the input & your time!

I have tested running the GLMs on several occ/abs datasets now. The issue persists for datasets of all sizes (whether occurrences are 2000 or 150), & it doesn't seem to be impacted by the spread of the absences/their min or max distance from occurrences. I have also used the BlockCV package & tried data splits of various types & this also doesn't impact the output of these uniform 0 suitabilities.

I have also now tried running GAMs & MAXENT on the small dataset (150 occ, 150 abs) and still see this same thing occurring. 
![image](https://user-images.githubusercontent.com/44001107/230742193-27322283-4482-4d6c-a678-1dd4d7bce458.png)

What is interesting (& I should have noted this earlier) is that I do not get many of these uniform outputs in earlier projection time steps, and as I move through time steps they occur more often (I only see a couple of these runs in 2041-2060, but see several for 2080-2100).

I'm wondering if perhaps these are instances where suitability is actually 0 across my entire extent, especially since I'm seeing it across model types (GLMs, GAMs, MAXENT, etc). I'm just trying to cover all my bases before I draw that conclusion!

**Comment by rpatin** [comment]
Hi Jenn,
Sorry I failed to notice that your projection also affected future environment. 
Then it is totally plausible that some algorithm under some future environmental condition predict uniform presence or absence. To understand why this occur and if this is indeed a prediction of your model and not a statistical artefact  you have to:
1. Identify the important variables in your model(s). This can differ between algorithm. You can look at that with [`get_variables_importance`](https://biomodhub.github.io/biomod2/reference/getters.out.html) and [`bm_PlotVarImpBoxplot`](https://biomodhub.github.io/biomod2/reference/bm_PlotVarImpBoxplot.html)
2. Look at your model response curve with [`bm_PlotResponseCurves`](https://biomodhub.github.io/biomod2/reference/bm_PlotResponseCurves.html), for the important variables previously identified.
3. Look at the change in environment across your future scenario(s). What is the distribution of the important variables under current and future scenario(s). 

If you see a lot of absences in a scenario, it is likely that one important variable (identified with 1) change distribution in the given scenario (identified with 3), toward a distribution where prediction are absences (identified with 2).

I hope this is clearer now. Feel free to update the post if you need some help in using the different functions mentioned.

Best,
Rémi

**Comment by jmmccar** [comment]
Hi Remi,

Just wanted to quickly say thank you before closing this issue! Upon looking at the variable weighting, my response curves, & the range of future climate variables I was able to quickly sort out that these are true returns of unsuitable conditions across my model extent. Thank you again so much for the guidance!
