### ISSUE TITLE
Determine model/evaluation datasets by distance between plots

### ISSUE THREAD

**Issue by natearoe** [biomodhub/biomod2#20]
I have plots that are less than 200m from each other, and I am concerned about spatial autocorrelation. I want to use a model building dataset and an evaluation data set, but I want to be sure that if two plots are less than 200m from each other that they are not split between the model dataset and the evaluation dataset. To clarify, plots less than 200m from each other should either both be in the model building dataset or both be in the evaluation data set. 

It looks to me like biomod2 has this type of functionality for psuedo-absences (resp.xy = matrix_of_XY_coord, PA.strategy = 'disk', PA.dist.min = 200). Is there similar functionality for establishing model/evaluation datasets?

Why do I want to do this? My understanding of why: If plots are less than 200m from each other, they are likely spatially autocorrelated and therefore the observations are not independent - this effectively reduces the degrees of freedom in analyses. Using one to predict the other exacerbates the issue.

**Comment by DamienGeorges** [comment]
If you want to do so, you will have to defined yourself the data you want to use for model calibration/evaluation manually using `DataSplitTable` argument from `BIOMOD_Modeling()`
