### ISSUE TITLE
bm.tuning with pseudo-absence data

### ISSUE THREAD

**Issue by DelphineChabanne** [biomodhub/biomod2#200]
Hi,

Is there a possibility to tune the models when working with multiple datasets created via 'random' selection (pseudo-absence).
I managed to get the tune done using a dataset that has presence and TRUE absence. However, if I use a random selection of cells (categorized as pseudo-absence then), the following error message occurred:  'Error in { : task 1 failed - "missing value where TRUE/FALSE'.

I also tested several datasets separately where I randomly select cells but categorized them as TRUE absences. The results of the tune vary among datasets, thus why I am asking if there is something else, I could do when using multiple datasets to create my ensemble model. 

Thank you very much in advance for any advice. 

Cheers,
Delphine

**Comment by rpatin** [comment]
Hi Delphine,
Thank you  for reporting :pray: 

Unfortunately, `BIOMOD_Tuning` have no support for pseudo-absences dataset for now. This will likely not change in the short-term but there should be a rework of `BIOMOD_Tuning` coming, although I cannot promise a timing yet.

Cheers,
Rémi

**Comment by jllancaster** [comment]
Ah very interesting. I have not been able to get Biomod_Tuning to work with my dataset of presence-background data with no true absences. Assumed I was doing something wrong, but it sounds like this hasn’t been implemented yet, right? So much of the recent literature suggests tuning is needed, I’ve been focusing on getting this done for a bit now.

**Comment by jllancaster** [comment]
Very nice @rpatin, and thanks for the speedy reply!
