### ISSUE TITLE
Cross Validation and Variable Selection

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#205]
Hey,

at the moment im getting to start with biomod2 package. How do i implement Cross Validation in BIOMOD_Modelling? I found the BIOMOD_CrossValidation function but there is also nb.rep and data.splti.perc as arguments with BIOMOD_MODELLING. I dont understand whats the difference and when to use what.

My goal is to use BIOMOD to make a logistic GLM for an invasive species. I dont know exactly how to implement i.t I have already, like in the example, my formatted data as "myBiomodData". Now i dont know how to make a logistic GLM model with the BIOMOD_Modelling function. Also i want to select Variables. Before the modelling process, i am deleting variables from my set that a highly correlated. Is there a option to do like stepwise AIC/BIC with BIOMOD_Modelling?

Thanks in advance,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Thank you for reporting :pray: 
Did you have a look to the [biomod2 website](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) ? You can find some examples there that can help you understand how to use `biomod2`. You also have some examples in the help of the different functions (e.g. [here](https://biomodhub.github.io/biomod2/reference/BIOMOD_CrossValidation.html) )
In summary, there are two ways of implementing cross-validation:
1. internally within `BIOMOD_Modeling` with argument `nb.rep` (number of cross-validation dataset) and `data.split.perc` (percentage of data kept for calibration). This perform a robust random cross-validation.
2. additionally if you want more complex cross-validation (stratified, blocked ...) or have access to the cross-validation dataset prior to running the model you can use `BIOMOD_CrossValidation`. However note that the function is a bit less robust when using pseudo-absence dataset. Note that we plan on improving it on the short term though.

Concerning the question on GLM, `biomod2` automatically does a stepwise AIC selection using `stepAIC`. If needed this could be adjusted in the long term to include other options.

Best, 
Rémi

**Comment by GitBen01** [comment]
Hi Rémi,

thank you for answering so fast! 
Okay, i think, i'll be using internally cross validation with nb.rep and data.split.perc. Like you said, biomod2 automatically does stepwise AIC selection. Now if im using nb.rep = 10 and data.split.perc = 90%, i am doing 10 runs. To evaluate my model, i'll average the AUC scores over the 10 runs. The problem is, when i do so, i have a nice averaged AUC, but i get quite the different variable selection in each run. Which model with what variable selection do i use? I just dont quite get my head around this problem. Is there a way to determine whats the best GLM model out of all my runs? Or can i use the 100% model with the do.full.model = TRUE option as my final model (and take the AUC of this one?) and say i did a 10x cross validation with 90% of my data? Maybe you can help me.

Best,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Some workaround for this problem is to perform an ensemble modeling. Using `BIOMOD_EnsembleModeling` you can build models that aggregate your individual models (through the mean, median, committee averaging or weighted mean) and produce a single model that integrates the uncertainties from thos different models. As with other model you can get variable importance and response curves, that can help you understand which variables are important and how does your species respond to environment.
Best,
Rémi

**Comment by GitBen01** [comment]
Hi Rémi,
thank you very much! Its so helpful, to be able to ask questions here.!The last question I have is if it is possible to test for spatial autocorrelation via Biomod2 package?
Best,
Ben
