### ISSUE TITLE
How to calculate AUC

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#206]
Hey,

is it possible to calculate AUC value with Biomod2? As evaluation value you can get the ROC : Relative Operating Characteristic value. I dont quite get yet, how to compute the AUC. Maybe i just dont get the connection between ROC, Sensitivity and Specificy. For each Modeloutput i get 1 value for the three. How do i compute a curve? Is it possible to plot ROC-Curves?

Thanks in advance,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Thank you for reporting :pray: 
In fact, the evaluation that we call ROC is the AUC (calculated with function `auc` from package `pROC`).
Unfortunately `biomod2` does not allow you to plot the ROC-Curves, but I believe that if you have the AUC you have a limited use for the ROC-Curves.
I hope this is clearrer now. If not, feel free to ask additional questions.
Best,
Rémi
