### ISSUE TITLE
`get_predictions` fails with `data.table` `obj@type`

### ISSUE THREAD

**Issue by CeresBarros** [biomodhub/biomod2#209]
Hi there,

I'm generating projections from an ensemble model using `BIOMOD_EnsembleForecasting`, but passing `new.env` and `new.env.xy` as `data.tables` , instead of rasters or `data.frames`.

This is leading to an error in `get_predictions`  when it checks `obj@type` because R 4.2 doesn't allow a length >1 vector inside an `if` statement.

```
  if (obj@type == "SpatRaster") {   <-------------------------- here
    if (length(grep("EM|merged", names(out))) > 0) {
      keep_layers <- .filter_outputs.vec(names(out), obj.type = "em", 
        subset.list = list(full.name = full.name, merged.by.PA = merged.by.PA, 
          merged.by.run = merged.by.run, merged.by.algo = merged.by.algo, 
          filtered.by = filtered.by, algo = algo))
    }
    else {
      keep_layers <- .filter_outputs.vec(names(out), obj.type = "mod", 
        subset.list = list(full.name = full.name, PA = PA, 
          run = run, algo = algo))
    }
    out <- subset(out, keep_layers)
  }
  ```
  Because in my case:
  ```
  Browse[5]> obj@type 
[1] "data.table" "data.frame"
  ```

I'm using:
```
Browse[5]> packageVersion("biomod2")
[1] ‘4.2.2’
```

**Comment by rpatin** [comment]
Hi Ceres,
Thank you for reporting :pray: 
The bug was fixed in the development branch and should be released on the main branch within a few weeks (see comments in the PR for more details https://github.com/biomodhub/biomod2/pull/210)
Thanks again for the bug-spotting and solution proposed!
Best,
Rémi
