### ISSUE TITLE
Merge projected outputs

### ISSUE THREAD

**Issue by PhilipFaure** [biomodhub/biomod2#215]
Hi,

Given one cannot use different pseudo-absence points on different types of models to ensemble them together (https://github.com/biomodhub/biomod2/issues/138#issue-1455913947), is there a way to merge projected model outputs together manually? For example, as an alternative, could one run three models with X, Y, and Z number of pseudo-absences, then once you have the final tif files of habitat suitability (for each model) across your study area, ensemble them together into one projected file.

I realize this is not a bug, but instead a question on whether [1] this would be statistically correct to do, and [2] how can one code this?

**Comment by PhilipFaure** [comment]
I've noticed that the following code means multiple models. Would this be similar to what Biomod2 is doing when it ensembles the final merged model? Or is it not advised to do this?

`library(raster)

GLM <- raster("./individual_projections/proj_XXXX_PA1_RUN1_GLM.tif")
Maxent <- raster("./individual_projections/proj_XXXX_PA1_RUN1_MAXENT.tif")
MaxNet <- raster("./individual_projections/proj_XXXX_PA1_RUN1_MAXNET.tif")

stck <- stack( GLM, Maxent, MaxNet)

stack_mean <- calc(stck, fun = mean, na.rm = T)

writeRaster(x = stack_mean,
            filename = "./individual_projections/stack_mean.tif",
            driver = "GeoTiff")`

**Comment by rpatin** [comment]
Hi Phillip,
Thank you for reporting :pray: 

First, note that with the upcoming `biomod2` version that we are currently developing, you will be able to use different pseudo-absences dataset for different models. Hopefully it should be out in a few weeks.

Meanwhile you can do as you suggested, i.e. running different `biomod2` workflow and combining manually the models. The only downside is that you won't get easily the additional information provided by `biomod2` (model evaluation, variable importance).

You can do a mean ensemble model as you pointed out but you can also use other type of ensemble models (committee averaging, median, coefficient of variation ... full list available [here](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html))

Best,
Rémi

**Comment by PhilipFaure** [comment]
Hi Rémi - I'm glad to hear this functionality will be included in the upcoming version. Thanks for the quick feedback!

**Comment by rpatin** [comment]
Hi Phillip,
Quick update, the github up-to-date version now has support for pseudo-absence dataset of different size as well as association of algorithm to different pseudo-absence dataset.
Best,
Rémi
