### ISSUE TITLE
Rangesize_Problem

### ISSUE THREAD

**Issue by JiangXin-NWU** [biomodhub/biomod2#217]
Hello everyone!
  I've encounted a problem, I try to calculate the absolute number of locations lost,stable,and gain from projection of ensemble in different scenarios ,current and the future, so as the explanation from the function of Rangesize said.I need binary projection object, but the problem is when i perform the process of  projection, there is no .grd object in my folder, but a .tiff object, but I saw other's video and I typed the same code, other people can get a .grd object then do the rangesize happily,but I'm not (only unhappy for a day). So i can get a binary object for rangesize analysis.  if there is any solution for this, I want to learn biomod2 well and publish a paper......thank you very much，for your answer，and so sorry for my poor English that may make you confused.

```
   myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             bm.proj = mybiomodprojection,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
```
NO .grd file

![image](https://user-images.githubusercontent.com/127280827/226278270-6afa9421-ca5c-462c-9c7b-e4287f5cf209.png)

**So I can't use the below code to get binary projection to analyze the rangesize**
### proj.current111 <- raster::stack("C:/Users/Administrator/Desktop/test1/Biomod2/A/proj_currentEM/proj_CurrentEM_A_ensemble.grd")

**Comment by MayaGueguen** [comment]
Hello there,

Indeed, to use and compute range sizes, you need to use your projection maps transformed as binary.
`.grd` is a format of `raster` files, as well as `.tif`. In the past year, we change to `.tif` format as it is easier to manage and most commonly used by people, but you can deal with them the same way as the `.grd` files :sun_with_face: 

In your case however, it seems that you only have the probability maps in your projection folder, and that you are missing the binary maps. To get them, you need to specify a metric (using the `metric.binary` parameter) when calling the [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function which will be used to transform the probabilities into `0` or `1` values.

Hope it helps
Maya

**Comment by JiangXin-NWU** [comment]
Thanks Maya,thank you for your kind and helpful reply.I will try it as soon as possible in this night (it's 19:23).I read the function how to use BIOMD_EnsembleForecasting several days ago, and get confused,only when i typed the following codes,then I can get the ensemble-projection. I have no idea why there are two codes, and what's their connection. So I watch other people's video (bought from one person) and use ther codes, I missed the parameter-metric.binary.   Thanks Maya（sounds like a singer's name）.

**Comment by JiangXin-NWU** [comment]
# Project ensemble models (from single projections)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             bm.proj = myBiomodProj,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')

# Project ensemble models (building single projections)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
myBiomodEMProj
plot(myBiomodEMProj)
from the R packages
others' code
myBiomodProj <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  bm.proj = mybiomodprojection,
  proj.name = 'currentEM1',
  models.chosen = "all",
  binary.meth = c('TSS','ROC'),
)

**Comment by JiangXin-NWU** [comment]
# Project ensemble models (from single projections)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             bm.proj = myBiomodProj,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')

# Project ensemble models (building single projections)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
myBiomodEMProj
plot(myBiomodEMProj)
**the above codes from the R packages**
**the following code I copy others'**
 myBiomodProj <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  bm.proj = mybiomodprojection,
  proj.name = 'currentEM1',
  models.chosen = "all",
  binary.meth = c('TSS','ROC'),
)
