### ISSUE TITLE
Categorical variables error message 

### ISSUE THREAD

**Issue by ellalewi547** [biomodhub/biomod2#218]
Hello, 

I have 2 categorical variables in my stack and I assigned them as factors at the stage of the rasterstack as so: 
```
mystack[[9]] <- as.factor(mystack[[9]])
mystack[[9]]
mystack[[10]] <- as.factor(mystack[[10]])
mystack[[10]]
```
However, when I have conducted the first projection on the current environment, I had this error message:
```
Error in { : task 10 failed - "non-conformable arguments"
In addition: There were 50 or more warnings (use warnings() to see the first 50)
3: In Ops.factor(x, min) : ‘-’ not meaningful for factors
4: In Ops.factor(x, min) : ‘-’ not meaningful for factors
5: In Ops.factor(x, min) : ‘-’ not meaningful for factors
```
Is this an issue with the categorical variables? Am I meant to assign them as factors when they are as rasters instead? Is this error message an issue with the categorical variables? 
I can also send over the raster stack layers if needed. 

Thank you in advance! 
Ella :)

**Comment by MayaGueguen** [comment]
Hello Ella,

Thank you for opening a separate issue for this question :pray: 
Always cool to keep things clear :sun_with_face: 

Could you show me what are the levels of your 2 categorical variables ?
```
levels(mystack[[9]])
levels(mystack[[10]])
```
It appears that we are trying at some point to apply a `min` operation over those factors.

Maya

**Comment by ellalewi547** [comment]
Hi Maya, thank you so much for your swift reply.

`levels(mystack[[9]])
[[1]]
   ID
1   0
2   1
3   2
4   3
5   4
6   5
7   6
8   7
9   8
10  9
11 10
12 11
13 12
14 13
15 14
16 15
17 16
18 17
19 18
20 19
21 20`

`
> levels(mystack[[10]])
[[1]]
   ID
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17`

**Comment by ellalewi547** [comment]
Thank you Maya. 
Sorry, do you mean the raster stack or the code used to format the rasterstack? 

`> Summary(mystack)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Summary’ for signature ‘"numeric"’
`

**Comment by ellalewi547** [comment]
This is the layers for the two categorical values: 
`[[9]]
class      : RasterLayer 
dimensions : 4008, 4699, 18833592  (nrow, ncol, ncell)
resolution : 1000, 1000  (x, y)
extent     : 2625837, 7324837, 1416579, 5424579  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs 
source     : dominant tree species.tif 
names      : dominant.tree.species.tif 
values     : 0, 20  (min, max)
attributes :
       ID
 from:  0
  to : 20


[[10]]
class      : RasterLayer 
dimensions : 4008, 4699, 18833592  (nrow, ncol, ncell)
resolution : 1000, 1000  (x, y)
extent     : 2625837, 7324837, 1416579, 5424579  (xmin, xmax, ymin, ymax)
crs        : +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs 
source     : land cover.tif 
names      : land.cover.tif 
values     : 1, 17  (min, max)
attributes :
       ID
 from:  1
  to : 17`

**Comment by MayaGueguen** [comment]
Thank you Ella, nothing suspicious here either.

So could you send me please : 
- the output of `show(myBiomodData)`
- the output of `show(myBiomodModelOut)`
- the code you used to do [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) ?
- the exact error you get and at which step you get it (if possible, _when running your code without parallelization_, so with `nb.cpu = 1`)

Thanks in advance,
Maya

**Comment by ellalewi547** [comment]
No problem, thank you.


1. `show(myBiomodData)`

`dir.name =  .

sp.name =  Martesmartes

	 2306 presences,  0 true absences and  3960 undefined points in dataset


	 10 explanatory variables

 reference.elevation.tif canopy.height.tif  forest.density.tif    NVDI.tif       rainfall.tif      slope.tif      temperature.tif 
 Min.   :  -4.0          Min.   : 0.00000   Min.   : 0.00      Min.   :0.0309   Min.   : 14.38   Min.   : 0.000   Min.   :-4.553  
 1st Qu.:  90.0          1st Qu.: 0.03546   1st Qu.: 0.00      1st Qu.:0.6288   1st Qu.: 49.03   1st Qu.: 0.435   1st Qu.: 5.610  
 Median : 216.0          Median : 9.07404   Median :26.88      Median :0.6990   Median : 57.55   Median : 1.179   Median : 8.409  
 Mean   : 403.2          Mean   : 9.81795   Mean   :29.66      Mean   :0.6654   Mean   : 66.03   Mean   : 2.531   Mean   : 7.974  
 3rd Qu.: 552.0          3rd Qu.:17.18216   3rd Qu.:51.52      3rd Qu.:0.7441   3rd Qu.: 74.05   3rd Qu.: 3.056   3rd Qu.:10.499  
 Max.   :3136.0          Max.   :38.64663   Max.   :99.02      Max.   :0.8385   Max.   :297.52   Max.   :32.873   Max.   :19.880  
    TPI.tif          dominant.tree.species.tif land.cover.tif  
 Min.   :-171.0094   Min.   : 0.00             Min.   : 1.000  
 1st Qu.:  -4.1098   1st Qu.: 3.00             1st Qu.: 3.000  
 Median :  -0.3517   Median :14.00             Median : 5.000  
 Mean   :  -0.9144   Mean   :10.73             Mean   : 5.816  
 3rd Qu.:   2.6150   3rd Qu.:16.00             3rd Qu.: 7.000  
 Max.   : 199.8699   Max.   :20.00             Max.   :17.000  `



2.`show(myBiomodModelOut)`

`Modeling folder : .

Species modeled : Martesmartes

Modeling id : 1679061453

Considered variables : reference.elevation.tif canopy.height.tif forest.density.tif NVDI.tif rainfall.tif slope.tif temperature.tif 
TPI.tif dominant.tree.species.tif land.cover.tif


Computed Models :  Martesmartes_PA1_RUN1_GLM Martesmartes_PA1_RUN1_GAM Martesmartes_PA1_RUN1_GBM Martesmartes_PA1_RUN1_CTA 
Martesmartes_PA1_RUN1_ANN Martesmartes_PA1_RUN1_SRE Martesmartes_PA1_RUN1_FDA Martesmartes_PA1_RUN1_MARS Martesmartes_PA1_RUN1_RF 
Martesmartes_PA1_RUN1_MAXNET Martesmartes_PA1_RUN2_GLM Martesmartes_PA1_RUN2_GAM Martesmartes_PA1_RUN2_GBM Martesmartes_PA1_RUN2_CTA 
Martesmartes_PA1_RUN2_ANN Martesmartes_PA1_RUN2_SRE Martesmartes_PA1_RUN2_FDA Martesmartes_PA1_RUN2_MARS Martesmartes_PA1_RUN2_RF 
Martesmartes_PA1_RUN2_MAXNET Martesmartes_PA1_RUN3_GLM Martesmartes_PA1_RUN3_GAM Martesmartes_PA1_RUN3_GBM Martesmartes_PA1_RUN3_CTA 
Martesmartes_PA1_RUN3_ANN Martesmartes_PA1_RUN3_SRE Martesmartes_PA1_RUN3_FDA Martesmartes_PA1_RUN3_MARS Martesmartes_PA1_RUN3_RF 
Martesmartes_PA1_RUN3_MAXNET Martesmartes_PA2_RUN1_GLM Martesmartes_PA2_RUN1_GAM Martesmartes_PA2_RUN1_GBM Martesmartes_PA2_RUN1_CTA 
Martesmartes_PA2_RUN1_ANN Martesmartes_PA2_RUN1_SRE Martesmartes_PA2_RUN1_FDA Martesmartes_PA2_RUN1_MARS Martesmartes_PA2_RUN1_RF 
Martesmartes_PA2_RUN1_MAXNET Martesmartes_PA2_RUN2_GLM Martesmartes_PA2_RUN2_GAM Martesmartes_PA2_RUN2_GBM Martesmartes_PA2_RUN2_CTA 
Martesmartes_PA2_RUN2_ANN Martesmartes_PA2_RUN2_SRE Martesmartes_PA2_RUN2_FDA Martesmartes_PA2_RUN2_MARS Martesmartes_PA2_RUN2_RF 
Martesmartes_PA2_RUN2_MAXNET Martesmartes_PA2_RUN3_GLM Martesmartes_PA2_RUN3_GAM Martesmartes_PA2_RUN3_GBM Martesmartes_PA2_RUN3_CTA 
Martesmartes_PA2_RUN3_ANN Martesmartes_PA2_RUN3_SRE Martesmartes_PA2_RUN3_FDA Martesmartes_PA2_RUN3_MARS Martesmartes_PA2_RUN3_RF 
Martesmartes_PA2_RUN3_MAXNET Martesmartes_PA3_RUN1_GLM Martesmartes_PA3_RUN1_GAM Martesmartes_PA3_RUN1_GBM Martesmartes_PA3_RUN1_CTA 
Martesmartes_PA3_RUN1_ANN Martesmartes_PA3_RUN1_SRE Martesmartes_PA3_RUN1_FDA Martesmartes_PA3_RUN1_MARS Martesmartes_PA3_RUN1_RF 
Martesmartes_PA3_RUN1_MAXNET Martesmartes_PA3_RUN2_GLM Martesmartes_PA3_RUN2_GAM Martesmartes_PA3_RUN2_GBM Martesmartes_PA3_RUN2_CTA 
Martesmartes_PA3_RUN2_ANN Martesmartes_PA3_RUN2_SRE Martesmartes_PA3_RUN2_FDA Martesmartes_PA3_RUN2_MARS Martesmartes_PA3_RUN2_RF 
Martesmartes_PA3_RUN2_MAXNET Martesmartes_PA3_RUN3_GLM Martesmartes_PA3_RUN3_GAM Martesmartes_PA3_RUN3_GBM Martesmartes_PA3_RUN3_CTA 
Martesmartes_PA3_RUN3_ANN Martesmartes_PA3_RUN3_SRE Martesmartes_PA3_RUN3_FDA Martesmartes_PA3_RUN3_MARS Martesmartes_PA3_RUN3_RF 
Martesmartes_PA3_RUN3_MAXNET


Failed Models :  none`

3.`myBiomodProjEuropeRasters <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut, 
  new.env = MyExpl3, 
  proj.name = 'currentCategories', 
  models.chosen = 'all', 
  metric.binary = 'TSS', 
  metric.filter = NULL,
  compress = TRUE, 
  build.clamping.mask = TRUE, 
  nb.cpu = 10,
  seed.val = 1
)`

MyExpl3 is the current raster stack but cropped and masked to Britain shapefile.  
I get the error after it has finished the BIOMOD_Projection. I am just running the nb.cpu = 1 but it will take a while. the exact error message has been screenshotted, as following: 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/110492601/226378095-0e2fbad9-5b80-4e2a-a728-d128460b1bd6.png)

Thank you.
