### ISSUE TITLE
RangeSize results question

### ISSUE THREAD

**Issue by JiangXin-NWU** [biomodhub/biomod2#219]
Hi，I have the RangeSize results with Maya's help，but the result that I don't know how to handle.
![image](https://user-images.githubusercontent.com/127280827/226386245-5c51dfa3-1ba6-4a58-a886-a827dc33ee01.png)
Emmm,there are two questions that I want to ask for help.The first one is that there are two results,A_EMeanByTSS_...and A_EMcaByTSS_...,which one should I choose. And it seems that they are the results from BIOMOD_ENsembleModeling, in which I choose em.algo=c('Emean','EMca').So i guess I should choose a better EM from them, which data should be used？I saw many people use testing.data to assess which model is better,but there is no testing data that may be blamed to  a new version of Biomod2(I'm not sure)
![image](https://user-images.githubusercontent.com/127280827/226388353-c029a775-6f15-4239-95d7-127a3200c2e4.png)
The second question is why there are so many 0 in the results，and I also check their map in Arcgis， but it seems that they look same very much.
Thank you，thank you，thank you！There is a saying，“An important thing should be repeated for three times”😂

**Comment by JiangXin-NWU** [comment]
1.Hi，Rémi,thanks for your kind and helpful reply.I'd like to rectify one thing that the EnsembleModeling projection in current and  EnsembleModeling projection in 2050_45 look the same,but I don't know the reason(Indeed I choose the different  envieonmental variables in different senarios).Rémi,I just want a rangesize result,but the results show A_EMcaByTSS_....and A_EMeanByTSS_..., So I'm confused and just want one better model from them(A_EMcaByTSS_....and A_EMeanByTSS_...).So I kept asking where they are from, you mentioned the model choosed depends on what I intend to do,I want to make a table that shows the gain,loss,stable,and pergain,perloss between two EM projection (current and 2050_4.5).So whether there is a simple solution for me to decide which model I should choose?
2.Rémi,thanks I got it.Sometimes I'm very confused by other people's video and some related document,but the only person should be blamed is myself.I lack some related mathmatics knowledge and own poor programming knowledge. I wonder wether there is any new document file.....
3.I don't catch it, Rémi.You mean that rangesize(proj.current = CurrentProj, proj.future = FutureProj),the CurrentProj and the FutureProj that I used are same?
Thanks,Rémi,looking for your reply.

**Comment by JiangXin-NWU** [comment]
Hi,Rémi,In fact,I set nb.rep = 3 in BIOMOD_Modeling,and I got the results for 24 models, 
![image](https://user-images.githubusercontent.com/127280827/226631620-2d3993b6-45f6-403e-a85d-c651e1b16c77.png)
![image](https://user-images.githubusercontent.com/127280827/226633330-8967918c-d68c-4ef2-95f2-9d0ca625c667.png)
Rémi，If I‘d like to make a table to show their difference, show which model is better.Which metric should be used,validation（If I don't get it wrong）?such as，nb.rep=3，then I get A_PA1_RUN1_MARS PA1 RUN1、A_PA1_RUN2_MARS PA1 RUN2、 A_PA1_RUN3_MARS PA1 RUN3，whether I should get 
 its mean TSS values [（Validation1+validation2+validation3）/3]？Then I can make a table，such as MARS TSS 0.95、GBM TSS 0.93......（random number）.

**Comment by rpatin** [comment]
Hi @JiangXin-NWU 
It is up to you to build your analysis plan (although there are plenty of litterature talking about that). 
Generally:
- either you build a single (or a few) model which have satisfying validation metric (the column validation here). And then you use the predictions from your few models and even could compare them
- or you build several models with different algorithm, pseudo-absences dataset, cross-validation repetition and then you can study:
  - heterogeneity in model performance (distribution of evaluation metric). Is algorithm/pseudoabsence/crossvalidation important for model performance. If so, you may wonder why (especially for pseudo absences and crossvalidation dataset)
  - variable importance: are the important variables always the same. If not there may be some thinking about it
  - if you want to have a single predictions you can do ensemble modeling and do the mean/weighted mean averaging of the single model (you can filter models to have a minimum performance metric)
  - other ensemble models can help you understand the confidence in your results: EMcv shows you the place where model prediction are the most variables among individual models.
  - Committee averaging (EMca) can do both (when you have 0 or 1, all model agree ; with value at 0.5 there is a large discrepancy between models)
  - [...]

In anycase I would not suggest you to select the best model among a large number of models with different algorithm, set of pseudo absences etc.

Hope this helps,
Best,
Rémi

**Comment by JiangXin-NWU** [comment]
Thanks,Rémi,many people just use this model,use that model,but they don't explain why in many times but just do that. I even can't find anything about this,just do choose what others choose.Thanks,Rémi,thanks.
