### ISSUE TITLE
weights of true absences versus pseudo absences

### ISSUE THREAD

**Issue by arnaudlyet** [biomodhub/biomod2#224]
Hi Wilfried and all,

I am trying to run a model with a mix of true and pseudo absences and I could not understand with the documentation if the default setting of the BIOMOD_Modeling() function would assign different weights to true absence vs pseudo abundance.

One could assume that true absences would be given a weight of 1 while pseudo absence would be given a weight of nb observations / nb of pseudo absences (with prevalence of .5). Is that correct assumption?

thank you for your help
Arno

**Comment by rpatin** [comment]
Hi Arno,
Thank you for reporting :pray: 

1. First concerning `biomod2` behaviour, the default setting do not consider difference between true absences and pseudo-absences. So if you ask for prevalence = 0.5, it will set the same automatic weight for true absences and pseudo-absences. You can still use argument `weights` in `BIOMOD_Modeling` and set the weights yourself.
2. Mixing true absences and pseudo absences will not be accepted anymore in future biomod2 version. It will still be possible if you mix them outside of `biomod2` (i.e. if you use argument `PA.user.table` in `BIOMOD_FormatingData`) but will not be automatically done when using `BIOMOD_FormatingData`. We consider that if you do not have enough true absences, it is better to only use pseudo-absences and keep your absences for a validation dataset for instance.
3. As I just said, we would not advise to mix true absences with pseudo absences. If you choose to do so, you can try to set higher weights for true absences compared to pseudo-absences _(for that you will have to use argument `weights` and specify the weights yourself)_. However we have rather few feedbacks on such practice to share with you.

Best,
Rémi
