### ISSUE TITLE
About myBiomodModelOut

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#232]
Hi,
When I run the model, I get the following error, but nothing similar happened when I ran it before this.
Code：
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.d,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    nb.rep = 10,
                                    data.split.perc = 75,
                                    # data.split.table = myBiomodCV,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC','KAPPA'),
                                    do.full.models = FALSE)

Error in { : task 10 failed - "cannot open the connection"
In addition: Warning messages:
1: executing %dopar% sequentially: no parallel backend registered 
2: In file(con, "r") :
  cannot open file './shazao/models/AllModels/shazao_PA1_RUN1_MAXENT_outputs/maxent.stderr': Permission denied
> myBiomodModelOut
Error: object 'myBiomodModelOut' not found

**Comment by luciamanzanares** [comment]
I had an error like that, want I find out was in the model selection I had MAXENT but didn't specify where the maxen.jar file was, so the program couldn't find it.

**Comment by 675979649** [comment]
I found the problem in this step：Pseudo-absences extraction
When I use the "random" method, it doesn't report an error, but when I use the "disk" method, I get this problem

**Comment by 675979649** [comment]
Thank you for your reply. The following is my code and occurrence data：
library(terra)
library(biomod2)
library(ggplot2)
library(gridExtra)
library(sp)
library(raster)
library(rasterVis)
library(lattice)

DataSpecies <- read.csv('F:/R/tianniu/tianniu.csv')  
head(DataSpecies) 
myRespName <- 'tianniu'
myResp <- as.numeric(DataSpecies[, myRespName])
myRespXY <- DataSpecies[, c('x', 'y')]

bio_2 <- raster('F:/R/tianniu/bio2.asc')
bio_3 <- raster('F:/R/tianniu/bio3.asc')
bio_8 <- raster('F:/R/tianniu/bio8.asc')
bio_9 <- raster('F:/R/tianniu/bio9.asc')
bio_14 <- raster('F:/R/tianniu/bio14.asc')
bio_15 <- raster('F:/R/tianniu/bio15.asc')
bio_18 <- raster('F:/R/tianniu/bio18.asc')
bio_19 <- raster('F:/R/tianniu/bio19.asc')
elev <- raster('F:/R/tianniu/bio20.asc')
myExpl <- stack(bio_2 , bio_3 , bio_14 , bio_15, bio_18, bio_19, elev)

#将真实存在数据转化为潜在的存在缺失数据
myResp.PA <- ifelse(myResp == 1, 1, NA)

myBiomodData.d <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 3,
                                       PA.nb.absences = 1000,
                                       PA.strategy = 'disk',
                                       PA.dist.min = 100000,
                                       PA.dist.max = 10000000,
                                       filter.raster = TRUE)

##建模参数设置------------------------------------------------------------------
myBiomodOptions <- BIOMOD_ModelingOptions() #用默认参数建模

##################################################运行单一模型
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.r,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    nb.rep = 10,
                                    data.split.perc = 75,
                                    # data.split.table = myBiomodCV,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC','KAPPA'),
                                    do.full.models = FALSE)
[tianniu.csv](https://github.com/biomodhub/biomod2/files/11158583/tianniu.csv)

**Comment by 675979649** [comment]
> myBiomodData.d

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  shazao

	 2204 presences,  0 true absences and  1739 undefined points in dataset


	 10 explanatory variables

      bio2             bio3              bio8              bio9             bio14            bio15             bio18            bio19            bio20            bio21       
 Min.   : 1.000   Min.   :  9.169   Min.   :-37.541   Min.   :-39.380   Min.   :  0.00   Min.   :  6.245   Min.   :   0.0   Min.   :   0.0   Min.   :-152.0   Min.   : 0.000  
 1st Qu.: 8.581   1st Qu.: 26.066   1st Qu.:  8.816   1st Qu.: -4.933   1st Qu.:  6.00   1st Qu.: 26.772   1st Qu.:  89.0   1st Qu.:  36.0   1st Qu.: 134.5   1st Qu.: 5.200  
 Median :10.522   Median : 34.515   Median : 17.375   Median :  5.056   Median : 14.00   Median : 44.802   Median : 160.0   Median :  86.0   Median : 358.0   Median : 6.500  
 Mean   :11.015   Mean   : 39.083   Mean   : 15.020   Mean   :  5.359   Mean   : 23.14   Mean   : 51.260   Mean   : 190.3   Mean   : 145.3   Mean   : 633.2   Mean   : 5.964  
 3rd Qu.:13.504   3rd Qu.: 47.321   3rd Qu.: 22.586   3rd Qu.: 20.822   3rd Qu.: 30.00   3rd Qu.: 67.807   3rd Qu.: 232.0   3rd Qu.: 164.0   3rd Qu.: 927.5   3rd Qu.: 7.400  
 Max.   :19.809   Max.   :100.000   Max.   : 36.662   Max.   : 36.913   Max.   :358.00   Max.   :192.415   Max.   :1810.0   Max.   :2043.0   Max.   :5735.0   Max.   :10.600  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> plot(myBiomodData.d)
载入需要的名字空间：tidyterra
载入需要的名字空间：ggtext
SpatRaster resampled to ncells = 5e+05
$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 10556, 2  (geometries, attributes)
 extent      : -178.875, 179.4583, -48.75, 83.45833  (xmin, xmax, ymin, ymax)
 coord. ref. :  
 names       :  resp         dataset
 type        : <num>           <chr>
 values      :    10 Initial dataset
                  10 Initial dataset
                  10 Initial dataset

$data.label
                              9                              10                              11                              12                              19                              20 
                "**Presences**"       "Presences (calibration)"        "Presences (validation)"        "Presences (evaluation)"             "**True Absences**"   "True Absences (calibration)" 
                             21                              22                              29                              30                              31                               1 
   "True Absences (validation)"    "True Absences (evaluation)"           "**Pseudo-Absences**" "Pseudo-Absences (calibration)"  "Pseudo-Absences (validation)"                    "Background" 

$data.plot

![image](https://user-images.githubusercontent.com/55433348/230255437-403e94c6-7176-4f30-baa2-b0ec5079ed52.png)

**Comment by 675979649** [comment]
Hi,
Subsequent errors that also occur when Do Single Models Projection.

Code:
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE)


Error: std::bad_alloc                     
In addition: Warning message:
[rast] SRS do not match 
> myBiomodProj
Error: object 'myBiomodProj' not found

![image](https://user-images.githubusercontent.com/55433348/230374923-a3e1c01a-00ab-4751-b947-564e1a879126.png)
![image](https://user-images.githubusercontent.com/55433348/230374953-1c21d026-f96f-417e-86b2-b4888f380125.png)

**Comment by 675979649** [comment]
Hello,
Today, I modified the above code:
myBiomodProjtn <- BIOMOD_Projection(bm.mod = myBiomodModelOuttn,
                                  proj.name = 'Current',
                                  new.env = myExpl1,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE,
                                  **overwrite=TRUE**)
Successful operation
Unfortunately, EM model has gone wrong again

> myBiomodEMProjtn <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEMtn, 
+                                              bm.proj = myBiomodProjtn,
+                                              models.chosen = 'all',
+                                              metric.binary = 'all',
+                                              metric.filter = 'all',
+                                              overwrite=TRUE)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Creating suitable Workdir...
Error in .fun_testIfIn(TRUE, "full.name", subset.list[["full.name"]],  : 
full.name must be 'lyr1', 'lyr1', 'lyr1', 'X1', 'pred', 'X2', 'pred', 'A.glabripennis', 'X1', './A.glabripennis/models/AllModels/A.glabripennis_PA1_RUN1_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', 'X2', 'pred', 'A.glabripennis', 'X1', './A.glabripennis/models/AllModels/A.glabripennis_PA1_RUN2_MAXENT_outputs/projMaxent.asc' or 'lyr1

**Comment by rpatin** [comment]
Hello Weicheng Ding,
I must admit I got lost in the errors you encountered and the steps you did before encountering the errors.
Could you share the environmental raster that you use as well as a script to reproduce your issue(s) ? You can also share data by mail (remi.patin@univ-grenoble-alpes.fr).
Best,
Rémi

**Comment by 675979649** [comment]
Hi Rémi,
The relevant data has been sent to you by email, thanks for your reply!
Best,
Weicheng

**Comment by rpatin** [comment]
The issue should be solved now (see https://github.com/biomodhub/biomod2/issues/233)
