### ISSUE TITLE
Error messege in BIOMOD_FormatingData

### ISSUE THREAD

**Issue by madeka89** [biomodhub/biomod2#234]
Hello all,

I am having issues formatting PA, the error I get is: 

```
Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterStack” to “SpatRaster”

```
Current code:
```
library(spatstat)
library(biomod2)
library(terra)
library(raster)
setwd("F:\\Ebola")
data<-read.csv("F:\\Ebola\\OccuranceData2.csv")
head(data)
myRespName <- 'Ebola'
myResp <- as.numeric(data[, myRespName])
myRespXY <- data[, c('X_WGS84', 'Y_WGS84')]
myExpl<-stack("F:\\Ebola\\TIFFNew\\ndvic1.tif",
              "F:\\Ebola\\TIFFNew\\ndvic2.tif")
plot(myExpl)

# # Format Data with pseudo-absences : random method
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = myExpl,
                                        resp.xy = myRespXY,
                                        resp.name = myRespName,
                                        PA.nb.rep = 1,
                                        PA.nb.absences = 1000,
                                        PA.strategy = 'random')

```
Thanks for your time!

**Comment by rpatin** [comment]
Hi @madeka89,
Thank you for reporting :pray: 
Could you also share:
- the output of `sessionInfo()` 
- the output of `show(myExpl)`
- the output of `rast(myExpl)`

Thanks in advance,
Best,
Rémi

**Comment by madeka89** [comment]
<html>
<body>


R version 4.1.1 (2021-08-10) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 19045)  Matrix products: default  locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           [5] LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] raster_3.5-2           sp_1.4-6               terra_1.7-23            [4] biomod2_4.2-2          spatstat_3.0-3         spatstat.linnet_3.0-6   [7] spatstat.model_3.2-1   rpart_4.1-15           spatstat.explore_3.1-0 [10] nlme_3.1-152           spatstat.random_3.1-4  spatstat.geom_3.1-0    [13] spatstat.data_3.0-1     loaded via a namespace (and not attached):  [1] fs_1.5.2              spatstat.sparse_3.0-1 usethis_2.1.6          [4] devtools_2.4.4        tools_4.1.1           profvis_0.3.7          [7] rgdal_1.6-5           utf8_1.2.2            R6_2.5.1              [10] DBI_1.1.3             mgcv_1.8-36           colorspace_2.0-2      [13] nnet_7.3-16           maxnet_0.1.4          urlchecker_1.0.1      [16] gbm_2.1.8             tidyselect_1.1.2      prettyunits_1.1.1     [19] processx_3.5.2        compiler_4.1.1        mda_0.5-2             [22] cli_3.3.0             scales_1.2.1          randomForest_4.6-14   [25] callr_3.7.0           plotmo_3.6.1          PresenceAbsence_1.1.9 [28] goftest_1.2-3         stringr_1.4.0         digest_0.6.29         [31] spatstat.utils_3.0-2  pkgconfig_2.0.3       htmltools_0.5.5       [34] sessioninfo_1.2.2     plotrix_3.8-2         fastmap_1.1.0         [37] htmlwidgets_1.5.4     rlang_1.0.4           rstudioapi_0.14       [40] shiny_1.7.4           generics_0.1.3        dplyr_1.0.7           [43] magrittr_2.0.1        Formula_1.2-4         Matrix_1.3-4          [46] Rcpp_1.0.10           munsell_0.5.0         fansi_0.5.0           [49] abind_1.4-5           lifecycle_1.0.1       pROC_1.18.0           [52] stringi_1.7.6         MASS_7.3-54           plyr_1.8.6            [55] pkgbuild_1.3.1        grid_4.1.1            earth_5.3.1           [58] promises_1.2.0.1      crayon_1.5.1          miniUI_0.1.1.1        [61] deldir_1.0-5          lattice_0.20-44       splines_4.1.1         [64] tensor_1.5            ps_1.6.0              pillar_1.8.1          [67] reshape2_1.4.4        codetools_0.2-18      pkgload_1.3.0         [70] glue_1.4.2            data.table_1.14.2     remotes_2.4.2         [73] vctrs_0.3.8           httpuv_1.6.3          foreach_1.5.2         [76] gtable_0.3.1          purrr_0.3.4           polyclip_1.10-0       [79] reshape_0.8.8         assertthat_0.2.1      cachem_1.0.6          [82] ggplot2_3.3.6         TeachingDemos_2.12    mime_0.12             [85] xtable_1.8-4          later_1.3.0           class_7.3-19          [88] survival_3.2-11       tibble_3.1.6          iterators_1.0.14      [91] memoise_2.0.1         ellipsis_0.3.2
--
 
> | >
>


</body>
</html>

**Comment by madeka89** [comment]
> show(myExpl)
class      : RasterStack 
dimensions : 811, 1427, 1157297, 2  (nrow, ncol, ncell, nlayers)
resolution : 0.04166667, 0.04166667  (x, y)
extent     : -17.54167, 41.91667, -18.04167, 15.75  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
names      : ndvic1, ndvic2 
min values :      0,      0 
max values :  33192,   9679

**Comment by madeka89** [comment]
> rast(myExpl)
Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterStack” to “SpatRaster”

**Comment by rpatin** [comment]
Hi @madeka89,
Thank you for the update :pray: 
Not sure what is happening there. Can you try loading the `.tif` with `terra` instead of `raster` ?
```
myExpl <- rast(c("F:\\Ebola\\TIFFNew\\ndvic1.tif",
              "F:\\Ebola\\TIFFNew\\ndvic2.tif"))
```
This should avoid the problem with conversion. _And will eventually be necessary as `raster` is deprecated and will disappeared by the end of the year_

Best,
Rémi

**Comment by madeka772** [comment]
Thank you! Everything is running smoothly.
