### ISSUE TITLE
Error in BIOMOD_PresenceOnly()

### ISSUE THREAD

**Issue by wildlifekarjee17** [biomodhub/biomod2#239]
Dear Team,

There is an issue while using BIOMOD_PresenceOnly(). ... I was using the default examples from the BIOMOD2 website.

Following are the examples:

```

# Evaluate models with Boyce index and MPA
 myBiomodPO <- BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut,   bm.em = myBiomodEM) 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Presence-Only Evaluation -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= 
Error in calib.lines[, 1] : incorrect number of dimensions 

# Evaluate models with Boyce index and MPA (using background data) 
  

myBiomodPO <- BIOMOD_PresenceOnly(bm.mod = myBiomodModelOut,  bm.em = myBiomodEM,  bg.env = values(myExpl))  


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Presence-Only Evaluation -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=       
 


! NAs have been automatically removed from bg.env dataError in calib.lines[, 1] : incorrect number of dimensions

```
 
![Screenshot (56)](https://user-images.githubusercontent.com/47804742/232332239-de485340-39f7-4f19-be23-3e579711dd13.png)

**Comment by rpatin** [comment]
Hello @wildlifekarjee17,
Thank you for reporting :pray: 
Indeed this is an oversight on our side, sorry for that.
The function as been fixed for current patch. So if you install the updated version with `devtools::install_github('biomodhub/biomod2')` it should now work properly. If not feel free to report again.
Best regards,
Rémi
