### ISSUE TITLE
Error Error in .local(obj, ...) : Unknown subinfo tag in Biomod_EnsembleModeling()

### ISSUE THREAD

**Issue by sainzvs** [biomodhub/biomod2#24]
I've detected the following error when excuting EnsembleModeling() function with a Pseudo-Absences dataset and em.by = 'PA_dataset+repet' setting. Exploring the source code oh this function it seems that the problem is here: 

if (inherits(get_formal_data(modeling.output, "BIOMOD.formated.data.PA")))

I tried by changing this code for the following one, and it worked.

if (inherits(get_formal_data(modeling.output), "BIOMOD.formated.data.PA"))

¿Is this change legitimate?

**Comment by DamienGeorges** [comment]
Thanks for repporting. That was a typo in the code. fixed now. Thanks again
