### ISSUE TITLE
Maxent Model Issue: Error in { : task 1 failed - "subscript out of bounds" 

### ISSUE THREAD

**Issue by wildlifekarjee17** [biomodhub/biomod2#240]
Maxent model failed to run. After fitting the model., an error message with warning [see reference pic below].  Usually,  no error can be noticed if someone used the default examples [BIOMOD2 WEBSITE].  However, while plotting the model callibration 'MAXENT' boxplot cann't be seen.  

FOLLOWING EXAMPLE:

```
 myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                     bm.options = myBiomodOptions,
                                    models = 'MAXENT',
                                     modeling.id = 'AllModels',
                                     CV.strategy = 'random',
                                     CV.nb.rep = 1,
                                     CV.perc = 0.8,
                                     var.import = 3,
                                     seed.val = 123,
                                     nb.cpu = 4,
                                     metric.eval = c('TSS','ROC'))
```
![Screenshot (58)](https://user-images.githubusercontent.com/47804742/232336743-91cd78e5-5642-4036-8aa5-ee07c796279a.png)

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...
Warning in .BIOMOD_Modeling.check.args(bm.format = bm.format, modeling.id = modeling.id,  :
  MAXENT has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.

	> Automatic weights creation to rise a 0.5 prevalence
Creating suitable Workdir...


Checking Cross-Validation arguments...

   > Random cross-validation selection
   !!! Some validation dataset do not have both presences and absences:  _allData_allRun



-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 5  environmental variables ( bio3 bio4 bio7 bio11 bio12 )
Number of evaluation repetitions : 2
Models selected :  

Total number of model runs: 0 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=--=-=-=- 



Error in { : task 1 failed - "subscript out of bounds"
In addition: Warning messages:
1: In bm_CrossValidation(bm.format = bm.format, strategy = CV.strategy,  :
  Some validation repetion do not have both presences and absences
2: In bm_RunModelsLoop(bm.format = bm.format, weights = weights, calib.lines = calib.lines,  :
  Parallelisation with `foreach` is not available for Windows. Sorry.
```

**Comment by rpatin** [comment]
Hi @wildlifekarjee17 
Thank you for reporting :pray:
A lot of information is available in the console output and it is always a good advice to read it carefully.
Here you had the following message:
```
Warning in .BIOMOD_Modeling.check.args(bm.format = bm.format, modeling.id = modeling.id,  :
  MAXENT has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.
```
It reads that you need to download file `maxent.jar` and put it in your working directory for `MAXENT` to be used within `biomod2`. Therefore `MAXENT` cannot be run. Thus, if you ask only for `MAXENT` it cannot work. Also note that the algorithm `MAXNET` is highly similar to `MAXENT` but also natively available within R and easily usable with `biomod2`.

Best,
Rémi

**Comment by wildlifekarjee17** [comment]
Dear @rpatin ,

Thanks a lot for this beautiful advice. It worked well.

I am using the default examples [GuloGulo Data] and I noticed validation scores partly fill with NA values while evaluation scores with complete NA [see reference screenshot]. Why this? Am I doing something wrong?

Thanks again
best regards
Ratnesh
![Screenshot (61)](https://user-images.githubusercontent.com/47804742/232750095-546b7664-47a9-4b23-a0c1-29f45feb9a3b.png)
.

**Comment by rpatin** [comment]
Hello Ratnesh,
Please avoid posting screenshots when you can copy-paste the content (here the evaluation table) :pray: 
Here you have built two kinds of models:
1. `GuloGulo_allData_RUN1_ALGO`
2. `GuloGulo_allData_allRun_ALGO`
The first set is a series of cross-validation models with a percentage of the dataset left out for validation. It allows a more independent evaluation of model performance than evaluation on the calibration data. Thus calibration of this models is not using the full dataset and sometimes people also want to build a model calibrated with the full dataset but without cross-validation. This is the second set of models. Thus you can see values in the validation column only for the first set of models  (with `RUN1`) as the second set (with `allRun`) uses all data for calibration.

If you do not want to build full models you need to set `CV.do.full.models = FALSE` in `BIOMOD_Modeling`.

I hope this is clearer now. If not feel free to update the issue.
Best regards,
Rémi
