### ISSUE TITLE
Projection of XY coordinates

### ISSUE THREAD

**Issue by beardant** [biomodhub/biomod2#241]
In all examples I find for Biomod2, the species data are presented in XY format with the projection WGS84 (EPSG 4326).
I was wondering whether Biomod2 also accepts species data in UTM format, e.g. crs 32610?

**Comment by rpatin** [comment]
Hi @beardant,
Thank you for reporting :pray: 
`biomod2` does not really take into account your projection system so you can feed it with any projection, as long as all the projected data (presence/absence coordinates & raster data) have the same projection. 
Hope this is clearer. If not feel free to precise your question,
Best regards,
Rémi
