### ISSUE TITLE
Error in MaxEnt tuning

### ISSUE THREAD

**Issue by momeni133** [biomodhub/biomod2#25]
Hello everyone,
Tuning works well for RF and GBM, but not for Maxent. Do you know how to solve this problem? I have one categorical and five continuous variables.

biomod.tun <-BIOMOD_tuning(myBiomodData,
+                            models = c("GBM", "RF","MAXENT.Phillips"))

-=-=-=-=-=-=-=-=-=-=
 Start tuning GBM. Start coarse tuning
Best optimization of coarse tuning:
1000 
-=-=-=-=-=-=-=-=-=-=
 8 
-=-=-=-=-=-=-=-=-=-=
 0.01 
-=-=-=-=-=-=-=-=-=-=
 10 
-=-=-=-=-=-=-=-=-=-=
Start fine tuning

 Finished tuning GBM
 
-=-=-=-=-=-=-=-=-=-=
Start tuning RF
note: only 5 unique complexity parameters in default grid. Truncating the grid to 5 .

Finished tuning RF
 
-=-=-=-=-=-=-=-=-=-=
Start tuning MAXENT.Phillips
Error in colSums(pres) : 'x' must be numeric
In addition: Warning messages:
1: In train.default(data@data.env.var, resp, method = "gbm", tuneGrid = tune.grid,  :
  The metric "Accuracy" was not in the result set. ROC will be used instead.
2: In train.default(data@data.env.var, resp, method = "gbm", tuneGrid = tune.grid,  :
  The metric "Accuracy" was not in the result set. ROC will be used instead.
Finished tuning MAXENT.Phillips
 
-=-=-=-=-=-=-=-=-=-=
Tuning MAXENT.Phillips failed!

**Comment by momeni133** [comment]
P.S. after converting the categorical variable into numeric, tuning works well for MaxEnt. It seems that in Biomod2, the MaxEnt is not able to handle categorical variables. Am I right?

**Comment by DamienGeorges** [comment]
Should be fixed in the latest version of biomod2 available on github
`devtools::install_github('biomodhub/biomod2')`
