### ISSUE TITLE
Question about [BIOMOD_EnsembleForecasting] - [looping multiple future scenarios]

### ISSUE THREAD

**Issue by brblais** [biomodhub/biomod2#251]
**Context and question**
Hello, I'm trying to loop 12 separate EnsembleForecasting scenarios (3x GCM, 2x future time periods, 2x SSP's). Each of the (12) scenarios is a Formal Class SpatRaster containing relevant environmental predictors. The code below 'runs' however the output (e.g., RangeSize, plots) seems to generate one single ensemble (of all 12 scenarios combined) rather than 12 separate outputs as desired. Also peculiar is that the 'FutureEM' folder called is largely devoid of output files (e.g., 'individual_projections" folder is empty), though an ".out" file is present.

I'm seeking help in adjusting my code that will run each of the SpatRaster scenarios separately, creating their own sub-directories and accessible outputs along the way. I'm eventually trying to get projections and multi-panel plots per GCM (e.g., HadGEM GCM for ssp126 and ssp585 pathways for 2050 and 2090 range projections, respectively). 

**Related code** 
```
#Note, code to generate 'current' BIOMOD_EnsembleForecasting all works fine up through this point
# Future Projection Scenarios
proj_scen <- c("current", #'current' was retained in the tutorial
               "2050_HAD_126", "2050_HAD_585","2050_MPI_126", "2050_MPI_585","2050_MRI_126", "2050_MRI_585", #for 2050 scenarios
               "2090_HAD_126", "2090_HAD_585","2090_MPI_126", "2090_MPI_585","2090_MRI_126", "2090_MRI_585" #for 2090 scenarios
)
  #each scen above is unique SpatRaster related to "period_GCM_ssp" 

#create a loop across commands for each scen
for(scen in proj_scen){
  cat("\n> projections of ", scen) 
  
FutureEM<-BIOMOD_EnsembleForecasting(
  bm.em=myBiomodEM,
  #bm.proj = myBiomodEMProj,
  proj.name = 'FutureEM',
  new.env = get(paste0("stk_", scen)),
  new.env.xy = NULL,
  models.chosen = "all",
  metric.binary = 'TSS',
  metric.filter = NULL,
  compress = TRUE,
  nb.cpu = 6,
)

future_plot<-plot(FutureEM) #save plot per scen

# Load current and future binary projections per scen
CurrentProjEM <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
FutureProjEM <- get_predictions(FutureEM, metric.binary = "TSS")

# Compute differences per scen
myBiomodRangeSizeEM <- BIOMOD_RangeSize(proj.current = CurrentProjEM, 
                                        proj.future = FutureProjEM)

rangeEM_comp<-myBiomodRangeSizeEM$Compt.By.Models
rangeEM_plot<-plot(myBiomodRangeSizeEM$Diff.By.Pixel)
}
```

Any assistance is appreciated, including directing me to similar forums/threads if applicable.
Thank you,
-Brian

**Comment by MayaGueguen** [comment]
Hello Brian,

Thank you for using one of the new issue templates !

Here is your code with some adjustments.
Main changes are : 
- specify a `proj.name` with the related scenario information in [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html)
- save plots
- save outputs of [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function

```
# Future Projection Scenarios
# each scen is unique SpatRaster related to "period_GCM_ssp" 
proj_scen <- c("current", #'current' was retained in the tutorial
               "2050_HAD_126", "2050_HAD_585","2050_MPI_126", 
               "2050_MPI_585","2050_MRI_126", "2050_MRI_585", #for 2050 scenarios
               "2090_HAD_126", "2090_HAD_585","2090_MPI_126", 
               "2090_MPI_585","2090_MRI_126", "2090_MRI_585" #for 2090 scenarios
)

# create a loop across commands for each scen
for (scen in proj_scen) {
    cat("\n> projections of ", scen) 
  
    FutureEM<-BIOMOD_EnsembleForecasting(
      bm.em=myBiomodEM,
      #bm.proj = myBiomodEMProj,
      proj.name = paste0('FutureEM_', scen),
      new.env = get(paste0("stk_", scen)),
      new.env.xy = NULL,
      models.chosen = "all",
      metric.binary = 'TSS',
      metric.filter = NULL,
      compress = TRUE,
      nb.cpu = 6,
    )

    pdf(paste0("Graphic_FutureEM_", scen, ".pdf"))
    plot(FutureEM)
    dev.off()

    # Load current and future binary projections per scen
    CurrentProjEM <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
    FutureProjEM <- get_predictions(FutureEM, metric.binary = "TSS")

    # Compute differences per scen
    myBiomodRangeSizeEM <- BIOMOD_RangeSize(proj.current = CurrentProjEM, 
                                            proj.future = FutureProjEM)

    rangeEM_comp <- myBiomodRangeSizeEM$Compt.By.Models
    rangeEM_map <- myBiomodRangeSizeEM$Diff.By.Pixel
    writeRaster(rangeEM_map, filename = paste0("rangeEM_map_", scen, ".tif"))
    write.table(rangeEM_comp, file = paste0("rangeEM_comp_", scen, ".tif"))

    pdf(paste0("Graphic_RangeEM_", scen, ".pdf"))
    plot(rangeEM_map)
    dev.off()
}
```

Hope it helps
Maya

**Comment by brblais** [comment]
Thanks so much, Maya! Your edits helped to generate separate runs per ‘scen’ like I envisioned. 

Can you direct me to any help pages/forums/examples etc. for calling and customizing plot figures from the output? My understanding is that ggplot functionality is built into biomod2…but its not necessary to write ggplot objects separately? For example, I’d like to change the helpful but lengthy file name headers generated by biomod2 to custom name(s) that are more publication friendly; adjust x-axis ticks for spacing; change legend item names; and select certain output graphics to generate multi-panel plots; etc. but unsure how to go about that if ‘usual’ ggplot language [e.g., `ggplot.object +theme()`] code is not how to go about it? 

Thank you!

**Comment by MayaGueguen** [comment]
Glad that it helped !

You have 2 types of plots within `biomod2` : 
- all the functions starting by `bm_Plot[...]` like [bm_PlotEvalBoxplot](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalBoxplot.html) or [bm_PlotResponseCurves](https://biomodhub.github.io/biomod2/reference/bm_PlotResponseCurves.html) for example
- and the predefined `plot` functions (for [projection outputs](https://biomodhub.github.io/biomod2/reference/BIOMOD.projection.out.html) for example).

`plot` functions always return the `ggplot` object created, while `bm_Plot[...]` functions return a `list` containing both `ggplot` object and the `data.frame` built and used to produce this graphic.

It means you can either start from the already built graphic and add some `ggplot` elements, or create your own graphic from the table (_only for `bm_Plot[...]` outputs_).

Here is an example with the [bm_PlotEvalBoxplot](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalBoxplot.html) function : 

```
library(biomod2)
library(ggplot2)
library(terra)

# Load species occurrences (6 species available)
data(DataSpecies)
head(DataSpecies)

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
data(bioclim_current)
myExpl <- terra::rast(bioclim_current)

# ---------------------------------------------------------------
# Format Data with true absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)

# Create default modeling options
myBiomodOptions <- BIOMOD_ModelingOptions()

# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id = 'AllModels',
                                    models = c('RF', 'GLM'),
                                    bm.options = myBiomodOptions,
                                    CV.strategy = 'random',
                                    CV.nb.rep = 2,
                                    CV.perc = 0.8,
                                    metric.eval = c('TSS','ROC'),
                                    var.import = 3,
                                    seed.val = 42)

# ---------------------------------------------------------------
# Represent evaluation scores
plot_out <- bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'run'))

names(plot_out) ## 2 elements are returned
head(plot_out$tab) ## the table used to produce the graphics

## You can directly use the ggplot produced :
plot_out$plot 
plot_out$plot + labs(title = "My graphic modified")

## Or create your own graphic : 
ggplot(plot_out$tab, aes_string(x = "algo", y = "calibration", fill = "run")) +
    geom_boxplot() + ## add boxplot
    facet_wrap("metric.eval") +
    xlab("") +
    theme(legend.title = element_blank()
          , legend.key = element_rect(fill = "white")
          , axis.text.x = element_text(angle = 45, hjust = 1))
```

Note that you have small examples at the end of each function documentation.
And you can also check the full example page : https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html

Maya

**Comment by brblais** [comment]
Hi @MayaGueguen 

Thank you for the info. Unfortunately it is still unclear how to modify/adjust 'map' plots. The following is from the _Gulo gulo_ tutorial with my questions following the two plot calls (plot outputs attached as pdf that show what I'm trying to describe...and adjust). Saving objects and adding calls to `+labs()` or `+names()` fail to work.

```
#
FutureEM<-BIOMOD_EnsembleForecasting(
  bm.em=myBiomodEM, #reduced EMalgos to 3 for simplicity (EMca, EMci,EMwmean)
  #bm.proj = myBiomodEMProj,
  proj.name = 'FutureEM',
  new.env = myExplFuture,
  new.env.xy = NULL,
  models.chosen = "all",
  metric.binary = 'TSS',
  metric.filter = NULL,
  compress = TRUE,
  nb.cpu = 6,
)

plot(FutureEM) #How rename each (facet?) titles in this plot?? convert prob scale to 0-1?

# Load current and future binary projections
CurrentProjEM <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
FutureProjEM <- get_predictions(FutureEM, metric.binary = "TSS")

# Compute differences
myBiomodRangeSizeEM <- BIOMOD_RangeSize(proj.current = CurrentProjEM, 
                                      proj.future = FutureProjEM)

myBiomodRangeSizeEM$Compt.By.Models

plot(myBiomodRangeSizeEM$Diff.By.Pixel) #how to change titles of this 1x2 map plot? Move legend inside figure and rename levels? 
```

Also, how to best call objects (e.g., .out files, image files) into the global environment that are saved into subdirectories? For example, I may wish to create a multi-panel plot of a specific GCM x time period x ssp pathway for which a subdirectory was made (as in the first post in this thread). Would `object<-get(load("../subdir_name/filename.out"))` be the way to go? My aims are to bring items from subdirectories into the environment in order to generate specific map plots. 

Thanks so much for your time,
-Brian
[Gulo_output.pdf](https://github.com/biomodhub/biomod2/files/11355542/Gulo_output.pdf)

**Comment by MayaGueguen** [comment]
Hello Brian,

I am sorry but as you did not provide the errors when it fails, I can not be of so much help...


For the modification you want to do and that you indicated onto your `pdf` files, these are `plot` and `ggplot2` questions :wink: 

#### For left graphic : 
Here is the `ggplot2` cheat sheet for general help : https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf
What you want to check more precisely in your case are the following : 
- to modify color scale : argument `labels` in [scale_fill_continuous](https://ggplot2.tidyverse.org/reference/scale_colour_continuous.html)
- to change facet names :  argument `labeller` in [facet_wrap](https://ggplot2.tidyverse.org/reference/facet_wrap.html)

#### For right graphic : 
Titles are directly extracted from the `stack` object (here `myBiomodRangeSizeEM$Diff.By.Pixel`) so you can change them by changing the `names` of this object.
As for the legend, you have to modify it with the [legend](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/legend) function. 


:exclamation: _but indeed as you have several things you would like to modify, might be also best for you to consider starting your own plot from scratch to be able to modify all the things you want._
_Note also that it is quite feasable to modify a pre-existing `ggplot2` graphic (the left graphic) but rather difficult to change a pre-existing basic `R` plot (the right graphic)._



#### As for the naming of your objects : 
Always keep in mind that you should : 
1. have a name that indicates you easily what your object contains
2. have a name that contains all the information of your object if you plan to have several versions of this object with slight differences 

For example, in your case : 
- either you put the information into the subdirectory names, and the plot / output files have always the same names within these subdirectories, but then you cannot move them in another place together
- or you put directly all the information within your plot / output files names

```
## Solution 1
Projections/GCM1_time1_ssp1/myOutputModel.out
                            myPlot.pdf
Projections/GCM1_time1_ssp2/myOutputModel.out
                            myPlot.pdf
Projections/GCM1_time2_ssp1/myOutputModel.out
                            myPlot.pdf
...

## Solution 
Projections/myOutputModel_GCM1_time1_ssp1.out
            myPlot_GCM1_time1_ssp1.pdf
            myOutputModel_GCM1_time1_ssp2.pdf
            myPlot_GCM1_time1_ssp2.pdf
            myOutputModel_GCM1_time2_ssp1.pdf
            myPlot_GCM1_time2_ssp1.pdf
...
```

Maya
