### ISSUE TITLE
Help with BIOMOD_FormatingData - Automatic transformation and standardisation of variables

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#253]
Hi,

i am modelling a Generalized Linear Model with quadratic terms and family = binomial(link = 'logit'). I often read i have to assure a normal distribution of my explanatory variables. If it is not the case i would like to transform the variables f.e with log(variable) or sqrt(variable). Also standardisation ((x-mean(x)/std(x)) to bring every variable on the same 'scale'  seems to be a good method in my opinion. Do i have to transform and stardardize my variables before i put everything in BIOMOD_FormatingData or is BIOMOD_FormatingData doing a automatic transformation/standardization of my variables? 

Best,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Thank you for reporting :pray: 
`biomod2` do not manage automatically variable transformation or standardisation. 
So if you want to have variable transformation or standardisation you have to do it before giving data to `BIOMOD_FormatingData` (and remember to do the same transformations/standardisation on the variable you feed to `BIOMOD_Projection`/`BIOMOD_EnsembleForecasting`)
Best,
Rémi
