### ISSUE TITLE
Error in BIOMOD_EnsembleForecasting

### ISSUE THREAD

**Issue by guimaricato** [biomodhub/biomod2#259]
Hi guys, I hope you are well.

I ran multiple models in the new version and it's really good, congratulations! However, when I had to run a specific one evaluating only by ROC, there was an error in the last part of the script (BIOMOD_EnsembleForecasting). I don't know if this error is linked to the evaluation metric, it was the only thing I did differently from the other scripts. I ran it considering both TSS and ROC and when I realized that TSS was doing poorly, I ran the rest of the script considering only ROC. I wonder if this might have caused this error. Please find part of my scripts and the error. Thank you in advance!

```
TursiopsModel <- BIOMOD_Modeling(bm.Tursiops,
                               modeling.id = "model_Tursiops",
                               models = c("GLM", "GAM", "RF", "GBM", "FDA"),
                               bm.options = bm.opt,
                               nb.rep = 10,
                               data.split.perc = 80,
                               do.full.models = F,
                               prevalence = 0.5,
                               var.import = 3,
                               metric.eval = c("TSS", "ROC")
```

```
TursiopsModel_EM <- BIOMOD_EnsembleModeling(TursiopsModel,
                                          models.chosen = "all",
                                          em.by = "all",
                                          metric.select = c("ROC"),
                                          em.algo = c("EMmean", "EMwmean", "EMca", "EMcv"),
                                          metric.select.thresh = c(0.8),
                                          metric.eval = c("ROC"),
                                          var.import = 3
```

```
Proj_TursiopsModel <- BIOMOD_Projection(bm.mod = TursiopsModel,
                                      proj.name = "Current",
                                      new.env = biostack,
                                      models.chosen = "all",
                                      metric.binary = "all",
                                      metric.filter = "all",
                                      build.clamping.mask = F,
                                      keep.in.memory = F)
```

```
Proj_TursiopsModel_EM <- BIOMOD_EnsembleForecasting(bm.em = TursiopsModel_EM,
                                                  bm.proj = Proj_TursiopsModel,
                                                  proj.name = "Current_EM",
                                                  models.chosen = "all",
                                                  metric.binary = "all",
                                                  metric.filter = "all",
                                                  output.format = ".img")
```

Error:

```
> Proj_TursiopsModel_EM <- BIOMOD_EnsembleForecasting(bm.em = TursiopsModel_EM,
+                                                   bm.proj = Proj_TursiopsModel,
+                                                   proj.name = "Current_EM",
+                                                   models.chosen = "all",
+                                                   metric.binary = "all",
+                                                   metric.filter = "all",
+                                                   output.format = ".img")
```

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Creating suitable Workdir...
Error in .fun_testIfIn(TRUE, "full.name", subset.list[["full.name"]],  : 
full.name must be 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1', 'lyr1', 'pred', 'lyr1', 'lyr1', 'X1',

**Comment by jdvidal** [comment]
I'm experiencing a similar problem as well. It appears to be occurring only with specific species in my dataset. I'll be keeping an eye out for a solution.

**Comment by rpatin** [comment]
Hello @guimaricato, @jdvidal,
Thank you for reporting and sorry for the inconvenience :pray: 
This issue is most likely linked to `biomod2` version `4.2-2` and should have been solved since then.
If you update to the current `biomod2`  version `4.2-3` with `devtools::install_github('biomodhub/biomod2')` and re-run your `BIOMOD_Projection` and your `BIOMOD_EnsembleForecasting` it should be solved. More info in issue https://github.com/biomodhub/biomod2/issues/233#issuecomment-1505430569.
Best,
Rémi

**Comment by guimaricato** [comment]
Hello, Rémi.

I have updated the package and no longer have this problem, thank you! I'll let you know if I notice anything else.

Best,
Guilherme
