### ISSUE TITLE
TSS and AUC of "Random Forest" algorithm have strange scores

### ISSUE THREAD

**Issue by LorenzoBernicchi** [biomodhub/biomod2#261]
Hello everyone,
I am posting this issue for asking about a modeling output that looks quite strange to me. I hope this is not an "off-topic" issue.

I modeled the distribution of my species without facing any errors or bugs, combining six different algorithms, namely: GLM, GBM, GAM, RF, MAXENT, and MAXNET. All five algorithms show similar values for both TSS (from 0.45 to 0.55) and AUC (from 0.75 to 0.85), except for the "Random Forest" algorithm. For every cross-validation run both the TSS and AUC values are 1.00, without any variation. 
I found it a little bit strange and I am wondering if this could be due to a modeling problem or something else.

Thank you very much in advance, I wish you a great day!

**Comment by rpatin** [comment]
Hello @LorenzoBernicchi,
Thank you for reporting :pray: 
The question is fully pertinent and it is indeed a strange situation.
Given the information you provided, I would think this is a situation of `RF` algorithm overfitting the data (see issue https://github.com/biomodhub/biomod2/issues/247#issuecomment-1521471384 ).

To confirm such diagnostic you would need to look at the projection and the response curves and see whether they are biologically plausible - more info [here](https://github.com/biomodhub/biomod2/issues/247#issuecomment-1521471384). If you can share more information on your issue (i.e. projection map for `RF` and the other algorithm, as well as response curves for the most important variables), we may help you further with your issue.

If you feel that the overfitting is unlikely and the high performance attributed to RF may be an error (which is possible - although highly unlikely) then we would need a reproducible example.

Have a great day as well,
Rémi

**Comment by nihalk84** [comment]
Thank you for your help. I will retry the scripts with updated versions.

**Comment by MarianMirea** [comment]
I also encountered this problem with RF. I thought it was a problem related to pseudo-absence points and tested several variants (From 50 to 50000). As you can see in the Object column is the number of pseudo absence points (the presence records sum to 120), And the calibration value of TSS is 0.99 or 1 in all the cases.

|run |algo|metric.eval|cutoff|sensitivity|specificity|calibration|validation|evaluation|Object               |
|----|----|-----------|------|-----------|-----------|-----------|----------|----------|---------------------|
|RUN1|RF  |TSS        |464   |100        |92.5       |0.95       |0.617     |NA        |Evaluation_pabs_50   |
|RUN1|RF  |TSS        |400   |100        |98.75      |0.988      |0.6       |NA        |Evaluation_pabs_100  |
|RUN1|RF  |TSS        |299.5 |100        |99.75      |0.998      |0.473     |NA        |Evaluation_pabs_500  |
|RUN1|RF  |TSS        |287   |100        |100        |1          |0.565     |NA        |Evaluation_pabs_1000 |
|RUN1|RF  |TSS        |280   |100        |99.875     |0.999      |0.519     |NA        |Evaluation_pabs_2000 |
|RUN1|RF  |TSS        |227.5 |100        |99.917     |0.999      |0.453     |NA        |Evaluation_pabs_3000 |
|RUN1|RF  |TSS        |212   |100        |99.969     |1          |0.495     |NA        |Evaluation_pabs_4000 |
|RUN1|RF  |TSS        |210   |100        |99.95      |1          |0.522     |NA        |Evaluation_pabs_5000 |
|RUN1|RF  |TSS        |234   |100        |99.958     |1          |0.517     |NA        |Evaluation_pabs_6000 |
|RUN1|RF  |TSS        |266.5 |100        |99.964     |1          |0.471     |NA        |Evaluation_pabs_7000 |
|RUN1|RF  |TSS        |245.5 |100        |100        |1          |0.442     |NA        |Evaluation_pabs_8000 |
|RUN1|RF  |TSS        |202   |100        |99.975     |1          |0.478     |NA        |Evaluation_pabs_10000|
|RUN1|RF  |TSS        |114.5 |100        |99.99      |1          |0.478     |NA        |Evaluation_pabs_50000|

**Comment by MarianMirea** [comment]
Hello everyone,

I'm back again after more tests. Here are 2 different species modeled in biomod2 and the results for TSS-RF, where we can see that in most cases sensitivity and specificity are close to or even 100%. In the last column "object" is the number of pseudo-absences for every run. 

Sorry in advance for the long tables!

This is the first species with 130 presences records. The locations from this species dose not occur in the same places or environment as the next. The environmental  data used is from Worldclim (bio_15, bio_18, bio_19, bio_3, bio_7, bio_9 ).
The only thing similar to @LorenzoBernicchi is the models used, where i used 'GLM', 'GAM', 'GBM', 'RF', 'MAXNET', exception being MAXENT.
**Species 1**
| algo | metric.eval | cutoff | sensitivity | specificity | calibration | validation | evaluation | Object    |
|------|-------------|--------|-------------|-------------|-------------|------------|------------|-----------|
| RF   | TSS         | 608    | 96.97       | 100         | 0.97        | 0.463      | NA         | pabs_60   |
| RF   | TSS         | 446    | 98.99       | 94.792      | 0.938       | 0.438      | NA         | pabs_120  |
| RF   | TSS         | 487    | 95.96       | 97.917      | 0.939       | 0.606      | NA         | pabs_180  |
| RF   | TSS         | 408    | 98.99       | 98.958      | 0.979       | 0.409      | NA         | pabs_240  |
| RF   | TSS         | 347    | 100         | 95.417      | 0.954       | 0.367      | NA         | pabs_300  |
| RF   | TSS         | 348    | 100         | 97.222      | 0.972       | 0.499      | NA         | pabs_360  |
| RF   | TSS         | 378    | 98.99       | 98.214      | 0.972       | 0.51       | NA         | pabs_420  |
| RF   | TSS         | 315    | 100         | 97.396      | 0.974       | 0.484      | NA         | pabs_480  |
| RF   | TSS         | 293    | 100         | 97.454      | 0.975       | 0.553      | NA         | pabs_540  |
| RF   | TSS         | 353    | 100         | 98.125      | 0.981       | 0.58       | NA         | pabs_600  |
| RF   | TSS         | 339.5  | 100         | 98.864      | 0.989       | 0.486      | NA         | pabs_660  |
| RF   | TSS         | 291    | 100         | 97.743      | 0.977       | 0.486      | NA         | pabs_720  |
| RF   | TSS         | 360    | 100         | 99.199      | 0.992       | 0.547      | NA         | pabs_780  |
| RF   | TSS         | 235    | 100         | 97.619      | 0.976       | 0.486      | NA         | pabs_840  |
| RF   | TSS         | 305    | 100         | 98.889      | 0.989       | 0.433      | NA         | pabs_900  |
| RF   | TSS         | 303.5  | 100         | 99.089      | 0.991       | 0.487      | NA         | pabs_960  |
| RF   | TSS         | 318    | 98.99       | 99.265      | 0.984       | 0.384      | NA         | pabs_1020 |
| RF   | TSS         | 309    | 100         | 98.727      | 0.987       | 0.47       | NA         | pabs_1080 |
| RF   | TSS         | 314.5  | 100         | 99.671      | 0.997       | 0.44       | NA         | pabs_1140 |
| RF   | TSS         | 297    | 100         | 99.167      | 0.992       | 0.428      | NA         | pabs_1200 |
| RF   | TSS         | 315.5  | 100         | 99.802      | 0.998       | 0.403      | NA         | pabs_1260 |
| RF   | TSS         | 311    | 100         | 99.716      | 0.997       | 0.441      | NA         | pabs_1320 |
| RF   | TSS         | 286    | 100         | 99.547      | 0.995       | 0.426      | NA         | pabs_1380 |
| RF   | TSS         | 264.5  | 100         | 99.566      | 0.996       | 0.545      | NA         | pabs_1440 |
| RF   | TSS         | 234    | 100         | 99.083      | 0.991       | 0.49       | NA         | pabs_1500 |
| RF   | TSS         | 291    | 100         | 99.439      | 0.994       | 0.441      | NA         | pabs_1560 |
| RF   | TSS         | 231    | 100         | 98.92       | 0.989       | 0.451      | NA         | pabs_1620 |
| RF   | TSS         | 273    | 100         | 99.256      | 0.993       | 0.427      | NA         | pabs_1680 |
| RF   | TSS         | 215    | 100         | 99.21       | 0.992       | 0.441      | NA         | pabs_1740 |
| RF   | TSS         | 300    | 100         | 99.722      | 0.997       | 0.448      | NA         | pabs_1800 |


For species 2 i included only the mean values for every algo, where you can see the RF sensitivity and specificity are close to or even 100%.
**Species 2**
| run  | algo   | metric.eval | cutoff | sensitivity | specificity | calibration | validation | evaluation |
|------|--------|-------------|--------|-------------|-------------|-------------|------------|------------|
| RUN1 | RF     | TSS         | 325.883| 99.630      | 98.600      | 0.982       | 0.469      | NA         |
| RUN1 | MAXNET | TSS         | 454.000| 81.736      | 72.420      | 0.544       | 0.467      | NA         |
| RUN1 | GLM    | TSS         | 557.967| 71.667      | 69.828      | 0.416       | 0.466      | NA         |
| RUN1 | GBM    | TSS         | 427.150| 98.472      | 86.634      | 0.852       | 0.501      | NA         |
| RUN1 | GAM    | TSS         | 505.850| 93.889      | 77.002      | 0.710       | 0.595      | NA         |

**Code block used**
```r
  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = env_current,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.strategy = "random",
                                       PA.nb.rep = 1,
                                       PA.nb.absences = p_abs)
  
  myBiomodOption <- BIOMOD_ModelingOptions()
  
  myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                      models = c('GLM', 'GAM', 'GBM', 'RF', 'MAXNET'),
                                      bm.options = myBiomodOption,
                                      nb.rep = 1,
                                      data.split.perc = 80,
                                      prevalence = 0.5,
                                      metric.eval = c('TSS', 'ROC', 'KAPPA'),
                                      var.import = 10,
                                      do.full.models = FALSE,
                                      nb.cpu = 1,
                                      seed.val = 13,
                                      modeling.id = paste(myRespName, "FirstModeling_pabs", p_abs, sep = "_"))
  myBiomodModelEval <- get_evaluations(myBiomodModelOut)

``` 
Where **"p_abs"** is a list with the different values tested (column object from table).

**Session info**
```r
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] gbm_2.1.8.1   biomod2_4.2-2 raster_3.6-20 sp_1.6-0     

loaded via a namespace (and not attached):
 [1] shape_1.4.6            tidyselect_1.2.0       terra_1.7-18           reshape2_1.4.4         splines_4.2.2         
 [6] lattice_0.20-45        colorspace_2.1-0       vctrs_0.6.1            generics_0.1.3         mgcv_1.8-41           
[11] utf8_1.2.3             survival_3.4-0         rlang_1.1.0            pillar_1.9.0           withr_2.5.0           
[16] glue_1.6.2             plotmo_3.6.2           foreach_1.5.2          lifecycle_1.0.3        plyr_1.8.8            
[21] mda_0.5-3              stringr_1.5.0          munsell_0.5.0          gtable_0.3.3           codetools_0.2-18      
[26] maxnet_0.1.4           class_7.3-20           fansi_1.0.4            Rcpp_1.0.10            scales_1.2.1          
[31] plotrix_3.8-2          abind_1.4-5            TeachingDemos_2.12     ggplot2_3.4.2          stringi_1.7.12        
[36] dplyr_1.1.1            grid_4.2.2             rgdal_1.6-6            cli_3.5.0              tools_4.2.2           
[41] magrittr_2.0.3         glmnet_4.1-7           PresenceAbsence_1.1.11 tibble_3.2.1           randomForest_4.7-1.1  
[46] Formula_1.2-5          pkgconfig_2.0.3        MASS_7.3-58.1          Matrix_1.5-1           data.table_1.14.8     
[51] pROC_1.18.0            reshape_0.8.9          rstudioapi_0.14        iterators_1.0.14       earth_5.3.2           
[56] R6_2.5.1               rpart_4.1.19           nlme_3.1-160           nnet_7.3-18            compiler_4.2.2        
```

**Comment by rpatin** [comment]
Hi @MarianMirea,
Thank you for all the information :pray: 
However I am not sure to identify what is your issue.
You get TSS value for the calibration that are very high (linked to the very high sensitivity/specificity that you highlight. It could indicate an overfit. However your validation metric are quite sensible and comparable to other algorithm (at least for species 2), therefore I would not worry too much about the very high performance of your RF on the calibration. At least not on the sole basis of the evaluation metric. Did you explore also the response curves produced as well as the prediction maps ? This could give you additional indices for overfitting in the RF algorithm which could require a different tuning of the model.

Feel free to detail your question if my answer did not cover it.
Best regards,
Rémi

**Comment by LorenzoBernicchi** [comment]
Dear @rpatin, sorry for my late reply but I had some issues recently.

Following what you answered to @MarianMirea, I checked the scores of the `RF` algorithms, and like to her also my `validation` scores were similar to those of other algorithms, while 'calibration' scores were much higher and almost everytime near 1. 

As you suggested, I checked for 'response curves' and honestly some of them do not appear biologically plausible to me (see the image for a reference: it is impossible for roe deer to be unaffected by the cover of urban settlements or intensive agricultural activities). Moreover, also the ensemble projection do not seem really correct to me, and thus I really think I am facing an overfitting problem. 

May I ask you how I could solve  this problem? 
Thank you in advance.

Lorenzo Bernicchi

![Immagine 2023-06-07 154101](https://github.com/biomodhub/biomod2/assets/121942966/e01c3a47-73ab-4ce9-a7b9-34472c49d407)
![Immagine 2023-06-07 154143](https://github.com/biomodhub/biomod2/assets/121942966/884fbc0b-7e9e-4b55-a9fa-0bbce87361bd)

**Comment by rpatin** [comment]
Hello @LorenzoBernicchi,

1. Concerning the negative TSS, it is totally possible:
`TSS = TruePositiveRate + TrueNegativeRate - 1`
making TSS ranging between -1 and 1. TSS < 0 is just a sign that the model is rather bad.
In your situation this happens for the validation of models suspected for overfit (RF, but also GAM, that have very good performance on calibration data but bad performance on validation data).

2. Concerning the RF overfit:
I am afraid we are no expert of random forest. I can point out that the next version of `biomod2` will have the tuning function back and fully functional to help you find appropriate parameters. It is expected to be release in late summer.
Meanwhile, you can try to adjust RF parameters:
```
myBiomodOptions <- BIOMOD_ModelingOptions(RF = list(nodesize = 10))
```
Increasing nodesize (from 5 to 10) should lead to smaller tree, less prone to overfit. Alternatively you can also try setting a value to `maxnodes` that should also lead to smaller tree or forest which might as well limit overfit.

Hope this helps,
Best regards,
Rémi
