### ISSUE TITLE
Projection error for maxent in biomod2

### ISSUE THREAD

**Issue by raianu191** [biomodhub/biomod2#27]
Hello,

I am also facing the same issue. I have also installed the newest biomod2 package (devtools::install_github('biomodhub/biomod2') but still get this error.

Hello,

I am also having an issue projecting MAXENT models.

```
Schi_Proj <- BIOMOD_Projection(modeling.output=Schi_models,
                               new.env=current,
                               proj.name='Schi_current',
                               selected.models='all',
                               binary.meth='TSS',
                               compress='gzip',
                               clamping.mask=F,
                               keep.in.memory=T,
                               output.format='.img')
```

Here the output message:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Models Projections -=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Building clamping mask

*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
*** in setMethod('BinaryTransformation', signature(data='RasterLayer')
	> Projecting Schi_PA1_RUN1_GLM ...
	> Projecting Schi_PA1_RUN1_GAM ...
	> Projecting Schi_PA1_RUN1_GBM ...
	> Projecting Schi_PA1_RUN1_CTA ...
	> Projecting Schi_PA1_RUN1_MARS ...
	> Projecting Schi_PA1_RUN1_RF ...
	> Projecting Schi_PA1_RUN1_ANN ...
	> Projecting Schi_PA1_RUN1_MAXENT.Phillips ...Error in .local(.Object, ...) : 

In addition: Warning message:
In system(command = maxent.command, wait = TRUE, intern = TRUE) :
  running command 'java -mx4096m -cp "/data/home/users/g.silvaarias/local/bin/maxent.jar" density.Project "Schi/models/Schi/Schi_PA1_RUN1_MAXENT.Phillips_outputs/Schi_PA1_RUN1.lambdas" "Schi/./m_25170024/part1" "Schi/./m_25170024/part1/projMaxent.asc"  doclamp=false visible=false autorun nowarnings notooltips' had status 1
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)
Calls: BIOMOD_Projection ... lapply -> FUN -> FUN -> .local -> .rasterObjectFromFile
Execution halted
```

I would appreciate any advice.

All the best,
Gustavo

_Originally posted by @gsilvaarias in https://github.com/biomodhub/biomod2/issues/21#issuecomment-703074753_

**Comment by karolceron** [comment]
the same to me

**Comment by acoconis** [comment]
I also have the same issue.

**Comment by karolceron** [comment]
I Fixed it removing the space from the name of my directory. 

E.g., niche modeling -> niche_modeling

**Comment by acoconis** [comment]
> I Fixed it removing the space from the name of my directory.
> 
> E.g., niche modeling -> niche_modeling

Interesting. Thanks. I don't have any spaces, but perhaps it's a problem with the directory naming (numbers?). I'll trying renaming.

**Comment by raianu191** [comment]
I have also solved the problem. I tried a number of stuffs, I don't know if the problem was solved by one step or a combination but the following works for me. 

Step 1: The location of your raster files should be plain with no signs. For instance use location (D:\apple) instead of (D:\apple_xxxx), this sign (_) is the problem in the later one.

Step 2: Try the below originally done by Damien Gorges (https://r-forge.r-project.org/forum/forum.php?thread_id=31622&forum_id=995&group_id=302)

intersect_mask <- function(x){
  values_x <- getValues(x)
  inter_x <- values_x %*% rep(1,nlayers(x))
  mask <- setValues(subset(x,1),values = (inter_x>0))
  return(mask)
}

myExpl<-stack(b1,b2,....) #all your stack data

myExpl <- stack(mask(myExpl, intersect_mask(myExpl)))

Step 3: In the  BIOMOD_Modeling command use;
sep = "" instead of sep="" at the end of the command. Originally also posted by Damien Gorges.

Hope this helps. It worked for me.

**Comment by chenqh0618** [comment]
Hi, I seems meet the same problem, and solved it.

my problem was caused by the different resolution and extend bewteen different environment layers (any minous differences could lead to fail projection of  MaxEnt).

we could `res(raster)` and `extent(raster)` to unify resolution and extent when difference is minous, and `x <- resample(x,y)` to unify x and y when difference is obvious. 

wish my methods also help for you guys!
