### ISSUE TITLE
Variable importance function showing NA for some variables 

### ISSUE THREAD

**Issue by CatherineBuckland** [biomodhub/biomod2#272]
Hi Biomod2 team, 
I've been using biomdo2 for a while to run SDMs, but I've just added a different rater dataset to my predictor stack. Normally I just use the bioclim variable,s but I've just addeda  raster of a particular soil type. The raster is just 0s and 1s to show where this particular soil type is found. All predcitor layers clipped to same extent, projected in same coordinate system and resolution - no issues with running the models. But when i go to call the variable importance metrics for each predictor, this new dataset just says NA. Any ideas what might be going on ? 
Many thanks in advance, 
Catherine
![VariableImp_screenshot](https://github.com/biomodhub/biomod2/assets/47150713/ef331fc9-c031-44c6-9812-a133a5b1a8f3)

**Comment by rpatin** [comment]
Hi Catherine,
Thank you for reporting :pray: 
Did you solve your issue ? If that is the case, feel free to share your solution.
Best regards,
Rémi

**Comment by CatherineBuckland** [comment]
Hi Remi,

Yes I put a quotation mark in the wrong place!! Oops!! User error

Cheers

Catherine
