### ISSUE TITLE
Error in BIOMOD_EnsembleForecasting - [Error in if (nrow(out) == 0) { : argument is of length zero]

### ISSUE THREAD

**Issue by evertonmaciel** [biomodhub/biomod2#273]
Hello biomod colleagues.
I am using the biomod code below to model species. This code work pretty well for some species, but eventually, the ensemble models are not output for some of them. Could someone help me. I will be grateful for it.

myBiomodData_model_sp <- BIOMOD_FormatingData(resp.var = DataSpecies$model_sp,
                                                             expl.var = myExpl,
                                                             resp.xy = DataSpecies[,c('X_WGS84','Y_WGS84')],
                                                             resp.name = "model_sp",
                                                             PA.nb.rep =  1,
                                                             PA.nb.absences = 10000, #dez mil para muitas ocorrencias e mil para poucas
                                                             PA.strategy = 'disk',
                                                             filter.raster = TRUE,
                                                             na.rm=T)

myBiomodOption_model_sp <- BIOMOD_ModelingOptions()
myBiomodModelOut_model_sp <- BIOMOD_Modeling(bm.format=myBiomodData_model_sp,
                                                            models = c('MAXNET'),
                                                            bm.options = myBiomodOption_model_sp, 
                                                            nb.rep = 10,
                                                            data.split.perc = 75,
                                                            prevalence = 0.5,
                                                            metric.eval = c('TSS','ROC'),
                                                            save.output = T,
                                                            do.full.models = F,
                                                            modeling.id = "model_sp"
)

myBiomodModelEval_model_sp <- get_evaluations(myBiomodModelOut_model_sp)
write.csv(myBiomodModelEval_model_sp,"model_sp.csv")

myBiomodEM_model_sp <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut_model_sp,
                                                              models.chosen = 'all',
                                                              em.by = 'PA_dataset',
                                                              #em.algo = c('EMmean', 'EMca'),
                                                              metric.select = c('TSS'),
                                                              metric.select.thresh = c(0.7),
                                                              metric.eval = c('ROC','TSS'),
                                                              prob.mean = T,
                                                              prob.cv = T,
                                                              prob.ci = T,
                                                              prob.ci.alpha = 0.05,
                                                              prob.median = T,
                                                              committee.averaging = T,
                                                              prob.mean.weight = F,
                                                              prob.mean.weight.decay = 'proportional',
                                                              var.import = 0)

myBiomodProj_model_sp <- BIOMOD_Projection(bm.mod = myBiomodModelOut_model_sp,
                                                          proj.name = 'Current',
                                                          new.env = myExpl,
                                                          models.chosen = 'all',
                                                          metric.binary = 'TSS',
                                                          compress = 'xz',
                                                          clamping.mask = T,
                                                          output.format = '.img', #.grd ou .img
                                                          do.stack=F)

myBiomodEF_model_sp <- BIOMOD_EnsembleForecasting(
  proj.name="ensemble_model_sp",
  bm.em = myBiomodEM_model_sp ,
  output.format='.img',
  metric.binary='TSS',
  new.env=myExpl
)

=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Error in if (nrow(out) == 0) { : argument is of length zero
In addition: Warning message:
In .local(obj, ...) : No link provided for this object

**Comment by MayaGueguen** [comment]
Hello Everton,

Thank you for reporting :pray: 

Could you share a bit more additional information ?

- what is the output of `sessionInfo()` ?
- what is the output of `show(myBiomodModelOut_model_sp)` ?
- what is the output of `show(myBiomodEM_model_sp)` ?
- did you share all the complete message error when runinng `BIOMOD_EnsembleForecasting` function ? for example do you know for which ensemble model it did not work ? did you have an error when running the `BIOMOD_Projection` function ?

Thanks in advance,
Maya

**Comment by evertonmaciel** [comment]
Hello @MayaGueguen,
thank you for your help!

The output of the previous functions works very well. The error only appears in the output of the BIOMOD_EnsembleForecastin function. I figured out that if the cut-off threshold is reduced, this error does not appear. For example, I ran models for a species with a value of 0.7 <metric.select.thresh = c(0.7)> which returned this error. Then I ran the same model with a value of 0.5 for the same species and the error did not appear. Would this error be the result of very poor models below the cut-off threshold?  Would it be advisable in cases like this to work with a lower threshold value?
with the best,
Everton

**Comment by MayaGueguen** [comment]
Yes, it could be indeed the reason.
But the function is supposed to tell you which models it is keeping due to threshold, and you should not have an error with such an uninformative message even if no model fullfill the threshold condition.
For me to explore more this, I would need a reproducible example, so feel free to send me your code and data to maya.gueguen [at] univ-grenoble-alpes.fr if you want.

Maya
