### ISSUE TITLE
Help with bm_PlotResponseCurves - Response Curve Outputs

### ISSUE THREAD

**Issue by jcarde88** [biomodhub/biomod2#275]
Hello everyone! I have a question regarding the variable response curves. Is there a way to obtain the variable values where the response curves peak (i.e., the values that are found to be the most suitable)? For example, in my study depth is the most important explanatory variable for explaining distribution, and I want to be able to give a precise depth value that is considered the most suitable habitat area rather than approximating a value from reading the response curve figures. Is there a way to do this? I’m relatively new to this package, so it’s possible I missed something.

Here's an example of my response curves for depth. I would like to report the values where they peak.
![image](https://github.com/biomodhub/biomod2/assets/136716404/a5f76698-8125-4a48-9c36-def49e39384f)

Thank you!

**Comment by rpatin** [comment]
Hello @jcarde88,
When you get the output of `bm_PlotResponseCurves` you obtain both the graphics and the table used to generate the graphics.
e.g.:
```
resp.out <- bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                           models.chosen = 'all',
                           fixed.var = 'mean', 
                           do.plot = FALSE)
```
Then you get `resp.out$tab` the table used to generate the graphics and resp.out$plot the plot in itself. You can now work with `resp.out$tab` to get the information you need:
```
library(dplyr)

g.max <- 
  resp.out$tab %>% 
  group_by(expl.name, pred.name) %>% 
  summarise(expl.val = expl.val[which.max(pred.val)],
            .groups = "drop")
```
This way you can get for each model the predictor value for which prediction are maxed. 

There are however several limits:
- If you want the peak(s) instead of the maximum you will need to use more complex code and functions
- If you have several important variables, the maximum may change with the values of other variables (a priori not a problem in your situation)
- If you need a more precise resolution than the one we used to compute the curves, you will need to use `BIOMOD_Projection` manually (on a `data.frame`) to have the resolution you need (though you can provide `new.env` to `bm_PlotResponseCurves`, the function use the range of each variables).

Cheers,
Rémi

**Comment by jcarde88** [comment]
Hi Rémi,

Thanks so much, I really appreciate your response. This was helpful!

Another quick question I have is how do you obtain the values that show the percentage contribution for each explanatory variable? In other words, I want to be able to report that "depth", for example, accounts for X% of the predicted occurance for the model.

One last question is where can I obtain the ensemble AUC value? I have many different output files but I can't seem to find what I'm looking for. I'm only seeing the single model AUC values.

I apologize for the basic questons, I'm still learning how this package works, but I really aprpeciate your help!

Thanks,
Jessica

**Comment by rpatin** [comment]
Hi Jessica,
1. **Variable Importance**
When you argument  `var.imp` in `BIOMOD_Modeling` you can get an estimation of variable importance using `get_variables_importance` or `bm_PlotVarImpBoxplot` on the output of `BIOMOD_Modeling`. Note however, that variable importance calculated there is not a percentage of explained deviance (see the [website](https://biomodhub.github.io/biomod2/reference/bm_VariablesImportance.html)). For instance it does not sum to 100%. However it allows to estimate the relative contribution of each covariates to the predictions and the method is easy to generalize across very different models. 
2. **Ensemble model AUC**
If you use `get_evaluations` on the output of `BIOMOD_EnsembleModeling` you should be able to see the AUC for the ensemble model.

Best,
Rémi

**Comment by LindeNozomiLeo** [comment]
Hi,

question about the AUC, I would be interested in obtaining the AUC values, but I do not see this in get_evaluations as mentioned.

Best,
Linde

**Comment by rpatin** [comment]
> Hi,
> 
> question about the AUC, I would be interested in obtaining the AUC values, but I do not see this in get_evaluations as mentioned.
> 
> Best, Linde

Hi Linde,
I opened a new issue to keep this one focused more on Response Curves.
Best,
Rémi

**Comment by jcarde88** [comment]
> Rémi

Hi Rémi,

Thank you for that clarification. 

Further regarding the ensemble AUC, I'm still a bit confused which values in the output to consider. I'm attaching the output from "get_evaluations" for reference. I know that the ROC values are the AUC values, but I'm confused about the difference between the calibration and validation columns. 

Furthermore, I'm not sure how to calculate the ensemble AUC from this spreadsheet since it shows the results from all 10 versions of the pseudo-absence trials and the 10 runs for each pseudo-absence. Do I average the ROC calibration values for each algorithm across ALL of these runs? Please advise.

[3. ModelEval_single.xlsx](https://github.com/biomodhub/biomod2/files/11826079/3.ModelEval_single.xlsx)

Thank you!
Jessica

**Comment by rpatin** [comment]
Hi Jessica,
Concerning the difference between `calibration`/`validation`/`evaluation` columns, you can see Maya's answer https://github.com/biomodhub/biomod2/issues/258#issuecomment-1531039877.

If you average ROC values across all runs, it will have **no statistical meaning** for the ensemble model. If you want to get AUC for your Ensemble Model, you need to use `get_evaluations` on the output of `BIOMOD_EnsembleModeling`. However, note that `validation` AUC may not be available (see https://github.com/biomodhub/biomod2/issues/281#issuecomment-1600705836).

Best,
Rémi
