### ISSUE TITLE
Help with bm_PlotEvalBoxplot and bm_PlotVarImpBoxplot [group_by]

### ISSUE THREAD

**Issue by guimaricato** [biomodhub/biomod2#278]
Hello, everyone. I would like to know if I can further customize "group_by". For example,

**1) bm_PlotEvalBoxplot**

`bm_PlotEvalBoxplot(bm.out = TursiopsModel, dataset = "validation", group.by = c('something', 'something'))`

Since I calculated ROC and TSS, would it be possible for me to show only one of them in the output? When I run the above code, two boxplots appear side by side (one for ROC and another for TSS).

**2) bm_PlotVarImpBoxplot**

`bm_PlotVarImpBoxplot(bm.out = TursiopsModel_EM, group.by = c('something', 'expl.var', 'something'))`

The same happens here. Since I calculated "em.algo = c("EMmean", "EMwmean", "EMca", "EMcv")" in "BIOMOD_EnsembleModeling", they all appear in a 2x2 figure. I would like to choose only one in the output (e.g. only wmean).

Thank you in advance.

Best,
Guilherme

**Comment by rpatin** [comment]
Hello Guilherme,
Thank you for reporting :pray: 
The functions `bm_PlotXXX` provides useful graphics but does not allow full customization. However they generally return the data used to produce the graphics that you can use to build the graphics you are looking for - although you then need to manipulate `ggplot2` manually.

1. **bm_PlotEvalBoxplot**
``` 
library(dplyr)
library(ggplot2)
eval.out <- bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, 
                               group.by = c('algo', 'run'),
                               do.plot = FALSE)
eval.out$tab %>% 
  filter(metric.eval == "TSS") %>% 
  ggplot() +
  geom_boxplot(aes(x= algo, y = calibration, fill = run))
```
_Note that you could also have built your graphics directly on the output of `get_evaluations(...)`_

2. **bm_PlotVarImpBoxplot**

Here is an example:
```
library(dplyr)
library(ggplot2)
varimp.out <- bm_PlotVarImpBoxplot(bm.out = myBiomodEM, 
                                   group.by = c('algo', 'expl.var', 'merged.by.PA'), 
                                   do.plot = FALSE)
varimp.out$tab %>% 
  filter(algo == "EMwmean") %>% 
  ggplot()+
  geom_boxplot(aes(x = expl.var, y = var.imp))
```
_Note that you could also have built your graphics directly on the output of `get_variables_importance(...)`_

I hope this is clearer now.
Best,
Rémi

**Comment by guimaricato** [comment]
Hey @rpatin, this worked perfectly. Thank you so much!
