### ISSUE TITLE
Help with BinaryTransformation - cannot find the raster

### ISSUE THREAD

**Issue by rpatin** [biomodhub/biomod2#283]
### Discussed in https://github.com/biomodhub/biomod2/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **LindeNozomiLeo** June 21, 2023</sup>
Hi,

How do I extract the raster or dataframe on which I can use the function bm_BinaryTransformation. I would like to get a binary map for my projections, however, these are stored as BIOMOD.projection.out.

I'm still very much getting used to how the data is stored on the harddrive, so any information on how to work with these i.e. load them into R (or view them) is very much welcome! (output.format=".img" seems to only save corrupt disk images)</div>

**Comment by rpatin** [comment]
Hi @LindeNozomiLeo,

To interact with disk files it is generally easier to go through the `biomod2` objects. You can load the objects with `myBiomodProj <-  get(load('Protea.laurifolia.current.projection.out'))` for instance. Then many functions are available to interact with such kind of objects (see the [website](https://biomodhub.github.io/biomod2/reference/getters.out.html) for some examples)

Concerning the binary transformation, everything can be handled through `BIOMOD_Projection`, if you give argument such as `metric.binary = c('TSS')` the binary transformation with TSS will be performed with the projection. Then you can always load the projected raster with:
```
myBinaryProj <- get_predictions(myBiomodProj, metric.binary = 'TSS')
```
If you would have wanted to build the binary projection yourself, you could get the continuous prediction as follow:
```
myProj <- get_predictions(myBiomodProj)
```
And the threshold can be retrieved within `get_evaluations(myBiomodModelOut)`

The default output format is now `GeoTIFF` although you can always use `.img` files if you prefer so. Which software is telling you the images are corrupted ?

Best regards,
Rémi

**Comment by LindeNozomiLeo** [comment]
Hi,

thank you! i have been using metric.binary, however none of the plotted maps do not seem to be binary?
it was my macbook, telling me they are corrupted, but I'll keep the default output format then!

Thanks again!

**Comment by rpatin** [comment]
Hi Linde,
Happy to help !
If you do:
```
plot(myBiomodProj, metric.binary = "TSS")
```
none of the maps are binary ?

Concerning the corrupted files, it might just be Mac not recognizing the `.img` format, but they may be totally valid once opened with Rstudio/Qgis/...

**Comment by LindeNozomiLeo** [comment]
Hi,

I wasn't aware that the metric.binary had to be added to the plot value.
Thank you for all the help!

best,
Linde

**Comment by LindeNozomiLeo** [comment]
hi,

this following line does not seem to work (adapted to the file specific for my species
`myBiomodProj <-  get(load('Protea.laurifolia.current.projection.out')) `

it give the following error

`rror in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'Mikania.lundiana/Mikania.lundiana.Current.projection.out', probable reason 'No such file or directory'`

**Comment by Cam-in** [comment]
Hi biomod community! 
In the binary transformation, there are different methods for setting the best threshold to transform continuous habitat suitability into binary data. There is the cut-off value in biomod2 available to get it from the evaluation table and Find.Optim.Stat function
But, I want to understand how the cut-off is calculated. Is the value that maximized Sensitivity+Specificity? Is there a formula that biomod2 displays on the background? Or which is exactly the process that it is applied? 

E.g.  I received from an ensemble model: 

- Sensitivity: 94.453
- Specificity: 98.154
- TSS: 0.927
- Cutoff value: 586

But (94.453 + 98.154) -1 = 191,607 it is not the cutoff value. 

Can somebody help me and teach me? Thanks =)
Cami
