### ISSUE TITLE
Help with get_predictions - Can I get actual and predicted values for my testing set points?

### ISSUE THREAD

**Issue by lewistrotter** [biomodhub/biomod2#286]
Hello,

Thank you for the very great package. 

I am trying to make some ROC curve plots from my testing/validation set so I can compare with DeLong test. What I need is both the actual and predicted values for each point in my ~2k validation set. I can then put it through pROC.

Is there a way to extract this raw data? I saw that the get_predictions function can return predictions but it's not clear if these combine the training and/or testing results, and to which point each prediction corresponds to.

Thank you!

**Comment by rpatin** [comment]
Hello @lewistrotter,
Thank you for reporting :pray:
Given that your `biomod2` version is up-to-date (> 4.2-3), you can use a combination of `get_predictions`,  `get_calib_lines` and `get_formal_data` to extract the information of interest.
1. If you supplied independant evaluation dataset (using `eval.resp` in `BIOMOD_FormatingData`, you can use directly `get_predictions`:
```
df.pred <- get_predictions(myBiomodModelOut, evaluation = TRUE) # get predictions for evaluations
myResp <- get_formal_data(myBiomodModelOut, subinfo = "eval.resp.var") # get evaluation response data
df.resp <- data.frame(resp = myResp, points = seq_along(myResp))
library(dplyr)
df.full <- 
  left_join(df.pred, df.resp, by = c("points")) 

```
2. Alternatively if you use cross-validation, you need to get the model prediction with `get_predictions` and filter them depending on their data status (calibration or validation):
```
df.pred <- get_predictions(myBiomodModelOut) # model predictions on calibration & validation dataset
df.calib <- get_calib_lines(myBiomodModelOut, as.data.frame = TRUE) # info on calibration and validation
myResp <- get_formal_data(myBiomodModelOut, subinfo = "resp.var") # get response data
df.resp <- data.frame(resp = myResp, points = seq_along(myResp))

library(dplyr)
df.full <- 
  left_join(df.pred, df.calib, by = c("PA","run","points")) %>% 
  left_join(., df.resp, by = "points")
head(df.full)
```
You will get this kind of `data.frame`:
```
              full.name      PA  run  algo  points pred calib.lines  resp
GuloGulo_allData_RUN1_RF allData RUN1   RF      1  492        TRUE    1
GuloGulo_allData_RUN1_RF allData RUN1   RF      1  492       FALSE    1
GuloGulo_allData_RUN1_RF allData RUN1   RF      2  850        TRUE    0
GuloGulo_allData_RUN1_RF allData RUN1   RF      2  850       FALSE    0
GuloGulo_allData_RUN1_RF allData RUN1   RF      3  922        TRUE    0
GuloGulo_allData_RUN1_RF allData RUN1   RF      3  922        TRUE    0

```
That you can filter as you wish using column `calib.lines`:
```
filter(df.full, !calib.lines) # to extract predictions for validation dataset
```

Best regards,
Rémi

**Comment by lewistrotter** [comment]
Thanks Rémi,

That worked. I was able to filter points to a validation-only successfully. However, my response values all appear to be 1s or NAs, no 0s... I would expect PAs to be 0, unless I'm misunderstanding something fundamental.

Could it be because I'm not using true absences or an evaluation set? The total number of points adds up as expected (5k of each presence, pseudoabsences).

Thanks!

Here's some basic code in case it helps:

`# load shapefile of presence-only (1s) points
shp <- shapefile(...)

# convert to dframe, seperate into xy and pres values
df <- as.data.frame(in_shp)
xy_vals <- df[, c("x", "y")]
pres_vals <- as.numeric(df[, "Presences"])

# load stack of expl var rasters
stk <- rast(...)

# format to bm2 data
bm_data <- BIOMOD_FormatingData(resp.name="Presences",
                                resp.var=vals,
                                expl.var=pres_vals ,
                                resp.xy=xy_vals,
                                PA.nb.rep=1,
                                PA.nb.absences=5000,
                                PA.strategy='disk',
                                PA.dist.min=240,
                                na.rm=TRUE,
                                filter.raster=TRUE)

# perform modelling using single models
bm_single_models <- BIOMOD_Modeling(bm.format=bm_data,
                                    modeling.id="delong test",
                                    models="MAXENT",
                                    CV.strategy='random',
                                    CV.nb.rep=1,
                                    CV.perc=0.8,
                                    var.import=1,          
                                    metric.eval=c("ROC"),
                                    do.progress=TRUE)


# extract preds, calibs, response, combine and filter
preds <- get_predictions(bm_single_models)
calib <- get_calib_lines(bm_single_models, as.data.frame=TRUE)
resps <- get_formal_data(bm_single_models, subinfo="resp.var")
resps <- data.frame(resp=resps, points=seq_along(resps))
all <- left_join(preds, calib, by=c("PA","run","points")) %>% left_join(., resps, by="points")

# extract predictions for validation dataset
test_preds <- filter(all, !calib.lines)

# responses all 1s or NAs...?
preds$resp`

**Comment by lewistrotter** [comment]
Thanks Rémi,

That worked. I was able to filter points to a validation-only successfully. However, my response values all appear to be 1s or NAs, no 0s... I would expect PAs to be 0, unless I'm misunderstanding something fundamental.

Could it be because I'm not using true absences or an evaluation set? The total number of points adds up as expected (5k of each presence, pseudoabsences).

Thanks!

Here's some basic code in case it helps:

```
# load shapefile of presence-only (1s) points
shp <- shapefile(...)

#convert to dframe, seperate into xy and pres values
df <- as.data.frame(in_shp)
xy_vals <- df[, c("x", "y")]
pres_vals <- as.numeric(df[, "Presences"])

#load stack of expl var rasters
stk <- rast(...)

#format to bm2 data
bm_data <- BIOMOD_FormatingData(resp.name="Presences",
resp.var=vals,
expl.var=pres_vals ,
resp.xy=xy_vals,
PA.nb.rep=1,
PA.nb.absences=5000,
PA.strategy='disk',
PA.dist.min=240,
na.rm=TRUE,
filter.raster=TRUE)

#perform modelling using single models
bm_single_models <- BIOMOD_Modeling(bm.format=bm_data,
modeling.id="delong test",
models="MAXENT",
CV.strategy='random',
CV.nb.rep=1,
CV.perc=0.8,
var.import=1,
metric.eval=c("ROC"),
do.progress=TRUE)

#extract preds, calibs, response, combine and filter
preds <- get_predictions(bm_single_models)
calib <- get_calib_lines(bm_single_models, as.data.frame=TRUE)
resps <- get_formal_data(bm_single_models, subinfo="resp.var")
resps <- data.frame(resp=resps, points=seq_along(resps))
all <- left_join(preds, calib, by=c("PA","run","points")) %>% left_join(., resps, by="points")

#extract predictions for validation dataset
test_preds <- filter(all, !calib.lines)

#responses all 1s or NAs...?
preds$resp
```

**Comment by rpatin** [comment]
Hello @lewistrotter,
Sorry I forgot that point: in `biomod2`, response can be `1` (presence), `0` (true absence) or `NA` (pseudo-absence). When you use pseudo-absences, you will have a combination of `1` and `NA` but you can replace `NA` by `0` for your calculations:
```
preds$resp <- ifelse(is.na(preds$resp), 0, 1)
```
Best,
Rémi

**Comment by lewistrotter** [comment]
Thanks Rémi, that worked!
