### ISSUE TITLE
About the Environment Data Regions Used by Biomod

### ISSUE THREAD

**Issue by colin123-tt** [biomodhub/biomod2#287]
In the maxent model I used before,we usually used the minimum polygon or point buffer to train the model.However, I found that biomod seems to use global enviromental data to train the model. Should we use global enviromental data ro set the minimum polygon or point buffer based on the point position to train the model when using biomod?

**Comment by rpatin** [comment]
Hi @colin123-tt,
We are not sure to fully understand your question :thinking:. So please correct me if my assumptions are wrong. 
I suppose, that you are looking for advice on how to select pseudo-absences to train the model. Your are generally using `maxent` and selecting pseudo absence with the _minimum polygon_ or _point buffer_. I suppose:
1. For the minimum polygon, you select pseudo-absences within the minimum convex polygon built with all presences
2. For the point buffer, you select pseudo-absences within a buffer around ) presences.

In  `biomod2` the default pseudo-absences selection method is a random sampling over the whole environmental grid (that you called _global environmental data_). However you can use other methods directly implemented in `biomod2` or provide directly the pseudo absences to `biomod2`. For that you need to set argument `PA.strategy` in `BIOMOD_FormatingData`:
- with `PA.strategy = 'random'` you get the default behaviour, random sampling on the whole raster
- with `PA.strategy = 'sre'` you generate pseudo absences outside of the broad environmental niche of the species
- with `PA.strategy = 'disk'` you generate pseudo absences within a minimum and maximum distance to all your presences (you can use your strategy for your point buffer method)
- with `PA.strategy = 'user.defined'` you can give pseudo-absences generated outside of `biomod2` (i.e. with your minimum polygon method.

As to which pseudo-absences strategy is better, it is not a question specific to `biomod2` but rather a generic modeling question. The answer depends on the research question and the potential bias in the data. Each pseudo-absences strategy comes with some assumptions which may or may not be appropriate given the case study. You can find more information on the [`biomod2` website](https://biomodhub.github.io/biomod2/articles/vignette_pseudoAbsences.html).

Hope this helps and feel free to elaborate if I missed something in your question.

Best regards,
Rémi

**Comment by colin123-tt** [comment]
Hello, my statement is incorrect. I am not asking how to select pseudo absent points, but rather how to select the range of pseudo absent points, using a global range or minimum polygon or point buffer?

In other words, do I see that Gulogulo in your sample file is a globally selected absence point? Do we also have to use a global scale to select our pseudo absence points?

**Comment by rpatin** [comment]
Hello @colin123-tt,
Sorry, I am not sure to understand the difference between _"how to select pseudo absent points"_ and _"how to select the range of pseudo absent points"_. The main issue in selecting pseudo-absence points is about the range in which the sampling is done. The different selection strategy proposed in `biomod2` are all about the range of selection (disk, SRE, whole area) and you can as well use your own method.

Concerning the choice in itself (which method to favor), I can only repeat that this is not a `biomod2` question but rather a generic SDM problem that depends on your case-study. The _Gulo gulo_ example is just one case study among other. In that one we did not used pseudo-absences, we just considered that the IUCN range was a faithful representation of presences (within the range) and absences (outside the range). The spatial scale (whole world) was chosen according to the question asked (range change under future climate for a widely distributed species). For other case study, other choices would have been made and pseudo-absences could have been required.

If you want more information on pseudo-absences and how to choose how to select them (or the range within which they are selected), I advise you to read the [related page on the website](https://biomodhub.github.io/biomod2/articles/vignette_pseudoAbsences.html).

Best regards,
Rémi

**Comment by colin123-tt** [comment]
Thank you for your patient answer
