### ISSUE TITLE
it seems time wasted in forecasting with duplicated MAXENT.Phillips models 

### ISSUE THREAD

**Issue by chenqh0618** [biomodhub/biomod2#29]
hello, 

it's not a bug but an problem I find.

when I use the function "BIOMOD_EnsembleForecasting" to forecaste my species under a new scenario, duplicated "MAXENT.Phillips"  models were applied, and environment asc file were wroten to my disk in each projection. 

file writing seems hard especially under a large map, and it is ok to write once as all projection are under the same environment.

So, I am interested if you could made some change to the code, so that duplicated MAXENT.Phillips projection in an forecasting only need once environment file writing.

Plus, maybe I am not familier enough to the package and there was already methods to exclude the problem. Could you please show how?
Nice day!

Jack Chen

**Comment by MayaGueguen** [comment]
_Some insights even if the subject is quite old_

Question was asked for `biomod2` version 3.5.
With changes to version 4.0, code for predictions should have been optimized, but the creation of `.csv` files for environment is quite inevitable, but computation time should have been minimized.
Code can be seen in function `.predict.MAXENT.Phillips_biomod2_model.data.frame` from the [biomod2_classes_4.R](https://github.com/biomodhub/biomod2/blob/master/R/biomod2_classes_4.R#L573) file.
