### ISSUE TITLE
Question about getting predictions from outfile

### ISSUE THREAD

**Issue by LindeNozomiLeo** [biomodhub/biomod2#295]
_Please make sure to close the issue once you consider it as solved_
_Please use screenshots only when you cannot copy-paste the object, e.g. for figures or maps_

Hi, I ran my code on a server and now I want access to the output by loading the outfiles and then use them to create maps. however now I'm getting the following error when I try and get the predictions

```
myBiomodEMPlant <-  get(load('lundiana_brylla_output/Mikania.lundiana.FutureEM_585_2100_GFDL.ensemble.projection.out'))

PlantProjEM <- get_predictions(myBiomodEMPlant, metric.binary = "TSS")
```

```
Error: [rast] file does not exist: ./Mikania.lundiana/proj_FutureEM_585_2100_GFDL/proj_FutureEM_585_2100_GFDL_Mikania.lundiana_ensemble_TSSbin.tif
In addition: Warning message:
./Mikania.lundiana/proj_FutureEM_585_2100_GFDL/proj_FutureEM_585_2100_GFDL_Mikania.lundiana_ensemble_TSSbin.tif: No such file or directory (GDAL error 4) 
```

it seemed to work for other time period I have, but this might be because I had some practice run on my computer, from which it might somehow still get information (this is really not ideal, as the quality of the ouput is lowever and I had no idea this was happening).

**Comment by rpatin** [comment]
Hi @LindeNozomiLeo,
Thank you for reporting :pray: 
I need some additional information here.
1. Did you ran the code on the server ? Or did you download the folders from the server and run the code on another computer ?
2. Did you looked for the folders `Mikania.lundiana/proj_FutureEM_585_2100_GFDL/` ?
3. Which OS are you using ?

Thanks in advance,
Best regards,
Rémi

**Comment by LindeNozomiLeo** [comment]
Hi, the specific code in this post was run on a computer with folders downloaded from the server. 
The folder that you mention does indeed exist on the server, in this case i hadn't downloaded the whole folder just the output file I need.
and when I'm trying to run the pasted code with files downloaded from the server I just do it on Rstudio on iOS, because I want to use the outfile to create maps and more visually interact with it. I believe the server is ubuntu. I'm not sure if this is the information you need.

**Comment by rpatin** [comment]
Hi,
Thank you for the update :pray: 
Ok, so when you download the whole folder, does it works correctly ? The output files rely on the whole folder.

Great, thanks for the OS info. I was asking because on windows there are issues with long path but that is likely not your concern here then !
Best,
Rémi

**Comment by rpatin** [comment]
Hi @LindeNozomiLeo,
Did you finally solve your issue ? Can you tell what the problem/solution were ?
Thanks,
Rémi
