### ISSUE TITLE
Help with BIOMOD - how to compute spatial autocorrelation

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#298]
Hi,

Id like to compute spatial autocorrelation for my model. Is there anyway to do it within BIOMOD2? I am trying to do it with the method from (Guisan, A.; Thuiller, W. & Zimmermann, N. E. (2017): Habitat Suitability and Distribution Models. With Applications in R. Cambridge: Cambridge University Press.) p. 114: 

```
> library(ape)
> xy <- pts.cal[,1:2]
> dists <- as.matrix(dist(xy))
> dists.inv <- 1/dists
> diag(dists.inv) <- 0
> Moran.I(a$residuals, dists.inv)
```

In this example `a` is: 
```
a = get_formal_model(Vorkommen_allData_RUN1_GLM)
```
 from one of my model runs. When running this code i get the following error:

```
Error in Moran.I(a$residuals, dists.inv) : 
  'weight' must have as many rows as observations in 'x'
```
Is there any way to compute spatial autocorrelation or did i make a mistake?

Best,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Thank you for reporting :pray: 
Unfortunately `biomod2` have not internal functions for auto-correlation checks.

Concerning your script, it seems there is a dimension mismatch between your residuals and `dist.inv`. Did you ensure to use only calibration data in `pts.cal` ? How did you generate `pts.cal` ?
You can check the mismatch with `length(a$residuals)` and `dim(dist.inv)`.

Best,
Rémi

**Comment by xiangyataboy** [comment]
> Hi,
> 
> Id like to compute spatial autocorrelation for my model. Is there anyway to do it within BIOMOD2? I am trying to do it with the method from (Guisan, A.; Thuiller, W. & Zimmermann, N. E. (2017): Habitat Suitability and Distribution Models. With Applications in R. Cambridge: Cambridge University Press.) p. 114:
> 
> ```
> > library(ape)
> > xy <- pts.cal[,1:2]
> > dists <- as.matrix(dist(xy))
> > dists.inv <- 1/dists
> > diag(dists.inv) <- 0
> > Moran.I(a$residuals, dists.inv)
> ```
> 
> In this example `a` is:
> 
> ```
> a = get_formal_model(Vorkommen_allData_RUN1_GLM)
> ```
> 
> from one of my model runs. When running this code i get the following error:
> 
> ```
> Error in Moran.I(a$residuals, dists.inv) : 
>   'weight' must have as many rows as observations in 'x'
> ```
> 
> Is there any way to compute spatial autocorrelation or did i make a mistake?
> 
> Best, Ben

Hello, have you succeeded in the spatial autocorrelation of the computational model in biomod2?
