### ISSUE TITLE
Help with BIOMOD_modelling - [How to get p-value from GLM]

### ISSUE THREAD

**Issue by GitBen01** [biomodhub/biomod2#300]
Hey,

i am doing univariable GLM models to preselect variables. With "get_formal_model" I get access to the coefficents. Is there a way to get the significance level/p-value?

Best,
Ben

**Comment by rpatin** [comment]
Hi Ben,
Thank you for reporting :pray: 
Did you solve your problem ? Feel free to share the solution if that is the case.
Best,
Rémi
