### ISSUE TITLE
  BIOMOD_FormatingData gave Error: std::bad_alloc. 

### ISSUE THREAD

**Issue by sandeepB055** [biomodhub/biomod2#306]
**Error and context**
preparing biomod formattingdata using all 19 bioclimatic variables in a single stack for a data of 27 occurences. running the code gave me this error line "Error: std::bad_alloc" in the console.
i repeated the same code with lesser number of PA but still same error. 

**Code used to get the error**

```
 read data ----
P.karavaali <- read.csv("p Karaavali.csv")
summary(P.karavaali)
head(P.karavaali)



bioclim_ZA_sub <- 
  raster::stack(
    c(
      bio1 <- raster('Current/wc2.1_30s_bio_1.tif'),
      bio2 <- raster('Current/wc2.1_30s_bio_2.tif'),
      bio3 <- raster('Current/wc2.1_30s_bio_3.tif'),
      bio4 <- raster('Current/wc2.1_30s_bio_4.tif'),
      bio5 <- raster('Current/wc2.1_30s_bio_5.tif'),
      bio6 <- raster('Current/wc2.1_30s_bio_6.tif'),
      bio7 <- raster('Current/wc2.1_30s_bio_7.tif'),
      bio8 <- raster('Current/wc2.1_30s_bio_8.tif'),
      bio9 <- raster('Current/wc2.1_30s_bio_9.tif'),
      bio10 <- raster('Current/wc2.1_30s_bio_10.tif'),
      bio11 <- raster('Current/wc2.1_30s_bio_11.tif'),
      bio12 <- raster('Current/wc2.1_30s_bio_12.tif'),
      bio13 <- raster('Current/wc2.1_30s_bio_13.tif'),
      bio14 <- raster('Current/wc2.1_30s_bio_14.tif'),
      bio15 <- raster('Current/wc2.1_30s_bio_15.tif'),
      bio16 <- raster('Current/wc2.1_30s_bio_16.tif'),
      bio17 <- raster('Current/wc2.1_30s_bio_17.tif'),
      bio18 <- raster('Current/wc2.1_30s_bio_18.tif'),
      bio19 <- raster('Current/wc2.1_30s_bio_19.tif')
       )
  )

bioclim_ZA_sub

format the data ----
P.karavaali_data <- 
  BIOMOD_FormatingData(
    resp.var = P.karavaali['Phrynoderma.karavaali'],
    resp.xy =P.karavaali[, c('Longitude', 'Latitude')],
    expl.var = bioclim_ZA_sub,
    resp.name = "Phrynoderma.karavaali",
    PA.nb.rep = 1,
    PA.nb.absences = 90,
    PA.strategy = 'random'
  )
```
>>>>>the console output of the function for which an error occurred.<<<<

```
## format the data ----
> P.karavaali_data <- 
+   BIOMOD_FormatingData(
+     resp.var = P.karavaali['Phrynoderma.karavaali'],
+     resp.xy =P.karavaali[, c('Longitude', 'Latitude')],
+     expl.var = bioclim_ZA_sub,
+     resp.name = "Phrynoderma.karavaali",
+     PA.nb.rep = 1,
+     PA.nb.absences = 270,
+     PA.strategy = 'random'
+   )

-=-=-=-=-=-=-=-=-=-= Phrynoderma.karavaali Data Formating -=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation

Checking Pseudo-absence selection arguments...

      ! No data has been set aside for modeling evaluation
   > random pseudo absences selection
Error: std::bad_alloc                     natory variables
> beepr::beep(8)
> gc()
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4438201 237.1    7634688 407.8  7634688 407.8
Vcells 6568727  50.2   12255594  93.6 10146236  77.5
> ## format the data ----
> P.karavaali_data <- 
+   BIOMOD_FormatingData(
+     resp.var = P.karavaali['Phrynoderma.karavaali'],
+     resp.xy =P.karavaali[, c('Longitude', 'Latitude')],
+     expl.var = bioclim_ZA_sub,
+     resp.name = "Phrynoderma.karavaali",
+     PA.nb.rep = 1,
+     PA.nb.absences = 90,
+     PA.strategy = 'random'
+   )

-=-=-=-=-=-=-=-=-=-= Phrynoderma.karavaali Data Formating -=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation

Checking Pseudo-absence selection arguments...

      ! No data has been set aside for modeling evaluation
   > random pseudo absences selection
Error: std::bad_alloc                     natory variables
```

additional info:   my laptop has 64 bit windows & 8gb ram. running lastesst version of R

**Comment by rpatin** [comment]
Hello @sandeepB055,
Thank you for reporting and using our template :pray: 
I feel this is a memory issue. Can you try:
1. Using `terraOptions(todisk = TRUE)`
2. Loading your data directly with `terra` rather than `raster`. FYI `raster` package will disappear soon:
```
library(terra)
bioclim_ZA_sub <- 
    rast(paste0('Current/wc2.1_30s_bio_',1:19,'.tif'))
names(bioclim_ZA_sub) <- paste0("bio",1:19)
```
Best regards,
Rémi

**Comment by rpatin** [comment]
Yes exactly. But please also remember to add `terraOptions(todisk = TRUE)`.
I am not sure this will solve your issue. If it does not we will likely have additional questions.

**Comment by sandeepB055** [comment]
still shows the same error

what could this mean? 
what if i reduce the number of variables i used. from 19 to like 3 or 4? will that take the load off ?

**Comment by rpatin** [comment]
`Error: std::bad_alloc` is highly likely to be a memory issue. It happens in the selection of pseudo-absences so I suppose that your raster file is very large. Can you print the results of `show(bioclim_ZA_sub)` ?
You may also try solution from other `biomod2` related to that error, see for instance [here](https://github.com/biomodhub/biomod2/issues/233#issuecomment-1523127698). You can try changing `terraOptions`:
   - `terraOptions(memfrac = 0.3)` will decrease the proportion of RAM that `terra` can use (default is 60%) as in https://github.com/rspatial/terra/issues/888#issuecomment-1386602439
   - `terraOptions(steps = 10)` will increase the number of chunks used in `terra` calculations as in https://github.com/rspatial/terra/issues/562#issuecomment-1057249873
  
If that still do not work, I may need to have your data to help your further (remi.patin@univ-grenoble-alpes.fr)
Best,
Rémi

**Comment by sandeepB055** [comment]
here is what my variables raster file looks like


> show(bioclim_ZA_sub)
class       : SpatRaster 
dimensions  : 21600, 43200, 19  (nrow, ncol, nlyr)
resolution  : 0.008333333, 0.008333333  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
sources     : wc2.1_30s_bio_1.tif  
              wc2.1_30s_bio_2.tif  
              wc2.1_30s_bio_3.tif  
              ... and 16 more source(s)
names       :      bio1,     bio2,       bio3,     bio4,  bio5,  bio6, ... 
min values  : -54.77083,  1.00000,   8.243729,    0.000, -31.2, -72.6, ... 
max values  :  31.38750, 22.23333, 100.000000, 2382.525,  48.6,  26.5, ... 



i tried the terraOptions(memfrac = 0.3)  but still the error persists

**Comment by rpatin** [comment]
Hi @sandeepB055,
Thank you for the additional information :pray: 
I am now quite convinced that you have a memory issue. You are manipulating a raster with 9*10^8 cells with only 8Gb of RAM so I am not sure there is an issue to that. I would have expected that `terraOptions(todisk = TRUE)` would solve your issue, but maybe you also had a limited disk space.

Among the advices we can give:
- work with more RAM & diskspace
- try using less than 19 bioclim variable (additionally there are correlations among them so you do not need all of them)
- you only have thirty or so data points, so do you really need such a large raster ? Maybe try reducing the extent of your study to limit the size of the raster you use
- do you really need a resolution of 30 arcseconds ? Maybe try working with a lower resolution

Best,
Rémi

**Comment by sandeepB055** [comment]
thank you for the help and inputs.

i will trim my dataset and try again.
