### ISSUE TITLE
How can I get TSS, ROC, KAPPA for calibration validation in BIOMOD_EnsembleModeling function?

### ISSUE THREAD

**Issue by Samyar1400** [biomodhub/biomod2#307]
Hi
I want to check if ensemble models perform better than RF, GLM, CTA etc. 

when I run the following codes, I get the evaluation metrics KAPPA','TSS','ROC' for both calibration and validation datasets:

```
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id= "Quercus cast.",
                                    models = c('RF','GLM','GBM','GAM','CTA'), 
                                    bm.options = myBiomodOption,
                                    CV.strategy = "random",
                                    CV.perc = 0.8,
                                    CV.nb.rep = 10,
                                    metric.eval = c('KAPPA','TSS','ROC'),
                                    var.import = 10,
                                    nb.cpu = 20)
```

When I run ensemble models using these codes, I only get the metrics for calibration, and the columns evaluation and valuation are NA. I can not understand why:

```
ensemble_models_TSS <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                               models.chosen = "all",
                                               em.by = 'all',
                                               metric.select = "TSS"),
                                               metric.select.thresh =  0.4,
                                               metric.eval = c("KAPPA", "TSS", "ROC"),
                                               var.import = 10,
                                               nb.cpu = 20,
                                               prob.cv = TRUE,
                                               em.algo = c('EMmean', 'EMmedian', 'EMca', 'EMwmean'))
```
I get the output something like that:

```
                                            full.name merged.by.PA merged.by.run merged.by.algo
1 GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
2 GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
3   GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
4   GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
  filtered.by   algo metric.eval cutoff sensitivity specificity calibration validation evaluation
1         TSS EMmean         TSS  545.0      95.764      96.716       0.925         NA         NA
2         TSS EMmean         ROC  540.5      96.067      96.661       0.995         NA         NA
3         TSS   EMca         TSS  626.0      95.915      98.248       0.942         NA         NA
4         TSS   EMca         ROC  625.0      95.915      98.248       0.994         NA         NA
> 
```
I would be very grateful if you can help me.

Thanks

**Comment by mula-jpg** [comment]
Hi Samyar1400,
Thanks for reporting.
Please follow #231, you can get clear answer
best

**Comment by rpatin** [comment]
Hi @Samyar1400 and thank you @mula-jpg for the answer.
I will close the issue but feel free to re-open it if something is still unclear.
Best,
Rémi

**Comment by Samyar1400** [comment]
Dear @rpatin and @mula-jpg thank you so much for the answer.

I got confused. 
I still have this question that HOW can I understand that if ensemble models perform better than RF, GLM, CTA or NOT. 
If the manuscript reviewers ask me why you used ensemble models, I cannot explain and justify the reviewers.
I would be very grateful if you can help me.

Another question is:
If I want to use this approach for evaluating the ensemble models:
use an independent evaluation dataset, using arguments eval.resp, eval.xy and/or eval.env.data in BIOMOD_FormatingData

I want to split the data into 70-30 percentage, repeat it 10 times and based on this independent dataset, I want to cross validate the ensemble models.

Thanks.
Regards
Jalil


Can I
