### ISSUE TITLE
How is the Ensemble modeling evaluation calculated ?

### ISSUE THREAD

**Issue by FannyThiery** [biomodhub/biomod2#308]
Hi all,

Firstly first, thank you for this amazing package !

I am currently modelling a marine species distribution and did an ensemble model and I wanted to know how the evaluation (last column of the 1st table) that you obtain thanks the eval data you put in the BIOMOD_FormatingData function at the beginning is calculated ? 
And how different is the evaluation of My Ensemble Model, filtered by ROC, filtered by algo = EMmean, metric.eval = ROC from manually calculating the mean of each single evaluation of prediction (predict.eval column in the 2nd table) by algo = EMmean and by eval.metrics = ROC ?

`> myBiomodEM@models.evaluation@val`

| sensitivity | specificity | calibration | validation | evaluation |
|--------|--------|--------|--------|--------|
| 89.928 | 87.239 | 0.962 | NA | 0.962 |
| 89.928 | 86.788 | 0.768 | NA | 0.768 |
| 89.928 | 87.200 | 0.962 | NA | 0.962 |
| 89.928 | 86.785 | 0.768 | NA | 0.768 |
| 85.612 | 91.121 | 0.969 | NA | 0.969 | 

*I just put the end of the table

`> myBiomodEM@models.prediction.eval@val`

| merged.by.algo | filtered.by | algo | pred.eval |
|--------|--------|--------|--------|
| mergedRun | mergedAlgo | ROC | 0.29692169 |
| mergedRun | mergedAlgo | ROC | 0.29692169 |
| mergedRun | mergedAlgo | ROC | 0.29692169 |
| mergedRun | mergedAlgo | ROC | 0.12270450 |
| mergedRun | mergedAlgo | ROC | 0.12270450 | 

I did calculate the mean of the 'pred.eval' column for EMmean that I first extracted by ROC and by TSS separately for each prediction and I obtain 0,2041  while the result for the 'evaluation' column in the first tab for EMmean by ROC is 0,962...
Same for TSS..
Did I do something wrong or do these 2 things aren't the same or calculated the same way ?

Thank you !

**Comment by rpatin** [comment]
Hi Fanny,
Thank you for reporting :pray:

The values you get in `myBiomodEM@models.prediction.eval@val` are the model predictions for the evaluation dataset, i.e. whether the species is predicted present or absent on a continuous scale. The fact that values here are low or here does not mean that your model is good or bad. 

The values you get in `myBiomodEM@models.evaluation@val` (or more easily through `get_evaluations(myBiomodEM)`) are aggregated metrics used to evaluate that compare model predictions for the evaluation dataset with their observed values. There are several way of doing this comparison (`AUC/ROC`, `TSS`) but they are not calculated by averaging model predictions.

Hope this is clearer. Feel free to update if not.
For more information on the basis of model evaluation I would advise to refer to textbooks on SDM.
Best regards,
Rémi

**Comment by FannyThiery** [comment]
Hi Rémi !

**Comment by FannyThiery** [comment]
Hi Rémi ! 

Thank you for taking time to answer. 
I do understand the differences now between `myBiomodEM@models.prediction.eval@val` and `myBiomodEM@models.evaluation@val`
But now, if `myBiomodEM@models.prediction.eval@val` is the value of the model prediction for the evaluation dataset, then what is `myBiomodEM@models.prediction@val` and what are the differences in between these two ? (I though `models.prediction.eval` was the evaluation of each single prediction point and `models.prediction` was the actual value (rather presence or absent on a continuous scale) of the prediction

And how is the evaluation (based on the evaluation dataset that I provided) calculated for an Ensemble model then ? 
For example, how the fist line evaluation (filtered.by = ROC, algo = EMmean, metric.eval = ROC) is calculated ?
<img width="857" alt="Capture d’écran, le 2023-08-18 à 12 14 19" src="https://github.com/biomodhub/biomod2/assets/100318109/6f03fed8-3051-412d-914b-d5b8373c2178">

Thank you very much, bests,
Fanny

**Comment by rpatin** [comment]
Hi Fanny,
Thank you for the update :pray: 
`myBiomodEM@models.prediction.eval@val` are the model predictions for the evaluation dataset
Meanwhile `myBiomodEM@models.prediction@val` are the model predictions for the calibration/validation dataset.
Evaluation metric are calculated globally and not pointwise. The actual value (rather presence or absent on a continuous scale) of the prediction is not directly available from those object slots. It is a combination of the threshold in the evaluation table and the model predictions (be it for the evaluation dataset or the calibration/validation dataset).
In general you should avoid digging into the object slots and would likely benefit from using the available functions (i.e. `get_predictions`, `get_evaluations` ...) described in the documentation: https://biomodhub.github.io/biomod2/reference/getters.out.html. Object slots might be useful when you have very specific need unfulfilled by the available functions.

For the evaluation of an ensemble models, it depends:
- if your model ensemble several cross-validation dataset, then all data are used as calibration and the evaluation metric are calculated on the whole calibration dataset. Evaluation is then not really independent from the data used to fit the model (although as it is an ensemble model it is slightly more complex). Evaluation metric on the evaluation dataset is however calculated as for the individual models
- if your model ensemble only one cross-validation dataset (i.e. `em.by = "PA+run"`) then evaluation is done as for the individual models with both `calibration`, `validation` and `evaluation` (if provided).

I hope this is clearer. If not feel free to update the post.
Best,
Rémi

**Comment by FannyThiery** [comment]
Thanks Rémi, 

Yes it is clearer ! 
When you say 'It is a combination of the threshold in the evaluation table and the model predictions' what do you mean about threshold ? is it the cutoff value that comes out in the table ?

Thank you again for taking time to answer,
Fanny

**Comment by rpatin** [comment]
Yes, the threshold are the cutoff value from the table.
Best,
Rémi
