### ISSUE TITLE
help with em.by

### ISSUE THREAD

**Issue by LindeNozomiLeo** [biomodhub/biomod2#314]
Hi, I was wondering what would be recommended for em.by when trying to ensemble models through EMmean, as well as EMcv or EMca. I understand that the EM.by are different ways of putting models together, however I do not understand what would be the most useful or valuable combination to form an ensemble model. so far I have been ensembling al my algoritms and run and psuedoabsence datasets together, and I’m quite happy with this besides that it cannot provide me with validation data. I’m curious which combination would be considered most relevant, when one is interested in the final distribution and not necessarily preformance between models.

these are my modelling settings
```
myBiomodModelOut<- BIOMOD_Modeling(bm.format=myBiomodData,
                                   models=c('GLM','GAM','RF','MAXENT'),
                                   bm.options=myBiomodOptions,
                                   var.import=3, 
                                   metric.eval= c('TSS','ROC'),
                                   CV.strategy = 'random',  
                                   CV.nb.rep = 3, 
                                   CV.perc = 0.75, 
                                   prevalence = 0.5)
```

**Comment by rpatin** [comment]
Hi @LindeNozomiLeo,
Thank you for reporting :pray: 

`em.by` can be used in several way depending on your aim when using ensemble models. Broadly speaking, there are two general aims to ensemble models:
1. Having the best predictions possible. Then you can build a single set of ensemble model (i.e. one _EMmean_ and one _EMcv_) that can integrate the variability of both algorithm, cross-validation and pseudo-absence dataset. Then using `em.by = 'all'` is generally the way to go.
2. Understanding the differences between algorithm, cross-validation and pseudo-absence dataset. Then you may wan to build several sets of ensemble models, that can help you understanding those differences. For example:
   - If you hints large differences between algorithm, you can use `em.by = 'algo'.
   - If you hints large differences between cross-validation dataset, you can use `em.by = 'PA+run'.
   - If you hints large differences between pseudo-absence dataset you can use `em.by = 'PA'.

Finally when you are interested in the final distribution and do not have large differences between algorithm/cross-validation and PA dataset (which you should try to understand if any) you are then aligning with goal 1 and should use `em.by = 'all'`.

Hope this helps,
Best,
Rémi
