### ISSUE TITLE
Categorical variables - variable importance analysis 

### ISSUE THREAD

**Issue by ellalewi547** [biomodhub/biomod2#316]
**Context and question**
Hello, I wondered if there was a way to evaluate the results for categorical variables - specifically whether there is a function to view the relative importance for each category within the variable. So in my case, we have dominant tree species and land cover type as the two categorical variables in the raster stack. It would be really useful to see exactly how each specific land cover type influence preference for the analysis, as the response curves do not seem to be compatible for categorical variables. My project is looking into habitat suitability for pine marten and it would be really useful to see, for example we expect, pine marten to show more preference for deciduous forest land cover and low preference for urban etc..  Is there a specific function to do this?

I hope this makes sense, let me know if you require further detail. Thank you very much for your time.

Ella

**Comment by rpatin** [comment]
Hello Ella,
Thank you for reporting :pray: 

Unfortunately there are no specific function to do this within `biomod2`.
You can however manually use the `biomod2` function to build such analysis. You can build a `data.frame` to setup a grid of values with different factor levels and a range of environmental conditions. Then you can use `BIOMOD_Projection` to get model predictions and you can finally analyse your predictions based on the factor levels to have the information you need. If need be I can send a short reproducible example, please let me know in that case.

Best regards,
Rémi

**Comment by mula-jpg** [comment]
Hello Remi,
 I factorized the categorical variables before running Biomod_modeling but their response curve showed a continuous graph. could you show me why the this happen? I expect the categorical (bar) graph style.

**Comment by mula-jpg** [comment]
Sorry, I will comeback with new Issue

**Comment by ellalewi547** [comment]
Hi Rémi, thank you for your response, we will look into building the analysis. I also just wanted to flag up an issue we have come across with the single model projections onto a new environment. We were experiencing an error message for the projection onto the new environment as: 'task 48 failed "factor land_cover has new levels 15"' (sorry I don't have the script to send you in the correct format). 
The error message was due to the fact the new environmental raster stack (Britain) had a landcover (class 15), but this class was not present in the training data/models (Europe) (presumably no presences or absences were detected in saltmarsh in the current/training raster stack, and thus the model didn't know what/how to project onto a new class)? So to fix this problem, we set land class 15 in the new environmental raster stack to NA and then it work. 
So it could be dealt with by allowing the model to run successfully and just projecting NA where the land class (or category more generally) is missing in the training data - so in our case land class 15. 

I do hope that makes sense without sending you the code but let me know if you would need it. 
Thank you again, Ella

**Comment by rpatin** [comment]
Hi Ella,
Thank you for the update :pray: 
Indeed, the model cannot project on unknown factor levels. Converting to NA would be an alternative strategy to what `biomod2` currently. I would favor the current strategy of leaving the task up to the user, which also forces the user to be aware of the issue. But I will discuss that with the dev team to confirm that.
Best,
Rémi
