### ISSUE TITLE
independent evaluation dataset for cross validate the ensemble models.

### ISSUE THREAD

**Issue by Samyar1400** [biomodhub/biomod2#318]
Dear @rpatin and @mula-jpg thank you so much for the answer to my comment #307.

I still have this question that HOW can I understand that if ensemble models perform better than RF, GLM, CTA or NOT.
If the manuscript reviewers ask me why I used ensemble models, I cannot explain and justify the reviewers.
I would be very grateful if you can help me.

Another question is:
If I want to use this approach for evaluating the ensemble models as you explained:
use an independent evaluation dataset, using arguments eval.resp, eval.xy and/or eval.env.data in BIOMOD_FormatingData

I want to split the data into 70-30 percentage, repeat it 10 times and based on this independent dataset, I want to cross validate the ensemble models.

Thanks.
Regards

**Comment by rpatin** [comment]
Dear @Samyar1400,

The idea behind ensemble models is to allow you to consider different types of models (RF, GLM, CTA ...). When several of them have good performance, you may benefit from using ensemble models. The idea behind ensemble models is not only to have better predictions, but also to have an idea of the mean predictions across models (i.e. using the mean of predictions across models) as well as their agreement (i.e. using the CV of predictions across models). That second point in itself is a sufficient justification to using ensemble models.

If you want to use ensemble models to have better predictions and want to justify it, then you need to evaluate the improvement in predictions and this is likely using an independent dataset (as you cited with arguments `eval.resp`, `eval.xy` and/or `eval.env.data` in BIOMOD_FormatingData). 

What you can do if you have 2 dataset: dataset 1 and dataset 2. Dataset 1 will be used to build the individual model. Dataset 2 will evaluate all models (individual or ensemble). Dataset 1 can the be split into 70-30 percentage to crossvalidate the individual models you can repeat the split 10 times for instance. However you can have only one evaluation of your ensemble model (with dataset 2). If you want to repeat the evaluation of your ensemble model you need to build several ensemble model. i.e. for each cross-validation fold (within dataset 1) you build an ensemble models across algorithm. You can then have a cross-validation of your ensemble model, but you will have several ensemble models, which may defeat your purpose of having a single model.

I hope this is clearer, if not feel free to ask more questions.
Best,
Rémi
