### ISSUE TITLE
Error in BIOMOD_4.2-4- bm_PlotEvalMean returns "Error in names(x) <- value : ..."

### ISSUE THREAD

**Issue by silveiratcl** [biomodhub/biomod2#319]
Hello, 

I´m updating an old code to the new version 4.3-4.  I changed the names of the arguments to the new version.
This is a sample of my  updated code:
 ```
myRespName <- 'Tubastraea coccinea'
DataSpecies <- as.numeric(df$occ_abs)
myRespXY <- df[,c("lon_dd", "lat_dd")]

predictors1 <- variables
names(predictors1) <- c ('bat', 'velc', 'sst', 'd_cost', 'd_mar', 'd_traf')
predictors1

myBiomodData1 <- BIOMOD_FormatingData(resp.var = DataSpecies,
                                      expl.var = predictors1,
                                      resp.xy = myRespXY,
                                      resp.name = myRespName)

myBiomodOption <- BIOMOD_ModelingOptions()
myBiomodOption

myBiomodModelOut1 <- BIOMOD_Modeling(myBiomodData1,
                                     models = c('GLM','RF'),
                                     bm.options = myBiomodOption,
                                     CV.nb.rep = 12,
                                     CV.strategy = "random",
                                     CV.perc = 0.7,
                                     prevalence = 0.5,
                                     var.import = 3,
                                     metric.eval = c('ROC'),
                                     scale.models = TRUE,
                                     CV.do.full.models = FALSE,
                                     modeling.id = 'Model1',
                                     seed.val = 42)

bm_PlotEvalMean(bm.out = myBiomodModelOut1)
```

Them I got the error message:

"Error in names(x) <- value : 
  'names' attribute [5] must be the same length as the vector [3]"

Any idea?

**Comment by rpatin** [comment]
Hello @silveiratcl,
Thank you for reporting :pray: 
Could you share a bit more information so that I can try to reproduce the error ? e.g. the output of:
- `show(myBiomodData1)`
- `show(myBiomodModelOut1)`
- `sessionInfo()`

In the case I fail at reproducing the issue, it would help if you could share your data (or a subset with a reproducible example).
Thanks in advance,
Best,
Rémi

**Comment by silveiratcl** [comment]
Hello Remi, thanks!

 show(myBiomodData1)
-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=
dir.name =  .

sp.name =  Tubastraea.coccinea

	 8 presences,  13 true absences and  0 undefined points in dataset


	 6 explanatory variables

      bat              velc             sst            d_cost      
 Min.   :0.3992   Min.   :0.1158   Min.   :21.69   Min.   :  0.00  
 1st Qu.:2.1034   1st Qu.:0.1583   1st Qu.:21.77   1st Qu.:  0.00  
 Median :3.3900   Median :0.1699   Median :21.84   Median :  0.00  
 Mean   :3.3562   Mean   :0.1661   Mean   :21.88   Mean   : 35.84  
 3rd Qu.:4.6848   3rd Qu.:0.1833   3rd Qu.:21.85   3rd Qu.: 82.52  
 Max.   :9.0676   Max.   :0.2508   Max.   :22.31   Max.   :165.11  
     d_mar             d_traf     
 Min.   :  198.3   Min.   : 1193  
 1st Qu.: 7792.2   1st Qu.: 1539  
 Median :15056.4   Median : 2223  
 Mean   :12360.9   Mean   : 7000  
 3rd Qu.:16643.2   3rd Qu.: 5728  
 Max.   :29385.5   Max.   :30406  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Warning message:
Not a validObject(): no slot of name "srs" for this object of class "RasterLayer" 



> show(myBiomodModelOut1)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Modeling folder : .

Species modeled : Tubastraea.coccinea

Modeling id : Model1

Considered variables : bat velc sst d_cost d_mar d_traf


Computed Models :  Tubastraea.coccinea_allData_RUN1_GLM 
Tubastraea.coccinea_allData_RUN1_RF Tubastraea.coccinea_allData_RUN2_GLM 
Tubastraea.coccinea_allData_RUN2_RF Tubastraea.coccinea_allData_RUN3_GLM 
Tubastraea.coccinea_allData_RUN3_RF Tubastraea.coccinea_allData_RUN4_GLM 
Tubastraea.coccinea_allData_RUN4_RF Tubastraea.coccinea_allData_RUN5_GLM 
Tubastraea.coccinea_allData_RUN5_RF Tubastraea.coccinea_allData_RUN6_GLM 
Tubastraea.coccinea_allData_RUN6_RF Tubastraea.coccinea_allData_RUN7_GLM 
Tubastraea.coccinea_allData_RUN7_RF Tubastraea.coccinea_allData_RUN8_GLM 
Tubastraea.coccinea_allData_RUN8_RF Tubastraea.coccinea_allData_RUN9_GLM 
Tubastraea.coccinea_allData_RUN9_RF Tubastraea.coccinea_allData_RUN10_GLM 
Tubastraea.coccinea_allData_RUN10_RF Tubastraea.coccinea_allData_RUN11_GLM 
Tubastraea.coccinea_allData_RUN11_RF Tubastraea.coccinea_allData_RUN12_GLM 
Tubastraea.coccinea_allData_RUN12_RF


Failed Models :  none

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
[3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_3.6-23 sp_1.6-0     

loaded via a namespace (and not attached):
 [1] maps_3.4.1             tidyr_1.3.0            jsonlite_1.8.4        
 [4] splines_4.2.3          foreach_1.5.2          carData_3.0-5         
 [7] Formula_1.2-5          yaml_2.3.5             pillar_1.9.0          
[10] backports_1.4.1        lattice_0.20-45        glue_1.6.2            
[13] pROC_1.18.4            digest_0.6.29          ggsignif_0.6.4        
[16] randomForest_4.7-1.1   colorspace_2.0-3       gbm_2.1.8.1           
[19] htmltools_0.5.4        cowplot_1.1.1          Matrix_1.5-3          
[22] plyr_1.8.8             pkgconfig_2.0.3        maxnet_0.1.4          
[25] PresenceAbsence_1.1.11 httpcode_0.3.0         broom_1.0.4           
[28] earth_5.3.2            purrr_1.0.1            scales_1.2.1          
[31] terra_1.7-39           TeachingDemos_2.12     timechange_0.2.0      
[34] tibble_3.2.1           mda_0.5-4              generics_0.1.2        
[37] car_3.1-2              ggplot2_3.4.2          xgboost_1.7.5.1       
[40] ggpubr_0.6.0           nnet_7.3-18            cli_3.6.1             
[43] rerddap_1.0.2          survival_3.5-3         magrittr_2.0.3        
[46] evaluate_0.15          ncdf4_1.21             fansi_1.0.3           
[49] MASS_7.3-58.2          rstatix_0.7.2          xml2_1.3.3            
[52] class_7.3-21           tools_4.2.3            data.table_1.14.2     
[55] lifecycle_1.0.3        stringr_1.5.0          munsell_0.5.0         
[58] plotrix_3.8-2          compiler_4.2.3         rlang_1.1.0           
[61] plotmo_3.6.2           grid_4.2.3             iterators_1.0.14      
[64] rstudioapi_0.14        rappdirs_0.3.3         heatwaveR_0.4.6       
[67] rmarkdown_2.14         gtable_0.3.0           codetools_0.2-19      
[70] abind_1.4-5            reshape_0.8.9          curl_4.3.2            
[73] reshape2_1.4.4         R6_2.5.1               lubridate_1.9.2       
[76] knitr_1.39             dplyr_1.1.1            fastmap_1.1.1         
[79] utf8_1.2.2             biomod2_4.2-4          hoardr_0.5.3          
[82] stringi_1.7.6          crul_1.3               Rcpp_1.0.11           
[85] vctrs_0.6.1            rpart_4.1.19           xfun_0.31             
[88] tidyselect_1.2.0

**Comment by rpatin** [comment]
Thank you for the update, I had no problem to reproduce your issue :pray: 
We had a hole in `bm_PlotEvalMean` checks that is now corrected (on the github version that you can get with `devtools::install_github('biomodhub/biomod2')`.

The problem was that you were trying to use `bm_PlotEvalMean` while you had only one evaluation metric (`ROC`) which is not possible. You can forego using `bm_PlotEvalMean` or use an additional evaluation metric in `BIOMOD_Modeling`, e.g. `TSS`.

Additionally, I noticed that you have a very small number of presences (8) and absences (13) and even less if you consider the cross-validation (6 presence and 9 absences in each calibration dataset). Meanwhile you are using 6 explanatory variables, which is way too much. With such a low number of presences you should not use more than one or two variables. Alternatively you can also use other techniques such as Ensemble of small models (ESM) for instance.

Best,
Rémi

**Comment by silveiratcl** [comment]
Hello Remi, thanks for  your help.

I got the github version and added the TSS metric `myBiomodModelOut1`. 
Also I reduced the number of predictor to 2 for this check.
Unfortunately now I got the following message: 

```
> bm_PlotEvalMean(bm.out = myBiomodModelOut2)
Error in draw_axis(break_positions = guide$key[[aesthetic]], break_labels = guide$key$.label,  : 
  lazy-load database 'C:/Users/silve/AppData/Local/R/win-library/4.2/gtable/R/gtable.rdb' is corrupt
In addition: Warning messages:
1: In draw_axis(break_positions = guide$key[[aesthetic]], break_labels = guide$key$.label,  :
  restarting interrupted promise evaluation
2: In draw_axis(break_positions = guide$key[[aesthetic]], break_labels = guide$key$.label,  :
  internal error -3 in R_decompress1
```

Any idea?
Thanks.
Thiago

**Comment by silveiratcl** [comment]
Hello Remi,

Unfortunately,  I´ve tried with the example on [documentation](https://www.rdocumentation.org/packages/biomod2/versions/4.2-4/topics/BIOMOD_Modeling) and got the same issue.

**Comment by rpatin** [comment]
Hello Thiago,
Can you try again after restarting R/Rstudio ?  the `lazy-load database` issue is common to many package and is generally solved be restarting R (see e.g. https://github.com/thomasp85/patchwork/issues/36)
Best,
Rémi

**Comment by silveiratcl** [comment]
Hell Rémi,
Now worked! Thanks by the help!
Cheers, 
Thiago
