### ISSUE TITLE
How to export Geotif? 

### ISSUE THREAD

**Issue by mula-jpg** [biomodhub/biomod2#321]
Dear Biomod2 developers,
 I want to export  the maps in terms of Geotif  to manipulate maps in ArcGIS but I did not get scripts in biomod2. Would you provide the scripts if available or is there other means?
Best,
Mulatu

**Comment by rpatin** [comment]
Dear Mulatu,
Thank you for reporting :pray: 
You can find the `.tif` files in your project folder (i.e. `GuloGulo/proj_Current/` or `GuloGulo/proj_Current/individual_projections` if you had `do.stack = FALSE`). Then you can open them with any GIS.
Alternatively you can use `get_predictions` on the output of `BIOMOD_Projection` to extract the raster in R and save them with `writeRaster` (although this feels a bit redundant)
Best,
Rémi
