### ISSUE TITLE
Please, can anyone tell me how to export geotif figures from the Biomod2 repackage for further processing in ArcGIS? including commands?

### ISSUE THREAD

**Issue by Ahmed4378** [biomodhub/biomod2#322]
Please, can anyone tell me how to export geotif figures from the Biomod2 repackage for further processing in ArcGIS? including commands?

**Comment by rpatin** [comment]
Hi @Ahmed4378,
Thank you for reporting :pray: 
Mulatu posted a similar issue so I will redirect you there: https://github.com/biomodhub/biomod2/issues/321
Best,
Rémi
