### ISSUE TITLE
Future projection  Error

### ISSUE THREAD

**Issue by mula-jpg** [biomodhub/biomod2#324]
Dear Biomod2 developers, 
  I tried to project future data but I faced an error. Here is the code?

```
        Mymodel<-BIOMOD_Modeling(
  bm.format=My_model,
  modeling.id = "allmdel1",
  models = c("GLM", "GBM", "GAM", "SRE", "CTA", "ANN", "FDA", "MARS", "RF", "MAXNET"),
  models.pa = NULL,
  bm.options = Mymodeling_Opt,
  CV.strategy = "random",
  CV.nb.rep = 3,
  CV.perc = 0.8,
  CV.k = NULL,
  CV.balance = NULL,
  CV.env.var = NULL,
  CV.strat = NULL,
  CV.user.table = NULL,
  CV.do.full.models = FALSE,
  weights = NULL,
  prevalence = 0.5,
  metric.eval = c("TSS", "ROC"),
  var.import = 3,
  scale.models = FALSE,
  nb.cpu = 0,
  seed.val = NULL,
  do.progress = TRUE)

## Load environmental variables extracted from BIOCLIM (biol3, biol4, biol7, biol9 & biol13,14, 15, 18, 19, Veget & lul)
 data(bioclim_future)
 myExplFuture <- terra::rast(c(Bio3_5045 = "biol3_5045.tif",Bio4_5045 = "biol4_5045.tif", Bio7_5045 = "biol7_5045.tif", Bio9_5045 = "biol9_5045.tif", Bio13_5045 = "biol13_5045.tif", Bio14_5045 = "biol14_5045.tif", Bio15_5045 = "biol15_5045.tif", Bio18_5045 = " biol18_5045.tif", Bio19_5045 = "biol19_5045.tif", Vege = "Veget.tif",
                               Lulc= "lul.tif"))
 myExplFuture<-stack(myExplFuture)
 myExplFuture
###Project onto future conditions
 myBiomodProjectionFuture <- BIOMOD_Projection(bm.mod = Mymodel,
                                               proj.name = 'Futur_5045eRangeSize',
                                               new.env = myExplFuture,
                                               models.chosen = all,
                                               metric.binary = 'TSS')
```

But the following error is happened. I want helps for this error
```
Error in .fun_testIfIn(TRUE, "names(new.env)", names(new.env), bm.mod@expl.var.names) : 
  
names(new.env) must be 'bio3', 'bio4', 'bio7', 'bio9', 'bio13', 'bio14', 'bio15', 'bio18', 'bio19', 'Veget' or 'lul
```

**Comment by rpatin** [comment]
Dear @mula-jpg,
Thank you for reporting :pray: 
The names of your future climate layer should match the names of your current climate layer. This is what the error message try to tell you. 
Here your future climate variable names are:
`Bio3_5045`, `Bio4_5045`, etc...
Instead of 
`bio3`, `bio4`, ... 
Beware of the letter case (here there should be no upper case).

I suppose if you do:
```
 myExplFuture <- terra::rast(c(bio3 = "biol3_5045.tif",bio4 = "biol4_5045.tif", bio7 = "biol7_5045.tif", bio9 = "biol9_5045.tif", bio13 = "biol13_5045.tif", bio14 = "biol14_5045.tif", bio15 = "biol15_5045.tif", bio18 = " biol18_5045.tif", bio19 = "biol19_5045.tif", Veget = "Veget.tif", lul = "lul.tif"))
```
This should work.

Best regards,
R2mi

**Comment by rpatin** [comment]
Dear Mulatu,
Thank you for the update :pray: 
How did you call the future climate variable ? And what is the error message that you get ?
The name you show are different from the error message you got before.
Best regards,
Rémi

**Comment by rpatin** [comment]
Dear Mulatu,
There are still discrepancy between what you typed and which code I wrote:
The error message asks for names such as `Veget` or `lul`, while you gave him `Vege` and `Lulc`.

The execution of `names(myExplFuture)` and `names(bioclim_curr)` should have the same output (the order does not matter however).

I hope this is clearer.
Best regards,
Rémi

**Comment by mula-jpg** [comment]
Dear Remi, 
 Sorry for repeated help request for one issue. It is a mandatory step and still I want to your help. There is still the same error message returned even if I removed the categorical variables (i.e. Veget and lul) in both current and future climatic conditions. Here are the variables what I want to use for the respective climatic condition  that put in the same working directory.
   For current:   bio3.tif, bio4.tif, bio7.tif, bio9.tif, bio13.tif, bio14.tif, bio15.tif", bio18.tif, bio19.tif
   For future_2050_4.5: bio3_5045.tif, bio4_5045.tif, bio7_5045.tif, bio9_5045.tif, bio13_5045.tif, bio14_5045.tif, bio15_5045.tif, bio18_5045.tif, bio19_5045.tif.  
Veget.tif and lul.tif are also the categorical variables which are constant in both conditions.  

Could you show me the possible scripts to project onto the future conditions.
 Best wishes,
Mulatu

**Comment by rpatin** [comment]
Dear Mulatu,
There is no problem for repeated help request and long issues :wink: 
Could you share:
- The code you use to load both current and future condition raster (i.e.   `myExplCurrent <- rast(...)` and `myExplFuture <- rast(...)`
- The output of both `names(myExplCurrent)` and `names(myExplFuture)`
- The output of `show(myBiomodData)`, the results of your call to `BIOMOD_FormatingData`

I am not sharing scripts to project onto future conditions, as the errors you encounter are highly likely tied to how you load the raster files for current and future conditions. 
Best regards,
Rémi

**Comment by mula-jpg** [comment]
Dear Remi,
Thank you too much for your willingness and patience
1) I loaded the current condition raster like this:
myExplCurrent <-  terra::rast( c("bio3.tif", "bio4.tif","bio7.tif","bio9.tif","bio13.tif","bio14.tif","bio15.tif","bio18.tif","bio19.tif", "Veget.tif", "lul.tif"))

myExplCurrent<-stack(myExplCurrent)
myExplCurrent

> names(myExplCurrent)
 [1] "bio3"  "bio4"  "bio7"  "bio9"  "bio13" "bio14" "bio15" "bio18" "bio19" "Veget"
[11] "lul" 

2)  Future condition raster:
    myExplFuture <- terra::rast(c(bio3 = "biol3_5045.tif",bio4 = "biol4_5045.tif", bio7 = "biol7_5045.tif", bio9 = "biol9_5045.tif", bio13 = "biol13_5045.tif", bio14 = "biol14_5045.tif", bio15 = "biol15_5045.tif", bio18 = " biol18_5045.tif", bio19 = "biol19_5045.tif", Veget = "Veget.tif", lul ="lul.tif"))
 myExplFuture<-stack(myExplFuture)
 myExplFuture

>   names(myExplFuture)
 [1] "biol3_5045"  "biol4_5045"  "biol7_5045"  "biol9_5045"  "biol13_5045"
 [6] "biol14_5045" "biol15_5045" "biol18_5045" "biol19_5045" "Veget"      
[11] "lul" 

3)show(myBiomodData)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  Vannn

sp.name =  myRespName

	 128 presences,  0 true absences and  10000 undefined points in dataset


	 11 explanatory variables

      bio3            bio4             bio7            bio9           bio13      
 Min.   :37.41   Min.   : 43.08   Min.   :13.60   Min.   : 4.50   Min.   : 20.0  
 1st Qu.:69.67   1st Qu.: 88.77   1st Qu.:16.80   1st Qu.:19.27   1st Qu.:100.0  
 Median :73.86   Median :113.82   Median :18.10   Median :22.33   Median :155.0  
 Mean   :72.19   Mean   :134.21   Mean   :18.36   Mean   :22.01   Mean   :169.7  
 3rd Qu.:76.33   3rd Qu.:156.96   3rd Qu.:19.80   3rd Qu.:25.33   3rd Qu.:226.0  
 Max.   :84.52   Max.   :386.74   Max.   :24.70   Max.   :32.63   Max.   :454.0  
                                                                                 
     bio14            bio15            bio18           bio19            Veget     
 Min.   : 0.000   Min.   : 35.13   Min.   : 17.0   Min.   :   0.0   1      :4393  
 1st Qu.: 2.000   1st Qu.: 68.72   1st Qu.:113.0   1st Qu.:  31.0   4      :2142  
 Median : 5.000   Median : 90.04   Median :160.0   Median :  53.0   5      :1727  
 Mean   : 8.814   Mean   : 90.37   Mean   :172.8   Mean   : 236.5   0      : 758  
 3rd Qu.:12.000   3rd Qu.:114.99   3rd Qu.:215.0   3rd Qu.: 476.0   6      : 465  
 Max.   :57.000   Max.   :138.93   Max.   :579.0   Max.   :1138.0   7      : 146  
                                                                    (Other): 497  
      lul      
 120    :4176  
 62     :1335  
 10     :1044  
 40     : 668  
 130    : 639  
 200    : 634  
 (Other):1632  


 1 Pseudo Absences dataset available ( PA1 ) with  10000 (PA1) pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Best regards
Mulatu

**Comment by rpatin** [comment]
Dear Mulatu,
Thank you for the update :pray:
So my first advice was wrong, you cannot rename the layer on the fly when loading a raster. So instead of writing:
```
myExplFuture <-  terra::rast(c(bio3 = "biol3_5045.tif",bio4 = "biol4_5045.tif", bio7 = "biol7_5045.tif", bio9 = "biol9_5045.tif", bio13 = "biol13_5045.tif", bio14 = "biol14_5045.tif", bio15 = "biol15_5045.tif", bio18 = " biol18_5045.tif", bio19 = "biol19_5045.tif", Veget = "Veget.tif", lul ="lul.tif"))
```
You should use:
```
myExplFuture <-  terra::rast(c("biol3_5045.tif","biol4_5045.tif", "biol7_5045.tif", "biol9_5045.tif", "biol13_5045.tif", "biol14_5045.tif",  "biol15_5045.tif", " biol18_5045.tif",  "biol19_5045.tif",  "Veget.tif", "lul.tif"))
names(myExplFuture) <- c("bio3","bio4","bio7", "bio9","bio13","bio14","bio15","bio18","bio19","Veget","lul")
```
You can then check that it worked with `names(myExplFuture)`. If that does not gives you the same name you had in `myExplCurrent`, there is no point in running the projection.

Also, you do not need to use `myExplCurrent<-stack(myExplCurrent)`. The `raster` package is deprecated and will disappear soon. Plus, `biomod2` will immediately convert the raster into `terra` format anyway.

Best regards,
Rémi

**Comment by mula-jpg** [comment]
Dear Remi,
Thank you very much. it is better now but there is error during projection onto future condition. Here is code and output.
   Code:    myExplFuture <-  terra::rast(c("biol3_5045.tif","biol4_5045.tif", "biol7_5045.tif", "biol9_5045.tif", "biol13_5045.tif", 
                                    "biol14_5045.tif",  "biol15_5045.tif", " biol18_5045.tif",  "biol19_5045.tif",  "Veget.tif", "lul.tif"))
      names(myExplFuture) <- c("bio3","bio4","bio7", "bio9","bio13","bio14","bio15","bio18","bio19","Veget","lul")
      names(myExplFuture)
Output: 
                   >  myExplFuture <-  terra::rast(c("biol3_5045.tif","biol4_5045.tif", "biol7_5045.tif", "biol9_5045.tif", "biol13_5045.tif", "biol14_5045.tif",  "biol15_5045.tif", " biol18_5045.tif",  "biol19_5045.tif",  "Veget.tif", "lul.tif"))
>  names(myExplFuture) <- c("bio3","bio4","bio7", "bio9","bio13","bio14","bio15","bio18","bio19","Veget","lul")
>   names(myExplFuture)
         [1] "bio3"  "bio4"  "bio7"  "bio9"  "bio13" "bio14" "bio15" "bio18" "bio19" "Veget"
        [11] "lul"  
##Project onto future conditions
 myBiomodProjectionFuture <- BIOMOD_Projection (bm.mod = Mymodel,  ## Output of BIOMOD_Modeling
                                               proj.name = 'Futur_5045eRangeSize',
                                               new.env = myExplFuture, 
                                               models.chosen = all,
                                               metric.binary = 'TSS') 
 
-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-= 
Error in models.chosen[1] : object of type 'builtin' is not subsettable

 Best regards, 
Mulatu
--

**Comment by mula-jpg** [comment]
Dear Remi,
 I got my problem. It is  in models. chosen, i.e. "all" instead of all. How ever, the output of projection showed the following error message. Is it great problem?
-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Building clamping mask

	> Projecting myRespName_PA1_RUN1_GLM ...
	> Projecting myRespName_PA1_RUN1_GBM ...
	> Projecting myRespName_PA1_RUN1_GAM ...
	> Projecting myRespName_PA1_RUN1_CTA ...
	> Projecting myRespName_PA1_RUN1_ANN ...
                                          
	> Projecting myRespName_PA1_RUN1_MARS ...Error : variables ‘Veget’, ‘lul’ were specified with different types from the fit
Continuing anyway, first few rows of modelframe are
  bio3 bio4 bio7 bio9 bio13 bio14 bio15 bio18 bio19 Veget lul
1   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA
2   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA
3   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA
4   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA
5   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA
6   NA   NA   NA   NA    NA    NA    NA    NA    NA    NA  NA

best regards
mulatu

**Comment by mula-jpg** [comment]
Dear Remi,
Sorry for late response, Now every one is Ok. Thank you very much for your help. But: 1) I am not understand the numbers -2, -1 ,0 and 1 in the output of  plot(myBiomodRangeSize$Diff.By.Pixel);
 
![image](https://github.com/biomodhub/biomod2/assets/136796870/6a324622-1752-4be8-939a-14fd86f6d2cd)
2) I did not get data frame when I order it to write like this: write.csv(myBiomodRangeSize, file = "EM_range size.csv"), Why?

Best regards Mulatu
