### ISSUE TITLE
Question about [Multiple species ensemble modeling] - [Can someone kindly share with me generic R code for multispecies ensemble modeling? I am beginner in SDM ]

### ISSUE THREAD

**Issue by JobMOd** [biomodhub/biomod2#326]
Can someone kindly share with me generic R code for multispecies ensemble modeling? I am beginner in SDM.

**Comment by rpatin** [comment]
Dear @JobMOd,
Thank you for reporting :pray: 
If you begin with SDM, I would highly suggest that you try first a single species ensemble modeling (see the example [here](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html))  
Once you have it running, you can share the code that you used (from loading the species data to projecting the ensemble modeling), and we can help you to refactor it for multiple species (with parallel computing or not).

The multiple species component is just a matter of coding loops. The parallel computing is a bit more tricky and may depend on the machine you are running the code so it may be more difficult to help you. But first you need to have a running example for a single species, to ensure that you have a satisfying workflow. Then we will help you with the loop and the parallel computing questions.

Additionnaly, I tried to help you with your previous issue (https://github.com/biomodhub/biomod2/issues/323), but you did not update it to tell if the advice was working or if you encountered new problem with your code (that you did not fully share somehow)

Best regards,
Rémi
