### ISSUE TITLE
Help with BIOMOD_ Why is my evaluation values N/A? 

### ISSUE THREAD

**Issue by JOMahony-dot** [biomodhub/biomod2#329]
Hi!
When I'm evaluating my model and ensemble model using the get_evaluations. I'm getting  results for calibration and validation but I'm getting N/A values for evaluation. Is there something missing in the code I 'am using?

![Ensemble evaluation](https://github.com/biomodhub/biomod2/assets/61708448/fab9dc86-8b92-4e4b-a5c4-2d6f843efc56)

![Models](https://github.com/biomodhub/biomod2/assets/61708448/72d7b405-babc-4bd7-aeed-a4e042005b3a)

```
**Data formatting**
resp.name<-"Avicennia marina"
Avicennia_data<-BIOMOD_FormatingData(resp.var = rep(1,nrow(Species_data)),expl.var=ter,resp.xy=Species_data[,c('X','Y')],resp.name=resp.name,PA.nb.rep=3,PA.nb.absences=10000,PA.strategy='random',na.rm = T)
**Modeling**
mybiomodcv <- bm_CrossValidation(bm.format = Avicennia_data,
+                                      k = 5,
+                                      nb.rep = 3,
+                                      do.full.models = FALSE)

Avicennia_opt<- BIOMOD_ModelingOptions()
Avicennia_opt
Avicennia_model<-BIOMOD_Modeling(Avicennia_data,models=c("RF"),bm.options=Avicennia_opt,nb.rep =10,data.split.perc=70,data.split.table = mybiomodcv,prevalence=0.5,metric.eval= c('TSS','ROC'), var.import=3)
Avicennia_model
AviModelEval <- get_evaluations(Avicennia_model)

# Step 9 Ensemble Modeling
Avi_EM<- BIOMOD_EnsembleModeling(bm.mod  = Avicennia_model,models.chosen = 'all',em.by='PA+run',metric.eval  = c('TSS','ROC'), metric.select= c('TSS'),metric.select.thresh= c(0.7),em.algo = c('EMmedian') )
# Step 10 Projecting of Ensemble Models
AviEF<- BIOMOD_EnsembleForecasting(bm.em  = Avi_EM, bm.proj = Avi_models_proj)
plot(AviEF)
# Step 11 Evaluation of Ensemble Models
get_evaluations(Avi_EM)

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for providing code and results :pray: 

Regarding your code, everything seems normal, as you did not specify evaluation dataset within the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html). This can be done through the `eval.resp.var`, `eval.expl.var` and `eval.resp.xy` parameters.
The idea is that : 
- **calibration** / **validation** correspond to your original dataset splitted through the cross-validation process.
- **evaluation** corresponds to a dataset completely independent from the data that is used to calibrate the models

*Note also* that you can now directly call for cross-validation tools within the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function through `CV.[...]` parameters.
But you can also do it separately as you did and provide your cross-validation table through the `CV.user.table` parameter in [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) together with `CV.strategy = 'user.defined'` :sun_with_face: 

Hope it is clearer that way, and do not hesitate if you need further informations.

Maya

**Comment by JOMahony-dot** [comment]
Hi Maya,

Thanks for this information! I was just wondering what data should be added to the  eval.resp.var, eval.expl.var and eval.resp.xy parameters. Is the same data as resp.var, expl.var and resp.xy?

Cheers,
James

**Comment by MayaGueguen** [comment]
Hello James,

`eval.resp.var`, `eval.expl.var` and `eval.resp.xy` should indeed follow the same format as `resp.var`, `expl.var` and `resp.xy`.
However, these parameters are only to be used if you have a dataset completely independent from the data that is going to be used to calibrate the model, and this evaluation data will only be used to calculate evaluation metrics, but will not be included in any other parts of the modeling process (ie models will not be built using this data).
There is no need for example if you have only one dataset, to split it in 2 to give a part to the `eval.[...]` parameters, as this step could be done with the `CV.[...]` parameters of cross-validation from the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.
Cross-validation step, with calibration and validation datasets is to ensure that your models are robust and not overfitting your data. Evaluation step is a plus to ensure the extrapolation capability of your models, but it is often difficult to be able to provide such a dataset.

Hope it helps !

Maya

**Comment by JOMahony-dot** [comment]
Hi Maya,

This is great thanks for the help!

Cheers,
James
