### ISSUE TITLE
Question about ensemble spatial projection - which Cross Validation runs should be kept to build the ensemble model and subsequent most accurate spatial projection?

### ISSUE THREAD

**Issue by francescorota93** [biomodhub/biomod2#332]
**Context and question**

I need to build ensemble models for hundreds of species and with several different algorithms.

I evaluate the models by algorithm with a 5-fold with 20 repetitions random cross-validation, then I would like to build the ensemble and build projections with the BIOMOD_EnsembleForecasting function.

My approach to save computational time and power is to get the best 10 runs ranking by decreasing TSS for each algorithm, build an ensemble with BIOMOD_EnsembleModeling() and then use the ensemble model with these best 10 runs to build the spatial projection with BIOMOD_EnsembleForecasting().

I am not sure if doing so, I overfit the spatial projections and get biased output. Which solution is possible? If I keep all 100 RUN per species the building of the ensemble and the following projection will take ages since I have hundreds of species.

In detail, my main issue is about how to select the subset of models in the 'models.chosen' parameter of the function BIOMOD_EnsembleModeling() to provide the most accurate spatial projections. Is my approach of keeping the best 10 CV runs based on TSS correct? Which is the common procedure?

Any help and clarification would be great!! Thanks in advance!

Francesco

**Comment by MayaGueguen** [comment]
Hello Francesco,

The [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function provides several parameters (`metric.select[...]`) to help you such models subselection :
- with `metric.select` and `metric.select.thresh`, you base your single models selection on one evaluation metric (_which has been given to the `metric.eval` method when calling the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function_) and you specify a minimum threshold value that must be reached to allow to keep the single model into the ensemble modelling
- with `metric.select.dataset` you specify on which part of the data the evaluation metric must have been calculated to select the single models (on _calibration_, _validation_ or _evaluation_ dataset)
- if you want to use your own evaluation metric, you can set `metric.select = 'user.defined'` and provide a table through the `metric.select.table` parameter with new values to be compared to the `metric.select.thresh` value

As for your method, it sounds perfectly okay to me to keep your best 10 models out of 100 (as there is plenty of way to combine single models into ensemble, for example `EMwmean` weights them in function of their evaluation metric value).
However, I'm a bit more sceptical to the need of running 100 replicates of single models. I don't know the size of your data (number of occurrence points, and background points) but I would say that you would get the variation into your data with less repetitions. But you can give it a try for one species to see how much the evaluation metric values vary between repetitions.

Concerning the potentiality of overfitting your projections, you can compute as well the coefficient of variation (add `EMcv` to `em.algo` when running [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html)) to get an idea if there is a lot of spatial areas where single model predictions differ. And finally rely on evaluation metric values based on different datasets (either between _calibration_ / _validation_, or _evaluation_ if you have an independent dataset to test your model).

Hope it helps,
Maya
