### ISSUE TITLE
EnsembleForecasting result in smaller than input variables

### ISSUE THREAD

**Issue by LorenzoBernicchi** [biomodhub/biomod2#334]
Hello everyone,
Today I found a strange bug in my results.

I built this model for an Italian region with several rasters (like the one in the first pic) with a given extent.
Anyway, when I finished my modeling and I visualized the resulting raster in QGIS i noticed something strange. 
The borders of my study area got smaller (like 1/2 pixels got canceled all around the borders of my study area) and I have some holes in it. Interestingly, all my input rasters had the correct size and there were no holes in them.
Do you know how could I solve this issue?

Hereafter you can find the two rasters (the first is one of the input and the second one is the result: in the second one the hole in the topt left is normal, since some variables do not covered that area) and the script I used to obtain them.
Thank you in advance, all the best!

```r
BIOMOD_data <- BIOMOD_FormatingData(
  resp.name = "Jackal_single",
  resp.var = Jackal_points,
  expl.var = Variables,
  PA.nb.rep = 10, 
  PA.nb.absences = 400,
  PA.strategy = 'random', 
  na.rm = T, filter.raster = T, 
)
AllModels <- c('CTA', 'FDA', 'GAM', 'GBM', 'GLM', 'MAXENT', 'MAXNET')

user.MAXENT <- list('_allData_allRun' = list(
  path_to_maxent.jar = "."
))

user.val <- list(MAXENT.binary.MAXENT.MAXENT = user.MAXENT)
myOptions <- bm_ModelingOptions(data.type = 'binary',
                                models = AllModels,
                                strategy = 'user.defined',
                                user.val = user.val,
                                user.base = 'bigboss')

Jackal_single_models <- BIOMOD_Modeling(
  bm.format = BIOMOD_data,
  modeling.id = "Single.models",
  models = AllModels,
  CV.strategy = "random",
  CV.nb.rep = 10,
  CV.perc = 0.7,
  CV.do.full.models = F,
  bm.options = myOptions,
  metric.eval = c("ROC", "TSS"),
  var.import = 1,
  nb.cpu = 4,
  do.progress = T
)

Jackal_ensemble_models <- BIOMOD_EnsembleModeling(
  bm.mod = Jackal_single_models,
  models.chosen = "all",
  em.by = "all",
  em.algo = "EMca",
  metric.select = c("ROC"),
  metric.select.thresh = c(0.7),
  metric.eval = c("ROC", "TSS"),
  var.import = 3,
  nb.cpu = 432,
  do.progress = T
)

Jackal_Projections <- BIOMOD_Projection(
  bm.mod = Jackal_single_models,
  proj.name = "Jackal_single_proj",
  new.env = Variables,
  models.chosen = "all",
  build.clamping.mask = F,
  nb.cpu = 4,
  omit.na = T, on_0_1000 = T, do.stack = T, output.format = ".tif"
)

Jackal_ensemble_forecasting <- BIOMOD_EnsembleForecasting(
  bm.em = Jackal_ensemble_models,
  bm.proj = Jackal_Projections,
  proj.name = "Jackal_ensemble_forecasting",
  models.chosen = "all",
  nb.cpu = 4,
  na.rm = T,
  on_0_1000 = T, do.stack = T,
  output.format = ".tif"
)
``` 

![image](https://github.com/biomodhub/biomod2/assets/121942966/a3500b02-abcc-48bc-95c6-877108d9ca00)
![image](https://github.com/biomodhub/biomod2/assets/121942966/156f280a-3d86-41a6-831c-57d47d0788c6)

**Comment by MayaGueguen** [comment]
Hello Lorenzo,

It might be that in some of your variables, you have `NA` in those areas.
Could you print all the layers of your `Variables` object ?

Maya

**Comment by LorenzoBernicchi** [comment]
Yes I saw that, but there is the place in the black circle in the first photo where all variables havee at least some pixels with values, but in the resulting rasters those pixels are not present, none of them and it results in the hole. I really do not understand this issue, I knew about the predictions only where raster do not have NAs, but this seems pretty strange to me.

**Comment by MayaGueguen** [comment]
Here is a small code to obtain a mask containing only pixels where you have sufficient variables values :
```
myMask <- Variables[[1]]
myMask[] <- 1
for (i in 1:nlayers(Variables)) {
  myMask[which(is.na(Variables[[i]])] <- NA
}
plot(myMask)
```

**Comment by LorenzoBernicchi** [comment]
Thank you so much @MayaGueguen, you had been really clear and polite to answer me! I will take another look at the variables and I will try to solve this issue! 
Thank you so much :)
