### ISSUE TITLE
species range change function unable to analyse ensemble model files

### ISSUE THREAD

**Issue by sandeepB055** [biomodhub/biomod2#336]
I'm using a small dataset of presence points and an area spanning indian subcontinent for a single species. after stacking the two ensemble model output .img files for "ca" & "wm" i used the BIOMOD_RangeSize function. the error shows that my raster stack has values outside 0,1 & NA. this is true when i checked but isn't this normal while building an ensemble model or have i made a mistake in order to get such values in my model output? 

P.karavaali_data <- 
  BIOMOD_FormatingData(
    resp.var = P.karavaali['Phrynoderma.karavaali'],
    resp.xy =P.karavaali[, c('Longitude', 'Latitude')],
    expl.var = bioclim_ZA_sub_stack,
    resp.name = "Phrynoderma.karavaali",
    PA.nb.rep = 1,
    PA.nb.absences = 100,
    PA.strategy = 'random'
  )

OUTPUT
dir.name =  .

sp.name =  Phrynoderma.karavaali

	 32 presences,  0 true absences and  100 undefined points in dataset

	 6 explanatory variables

P.karavaali_models <- 
  BIOMOD_Modeling(
    bm.format = P.karavaali_data,
    models = c("GLM", "GBM", "GAM", "CTA", "ANN", "SRE", "FDA", "MARS", "RF", "MAXENT",
               "MAXNET", "XGBOOST"),
    bm.options = NULL,
    CV.nb.rep = 1,
    data.split.perc = 70,
    var.import = 1,
    modeling.id = "demo1"
  )

P.karavaali_ensemble_models <- BIOMOD_EnsembleModeling(P.karavaali_models,
                                                  em.by = 'all',
                                                  metric.select = 'TSS',
                                                  metric.select.thresh= 0.8,
                                                  em.algo = c('EMcv', 'EMca', 'EMwmean'))

OUTPUT
Projection directory : ./Phrynoderma.karavaali/ensemble_current

sp.name : Phrynoderma.karavaali

expl.var.names : wc2.1_30s_bio_1 wc2.1_30s_bio_5 wc2.1_30s_bio_12 
wc2.1_30s_bio_13 wc2.1_30s_bio_14 wc2.1_30s_bio_19

modeling.id : demo1 ( 
./Phrynoderma.karavaali/Phrynoderma.karavaali.demo1.ensemble.models.out )

models.projected : 
Phrynoderma.karavaali_EMcvByTSS_mergedData_mergedRun_mergedAlgo, Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo, Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo

available binary projection : KAPPA, TSS, ROC

P.karavaali_models_proj_current <- 
  BIOMOD_Projection(P.karavaali_models,
                    new.env = new_env_India,
                    proj.name = "current1",
                    metric.binary = 'TSS',
                    output.format = ".tif",
                    do.stack = FALSE
  )
P.karavaali_ensemble_models_proj_current <- 
  BIOMOD_EnsembleForecasting(P.karavaali_ensemble_models,
                             bm.proj = P.karavaali_models_proj_current,
                             metric.binary = 'all',
                             proj.name = "ensemble_current",
                             output.format = ".img",
                             do.stack = FALSE)

future_env_2041 <- stack(c(bio1<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_1.tif",
                                   bio5<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_5.tif",
                                   bio12<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_12.tif",
                                   bio13<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_13.tif",
                                   bio14<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_14.tif",
                                   bio19<-"D:/academics/PhD plans/climate Data/future data/MPI-ESM1-2-HR_ssp370_2021-2040/New folder/wc2.1_30s_bio_19.tif"))

P.karavaali_models_proj_2041 <- 
  BIOMOD_Projection(P.karavaali_models,
                    new.env = future_env_2041,
                    proj.name = "project single 2041",
                    metric.binary = 'TSS',
                    output.format = ".tif",
                    do.stack = FALSE
  )
OUTPUT
Projection directory : ./Phrynoderma.karavaali/project single 2041

sp.name : Phrynoderma.karavaali

expl.var.names : wc2.1_30s_bio_1 wc2.1_30s_bio_5 wc2.1_30s_bio_12 
wc2.1_30s_bio_13 wc2.1_30s_bio_14 wc2.1_30s_bio_19

modeling.id : demo1 ( 
./Phrynoderma.karavaali/Phrynoderma.karavaali.demo1.models.out )

models.projected : 
Phrynoderma.karavaali_PA1_RUN1_GLM, Phrynoderma.karavaali_PA1_RUN1_GBM, Phrynoderma.karavaali_PA1_RUN1_GAM, Phrynoderma.karavaali_PA1_RUN1_CTA, Phrynoderma.karavaali_PA1_RUN1_ANN, Phrynoderma.karavaali_PA1_RUN1_SRE, Phrynoderma.karavaali_PA1_RUN1_FDA, Phrynoderma.karavaali_PA1_RUN1_MARS, Phrynoderma.karavaali_PA1_RUN1_RF, Phrynoderma.karavaali_PA1_RUN1_MAXNET, Phrynoderma.karavaali_PA1_RUN1_XGBOOST

available binary projection : TSS

P.karavaali_ensemble_models_proj_2041 <- 
  BIOMOD_EnsembleForecasting(P.karavaali_ensemble_models,
                             bm.proj = P.karavaali_models_proj_2041,
                             metric.binary = 'all',
                             proj.name = "project ensemble_2041",
                             output.format = ".img",
                             do.stack = FALSE)

OUTPUT
Projection directory : ./Phrynoderma.karavaali/project ensemble_2041

sp.name : Phrynoderma.karavaali

expl.var.names : wc2.1_30s_bio_1 wc2.1_30s_bio_5 wc2.1_30s_bio_12 
wc2.1_30s_bio_13 wc2.1_30s_bio_14 wc2.1_30s_bio_19

modeling.id : demo1 ( 
./Phrynoderma.karavaali/Phrynoderma.karavaali.demo1.ensemble.models.out )

models.projected : 
Phrynoderma.karavaali_EMcvByTSS_mergedData_mergedRun_mergedAlgo, Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo, Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo

available binary projection : KAPPA, TSS, ROC

## load binary projections

p.karavaali_bin_project_current <- stack(c(ca="/proj_ensemble_current/individual_projections/Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo.img",  wm= "proj_ensemble_current/individual_projections/Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo.img"))

show(p.karavaali_bin_project_current)

p.karavaali_bin_project_2041 <- stack(c(ca="proj_project ensemble_2041/individual_projections/Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo.img",
                                        wm= "individual_projections/Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo.img"))

show(p.karavaali_bin_project_2041)

SRC_current_2041 <- BIOMOD_RangeSize(proj.current =  p.karavaali_bin_project_current,
                                     proj.future =  p.karavaali_bin_project_2041)

```

OUTPUT ERROR 

Each projection in 'proj.current' will be compared once with its corresponding projection in 'proj.future'. Error in .BIOMOD_RangeSize.check.args(proj.current, proj.future) : 
  'proj.current' and 'proj.future' must have only values among 0, 1 or NA.     (why is it showing this error??)

**Comment by MayaGueguen** [comment]
Hello there,

[BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function requires **binary** maps, containing either 0, 1 or NA values.

Projections obtained from [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions contain probability values, either between 0 and 1000, or 0 and 1 if you put `on_0_1000 = FALSE`.
If you put a value to the `metric.binary` parameter of one of these 2 functions, you should get binary maps from the probability maps, converted using the threshold optimising the selected evaluation metric.
These binary maps are identified with a `TSSbin` pattern (if you put `metric.binary = 'TSS'`) within the raster filenames. These are the maps you should load and give to the [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function.
If your `BIOMOD.projection.out` object is loaded into R (`P.karavaali_models_proj_2041` for example in your script), you can use it to load directly these binary maps using the [get_predictions](https://biomodhub.github.io/biomod2/reference/getters.out.html) function :
```
ras.bin.2041 = get_predictions(P.karavaali_models_proj_2041, metric.binary = "TSS")
```

Hope it helps,
Maya

**Comment by sandeepB055** [comment]
i tried what you suggested. i still got an error.

p.karavaali_bin_project_current <- stack(c(ca="D:/academics/PhD plans/SDM/P. karavaali/work_dir/Phrynoderma.karavaali/proj_ensemble_current/individual_projections/Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.img",
                                           wm= "D:/academics/PhD plans/SDM/P. karavaali/work_dir/Phrynoderma.karavaali/proj_ensemble_current/individual_projections/Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.img"))

show(p.karavaali_bin_project_current)

p.karavaali_bin_project_2041 <- stack(c(ca="D:/academics/PhD plans/SDM/P. karavaali/work_dir/Phrynoderma.karavaali/proj_project ensemble_2041/individual_projections/Phrynoderma.karavaali_EMcaByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.img",
                                        wm= "D:/academics/PhD plans/SDM/P. karavaali/work_dir/Phrynoderma.karavaali/proj_project ensemble_2041/individual_projections/Phrynoderma.karavaali_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.img"))



## SRC current -> 2041

SRC_current_2041 <- BIOMOD_RangeSize(p.karavaali_bin_project_current,p.karavaali_bin_project_2041)


ras.bin.2041 = get_predictions(P.karavaali_models_proj_2041, metric.binary = "TSS")
ras.bin.current = get_predictions(P.karavaali_ensemble_models_proj_current, metric.binary = "TSS")
  
  
SRC_current_2041 <- BIOMOD_RangeSize(ras.bin.current,ras.bin.2041)

  
  OUTPUT
Each projection in 'proj.current' will be compared once with its corresponding projection in 'proj.future'. Error in .BIOMOD_RangeSize.check.args(proj.current, proj.future) : 
  'proj.current' and 'proj.future' must have only values among 0, 1 or NA.
> ras.bin.2041 = get_predictions(P.karavaali_models_proj_2041, metric.binary = "TSS")
> ras.bin.current = get_predictions(P.karavaali_ensemble_models_proj_current, metric.binary = "TSS")
Warning messages:
1: Too large for int: nan (GDAL error 1) 
2: Too large for int: nan (GDAL error 1) 
> SRC_current_2041 <- BIOMOD_RangeSize(ras.bin.current,ras.bin.2041)

-=-=-=-=-=-=-=-=-=-=-=-= Do Range Size Computation -=-=-=-=-=-=-=-=-=-=-=-=
Error in .BIOMOD_RangeSize.check.args(proj.current, proj.future) : 
  When proj.current' have more than 1 projection, 'proj.future' must have the same number of projection.

**Comment by sandeepB055** [comment]
thank you so much. the above info helped. 

i am currently plotting the src$diff by pixel and the "wmean" file is returing infinity values. the map is blank however the "ca" is visualised perfectly

code used

p.karavaali_src_map <- SRC_current_2041$Diff.By.Pixel

names(p.karavaali_src_map)<-c("current_2041_ca","current_2041_wm")
p.karavaali_src_map
my.at <- seq(-2.5, 1.5, 1)


myColorkey <- 
  list(
    at = my.at, ## where the colors change
    labels = 
      list(
        labels = c("lost", "pres", "abs","gain"), ## labels
        at = my.at[-1] - 0.5 ## where to print labels
        ))



rasterVis::levelplot( 
  p.karavaali_src_map, 
  main = "P karavaali range change",
  colorkey = myColorkey,
  col.regions=c('#f03b20', '#99d8c9', '#f0f0f0', '#2ca25f'),
  layout = c(2,2)
)


OUTPUT

> p.karavaali_src_map
class       : SpatRaster 
dimensions  : 2520, 4200, 2  (nrow, ncol, nlyr)
resolution  : 0.008333333, 0.008333333  (x, y)
extent      : 65, 100, 4, 25  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source(s)   : memory
names       : current_2041_ca, current_2041_wm 
min values  :              -2,             NaN 
max values  :               1,             NaN 
> my.at <- seq(-2.5, 1.5, 1)
> myColorkey <- 
+   list(
+     at = my.at, ## where the colors change
+     labels = 
+       list(
+         labels = c("lost", "pres", "abs","gain"), ## labels
+         at = my.at[-1] - 0.5 ## where to print labels
+         ))
> rasterVis::levelplot( 
+   p.karavaali_src_map, 
+   main = "P karavaali range change",
+   colorkey = myColorkey,
+   col.regions=c('#f03b20', '#99d8c9', '#f0f0f0', '#2ca25f'),
+   layout = c(2,2)
+ )
Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
![3b9952ca-868c-429b-a50d-00962a169b03](https://github.com/biomodhub/biomod2/assets/122000479/36042dae-5c59-42e4-9b38-ea9237fc1bc9)

**Comment by MayaGueguen** [comment]
I'm glad that it helped !

What is returning the `SRC_current_2041$Compt.By.Species` object ?

**Comment by sandeepB055** [comment]
@MayaGueguen  i am not having that option currently. no idea why.

**Comment by MayaGueguen** [comment]
This is coherent with the fact that you don't see anything when trying to plot the `wmean` range size comparison, as it seems you do not have any values into your `SRC_current_2041$Compt.By.Species` second line.
Try and check the 2 binary maps you gave to the [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function for the `wmean` scenario.

**Comment by MayaGueguen** [comment]
It seems indeed that you are giving the paths to the write files...
What do you get if doing for example : 
```
unique(p.karavaali_bin_project_current[[1]][])
```
?
