### ISSUE TITLE
Help with BIOMOD_xxx - [changing model settings]

### ISSUE THREAD

**Issue by hillary5** [biomodhub/biomod2#340]
Dear biomod Team,

I am trying to change model settings but BIOMOD_ModelingOptions does not exists anymore. In the past versions I used the code below.

I have looked the help and I think, but not sure, the new way is using the function bm_ModelingOptions, however I just don’t know how to do it. 

I tried creating a list with the settings for each model and passing this list as user.val to bm_ModelingOptions but it does not work. 

Can you give me further information on how to do it?

Cheers,

Hillary.

**Code used**
myBiomodOptions <- BIOMOD_ModelingOptions(
  
  GLM = list( type = 'simple',
              interaction.level = 0,
              myFormula = NULL,
              test = 'BIC',
              family = 'binomial',
              mustart = 0.5,
              control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE) ),
  
  
  MAXENT = list( maximumiterations = 500,
                 visible = FALSE,
                 linear = TRUE,
                 quadratic = TRUE,
                 product = FALSE,
                 threshold = FALSE,
                 hinge = FALSE,
                 lq2lqptthreshold = 80,
                 l2lqthreshold = 10,
                 hingethreshold = 15,
                 beta_threshold = -1,
                 beta_categorical = -1,
                 beta_lqp = -1,
                 beta_hinge = -1,
                 defaultprevalence = 0.5,
                 threads=1),
  
)

**Comment by MayaGueguen** [comment]
Hello Hillary,

Thank you for your patience and trying the new version :pray: 
Could you also share with me the code you try to configure the modeling options with the new version ?
I'll be of better help that way :)

Maya

**Comment by hillary5** [comment]
Dear Maya,



Thank you for your reply. Please find the code I used below.



Cheers,



Hillary 







# Load species occurrences (6 species available)

data(DataSpecies)





# Select the name of the studied species

myRespName <- 'GuloGulo'



# Get corresponding presence/absence data

myResp <- as.numeric(DataSpecies[, myRespName])



# Get corresponding XY coordinates

myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]



# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)

data(bioclim_current)

myExpl <- terra::rast(bioclim_current)







# ---------------------------------------------------------------------------- #

# Format Data with true absences

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,

                                     expl.var = myExpl,

                                     resp.xy = myRespXY,

                                     [resp.name](http://resp.name/) = myRespName)







options <- list(c(



GLM = list( type = 'simple',

interaction.level = 0,

myFormula = NULL,

test = 'BIC',

family = 'binomial',

mustart = 0.5,

control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE) ),



MAXENT = list( maximumiterations = 500,

visible = FALSE,

linear = TRUE,

quadratic = TRUE,

product = FALSE,

threshold = FALSE,

hinge = FALSE,

lq2lqptthreshold = 80,

l2lqthreshold = 10,

hingethreshold = 15,

beta_threshold = -1,

beta_categorical = -1,

beta_lqp = -1,

beta_hinge = -1,

defaultprevalence = 0.5,

threads=1)





)



opt.u <- bm_ModelingOptions(data.type = 'binary',

                            models = c('GLM', 'MAXNET'),

                            strategy = "default",

                            user.val = options,

                            bm.format= myBiomodData)







#check model settings shows nothing is changed

opt.u





# ---------------------------------------------------------------------------- #

# Model single models

myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,

							   OPT.user = opt.u,

                                    [modeling.id](http://modeling.id/) = 'AllModels',

                                    models = c('GLM', 'MAXNET'),

                                    CV.strategy = 'random',

                                    CV.nb.rep = 2,

                                    CV.perc = 0.8,

                                    OPT.strategy = 'bigboss',

                                    metric.eval = c('TSS','ROC'),

                                    var.import = 2,

                                    seed.val = 42)

**Comment by MayaGueguen** [comment]
Thank you Hillary :pray: 

_Please note that version 4.2-5 now retrieve directly parameters from functions in related packages, except for MAXENT._
For example, for GLM, you can check `?stats::glm` to see which parameters are required by the function.
All model packages included in `biomod2` can be found in `data("ModelsTable")`.
Formula can be either given directly as a formula object, created through the [bm_MakeFormula](https://biomodhub.github.io/biomod2/reference/bm_MakeFormula.html) function, or created automatically by `biomod2`.

:warning: Default options are really not changed from default functions configuration.
We provide a set of modified options a bit more adapted to modelling through the `bigboss` setup, and values can be checked through `data("OptionsBigboss")`.


Below, I specified only options values that were different from the `bigboss` set : 

```
## Define GLM options changing compared to OptionsBigboss
form.GLM <- bm_MakeFormula(resp.name = myBiomodData@sp.name
                           , expl.var = head(myBiomodData@data.env.var)
                           , type = 'simple'
                           , interaction.level = 0)
user.GLM <- list('_allData_allRun' = list(formula = form.GLM))

## Define MAXENT options changing compared to OptionsBigboss
user.MAXENT <- list('_allData_allRun' = list(path_to_maxent.jar = getwd()
                                             , product = FALSE
                                             , threshold = FALSE
                                             , hinge = FALSE))

## Gather in one list
## Models names can be found in OptionsBigboss@models
user.val <- list(GLM.binary.stats.glm = user.GLM
                 , MAXENT.binary.MAXENT.MAXENT = user.MAXENT)
```

You have 2 ways of building your options then : 
- the first one through the [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) function (check [secundary functions examples](https://biomodhub.github.io/biomod2/articles/examples_2_secundaryFunctions.html) on documentation website).

```
opt.u <- bm_ModelingOptions(data.type = 'binary',
                            models = c('GLM', 'MAXENT'),
                            strategy = "user.defined",
                            user.val = user.val,
                            user.base = "bigboss",
                            bm.format = myBiomodData)
opt.u

myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                modeling.id = 'AllModels',
                                models = c('GLM', 'MAXENT'),
                                CV.strategy = 'random',
                                CV.nb.rep = 2,
                                CV.perc = 0.8,
				OPT.user = opt.u,
                                metric.eval = c('TSS','ROC'),
                                var.import = 2,
                                seed.val = 42)
```

- and the second one directly through the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function (check [main examples](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html)),

```
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                modeling.id = 'AllModels',
                                models = c('GLM', 'MAXENT'),
                                CV.strategy = 'random',
                                CV.nb.rep = 2,
                                CV.perc = 0.8,
                                OPT.data.type = 'binary',
                                OPT.strategy = "user.defined",
                                OPT.user.val = user.val,
                                OPT.user.base = "bigboss",
                                metric.eval = c('TSS','ROC'),
                                var.import = 2,
                                seed.val = 42)
```

Hope it helps,
Maya
