### ISSUE TITLE
Error in BIOMOD_plot(myBiomodData) - [Error in nchar(dcall, type = "w") : invalid multibyte string, element 1]

### ISSUE THREAD

**Issue by liushuhao-666** [biomodhub/biomod2#342]
Dear all,

Please help me.

> plot(myBiomodData)
$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 2488, 2  (geometries, attributes)
 extent      : -178.5, 178.5, -55.99999, 82.00001  (xmin, xmax, ymin, ymax)
Error in nchar(dcall, type = "w") : invalid multibyte string, element 1

This code has error.

**Comment by MayaGueguen** [comment]
Hello there,

I will need a bit more information to be able to help you.
Could you share with me please : 
- the code you used to produce your `myBiomodData` object
- the output of the command `show(myBiomodData)`
- the output of the command `sessionInfo()`

Thanks in advance,
Maya
