### ISSUE TITLE
Help with bm_PlotResponseCurves - [Change axis scale]

### ISSUE THREAD

**Issue by Friepei** [biomodhub/biomod2#346]
Hello,

I am trying to change my response curves' Minimum and Maximum of the x- and y- axis to compare the results of two species.

I am using the bm_PlotResponseCurves() as function to plot the response curves.

bm_PlotResponseCurves(bm.out = myBiomodEM, 
                      show.variables = c("Temperature"),
                      models.chosen = get_built_models(myBiomodEM)[c(1)],
                      fixed.var = 'median',
                      do.plot = FALSE,
                      do.progress = TRUE,
                     ) 

I tried tp change the axis by adding xlim() and ylim()  and range(), but nothing worked. 

Is it possible to change the axis?

Cheeers

**Comment by MayaGueguen** [comment]
Hello there,

Could you share the code you used to try and change x and y axis please ?
Also, note that each `bm_Plot[...]` function returns a `list` containing two objects : 
1. the table built to create the graphic
2. the `ggplot2` object rendered
You can then start from this `ggplot2` object and add new `ggplot2` commands or specifications. For example : 
```
myPlot <- bm_PlotResponseCurves(bm.out = myBiomodEM,
                                show.variables = c("Temperature"),
                                models.chosen = get_built_models(myBiomodEM)[c(1)],
                                fixed.var = 'median',
                                do.plot = FALSE,
                                do.progress = TRUE,
)

myPlot$plot + xlim(0, 100)
```

Maya

**Comment by Friepei** [comment]
Thank you, that worked!

My problem was that I inserted the commands inside the bm_ResponseCurves function
