### ISSUE TITLE
biomod not returning individual projections, TSS & AUC values

### ISSUE THREAD

**Issue by tobioke** [biomodhub/biomod2#347]
Hi there,

I just updated my biomod2 and I noticed there have been several changes. I was able to use the 2023 `Biomod2` manual to get my codes up to date.  I was doing multi-species modeling for current and future. My code ran to completion after the editing. The issue was the process did not write `individual projections`; the folder was empty. Perhaps I needed to turn on the feature that does this, but the manual made no reference to such. 

Also, the model evaluation did not return values for `TSS` and `ROC` for `individual run` and `mergedalgo`, which are my evaluation metrics. 

Given these issues, I thought the CRAN version might be the problem and decided to install the github version using `devtools::install_github('biomodhub/biomod2')`.  This started to throw an error that did not appear on the CRAN version. There's also an additional error that suggests that the `biomod2.rdb` file is corrupt. I have deleted and reinstalled the github version a couple of times but the errors persist.  I have now reverted to the CRAN version and the errors have disappeared. I thought you should be aware of this. 

> Error in BIOMOD_ModelingOptions() : 
  could not find function "BIOMOD_ModelingOptions"

> Error in fetch(key) : 
  lazy-load database 'C:/Users/.../AppData/Local/R/win-library/4.3/biomod2/help/biomod2.rdb' is corrupt

Below is the code that I'm working with. Any help would be appreciated.  

MyBiomodSF <- function(sp.names){
  
  myRespName = sp.names
  
  cat('\n',myRespName,'modeling...')  

myResp <- as.numeric(unlist(mammal_data[,myRespName]))
  
  
  myRespCoord = mammal_data[,c('Longitude','Latitude')]
  
  
  ### Initialisation
  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = ExplCur,
                                       resp.xy = myRespCoord,
                                        resp.name = myRespName,
                                       PA.nb.rep = 1,
                                       PA.nb.absences = 200,
                                       PA.strategy = 'random')

  
  myBiomodOption <- BIOMOD_ModelingOptions()
  
  
  ### Modelling 
  myBiomodModelOut <- BIOMOD_Modeling( 
    bm.format = myBiomodData, 
    models = c('RF','GBM'), 
    #models = c("MAXENT.Phillips"), 
    bm.options = myBiomodOption, 
    CV.strategy = 'kfold',
    CV.nb.rep = 2, 
    CV.k = 2, 
    prevalence = 0.5, 
    var.import = 3,
    metric.eval = c('TSS','ROC'),
    #SaveObj = TRUE,
    scale.models = FALSE,
    CV.do.full.models = TRUE,
    modeling.id = paste(myRespName,"BIOMOD", sep = ""))
  
  ### save models evaluation scores and variables importance on hard drive
  capture.output(get_evaluations(myBiomodModelOut),
                 file=file.path(myRespName, 
                                paste(myRespName,"_formal_models_evaluation.csv", sep="")))
  
  capture.output(get_variables_importance(myBiomodModelOut),
                 file=file.path(myRespName, 
                                paste(myRespName,"_formal_models_variables_importance.csv", sep="")))   
  
  
  
  ### Building ensemble-models
  myBiomodEM <- BIOMOD_EnsembleModeling( 
    bm.mod = myBiomodModelOut,
    models.chosen = 'all', 
    em.by='all',
    metric.select = c('TSS', 'ROC'),
    metric.select.thresh = c(0.5, 0.7),
    em.algo = c('EMmedian', 'EMwmean', 'EMcv', 'EMca'),
    var.import = 3)
  
  
  ### save models evaluation scores and variables for ensemble importance on hard drive
  capture.output(get_evaluations(myBiomodEM),
                 file=file.path(myRespName, 
                                paste(myRespName,"_formal_models_evaluation_EM.csv", sep="")))
  
  capture.output(get_variables_importance(myBiomodEM),
                 file=file.path(myRespName, 
                                paste(myRespName,"_formal_models_variables_importance_EM.csv", sep="")))   
  
  
  ### Make projections on current variable
  myBiomodProj <- BIOMOD_Projection(
    bm.mod = myBiomodModelOut,
    new.env = ExplCur,
    proj.name = 'current',
    models.chosen = 'all',
    metric.binary = 'all',
    compress = 'xz',
    build.clamping.mask = F,
    output.format = '.img')
  
  
  ### Make ensemble-models projections on current variable
  myBiomodEF <- BIOMOD_EnsembleForecasting( 
    bm.em = myBiomodEM,
    bm.proj = myBiomodProj,
    metric.binary = 'all',
    metric.filter = 'all',
    output.format = '.img')
  

  ####Projection on future environmental conditions 2021-2040 CMRN
  myBiomodProjectionFuture40_CN <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                                     new.env = ExplFuture40_CN,
                                                     proj.name = 'future40_CN',
                                                     models.chosen = 'all',
                                                     metric.binary = 'all',
                                                     compress = FALSE,
                                                     build.clamping.mask = TRUE,
                                                     output.format = '.img')

  ### Make ensemble-models projections on future variable 2021-2040 CMRN
  myBiomodEF40_CN <- BIOMOD_EnsembleForecasting(
    bm.em = myBiomodEM,
    bm.proj = myBiomodProjectionFuture40_CN,
    metric.binary = 'all',
    output.format = '.img')
}

**Comment by MayaGueguen** [comment]
Hello there,

Individual projections are not anymore produced by default.
All projections are stored within a single file contained within your projection folder, unless you set `do.stack = FALSE` when calling [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions.

Last version on github (4.2-5) has several changes, most of them impacting the definition of modeling options.
`BIOMOD_ModelingOptions` function has been replaced by [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) which is called directly from [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function through `OPT.[...]` parameters.
Examples on how to use this new configuration can be found [main](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) and [secundary](https://biomodhub.github.io/biomod2/articles/examples_2_secundaryFunctions.html) functions example pages.
More details on the version changes are also available on the [News](https://biomodhub.github.io/biomod2/articles/news.html) page.

Hope it helps,
Maya

**Comment by tobioke** [comment]
Hi Maya,

Thank you for getting back to me and directing me to those examples. 

I was wondering if you could help clarify a few things regarding the outputs in the projection folder because it's not clear what those are: 

(1) if I plot `_ensemble.img` for instance, I get several files suffixed by` _mergedAlgo.1, _mergedAlgo.2`, .etc. But it's not clear how these individual layers were generated because some of them look different from the rest, both in terms of the pattern of prediction and data range. See the attached figure. The left and right don't seem they belong in the same model. More so, I was expecting a consensus file, at least given the notion of an ensemble. So, which one is the ensemble of all the models or how could one generate it? 

(2) As you will notice from my code, in the `em.algo`, I indicated `c('EMmedian', 'EMwmean', 'EMcv', 'EMca')` and consistently selected `all` for `models.chosen` and `metric.binary`. But only `EMmedian` was used for map outputs and all the outputs were `byTSS` even where the file indicated `ROC` (e.g., `_ensemble_ROCbin.img`). So, do you know why `biomod2` would ignore these other settings and why it would mislabel files?

(3) The` calibration/validation` component of the evaluation output is new (at least to me). Are these the same conceptually as the `training/testing` and do the values represent those of the corresponding evaluation metrics such as `TSS/ROC`?

(4) In the earlier version, I was able to use conditional statements or simple equations to set `pseudoabsences` based on the understanding of my species data, the choice of algorithms and also to manage computing time. For example,  `PA.nb.absences = 30*sum(myResp==1)`.  This seems no longer possible in the current version. Is there a way around it?

(5) This is more of a data management issue. When I exported the `get_evaluations` component to a `.csv` file, some of the columns were stacked below the preceding columns. In the past, I managed this through a combination of inelegant coding and manual manipulation. It was tedious but worked. Now, my old approach is not working due to the changes. I was wondering if you have a way to easily export the columns (multiple files) as continuous columns (left to right) in `R`. I'm doing multi-species modelling. 

Hope to hear from you.

Tobi


![image](https://github.com/biomodhub/biomod2/assets/82488680/9736e5c1-b0bb-4c6f-9d96-0e64ba6fcbe2)

**Comment by MayaGueguen** [comment]
Hello Tobi,

I'll try to give you as inputs as possible regarding your questions :eyes: 
Maybe it would be easier also if you could send a screenshot of your folder, or the list of file names contained in it.

1. By default, in [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions, all predictions are saved within one single file. To have one file per projection, you must set `do.stack = FALSE`.

2. Here, it would help to see what files you get in your modeling folder. First, you can try running `get_built_models(myBiomodEM)` to see which models effectively worked or not.
The `metric.select` and `metric.select.thresh` arguments in the [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function are here to filter single models and keep only the one matching the evaluation metric minimal threshold to build the ensemble models. If GBM is never selected, it must be because all evaluation values for GBM single models are below your defined ` metric.select.thresh`.
Did you also check the warnings and messages when running the function ? Maybe something was said concerning the fact that only `EMmedian` worked ?

3. When calling the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, you ask for your dataset to be divided into cross-validation datasets according to the k-fold method with k = 2 and 2 repetitions. For each run, `calibration` data is the data used to calibrate the model, the rest is considered as `validation`, and evaluation metrics are calculated for both these datasets.
So yes, it is the same as having a `training` and a `testing` dataset.

4. I don't get why this is not possible, or maybe I don't understand exactly what you want to do...

5. Not sure here from which data you start and to where you want to go. More precisions would help. If it is because you have one `.csv` file per species containing the result of the [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html) function, then you can easily do something like : 
```
## myEvalFiles : vector containing the path to your evaluation files

library(foreach)
library(data.table)

allEval = foreach(fi = myEvalFiles, .combine = rbind) %do%
{
   fread(fi, data.table = FALSE)
}
```

Maya

**Comment by tobioke** [comment]
Hi Maya,

Thanks again for your response. I'm familiar with those primary functions and settings and what they do.

I didn't get any messages regarding what method of generating an ensemble worked or didn't work as I ran the models in parallel. At the same time, if indeed other methods of compiling ensemble failed, `biomod2` should at the very least return `EMca` for `EMmedian` as it is a measure of uncertainty and not a probability. 

As for your request for the contents of the folder, please see the attached screenshot.

Regarding item 4, this is the error message that I got when I tried to use the mentioned equation to set pseudoabsences and the only action that removed the error message was to supply a value.  A new option in `biomod2` is the `user-defined` setting. But the equation did not work with that option either and I read from the manual that one has to submit a table for the `user-defined` option, which was different from just passing the equation. 

```
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = ExplCur,
                                       resp.xy = myRespCoord,
                                       resp.name = myRespName,
                                       PA.nb.rep = 1,
                                       PA.nb.absences = 30*sum(myResp==1),
                                       PA.strategy = 'random')
```

> Error in if ((nb.rep == 0 || any(nb.absences <= 0)) & strategy != "user.defined") { : 
>   missing value where TRUE/FALSE needed

As to item 5, the code did not solve the problem and produced the same result as my other attempts. For context, I'm attaching one of the `.csv` files from `get_evaluations` outputs. As you will see, the columns are stacked instead of appearing as a set of laterally progressing columns like in a normal spreadsheet and `R` doesn't seem to know how to deal with this (don't read anything into the values on the spreadsheet as I'm just running a test model to see that my codes are in order).  So, instead of stacked columns, I'm hoping to obtain something of this nature when I load the files into `R` 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xtobi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xtobi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



full.name.merged.by.PA | Merged.by.run | Merged.by.algo | filtered.by | algo | …. | evaluation
-- | -- | -- | -- | -- | -- | --




</body>

</html>


Or in the case of the individual runs

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xtobi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xtobi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



PA | run | algo | metric.eval | cutoff | sensitivity | specificity | calibration | validation | evaluation
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
PA1 | RUN1 | RF | TSS | 960 | 98.886 | 64.211 | 0.631 | 0.599 | NA
PA1 | RUN1 | RF | ROC | 953 | 98.972 | 64.211 | 0.823 | 0.83 | NA
PA1 | RUN1 | GBM | TSS | 597 | 79.623 | 90.526 | 0.711 | 0.58 | NA



</body>

</html>




![image](https://github.com/biomodhub/biomod2/assets/82488680/3f0876bc-95f2-4d65-962e-588d49f2a60d)


[Alces.alces_formal_models_evaluation_EM.csv](https://github.com/biomodhub/biomod2/files/13044830/Alces.alces_formal_models_evaluation_EM.csv)

Thanks for looking into it.

**Comment by MayaGueguen** [comment]
Hello Tobi,

Thank you for the additional informations :pray: 

I'm not sure everything is still clear on my side.
Could you share the output of the following commands please ?
```
head(myResp)
table(myResp)
30*sum(myResp==1)
show(myBiomodData)
get_built_models(myBiomodEM)
get_evaluations(myBiomodEM)
```

Maya

**Comment by tobioke** [comment]
Hi Maya,

I decided to re-run the model using `lapply` so that I could get the contents of those objects you requested and possibly catch any error or warning messages. The model did not return both `myBiomoData` and `myBiomoEM` and I have run the model a couple of times. I'm sure the objects were generated, otherwise, it would have been impossible to create the ensemble outputs. Is there a way to force `biomod2` to return those two objects?

Regarding passing an equation to `PA.nb.absences`, I noticed a mistake in my initial code where I used `myResp <- as.numeric(unlist(mammal_data[,myRespName]))` instead of `myResp <- as.numeric(mammal_data[,myRespName])`. I had `unlist` the data as a solution to an initial error, which now triggers a different error when I try to pass the equation. The equation now works as before. So, that part is considered resolved. 

Thanks for your time.

Tobi

**Comment by MayaGueguen** [comment]
Hello Tobi,

Thank you for the update :pray:

Glad that the number of pseudo-absences problem was solved.

As for getting and showing your `myBiomodData` and `myBiomodEM` object, you can load them directly from your simulation folders. In each species folder, you should have files such as `[...].models.out` and `[...].ensemble.models.out`. You just need to `load` them into your R session, but keep in mind that they will not be named `myBiomodModelOut` and `myBiomodEM` but rather the name of the file. Once you have them, you can retrieve formated data using the [get_formal_data](https://biomodhub.github.io/biomod2/reference/getters.out.html) function.

Maya

**Comment by tobioke** [comment]
Hi Maya,

Funny enough I had loaded and examined the formatted data and the contents of `...models.out`  but didn't know they were what you were looking for as I was looking for those precise objects. See below for the formatted data.




```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-

dir.name =  .

sp.name =  Alces.alces

	 14007 presences,  0 true absences and  143807 undefined points in dataset


	 6 explanatory variables

      bio1             bio12              bio9            bio10           bio14             bio17        
 Min.   :-25.175   Min.   :  59.36   Min.   :-39.69   Min.   :-4.64   Min.   :  0.000   Min.   :   3.93  
 1st Qu.:-11.410   1st Qu.: 238.50   1st Qu.:-29.24   1st Qu.: 7.89   1st Qu.:  8.314   1st Qu.:  28.17  
 Median : -8.591   Median : 273.25   Median :-21.30   Median :10.04   Median : 10.944   Median :  35.98  
 Mean   : -8.004   Mean   : 330.51   Mean   :-20.72   Mean   :10.15   Mean   : 13.049   Mean   :  43.64  
 3rd Qu.: -4.031   3rd Qu.: 334.84   3rd Qu.:-14.11   3rd Qu.:13.90   3rd Qu.: 14.946   3rd Qu.:  48.17  
 Max.   :  4.735   Max.   :7088.44   Max.   : 10.02   Max.   :17.57   Max.   :347.157   Max.   :1189.34  


 1 Pseudo Absences dataset available ( PA1 ) with  67625 (PA1) pseudo absences


```

I found a solution to the data exporting issue. It turns out that the `capture.output` function that I was using to export both `myBiomodEM` and `myBiomodModelOut` writes out data as `strings`, leading to stacked columns. To get a numerical `data.frame`, I used `write.table` instead, which solved the problem. 

The question that I have at this point is whether it is by design that `get_evaluations(myBiomodEM)` returns NA for `validation` (see attached spreadsheet). This was not the case for the individual models.

[Alces.alces_formal_models_evaluation_EM.csv](https://github.com/biomodhub/biomod2/files/13171269/Alces.alces_formal_models_evaluation_EM.csv)

**Comment by MayaGueguen** [comment]
Hello Tobi,

Glad to hear that your evaluation table now looks correct.
As for the `NA` in the `validation` column, it is normal for ensemble models as you asked to merge all runs together, so you do not have anymore your data cut into calibration and validation parts, as they do not match between runs.

Maya

**Comment by tobioke** [comment]
You have been very helpful, Maya.

Thanks,

Tobi
