### ISSUE TITLE
The "std::bad_alloc" error when using BIOMOD_RangeSize 

### ISSUE THREAD

**Issue by xiadawei123** [biomodhub/biomod2#349]
Hello！

After completing the predictions for the current single model and the future single model using the provided code, I encountered the following error when attempting to compare them using `BIOMOD_RangeSize`. Can you provide me with some assistance? Thank you.

myBiomodProj <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name = "Current", 
  new.env = bioclim_sub,  
  models.chosen = "all", 
  metric.binary = "all",  
  metric.filter = "all",
  build.clamping.mask = TRUE,
  output.format = ".tif",
  do.stack = FALSE
)

myBiomodProjectionFuture <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name = "Future_ssp126_2081_2100",
  new.env = ssp126_2081_2100_bioclim_sub,
  models.chosen = "all",
  metric.binary = "TSS",
  build.clamping.mask = TRUE,
  output.format = ".tif"
)

CurrentProj <- get_predictions(myBiomodProj, metric.binary = "TSS")
FutureProj <- get_predictions(myBiomodProjectionFuture, metric.binary = "TSS")

######above is ok

myBiomodRangeSize <- BIOMOD_RangeSize(
  proj.current = CurrentProj,
  proj.future = FutureProj
)

-=-=-=-=-=-=-=-=-=-=-=-= Do Range Size Computation -=-=-=-=-=-=-=-=-=-=-=-=

 Each projection in 'proj.current' will be compared once with its corresponding projection in 'proj.future'. Error: std::bad_alloc

**Comment by MayaGueguen** [comment]
Hello there,

Could you try setting the `model.as.col` option to `TRUE` within the [get_predictions](https://biomodhub.github.io/biomod2/reference/getters.out.html) function please ?

```
CurrentProj <- get_predictions(myBiomodProj, 
                               metric.binary = "TSS",
                               model.as.col = TRUE)
FutureProj <- get_predictions(myBiomodProjectionFuture, 
                              metric.binary = "TSS",
                              model.as.col = TRUE)

myBiomodRangeSize <- BIOMOD_RangeSize(
            proj.current = CurrentProj,
            proj.future = FutureProj
)
```

Maya

**Comment by xiadawei123** [comment]
> Hello there,
> 
> Could you try setting the `model.as.col` option to `TRUE` within the [get_predictions](https://biomodhub.github.io/biomod2/reference/getters.out.html) function please ?
> 
> ```
> CurrentProj <- get_predictions(myBiomodProj, 
>                                metric.binary = "TSS",
>                                model.as.col = TRUE)
> FutureProj <- get_predictions(myBiomodProjectionFuture, 
>                               metric.binary = "TSS",
>                               model.as.col = TRUE)
> 
> myBiomodRangeSize <- BIOMOD_RangeSize(
>             proj.current = CurrentProj,
>             proj.future = FutureProj
> )
> ```
> 
> Maya

After I added model.as.col = TRUE, the error of "Each projection in 'proj.current' will be compared once with its corresponding projection in 'proj.future'. Error: std::bad_alloc" still existed. I will try again, and if you have any other suggestions, please feel free to let me know. Thank you again

**Comment by xiadawei123** [comment]
> It might also be because your computer memory is not sufficient. How much are your maps big in terms of pixels ? And how many projections do you have ?
> 
> ```
> head(CurrentProj)
> str(CurrentProj)
> 
> head(FutureProj)
> str(FutureProj)
> ```
> 
> Maya

Hi Maya
as follow：

> head(myBiomodProj)
Error in x[seq_len(n)] : object of type 'S4' is not subsettable
> str(myBiomodProj)
Formal class 'BIOMOD.projection.out' [package "biomod2"] with 11 slots
  ..@ modeling.id     : chr "AllModels"
  ..@ proj.name       : chr "Current"
  ..@ dir.name        : chr "."
  ..@ sp.name         : chr "Bins"
  ..@ expl.var.names  : chr [1:7] "bio1" "bio2" "bio3" "bio7" ...
  ..@ coord           :'data.frame':	0 obs. of  0 variables
  ..@ scale.models    : logi FALSE
  ..@ models.projected: chr [1:105] "Bins_PA1_RUN1_GLM" "Bins_PA1_RUN1_GBM" "Bins_PA1_RUN1_GAM" "Bins_PA1_RUN1_CTA" ...
  ..@ models.out      :Formal class 'BIOMOD.stored.data' [package "biomod2"] with 2 slots
  .. .. ..@ inMemory: logi FALSE
  .. .. ..@ link    : chr "./Bins/Bins.AllModels.models.out"
  ..@ type            : chr "SpatRaster"
  ..@ proj.out        :Formal class 'BIOMOD.stored.SpatRaster' [package "biomod2"] with 3 slots
  .. .. ..@ val     :Formal class 'PackedSpatRaster' [package "terra"] with 3 slots
  .. .. .. .. ..@ definition: chr "rast(ncols=360, nrows=180, nlyrs=1, xmin=-180, xmax=180, ymin=-90, ymax=90, names=c('lyr.1'), crs='GEOGCRS[\"WG"| __truncated__
  .. .. .. .. ..@ values    : num [1:64800, 1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  .. .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. .. ..$ : NULL
  .. .. .. .. .. .. ..$ : chr "lyr.1"
  .. .. .. .. ..@ attributes: list()
  .. .. ..@ inMemory: logi FALSE
  .. .. ..@ link    : chr [1:735] "./Bins/proj_Current/individual_projections/proj_Current_Bins_PA1_RUN1_GLM.tif" "./Bins/proj_Current/individual_projections/proj_Current_Bins_PA1_RUN1_GBM.tif" "./Bins/proj_Current/individual_projections/proj_Current_Bins_PA1_RUN1_GAM.tif" "./Bins/proj_Current/individual_projections/proj_Current_Bins_PA1_RUN1_CTA.tif" ...
> head(myBiomodProjectionFuture)
Error in x[seq_len(n)] : object of type 'S4' is not subsettable
> str(myBiomodProjectionFuture)
Formal class 'BIOMOD.projection.out' [package "biomod2"] with 11 slots
  ..@ modeling.id     : chr "AllModels"
  ..@ proj.name       : chr "Future_ssp126_2081_2100"
  ..@ dir.name        : chr "."
  ..@ sp.name         : chr "Bins"
  ..@ expl.var.names  : chr [1:7] "bio1" "bio2" "bio3" "bio7" ...
  ..@ coord           :'data.frame':	0 obs. of  0 variables
  ..@ scale.models    : logi FALSE
  ..@ models.projected: chr [1:105] "Bins_PA1_RUN1_GLM" "Bins_PA1_RUN1_GBM" "Bins_PA1_RUN1_GAM" "Bins_PA1_RUN1_CTA" ...
  ..@ models.out      :Formal class 'BIOMOD.stored.data' [package "biomod2"] with 2 slots
  .. .. ..@ inMemory: logi FALSE
  .. .. ..@ link    : chr "./Bins/Bins.AllModels.models.out"
  ..@ type            : chr "SpatRaster"
  ..@ proj.out        :Formal class 'BIOMOD.stored.SpatRaster' [package "biomod2"] with 3 slots
  .. .. ..@ val     :Formal class 'PackedSpatRaster' [package "terra"] with 3 slots
  .. .. .. .. ..@ definition: chr "rast(ncols=11135, nrows=5403, nlyrs=105, xmin=68.8666666666667, xmax=161.658333333333, ymin=-15.0750000000001, "| __truncated__
  .. .. .. .. ..@ values    : num[0 , 0 ] 
  .. .. .. .. ..@ attributes:List of 1
  .. .. .. .. .. ..$ sources:'data.frame':	105 obs. of  4 variables:
  .. .. .. .. .. .. ..$ sid   : int [1:105] 1 2 3 4 5 6 7 8 9 10 ...
  .. .. .. .. .. .. ..$ source: chr [1:105] "C:/Users/11912/AppData/Local/Temp/Rtmp0Q4t98/spat_5qulLVdkJETjyET_9592.tif" "C:/Users/11912/AppData/Local/Temp/Rtmp0Q4t98/spat_X3o3lVw7be7XmYM_9592.tif" "C:/Users/11912/AppData/Local/Temp/Rtmp0Q4t98/spat_LaO1pyo0LhgMyMk_9592.tif" "C:/Users/11912/AppData/Local/Temp/Rtmp0Q4t98/spat_DEE69oRT36WhSxz_9592.tif" ...
  .. .. .. .. .. .. ..$ bands : num [1:105] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. .. .. ..$ nlyr  : num [1:105] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..@ inMemory: logi TRUE
  .. .. ..@ link    : chr [1:2] "./Bins/proj_Future_ssp126_2081_2100/proj_Future_ssp126_2081_2100_Bins.tif" "./Bins/proj_Future_ssp126_2081_2100/proj_Future_ssp126_2081_2100_Bins_TSSbin.tif"
>

**Comment by MayaGueguen** [comment]
Hello there,

These are the outputs for : 
```
head(myBiomodProj)
str(myBiomodProj)

head(myBiomodProjectionFuture)
str(myBiomodProjectionFuture)
```
and not : 
```
CurrentProj <- get_predictions(myBiomodProj, 
                               metric.binary = "TSS",
                               model.as.col = TRUE)
FutureProj <- get_predictions(myBiomodProjectionFuture, 
                              metric.binary = "TSS",
                              model.as.col = TRUE)

head(CurrentProj)
str(CurrentProj)

head(FutureProj)
str(FutureProj)
````

Could you please provide me the outputs for these commands ?

Maya
