### ISSUE TITLE
formatting user.defined table for CV in modeling SDM transferability 

### ISSUE THREAD

**Issue by rwdearth** [biomodhub/biomod2#350]
_Please make sure to close the issue once you consider it as solved_
**Context and question**

I am currently working on building models for SDM transferability. (woody species) 
It means I am training my model in their native range (region A) first, and then project its predictions in novel environment (region B). And, to cross-validate if these predictions are accurate, I am thinking to use invasive occurrences in region B. 
So, basically, I have two sets of occurrences, one for calibration and one for validation. (Normal approach would have only one set of occurrence in their native range and split the occurrences for calibration and validation.) 
If I want to pursue this task, I need to provide user.defined table for CV, right? 

**My questions :**

1. How should I format my data when I have two different sets of occurrence from two distant regions (native vs. introduced). 
2. In BIOMOD_modeling, shall I provide two different data formats; one for calibration (myBioData) and one for cross-validation (user.defined table)? 
3. If so, how shall I provide user.defined table? do you have any example codes or table format? 

It would be greatly appreciated if you provide any guidance on this. 

Thank you! 

**Related code**

So, for training(calibration) input, I would have 

dav <- read.csv(file="dav_occ2.csv", header=TRUE) ## occurrence data frame with 2 columns of lng and lat 
species <- "davidii"
dav <- cbind(dav, rep.int(1, length(nrow(dav))))

myBioData <- BIOMOD_FormatingData(resp.name = species,
                                  resp.var = dav[, 4],
                                  resp.xy = dav[, 1:2],
                                  expl.var = range,                           **## should this raster file include BOTH native and novel geographic range?** 
                                  PA.nb.rep = 5,
                                  PA.nb.absences = 5000,
                                  PA.strategy="disk",              **## If range includes both, I set "disk" to ensure that I get random points only within the native range.** 
                                  PA.dist.min = 5000,
                                  PA.dist.max = 79000,
                                  na.rm=TRUE)

model.out <- BIOMOD_Modeling(
  myBioData,           **## so, would this be my normal input data (native occurrence in region A + background points) from native range for calibration?**
  [modeling.id](http://modeling.id/)='AllModels', 
  models = c('MAXENT'),
  bm.options = myBioOption,
  CV.strategy = 'user.defined',
  CV.nb.rep=10, 
  CV.user.table=cv.table,           **## cv.table  -> so, this should contain only second set (invasive occurrence in region B) for validation?** 
  var.import=2, 
  prevalence=0.5, 
  metric.eval=c(’TSS’, ‘ROC’), 
  seed.val=32) 
                          
from your Vignette, 

**user-defined** Allow the user to give its own crossvalidation table. For a presence-absence dataset, column names must be formatted as: _allData_RUNx with x an integer. For a presence-only dataset for which several pseudo-absence dataset were generated, column names must be for- matted as: _PAx_RUNy with x an integer and PAx an existing pseudo-absence dataset and y an integer 

With this description, it is a bit difficult to imagine a table. If there is any exemplary table as a reference, it would be great. 

```

**Comment by MayaGueguen** [comment]
Hello Eun,

Thank you for posting this issue with detailed informations :pray: 

If I understand correctly, you want to : 
1. build your model over zone A with dataset Native
2. validate over zone B with Invasive dataset
3. project over zone B

For that, you should use the `eval.[...]` parameters (`eval.resp.var`, `eval.expl.var` and `eval.resp.xy`) in [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function. These parameters allow you to give an independent dataset that will be only used to predict over those points, and calculate evaluation metrics.

Basically, it means that your workflow will look like this : 
1. Give your 2 datasets (Native and Invasive) to [Biomod_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function
2. Run [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function dividing the Native dataset with cross-validation methods (through `CV.[...]` parameters), to calibrate your model over your first dataset
4. Get evaluations for `calibration` and `validation` datasets built from Native data ; and for `evaluation` corresponding to Invasive dataset.
5. Project your model onto your new range (zone B - Invasive) dataset



In terms of code, it should look like this : 
```
species <- "davidii"

## Load NATIVE occurrences
## Should be a table with 3 columns : x, y, obs
## With obs column containing 0 or 1 values
tab.native <- read.csv(file = "dav_occ2.csv", header = TRUE)

## Load NATIVE environment
# var.native

## Load INVASIVE occurrences
## Should be a table with 3 columns : x, y, obs
## With obs column containing 0 or 1 values
## You should have presences and absences within this dataset
## Otherwise, if you have only presences, you will only be able to compute BOYCE index
# tab.invasive

## Load INVASIVE environment
# var.invasive


## Format data giving BOTH occurrences dataset
myBioData <- BIOMOD_FormatingData(resp.name = species,
                                  resp.var = tab.native$obs
                                  resp.xy = tab.native[, c("x", "y")],
                                  expl.var = var.native,
                                  eval.resp.var = tab.invasive$obs,
                                  eval.resp.xy = tab.invasive[, c("x", "y")],
                                  eval.expl.var = var.invasive,
                                  PA.nb.rep = 5,
                                  PA.nb.absences = 5000,
                                  PA.strategy = "disk", ## only points in native range
                                  PA.dist.min = 5000,
                                  PA.dist.max = 79000,
                                  na.rm = TRUE)

## Run models over NATIVE dataset (with cross-validation),
## and calculate evaluation metrics on both NATIVE and INVASIVE datasets
myBioMod <- BIOMOD_Modeling(myBioData,
                            modeling.id = 'AllModels',
                            models = c('MAXENT'),
                            bm.options = myBioOption,
                            CV.strategy = 'random',
                            CV.nb.rep = 10,
                            CV.perc = 0.7,
                            var.import = 2,
                            prevalence = 0.5,
                            metric.eval = c(’TSS’,  ‘ROC’, 'BOYCE'),
                            seed.val = 32)

myEval = get_evaluations(myBioMod)

## Project over INVASIVE dataset
myBioProj <- BIOMOD_Projection(bm.mod = myBioMod,
                               proj.name = 'ZoneB',
                               new.env = var.invasive,
                               models.chosen = 'all')
``` 

Please tell me if something remains unclear :eyes: 
Maya

**Comment by rwdearth** [comment]
Thank you so much for the codes, Maya. It really helped. 

But, another issue occurs with **eval.resp.var** in formating data
I just ran this code and error pops up with following message: 

Error in .check_formating_resp.var(resp.var = eval.sp, eval.data = TRUE) :
  Evaluation response data must have both presences and absences
Calls: BIOMOD_FormatingData ... .BIOMOD.formated.data.check.args -> .check_formating_resp.var
Execution halted

Since I have only presence data, would there be any way to go around? 

once again, would appreciate your answer to this. 

best, 

Eun

**Comment by rwdearth** [comment]
Hi, Maya, 

In addition to the error message yesterday, I encountered another error to share, and hope this information is useful to you and others. 
(The BIOMOD_FormattingData won't proceed without absences, so I had to create true absences data - based on my hypothesis - rather than pseudo-absences.)  However, another error message pops up as below with metric eval. BIOMOD2 package at this point does not seem to provide 'BOYCE' index.  

MAXENT default prevalence option was updated to fit with modeling prevalence (i.e 0.5 )
        > Automatic weights creation to rise a 0.5 prevalenceError in .fun_testIfIn(TRUE, "metric.eval", metric.eval, avail.eval.meth.list) :

metric.eval must be 'TSS', 'KAPPA', 'ACCURACY', 'BIAS', 'POD', 'FAR', 'POFD', 'SR', 'CSI', 'ETS', 'HK', 'HSS', 'OR', 'ORSS' or 'ROC
Calls: BIOMOD_Modeling -> .BIOMOD_Modeling.check.args -> .fun_testIfIn
Execution halted

So, I am writing again to make sure the current issue is known to all. 

- when providing a separate **eval.resp.var** in formating data, it is REQUIRED to provide absence records (No pseudo-absence is accepted.) 
- Since only presence records are accepted for evaluation records, there is NO 'Boyce' index in evaluation metric lists. 

So, for future library updates, I wish some of those issues can be reflected somehow. 

But, other than that, many thanks to Maya and others who contributed this biomod working! 

best, 

Eun

**Comment by MayaGueguen** [comment]
Hello Eun,

Ah, yes, sorry, I missed a few things...

Could you share with me the output of `sessionInfo()` please ?
You might be using a version previous to the addition of the BOYCE index within the evaluation metrics.
Try to use the `biomod2` version on CRAN (4.2-4), available through `install.packages("biomod2")` command.

And yes, we indeed restricted `eval.resp.var` to contain both presences and absences data to be able to compute most evaluation metrics.
What you can do is to sample randomly points within your evaluation area (zone B - invasive here) and add them to your evaluation dataset as "absences". But then only rely on BOYCE values when considering `evaluation` metrics (as other need true absences to be calculated).

Hope it helps,
Maya
