### ISSUE TITLE
Compared with the current situation

### ISSUE THREAD

**Issue by xiadawei123** [biomodhub/biomod2#351]
Hi，
I have fully run the current and future prediction results, and I would like to use the .bin results in the CurrentEM and FutureEM folders for visualization, and then compare them using BIOMOD_RangeSize. My Current results seem normal, but my Future results look a little strange. I am confused about the display results of the .bin in FutureEM, and I greatly appreciate your help.

code used as follow：
###Current
myBiomodProj <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name = "Current",  
  new.env = bioclim_sub,  
  models.chosen = "all",  
  metric.binary = "all",  
  metric.filter = "all",
  build.clamping.mask = TRUE,
  output.format = ".tif",
  do.stack = FALSE
)
myBiomodEMProj <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  bm.proj = myBiomodProj,    
  proj.name = "CurrentEM",
  models.chosen = "all",
  metric.binary = "all",
  metric.filter = "all",
  output.format = ".tif",
  do.stack = FALSE
)

###Future
myBiomodProjectionFuture <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name = "Future_ssp126_2081_2100",
  new.env = ssp126_2081_2100_bioclim_sub,
  models.chosen = "all",
  metric.binary = "TSS",
  build.clamping.mask = TRUE,
  output.format = ".tif"
)
myBiomodEMProjFuture <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  bm.proj = myBiomodProjectionFuture,
  proj.name = "FutureEM_ssp126_2081_2100",
  models.chosen = "all",
  metric.binary = "all",
  metric.filter = "all",
  output.format = ".tif",
  do.stack = FALSE
)

###Comparison
Bin_proj_current <-
  rast(c(ca1 = "C:/Users/proj_CurrentEM/individual_projections/Bins_EMcaByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.tif" )）
names(Bins_bin_proj_current) <- paste0("cur_",c("ca"))
plot(Bins_bin_proj_current)

![image](https://github.com/biomodhub/biomod2/assets/148743500/1c371dbc-5215-4c39-be18-3cd0676ac111)

Bin_ssp126_2041_2060_bin <-
  rast(c( ca2 = "C:/Users/Desktop/proj_FutureEM_ssp126_2041_2060/individual_projections/Bins_EMcaByTSS_mergedData_mergedRun_mergedAlgo_TSSbin.tif" ))
names(Bins_ssp126_2041_2060_bin) <- paste0("ssp126_2041_2060_",c("ca"))
plot(Bins_ssp126_2041_2060_bin)

![image](https://github.com/biomodhub/biomod2/assets/148743500/cb2180c2-2fe5-4b01-8470-9afaf470e2c8)

Thank you!

**Comment by MayaGueguen** [comment]
Hello there,

To try and understand what is going on with your future projection, you need to dig up a bit what is going on in your data and models :eyes: 

Having a look at **variables' importance**, as well as **response curves** should give you insight about which variables have an impact on your species' probability of presence. Then you should have a look at your **variables' future map**.

For example, here, it could be that only one variable (let's call it `VarA`) is driving the probability of presence of your species. Let's say that the model predicts that your species is present when `VarA` is between 10 and 25. If in the future, `VarA` has values between 10 and 25 all over your study area, then it explains why your species is predicted present everywhere.

Maya
