### ISSUE TITLE
Help with BIOMOD_Formatingdata - differences between undefined data and pseudo-absences.

### ISSUE THREAD

**Issue by joshc99** [biomodhub/biomod2#352]
Hello,

I have tried to review documentation, videos and other questions but I'm still not 100% sure on this. I am trying to run some simple models for a bird species with presence and pseudo-absence data, but to try and mitigate sampling bias, I want to select pseudo-absences from the presence data of other bird species. 

In trying to find the easiest way to do this with biomod, I am not sure if I need to use the user defined pseudo-absences or if I can just include this within the background/undefined/NA points for resp.xy and resp.var.

To summarise, my question is if I include sites in my resp.xy with resp.var=NA, and use PA.strategy='random' does this only generate pseudo-absences from those NA points? Or does this just pull points from anywhere within the environmental layers. And as a follow-up question, if we can use the resp.xy and resp.var to define where pseudo-absences should be drawn from, what is the benefit of using the user defined method?

For reference, I have included a screenshot of part of my resp matrix (where resp=1 is the species I am modelling and resp=NA is the points I want to draw my pseudo-absences from). 

Thank you so much for any help you can provide!
Cheers!!  :)

![image](https://github.com/biomodhub/biomod2/assets/149371814/5661cce5-3749-4d0c-a08b-ee95afc153f2)

**Comment by MayaGueguen** [comment]
Hello Josh,

Thank you for your question, I'll try to give you some clarifications :bulb: 

If I understand correctly, you have presence points for your species A, and want to draw pseudo-absence points among presence points of other species.

- If you use the `random` method with raster maps, it will draw pseudo-absences within points all over your study area (_which you don't want here_)
- If you use the `resp.var` with `NA` values, it will draw pseudo-absences within these `NA` points (_which is what you want_)
- If you use the `user.defined` method, you can give it a table containing points preliminary randomly drawn by yourself among your other bird species presences (_which is what you want_) but you could also give pseudo-absences drawn following any other specific decisions you would like

So indeed, you could manage to do what you want with both methods : `user.defined` or `random` with `NA` points within your `resp.var`. But the `user.defined` method will require for your to do the random selection before using `biomod2` functions.

In any case, be sure to check your pseudo-absence selection, for example with by plotting your `BIOMOD.formated.data.PA` object obtained from the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) :detective: 

Maya

**Comment by joshc99** [comment]
Hi Maya,

Perfect, thank you for such a quick and helpful reply. I guess I didn't understand why there would be the option for both methods if you could use either but I see the user defined method allows you to pick exactly which are used in which PA draw. Thank you!

I have also a related follow-up question. Does biomod ignore NA/background points if they have the same coordinates (or share a raster cell) with a presence point (since these should not be suitable for pseudo-absence points)?? Or do we need to manually filter these out of the NA/background data set prior to the BIOMOD_Formatingdata step??

Thank you!

**Comment by MayaGueguen** [comment]
Hello Josh,

Sorry for the delay :pray:, I did not forget you, but wanted to check things first to be sure to give you the correct answer.

So, there is no check on coordinates at the occurrence/background level. Meaning that indeed, if you have presence and background points with same coordinates, and you sample pseudo-absence points with `PA.strategy = 'random'`, you can select these points : 

```
library(biomod2)
library(terra)

# Load species occurrences (6 species available)
data("DataSpecies")
head(DataSpecies)

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
data("bioclim_current")
myExpl <- rast(bioclim_current)


## ADD background points with same coordinates as some presences : 
myResp.PA <- ifelse(myResp == 1, 1, NA)
myRespXY = rbind(myRespXY[which(myResp.PA==1)[1:10], ], myRespXY)
dim(myRespXY)
length(myResp.PA)

myResp.PA = c(rep(NA,10), myResp.PA)
myResp.PA[1:20]
myRespXY[1:20, ]

## SELECT pseudo-absences : 
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 4,
                                       PA.nb.absences = 1000,
                                       PA.strategy = 'random')
plot(myBiomodData.r)
summary(myBiomodData.r)
head(myBiomodData.r@PA.table) ## if there is TRUE in the first 10 lines, it has been selected
```

The `filter.raster` parameter within the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function allows to keep only one point if some have same coordinates / or fall in the same pixel. BUT :warning: it keeps the first point occuring in the dataset without regarding if it is an occurrence or a background point.

So it is better indeed to filter your data before if you want to be sure not to select these points. Note that it should not have a big impact on your modelisation if you are selecting enough pseudo-absence points anyway.

Maya

**Comment by joshc99** [comment]
Hi Maya,

Thanks for coming back to this, and with such a detailed response! That all makes sense, thank you! The way my data is formatted is with the presences listed first, so if I use filter.raster it should only remove pseudo-absences (and duplicate presences of course).

Thank you!
