### ISSUE TITLE
BIOMOD_Projection clamping error 'writeRaster': [subset] you cannot select a layer with a name that is not unique""

### ISSUE THREAD

**Issue by rwdearth** [biomodhub/biomod2#353]
Hello, 

**Error and context**
I enountered unexpected error while the same code worked for different sets of environmental variables. 
But, only this particular version gives this clamping error in BIOMOD projection. 

The batch script stopped at BIOMOD_projection, and I have no idea what caused this problem because it seems all layers and model names are unique.  If I set build.clamping.mask=TRUE, then it gives an error:  > Building clamping mask
Error: [subset] invalid name(s)
Execution halted

Error in { :
  task 1 failed - "task 5 failed - "error in evaluating the argument 'x' in selecting a method for function 'writeRaster': [subset] you cannot select a layer with a name that is not unique""
Calls: BIOMOD_Projection -> %dopar% -> <Anonymous>

**Code used to get the error**
New_proj <- BIOMOD_Projection(model.out,
                     proj.name="Palmatum",
                    new.env=UK_env_masked,
                    models.chosen ="all",
                    compress='gzip',
                    build.clamping.mask=FALSE,
                    nb.cpu=3,
                    seed.val=32)

-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=

        > Projecting palmatum_PA1_RUN1_MAXENT ...
        > Projecting palmatum_PA1_RUN2_MAXENT ...
        > Projecting palmatum_PA1_RUN3_MAXENT ...
        > Projecting palmatum_PA1_RUN4_MAXENT ...
        > Projecting palmatum_PA1_RUN5_MAXENT ...
        > Projecting palmatum_PA1_RUN6_MAXENT ...
        > Projecting palmatum_PA1_RUN7_MAXENT ...
        > Projecting palmatum_PA1_RUN8_MAXENT ...
        > Projecting palmatum_PA1_RUN9_MAXENT ...
        > Projecting palmatum_PA1_RUN10_MAXENT ...
        > Projecting palmatum_PA2_RUN1_MAXENT ...
        > Projecting palmatum_PA2_RUN2_MAXENT ...
        > Projecting palmatum_PA2_RUN3_MAXENT ...
        > Projecting palmatum_PA2_RUN4_MAXENT ...
        > Projecting palmatum_PA2_RUN5_MAXENT ...
        > Projecting palmatum_PA2_RUN6_MAXENT ...
        > Projecting palmatum_PA2_RUN7_MAXENT ...
        > Projecting palmatum_PA2_RUN8_MAXENT ...
        > Projecting palmatum_PA2_RUN9_MAXENT ...
        > Projecting palmatum_PA2_RUN10_MAXENT ...
        > Projecting palmatum_PA3_RUN1_MAXENT ...
        > Projecting palmatum_PA3_RUN2_MAXENT ...
        > Projecting palmatum_PA3_RUN3_MAXENT ...
        > Projecting palmatum_PA3_RUN4_MAXENT ...
        > Projecting palmatum_PA3_RUN5_MAXENT ...
        > Projecting palmatum_PA3_RUN6_MAXENT ...
        > Projecting palmatum_PA3_RUN7_MAXENT ...
        > Projecting palmatum_PA3_RUN8_MAXENT ...
        > Projecting palmatum_PA3_RUN9_MAXENT ...
        > Projecting palmatum_PA3_RUN10_MAXENT ...
        > Projecting palmatum_PA4_RUN1_MAXENT ...
        > Projecting palmatum_PA4_RUN2_MAXENT ...
        > Projecting palmatum_PA4_RUN3_MAXENT ...
        > Projecting palmatum_PA4_RUN4_MAXENT ...
        > Projecting palmatum_PA4_RUN5_MAXENT ...
        > Projecting palmatum_PA4_RUN6_MAXENT ...
        > Projecting palmatum_PA4_RUN7_MAXENT ...
        > Projecting palmatum_PA4_RUN8_MAXENT ...
        > Projecting palmatum_PA4_RUN9_MAXENT ...
        > Projecting palmatum_PA4_RUN10_MAXENT ...
        > Projecting palmatum_PA5_RUN1_MAXENT ...
        > Projecting palmatum_PA5_RUN2_MAXENT ...
        > Projecting palmatum_PA5_RUN3_MAXENT ...
        > Projecting palmatum_PA5_RUN4_MAXENT ...
        > Projecting palmatum_PA5_RUN5_MAXENT ...
        > Projecting palmatum_PA5_RUN6_MAXENT ...
        > Projecting palmatum_PA5_RUN7_MAXENT ...
        > Projecting palmatum_PA5_RUN8_MAXENT ...
        > Projecting palmatum_PA5_RUN9_MAXENT ...
        > Projecting palmatum_PA5_RUN10_MAXENT ...Error in { : task 1 failed - "task 5 failed - "error in evaluating the argument 'x' in selecting a method for function 'writeRaster': [subset] you cannot select a layer with a name that is not unique"" Calls BIOMOD_Projection -> %dopar% -> <Anonymous>

```
# Example for an error in BIOMOD_EnsembleForecasting

myBiomodData <- BIOMOD_FormatingData( ** write arguments here **)
myBioData <- BIOMOD_FormatingData(resp.name = species,
                                  resp.var = pal[, 4], 
                                  resp.xy = pal[, 1:2],
                                  expl.var = KJ_range,
                                  PA.nb.rep = 5, 
                                  PA.nb.absences = 10000, 
                                  PA.strategy="disk",
                                  PA.dist.min=60000, 
                                  PA.dist.max=200000, 
                                  na.rm=TRUE)

myBiomodModelOut <- BIOMOD_Modeling( ** write arguments here **)
model.out <- BIOMOD_Modeling(
  myBioData,
  modeling.id='AllMOdels', 
  models = c('MAXENT'), 
  bm.options = myBioOption,
  CV.strategy = 'random', 
  CV.nb.rep = 10, 
  CV.perc = 0.75, 
  var.import = 2,
  prevalence=0.5, 
  metric.eval = c('TSS', 'ROC'),
  nb.cpu=3,  
  seed.val=32

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for posting :pray: 
Could you provide me please the output of the following commands ?

- `sessionInfo()`
- `show(myBioData)`
- `KJ_range`
- `UK_env_masked`

Maya
