### ISSUE TITLE
Error in BIOMOD_2 - MAXENT "object 'Back_swd' not found"

### ISSUE THREAD

**Issue by Unidad-Robotica-Dlab** [biomodhub/biomod2#355]
Hello Biomod team :)

**Error and context**
When running MAXENT in Biomod2 I feed MAXENT models with background data so MAXENT can chosse it's own background. However, I keep getting the same error. I have tried using the code provided here: [https://rpubs.com/dgeorges/190889](url)

- I checked that the file path doesn't have any spaces
- the environmetal variables are in ASCII and have rectangular cells
- I gave the dir.name to BIOMOD_Formatig data as in [https://github.com/biomodhub/biomod2/issues/341](url)

**Code used to get the error**

myBiomodglobal2 <- BIOMOD_FormatingData(resp.var = sp.trn$status,
                                       expl.var = varclim,
                                       resp.xy = sp.trn[,1:2],
                                       resp.name = "Carpoglobal1",
                                       eval.resp.var = sp.tst$status,
                                       eval.expl.var = varclim,
                                       eval.resp.xy = sp.tst[,1:2],
                                       PA.nb.rep = 0,
                                       PA.nb.absences = NULL, 
                                       PA.strategy = NULL,
                                       PA.dist.min = NULL,
                                       PA.dist.max = NULL,
                                       na.rm = TRUE,
                                       dir.name = "G:/for_biomod_dormilon/" )

maxent.background.dat.dir <- "maxent_bg"
dir.create(maxent.background.dat.dir, showWarnings = FALSE, recursive = TRUE)

###########resave explanatory data####
for(var_ in names(varclim)){
  cat("\n> saving", paste0(var_, ".asc"))
  writeRaster(subset(varclim, var_), 
              filename = file.path(maxent.background.dat.dir, paste0(var_, ".asc")),
              overwrite = TRUE)
}
myBiomodOption <- BIOMOD_ModelingOptions(MAXENT = list(background_data_dir= maxent.background.dat.dir)

myBiomodGlobalout_test2 <- BIOMOD_Modeling(bm.format = myBiomodglobal2,
                                       models = c("MAXENT"),
                                       bm.options = myBiomodOption,
                                       CV.nb.rep = 1,
                                       CV.perc =  0.7,                                      
                                       var.import = 20, 
                                       metric.eval= c('KAPPA', 'TSS', 'ROC') 
                                       ) 

 ###########format data for biomod 2####
> ###############################################
> myBiomodglobal2 <- BIOMOD_FormatingData(resp.var = sp.trn$status,
                                       expl.var = varclim,
                                        resp.xy = sp.trn[,1:2],
                                        resp.name = "Carpoglobal1", # change species name
                                        eval.resp.var = sp.tst$status,
                                        eval.expl.var = varclim,
                                        eval.resp.xy = sp.tst[,1:2],
                                        PA.nb.rep = 0,
                                        PA.nb.absences = NULL, 
                                        PA.strategy = NULL,
                                        PA.dist.min = NULL,
                                        PA.dist.max = NULL,
                                        na.rm = TRUE,
                                        dir.name = "G:/for_biomod_dormilon/" )

-=-=-=-=-=-=-=-=-=-=-=-=-= Carpoglobal1 Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

myBiomodglobal2

-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  G:/for_biomod_dormilon/

sp.name =  Carpoglobal1
	 590 presences,  590 true absences and  0 undefined points in dataset
	 5 explanatory variables

      bio7            bio6            bio18            bio19      
 Min.   :112.0   Min.   :-52.00   Min.   :  0.00   Min.   : 21.0  
 1st Qu.:175.0   1st Qu.: 38.00   1st Qu.: 12.00   1st Qu.:136.0  
 Median :200.0   Median : 55.00   Median : 47.00   Median :213.0  
 Mean   :208.5   Mean   : 55.32   Mean   : 79.34   Mean   :261.6  
 3rd Qu.:241.0   3rd Qu.: 72.00   3rd Qu.: 95.00   3rd Qu.:322.2  
 Max.   :374.0   Max.   :176.00   Max.   :643.00   Max.   :990.0  
   footprint      
 Min.   :  0.000  
 1st Qu.:  8.272  
 Median : 19.038  
 Mean   : 34.588  
 3rd Qu.: 48.199  
 Max.   :128.000  

Evaluation data :

	 148 presences,  147 true absences and  0 undefined points in dataset

      bio7            bio6            bio18            bio19      
 Min.   :122.0   Min.   : -9.00   Min.   :  0.00   Min.   : 25.0  
 1st Qu.:173.0   1st Qu.: 24.00   1st Qu.: 31.00   1st Qu.:206.0  
 Median :188.0   Median : 38.00   Median : 55.00   Median :558.0  
 Mean   :195.5   Mean   : 42.55   Mean   : 64.67   Mean   :535.8  
 3rd Qu.:210.5   3rd Qu.: 60.50   3rd Qu.: 88.00   3rd Qu.:857.5  
 Max.   :374.0   Max.   :126.00   Max.   :545.00   Max.   :990.0  
   footprint      
 Min.   :  1.000  
 1st Qu.:  4.614  
 Median : 11.719  
 Mean   : 30.667  
 3rd Qu.: 48.022  
 Max.   :128.000  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

show(varclim) # if using an environment raster
class       : SpatRaster 
dimensions  : 2269, 4641, 5  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -163.25, 30.125, -46.04168, 48.49999  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
sources     : bio7.tif  
              bio6.tif  
              bio18.tif  
              ... and 2 more source(s)
names       : bio7, bio6, bio18, bio19, footprint 

> maxent.background.dat.dir <- "maxent_bg"
> dir.create(maxent.background.dat.dir, showWarnings = FALSE, recursive = TRUE)
> ###########resave explanatory data####
> for(var_ in names(varclim)){
   cat("\n> saving", paste0(var_, ".asc"))
   writeRaster(subset(varclim, var_), 
               filename = file.path(maxent.background.dat.dir, paste0(var_, ".asc")),
               overwrite = TRUE)
 }

> saving bio7.asc
> saving bio6.asc
> saving bio18.asc
> saving bio19.asc
> saving footprint.asc
> myBiomodOption <- BIOMOD_ModelingOptions(MAXENT = list(background_data_dir= maxent.background.dat.dir))
> myBiomodGlobalout_test <- BIOMOD_Modeling(bm.format = myBiomodglobal2,
                                        models = c("MAXENT"),
                                        bm.options = myBiomodOption,
                                        CV.nb.rep = 1,
                                        CV.perc =  0.7,                                      
                                        var.import = 20, 
                                        metric.eval= c('KAPPA', 'TSS', 'ROC') # performance metric
                                        ) 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Checking Models arguments...

	> Automatic weights creation to rise a 0.5 prevalence
Creating suitable Workdir...

Checking Cross-Validation arguments...

   > Random cross-validation selection

-=-=-=-=-=-=-=-=-=-=-=-= Carpoglobal1 Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=

 5  environmental variables ( bio7 bio6 bio18 bio19 footprint )
Number of evaluation repetitions : 1
Models selected : MAXENT 

Total number of model runs: 1 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

-=-=-=--=-=-=- Carpoglobal1_allData_RUN1_MAXENT 

Model=MAXENT
	> MAXENT modeling...
		Creating Maxent Temp Proj Data...Error in { : task 1 failed - "object 'Back_swd' not found"

```

**Environment Information**
Please paste the output of `sessionInfo()` in your current R session below.
```
sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: America/Santiago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ecospat_4.0.0    ggmap_3.0.2      dplyr_1.1.3      ggplot2_3.4.4   
 [5] reshape2_1.4.4   gridExtra_2.3    abind_1.4-5      usdm_2.1-7      
 [9] terra_1.7-46     biomod2_4.2-4    ecodist_2.1.3    rasterVis_0.51.6
[13] lattice_0.22-5   ade4_1.7-22      dismo_1.3-14     raster_3.6-26   
[17] sp_2.0-0        

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0       viridisLite_0.4.2      bitops_1.0-7          
 [4] reshape_0.8.9          pROC_1.18.4            rpart_4.1.19          
 [7] lifecycle_1.0.3        survival_3.5-5         magrittr_2.0.3        
[10] compiler_4.3.1         rlang_1.1.1            tools_4.3.1           
[13] igraph_1.5.1           plotrix_3.8-3          utf8_1.2.3            
[16] data.table_1.14.8      interp_1.1-4           xgboost_1.7.5.1       
[19] classInt_0.4-10        PresenceAbsence_1.1.11 plyr_1.8.8            
[22] RColorBrewer_1.1-3     earth_5.3.2            KernSmooth_2.23-21    
[25] withr_2.5.2            purrr_1.0.2            nnet_7.3-19           
[28] grid_4.3.1             fansi_1.0.4            latticeExtra_0.6-30   
[31] e1071_1.7-13           colorspace_2.1-0       scales_1.2.1          
[34] iterators_1.0.14       MASS_7.3-60            RgoogleMaps_1.4.5.3   
[37] cli_3.6.1              generics_0.1.3         rstudioapi_0.15.0     
[40] httr_1.4.7             proxy_0.4-27           stringr_1.5.0         
[43] splines_4.3.1          parallel_4.3.1         vctrs_0.6.3           
[46] Matrix_1.6-1.1         jsonlite_1.8.7         Formula_1.2-5         
[49] jpeg_0.1-10            foreach_1.5.2          hexbin_1.28.3         
[52] tidyr_1.3.0            glue_1.6.2             plotmo_3.6.2          
[55] codetools_0.2-19       stringi_1.7.12         mda_0.5-4             
[58] gtable_0.3.4           deldir_1.0-9           munsell_0.5.0         
[61] tibble_3.2.1           pillar_1.9.0           randomForest_4.7-1.1  
[64] gbm_2.1.8.1            R6_2.5.1               maxnet_0.1.4          
[67] png_0.1-8              TeachingDemos_2.12     class_7.3-22          
[70] Rcpp_1.0.11            nlme_3.1-162           mgcv_1.8-42           
[73] fs_1.6.3               zoo_1.8-12             usethis_2.2.2         
[76] pkgconfig_2.0.3  
```
[varclim.zip](https://github.com/biomodhub/biomod2/files/13257729/varclim.zip)


**Additional information**
If you have any additional information or context you can add it here.

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for the nicely formatted issue :pray: :sun_with_face: 

Could you try without defining the `background_data_dir` parameter within the `BIOMOD_ModelingOptions` function please ?
It is possible that it was the way to do it before, when we managed climatic data for MAXENT only through `.asc` files, but that we fixed it nwow to use directly the data provided through the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function.

Maya

**Comment by Unidad-Robotica-Dlab** [comment]
Thank you so much for replying. 

The actual model includes, besides MAXENT; RF, GBM and GAM. 
BIOMOD_Modeling works without problem with all of them but fail with MAXENT when background_data_dir is given.
Considering that for RF is better to have similar number of presences and pseudo-absences,
I was hopping to give maxent the background so it can generate the maximun number of random of data from all the background, and for that, I believe it requires the background_data_dir. Otherwise, I can try to give different 
pseudo-absences for each modelling algorithms as it was asked in #354, however, the 'random' option would be needed only for maxent and the 'disk' option would be needed for the other algorithms.

I saw that 'it is possible now to create several pseudo-absence repetitions with different number of points, but with the same sampling strategy' so not sure how to proceed.

I have only started using the new Biomod2 recently, so apologies in advance for any confusion.
Also, please let me know if I should add a this response as a new question as 'help wanted'.

**Comment by MayaGueguen** [comment]
Yes, indeed it is only possible to create several pseudo-absence sets with different number of points but with the same sampling strategy.

One option would be to run two different simulations separately (one set with `RF`, `GBM`, `GAM` ; one set with `MAXENT`), but then you would not be able to combine them into ensemble models.

Other option would be for to select you pseudo-absences yourself and give them to the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function through the `PA.user.table` parameter and using `PA.strategy = 'user.defined'`.
In that case, you can use directly the [bm_PseudoAbsences](https://biomodhub.github.io/biomod2/reference/bm_PseudoAbsences.html) function.

Hope it helps :sunflower: 

Maya
