### ISSUE TITLE
Biomod2 has an error while modeling Maxent，such as Error in MAXENT, more info available in [short error summary here]

### ISSUE THREAD

**Issue by xiangyataboy** [biomodhub/biomod2#356]
Biomod2 has an error while modeling Maxent：

myBiomodOption <- BIOMOD_ModelingOptions(
  MAXENT = list( path_to_maxent.jar =  "Desktop/R work/PR/maxent/maxent.jar",
                 maximumiterations = 200,
                 visible = FALSE,
                 linear = TRUE,
                 quadratic = TRUE,
                 product = TRUE,
                 threshold = TRUE,
                 hinge = TRUE,
                 lq2lqptthreshold = 80,
                 l2lqthreshold = 10,
                 hingethreshold = 15,
                 beta_threshold = -1,
                 beta_categorical = -1,
                 beta_lqp = -1,
                 beta_hinge = -1,
                 defaultprevalence = 0.5))

library(biomod2)
my_data <- BIOMOD_FormatingData(resp.var = rep(1, nrow(data.excel)), 
                                expl.var = bioclim_sub,
                                resp.xy =data.excel[,2:3],
                                resp.name = "PR",
                                PA.nb.rep = 5,
                                PA.nb.absences = 500
 PA.strategy = 'random')

my_models <- BIOMOD_Modeling(my_data, models = c('GLM','MARS','RF','CTA','ANN','MAXENT.Phillips'),
                             CV.nb.rep= 3
                             CV.perc=0.75,
                             bm.options =myBiomodOption,
                             metric.eval = c('TSS','ROC'),
                             scale.models=F,
                             var.import = 3, do.full.models = F, modeling.id = "test")

Here are some of the errors above R

-=-=-=--=-=-=- PR_PA5_RUN3_CTA 

Model=Classification tree 
	 5 Fold Cross-Validation
	> CTA modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |=======================================================================================================| 100%

-=-=-=--=-=-=- PR_PA5_RUN3_ANN 

Model=Artificial Neural Network 
	 5 Fold Cross Validation + 3 Repetitions
	> ANN modeling...
	Model scaling...
*** single value predicted
   ! Note :  PR_PA5_RUN3_ANN failed!

-=-=-=--=-=-=- PR_PA5_RUN3_MAXENT 

Model=MAXENT
	> MAXENT modeling...
		Creating Maxent Temp Proj Data...
*** Error in MAXENT, more info available in ./PR/models/test/PR_PA5_RUN3_MAXENT_outputs/maxent.stderr
*** inherits(g.pred,'try-error')
   ! Note :  PR_PA5_RUN3_MAXENT failed!

How to solve the problem above

**Comment by MayaGueguen** [comment]
Hello there,

Did you check the content of the `./PR/models/test/PR_PA5_RUN3_MAXENT_outputs/maxent.stderr` file ?
Also, could you provide the outputs of the following commands please ?

- `sessionInfo()`
- `my_data`
- `plot(my_data)`

Maya

**Comment by xiangyataboy** [comment]
> Hello there,
> 
> Did you check the content of the `./PR/models/test/PR_PA5_RUN3_MAXENT_outputs/maxent.stderr` file ? Also, could you provide the outputs of the following commands please ?
> 
> * `sessionInfo()`
> * `my_data`
> * `plot(my_data)`
> 
> Maya
I've checked the maxent.stderr file and found that it's only 1kb in size,here's what you need.
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)
> my_data

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  PR

	 83 presences,  0 true absences and  1000 undefined points in dataset


	 4 explanatory variables

     crop12           crop4            crop15           crop3      
 Min.   :  16.0   Min.   : 258.5   Min.   : 26.57   Min.   :20.94  
 1st Qu.: 144.5   1st Qu.: 596.8   1st Qu.: 82.35   1st Qu.:31.23  
 Median : 540.0   Median : 789.5   Median : 93.75   Median :36.64  
 Mean   : 687.8   Mean   : 823.6   Mean   : 95.50   Mean   :36.52  
 3rd Qu.:1039.5   3rd Qu.:1045.0   3rd Qu.:109.42   3rd Qu.:41.54  
 Max.   :5728.0   Max.   :1629.9   Max.   :157.48   Max.   :54.05  


 2 Pseudo Absences dataset available ( PA1, PA2 ) with  500 (PA1, PA2) pseudo absences


> plot(my_data)
SpatRaster resampled to ncells = 501102
$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 1249, 2  (geometries, attributes)
 extent      : 75.02917, 111.9958, 20.0375, 44.90417  (xmin, xmax, ymin, ymax)
 coord. ref. :  
 names       :  resp         dataset
 type        : <num>           <chr>
 values      :    10 Initial dataset
                  10 Initial dataset
                  10 Initial dataset

$data.label
                              9                              10                              11 
                "**Presences**"       "Presences (calibration)"        "Presences (validation)" 
                             12                              19                              20 
       "Presences (evaluation)"             "**True Absences**"   "True Absences (calibration)" 
                             21                              22                              29 
   "True Absences (validation)"    "True Absences (evaluation)"           "**Pseudo-Absences**" 
                             30                              31                               1 
"Pseudo-Absences (calibration)"  "Pseudo-Absences (validation)"                    "Background" 

$data.plot

**Comment by MayaGueguen** [comment]
Could you send please : 

- the content of the file (or the file directly) `./PR/models/test/PR_PA5_RUN3_MAXENT_outputs/maxent.stderr`
- the full result of the `sessionInfo()` command
- the plot associated with the `plot(my_data)` command

?

**Comment by xiangyataboy** [comment]
> Could you send please :
> 
> * the content of the file (or the file directly) `./PR/models/test/PR_PA5_RUN3_MAXENT_outputs/maxent.stderr`
> * the full result of the `sessionInfo()` command
> * the plot associated with the `plot(my_data)` command
> 
> ?
Sorry, I solved the problem with the maxent.stderr file and found that the path has spaces (R “spaces” work)，thank you for the answer.Then I found out that there is a new error, and the file generated by the MAXENT model does not have projMaxent.asc. Here's what the error is about:

Warning messages:
1: glm.fit:The fitting probability is calculated as a value of zero or one
2: In system(command = maxent.command, wait = TRUE, intern = TRUE) :
  Run the command "java -mx512m -cp "C:\Users\34002\Desktop/maxent.jar" density.Project "" "./PR/models/test/PR_PA2_RUN2_MAXENT_outputs/Predictions/Pred_swdBis_33107.csv" "./PR/models/test/PR_PA2_RUN2_MAXENT_outputs/projMaxent.asc" doclamp=false visible=false autorun nowarnings notooltips'The status is 1
3: In file(fname, "r") :
  Unable to open file'./PR/models/test/PR_PA2_RUN2_MAXENT_outputs/projMaxent.asc': No such file or directory
Error in { : task 6 failed - "Unable to make model prediction"

```
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggtext_0.1.2    tidyterra_0.4.0 ecospat_4.0.0   spatial_7.3-17  rgdal_1.6-7     raster_3.6-26   sp_2.1-1       
[8] biomod2_4.2-4  

loaded via a namespace (and not attached):
 [1] gtable_0.3.4           gbm_2.1.8.1            ggplot2_3.4.4          maxnet_0.1.4          
 [5] lattice_0.22-5         vctrs_0.6.3            tools_4.3.1            generics_0.1.3        
 [9] tibble_3.2.1           proxy_0.4-27           PresenceAbsence_1.1.11 fansi_1.0.5           
[13] pkgconfig_2.0.3        Matrix_1.6-1.1         KernSmooth_2.23-22     data.table_1.14.8     
[17] lifecycle_1.0.3        compiler_4.3.1         stringr_1.5.0          munsell_0.5.0         
[21] terra_1.7-55           codetools_0.2-19       class_7.3-22           Formula_1.2-5         
[25] tidyr_1.3.0            pillar_1.9.0           MASS_7.3-60            classInt_0.4-10       
[29] iterators_1.0.14       plotmo_3.6.2           rpart_4.1.21           earth_5.3.2           
[33] abind_1.4-5            foreach_1.5.2          nlme_3.1-163           mda_0.5-4             
[37] TeachingDemos_2.12     tidyselect_1.2.0       stringi_1.7.12         purrr_1.0.2           
[41] sf_1.0-14              dplyr_1.1.3            reshape2_1.4.4         splines_4.3.1         
[45] grid_4.3.1             colorspace_2.1-0       cli_3.6.1              magrittr_2.0.3        
[49] randomForest_4.7-1.1   survival_3.5-7         utf8_1.2.4             e1071_1.7-13          
[53] withr_2.5.2            scales_1.2.1           plotrix_3.8-3          xgboost_1.7.5.1       
[57] nnet_7.3-19            mgcv_1.9-0             rlang_1.1.1            gridtext_0.1.5        
[61] Rcpp_1.0.11            glue_1.6.2             DBI_1.1.3              xml2_1.3.5            
[65] pROC_1.18.5            rstudioapi_0.15.0      reshape_0.8.9          jsonlite_1.8.7        
[69] R6_2.5.1               plyr_1.8.9             units_0.8-4       

<html>
<body>
<!--StartFragment-->

> my_data 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  dir.name =  .  sp.name =  PR 	 83 presences,  0 true absences and  1000 undefined points in dataset   	 4 explanatory variables       crop12           crop4            crop15           crop3        Min.   :  16.0   Min.   : 258.5   Min.   : 26.57   Min.   :20.94    1st Qu.: 144.5   1st Qu.: 596.8   1st Qu.: 82.35   1st Qu.:31.23    Median : 540.0   Median : 789.5   Median : 93.75   Median :36.64    Mean   : 687.8   Mean   : 823.6   Mean   : 95.50   Mean   :36.52    3rd Qu.:1039.5   3rd Qu.:1045.0   3rd Qu.:109.42   3rd Qu.:41.54    Max.   :5728.0   Max.   :1629.9   Max.   :157.48   Max.   :54.05      2 Pseudo Absences dataset available ( PA1, PA2 ) with  500 (PA1, PA2) pseudo absences  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
--
 
> | >
>

<!--EndFragment-->
</body>
</html>
> plot(my_data)
SpatRaster resampled to ncells = 501102
$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 1249, 2  (geometries, attributes)
 extent      : 75.02917, 111.9958, 20.0375, 44.90417  (xmin, xmax, ymin, ymax)
 coord. ref. :  
 names       :  resp         dataset
 type        : <num>           <chr>
 values      :    10 Initial dataset
                  10 Initial dataset
                  10 Initial dataset

$data.label
                              9                              10                              11 
                "**Presences**"       "Presences (calibration)"        "Presences (validation)" 
                             12                              19                              20 
       "Presences (evaluation)"             "**True Absences**"   "True Absences (calibration)" 
                             21                              22                              29 
   "True Absences (validation)"    "True Absences (evaluation)"           "**Pseudo-Absences**" 
                             30                              31                               1 
"Pseudo-Absences (calibration)"  "Pseudo-Absences (validation)"                    "Background" 

$data.plot
```
![plot](https://github.com/biomodhub/biomod2/assets/143244986/0a43d195-127d-43f2-8660-ac6bb51b272e)
