### ISSUE TITLE
Question about BIOMOD_Projection output - Change in output pdf resolution

### ISSUE THREAD

**Issue by Data-Madman** [biomodhub/biomod2#357]
Hellow everyone,

I'm having trouble plotting and exporting the BIOMOD_Projection output.
I want to predict the distribution of intertidal areas, which is a dataset with high resolution.
![image](https://github.com/biomodhub/biomod2/assets/81616267/6dbaa564-a699-467e-815d-ea738430680d)
However, if you follow the official method of plotting project.out directly plot(output), you get a very much lower resolution image.
![image](https://github.com/biomodhub/biomod2/assets/81616267/b2dc2c28-3523-4893-87ed-8a8f72896c2e)

Also, if I want to export the results directly to '.tif' via the BIOMOD_Projection function and use ArcGIS to look at the results, I find that even though I set up all model, only 4 tifs are exported, and I'm not sure of the exact significance of these four files.
![image](https://github.com/biomodhub/biomod2/assets/81616267/992170ea-2f04-4b82-b0a5-502295935a6b)

In a word, I don't know how to view the model outputs in raw resolution and whether the format of the outputs can be transformed, and how I should go about processing them?

The code is below:
`myBiomodProj <- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name = 'Current1',
  new.env = mask3,
  models.chosen = 'all',
  metric.binary = 'all',
  output.format = '.tif',
  build.clamping.mask = TRUE
)#a raster file will be saved within the projection folder. This mask values will correspond to the number of variables in each pixel that are out of their calibration / training range, identifying locations where predictions are uncertain.
myBiomodProj
plot(myBiomodProj)`

**Comment by MayaGueguen** [comment]
Hello there,

By default, all projections are saved within one file, rather one file per projection.
If you want to change that, set `do.stack = FALSE` in [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function.

Here, you have : 

- `proj_Current1_ClampingMask` : the clamping mask (as you set `build.clamping.mask = TRUE`)
- `proj_Current1_Littorina.IM3` : all your projections in a stacked raster object
- `proj_Current1_Littorina.IM3_ROCbin` : all your projections transformed in binary values according to the ROC metric
- `proj_Current1_Littorina.IM3_TSSbin` : all your projections transformed in binary values according to the TSS metric

Hope it helps,
Maya

**Comment by Data-Madman** [comment]
@MayaGueguen 
Thank you so much for such a clear and timely response! I got a lot from it！
I still have a question, since R language is not my usual software, I wonder if the pdf file of the raster plotted using plot will necessarily undergo resolution changes? Since the intertidal zone is supposed to be narrow, the resolution change would be troublesome for me.
Thanks，
Linxuan

**Comment by MayaGueguen** [comment]
Hello Linxuan,

Ah, yes, if you visualize it within a pdf file, you might see some differences in terms of resolution, but they will be due to graphic rendering and choice of file size. Maybe indeed you will have a better view through ArcGIS ?

Maya

**Comment by rpatin** [comment]
Hello Linxuan, Maya,
Just a quick note, you have an argument `maxcell` that you can give to the `plot` method for `BIOMOD.proj.out` object (output of `BIOMOD_Projection()` for instance) that is transmitted to `terra::plot` and change the resolution of the raster plot. Default value is `5e5` so you can set it to higher value if you want a finer resolution map.
So you would do instead:
```
plot(myBiomodProj, maxcell = 1e7) # or try higher value for maxcell if need be
```

Rémi

**Comment by Data-Madman** [comment]
Hello Maya, Rémi,
Thank you very much. I tried the code and found that the results did not change. I will try again to solve the problem.
Thanks again！
