### ISSUE TITLE
Current VS Future

### ISSUE THREAD

**Issue by xiadawei123** [biomodhub/biomod2#359]
Hi 

 I have successfully used "Biomod2" to complete SDM analysis of the target species. I have a question for you about the fitness index measurement. In the current outcome, the fitness index is 0 to 1000, but in the future, the fitness index is 0 to 300. Can I make a direct comparison or do I need additional standardization? If so, can you tell me how to set it. Thank you!

**Comment by xiadawei123** [comment]
for example:
![image](https://github.com/biomodhub/biomod2/assets/148743500/e4d4e53a-73af-49c2-b99c-d8fd62811752)

**Comment by MayaGueguen** [comment]
Hello there,

Probability of presence outputs are by default on a `0` to `1000` scale.
So it is comparable between predictions and if you get values within a smaller range, it simply means that the conditions you are projecting onto are not favorable to your species.

However, on the plot you sent, you seem to have two models, and I'm guessing : 

- `fut_ca` corresponds to Communittee averaging model
- `fut_cv` corresponds to Coefficient of variation

right ?

If it is so, then be aware that outputs of Coefficient of variation do not correspond to probability of presence, but to... coefficient of variation values. As mentioned in issue #345, it is the ratio between standard deviation and mean, so it is a dimensionless number and it represents an estimation of how much there is variability around the mean value. Meaning in this context : the closer to 0, the more the models agree between them. The higher, the more they diverge (the more dispersion there is around the mean probability of presence across models). It is multiplied by 100, to be presented as a kind of percentage.

Hope it helps,

Maya

**Comment by xiadawei123** [comment]
> Hello there,
> 
> Probability of presence outputs are by default on a `0` to `1000` scale. So it is comparable between predictions and if you get values within a smaller range, it simply means that the conditions you are projecting onto are not favorable to your species.
> 
> However, on the plot you sent, you seem to have two models, and I'm guessing :
> 
> * `fut_ca` corresponds to Communittee averaging model
> * `fut_cv` corresponds to Coefficient of variation
> 
> right ?
> 
> If it is so, then be aware that outputs of Coefficient of variation do not correspond to probability of presence, but to... coefficient of variation values. As mentioned in issue #345, it is the ratio between standard deviation and mean, so it is a dimensionless number and it represents an estimation of how much there is variability around the mean value. Meaning in this context : the closer to 0, the more the models agree between them. The higher, the more they diverge (the more dispersion there is around the mean probability of presence across models). It is multiplied by 100, to be presented as a kind of percentage.
> 
> Hope it helps,
> 
> Maya

Hi Maya

Thank you very much for your timely reply. In the integrated way of ca, I can directly compare the fitness index between the present and the future, and cv stands for the coefficient of variation. Thanks again, have a nice day!
