### ISSUE TITLE
Trouble using categorical explanatory variable

### ISSUE THREAD

**Issue by merijnvdb** [biomodhub/biomod2#36]
I am trying to use Biomod2 to model and project distributions of a species using presences, pseudo-absences, and 7 explanatory variables of which one is a categorical variable (landcover)

My Formating is going fine, 

problems start when I start Modeling:

BIOMOD_Modeling (using   ' models = c('GLM','GBM','GAM','CTA','ANN','SRE','FDA','RF','MAXENT.Phillips')  ',
works well except for that in the output everything related to 'SRE' fails to be included? It is dropped despite the absence of warnings or errors.

Furthermore, when projecting I run into an error I have seen others have had, but I cannot find a solution:
'Projecting Wolf_PA1_Full_CTA ...Error: variable 'Landcover_Final' was fitted with type "factor" but type "numeric" was supplied
In addition: Warning message:
In model.frame.default(Terms, newdata, na.action = na.action, xlev = attr(object,  :
  variable 'Landcover_Final' is not a factor' 

This is surprising, as after I load my rasters into R, I use the ratify() function on the raster of this variable. Both the View(raster) as well as is.raster(raster) give me the impression that this works? Of course, the values of the raster are still technically numerical, (1,2,3 and 4),  as I have not found a way to change the values of a raster in anything but numbers...

**Comment by MayaGueguen** [comment]
Hi there,

Could you try installing the last development version of biomod2 :
`devtools::install_github("biomodhub/biomod2", dependencies = TRUE)`

and testing again your code to see if the projection error is removed ?

As for SRE, it does not work with categorical variable, that must be why it has been removed, but you're right, we should add a warning message to inform the user about that.

Maya
