### ISSUE TITLE
Error in BIOMOD_Modeling - c("GBM", "GLM" ...)

### ISSUE THREAD

**Issue by woojunbang** [biomodhub/biomod2#363]
Hello! 

I'm beginner about this program and also user for R.
I tried to practice the SDM by using this tutorial: 
https://pedrohbraga.github.io/SpeciesDistribModelling-in-R-Workshop/sdm_workshop.html#data-preparation

and I got a error message about biomod modelling option when I using the R (Rstudio)!

I type like this:

myBiomodModelOut <- BIOMOD_Modeling(
    data = myBiomodData,
    models = c('GBM', 'GLM', 'RF', 'MAXENT.Phillips'),
    models.options = myBiomodOption,
    NbRunEval = 3,
    DataSplit = 70,
    Prevalence = 0.5,
    VarImport = 5,
    models.eval.meth = c('TSS', 'ROC'),
    SaveObj = TRUE,
    rescal.all.models = FALSE,
    do.full.models = FALSE,
    modeling.id = paste(myRespName, "CurrentClim", sep="")
)

then got this message from the code:

BIOMOD_Modeling(data = myBiomodData, models = c("GBM", "GLM", 에서 다음과 같은 에러가 발생했습니다:
  argument 1 matches multiple formal arguments

translate it as english:

Error in BIOMOD_Modeling(myBiomodData, models = c("GLM", "GAM", ... argument 1 matches multiple formal arguments.

How to fix it?

The whole type like this:

myResp <- read.table("data/matrices/NT_PAM_5.txt", header = TRUE)
myExpl <- read.table("data/matrices/NT_EnvVar_5.txt", header = TRUE)

myResp <- read.table("data/matrices/NT_PAM_5.txt", header = TRUE)
myExpl <- read.table("data/matrices/NT_EnvVar_5.txt", header = TRUE)
myRespName <- names(myResp)[1]
myRespCoord <- read.table("data/matrices/NT_coords_5.txt", header = TRUE)

myBiomodData <- BIOMOD_FormatingData(resp.var = as.data.frame(myResp[,myRespName]),
                                     expl.var = myExpl,
                                     resp.xy = as.data.frame(myRespCoord),
                                     resp.name = myRespName,
                                     #PA.nb.rep = 2,
                                     #PA.nb.absences = 200,
                                     #PA.strategy = 'random',
                                     na.rm = TRUE)

myBiomodOption <- BIOMOD_ModelingOptions()

myBiomodModelOut <- BIOMOD_Modeling(
    data = myBiomodData,
    models = c('GBM', 'GLM', 'RF', 'MAXENT.Phillips'),
    models.options = myBiomodOption,
    NbRunEval = 3,
    DataSplit = 70,
    Prevalence = 0.5,
    VarImport = 5,
    models.eval.meth = c('TSS', 'ROC'),
    SaveObj = TRUE,
    rescal.all.models = FALSE,
    do.full.models = FALSE,
    modeling.id = paste(myRespName, "CurrentClim", sep="")
)

Thank you very much for your help.

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for posting and welcome into `biomod2` community ! :wave: 

`biomod2` has changed and improved a lot lately, so it seems that the example your following is not up-to-date.
Parameter names in [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function for example have changed.

I strongly advise you to check that you have the `4.2-4` version installed from CRAN (you can check that with the command `packageVersion('biomod2')`), and to check for [examples here](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) onto our [documentation website](https://biomodhub.github.io/biomod2/index.html) :slightly_smiling_face: 

Once you had a look, do not hesitate to come back if you still have questions / problems !

Maya
