### ISSUE TITLE
Help with BIOMOD_Modelling: How use models.pa argument

### ISSUE THREAD

**Issue by NadiaVic** [biomodhub/biomod2#365]
Hi, I am trying to use the models.pa parameter in the BIOMOD_Modeling function, but I do not know how write the list, and indicate which list is for each model.

Error in .fun_testIfInherits(TRUE, "models.pa", models.pa, "list") :
models.pa must be a 'list' object

I want to use for three algoritms (GLM; RF and Maxent),different PA sets. For example, with GLM and Maxent ten sets of 10000 PA, and with RF 10 sets of 150.
Accordingly to the documentation "models.pa (optional, default NULL)
A list containing for each model a vector defining which pseudo-absence datasets are to be used, must be among colnames (bm.format@PA.table).

I wrote this in the formating data:

Cmac_dataPA <-
BIOMOD_FormatingData(
resp.var = Cmac_occ["C_maculatus"],
resp.xy = Cmac_occ[, c("Longitude", "Latitude")],
expl.var = bioc2,
resp.name = "C_maculatus",
PA.nb.rep = 20,
PA.nb.absences = c(10000,10000, 10000,10000,10000, 10000,10000,10000, 10000,10000,150, 150,
150, 150, 150, 150, 150, 150, 150, 150),
PA.strategy = 'random',
filter.raster=TRUE
)

But I do not know how write the models.pa argument in the BIOMOD_Modelling:

C_macGLMAx<-BIOMOD_Modeling(bm.format = Cmac_data,
                bm.options = Cmac_opt,
                modeling.id = 'AllModels',
                models=c("GLM", "MAXENT", "RF"),
                CV.strategy = 'random',  
                CV.nb.rep = 10,
                CV.perc = 0.8,
                var.import = 3,
                metric.eval = c("KAPPA", "TSS","ROC"))
models.pa=??

Thanks in advance!

**Comment by MayaGueguen** [comment]
Hello Nadia,

Thank you so much for reposting here 🙏 🌞 

Yes, I realized lately that this is part is missing a bit of documentation on the website and within the help function... I'll try to remediate to that. Sorry for the lack of information.

You did great for the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) part.
The `models.pa` parameter within the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function should work this way in your case : 
```
Cmac_dataPA <- BIOMOD_FormatingData(
                     resp.var = Cmac_occ["C_maculatus"],
                     resp.xy = Cmac_occ[, c("Longitude", "Latitude")],
                     expl.var = bioc2,
                     resp.name = "C_maculatus",
                     PA.nb.rep = 20,
                     PA.nb.absences = c(10000,10000, 10000,10000,10000, 10000,10000,10000, 10000,10000,
                          150, 150, 150, 150, 150, 150, 150, 150, 150, 150),
                     PA.strategy = 'random',
                     filter.raster=TRUE
)

C_macGLMAx <- BIOMOD_Modeling(
                     bm.format = Cmac_data,
                     bm.options = Cmac_opt,
                     modeling.id = 'AllModels',
                     models = c("GLM", "MAXENT", "RF"),
                     CV.strategy = 'random',
                     CV.nb.rep = 10,
                     CV.perc = 0.8,
                     var.import = 3,
                     metric.eval = c("KAPPA", "TSS","ROC")
                     models.pa = list(GLM = paste0("PA", 1:10),
                         MAXENT = paste0("PA", 1:10),
                         RF = paste0("PA", 11:20))
)
````

Please, do not hesitate if you encounter other questions or problems !
Maya

**Comment by NadiaVic** [comment]
Thanks!!!!!!
This works!!!!
