### ISSUE TITLE
Error in BIOMOD_ModelingOptions - [>could not find function "BIOMOD_ModelingOptions"<]

### ISSUE THREAD

**Issue by ddreza** [biomodhub/biomod2#370]
Hi guys, I'm having this problem with a function in the 'biomod2' package. I already have 'biomod2' installed, and I can run any other commands and functions from 'biomod2,' except for this specific one. Could someone help me?

"
> bm.opt <- BIOMOD_ModelingOptions(GAM = list(k = 10),
+                                  MAXENT = list(path_to_maxent.jar = path.to.maxent.jar,
+                                                background_data_dir = maxent.background.dat.dir,
+                                                maximumbackground = 200))
Error in BIOMOD_ModelingOptions(GAM = list(k = 10), MAXENT = list(path_to_maxent.jar = path.to.maxent.jar,  : 
  could not find function "BIOMOD_ModelingOptions"

"

**Comment by MayaGueguen** [comment]
Hello there,

It seems that you switched from `4.2-4` (or previous) biomod2 version to `4.2-5` github version. Thanks for trying ! :pray: :heart: 

As mentioned onto the [documentation website](https://biomodhub.github.io/biomod2/index.html), `4.2-5` version changes the way to deal with modeling options : 
- `BIOMOD_ModelingOptions` function turned into [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html)
- modeling options are now automatically retrieved from single models functions, normally allowing the use of all arguments taken into account by these functions
- and modeling options can be directly built through [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function and `OPT.[...]` parameters

I show here in this issue https://github.com/biomodhub/biomod2/issues/340#issuecomment-1750172552 an example to use these new settings of modeling options, with 2 specific cases, whether you want only to use predefined options, or if you want to modify some like in your case.

I'll try to add more examples online for these new functions behaviour.

Please do not hesitate if you have further questions :eyes: 

Maya
