### ISSUE TITLE
Help with BIOMOD_Ensemble Modeling- [Why algorithms below the metric.select.thresh vabue included for ensemble?? 

### ISSUE THREAD

**Issue by mula-jpg** [biomodhub/biomod2#375]
**Context and question**
Dear biomod2 developers,
I used default metric. select. dataset (validation) in BIOMOD_EnsemblingModeling. The evaluation metric is also TSS with its threshold 0.8. The TSS value of each algorithm is below this threshold. So, I expect to fail all algorithms to run and give output. Why?? Could you show me my fault.

**Code used**
Mymodel<-BIOMOD_Modeling(
  bm.format= myBiomodData,
  modeling.id = "allmdel1",
  models = c("GLM", "GBM", "GAM", "CTA", "MARS","RF", "MAXNET"),
  models.pa = NULL,
  bm.options = Mymodeling_Opt,
  CV.strategy = "random",
  CV.nb.rep = 3,
  CV.perc = 0.70,
  CV.k = NULL,
  CV.balance = NULL,
  CV.env.var = NULL,
  CV.strat = NULL,
  CV.user.table = NULL,
  CV.do.full.models = FALSE,
  weights = NULL,
  prevalence = 0.5,
  metric.eval = c("TSS", "ROC"),
  var.import = 3,
  scale.models = FALSE,
  nb.cpu = 0,
  seed.val = NULL,
  do.progress = TRUE)
```
bm_PlotEvalMean(
    bm.out=Mymodel,
    metric.eval = c("TSS", "ROC"),
    dataset = "validation",
    group.by = "algo",
    do.plot = TRUE,
  xlim= c(0.5, 1),
  ylim= c(0.5, 1))
$tab
    name     ROC     TSS                          sd1                sd2
1    CTA 0.8910000     0.7676667         0.018083141 0.03868247
2    GAM 0.9063333   0.7520000        0.066935292     0.10808793
3    GBM 0.9580000    0.7010000        0.001000000  0.06114736
4    GLM 0.9090000    0.7316667        0.063929649 0.11411544
5   MARS 0.9310000   0.7546667        0.035538711 0.04562163
6 MAXNET 0.9583333  0.7873333       0.016010413 0.03894012
7     RF 0.8880000       0.7386667        0.005196152 0.01078579

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = Mymodel,
                                       models.chosen = 'all',
                                       em.by = 'all',
                                       em.algo = c('EMmean','EMca', 'EMwmean'),
                                       metric.select = c('TSS'),
                                       metric.select.thresh = c(0.8),
                                       metric.eval = 'TSS',
                                       var.import = 3,
                                       EMci.alpha = 0.05,
                                       EMwmean.decay = 'proportional')
myBiomodEM

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
  ! Ensemble Models will be filtered and/or weighted using validation dataset (if possible). Please use `metric.select.dataset` for alternative options.
   > Evaluation & Weighting methods summary :
      TSS over 0.8


  > mergedData_mergedRun_mergedAlgo ensemble modeling
   > Mean of probabilities by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 

  |==============================================================================================| 100%

   > Committee averaging by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 

  |==============================================================================================| 100%

		  original models scores =  0.802 0.839 0.803 0.804 0.816
		  final models weights =  0.197 0.206 0.198 0.198 0.201
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 

  |==============================================================================================| 100%

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> # Get evaluation scores & variables importance
>  Geteva<- get_evaluations(myBiomodEM)
>  Geteva
                                                full.name merged.by.PA merged.by.run merged.by.algo
1  myRespName_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
2  myRespName_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
3    myRespName_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
4    myRespName_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
5 myRespName_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
6 myRespName_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo
  filtered.by    algo metric.eval cutoff sensitivity specificity calibration validation evaluation
1         TSS  EMmean         TSS  221.0      95.312       91.63       0.870         NA         NA
2         TSS  EMmean         ROC  228.5      95.312       91.86       0.979         NA         NA
3         TSS    EMca         TSS  500.0      93.750       92.41       0.862         NA         NA
4         TSS    EMca         ROC  500.0      93.750       92.41       0.965         NA         NA
5         TSS EMwmean         TSS  221.0      95.312       91.66       0.870         NA         NA
6         TSS EMwmean         ROC  226.0      95.312       91.78       0.979         NA         NA

**Comment by MayaGueguen** [comment]
Hello,

I'm not sure we fully understand each other here, so to be sure we are on the same page, I try back to the beginning :sun_with_face: 
Please tell me if I'm mistaken somewhere.

- There is the `metric.select.dataset` parameter within the [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function you can use, that can be either `calibration`, `validation` or `evaluation`. It will define which evaluation metric values will be used to select single models that will be effectively taken into account to build ensemble models.

- In your case, you would to keep single models with TSS > 0.8 for the validation datasets, right ?

- You can check these values with the command : `get_evaluations(Mymodel)` and see if you have values > 0.8 within the `validation` column.


Is this clearer that way ?

Maya

**Comment by mula-jpg** [comment]
Dear Maya,
Sorry for late response. You are right. In get_evaluations(Mymodel) all values are NA within the validation column. My confusion was why the ensemble model included the  algorithms with the TSS values < 0.8 in validation dataset because the default ensemble modeling accept the validation dataset. After a while, I understand that It run by considering the calibration dataset b/c I set **em.by = 'all'** (no validation dataset). Is my understanding right??
Best regards
Mulatu

**Comment by MayaGueguen** [comment]
Dear Mulatu,

Thank you for your patience :pray: 

Could you show me the output of : 
- `get_evaluations(Mymodel)`
- `get_kept_models(myBiomodEM)`
so I can better understand which models are selected or not ?

Maya

**Comment by mula-jpg** [comment]
Dear Maya,
When I run models to show what you want, I got strange things in BIOMOD_EnsemblingModeling.  It failed now rather than run (It come back to what I expect in the first trail). I did not request help if it failed in the first trail. But in my previous trials, it run (**you can see in my first post**).    I confused!. Why previously run but now failed. I did not change any parameter.
> getevalu<-get_evaluations(Mymodel)
> getevalu
                    full.name  PA  run   algo metric.eval cutoff sensitivity specificity
1     myRespName_PA1_RUN1_GLM PA1 RUN1    GLM         TSS  495.0      98.148      95.328
2     myRespName_PA1_RUN1_GLM PA1 RUN1    GLM         ROC  496.5      98.148      95.385
3     myRespName_PA1_RUN1_GBM PA1 RUN1    GBM         TSS  439.0     100.000      97.328
4     myRespName_PA1_RUN1_GBM PA1 RUN1    GBM         ROC  441.0     100.000      97.342
5     myRespName_PA1_RUN1_GAM PA1 RUN1    GAM         TSS  515.0      94.444      94.556
6     myRespName_PA1_RUN1_GAM PA1 RUN1    GAM         ROC  521.5      94.444      94.642
7     myRespName_PA1_RUN1_CTA PA1 RUN1    CTA         TSS  441.0      88.889      93.871
8     myRespName_PA1_RUN1_CTA PA1 RUN1    CTA         ROC  441.5      88.889      93.871
9     myRespName_PA1_RUN1_ANN PA1 RUN1    ANN         TSS  767.0      94.444      94.928
10    myRespName_PA1_RUN1_ANN PA1 RUN1    ANN         ROC  767.5      94.444      94.956
11    myRespName_PA1_RUN1_FDA PA1 RUN1    FDA         TSS  342.0      92.593      88.284
12    myRespName_PA1_RUN1_FDA PA1 RUN1    FDA         ROC  343.5      92.593      88.856
13   myRespName_PA1_RUN1_MARS PA1 RUN1   MARS         TSS  404.0      98.148      93.299
14   myRespName_PA1_RUN1_MARS PA1 RUN1   MARS         ROC  413.5      98.148      93.513
15     myRespName_PA1_RUN1_RF PA1 RUN1     RF         TSS    0.0     100.000       0.000
16     myRespName_PA1_RUN1_RF PA1 RUN1     RF         ROC    1.0      96.296      94.928
17 myRespName_PA1_RUN1_MAXNET PA1 RUN1 MAXNET         TSS  155.0      92.593      94.814
18 myRespName_PA1_RUN1_MAXNET PA1 RUN1 MAXNET         ROC  155.5      92.593      94.856
19    myRespName_PA1_RUN2_GLM PA1 RUN2    GLM         TSS  444.0      98.077      94.814
20    myRespName_PA1_RUN2_GLM PA1 RUN2    GLM         ROC  451.5      98.077      94.871
21    myRespName_PA1_RUN2_GBM PA1 RUN2    GBM         TSS  393.0     100.000      96.357
22    myRespName_PA1_RUN2_GBM PA1 RUN2    GBM         ROC  396.5     100.000      96.371
23    myRespName_PA1_RUN2_GAM PA1 RUN2    GAM         TSS  545.0      92.308      94.700
24    myRespName_PA1_RUN2_GAM PA1 RUN2    GAM         ROC  552.5      92.308      94.814
25    myRespName_PA1_RUN2_CTA PA1 RUN2    CTA         TSS  446.5      92.308      94.243
26    myRespName_PA1_RUN2_CTA PA1 RUN2    CTA         ROC  449.0      92.308      94.243
27    myRespName_PA1_RUN2_ANN PA1 RUN2    ANN         TSS  883.0      90.385      95.757
28    myRespName_PA1_RUN2_ANN PA1 RUN2    ANN         ROC  883.5      90.385      95.771
29    myRespName_PA1_RUN2_FDA PA1 RUN2    FDA         TSS  332.0      88.462      93.086
30    myRespName_PA1_RUN2_FDA PA1 RUN2    FDA         ROC  334.5      88.462      93.271
31   myRespName_PA1_RUN2_MARS PA1 RUN2   MARS         TSS  293.0      98.077      92.100
32   myRespName_PA1_RUN2_MARS PA1 RUN2   MARS         ROC  298.5      98.077      92.271
33     myRespName_PA1_RUN2_RF PA1 RUN2     RF         TSS    0.0     100.000       0.000
34     myRespName_PA1_RUN2_RF PA1 RUN2     RF         ROC    1.0      96.154      94.800
35 myRespName_PA1_RUN2_MAXNET PA1 RUN2 MAXNET         TSS  198.0      90.385      96.014
36 myRespName_PA1_RUN2_MAXNET PA1 RUN2 MAXNET         ROC  199.5      90.385      96.071
37    myRespName_PA1_RUN3_GLM PA1 RUN3    GLM         TSS  535.0     100.000      96.670
38    myRespName_PA1_RUN3_GLM PA1 RUN3    GLM         ROC  542.5     100.000      96.713
39    myRespName_PA1_RUN3_GBM PA1 RUN3    GBM         TSS  351.0     100.000      96.985
40    myRespName_PA1_RUN3_GBM PA1 RUN3    GBM         ROC  358.0     100.000      97.028
41    myRespName_PA1_RUN3_GAM PA1 RUN3    GAM         TSS  535.0      96.296      95.456
42    myRespName_PA1_RUN3_GAM PA1 RUN3    GAM         ROC  536.5      96.296      95.470
43    myRespName_PA1_RUN3_CTA PA1 RUN3    CTA         TSS  491.0      87.037      95.099
44    myRespName_PA1_RUN3_CTA PA1 RUN3    CTA         ROC  495.0      87.037      95.099
45    myRespName_PA1_RUN3_ANN PA1 RUN3    ANN         TSS  908.0      90.741      97.199
46    myRespName_PA1_RUN3_ANN PA1 RUN3    ANN         ROC  907.0      90.741      97.199
47    myRespName_PA1_RUN3_FDA PA1 RUN3    FDA         TSS  319.0      94.444      91.855
48    myRespName_PA1_RUN3_FDA PA1 RUN3    FDA         ROC  316.5      96.296      91.412
49   myRespName_PA1_RUN3_MARS PA1 RUN3   MARS         TSS  303.0     100.000      93.984
50   myRespName_PA1_RUN3_MARS PA1 RUN3   MARS         ROC  309.5     100.000      94.027
51     myRespName_PA1_RUN3_RF PA1 RUN3     RF         TSS    0.0     100.000       0.000
52     myRespName_PA1_RUN3_RF PA1 RUN3     RF         ROC    3.0     100.000      96.985
53 myRespName_PA1_RUN3_MAXNET PA1 RUN3 MAXNET         TSS   72.0      98.148      93.841
54 myRespName_PA1_RUN3_MAXNET PA1 RUN3 MAXNET         ROC   74.5      98.148      93.984
   calibration validation evaluation
1        0.935      0.712         NA
2        0.987      0.932         NA
3        0.973      0.661         NA
4        0.995      0.957         NA
5        0.890      0.666         NA
6        0.979      0.923         NA
7        0.828      0.775         NA
8        0.917      0.891         NA
9        0.894      0.676         NA
10       0.965      0.882         NA
11       0.812      0.730         NA
12       0.948      0.935         NA
13       0.915      0.740         NA
14       0.982      0.955         NA
15       0.912      0.624         NA
16       0.974      0.826         NA
17       0.874      0.753         NA
18       0.980      0.956         NA
19       0.929      0.648         NA
20       0.986      0.843         NA
21       0.964      0.653         NA
22       0.992      0.950         NA
23       0.870      0.636         NA
24       0.978      0.820         NA
25       0.866      0.733         NA
26       0.934      0.844         NA
27       0.862      0.655         NA
28       0.958      0.924         NA
29       0.816      0.735         NA
30       0.939      0.880         NA
31       0.902      0.751         NA
32       0.979      0.953         NA
33       0.910      0.652         NA
34       0.974      0.844         NA
35       0.865      0.647         NA
36       0.980      0.937         NA
37       0.967      0.580         NA
38       0.991      0.894         NA
39       0.970      0.605         NA
40       0.995      0.875         NA
41       0.918      0.652         NA
42       0.987      0.912         NA
43       0.821      0.672         NA
44       0.911      0.836         NA
45       0.879      0.516         NA
46       0.937      0.764         NA
47       0.865      0.697         NA
48       0.976      0.888         NA
49       0.940      0.732         NA
50       0.987      0.929         NA
51       0.944      0.649         NA
52       0.995      0.839         NA
53       0.920      0.759         NA

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = Mymodel,
+                                        models.chosen = 'all',
+                                        em.by = 'all',
+                                        em.algo = c('EMwmean','EMca'),
+                                        metric.select = c('TSS'),
+                                        metric.select.thresh = c(0.8),
+                                        metric.eval = c('ROC','TSS'),
+                                        var.import = 3,
+                                        EMci.alpha = 0.05,
+                                        EMwmean.decay = 'proportional')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
  ! Ensemble Models will be filtered and/or weighted using validation dataset (if possible). Please use `metric.select.dataset` for alternative options.
   > Evaluation & Weighting methods summary :
      TSS over 0.8


     !! Ensemble Model mergedData_mergedRun_mergedAlgo selected by TSS have no model selected and will fail.
     !! Please make sure this is intended or review your selection metrics and threshold.

  > mergedData_mergedRun_mergedAlgo ensemble modeling
   ! No models kept due to threshold filtering... Ensemble Modeling will fail!
   ! Note :  myRespName_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo failed!

   ! Note :  myRespName_EMcaByTSS_mergedData_mergedRun_mergedAlgo failed!

! All models failed

**Comment by MayaGueguen** [comment]
Dear Mulatu,

No worries :slightly_smiling_face: 
I just wanted to be sure of what is happening, and to be sure that we understand each other :eyes: 
So indeed, it seems to be working as it should now, not finding and selecting single models with `TSS > 0.8` within the `validation` results.

Maybe you had some files that were mixed together within the folder ?

Maya
