### ISSUE TITLE
Error in BIOMOD.formated.data [I am tring to run the code for mutiple spcies and get this erro 'checkForRemoteErrors(val)']

### ISSUE THREAD

**Issue by evertonmaciel** [biomodhub/biomod2#376]
## load the required packages
 library(biomod2)
 library(raster)
 library(rasterVis)
 library(gridExtra)
 library(reshape2)
 library(snowfall)
 library(snow)
 
 
 ## read data ----
 ## species occurences data
 data <- read.csv('savanas_neotrop.csv', stringsAsFactors = FALSE)
 head(data)
              species     long     lat
1 Abarema.barbouriana -58.8256  7.2681
2 Abarema.barbouriana -70.3186 -3.5361
3 Abarema.barbouriana -60.2278 -2.5233
4 Abarema.barbouriana -69.9303  0.9656
5 Abarema.barbouriana -50.9264  2.4322
6 Abarema.barbouriana -63.4114  5.3181
 table(data$species)

Abarema.barbouriana  Abarema.campestris   Abarema.cochleata 
                 85                  19                  57 
 spp_to_model <- unique(data$species)
 
 ## curent climatic variables
 stk_current <- 
   raster::stack(
     c(
       bio_1 =  "wc2.1_5m_prec_01.tif",
       bio_12 = "wc2.1_5m_tmax_01.tif",
       bio_8 =  "wc2.1_5m_tmin_01.tif"
     ),
     RAT = FALSE
   )
 
 
 ## build species modelling wrapper ----
 biomod2_wrapper <- function(sp){
   cat("\n> species : ", sp)
   
   ## get occurrences points
   sp_dat <- data[data$species == sp, ]
   
   ## formating the data
   sp_format <- 
     BIOMOD.formated.data(
       resp.var = rep(1, nrow(sp_dat)), 
       expl.var = stk_current,
       resp.xy = sp_dat[, c("long", "lat")],
      resp.name = sp,
       PA.strategy = "random", 
       PA.nb.rep = 1, 
       PA.nb.absences = 1000
     )
   
 
   ## define models options
   myBiomodData_sp_opt <- BIOMOD_ModelingOptions()
   
   myBiomodModelOut_Wa_communis <- BIOMOD_Modeling(bm.format=myBiomodData_sp_opt,
                                                   models = c('MAXNET'),
                                                   bm.options = sp_opt, 
                                                   nb.rep = 10,
                                                   data.split.perc = 80,
                                                   prevalence = 0.5,
                                                   metric.eval = c('TSS','ROC'),
                                                   save.output = T,
                                                   do.full.models = F,
                                                   modeling.id = "demo2"
   )

 
   
   ## build ensemble models
   sp_ens_model <- 
     BIOMOD_EnsembleModeling(
       modeling.output = sp_model,
       em.by = 'all',
       eval.metric = 'TSS',
       eval.metric.quality.threshold = 0.4,
       models.eval.meth = c('TSS','ROC'),
       prob.mean = FALSE,
      prob.mean.weight = TRUE,
      VarImport = 0
     )
   
   ## do projections
   proj_scen <- c("current")
   
   for(scen in proj_scen){
     cat("\n> projections of ", scen)
     
     ## single model projections
     sp_proj <- 
       BIOMOD_Projection(
         modeling.output = sp_model,
         new.env = get(paste0("stk_", scen)),
         proj.name = scen,
         selected.models = 'all',
         binary.meth = "TSS",
         filtered.meth = NULL,
         compress = TRUE,
         build.clamping.mask = FALSE,
         do.stack = FALSE,
         output.format = ".img"
       )
     
     ## ensemble model projections
     sp_ens_proj <- 
       BIOMOD_EnsembleForecasting(
         EM.output = sp_ens_model,
         projection.output = sp_proj,
         binary.meth = "TSS",
         compress = TRUE,
         do.stack = FALSE,
         output.format = ".img"
       )
   }
   
   return(paste0(sp," modelling completed !"))
 }
 
 
## launch the species modelling wrapper over species list ----
 if(require(snowfall)){ 
 ## start the cluster
 sfInit(parallel = TRUE, cpus = 4) 
sfExportAll()
sfLibrary(biomod2)
## launch our wrapper in parallel
 sf_out <- sfLapply(spp_to_model, biomod2_wrapper)
 ## stop the cluster
 sfStop()
} else { ## sequencial computation
 for (sp in spp_to_model){
 biomod2_wrapper(sp)
}
}
Explicit sfStop() is missing: stop now.

Stopping cluster

snowfall 1.84-6.2 initialized (using snow 0.4-4): parallel execution on 4 CPUs.

Library biomod2 loaded.
Library biomod2 loaded in cluster.

Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: unable to find an inherited method for function 'BIOMOD.formated.data' for signature '"missing", "missing"'

**Comment by MayaGueguen** [comment]
Hello there,

Could you share the output of the `sessionInfo()` command please ?
I'm not sure you are using the last version of the package available on CRAN.
It is the 4.2-4 version, you can install it with `install.packages('biomod2')`.

As for your error, you run a wrapper of functions within a loop over species within a parallelisation loop.
So it is complicated for me to know at which step your error occurr.

Could you :
- please be sure to have the last version of biomod2 installed 
- if the error still occurs, try to run, one species at a time, each function of your wrapper, to identify within each function the error is
?

Thanks in advance, 
Maya

**Comment by MayaGueguen** [comment]
Hello Maciel,

Thank you for updating :pray: 
It will definitely help us to be of more help to you :slightly_smiling_face: 

As for your error, you are still runinng your code in parallel on a loop of species for a bunch of functions, so it is hard for me to see from where it is coming.

Could you please try running your code without `SnowFall` parallelisation, for one species, and one function at a time please ?
For example : 
```
library(biomod2)
library(raster)
library(rasterVis)
library(gridExtra)
library(reshape2)
library(snowfall)
library(snow)

## species occurences data
data <- read.csv('savanas_neotrop.csv', stringsAsFactors = FALSE)
spp_to_model <- unique(data$species)

## curent climatic variables
stk_current <- raster::stack(c(bio_1 = "wc2.1_5m_prec_01.tif",
                               bio_12 = "wc2.1_5m_tmax_01.tif",
                               bio_8 = "wc2.1_5m_tmin_01.tif"),
                              RAT = FALSE)

## RUNNING FOR FIRST SPECIES : 
sp = spp_to_model[1]
cat("\n> species : ", sp)

## get occurrences points
sp_dat <- data[data$species == sp, ]

## THEN ALL YOUR STEPS
## formating
## modeling
## projection 
...
```

:warning: NOTE that a lot of parameter names and functions changed in the last version so you might have to adapt some parts of your code. [Documentation website](https://biomodhub.github.io/biomod2/index.html) with all information for each function and examples is up-to-date.
Do not hesitate if you have questions.

Maya
