### ISSUE TITLE
How to install the ggbiplot in r 4.2.3

### ISSUE THREAD

**Issue by Ahmed4378** [biomodhub/biomod2#379]
How to install the ggbiplot in the r 4.2.3 I faced error please

**Comment by MayaGueguen** [comment]
Hello Ahmed,

Here it is a forum for the `biomod2` package.
You can refer to the [ggbiplot github page](https://github.com/vqv/ggbiplot).

It seems that you can install it with :
```
library(devtools)
install_github("vqv/ggbiplot")
```

Maya
