### ISSUE TITLE
Question about binary maps ensemble_TSSbin.tif

### ISSUE THREAD

**Issue by Lisa-Tedeschi** [biomodhub/biomod2#384]
I have a very quick question, just to be sure I'm understanding things here. In the function `BIOMOD_EnsembleForecasting()`, I specified TSS as a `metric.binary`, like this.

```
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             bm.proj = myBiomodProj,
                                             proj.name = "CurrentEM",
                                             models.chosen = "all",
                                             metric.binary = c("TSS"),
                                             metric.filter = c("TSS"))
```

So as far as I understand, each species' ensemble model should be binarized based on a threshold provided by the species' model TSS. And the output should be a raster called `proj_CurrentEM_nameofspecies_ensemble_TSSbin.tif` in my folder nameofspecies > proj_CurrentEM , right? With 0 as unsuitable cells (based on the TSS threshold) and 1 as suitable cells.
I'm using biomod2 v.4.2-4.

**Comment by mula-jpg** [comment]
Dear Lisa,
The output is a continuous habitat suitability index in terms of pixel. After export to Arc GIS you can do binary using the cutoff threshold value given with TSS in get_evaluation output.
Best wishes
Muatu

**Comment by MayaGueguen** [comment]
Dear Lisa,

Yes, you understand it right :slightly_smiling_face: 
Do not hesitate if you need some more clarifications.

Maya
