### ISSUE TITLE
What is difference # Project ensemble models (from single projections) vs # Project ensemble models (building single projections) ? 

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#385]
Dear helpful biomod2 people
Please may I ask what the difference is between these two modeling scripts.
Do we have to run both of them sequentially to create the ensemble model?   Or are they variants of the same approach?
The console script outputs seem to behave slightly differently.  

The following text is from the console after running the example scripts

<html>
<body>

# Project ensemble models (from single projections) > myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,  +                                              bm.proj = myBiomodProj, +                                              models.chosen = 'all', +                                              metric.binary = 'all', +                                              metric.filter = 'all')  -_

which then prints this 

_=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=  Creating suitable Workdir...  	> Projecting GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo ... 	> Projecting GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo ...  	> Building TSS binaries / filtered 	> Building ROC binaries / filtered  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-__

So at this stage I have a folder called proj_Current now containing projections  one of which is called proj_Current_GuloGulo_ensemble.tif

Is this the ensemble model?

Afterwards the example script then suggests to me to run as follows.

=-=-=-=-=-=-=-=-=-=-=-= > # Project ensemble models (building single projections) > myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, +                                              proj.name = 'CurrentEM', +                                              new.env = myExpl, +                                              models.chosen = 'all', +                                              metric.binary = 'all', +                                              metric.filter = 'all')  -

which then prints this  which is slightly different to before 

_=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=  Creating suitable Workdir...  -=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=  	> Projecting GuloGulo_allData_RUN1_RF ... 	> Projecting GuloGulo_allData_RUN1_GLM ... 	> Projecting GuloGulo_allData_RUN2_RF ... 	> Projecting GuloGulo_allData_RUN2_GLM ... -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  	> Projecting GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo ... 	> Projecting GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo ...  	> Building TSS binaries / filtered 	> Building ROC binaries / filtered  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
--_
 
> | >
>

</body>
</html>

And then it has created another folder called proj_CurrentEM which contains a file called proj_CurrentEM_GuloGulo_ensemble.tif 

Please is this the same thing or different.

Thank you.   I appreciate your help.  I am a BIG fan of biomod2.

**Comment by MayaGueguen** [comment]
Hello Carlos,

When you do ensemble projection, it means that it has to use single models (A) selected to build ensemble models (B), by making projections with A, and then combining these projections to obtain projections with B.
You can either do this first projection step independently with [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html), and then provide the results to the [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function : 
```
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodMod,
                                  proj.name = 'CurrentMod',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all')

myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             bm.proj = myBiomodProj,
                                             proj.name = 'CurrentEM1',
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
```
or you can do both steps within the [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function directly : 
```
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM2',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
```
In the first case, you will be able to access to single models projections, while in the second we will directly get projections for ensemble models.

The choice depends mainly on that :slightly_smiling_face: 

Maya

**Comment by carlosbedson** [comment]
Dear Maya, 
Thank you very much for taking the time to write this helpful clear explanation (and just at Christmas time) - much appreciated.
I now understand how these alternative routes to ensemble modelling work.
I have tested it out several times on different data sets and all is running smoothly.

For my current purpose I am not needing to review the single model projections.
My data set comprises 13 variable layers at small pixel scale and which total ~300MB  and then different species records number from about 6,000 to 12,000 presence points and then the same pseudo-absences.
When I run the first approach you describe: single model takes 30 minutes to process and then the ensemble takes 12 minutes.
When I run the second approach - straight to ensemble - it takes 30 minutes to process.   So that second approach presently is my preference; especially as I have many species to consider.   

Thank you again for your help.   I was introduced to biomod2 by Neftali Sillero.   He said it is a complex sophisticated package to learn; but to do so, provides great flexibility and thorough outputs.  He is right and I am always enjoying using biomod2.

With best wishes,   Carlos
