### ISSUE TITLE
Help with  - [can't load my data properly]

### ISSUE THREAD

**Issue by yasirdogan** [biomodhub/biomod2#386]
**Context and question**
I saved my environment as .RData file and I want to load my data but i think R doesn't load properly. I load my .RData file and sometimes i have to run codes and read bio datas manually again.

When i load my .Rdata file  I can view 'myBiomodModelOut' but when i want to do projection R can't find my saved output file 'myBiomodModelOut'. 

Error messsage: 'Error in .fun_testIfInherits(TRUE, "bm.mod", bm.mod, "BIOMOD.models.out") : 
  object 'myBiomodModelOut' not found'

**Code used**
setwd("/Users/yasirdogan/Desktop/R_wd/Modelling")
library(biomod2)
library(terra)
library(tidyterra)
library(ggtext)
library(ggplot2)

# load the data 
tree <- read.csv("tree.csv", header = TRUE )

# getting presence values from data
resp.name <- 'Abies_cilicica'
myResp.PA <- as.numeric(tree[,resp.name])

# getting presence coordinates fromd data
myRespXY <- tree[,c("lon", "lat")]
plot(myRespXY)

# environmental layers as explanatory variables
bio4 <- rast("/Users/yasirdogan/Desktop/R_wd/Modelling/bio_4.tif")
bio12 <- rast("/Users/yasirdogan/Desktop/R_wd/Modelling/bio_12.tif")
bio15 <- rast("/Users/yasirdogan/Desktop/R_wd/Modelling/bio_15.tif")
bio17 <- rast("/Users/yasirdogan/Desktop/R_wd/Modelling/bio_17.tif")
bio19 <- rast("/Users/yasirdogan/Desktop/R_wd/Modelling/bio_19.tif")

myExpl= c( bio12, bio15, bio17, bio19, bio4)

# Format Data with pseudo-absences : random method

myBiomodData <- BIOMOD_FormatingData(resp.name = 'Abies_cilicica',
                                     resp.var = myResp.PA,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     PA.nb.rep = 1,
                                     PA.nb.absences =26084,
                                     PA.strategy = 'random',
                                     na.rm = TRUE,
                                     filter.raster = FALSE)

# Create 'default' modeling options
myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodOptions

# Model single models
NEW_myBiomodModelOut <- BIOMOD_Modeling(
  bm.format = myBiomodData ,
  modeling.id = as.character(format(Sys.time(), "%s")),
  models = c( 'GLM', 'GBM', 'GAM', 'CTA', 'ANN', 'SRE', 'FDA', 'MARS', 'RF', 'MAXENT', 'MAXNET','XGBOOST' ),
  models.pa = NULL,
  bm.options = myBiomodOptions,
  CV.strategy = "random",
  CV.nb.rep = 1,
  CV.perc = 0.7,
  CV.k = NULL,
  CV.balance = NULL,
  CV.env.var = NULL,
  CV.strat = NULL,
  CV.user.table = NULL,
  CV.do.full.models = FALSE,
  weights = NULL,
  prevalence = NULL,
  metric.eval = c("KAPPA", "TSS", "ROC"),
  var.import = 1,
  scale.models = FALSE,
  nb.cpu = 1,
  seed.val = NULL,
  do.progress = TRUE)

# Projection

current_myBiomodProj<- BIOMOD_Projection(
  bm.mod = myBiomodModelOut,
  proj.name ='abies_current',
  new.env = myExpl,
  new.env.xy = myRespXY,
  models.chosen = "all",
  metric.binary = 'all',
  metric.filter = 'all',
  compress = TRUE,
  build.clamping.mask = TRUE,
  nb.cpu = 4,
  seed.val = NULL)

**Environment Information**
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 14.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.4   ggtext_0.1.2    tidyterra_0.4.0 terra_1.7-55    biomod2_4.2-4  

loaded via a namespace (and not attached):
 [1] tidyr_1.3.0            jsonlite_1.8.7         splines_4.2.3          foreach_1.5.2         
 [5] Formula_1.2-5          sp_2.1-1               yaml_2.3.7             pillar_1.9.0          
 [9] lattice_0.22-5         glue_1.6.2             pROC_1.18.5            digest_0.6.33         
[13] gridtext_0.1.5         randomForest_4.7-1.1   colorspace_2.1-0       gbm_2.1.8.1           
[17] htmltools_0.5.7        Matrix_1.5-4.1         plyr_1.8.9             pkgconfig_2.0.3       
[21] maxnet_0.1.4           PresenceAbsence_1.1.11 earth_5.3.2            purrr_1.0.2           
[25] scales_1.2.1           TeachingDemos_2.12     tibble_3.2.1           proxy_0.4-27          
[29] mda_0.5-4              generics_0.1.3         xgboost_1.7.5.1        withr_2.5.2           
[33] nnet_7.3-19            cli_3.6.1              survival_3.5-7         magrittr_2.0.3        
[37] evaluate_0.23          fansi_1.0.5            doParallel_1.0.17      MASS_7.3-60           
[41] xml2_1.3.5             class_7.3-22           tools_4.2.3            data.table_1.14.8     
[45] lifecycle_1.0.3        stringr_1.5.0          munsell_0.5.0          plotrix_3.8-3         
[49] compiler_4.2.3         e1071_1.7-13           rlang_1.1.2            plotmo_3.6.2          
[53] classInt_0.4-10        units_0.8-4            grid_4.2.3             iterators_1.0.14      
[57] rstudioapi_0.15.0      rmarkdown_2.25         gtable_0.3.4           codetools_0.2-19      
[61] abind_1.4-5            DBI_1.1.3              reshape_0.8.9          reshape2_1.4.4        
[65] R6_2.5.1               knitr_1.45             dplyr_1.1.3            fastmap_1.1.1         
[69] utf8_1.2.4             KernSmooth_2.23-22     stringi_1.7.12         parallel_4.2.3        
[73] Rcpp_1.0.11            vctrs_0.6.4            sf_1.0-14              rpart_4.1.21          
[77] tidyselect_1.2.0       xfun_0.41

**Comment by yasirdogan** [comment]
A BIOMOD.models.out object containing models outputs, or links to saved outputs.
Models outputs are stored out of R (for memory storage reasons) in 2 different folders created in the current working directory :

a models folder, named after the resp.name argument of [BIOMOD_FormatingData](http://127.0.0.1:10965/help/library/biomod2/help/BIOMOD_FormatingData), and containing all calibrated models for each repetition and pseudo-absence run

a hidden folder, named .BIOMOD_DATA, and containing outputs related files (original dataset, calibration lines, pseudo-absences selected, predictions, variables importance, evaluation values...), that can be retrieved with [get_[...]]

**### I think i erased hidden folders when i clean my environment and i cant find my output file in models folder. Because of that R cant do projection. But I don't understand why i can view my missed output data when load my .RData file.**

**Comment by MayaGueguen** [comment]
Hello there,

Yes, biomod2 workflow and functions rely on a hidden directory called `.BIOMOD_DATA` automatically created when you start running [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.
[BIOMOD.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.models.out.html) and [BIOMOD.ensemble.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.ensemble.models.out.html) objects contain summary informations about your modeling but also refer to elements that are saved within this hidden folder. So if you delete this folder, you loose all information contained in it :grimacing: 

So you might still see some informations about your modeling that are saved within the `.RData` object, but you won't be able to access elements that were saved within `.BIOMOD_DATA` and referenced through links within the `.RData`.

I'm afraid you will have to redo your simulations...

Hope it helps,

Maya

**Comment by yasirdogan** [comment]
Hello,

Thank you for your response. I have a basic question: what's the best method to safeguard all of my data, including hidden folders? I'm concerned about losing or overwriting the files in these hidden directories.

I've started avoiding clicking 'delete my hidden files' when cleaning my environment :), but is this sufficient? Could restarting my computer result in data loss within these hidden folders?

I doubt that biomod2 writes these hidden folders onto RAM or a temporary file. Nevertheless, if that were the case, I might need to store all data on my SSD as well. Do you have any specific procedures when working on biomod2 or R in general to prevent the loss of this kind of data?"

Best wishes,
Yasir

**Comment by MayaGueguen** [comment]
Hello Yasir,

Hidden folders should not be impacted by basic actions such as restarting your computer :wink: 
There is no procedure specific to biomod2 : like any working case, you should be cautious with your raw data, and defining well your working paths and directory.
There are some parameters that may help you ensure you do not erase previous runs if you want to test different settings, like `modeling.id` in [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html), or `proj.name` in [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions.
But otherwise, you just have to ensure you move your modeling folder as a whole.

Hope it helps,
Maya

**Comment by yasirdogan** [comment]
Greetings,

"I received the message 'R section terminated due to a fatal error.' I suspect it might be related to high RAM consumption, but I'm not entirely certain. Do you have any insights into what could be causing this issue?

Thank you for your assistance.

Best regards,
Yasir
![Screenshot](https://github.com/biomodhub/biomod2/assets/154328077/0f35dcd3-76d0-4606-884b-8f78a254c39e)

**Comment by yasirdogan** [comment]
I suspect the issue might be tied to the RAM because whenever my memory usage surpasses 9GB, my system encounters fatal errors. Despite using macOS, which utilizes swap memory, and having 16GB of DDR5 RAM, I'm unsure if an upgrade to a more powerful computer is necessary. I'm uncertain if there are common reasons that could lead to this specific error.

**Comment by MayaGueguen** [comment]
Hello there,

Yes, this is highly probable that is due to a memory error..
Models can be quite consuming, especially if you run them with raster files at high resolution.

I hope you manage to find a stronger computer, or to reduce your study area. 💪 
Maya
