### ISSUE TITLE
Error in BIOMOD_FormatingData - Error: Not compatible with requested type: [type=character; target=double].

### ISSUE THREAD

**Issue by Daviser95** [biomodhub/biomod2#389]
**Error and context**
Hi everyone, after having used biomod2 in previous versions in the past, I am now trying to reuse it in the new versions, following the cartoon with the main functions for my data.
I'm having trouble using the Biomod_FormatingData function, and it looks like some of the initial data is wrong, but it's part of the same code I used in the past that worked, and even checking it again I can't figure out where it's wrong.
I attached the codes below:

**Code used to get the error**
```
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                         expl.var = env,
                                         resp.xy = myRespXY,
                                         resp.name = myRespName)
```
and i get the error: 
```
Error in .local(sp, env, ...) : 
No absences were given and no pseudo-absences were given or configured, at least one of those option is required.
```

When I try to run this code, by inserting pseudo absences:
```
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                      expl.var = env,
                                      resp.xy = myRespXY,
                                      resp.name = myRespName,
                                      PA.nb.rep = 10,
                                      PA.nb.absences = 10000,
                                      PA.strategy = 'sre',
                                      PA.sre.quant = 0.05,
                                      na.rm = TRUE)
```
instead I get the error:
```
Error: Not compatible with requested type: [type=character; target=double].
```
This is the error that is currently blocking me, and I haven't found anything similar among the biomod2 issues.
I checked that the elements used as inputs are the ones required, and they are. I also tried running the code reported in the vignette, and in that case, the function works. Other tests, such as using a raster stack instead of a SpatRatser object, still produced the same error.

**Environment Information**
Please paste the output of `sessionInfo()` in your current R session below.
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.utf8  LC_CTYPE=Italian_Italy.utf8    LC_MONETARY=Italian_Italy.utf8
[4] LC_NUMERIC=C                   LC_TIME=Italian_Italy.utf8    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spThin_0.2.0      knitr_1.40        fields_14.1       viridis_0.6.2     viridisLite_0.4.1 spam_2.9-1       
[7] terra_1.7-3       biomod2_4.2-4    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9             lattice_0.20-45        class_7.3-20           plotmo_3.6.2           earth_5.3.1           
 [6] assertthat_0.2.1       foreach_1.5.2          utf8_1.2.2             R6_2.5.1               plyr_1.8.7            
[11] ggplot2_3.4.0          pillar_1.8.1           TeachingDemos_2.12     rlang_1.0.6            rstudioapi_0.14       
[16] data.table_1.14.2      raster_3.5-29          rpart_4.1.16           Matrix_1.4-2           splines_4.2.1         
[21] mda_0.5-3              stringr_1.5.0          munsell_0.5.0          xfun_0.34              compiler_4.2.1        
[26] pkgconfig_2.0.3        PresenceAbsence_1.1.11 gbm_2.1.8.1            nnet_7.3-17            tidyselect_1.2.0      
[31] tibble_3.1.8           gridExtra_2.3          codetools_0.2-18       randomForest_4.7-1.1   reshape_0.8.9         
[36] fansi_1.0.3            dplyr_1.0.9            MASS_7.3-58.1          jsonlite_1.8.0         gtable_0.3.1          
[41] lifecycle_1.0.3        DBI_1.1.3              usdm_2.1-7             magrittr_2.0.3         pROC_1.18.0           
[46] scales_1.2.1           maxnet_0.1.4           cli_3.3.0              stringi_1.7.8          reshape2_1.4.4        
[51] sp_1.5-0               generics_0.1.3         vctrs_0.5.2            xgboost_1.7.6.1        Formula_1.2-4         
[56] iterators_1.0.14       tools_4.2.1            glue_1.6.2             maps_3.4.0             abind_1.4-7           
[61] plotrix_3.8-2          survival_3.4-0         colorspace_2.1-0       dotCall64_1.0-1       
```
Any advice can be of great help.
Thanks in advance.

**Comment by HeleneBlt** [comment]
Hello there,
Thank you for reporting 🙏 
To be able to help you, I would like more information: is this the same data you have already used with Biomod2, and if so, do you know which version you used?
My first guess is the problem came with `env`: could you send more details or directly the data if possible so I can be able to reproduce the error?
Hélène

**Comment by Daviser95** [comment]
Hi Hélène,
thanks for the quick reply.
No, these are not the same variables and the same code that I had used in the past, in which I still referred to the raster package. In this case, I based the analyses on the new version of 'biomod2' and the 'terra' package.
However, I have some news about this problem, because this error only occurs on the computer whose information I sent in the previous report. In fact, running the code on my PC works (and is still currently running). The code is the same and also the data used, both the occurrences and the variables, therefore I don't think the problem concerns the variables, but perhaps it depends on other factors. I proceeded to update R and R Studio, but the error was not resolved. 
One more thing I wanted to try was to uninstall biomod2 and reinstall it.
I can also share the files used and the code if it helps you: https://we.tl/t-rIz0H8UrR3, this is the link where you can find all.

**Comment by HeleneBlt** [comment]
Hi 
Glad to know that you could have run the code another way. 
I was able to reproduce the error with your data : the coordinates were in character and with a comma as decimal operator.
If you open your file this way : 
`LynxPres<-read.csv("eval_dataset_cimatti.csv", sep =";",dec=",")` 
it should be fine. 
Don't hesitate if the error occurs again.
Hélène

**Comment by Daviser95** [comment]
Thank you, Hélène! 
This error was much easier than I thought. 
Unfortunately, I am still encountering some issues with biomod2, probably related to high memory consumption, even if I am using a workstation with 128 Gb RAM. I was able to run the full code and obtain my models using worldclim variables at ~1km resolution, but only after using `terraOptions (memmax=20 Gb)`. Before using this option, I was getting an error related to an out-of-memory issue (`Error: std::bad_alloc`).

Now, I am re-running the same code but with different variables at ~300m resolution. I was not able to use the GBM model during `BIOMOD_Modeling`, probably due to excessive memory consumption. After selecting a different set of models (GLM, RF, MARS, ANN, XGBOOST), I am still having problems when running the projections (`BIOMOD_Projection`), likely related to memory consumption, even when I set `terraOptions (memmax=20 Gb)`.

I'm unsure if there is a way to avoid these issues and simplify the process, or if some functions still need optimization.
Thank you for your work!
Davide

**Comment by HeleneBlt** [comment]
Hello Davide, 

I'm afraid I can't be of much help. We try to optimize as much as possible but for some algorithms or resolutions, memory can still be a problem. Perhaps, you could try with `terraOptions (todisk = TRUE) `.

Hélène

**Comment by Daviser95** [comment]
Thanks for this tip Hélène, when I try with `terraOptions(todisk = TRUE)`, do I need to specify the path where to store the raster?
I'm trying to rerun the code, this time I selected fewer algorithms so that I have 75 models to project. Is there anything I can do besides `terraOptions(memmax=20)`? 
I read something about `terraOptions (steps)` but I don't know how this option could help, and I also find `keep.in.memory` option in `BIOMOD_Projection`, but I'm not sure setting this option will solve these problems.
Thank you for your support!

**Comment by HeleneBlt** [comment]
Hi ! 
For `terraOptions(todisk = TRUE)`, the rasters will be written in temp file if no file name is specified. 
You can find more information about `steps` in this [issue ](https://github.com/rspatial/terra/issues/562) in terra package. 
You can also try `terraOptions(memfrac = 0.3) ` which will decrease the proportion of RAM that terra can use (default is 60%) but I'm not sure it gonna be very different than with  `terraOptions(memmax=20)`
An yes, `keep.in.memory = FALSE` will help (but maybe will not be enough). Sorry I didn't mention it, I must have assumed you'd already tried it. You can also set `do.stack = FALSE` even if by default, it must already be the case.
I hope you gonna find a way.

Hélène
