### ISSUE TITLE
FormatingData can't cope with "Matrix" "Array"

### ISSUE THREAD

**Issue by hannahwauchope** [biomodhub/biomod2#39]
I've noticed while using the BIOMOD_FormatingData function that if I input matrices that are of class "Matrix" "Array", I get the following warning: 

Warning message:
In if (!(class(eval.expl.var) %in% available.types[-which(available.types ==  :
  the condition has length > 1 and only the first element will be used

I know that there is actually no issue - it's just the checking function is taking the first argument ("matrix"), but it's still annoying to get the warning message, and might confuse someone less familiar with what that line of code is doing. As far as I understand, it's now quite difficult to make objects of *only* class matrix now, so that doesn't seem like the best solution. 

Thanks!!

**Comment by MayaGueguen** [comment]
Thanks for the message Hannah !
Indeed, it indicates a bad dealing with the input condition, I will give it a look as soon as possible.

Maya
