### ISSUE TITLE
Help with BIOMOD_- PA's not generated

### ISSUE THREAD

**Issue by beardant** [biomodhub/biomod2#390]
I am modeling something with raster stacks and presence data in EPSG 3035. This has worked fine so far, 
despite getting some warnings when doing Ensembleforecasting 
(proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found...)
but the forecasts are still created.

However, now I can't actually model anymore, because my pseudo-absences are not generated:

```
> Disk pseudo absences selection
   > Pseudo absences are selected in explanatory variablesproj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found

   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables
   > All available cells have been selected ( 0 cells )
   > No cells are available (0 pseudo absences selected )

   ! PA selection not done

      ! No data has been set aside for modeling evaluationError in .local(sp, env, ...) : 
  No absences were given and no pseudo-absences were given or configured, at least one of those option is required.
```

**Comment by HeleneBlt** [comment]
Hello there,
Thank you for reporting :pray: 
So, to be sure that I understand well : you made some modelisation with biomod2 with raster stacks and presence data in EPSG 3035 with errors you found harmless. But now, you found the same errors and you think it's leading to another error. Did you use the same data? Did you make some update? 
Could you share some additional information : 

- the output of `sessionInfo()`
- the call of `BIOMOD_FormatingData`
- the summary of your response and explanatory variables 

Thank you
Hélène
