### ISSUE TITLE
Error in BIOMOD_Modeling - [I am running the MAXENT algorithm with bigboss options in biomod2 4.2.5 version, I get the following error when I try to run the model "unused argument (temp_workdir = MWD$m_outdir)"]

### ISSUE THREAD

**Issue by TDphoneix** [biomodhub/biomod2#392]
I am using the following code to built the model

sp_data <- BIOMOD_FormatingData(resp.var = as.numeric(sp$ob),
                            expl.var = curr_test_stack,
                            resp.xy = sp[,c("long","lat")],
                            resp.name = sp$species[1],
                            filter.raster = F,
                            PA.nb.rep = 1,
                            PA.nb.absences = 10000,
                            PA.strategy = 'random')
  
mdl <- BIOMOD_Modeling(bm.format = sp_data,
                         models = c('MAXENT'),
                         CV.strategy = 'random',
                         CV.nb.rep = 3,
                         CV.k = 5,
                         prevalence = NULL,
                         CV.perc = 0.8,
                         OPT.strategy = 'bigboss',
                         OPT.user.base = 'bigboss',
                         var.import = 5,
                         CV.do.full.models = F,
                         metric.eval = c('TSS','ROC'),
                         )

When the modelling starts, I get the following error :
Error in { : 
  task 1 failed - "unused argument (temp_workdir = MWD$m_outdir)"

How do I fix this?

**Comment by TDGtamu** [comment]
I am having the same issue where maxent would run but time out saying "_Error in { : task 1 failed - "unused argument (tmep_workdir = MWD$m_outdir)".  Were you able to resolve this issue or find a work?  If so could you please share.  Your post was the only one I found that mentioned this exact error.

**Comment by HeleneBlt** [comment]
Hello, 
Thanks for reporting: there was indeed an error with the use of MAXENT and the importance of the variables.
I just push a commit. If you update the biomod2 4.2.5 version, it should work. 
Please let me know if the error persists.
Hélène

**Comment by TDphoneix** [comment]
@TDGtamu  sorry for responding late. I just reverted into the stable version and used MAXENT that way, as no one was responding to the issue. But I think @HeleneBit has fixed it for now so I guess it should function correctly.

**Comment by TDGtamu** [comment]
Thanks for the help! I was able to run Maxent after the update.
