### ISSUE TITLE
Please advise what is meant by the range change definitions "Future range size no dispersal vs full dispersal"

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#397]
Dear helpful biomod2 team

Please may I ask what are the basic assumptions or principles with these two definitions.

FutureRangeSize0Disp : number of pixels predicted to be occupied, assuming no migration

FutureRangeSize1Disp : number of pixels predicted to be occupied, assuming migration

Thank you.
With best wishes, Carlos

**Comment by MayaGueguen** [comment]
Hello Carlos,

Sorry that this is not clear enough within the documentation, we'll try to improve that ⛑️ 
I assume that this is related to the use of the [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function.

This is actually a strong wording to something very simple : 
- _assuming migration_ : it just means that you are projecting over the whole area you are providing through `proj.future` parameter, regardless of whether it was included within the current range (defined by the `proj.current` parameter).
- _assuming no migration_ : it means that you take the above projection and only keep original range, so removing pixels that were not included within the current range

Hope it's clearer that way 👀 
Maya

**Comment by wthuiller** [comment]
Hey,
True Carlos, yet, this is what is generally used in the literature (no vs full dispersal for protected range shifts). But I hear the point, and at least, we certainly need to better explain in the documentation. 
Best
Wilfried
