### ISSUE TITLE
Please is it possible to produce Evaluation Strip for categorical values with the category values on x axis at bottom as separate ticks not as implied continuous values

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#405]
Dear Helpful biomod2 people
I really like the variable response curve outputs which are very informative.  Thank you.
When I have a categorical variable - e.g. Landcover or Soil - the output is produced as sort of a spiky line on a logistic regression.  For example -see image for Chalk Carpet Moth - The category numbers at the bottom are not quite distinct if say we have 20 categories - it shows every 5th category. please is it possible for the x axis to show as tick marks each individual category number.   I appreciate this might be tricky technically.  Thank you for considering. With best wishes, Carlos
![VRC](https://github.com/biomodhub/biomod2/assets/70659477/08cec51b-1329-4e63-ac19-97c2f5b95510)

**Comment by HeleneBlt** [comment]
Hi Carlos, 

Thanks a lot for your interest and your suggestion 🙏
To keep `biomod2` as general as possible, we can't change the plots. However, you can change them yourself. `bm_PlotResponseCurves` returns the plots but also a data.frame with the associated variables and predicted values. You can therefore reproduce the plots with `ggplot2` and adjust them as you wish.
Hope it helps.

Hélène
