### ISSUE TITLE
Custom cutoff threshold evaluations

### ISSUE THREAD

**Issue by anackr** [biomodhub/biomod2#407]
Hi everyone

I am running Maxent models with 3-fold cross-validation and had some doubts about evaluation metrics.
Since results we obtain from get_evaluations() are the values for those specific cutoffs, there is a very wide range of possible cutoffs for my models.
So, I would like to **see if there is a cutoff where I can obtain at least 0.7 AUC and at lease 0.9 sensitivity** (there is no such thing in m get_evaluations()).

So I used this

`binary <- bm_BinaryTransformation(data = eval_proj_df$pred, threshold = 400)`

where eval_proj_df was obtained through get_predictions()

But I cannot figure out how I can evaluate AUC and sensitivity properly with this cutoff (and other threshold values). 
When I use bm_FindOptimStat(metric.eval = 'ROC', fit = binary, obs = get_formal_data(model, "resp.var")) , it establishes another cutoff (for instance 0 or 0.5). e.g.:

```
> binary_400 <- bm_BinaryTransformation(data = eval_proj_df$pred, threshold = 400)
> 
> bm_FindOptimStat(metric.eval = 'ROC', fit = binary_400, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         ROC    0.5    91.42857       38.14 0.6478429
> bm_FindOptimStat(metric.eval = 'TSS', fit = binary_400, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         TSS      0         100           0 0.2956857
> 
  > binary_500 <- bm_BinaryTransformation(data = eval_proj_df$pred, threshold = 500)
> 
  > bm_FindOptimStat(metric.eval = 'ROC', fit = binary_500, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         ROC    0.5    82.85714       54.84 0.6884857
> bm_FindOptimStat(metric.eval = 'TSS', fit = binary_500, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         TSS      0         100           0 0.3769714
> 
  > binary_600 <- bm_BinaryTransformation(data = eval_proj_df$pred, threshold = 600)
> 
  > bm_FindOptimStat(metric.eval = 'ROC', fit = binary_600, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         ROC    0.5    71.42857       67.62 0.6952429
> bm_FindOptimStat(metric.eval = 'TSS', fit = binary_600, obs = obs_sem_nas)
metric.eval cutoff sensitivity specificity best.stat
1         TSS      0         100           0 0.3904857
```

Is there a solution for seeing the apropriate value of AUC and sensitivity with a custom cutoff threshold?

In addition, once I obtain this binary vector, what should be the following steps to produce graphs and projection maps?

Sorry for the newbie questions!

Thanks in advance :)

**Comment by HeleneBlt** [comment]
Hello there, 

bm_FindOptimStat is made to work with normally a continuous fit vector. So in your case, as you already transformed your prediction data in binary, the cutoff will behave differently.
For TSS metrics, you can just do : 
`bm_FindOptimStat(metric.eval = 'TSS', fit = eval_proj_df$pred, obs = obs_sem_nas, threshold = 400)
`
For ROC metrics, `bm_FindOptimStat` will create the curve (by testing all the thresholds) and calculate the AUC. It will return the best threshold. 
What you can do is use the function `pROC::roc` to create the curve and see at which threshold you can have at least 0.9 sensitivity and maximize the specificity. The AUC will not change. 

Please note that eval_proj_df$pred gives you predictions for all your algorithms and runs so be sure that you have selected the predictions of the model you want. 

Hope it helps, 
Hélène

**Comment by anackr** [comment]
Thank you very much, Helene! 

That makes sense.
Do you know if it is possible, in biomod, to implement the minimum training presence threshold and the 10% presece threshold?

I am looking for ways to quantify overfitting, other than AUCdiff.

**Comment by HeleneBlt** [comment]
Hello Ana, 

Sorry, we didn't implement the minimum training presence threshold or the 10% presence threshold in Biomod2. 
However, you have a big set of metrics so by optimizing different metrics, you can have different results. For example, with POD : Probability of detection (hit rate), you will probably have a similar result than with the minimum training presence threshold. 
You can also look to FAR : False alarm ratio, POFD : Probability of false detection (fall-out), SR : Success ratio. 

Hope it helps. 
Hélène

**Comment by anackr** [comment]
Thank you!
