### ISSUE TITLE
BIOMOD error: argument 1 matches multiple formal arguments

### ISSUE THREAD

**Issue by srknozdemir** [biomodhub/biomod2#409]
ı run the following codes.

ProLau_models <- 
  BIOMOD_Modeling(
    data = ProLau_data,
    models = c("GLM", "GBM", "RF", "GAM"),
    models.options = ProLau_opt,
    NbRunEval = 2,
    DataSplit = 80,
    VarImport = 3,
    modeling.id = "demo1"
  )

I faced the following error.
Error in BIOMOD_Modeling(data = ProLau_data, models = c("GLM", "GBM",  : 
  argument 1 matches multiple formal arguments

How can I handle this error?

**Comment by HeleneBlt** [comment]
Hello again, 

Here, you need to remove `data = ` in your call.
But in the same way, you'll need to update your version to enable us to help you more. 
Hope you'll adapt quickly to version 4.2-4. 

Hélène
