### ISSUE TITLE
Variable Selection

### ISSUE THREAD

**Issue by kyrangraves** [biomodhub/biomod2#41]
Hello,

I am currently developing models to predict the distribution of deep-sea biotopes across the North Atlantic. I am posting to enquire about the potential to add an additional feature to BIOMOD2.

I have gone through a variable selection process for each of my chosen modeling algorithms (MaxEnt, GAMs, RF) outside of BIOMOD. My list of selected variables for each model algorithm is different for one of my biotopes. As I understand, at current, you have to select the same list of predictor variables across all your chosen algorithms.

Is there any potential for this to be changed in the future to allow for different selected variables for each of your chosen algorithms? 

Many thanks, 
Kyran

**Comment by MayaGueguen** [comment]
Hello Kyran,

Sorry, but this is not likely to happen.
You will have to run a different BIOMOD_Modeling object for your biotope with a different list of variables.

Hope you will still get the models you want :)
Maya

**Comment by kyrangraves** [comment]
Hi Maya,

Thanks for getting back to me so quickly - not a problem! Just thought it was worth an ask :) 

Are you still able to ensemble multiple BIOMOD_Modeling objects?

Kyran

**Comment by MayaGueguen** [comment]
Hi Kyran,

Sure, with the BIOMOD_EnsembleModeling function.

Maya

**Comment by DamienGeorges** [comment]
Well.. I do not think that building ensemble from different BIOMOD_Modelling() outputs (as @kyrangraves  will have to do if you use different set of environment variable) is an available biomod2 feature. I think you will have to combine single models projections 'by hand' to produce your ensemble model. But maybe this is a new feature @MayaGueguen has devel recently.

Cheers,
Damien

**Comment by MayaGueguen** [comment]
My mistake, indeed, I read too fast...
No, you can not combine several BIOMOD_Modeling objects within one ensemble output.
But anyway, it would mean that you would like to combine models for different biotopes and I'm not sure that's what you want ?

Sorry for the bad previous answer.

Maya

**Comment by kyrangraves** [comment]
Hi Maya,

No, they would not be the same biotope.

I'm looking to ensemble three different modelling algorithms for the same biotope - RF, GAM & MaxEnt. However, because the three different algorithms use three slightly different predictor variables they cannot all be modelled together, at the same time as one single BIOMOD_Modelling object - as we previously established - hence why there is now the need to combine three individual BIOMOD_Modelling objects (one for each algorithm and unique predictor list).

However, from what you have said @DamienGeorges, this is not possible so will have to, unfortunately, figure out how to do this by hand.

Thank you for your help! 

Kyran
