### ISSUE TITLE
Error in BIOMOD - manual caption of terrain() cutoff

### ISSUE THREAD

**Issue by eragrostis** [biomodhub/biomod2#411]
In the manual page for terrain a paragraph says: 

"TRIriley (TRI according to Riley et al. (2007)) returns the square root of summed squared differences between the value of a cell and its 8 surrounding cells. TRIrmsd computes the square root of the mean of the squared differences between these cells. The benefit of TRIrmsd"

e.g. https://search.r-project.org/CRAN/refmans/terra/html/terrain.html

This is clearly cut off at the end. What is the benefit?

**Comment by MayaGueguen** [comment]
Hello there,

This seems to be a problem related to the `terra` package.
Please try and post on their [issue page](https://github.com/rspatial/terra/issues).

Maya
