### ISSUE TITLE
Please what are the units of EMcv

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#414]
Dear Helpful Biomod2 people

I understand that the units of projection from Ensemble Models for committee average and weighted mean are presented in a scale from 0 to 1000.    This applies to EMca and EMwmean.
To help my readers I am then multiplying these by 0.1 to give maps with values from 0 to 100%.

However please what are the range of values for EMcv.  The vignette states this is sd/mean and I appreciate that this may have no upward limit.   However please I wonder again whether the value is already a % calculated - or whether like EMca and EMwmean it would again need me to multiply by 0.1   

I am showing you an example output map here which is similar to that of the page 343 of the Guisan et al. 2017 Habitat Suitability and Distribution Models book .

Thank you for considering.   With best wishes, Carlos  

![EXAMPLE ](https://github.com/biomodhub/biomod2/assets/70659477/c4a86633-22d2-4041-8978-a1111c853031)

**Comment by HeleneBlt** [comment]
Hi Carlos ! 

Sorry for the late reply 😬 
For EMcv, we return `sd/mean *100`. But, depending on your case, you will maybe need to make some adjustments for a good visualization. 
Hope it helps ! 

Hélène

**Comment by carlosbedson** [comment]
Chere Helene - merci beaucoups - this is very helpful - yes  * 100    - i thought this likely to be the case.   I know I can adjust my legend value range also to ensure the visualisation is appropriate.  Thank you so much for your help.  A bientot.  Carlos
