### ISSUE TITLE
Help with BIOMOD_4.2-5 - [tune parameters for Random Forest model]

### ISSUE THREAD

**Issue by suicmezburak** [biomodhub/biomod2#415]
When I created a model with default settings using the RF algorithm, I encountered an overfit problem.

Therefore, I created a new model using bigboss settings. When I changed the nodesize parameter to 10 in these settings, I did not encounter the overfit problem. Then, I wanted to use the RF algorithm with appropriate parameters using bm_Tuning via bm_ModelingOptions, but the parameter it created seemed to contain only mtyr. In fact, when I looked at the result after the tuning process, there were no nodesize or ntrees values, and when I created the model with the results of the bm_Tuning function, I encountered the overfit problem again.

First of all, I am sharing the code in case there is an error on my part;

```
x_data <- 
  BIOMOD_FormatingData(
    resp.name = respname,
    resp.var = respvar,
    expl.var = cv_bio,
    resp.xy = respxy,
    PA.nb.rep = 3,
    PA.nb.absences = 264, 
    PA.strategy = "random",
    filter.raster = TRUE
  )


cv.k <- bm_CrossValidation(
  bm.format = x_data, 
  strategy = "kfold", 
  nb.rep = 3, 
  k = 5)


## Define individual models options
opt.d <- 
  bm_ModelingOptions(
    data.type = "binary", 
    models = c("RF"), 
    strategy = "tuned",
    bm.format = x_data,
    calib.lines = cv.k
  )

``` 

Here is the content of opt.d, I did not print it all for the sake of length. As can be seen, it does not contain any information for ntrees or nodesize.
```
opt.d@options[["RF.binary.randomForest.randomForest"]]@args.values
$`_PA1_RUN1`
$`_PA1_RUN1`$mtry
[1] 1

$`_PA1_RUN1`$type
[1] "classification"


$`_PA1_RUN2`
$`_PA1_RUN2`$mtry
[1] 1

$`_PA1_RUN2`$type
[1] "classification"


$`_PA1_RUN3`
$`_PA1_RUN3`$mtry
[1] 2

$`_PA1_RUN3`$type
[1] "classification"


$`_PA1_RUN4`
$`_PA1_RUN4`$mtry
[1] 1
```

When I create a model with these settings, I get the following results:
```
        full.name  PA   run algo metric.eval cutoff sensitivity specificity calibration validation
1   x_PA1_RUN1_RF PA1  RUN1   RF         TSS    505         100         100           1      0.906
2   x_PA1_RUN1_RF PA1  RUN1   RF         ROC    508         100         100           1      0.990
3   x_PA1_RUN2_RF PA1  RUN2   RF         TSS    495         100         100           1      0.924
4   x_PA1_RUN2_RF PA1  RUN2   RF         ROC    495         100         100           1      0.981
5   x_PA1_RUN3_RF PA1  RUN3   RF         TSS    500         100         100           1      0.924
```
What could cause this? Can tuned model settings and bigboss be used together, that is, can tuned mtyr values be added to bigboss settings?

Briefly, how can I tune the Random forest model and use these settings in the BIOMOD_Modeling content? This way I won't encounter overfit problems.

current R session below.
```
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Turkish_Turkey.utf8  LC_CTYPE=Turkish_Turkey.utf8    LC_MONETARY=Turkish_Turkey.utf8
[4] LC_NUMERIC=C                    LC_TIME=Turkish_Turkey.utf8    

time zone: Europe/Istanbul
tzcode source: internal

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] caret_6.0-94         lattice_0.22-5       ggplot2_3.4.4        terra_1.7-71         xgboost_1.7.7.1     
 [6] randomForest_4.7-1.1 maxnet_0.1.4         earth_5.3.2          plotmo_3.6.2         TeachingDemos_2.12  
[11] plotrix_3.8-4        Formula_1.2-5        gbm_2.1.9            mgcv_1.9-0           nlme_3.1-163        
[16] gam_1.22-3           foreach_1.5.2        mda_0.5-4            class_7.3-22         rpart_4.1.21        
[21] nnet_7.3-19          biomod2_4.2-5       

loaded via a namespace (and not attached):
 [1] gtable_0.3.4           raster_3.6-26          recipes_1.0.9          vctrs_0.6.5            tools_4.3.2           
 [6] generics_0.1.3         stats4_4.3.2           parallel_4.3.2         tibble_3.2.1           PresenceAbsence_1.1.11
[11] fansi_1.0.6            ModelMetrics_1.2.2.2   pkgconfig_2.0.3        Matrix_1.6-1.1         data.table_1.15.0     
[16] lifecycle_1.0.4        compiler_4.3.2         stringr_1.5.1          munsell_0.5.0          dismo_1.3-14          
[21] codetools_0.2-19       prodlim_2023.08.28     pillar_1.9.0           MASS_7.3-60            gower_1.0.1           
[26] iterators_1.0.14       abind_1.4-5            parallelly_1.36.0      lava_1.7.3             digest_0.6.34         
[31] tidyselect_1.2.0       future_1.33.1          stringi_1.8.3          purrr_1.0.2            listenv_0.9.1         
[36] dplyr_1.1.4            reshape2_1.4.4         grid_4.3.2             colorspace_2.1-0       cli_3.6.1             
[41] magrittr_2.0.3         survival_3.5-7         utf8_1.2.4             future.apply_1.11.1    withr_3.0.0           
[46] scales_1.3.0           sp_2.1-3               timechange_0.3.0       lubridate_1.9.3        globals_0.16.2        
[51] timeDate_4032.109      hardhat_1.3.1          rlang_1.1.2            Rcpp_1.0.12            glue_1.7.0            
[56] pROC_1.18.5            ipred_0.9-14           rstudioapi_0.15.0      reshape_0.8.9          jsonlite_1.8.8        
[61] R6_2.5.1               plyr_1.8.9            
```

**Comment by HeleneBlt** [comment]
Hi, 

Thanks for this well-explained issue and for trying out the different possibilities in Biomod_4.2-5 !
Indeed, the default and bigboss settings are general and might not be suitable for some particular cases. 
Yes, `mtry` is the only parameter available in the tuning options for Random Forest.

You can mix tuned options and modified parameters. It will look like this : 

```
opt.d <- bm_ModelingOptions(data.type = 'binary',
                            models = 'RF',
                            strategy = 'bigboss',    
                            bm.format = x_data,
                            calib.lines = cv.k)

## You use the function bm_Tuning to tuned mtry
tuned.rf <- bm_Tuning(model = 'RF',
                      tuning.fun = 'rf', 
                      bm.options = opt.d@options$RF.binary.randomForest.randomForest,
                      bm.format = x_data, 
                      calib.lines = cv.k)

## You change the nodesize parameter. Here for all your PAs and RUNs.
for(n in names(tuned.rf)){
  tuned.rf[[n]] <- c(tuned.rf[[n]], nodesize = 10)
}

## You can integrate it in your opt.d
user.val <- list( RF.binary.randomForest.randomForest = tuned.rf)

opt.d <- bm_ModelingOptions(data.type = 'binary',
                            models = 'RF',
                            strategy = 'user.defined',   
                            user.val = user.val,
                            bm.format = x_data,
                            calib.lines = cv.k)

print(opt.d, dataset = "_PA1_RUN1")
print(opt.d, dataset = "_PA1_RUN4")
print(opt.d, dataset = "_allData_allRun") # here, "_allData_allRun" should not be modified.
```

Hope it helps. Don't hesitate if it's still not clear.
Hélène

**Comment by suicmezburak** [comment]
Thank you for your answer, Hélène. I created the model as you described and I can mix the settings as I want, it was a very understandable answer.

**Comment by suicmezburak** [comment]
Hello again Hélène, first of all, I would like to express my gratitude to the entire biomod2 team.

I have another topic I would like to discuss, and since it is a similar subject, I am conveying it here without opening a different title.

I want to create a model using the MAXENT, RF, and XGBOOST algorithms. For RF and XGBOOST, I want to generate as many pseudo-absence data (263) as the number of my existing records, with 4 repetitions. For MAXENT, I want to generate 10,000 pseudo-absence data, again with 4 repetitions. Afterward, I want to create these three models by adjusting the parameters with `bm_Tuning()`.

In this context, I attempted to generate the desired PAs using the `BIOMOD_FormatingData()` function; 
```r
x_data <- 
  BIOMOD_FormatingData(
    resp.name = respname,
    resp.var = respvar,
    expl.var = current_bio,
    resp.xy = respxy,
    PA.nb.rep = 8, 
    PA.nb.absences = c(rep(263, 4), rep(10000, 4)), #263
    PA.strategy = "random",
    filter.raster = TRUE
  )
```
In this way, I believe I have been able to generate the desired PAs as intended, and when I check, there doesn't seem to be any issue. Do you think there is a problem?

Then, before tuning the models, I pulled the bigboss parameters as opt.d. However, here I encountered an issue due to the maxent file being in a different directory on my computer, so I changed the working directory twice. See below;
```r
### Create CrossValidation table
cv.k <- bm_CrossValidation(
  bm.format = x_data, 
  strategy = "kfold", 
  nb.rep = 5, 
  k = 5
)


# Define individual models options
setwd("C:/Users/Hp/Desktop/sdm_data/maxent")

opt.d <- 
  bm_ModelingOptions(
    data.type = "binary", 
    models = c("MAXENT", "RF", "XGBOOST"), 
    strategy = "bigboss",
    bm.format = x_data,
    calib.lines = cv.k
  )

## Back to first working directory
setwd("C:/Users/Hp/Desktop/x_model")
```
Is it possible to resolve my issue without changing the working directory in this way and also without altering the file location of `MAXENT`, but rather with a different approach? Do you have any recommendations?

Afterwards, to tune the model parameters, based on your advice in the initial question, I created the following code:
```r
### tune parameters for MAXENT
tuned.maxent <- bm_Tuning(
  model = "MAXENT", 
  tuning.fun = "ENMevaluate", 
  bm.options = opt.d@options$MAXENT.binary.MAXENT.MAXENT,
  bm.format = x_data,
  calib.lines = cv.k,
  metric.eval = "or.mtp.avg"
)


### tune parameters for XGBOOST
tuned.xgboost <- bm_Tuning(
  model = "XGBOOST", 
  tuning.fun = "xgbTree", 
  bm.options = opt.d@options$XGBOOST.binary.xgboost.xgboost,
  bm.format = x_data,
  calib.lines = cv.k,
)


### tune parameters for Random Forest
tuned.rf <- bm_Tuning(
  model = "RF", 
  tuning.fun = "rf", 
  bm.options = opt.d@options$RF.binary.randomForest.randomForest,
  bm.format = x_data,
  calib.lines = cv.k
)

# Change the nodesize parameter and ntree for all PAs and RUNs
## Random Forest
for(n in names(tuned.rf)){
  tuned.rf[[n]] <- c(tuned.rf[[n]], nodesize = 10)
}

for(n in names(tuned.rf)){
  tuned.rf[[n]] <- c(tuned.rf[[n]], ntree = 250)
}

## Integrate tuned list to opt.d
user.val <- list()
user.val$MAXENT.binary.MAXENT.MAXENT <- tuned.maxent
user.val$XGBOOST.binary.xgboost.xgboost <- tuned.xgboost
user.val$RF.binary.randomForest.randomForest <- tuned.rf


opt.d <- bm_ModelingOptions(
  data.type = "binary", 
  models = c("MAXENT", "RF", "XGBOOST"), 
  strategy = "user.defined", 
  user.val = user.val, 
  bm.format = x_data, 
  calib.lines = cv.k
)
```
Here, I am achieving the intended results for RF and XGBOOST, and it doesn't seem like there is an issue. However, for MAXENT, I am encountering the following error:
```r
> Dataset _PA1_RUN1
			> Tuning parameters...*** Running initial checks... ***

Loading required namespace: rJava
* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Removed 210 background points with NA predictor variable values.
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

		> Dataset _PA1_RUN2
			> Tuning parameters...*** Running initial checks... ***

* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Removed 211 background points with NA predictor variable values.
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

## goes like this for all PAs and RUNs.
```

I haven't found a solution, to be honest. Moreover, within the `BIOMOD_Modeling()` function, I can command the models to use the desired PAs with the statement `models.pa = list(MAXENT = paste0("PA", 5:8), RF = paste0("PA", 1:4), XGBOOST = paste0("PA", 1:4)).` I'm not entirely sure if the tuning results for RF and XGBOOST are generated exactly as I want (263 PA with 4 repetitions), or if PAs play a role in the tuning stage, and how can I solve the problem for MAXENT?

Sorry if it's too long :) If I wasn't clear, you can specify. I'm waiting for your suggestions, thank you in advance.

**Comment by MayaGueguen** [comment]
Hello there,

We had a look to this problem with Hélène, and encountered indeed the same error than yours :eyes:

The digging was a bit complex, but we finally found that it was coming from the [ENMevaluate](https://jamiemkass.github.io/ENMeval/reference/ENMevaluate.html) function we use to tune `MAXENT` model. It seems that, with the configuration we had, it was trying to use, not the `maxent.jar` file that should be in your working directory, but rather the Java version of Maxent defined within the [dismo](https://github.com/rspatial/dismo/) package. And this Maxent version tried to access, we don't know why, to temporary files that do not exist.
However, it is possible to ask [ENMevaluate](https://jamiemkass.github.io/ENMeval/reference/ENMevaluate.html) function to use `maxnet` algorithm instead, and then your code should be working.

I just pushed a commit onto the GitHub, adding these modifications.
Note that there is a new element called `MAXENT.algorithm` within the `params.train` parameter of the [bm_Tuning](https://biomodhub.github.io/biomod2/reference/bm_Tuning.html) function defining which algorithm the [ENMevaluate](https://jamiemkass.github.io/ENMeval/reference/ENMevaluate.html) function should use.
I set it to `maxnet` by default, but you can set it to `maxent.jar` if you would like to use the Maxent version from the [dismo](https://github.com/rspatial/dismo/) package (but which was causing you an error).

Please, update your `biomod2` version with the last on GitHub and give it a try ! :eyes: 

Maya

**Comment by suicmezburak** [comment]
Hello Maya,
First of all, thank you for the response. As you mentioned, I still encounter errors when trying to use `maxent.jar`, but the code runs smoothly with the default setting, `maxnet`. However, even though the code runs, I couldn't get any results because it attempts to use all the cores, see;
```r
		> Dataset _PA1_RUN1
			> Tuning parameters...*** Running initial checks... ***

* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Removed 209 background points with NA predictor variable values.
* Model evaluations with random 10-fold cross validation...

*** Running ENMeval v2.0.4 with maxnet from maxnet package v0.1.4 ***

  |                                                                                                                      |   0%
Of 8 total cores using 8...
Running in parallel using doSNOW...
``` 
Is this originating from the source code? I couldn't prevent it from using all available cores.

Secondly, if you pay attention to the beginning of the above text, the tuning process for MAXENT starts with "`> Dataset _PA1_RUN1.`" I have generated 8 PA sets, where PA1 to PA4 will be used for RF and XGBOOST, and PA5 to PA8 will be used for MAXENT. Is there a way to limit this to save time during the tuning processes?

Best regards,
Burak

**Comment by MayaGueguen** [comment]
Hello Burak,

Thank you for testing 🙏 
I just pushed a new commit with a `MAXENT.parallel` parameter, allowing you to disable parallelisation if you set it to `FALSE`.

As for your question regarding the specific sets of calibration you would like to use, you can only give to the [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) function the calibration columns you would like to use. The function should provide you then with tuned parameters for MAXENT, and you can use the `user.defined` configuration to set these modeling options to your [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, as you did previously : 


```
### tune parameters for MAXENT
tuned.maxent <- bm_Tuning(
  model = "MAXENT", 
  tuning.fun = "ENMevaluate", 
  bm.options = opt.d@options$MAXENT.binary.MAXENT.MAXENT,
  bm.format = x_data,
  calib.lines = cv.k[, grep(paste0("PA", 5:8, collapse = "|"), colnames(cv.k)],
  metric.eval = "or.mtp.avg"
)


### tune parameters for XGBOOST
tuned.xgboost <- bm_Tuning(
  model = "XGBOOST", 
  tuning.fun = "xgbTree", 
  bm.options = opt.d@options$XGBOOST.binary.xgboost.xgboost,
  bm.format = x_data,
  calib.lines = cv.k[, grep(paste0("PA", 1:4, collapse = "|"), colnames(cv.k)]
)


### tune parameters for Random Forest
tuned.rf <- bm_Tuning(
  model = "RF", 
  tuning.fun = "rf", 
  bm.options = opt.d@options$RF.binary.randomForest.randomForest,
  bm.format = x_data,
  calib.lines = cv.k[, grep(paste0("PA", 1:4, collapse = "|"), colnames(cv.k)]
)

# Change the nodesize parameter and ntree for all PAs and RUNs
## Random Forest
for(n in names(tuned.rf)){
  tuned.rf[[n]] <- c(tuned.rf[[n]], nodesize = 10)
}

for(n in names(tuned.rf)){
  tuned.rf[[n]] <- c(tuned.rf[[n]], ntree = 250)
}

## Integrate tuned list to opt.d
user.val <- list()
user.val$MAXENT.binary.MAXENT.MAXENT <- tuned.maxent
user.val$XGBOOST.binary.xgboost.xgboost <- tuned.xgboost
user.val$RF.binary.randomForest.randomForest <- tuned.rf


opt.d <- bm_ModelingOptions(
  data.type = "binary", 
  models = c("MAXENT", "RF", "XGBOOST"), 
  strategy = "user.defined", 
  user.val = user.val, 
  bm.format = x_data, 
  calib.lines = cv.k
)
```

Hope it will help and work ! 👀 
Maya

**Comment by suicmezburak** [comment]
Hello Maya,
Thanks for the help regarding to use specific sets of calibration issue. Thanks to your guidance, I no longer encounter any problems in that regard. Thank you repeatedly.

As for the Maxent tune issue, I have tested it; unfortunately, it still produces an error. Here is the code and error code;
```r
### tune parameters for MAXENT
tuned.maxent <- bm_Tuning(
  model = "MAXENT", 
  tuning.fun = "ENMevaluate", 
  bm.options = opt.d@options$MAXENT.binary.MAXENT.MAXENT,
  bm.format = pterocarya_data,
  calib.lines = cv.k,
  metric.eval = "or.mtp.avg",
  params.train = list(MAXENT.parallel = FALSE)
  )

> Dataset _PA1_RUN1
			> Tuning parameters...
		> Dataset _PA1_RUN2
			> Tuning parameters...
		> Dataset _PA1_RUN3
			> Tuning parameters...
		> Dataset _PA1_RUN4
			> Tuning parameters...
		> Dataset _PA1_RUN5
			> Tuning parameters...
### Repeating for all dataset like this
Error in { : task 1 failed - "argument is of length zero"
``` 

```r
traceback()
4: stop(simpleError(msg, call = expr))
3: e$fun(obj, substitute(ex), parent.frame(), e$data)
2: foreach(PA.i = combi$PA, calib.i = combi$calib, dataset.i = combi$name_dataset) %do% 
       {
           cat(paste0("\n\t\t> Dataset ", dataset.i))
           argstmp <- bm.options@args.default
           if (model == "MAXNET") {
               warning("No tuning available for that model. Sorry.")
           }
           else {
               if (model %in% c("MAXENT", "SRE")) {
                   cat("\n\t\t\t> Tuning parameters...")
                   mySpExpl <- get_species_data(bm.format)
                   mySpExpl[["_allData_allRun"]] <- TRUE
                   mySpExpl <- mySpExpl[which(calib.lines[, calib.i] == 
                     TRUE), ]
                   mySpExpl <- mySpExpl[which(mySpExpl[, PA.i] == 
                     TRUE), ]
                   myResp <- mySpExpl[, 1]
                   myExpl <- mySpExpl[, 4:(3 + ncol(bm.format@data.env.var))]
                   if (params.train$MAXENT.algorithm == "maxnet") {
                     mySpExpl[["_allData_allRun"]] <- NULL
    ...
1: bm_Tuning(model = "MAXENT", tuning.fun = "ENMevaluate", bm.options = opt.d@options$MAXENT.binary.MAXENT.MAXENT, 
       bm.format = pterocarya_data, calib.lines = cv.k, metric.eval = "or.mtp.avg", 
       params.train = list(MAXENT.parallel = FALSE))
``` 
Thanks again for all the trouble 🙏🙏🙏
Burak

**Comment by MayaGueguen** [comment]
Hello Burak,

Indeed, I did a mistake in the code in how to retrieve `params.train` values.
I just pushed a correction onto the github version.
Could you try and reinstall `biomod2` to test ? :pray: 

Maya

**Comment by suicmezburak** [comment]
Hello Maya, 
The code worked 👏👏👏 . Thank you for your valuable time. 🙏🙏🙏
