### ISSUE TITLE
Help with BIOMOD_projection - how to customize the resulting plots

### ISSUE THREAD

**Issue by carmerlun** [biomodhub/biomod2#417]
I fitted different models using biomod2 (GLM, MAXNET, RF...). Now I am making predictions using the biomod_projection function, focusing first in the RF model.  I am interested in watching the results visually so I am using the plot() function, like this:

```
plot(
  x,
  coord = NULL,
  plot.output,
  do.plot = TRUE,
  std = TRUE,
  scales,
  size,   <======
  ...
) 
```

But in order to use these plots in a report or paper, I need to customize the format to some extend. Can I change the text size or make other changes in the layout? I'm confused since I don't know if I can use the arguments of terra plot, ggplot, etc. I've had no success with the size parameter suggested above. 

**Here is an example of my code:** 

```
projection_output_1 <- BIOMOD_Projection(
  bm.mod = my_model_RF,
  new.env = new_environ,
  proj.name = "testing_winter",
  models.chosen	= get_built_models(models_RF),
  metric.binary = 'TSS',
  output.format = '.grd'
)

#plotting attempt, but I preffer the png below
plot(projection_output_1, size = 50)

# creating a png file
png("Figures/plot_1.png",
    width = 2000, height = 1000,
    units = "px", pointsize = 30, bg = "white"
)
plot(predict_summer_present_1, size = 50) 
dev.off()

```

What I get are three plots in a horizontal arrangement since I chose three 'runs'. Changing the value of the size parameter makes no difference at all in any of the code tested so far. Is there a way to customize the plot?

**Comment by HeleneBlt** [comment]
Hi ! 

Indeed the `plot` function for `BIOMOD.projection.out` object doesn't allow more modifications.  However, all the projections can be found in your files `species_name/testing_winter`. You can find the link in `projection_output_1@proj.out@link`
You can load them and plot them with terra as you want. 
Please note you can also keep them in memory with the argument `keep.in.memory` in the [`BIOMOD_Projection`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function.

Hope it helps.
Hélène

**Comment by carmerlun** [comment]
Thank you very much, Hélène, that certainly solves my problem.
