### ISSUE TITLE
Question about bm_Findoptimstat - ROC uses the wrong threshold?

### ISSUE THREAD

**Issue by EllieHarris-1** [biomodhub/biomod2#418]
I am not sure if this is a bug or a misunderstanding of the processes/outputs on my end.

I have an ensemble model of 5 PA datasets (so PA1_allRun, PA2_allRun etc). I wanted to get the evaluation scores of TSS, ROC, and KAPPA but using the same threshold for each one (the TSS threshold as this is what my binary transformations are based on).

Once I had the ensemble model evaluations, I plugged the TSS threshold into bm_Findoptimstat to get the values for Kappa and ROC at this threshold. Whilst Kappa and TSS seem to be running as expected, the output for ROC does not use the threshold that I have specified.

In the reproducible example below, I have specified a random threshold of 656, and you can see that the TSS and KAPPA metrics use this threshold, but the ROC uses a threshold of 693. Why is it that this is not using the specified threshold?

Thanks in advance for your help!

```
# (using the example code from the bm_Findoptimstat help page)
# Generate a binary vector
set.seed(5)
vec.a <- sample(c(0, 1), 100, replace = TRUE)

# Generate a 0-1000 vector (random drawing)
vec.b <- runif(100, min = 0, max = 1000)

# Find optimal threshold for a specific evaluation metric
bm_FindOptimStat(metric.eval = 'TSS', fit = vec.b, obs = vec.a, threshold = 656)
# metric.eval cutoff sensitivity specificity   best.stat 
#   TSS    656    42.30769    72.91667 0.1522436 

bm_FindOptimStat(metric.eval = 'ROC', fit = vec.b, obs = vec.a, threshold = 656)
# metric.eval   cutoff sensitivity specificity best.stat         
#  ROC 693.5839    40.38462    79.16667 0.5909455

bm_FindOptimStat(metric.eval = 'KAPPA', fit = vec.b, obs = vec.a, threshold = 656)
# metric.eval cutoff sensitivity specificity   best.stat 
# KAPPA    656    42.30769    72.91667 0.1501976

```

**Comment by HeleneBlt** [comment]
Hello there, 

Thanks for your comment 🙏 
Indeed, there is a difference with ROC. It doesn't take into account the threshold you've given it. To get the ROC values, it is necessary to create the ROC curve, so with all the different thresholds.
After, it returns the best threshold (693). 
You can create yourself the roc curves with `pROC::roc` and look for the sensitivity and specificity associated with your threshold but it's not possible to have an Area Under the Curve for a single threshold. 

Don't hesitate to ask if it's not clear. 
Hélène

**Comment by EllieHarris-1** [comment]
Ah yes of course! Thank you
