### ISSUE TITLE
Help with BIOMOD -  C drive increasing GB & getting full  -- where does biomod2 write files to 

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#420]
Dear Helpful biomod2 team

Please - i am running models for 15 species - using my R working directory on an external hard drive "D" and yet my laptop C drive keeps filling up and I am not sure why.

So please for example today I started as follows
Laptop C Drive showed 35.8 GB free
External D Drive R folder showed 134GB stored and this is my working directory. 

Then I ran biomod2 for one species, pine marten, only 60 records 180 absences for current and future climate projections, though at large scale, a whole country at hectare pixel (which biomod2 handles magnificently).

Afterwards I see as follows
Laptop C Drive now shows 27.7GB free (therefore 8 GB has been created somewhere)
External D Drive R folder now shows 139 GB stored and the folder with pine marten shows as 5.2 GB.
So please do we know how it is the C drive has been taken up with so much extra data and GB.
Because in theory it all should have gone to the D Drive folder (?)

Please is there perhaps a temporary or hidden folder somewhere that biomod2 is also writing to on the C drive?
I have tried Windows searches for large files and yet cannot locate anything new which was created today.  

Thank you if you have any knowledge or can offer any advice.
With best wishes, Carlos

**Comment by carlosbedson** [comment]
Hello again - i have found that files are being written to a folder as follows
C:Users/MyName/AppData/Local/Temp/ and then for example RtmpiOP1gw   which contains about 170GB of tifs      such as spat_215QKoOpWOrD4SG_340.tif   

Please is this how things are supposed to work.   If so, please is there a way I can manage / reduce / externally store these tifs.   Otherwise my C drive keeps filling up.  

Thank you for any advice.  With best wishes Carlos

**Comment by HeleneBlt** [comment]
Hi Carlos, 

The culprit is not Biomod2 here but other packages we use that create temporary files. 
I think a big part comes from Terra. You can check where it writes it with `terraOptions()` (I bet `C:Users/MyName/AppData/Local/Temp/RtmpiOP1gw` ) and you can change the path with `terraOptions(tempdir=)`. 

Let me know if the problem comes from something else, 
Hélène

**Comment by HeleneBlt** [comment]
Yes, by the intermediary of Terra, Biomod2 will sometimes need access to temporary files and it will get confused if you change the path or remove the files. But I suppose if you set the temporary files and your working directory at the beginning of the session, it will be fine. 
For the difference between Binary and Probability, I think it comes from the size differences. Terra can have different ways to save it (and maybe doesn't need temporary files if it's light enough 🤔 ) 

Hope it will help to lighten your hard drive.
Hélène

**Comment by carlosbedson** [comment]
Hello Helene - thank you so much for your very helpful and informative reply.   I appreciate it.   
I have redone these models and everything is working fine.
However I would please just make a little suggestion to explain on biomod2 website or somewhere about this various file architecture.   In my instance I had run some (for me) large models which were of 13 layers, each 13m pixels with up to 45000 p/a points - and each time making a large GB of outputs and taking 8 hours to run on my laptop.   
I don't know how this compares to others - whether i am overly ambitious or greedy for data.  However - it works very well - and biomod2 is impressive for tackling it.  
Once run, I had mistakenly moved these to the external drive and then the links with the temporary files broke so I had to rerun them all again.  This was no great hardship because I worked on other things in parallel. 
However please what I would say is to describe this architecture somewhere: the importance of having working directory aligned, output projection files aligned and the terra temporary folder all aligned.  In my instance for these 16 species, as per above, I now have on my external drive 406GB biomod2 outputs and of this 260GB is in the terra temporary folder.   This is all working fine - and my laptop is not overburdened.     
Thank you so much again for your help.  With best wishes Carlos
