### ISSUE TITLE
Bias file - How can I add a bias file when using MaxEnt?

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#421]
Hi!

Does anybody know how to add a bias file when using MaxEnt in both the old a new versions of biomod2?

Didn't find anything about that in the instructions of the package.
I looked for a suggestion on ChatGPT, and the indication I got concern the addition of a _bias_ argument.
In the end, code looked like this:

biasfile <- raster("path/biasfile.tif")

BIOMOD_Modeling(...,
                                 bias = biasfile)

I ran the code and it did not produce any errors. The results yielded a slight improvement, but I would like to double-check this is the right approach.

Thanks!
L

**Comment by MayaGueguen** [comment]
Hello Luis,

You can find in the **Note** section of the [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) documentation page the list of the different parameters that can be passed to MaxEnt through `biomod2`.
I'm afraid the *biasfile* is not in the list :grimacing: 

Maya

**Comment by luispedrosantiago** [comment]
Hi Maya,

Has this been addressed in the newer versions?
Thanks!

Luis

**Comment by MayaGueguen** [comment]
Hello Luis,

I'm afraid we did not change MAXENT parameters in the last version 😬 
So no, the `biasfile` parameter is still not included within our MAXENT parametrization in biomod2.

Sorry for the inconvenience,
Maya
