### ISSUE TITLE
NEED HELP！There is something wrong with the results projected onto future variables

### ISSUE THREAD

**Issue by AlilLearner** [biomodhub/biomod2#426]
Dear Biomood2 people，Please help me with my confusion.

**Context and question**
The code works fine and the projection using contemporary variables is as expected, but when using future climate variables, the projections look completely unreasonable and appear to be using an unfiltered algorithm for projection. In addition, I tried to use future climate variables to operate as contemporary climate variables, and the results were as expected, which should verify that it is not a problem with variables.

**Related code** _(optional)_
# wd
setwd("G:/samVar2/AG")

# package
library(tidyverse)   
library(terra)       
library(tidyterra)   
library(ggspatial)   
library(biomod2)    

# coordinate
Anoplolepisgracilipes_occ <- read.csv("G:/rawbio/coordinates/AGfinal.csv")   
head(Anoplolepisgracilipes_occ)  

# species name
myRespName <- "Anoplolepisgracilipes"  

# occ
myResp <- as.numeric(Anoplolepisgracilipes_occ[, myRespName])   

# xy
myRespXY <- Anoplolepisgracilipes_occ[, c("Longitude", "Latitude")]   

# var
bioclim_ZA_sub <- raster::stack(   
  c(
    bio02 = 'G:/rawbio/bioR/bioR10masc/bio2.asc',    
    bio04 = 'G:/rawbio/bioR/bioR10masc/bio4.asc',
    bio06 = 'G:/rawbio/bioR/bioR10masc/bio6.asc',
    bio12 = 'G:/rawbio/bioR/bioR10masc/bio12.asc',
    bio18 = 'G:/rawbio/bioR/bioR10masc/bio18.asc',
    bio19 = 'G:/rawbio/bioR/bioR10masc/bio19.asc'
  )
)
myExpl <- rast(bioclim_ZA_sub)   

# data formating
myBiomodData <- BIOMOD_FormatingData(
  resp.var = myResp,       
  expl.var = myExpl,        
  resp.xy = myRespXY,       
  resp.name = myRespName,  
  PA.nb.rep = 8,           
  PA.nb.absences = 10000,   
  PA.strategy = 'random'   
)

# single model
modeling_id <- "AllModels"            
nb_rep <- 10                                  
data_split_perc <- 75                       
var_import <- 3                             
metric_eval <- c("TSS", "ROC")          
nb_cpu <- 8                                   
do_full_models <- FALSE                 
seed.val = 42

myBiomodModelOut <- BIOMOD_Modeling(
  bm.format = myBiomodData,
  modeling.id = modeling_id,
  nb.rep = nb_rep,
  data.split.perc = data_split_perc,
  var.import = var_import,
  metric.eval = metric_eval,
  nb.cpu = nb_cpu,
  do.full.models = do_full_models,
  seed.val = seed.val
)
myBiomodModelOut  

# evaluate
evaluation_data <- get_evaluations(myBiomodModelOut)

# EMbyMetric
myBiomodEM <- BIOMOD_EnsembleModeling(
  bm.mod = myBiomodModelOut,
  models.chosen = "all",
  em.by = "all",
  metric.select = c("TSS","AUC"),
  metric.select.thresh = c(0.75,0.9),
  var.import = 3,
  metric.eval = c("TSS", "ROC"),
  em.algo = c("EMmean", "EMcv", "EMci", "EMmedian", "EMca", "EMwmean"),
  EMci.alpha = 0.05,
  EMwmean.decay = "proportional"
)
myBiomodEM

# EMcurrent
myBiomodEMProj <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  bm.proj = myBiomodProj,
  models.chosen = "all",
  metric.binary = "all",
  metric.filter = "all",
  output.format = ".tif",
  do.stack = FALSE
)

myBiomodEMProj <- BIOMOD_EnsembleForecasting(
  bm.em = myBiomodEM,
  proj.name = "CurrentEM",
  new.env = myExpl,
  models.chosen = "all",
  metric.binary = "all",
  metric.filter = "all",
  output.format = ".tif",
  do.stack = FALSE
)
myBiomodEMProj

# Example for a question on BIOMOD_EnsembleModeling output

![660edf3d2994e1241a73ac34c3316bb](https://github.com/biomodhub/biomod2/assets/157278469/c0e9acf5-5526-4113-a5d2-8113101f02e6)
![edd1fc3bac480231ab80afa30b2bb92](https://github.com/biomodhub/biomod2/assets/157278469/02525467-cd3b-4cdf-ad22-ad3ac73e4c46)

myBiomodData <- BIOMOD_FormatingData( ** write arguments here **)
show(myBiomodData)
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  Anoplolepisgracilipes

	 256 presences,  0 true absences and  92488 undefined points in dataset

	 6 explanatory variables

     bio02            bio04            bio06             bio12          bio18            bio19     
 Min.   : 1.000   Min.   :   0.0   Min.   :-49.724   Min.   :   0   Min.   :   0.0   Min.   :   0  
 1st Qu.: 8.534   1st Qu.: 359.6   1st Qu.:-24.638   1st Qu.: 262   1st Qu.:  85.0   1st Qu.:  23  
 Median :11.045   Median : 782.7   Median : -3.904   Median : 509   Median : 177.0   Median :  58  
 Mean   :10.964   Mean   : 815.6   Mean   : -6.998   Mean   : 739   Mean   : 218.4   Mean   : 138  
 3rd Qu.:13.362   3rd Qu.:1254.9   3rd Qu.: 10.234   3rd Qu.: 983   3rd Qu.: 285.0   3rd Qu.: 134  
 Max.   :21.148   Max.   :2363.8   Max.   : 26.300   Max.   :7142   Max.   :3727.0   Max.   :4466  

 10 Pseudo Absences dataset available ( PA1, PA2, PA3, PA4, PA5, PA6, PA7, PA8, PA9, PA10 ) with  
10000 (PA1, PA2, PA3, PA4, PA5, PA6, PA7, PA8, PA9, PA10) pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
show(myExpl) # if using an environment raster
# <html>
<body>

> show(myExpl) class       : SpatRaster  dimensions  : 836, 2154, 6  (nrow, ncol, nlyr) resolution  : 0.1666667, 0.1666667  (x, y) extent      : -179.5, 179.5, -55.83333, 83.5  (xmin, xmax, ymin, ymax) coord. ref. : +proj=longlat +datum=WGS84 +no_defs  sources     : bio2.asc                 bio4.asc                 bio6.asc                 ... and 3 more source(s) names       : bio02, bio04, bio06, bio12, bio18, bio19  

> show(myExpl30126) class       : SpatRaster  dimensions  : 836, 2154, 6  (nrow, ncol, nlyr) resolution  : 0.1666667, 0.1666667  (x, y) extent      : -179.5, 179.5, -55.83333, 83.5  (xmin, xmax, ymin, ymax) coord. ref. : +proj=longlat +datum=WGS84 +no_defs  sources     : bio1.asc                 bio2.asc                 bio7.asc                 ... and 3 more source(s) names       : bio02, bio04, bio06, bio12, bio18, bio19
--
> | >
>

</body>
</html>

myBiomodModelOut <- BIOMOD_Modeling( ** write arguments here **)
show(myBiomodModelOut)
#<html>
<body>

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  Modeling folder : .  Species modeled : Anoplolepisgracilipes  Modeling id : AllModels  Considered variables : bio02 bio04 bio06 bio12 bio18 bio19   Computed Models :  Anoplolepisgracilipes_PA1_RUN1_GLM Anoplolepisgracilipes_PA1_RUN1_GBM  Anoplolepisgracilipes_PA1_RUN1_GAM Anoplolepisgracilipes_PA1_RUN1_CTA Anoplolepisgracilipes_PA1_RUN1_ANN  Anoplolepisgracilipes_PA1_RUN1_SRE Anoplolepisgracilipes_PA1_RUN1_FDA Anoplolepisgracilipes_PA1_RUN1_MARS  Anoplolepisgracilipes_PA1_RUN1_RF Anoplolepisgracilipes_PA1_RUN1_MAXNET Anoplolepisgracilipes_PA1_RUN1_XGBOOST  Anoplolepisgracilipes_PA2_RUN1_GLM Anoplolepisgracilipes_PA2_RUN1_GBM Anoplolepisgracilipes_PA2_RUN1_GAM  Anoplolepisgracilipes_PA2_RUN1_CTA Anoplolepisgracilipes_PA2_RUN1_ANN Anoplolepisgracilipes_PA2_RUN1_SRE  Anoplolepisgracilipes_PA2_RUN1_FDA Anoplolepisgracilipes_PA2_RUN1_MARS Anoplolepisgracilipes_PA2_RUN1_RF  Anoplolepisgracilipes_PA2_RUN1_MAXNET Anoplolepisgracilipes_PA2_RUN1_XGBOOST Anoplolepisgracilipes_PA3_RUN1_GLM  Anoplolepisgracilipes_PA3_RUN1_GBM Anoplolepisgracilipes_PA3_RUN1_GAM Anoplolepisgracilipes_PA3_RUN1_CTA  Anoplolepisgracilipes_PA3_RUN1_ANN Anoplolepisgracilipes_PA3_RUN1_SRE Anoplolepisgracilipes_PA3_RUN1_FDA  Anoplolepisgracilipes_PA3_RUN1_MARS Anoplolepisgracilipes_PA3_RUN1_RF Anoplolepisgracilipes_PA3_RUN1_MAXNET  Anoplolepisgracilipes_PA3_RUN1_XGBOOST Anoplolepisgracilipes_PA4_RUN1_GLM Anoplolepisgracilipes_PA4_RUN1_GBM  Anoplolepisgracilipes_PA4_RUN1_GAM Anoplolepisgracilipes_PA4_RUN1_CTA Anoplolepisgracilipes_PA4_RUN1_ANN  Anoplolepisgracilipes_PA4_RUN1_SRE Anoplolepisgracilipes_PA4_RUN1_FDA Anoplolepisgracilipes_PA4_RUN1_MARS  Anoplolepisgracilipes_PA4_RUN1_RF Anoplolepisgracilipes_PA4_RUN1_MAXNET Anoplolepisgracilipes_PA4_RUN1_XGBOOST  Anoplolepisgracilipes_PA5_RUN1_GLM Anoplolepisgracilipes_PA5_RUN1_GBM Anoplolepisgracilipes_PA5_RUN1_GAM  Anoplolepisgracilipes_PA5_RUN1_CTA Anoplolepisgracilipes_PA5_RUN1_SRE Anoplolepisgracilipes_PA5_RUN1_FDA  Anoplolepisgracilipes_PA5_RUN1_MARS Anoplolepisgracilipes_PA5_RUN1_RF Anoplolepisgracilipes_PA5_RUN1_MAXNET  Anoplolepisgracilipes_PA5_RUN1_XGBOOST Anoplolepisgracilipes_PA6_RUN1_GLM Anoplolepisgracilipes_PA6_RUN1_GBM  Anoplolepisgracilipes_PA6_RUN1_GAM Anoplolepisgracilipes_PA6_RUN1_CTA Anoplolepisgracilipes_PA6_RUN1_ANN  Anoplolepisgracilipes_PA6_RUN1_SRE Anoplolepisgracilipes_PA6_RUN1_FDA Anoplolepisgracilipes_PA6_RUN1_MARS  Anoplolepisgracilipes_PA6_RUN1_RF Anoplolepisgracilipes_PA6_RUN1_MAXNET Anoplolepisgracilipes_PA6_RUN1_XGBOOST  Anoplolepisgracilipes_PA7_RUN1_GLM Anoplolepisgracilipes_PA7_RUN1_GBM Anoplolepisgracilipes_PA7_RUN1_GAM  Anoplolepisgracilipes_PA7_RUN1_CTA Anoplolepisgracilipes_PA7_RUN1_ANN Anoplolepisgracilipes_PA7_RUN1_SRE  Anoplolepisgracilipes_PA7_RUN1_FDA Anoplolepisgracilipes_PA7_RUN1_MARS Anoplolepisgracilipes_PA7_RUN1_RF  Anoplolepisgracilipes_PA7_RUN1_MAXNET Anoplolepisgracilipes_PA7_RUN1_XGBOOST Anoplolepisgracilipes_PA8_RUN1_GLM  Anoplolepisgracilipes_PA8_RUN1_GBM Anoplolepisgracilipes_PA8_RUN1_GAM Anoplolepisgracilipes_PA8_RUN1_CTA  Anoplolepisgracilipes_PA8_RUN1_SRE Anoplolepisgracilipes_PA8_RUN1_FDA Anoplolepisgracilipes_PA8_RUN1_MARS  Anoplolepisgracilipes_PA8_RUN1_RF Anoplolepisgracilipes_PA8_RUN1_MAXNET Anoplolepisgracilipes_PA8_RUN1_XGBOOST  Anoplolepisgracilipes_PA9_RUN1_GLM Anoplolepisgracilipes_PA9_RUN1_GBM Anoplolepisgracilipes_PA9_RUN1_GAM  Anoplolepisgracilipes_PA9_RUN1_CTA Anoplolepisgracilipes_PA9_RUN1_ANN Anoplolepisgracilipes_PA9_RUN1_SRE  Anoplolepisgracilipes_PA9_RUN1_FDA Anoplolepisgracilipes_PA9_RUN1_MARS Anoplolepisgracilipes_PA9_RUN1_RF  Anoplolepisgracilipes_PA9_RUN1_MAXNET Anoplolepisgracilipes_PA9_RUN1_XGBOOST Anoplolepisgracilipes_PA10_RUN1_GLM  Anoplolepisgracilipes_PA10_RUN1_GBM Anoplolepisgracilipes_PA10_RUN1_GAM Anoplolepisgracilipes_PA10_RUN1_CTA  Anoplolepisgracilipes_PA10_RUN1_ANN Anoplolepisgracilipes_PA10_RUN1_SRE Anoplolepisgracilipes_PA10_RUN1_FDA  Anoplolepisgracilipes_PA10_RUN1_MARS Anoplolepisgracilipes_PA10_RUN1_RF Anoplolepisgracilipes_PA10_RUN1_MAXNET  Anoplolepisgracilipes_PA10_RUN1_XGBOOST   Failed Models :  Anoplolepisgracilipes_PA5_RUN1_ANN Anoplolepisgracilipes_PA8_RUN1_ANN  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
--
 
> | >
>

</body>
</html>

myBiomodEM <- BIOMOD_EnsembleModeling( ** write arguments here **)
show(myBiomodEM)
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.ensemble.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

sp.name : Anoplolepisgracilipes

expl.var.names : bio02 bio04 bio06 bio12 bio18 bio19

models computed: 
Anoplolepisgracilipes_EMmeanByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMcvByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMmedianByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMcaByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMciInfByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMciSupByTSS_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMmeanByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMcvByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMmedianByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMcaByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMwmeanByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMciInfByROC_mergedData_mergedRun_mergedAlgo, Anoplolepisgracilipes_EMciSupByROC_mergedData_mergedRun_mergedAlgo

models failed: none

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# for a question on evaluation of ensemble models:
get_evaluations(myBiomodEM)
# <html>
<body>

> get_evaluations(myBiomodEM)                                                              full.name merged.by.PA merged.by.run merged.by.algo 1    Anoplolepisgracilipes_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 2    Anoplolepisgracilipes_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 3  Anoplolepisgracilipes_EMmedianByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 4  Anoplolepisgracilipes_EMmedianByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 5      Anoplolepisgracilipes_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 6      Anoplolepisgracilipes_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 7   Anoplolepisgracilipes_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 8   Anoplolepisgracilipes_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 9    Anoplolepisgracilipes_EMmeanByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 10   Anoplolepisgracilipes_EMmeanByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 11 Anoplolepisgracilipes_EMmedianByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 12 Anoplolepisgracilipes_EMmedianByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 13     Anoplolepisgracilipes_EMcaByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 14     Anoplolepisgracilipes_EMcaByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 15  Anoplolepisgracilipes_EMwmeanByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo 16  Anoplolepisgracilipes_EMwmeanByROC_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo    filtered.by     algo metric.eval cutoff sensitivity specificity calibration validation evaluation 1          TSS   EMmean         TSS  511.0      95.312      92.354       0.877         NA         NA 2          TSS   EMmean         ROC  511.5      95.312      92.370       0.978         NA         NA 3          TSS EMmedian         TSS  422.0      97.266      90.370       0.877         NA         NA 4          TSS EMmedian         ROC  425.5      97.266      90.451       0.976         NA         NA 5          TSS     EMca         TSS  530.0      96.484      90.539       0.870         NA         NA 6          TSS     EMca         ROC  531.5      96.484      90.539       0.973         NA         NA 7          TSS  EMwmean         TSS  512.0      95.312      92.350       0.877         NA         NA 8          TSS  EMwmean         ROC  514.5      95.312      92.425       0.978         NA         NA 9          ROC   EMmean         TSS  461.0      96.875      94.622       0.915         NA         NA 10         ROC   EMmean         ROC  468.5      96.875      94.817       0.990         NA         NA 11         ROC EMmedian         TSS  452.0      97.266      93.448       0.907         NA         NA 12         ROC EMmedian         ROC  456.5      97.266      93.549       0.983         NA         NA 13         ROC     EMca         TSS  545.0      96.875      93.075       0.899         NA         NA 14         ROC     EMca         ROC  544.0      96.875      93.075       0.993         NA         NA 15         ROC  EMwmean         TSS  464.0      96.875      94.580       0.915         NA         NA 16         ROC  EMwmean         ROC  472.5      96.875      94.803       0.990         NA         NA
--
 
> | >
>

</body>
</html>
```

**Other outputs** _(optional)_
If your question is about a figure or a map, you can add a screenshot here.

**Environment Information** _(optional)_
If the question relates to model output, please paste the output of `sessionInfo()` in your current R session below.
```
# paste output of sessionInfo() here
```

**Comment by MayaGueguen** [comment]
Hello there,

It seems that you are not using the most recent versions of `biomod2`.
You can install the 4.2-4 version through `install.packages` command, or the last one from the github (4.2-5) with : 
```
library(devtools)
install_github("biomodhub/biomod2")
```

As for your projections, I don't manage to see very well your data with your copy/paste :eyes: 
Are your present and future data on the same scales / ranges ?

Maya

**Comment by AlilLearner** [comment]
Thank you for your reply!
first of all,the data in present and future are on the same scales / ranges, and I'll run the code after updating the version and see if that fixes the problem, hopefully you can wait for me.
Best.
