### ISSUE TITLE
Behaviour of undocumented model parameters in `BIOMOD_ModelingOptions`, with the case of random forests

### ISSUE THREAD

**Issue by Farewe** [biomodhub/biomod2#43]
Hello there,

I would like to learn what happens if we request a model parameter undocumented in the help file of `BIOMOD_ModelingOptions`?
Will this parameter be passed to the model, or will it be ignored?

For example, for random forest models, [recent studies have suggested that specifying the sample size](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.05615) is of paramount importance for the quality of RF predictions. [Specifically, it has been shown that random forest models can be the worst modelling technique with default parameters, and the best modelling technique when down-sampled](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecm.1486) (i.e., when the sample size argument, `sampsize` is tuned). 

I would like to know what happens if we specify this parameter in `BIOMOD_ModelingOptions`, despite it is not officially documented? 

If this is an unsupported feature at the moment, I would like to request it to be implemented in the near future, because of the significance of the new results on the importance of this parameter? 

Thanks a lot
Boris

**Comment by MayaGueguen** [comment]
Hello Boris,

I'm very sorry for the late answer...
Indeed, `sampsize` is not included in RF modeling options in `BIOMOD_ModelingOptions` function.
Unfortunately, when it is the case, even if you add it to the modeling options, in `biomod2 `code it will not be given as new value to the [`randomForest`](http://127.0.0.1:10068/library/randomForest/html/randomForest.html) function. Therefore default value of the function will be used, in that case : `if (replace) nrow(x) else ceiling(.632*nrow(x))`.

But I noted it, that this should be included.
I'm currently cleaning `biomod2` package and code, and hope to release it soon. I'll try to make sure to include this at the same time.

Sorry for the inconvenience.
Maya

**Comment by Farewe** [comment]
Hi Maya,

that's good to know, thank you. 👍 

I am looking forward to the release of the new version of biomod2. Do you have an estimated time of release, if that's possible given the amount of work it must represent? ;)

Cheers
