### ISSUE TITLE
Error when trying to plot model evaluation scores. 

### ISSUE THREAD

**Issue by Arjunpal96** [biomodhub/biomod2#435]
I was trying to plot the model evaluation scores but an error was shown.

## define individual models options ---- 
ProLau_opt <- 
  BIOMOD_ModelingOptions(
    GLM = list(type = 'quadratic', interaction.level = 1),
    GBM = list(n.trees = 1000),
    GAM = list(algo = 'GAM_mgcv')
  )

## run the individual models ----
ProLau_models <- 
  BIOMOD_Modeling(
    bm.format = ProLau_data,
    models = c("GLM", "GBM", "RF", "GAM", "MAXENT"),
    bm.options = ProLau_opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = 3,
    metric.eval = c("KAPPA", "TSS", "ROC")
  )

## get models evaluation scores
ProLau_models_scores <- get_evaluations(ProLau_models)

## ProLau_models_scores is a 5 dimension array containing the scores of the models
dim(ProLau_models_scores)
dimnames(ProLau_models_scores)

## plot models evaluation scores
bm_PlotEvalMean(
  ProLau_models,
  by = "models", 
  metrics = c("KAPPA","ROC","TSS"), 
  xlim = c(0.5,1), 
  ylim = c(0.5,1)
)

This was the error:
> ## plot models evaluation scores
> bm_PlotEvalMean(
+   ProLau_models,
+   by = "models", 
+   metrics = c("ROC","TSS"), 
+   xlim = c(0.5,1), 
+   ylim = c(0.5,1)
+ )
Error in .fun_testIfIn(TRUE, "names(args)", names(args), c("xlim", "ylim",  : 
  
names(args) must be 'xlim', 'ylim' or 'main

**Comment by HeleneBlt** [comment]
Hello, 

Here, `xlim` and `ylim` are right but the arguments `by` and `metrics` don't exist. As you can see in the documentation of [bm_PlotEvalMean](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalMean.html), the arguments are `group.by` and `metric.eval` . You will also need to change `"models"` into `"algo"`. 
Normally, with these modifications, your code must work. 

Hope it helps. 
Hélène

**Comment by Arjunpal96** [comment]
I am a beginner in species distribution modelling and biomod. Can you please tell me what changes I need to make in the code for ##plot models evaluation scores?

**Comment by HeleneBlt** [comment]
Hi again, 

Indeed I should have put the code directly!

```
bm_PlotEvalMean(
ProLau_models,
group.by = "algo",
metric.eval = c("KAPPA","ROC","TSS"),
xlim = c(0.5,1),
ylim = c(0.5,1)
)
```
Don't hesitate to tell me if you still face some errors,

Hélène
