### ISSUE TITLE
Algorithms selection for moddeling involving cathegorical and continuous variables

### ISSUE THREAD

**Issue by AWys0cki** [biomodhub/biomod2#436]
Dear biomod2 Community,

I am reaching out to seek guidance on selecting appropriate algorithms for modeling species within the Biomod2 framework.

My research incorporating a diverse range of variables, including those related to forest structure, bioclimatic conditions, terrain morphology, etc. Importantly, some of these variables are categorical in nature, such as geomorphons, forest continuity or land cover.

Given this dataset composition, I am curious about which algorithms (GLM, GBM, GAM, CTA, ANN, SRE, FDA, MARS, MAXENT, MAXNET, XGBOOST) would be suitable for my analysis.

Any insights or recommendations regarding the compatibility of these algorithms with my dataset would be greatly appreciated. Your expertise and advice will be invaluable in guiding my research endeavors.

Thank you in advance for your assistance.

Warm regards,
Adrian

**Comment by AWys0cki** [comment]
All variables are raster (.asc) files.

**Comment by HeleneBlt** [comment]
Hello Adrian ! 

SRE and XGBOOST don't accept categorical variables: these two algorithms will be automatically discarded by biomod2. 
All the other algorithms will work. Of course, you must be careful with your variable selection: look at the correlations, not too many variables if you have few occurrences, ...
With categorical variables, decision tree models may have good results but I will advise you to pay attention to the response curves to see if there aren't strange behaviors. 

I hope it helps. 

Hélène

**Comment by AWys0cki** [comment]
Hey Hélène,

Thanks a bunch for your advice on the algorithms! I really appreciate your insights on SRE and XGBOOST, and I'll definitely keep in mind the issue with categorical variables. Your tips on variable selection and checking raster correlations are spot on, and I'll make sure to incorporate them into my analysis.

Cheers
Adrian
