### ISSUE TITLE
Question about clamp mask

### ISSUE THREAD

**Issue by willright28** [biomodhub/biomod2#44]
Hi all
I have a question about using function BIOMOD_Projection with arg "clamping.mask =TURE".  I can see a ClampingMask file in the output "proj_" folder. Does it mean when we use the function BIOMOD_EnsembleForecasting to produce the ensemble forecast the area detected by clamping have been masked automatically? Or if we set "clamping.mask" to FALSE (however the ClampingMask file could still be found), the potential non-analogous area will allow being extrapolated?

Thanks in advance!

**Comment by willright28** [comment]
I checked the clamping mask map and found out that some areas have a value larger than 1, what's this all about?
Are the values equal to one corresponding to the uncertainty in models predictions, right?
Any clues and suggestions are appreciated, thanks!

**Comment by MayaGueguen** [comment]
Hello,

The clamping mask values correspond to the number of variables in each pixel that are out of their calibration / training range, identifying locations where predictions are uncertain. So the higher the value, the more variables out of their calibration range.

Buliding a clamping mask does not imply however that these uncertain areas are masked from projected maps. You will have to decide on your own how you want to deal with these areas.

Hope it helps

Maya

**Comment by willright28** [comment]
Thanks a lot for your help!



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 4, 2022 15:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [biomodhub/biomod2] Question about clamp mask (Issue #44)




 
Hello,
 
The clamping mask values correspond to the number of variables in each pixel that are out of their calibration / training range, identifying locations where predictions are uncertain. So the higher the value, the more variables out of their calibration range.
 
Buliding a clamping mask does not imply however that these uncertain areas are masked from projected maps. You will have to decide on your own how you want to deal with these areas.
 
Hope it helps
 
Maya
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
