### ISSUE TITLE
How do I re-run the output model results

### ISSUE THREAD

**Issue by MrShuaiB1** [biomodhub/biomod2#457]
Dear Developer,

Hello! I am reaching out to commend you on your excellent R package for species distribution modeling. However, I have encountered a few issues that I hope you can help me with.

After running the model, I unfortunately forgot to save the environmental variables, and my R session has since been closed. I found files ending with ".out" in my directory, but I am unsure how to reload the results of the models I've already run in R. Do I need to rerun everything? Considering the large number of species I am working with, this would be a massive undertaking. Is there any code available that could help me reload these output files so I can retrieve the environmental variables? I am currently using biomod2 version 3.5.1.

Please excuse any mistakes in my English, and thank you in advance for your assistance.

Wishing you well in both your personal and professional endeavors.

Best regards
<img width="941" alt="截屏2024-05-13 18 56 26" src="https://github.com/biomodhub/biomod2/assets/156744888/d5586ca1-1811-49a9-8419-6d781c6ab2ac">

**Comment by MrShuaiB1** [comment]
I want to get the impact of environmental variables on the species distribution model, and the image. I want to use the output

**Comment by MayaGueguen** [comment]
Hello Mr Shuai,

Thank you for posting !

Of course, you do not have to re run your simulations each time you re open your session :slightly_smiling_face: 

The `.out` objects within your simulation folder are R object, that you can load in your session with the `load` command : 
```
## load your BIOMOD_Modeling output 
load("Anthemis.cotula/Anthemis.cotula.demo1.models.out")

## Be careful, the object within R as the same name as its filename !
## You can rename it if you prefer : 
myBiomodMod <- Anthemis.cotula.demo1.models.out
```
Once your modeling object is loaded, you have a bunch of functions, starting with `get_[...]` that can help you getting all your results, for example : 
```
## getting evaluation scores
myEval <- get_evaluations(myBiomodMod)
```
You can check the [getters documentation page](https://biomodhub.github.io/biomod2/reference/getters.out.html) for more information.

:information_source: _Note that there is an hidden folder called `.BIOMOD_DATA` created within your simulation folder, containing some of the results and that you should of course not delete. Objects within this folder are also R object that you can also open with the `load` function if needed, but check first the getters we implemented to make your life easier :slightly_smiling_face:_ 

Hope it helps !

Maya

**Comment by MrShuaiB1** [comment]
> Hello Mr Shuai,
> 
> Thank you for posting !
> 
> Of course, you do not have to re run your simulations each time you re open your session 🙂
> 
> The `.out` objects within your simulation folder are R object, that you can load in your session with the `load` command :
> 
> ```
> ## load your BIOMOD_Modeling output 
> load("Anthemis.cotula/Anthemis.cotula.demo1.models.out")
> 
> ## Be careful, the object within R as the same name as its filename !
> ## You can rename it if you prefer : 
> myBiomodMod <- Anthemis.cotula.demo1.models.out
> ```
> 
> Once your modeling object is loaded, you have a bunch of functions, starting with `get_[...]` that can help you getting all your results, for example :
> 
> ```
> ## getting evaluation scores
> myEval <- get_evaluations(myBiomodMod)
> ```
> 
> You can check the [getters documentation page](https://biomodhub.github.io/biomod2/reference/getters.out.html) for more information.
> 
> ℹ️ _Note that there is an hidden folder called `.BIOMOD_DATA` created within your simulation folder, containing some of the results and that you should of course not delete. Objects within this folder are also R object that you can also open with the `load` function if needed, but check first the getters we implemented to make your life easier 🙂_
> 
> Hope it helps !
> 
> Maya

Dear MayaGueguen,

Thank you very much for your prompt and meticulous response. Based on the information you provided, I successfully loaded the individual models.

However, when I tried to reconstruct the ensemble species distribution model using the loaded individual model results, I encountered an error in R. In my previous attempt to construct the ensemble model, I did not specify the quantity for "VarImport = 0," and as a result, I was unable to obtain the variable importance for the ensemble model.

Therefore, I would like to specify this variable and use the results of each individual model to reconstruct the ensemble model to obtain the environmental variable importance. However, I am facing difficulties in doing so. Could you kindly assist me once again?

Best regards,
Shuai
<img width="1027" alt="截屏2024-05-14 11 15 52" src="https://github.com/biomodhub/biomod2/assets/156744888/2d475ba8-4eb6-40f3-9678-249eeec3022e">

**Comment by MrShuaiB1** [comment]
Thank you very much for your help, but I can't seem to rebuild the integration model in R with the ensemble models loaded, and I'm asking for your help

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/13/2024 21:16 |
| To | biomodhub/biomod2 ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [biomodhub/biomod2] How do I re-run the output model results (Issue #457) |

Hello Mr Shuai,

Thank you for posting !

Of course, you do not have to re run your simulations each time you re open your session 🙂

The .out objects within your simulation folder are R object, that you can load in your session with the load command :

## load your BIOMOD_Modeling output 
load("Anthemis.cotula/Anthemis.cotula.demo1.models.out")

## Be careful, the object within R as the same name as its filename !
## You can rename it if you prefer : 
myBiomodMod <- Anthemis.cotula.demo1.models.out


Once your modeling object is loaded, you have a bunch of functions, starting with get_[...] that can help you getting all your results, for example :

## getting evaluation scores
myEval <- get_evaluations(myBiomodMod)


You can check the getters documentation page for more information.

ℹ️ Note that there is an hidden folder called .BIOMOD_DATA created within your simulation folder, containing some of the results and that you should of course not delete. Objects within this folder are also R object that you can also open with the load function if needed, but check first the getters we implemented to make your life easier 🙂

Hope it helps !

Maya

**Comment by MayaGueguen** [comment]
Hello Shuai,

Glad to hear that we are making progress :slightly_smiling_face: 
:warning: Be sure to check your working directory : you should not be inside your species simulaion folder, ie directly where you have `.out` object but in the upper folder.

Maya

**Comment by MrShuaiB1** [comment]
Additionally, if I set VarImport = 0 (i.e., not selecting variable importance) compared to setting VarImport = 1, will there be significant differences in the prediction results of the ensemble models?



在 2024-05-14 15:45:34，"MayaGueguen" ***@***.***> 写道：

Hello Shuai,

Glad to hear that we are making progress 🙂
⚠️ Be sure to check your working directory : you should not be inside your species simulaion folder, ie directly where you have .out object but in the upper folder.

Maya

**Comment by MrShuaiB1** [comment]
Dear Maya,

It's wonderful to receive your reply so quickly. I promptly modified the code as you suggested, successfully ran it, and obtained the variable importance for the individual models.

To get the variable importance for the ensemble models, should I set VarImport = 1 in the BIOMOD_EnsembleModeling function? I have already received a column of data. I noticed that increasing the number in this line of code provides more columns of variable importance. Could you please confirm if this is the correct approach?

Additionally, if I set VarImport = 0 (i.e., not selecting variable importance) compared to setting VarImport = 1, will there be significant differences in the prediction results of the ensemble models? Or does changing this value only affect the output of variable importance without impacting the ensemble model performance?

Thank you once again for your and the developers' dedication. I truly admire your work in developing such a powerful R package and your active support in helping users solve various issues. My sincere respect to you all!

Best wishes,
Shuai



在 2024-05-14 15:45:34，"MayaGueguen" ***@***.***> 写道：

Hello Shuai,

Glad to hear that we are making progress 🙂
⚠️ Be sure to check your working directory : you should not be inside your species simulaion folder, ie directly where you have .out object but in the upper folder.

Maya

**Comment by MayaGueguen** [comment]
Thank you for your kind feedbacks :heart: 
It is always appreciated :sun_with_face: 

Now, for your questions about variables importance, the principle of the calculation is : 
> For each variable to be evaluated : 
> - shuffle the original variable
> - compute model prediction with shuffled variable
> - calculate Pearson's correlation between reference and shuffled predictions
> - return score as 1 - cor

(see [bm_VariablesImportance](https://biomodhub.github.io/biomod2/reference/bm_VariablesImportance.html) function for details and format of result)

Hence, the number you give to `var.import` parameter (within [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions) corresponds to the number of times you will shuffle each variable.

This will not have any impact on predicted values, model performances, or anything else.
:warning: The only impact on your simulation will be the **computation time**, as it will rerun predictions for all concerned single models each time it shuffles a variable.

Hope it will be clearer now !

Maya

**Comment by MrShuaiB1** [comment]
Dear Maya,

Thank you once again for all your help and the invaluable support you and the developers provide. I truly admire your dedication and hard work in developing such a powerful R package. I hope more people can benefit from it.

Best wishes for a wonderful life!

Sincerely,
Shuai



在 2024-05-14 16:50:36，"MayaGueguen" ***@***.***> 写道：

Thank you for your kind feedbacks ❤️
It is always appreciated 🌞

Now, for your questions about variables importance, the principle of the calculation is :

For each variable to be evaluated :

shuffle the original variable
compute model prediction with shuffled variable
calculate Pearson's correlation between reference and shuffled predictions
return score as 1 - cor

(see bm_VariablesImportance function for details and format of result)

Hence, the number you give to var.import parameter (within BIOMOD_Modeling or BIOMOD_EnsembleModeling functions) corresponds to the number of times you will shuffle each variable.

This will not have any impact on predicted values, model performances, or anything else.
⚠️ The only impact on your simulation will be the computation time, as it will rerun predictions for all concerned single models each time it shuffles a variable.

Hope it will be clearer now !

Maya
