### ISSUE TITLE
Error in BIOMOD_ModelingOptions

### ISSUE THREAD

**Issue by SHANTIKUMARI12345** [biomodhub/biomod2#459]
**Context and question**
Getting an error in BIOMOD_ModelingOptions 

**Code used**
## setup environment ----
> library(mda)
> library(gam)
> library(earth)
> library(maxnet)
> library(xgboost)
> ## load the required packages
> library(biomod2)
> library(ggplot2)
> library(gridExtra)
> library(raster)
> library(rasterVis)
> library(tidyterra)
> ## read data ----
> ProLau_occ <- read.csv('../data/ProLau_occ.csv')
> summary(ProLau_occ)
      long            lat         Protea.laurifolia
 Min.   :18.38   Min.   :-34.38   Min.   :1        
 1st Qu.:18.88   1st Qu.:-33.83   1st Qu.:1        
 Median :19.12   Median :-33.38   Median :1        
 Mean   :19.39   Mean   :-33.16   Mean   :1        
 3rd Qu.:19.38   3rd Qu.:-32.62   3rd Qu.:1        
 Max.   :31.03   Max.   :-30.40   Max.   :1        
> bioclim_ZA_sub <- 
+   raster::stack(
+     c(
+       bio_5  = '../data/worldclim_ZA/worldclim_ZA_bio_5.asc',
+       bio_7  = '../data/worldclim_ZA/worldclim_ZA_bio_7.asc',
+       bio_11 = '../data/worldclim_ZA/worldclim_ZA_bio_11.asc',
+       bio_19 = '../data/worldclim_ZA/worldclim_ZA_bio_19.asc'
+     )
+   )
> bioclim_ZA_sub
class      : RasterStack 
dimensions : 219, 175, 38325, 4  (nrow, ncol, ncell, nlayers)
resolution : 0.1666667, 0.1666667  (x, y)
extent     : 11.66668, 40.83334, -47, -10.5  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
names      : bio_5, bio_7, bio_11, bio_19 

> ## format the data ----
> ProLau_data <- 
+   BIOMOD_FormatingData(
+     resp.var = ProLau_occ['Protea.laurifolia'],
+     resp.xy = ProLau_occ[, c('long', 'lat')],
+     expl.var = bioclim_ZA_sub,
+     resp.name = "Protea.laurifolia",
+     PA.nb.rep = 2,
+     PA.nb.absences = 500,
+     PA.strategy = 'random'
+   )

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Protea.laurifolia Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation
 !!! Some data are located in the same raster cell. 
          Please set `filter.raster = TRUE` if you want an automatic filtering.

Checking Pseudo-absence selection arguments...

      ! No data has been set aside for modeling evaluation
   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables

 ! Some NAs have been automatically removed from your data
      ! No data has been set aside for modeling evaluation
 !!! Some data are located in the same raster cell. 
          Please set `filter.raster = TRUE` if you want an automatic filtering.
      ! No data has been set aside for modeling evaluation
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> ## formatted object summary
> ProLau_data

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  Protea.laurifolia

	 520 presences,  0 true absences and  937 undefined points in dataset

	 4 explanatory variables

     bio_5           bio_7           bio_11          bio_19   
 Min.   : 92.0   Min.   : 92.0   Min.   : 25.0   Min.   :  0  
 1st Qu.:271.0   1st Qu.:232.0   1st Qu.: 97.0   1st Qu.: 24  
 Median :293.0   Median :264.0   Median :110.0   Median : 51  
 Mean   :294.1   Mean   :262.8   Mean   :111.1   Mean   :113  
 3rd Qu.:316.0   3rd Qu.:299.0   3rd Qu.:124.0   3rd Qu.:163  
 Max.   :383.0   Max.   :352.0   Max.   :187.0   Max.   :586  

 2 Pseudo Absences dataset available ( PA1, PA2 ) with  500 (PA1, PA2) pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> ## plot of selected pseudo-absences
> #install.packages('ggtext')
> library(ggtext)
> plot(ProLau_data)
$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 2560, 2  (geometries, attributes)
 extent      : 14.58334, 37.58334, -46.91667, -22.25  (xmin, xmax, ymin, ymax)
 coord. ref. :  
 names       :  resp         dataset
 type        : <num>           <chr>
 values      :    10 Initial dataset
                  10 Initial dataset
                  10 Initial dataset

$data.label
                              9                              10 
                "**Presences**"       "Presences (calibration)" 
                             11                              12 
       "Presences (validation)"        "Presences (evaluation)" 
                             19                              20 
            "**True Absences**"   "True Absences (calibration)" 
                             21                              22 
   "True Absences (validation)"    "True Absences (evaluation)" 
                             29                              30 
          "**Pseudo-Absences**" "Pseudo-Absences (calibration)" 
                             31                               1 
 "Pseudo-Absences (validation)"                    "Background" 

$data.plot

> ## define individual models options ---- 
> ProLau_opt <- 
+   BIOMOD_ModelingOptions(
+     GLM = list(type = 'quadratic', interaction.level = 1),
+     GBM = list(n.trees = 100),
+     GAM = list(algo = 'GAM_mgcv')
+   )
Error in BIOMOD_ModelingOptions(GLM = list(type = "quadratic", interaction.level = 1),  : 
  could not find function "BIOMOD_ModelingOptions"s"

**Comment by MayaGueguen** [comment]
Hello there,

It seems that you have updated your biomod2 version :eyes: 
You can check which one you have by typing : `packageVersion("biomod2")`.

Switching from version 4.2-4 to 4.2-5, `BIOMOD_ModelingOptions` has been replaced by [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html). This function can be used together with `OPT.[...]` parameters within [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.

We created a [specific page tutorial](https://biomodhub.github.io/biomod2/articles/vignette_modelingOptions.html) to guide and help through this new way of providing modeling options.

Please have a look, and do not hesitate to come back to us if you still have questions !

Maya

**Comment by SHANTIKUMARI12345** [comment]
## setup environment ----

setwd("H:/biomod2-tutorial-material-master/biomod2-tutorial-material-master/biomod2_video_single_species_modelling/workdir")
## install the latest release of biomod2
devtools::install_github('biomodhub/biomod2', lib = 'C:/Users/phd-shanti')
## load the required packages
library(biomod2)

> packageVersion("biomod2")
[1] ‘4.2.5’

> ## load the required packages   ##Here I  Got an error 

> library(biomod2)

Error: package or namespace load failed for ‘biomod2’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘vctrs’ 0.6.3 is already loaded, but >= 0.6.4 is required

##  the update file of vctrs is located at this location C:\Users\phd-shanti\vctrs but while loading library biomod2 it is taking vctrs old version 

##I had previously used biomod2 on this system with a default path, but as Its asking me to update various attached library within biomod2 so I changed my path of installation. There might be some lingering configurations or package versions causing conflicts. How to address this please help me in this ?

**Comment by MayaGueguen** [comment]
Hello Shantiku,

R has been updated quite fast recently, so you might have either version 4.3.3 or 4.4.0 already.
Most of your packages were installed under 4.3.1 so that's why you get the warning messages.

- You can either choose to install the more recent version of R, so you will have to reinstall all of your packages, but you will start from fresh and new bases.
- Or you can stay with your version, but be sure to :
     - remove all install versions you have of `vctrs` with `remove.packages("vctrs")` 
     - update all packages you have already installed (_for example in RStudio, go in `Tools -> Check for Packages Updates`_)
     - try and install all of your packages in the same place 

Hope it helps,
Maya

**Comment by SHANTIKUMARI12345** [comment]
"Hello, ma'am/sir,

Thank you for your response.

I would like to inquire about something else: if I were to use the updated/latest version of R by removing old packages, and at the same time use Biomod2 source code that was developed four years ago, it's possible that errors might occur in subsequent lines of the default script and data. Rectifying each error could take a significant amount of time. Please pardon me for any inconvenience and suggest me some other way.
With regards
Shanti

**Comment by SHANTIKUMARI12345** [comment]
Hello sir/madam

I was trying current version and got error as 
## run the individual models ----
ProLau_models <-  
  bm_ModelingOptions(
  data.type,
  models = c("ANN", "CTA", "FDA", "GAM", "GBM", "GLM", "MARS", "MAXENT", "MAXNET", "RF",
             "SRE", "XGBOOST"),
  strategy,
  user.val = NULL,
  user.base = "bigboss",
  bm.format = NULL,
  calib.lines = NULL
)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Error: object 'data.type' not found

Here I am attaching my code 
[source code.docx](https://github.com/biomodhub/biomod2/files/15325121/source.code.docx)

**Comment by MayaGueguen** [comment]
Hello Shanti,

If your script is 4 years old, then you were probably working with the 3.5-1 or 3.5-3 biomod2 version.
A lot of cleaning and reorganisation was done to switch to 4.1.1 version, and we continued our cleaning and improving job since then. So there is now a big difference between the versions, and we do not provide support anymore for old versions, sorry for that.

Archive are available [here on github](https://github.com/biomodhub/biomod2/tags) or [here on CRAN](https://cran.r-project.org/src/contrib/Archive/biomod2/), it is up to you to try and install those old versions on R current version.
:warning: But I would advise against it, first because dependencies might not work, and second because the cleaning allow us to correct quite a lot of errors that were present in the code at that time, and code is much more robust now.

If you were to switch to current biomod2 version, we have a lot of material to help you with the transition on our [documentation website](https://biomodhub.github.io/biomod2/) : 
- global example presenting the [main functions](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html)
- and examples going a bit more in details for [secundary functions](https://biomodhub.github.io/biomod2/articles/examples_2_secundaryFunctions.html)
(_functions called and used by main functions, but that can also be used directly by the user if needed_)
- a [new presentation](https://biomodhub.github.io/biomod2/articles/vignette_presentation.html) summarizing all the different tools and functions available in biomod2

On addition to all that, we have specific tutorials for different aspects (for example for [modeling options](https://biomodhub.github.io/biomod2/articles/vignette_modelingOptions.html)) and all functions are documented with details and examples (for example for [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html)).

Please have a look to these materials and do not hesitate to come back to us for hep or questions :eyes: 

Maya

**Comment by SHANTIKUMARI12345** [comment]
Hello mam/sir,

Can you please help me in this, 
I was installing biomod2 and got stuck while loading the library. Here, I am attaching the documents containing details that show many packages are not available in my library or location. 
This might be a silly mistake, apologies for that but help me to rectify it.

[biomd2_library.txt](https://github.com/biomodhub/biomod2/files/15344484/biomd2_library.txt)

**Comment by MayaGueguen** [comment]
Hello Shanti,

For missing packages, please install them through the usual `install.packages` command : 
```
install.packages(c("mda", "gam", "earth", "maxnet", "randomForest", "xgboost"))
```

As for the `bioclim_current.rda` object, it is simply an R object that can be open with the `load` command, and that we provide for users for tutorials and examples (see [documentation](https://biomodhub.github.io/biomod2/reference/bioclim_current.html)).

This is completely independent of how you handle, create and prepare your own data to give to `biomod2` functions.

As for analysing biomod2 outputs, we provide a lot of [getters](https://biomodhub.github.io/biomod2/reference/getters.out.html) (like for example [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html)) and plot functions (all starting with `bm_Plot[...]`, like for example [bm_PlotEvalBoxplot](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalBoxplot.html)) and you can find the list of all functions [here](https://biomodhub.github.io/biomod2/reference/index.html), and they are all brielfy presented in this [presentation](https://biomodhub.github.io/biomod2/articles/vignette_presentation.html) I mentioned you above.

Alos, please have a look at the [complete tutorial](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) to get a better idea of outputs and how to deal with them.

Maya

**Comment by SHANTIKUMARI12345** [comment]
Hello mam/sir,

I was trying BIOMOD_EnsembleModeling with my own dataset using the code source [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html)
and got stuck here 
> # Model ensemble models
> myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
+                                       models.chosen = 'all',
+                                       em.by = 'all',
+                                       em.algo = c('EMmean', 'EMca'),
+                                       metric.select = c('TSS'),
+                                       metric.select.thresh = c(0.7),
+                                       metric.eval = c('TSS', 'ROC'),
+                                       var.import = 3,
+                                       seed.val = 42)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
  ! Ensemble Models will be filtered and/or weighted using validation dataset (if possible). Please use `metric.select.dataset` for alternative options.
   > Evaluation & Weighting methods summary :
      TSS over 0.7

!!! Removed models using the Full dataset as ensemble models cannot merge repetition dataset (RUN1, RUN2, ...) with Full dataset unless em.by = 'PA+run'.

     !! Ensemble Model mergedData_mergedRun_mergedAlgo selected by TSS have no model selected and will fail.
     !! Please make sure this is intended or review your selection metrics and threshold.

  > mergedData_mergedRun_mergedAlgo ensemble modeling
   ! No models kept due to threshold filtering... Ensemble Modeling will fail!
   ! Note :  Burans_EMmeanByTSS_mergedData_mergedRun_mergedAlgo failed!

   ! Note :  Burans_EMcaByTSS_mergedData_mergedRun_mergedAlgo failed!

! All models failed

Here I am attaching my entire details in docs file 
https://github.com/biomodhub/biomod2/files/15368351/biomodensamble_Rconsol.docx, please open it once and suggest me some solution.
Thanks in advance.

With Regards
Shanti

**Comment by SHANTIKUMARI12345** [comment]
Hello mam/sir,

I was using source code from [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html)
# Model single models       -   This part is running successful
# Model ensemble models -   Got an error in section metric.select.thresh = c(0.6)  

1. I need help with setting or checking the metric.select.thresh = c(0.6) value while working on the ensemble models section to avoid errors. I tried changing the value to 0.4 and others, but I still got an error. I want to check the threshold value of models first.
