### ISSUE TITLE
implement 'SpatVector' and 'SpatRaster' input formats from pkg 'terra'

### ISSUE THREAD

**Issue by AMBarbosa** [biomodhub/biomod2#46]
Hi, as some spatial packages evolve while others become obsolete (with some of them disappearing as soon as next year), I think it would be important to implement 'SpatVector' (besides / instead of 'SpatialPoints') and 'SpatRaster' (besides / instead of 'RasterStack') inputs from package 'terra', e.g. in functions `BIOMOD_FormatingData` and `BIOMOD_Projection`. These formats also usually make the code run visibly faster, e.g. with 'predict' functions. Is this implementation predicted to happen soon in 'biomod2'? Cheers!

**Comment by MayaGueguen** [comment]
Hi there,

Thank you for the suggestion.
I'm currently cleaning the biomod2 package, that will hopefully help both users and maintainers. Once this work done, we will be able to consider improvements of the package, but this is not a next-month priority.

Sorry for the inconvenience.

Maya

**Comment by rpatin** [comment]
Hi there,
`SpatRaster` and `SpatVector` are now handled by the package in the current github version (4.2-0).
You can update with 
```
devtools::install_github('biomodhub/biomod2')
```
Cheers,
Rémi
