### ISSUE TITLE
Modeling options not working

### ISSUE THREAD

**Issue by ShreePoudel0** [biomodhub/biomod2#461]
Hello.
It seems there was an update that changed BIOMOD_ModelingOptions to bm_modelingoptions. I was manually changing the parameters of RF and GBM. Now i dont know how to do it. I didnt understand the tutorial mentioned in previous issue regarding same problem. Can you explain how the function works now.
Thank you

**Comment by MayaGueguen** [comment]
Hello Shree,

Yes, switching from version 4.2-4 to 4.2-5, `BIOMOD_ModelingOptions` has been replaced by [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html). This function can be used together with `OPT.[...]` parameters within [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.

In your case, you would like to modify yourself some options, so using `strategy = 'user.defined'`.
Did you have a look at our [modeling options vignette](https://biomodhub.github.io/biomod2/articles/vignette_modelingOptions.html) (the User defined section at the end) ? :eyes: 

Which parameters would like to change in `RF` and `GBM` ?
You can also check if they are already set in the way you want within the biomod2 [bigboss](https://biomodhub.github.io/biomod2/reference/OptionsBigboss.html) options.

Maya

**Comment by ShreePoudel0** [comment]
Hello. I read the vignette of modeling options but couldnt implement it well.
myBiomodOption <- BIOMOD_ModelingOptions(RF= list(nodesize = 15,
                                                  maxnodes = 10),
                                         GBM = list(n.trees = 500))
This was what i used previously in BIOMOD_modelingoptions. How do we implement this in current bm_modelingoptions functions?
Thank you

**Comment by MayaGueguen** [comment]
Hello Shree,

```
## Here are the parameters you want to change :
user.RF <- list('_allData_allRun' = list(nodesize = 15))
user.GBM <- list('_allData_allRun' = list(n.trees = 500))

## Gather in one list
## Models names can be found in OptionsBigboss@models
user.val <- list(RF.binary.randomForest.randomForest = user.RF,
                 GBM.binary.gbm.gbm = user.GBM)

myOpt <- bm_ModelingOptions(data.type = 'binary',
                            models = c("RF", "GBM"),
                            strategy = "user.defined",
                            user.val = user.val,
                            user.base = "bigboss")
print(myOpt)
```

Maya

**Comment by MayaGueguen** [comment]
Hello Shree,

I made a correction to my previous answer, please check and try again.
You have to give your output from the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function to the [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) function.

Maya
