### ISSUE TITLE
BIOMOD_Projection (future bioclim): [subset] invalid name(s)

### ISSUE THREAD

**Issue by Biomoduser** [biomodhub/biomod2#462]
My model has been successfully built, but I made an error in projecting future climate data.

My error:  Error: [subset] invalid name(s)

The code I used:
bioclim_ZA_2040_ssp126 <-
  raster::stack(
    c(Bio1  = 'bio1_ssp126_2021-2040.asc',
      Bio2  = 'bio2_ssp126_2021-2040.asc',
      Bio3  = 'bio3_ssp126_2021-2040.asc',
      Bio7  = 'bio7_ssp126_2021-2040.asc',
      Bio12 = 'bio12_ssp126_2021-2040.asc',
      Bio14  = 'bio14_ssp126_2021-2040.asc',
      Bio15  = 'bio15_ssp126_2021-2040.asc'
    )
  )
bioclim_ZA_2040_ssp126
?BIOMOD_Projection
ProLau_models_proj_2040_ssp126 <- 
  BIOMOD_Projection(
    bm.mod = ProLau_models_2,
    new.env = bioclim_ZA_2040_ssp126,
    proj.name = "2040_ssp126",
    binary.meth = "TSS",
    output.format = ".img",
    do.stack = FALSE
  )
I have built details of successful models（ProLau_models_2）:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Modeling folder : .

Species modeled : fatua

Modeling id : fourModels

Considered variables : Bio1 Bio2 Bio3 Bio7 Bio12 Bio14 Bio15 AK AN AP PH SOM 
TP Aspect Slope HF

Computed Models :  fatua_PA1_RUN1_GLM fatua_PA1_RUN1_GBM fatua_PA1_RUN1_RF 
fatua_PA1_RUN1_MARS fatua_PA1_RUN2_GLM fatua_PA1_RUN2_GBM fatua_PA1_RUN2_RF 
fatua_PA1_RUN2_MARS fatua_PA1_RUN3_GLM fatua_PA1_RUN3_GBM fatua_PA1_RUN3_RF 
fatua_PA1_RUN3_MARS fatua_PA1_RUN4_GLM fatua_PA1_RUN4_GBM fatua_PA1_RUN4_RF 
fatua_PA1_RUN4_MARS fatua_PA1_RUN5_GLM fatua_PA1_RUN5_GBM fatua_PA1_RUN5_RF 
fatua_PA1_RUN5_MARS fatua_PA1_allRun_GLM fatua_PA1_allRun_GBM 
fatua_PA1_allRun_RF fatua_PA1_allRun_MARS fatua_PA2_RUN1_GLM 
fatua_PA2_RUN1_GBM fatua_PA2_RUN1_RF fatua_PA2_RUN1_MARS fatua_PA2_RUN2_GLM 
fatua_PA2_RUN2_GBM fatua_PA2_RUN2_RF fatua_PA2_RUN2_MARS fatua_PA2_RUN3_GLM 
fatua_PA2_RUN3_GBM fatua_PA2_RUN3_RF fatua_PA2_RUN3_MARS fatua_PA2_RUN4_GLM 
fatua_PA2_RUN4_GBM fatua_PA2_RUN4_RF fatua_PA2_RUN4_MARS fatua_PA2_RUN5_GLM 
fatua_PA2_RUN5_GBM fatua_PA2_RUN5_RF fatua_PA2_RUN5_MARS fatua_PA2_allRun_GLM 
fatua_PA2_allRun_GBM fatua_PA2_allRun_RF fatua_PA2_allRun_MARS 
fatua_allData_allRun_GLM fatua_allData_allRun_GBM fatua_allData_allRun_RF 
fatua_allData_allRun_MARS

Failed Models :  none

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Details of future climate data I used:
class      : RasterStack 
dimensions : 357, 551, 196707, 7  (nrow, ncol, ncell, nlayers)
resolution : 0.04166667, 0.04166667  (x, y)
extent     : 73.45833, 96.41667, 34.33333, 49.20833  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
names      :  Bio1, Bio2, Bio3, Bio7, Bio12, Bio14, Bio15 
min values : -18.2,    ?,    ?,    ?,     ?,     ?,     ? 
max values :    17,    ?,    ?,    ?,     ?,     ?,     ? 

Screenshot of my running interface:
![屏幕截图 2024-05-22 135226](https://github.com/biomodhub/biomod2/assets/170496370/5ad701b7-a949-4c8e-89dc-34149224c29b)

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for posting with detailed informations :pray: 

With the print of your `ProLau_models_2` object, I see that you ran your single models with 16 variables : 

> Considered variables : Bio1 Bio2 Bio3 Bio7 Bio12 Bio14 Bio15 AK AN AP PH SOM TP Aspect Slope HF

However, when building your `bioclim_ZA_2040_ssp126` object, containing your new environment, you give it only the bioclim variables, and not the other variables (AK AN AP PH SOM TP Aspect Slope HF).
You need to give for projections all the same variables that you used to build the models.

But indeed, the error message could be clearer, we'll try to work on that !

Maya

**Comment by MayaGueguen** [comment]
For your information, I just submitted a correction on the github version, to have a clearer error message in such situation :slightly_smiling_face: 
You can install it if you want with : 
```
library(devtools)
install_github("biomodhub/biomod2")
```
Maya

**Comment by Biomoduser** [comment]
> Hello there,
> 
> Thank you for posting with detailed informations 🙏
> 
> With the print of your object, I see that you ran your single models with 16 variables :`ProLau_models_2`
> 
> > Considered variables : Bio1 Bio2 Bio3 Bio7 Bio12 Bio14 Bio15 AK AN AP PH SOM TP Aspect Slope HF
> 
> However, when building your object, containing your new environment, you give it only the bioclim variables, and not the other variables (AK AN AP PH SOM TP Aspect Slope HF). You need to give for projections all the same variables that you used to build the models.`bioclim_ZA_2040_ssp126`
> 
> But indeed, the error message could be clearer, we'll try to work on that !
> 
> Maya

Thank you very much for your answer. 
This is very useful for me. These other variables (AK AN AP PH SOM TP Aspect Slope HF) have not been added since future changes are not available. But I try to assume that these variables will not change in the future, and then add the variables in the present state to solve the error. Thank you very much for your thoughts. This bag has been very helpful to my research！


Moon

**Comment by Biomoduser** [comment]
> For your information, I just submitted a correction on the github version, to have a clearer error message in such situation 🙂 You can install it if you want with :
> 
> ```
> library(devtools)
> install_github("biomodhub/biomod2")
> ```
> 
> Maya

The modifications you have made are greatly appreciated! They will be invaluable to future users of biomod.
Thank you for your patience and best wishes for the future.

Moon
