### ISSUE TITLE
Help with "BIOMOD_EnsembleModeling" on different device

### ISSUE THREAD

**Issue by Haikalidris** [biomodhub/biomod2#465]
Dear all,

When I working on my analysis, I had a problem re-running the "BIOMOD_EnsembleModeling" on a different device. I have moved all the data that I ran on the previous device to the other device, and I have updated all the link paths related to the results of "BIOMOD_Modeling" such as 'formated.input.data', 'dir.name', 'models.prediction', etc. to the latest link paths because it associated with the data that ensemble command need.

However, I always experience an error like the following:

> javlang.EM.mod02 <- BIOMOD_EnsembleModeling(bm.mod = javlang.models.mod02,
+                                           models.chosen = c("jbl.mod02_PA1_RUN1_GLM",
+                                                             "jbl.mod02_PA1_RUN2_GLM",
+                                                             "jbl.mod02_PA1_RUN3_GLM",
+                                                             "jbl.mod02_PA1_RUN4_GLM",
+                                                             "jbl.mod02_PA1_RUN5_GLM",
+                                                             "jbl.mod02_PA1_RUN1_GBM",
+                                                             "jbl.mod02_PA1_RUN2_GBM",
+                                                             "jbl.mod02_PA1_RUN3_GBM",
+                                                             "jbl.mod02_PA1_RUN4_GBM",
+                                                             "jbl.mod02_PA1_RUN5_GBM",
+                                                             "jbl.mod02_PA1_RUN1_RF",
+                                                             "jbl.mod02_PA1_RUN2_RF",
+                                                             "jbl.mod02_PA1_RUN3_RF",
+                                                             "jbl.mod02_PA1_RUN4_RF",
+                                                             "jbl.mod02_PA1_RUN5_RF",
+                                                             "jbl.mod02_PA1_RUN1_MAXENT",
+                                                             "jbl.mod02_PA1_RUN2_MAXENT",
+                                                             "jbl.mod02_PA1_RUN3_MAXENT",
+                                                             "jbl.mod02_PA1_RUN4_MAXENT",
+                                                             "jbl.mod02_PA1_RUN5_MAXENT"),
+                                           [em.by](http://em.by/) = 'PA+run',
+                                           em.algo = 'EMwmean',
+                                           metric.select.dataset = 'calibration',
+                                           metric.select = 'TSS',
+                                           metric.select.thresh = 0.4,
+                                           metric.eval = c('ROC', 'TSS', 'KAPPA'),
+                                           var.import = 3)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   > Evaluation & Weighting methods summary :
      TSS over 0.4

  > PA1_RUN1_mergedAlgo ensemble modeling
		  original models scores =  0.942 0.721 0.995 0.6
		  final models weights =  0.289 0.221 0.305 0.184
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading
2: In file(file, "rt") :
  cannot open file 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN1_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory

  > PA1_RUN2_mergedAlgo ensemble modeling
		  original models scores =  0.638 0.708 0.996 0.698
		  final models weights =  0.21 0.233 0.328 0.23
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading
2: In file(file, "rt") :
  cannot open file 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN2_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory

  > PA1_RUN3_mergedAlgo ensemble modeling
		  original models scores =  0.726 0.725 0.992 0.618
		  final models weights =  0.237 0.237 0.324 0.202
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading
2: In file(file, "rt") :
  cannot open file 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN3_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory

  > PA1_RUN4_mergedAlgo ensemble modeling
		  original models scores =  0.705 0.72 0.987 0.666
		  final models weights =  0.229 0.234 0.321 0.216
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading
2: In file(file, "rt") :
  cannot open file 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN4_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory

  > PA1_RUN5_mergedAlgo ensemble modeling
		  original models scores =  0.703 0.728 0.995 0.603
		  final models weights =  0.232 0.24 0.328 0.199
   > Probabilities weighting mean by TSS ...
			Evaluating Model stuff...
			Evaluating Predictor Contributions... 
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from a rank-deficient fit may be misleading
2: In file(file, "rt") :
  cannot open file 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN5_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory
Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "Unable to make model prediction"""

Can you help me please by providing instructions regarding which part of "BIOMOD_Modeling" that should be changed so that the Maxent 'Pred_swd.csv' files can be detected?

Thank you in advance
Haikal Idris

**Comment by HeleneBlt** [comment]
Hello there, 

It seems it is an issue only with MAXENT 👀 

Could you : 

- check if the settings for `java` are correct and if you have the `maxent.jar` file in your working directory. 
(You can check if you can run a MAXENT model with biomod2 for example )

- Did you change the option `path_to_maxent.jar` when you did the modelling on the other device? In this case, you will need to change the link in  javlang.models.mod02@models.options  (in the same way you already changed the other links )

Thanks 🙏 
Hélène

**Comment by Haikalidris** [comment]
Hello Hélène,

Thank you for your response

I already checked the maxent.jar in my directory and update the path_to_maxent.jar as well as the javlang.models.mod02@models.options, but it is still have the same error.

All the files that resulted from the previous running is still complete, however, that results for maxent make differents folder that I think contains some of the maxent.jar results

is there any suggestion to change the " 'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN4_MAXENT_outputs/Predictions/Pred_swd.csv': No such file or directory" to the right paths?

Thank you
Haikal

**Comment by Haikalidris** [comment]
Hi Hélène,

Yes it is, the  'D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN4_MAXENT_outputs/Predictions/Pred_swd.csv' is the ancient paths. The new paths is 'E:/R_Project/project/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/jbl.mod02_PA1_RUN1_MAXENT_outputs/Predictions/Pred_swd.csv'

and regarding modeling.id, I don't know if it's normal but it worked fine in the previous process. Maybe I'll consider to try running again with the another model ID and the new paths. 

by the way, if I run it again on my device with the same parameters, will it produce different predictions from the previous run?

Haikal

**Comment by HeleneBlt** [comment]
Hello, 

Thanks for the clarification, I was going in the wrong direction!
MAXENT models are different from the others: it seems you also need to change `model_output_dir` in `D:/Javlang_JBL_2024_mod02/Running_mod02/jbl.mod02/models/./jbl.mod02_PA1_RUN4_MAXENT` . 

I hope it's the last change you have to make. However, if rerunning the models is possible, it can be the easiest solution.  

There's an element of randomness in the models, so the predictions won't be exactly the same. However, if you have defined the seed (with the argument `seed.val`), you'll get the same predictions.

Hélène

**Comment by Haikalidris** [comment]
Hi,

Thank you very much for your help and suggestions. 
I will try to rerun the model and define the seed.val

Thank you
Haikal
