### ISSUE TITLE
Help with BIOMOD_FormatingData - [Problem with the number of presence after PA generation]

### ISSUE THREAD

**Issue by VDjianBiogeo** [biomodhub/biomod2#466]
Hello,

I'm trying to extract the pseudo-absences generated by the ```BIOMOD_FormatingData``` function in order to tune some RF and GBM models with another package. However, I have some issues with the number of pseudo-absences and presences after the PA generation process.

My original dataset has 649 presences at a global scale. I generated as much pseudo-absences as presences in order to have 10 PA datasets. My guess was that I would end up with 1298 points, with my original 649 presences and 649 pseudo-absences. 

```
  data <- mycto.occ[,c("x", "y", sp)] %>%
    na.omit()
  myRespName <- paste(substr(sp, 1, 1), 
                      str_split(sp, pattern = "_", simplify = T)[,2], sep=".")
  
  bm_data <- BIOMOD_FormatingData(resp.var= data[,3],
                                  expl.var= env_filtered,
                                  resp.xy = data[,1:2]), 
                                  resp.name = myRespName,
                                  PA.nb.rep = 10, 
                                  PA.nb.absences = as.integer(nrow(data)), 
                                  PA.strategy = 'sre',
                                  PA.sre.quant = 0.025, 
                                  na.rm = TRUE)
``` 

However, when I look at the number of rows in ```bm_data@PA.table```, I get 6846 rows. And when I look the number of presences using ```bm_data@PA.table$PA1[bm_data@PA.table$PA1 == T]```, I get 1058 presences, wich is more than my original 649 presences. 

And when I do a ```summary``` on my BIOMOD formated data, I get this result:

```
summary(bm_data)

       dataset run   PA Presences True_Absences Pseudo_Absences Undefined
1      initial  NA <NA>       409             0               0      6455
2  calibration  NA  PA1       409             0             649        NA
3  calibration  NA  PA2       409             0             649        NA
4  calibration  NA  PA3       409             0             649        NA
5  calibration  NA  PA4       409             0             649        NA
6  calibration  NA  PA5       409             0             649        NA
7  calibration  NA  PA6       409             0             649        NA
8  calibration  NA  PA7       409             0             649        NA
9  calibration  NA  PA8       409             0             649        NA
10 calibration  NA  PA9       409             0             649        NA
11 calibration  NA PA10       409             0             649        NA 
```
What happened to my presences? How can I extract all PA datasets with the right spatial coordinates associated with the right spatial cell?

Here is my species occurrence file:
[Data.csv](https://github.com/biomodhub/biomod2/files/15466200/Data.csv)

I cannot join my env file, it is too heavy unfortunately. 

Thank you in advance for your help!
Valentin

**Comment by HeleneBlt** [comment]
Hello Valentin, 

Indeed, it can be confusing at first  ! 

So : 
- your ` bm_data@PA.table` have 6846 rows because the points choosen for PA1 are not the same than for PA2 (and PA3,...). So you're gonna have approximately _649 + 649*10 = 7139 points_ (some points could be the same).

- You have only 409 presences in your summary. I suspect you have an message like 
 " !!! Some data are located in the same raster cell. " 
   when you run `BIOMOD_FormatingData`. 

- When you look at `bm_data@PA.table$PA1[bm_data@PA.table$PA1 == T]` , you will find all the points use for this dataset: the presence points + the pseudo absences points _(409 + 649 = 1058)_. 

So if you want to extract the points of PA1 for example: 
`bm_data@data.species[bm_data@PA.table$PA1]`  will give you a vector with `1` for the presences points and `NA` for the pseudo absences points. 
And you can have the coordinates with `bm_data@coord[bm_data@PA.table$PA1, ]`

I hope it's clearer this way. Don't hesitate if you have other questions!

Hélène

**Comment by HeleneBlt** [comment]
Hi again, 

Yes, by default biomod2 removes points if all the environmental variables are not available. You can set the argument `na.rm` to `FALSE` if you want to avoid that. 

For the tuning, we use the package `caret` and only `mtry` are available for the tuning of `RF` with `randomForest`.  
If there are any updates to the caret package, we'll add them quickly. But we had no immediate plan of switching to another package, sorry 😅 
However, you can change all the parameter of `RF` with `bm_ModelingOptions.` More info [here](https://biomodhub.github.io/biomod2/articles/vignette_modelingOptions.html).

Hope it helps ! 
Hélène

**Comment by VDjianBiogeo** [comment]
Hello Hélène,

Ok, that's what I thought, thank you for confirming! Is it better to take them off or to let them in the dataset?

I have another question for the use of ```bm_ModelingOptions```. I have trained GBM and RF models on each PA dataset generated with ```BIOMOD_FormatingData``` in order to define the optimal hyperparameters for each. But is it possible to specify them for each PA dataset with ```bm_ModelingOptions``` (just like when I select "tuned" as argument in ```BIOMOD_Modeling```) or does the same hyperparameters are used for all PA dataset runs? 

If so, is there a way to go past this issue? For example, by going back to the ```BIOMOD_FormatingData``` and putting manually each one of the previously generated PA datasets individually in order to specify the hyperparameters for each one of them? Not sure if I'm making sense, sorry if it's confused.

Thanks anyways!
Valentin

**Comment by HeleneBlt** [comment]
Hello Valentin, 

It depends on which model you use. From memory, CTA accepts NA without any problem for example, but not RF. Generally, I will advise removing them or using an imputation method to have a full dataset. 

In fact, Maya has created bm_ModelingOptions specifically to be able to modify the parameters of each dataset 🥳 

If you give `myBiomodData` to `bm_ModelingOptions`, you will be able to detail the options for all the different PA datasets.
```
user.val <-  list ( RF.binary.randomForest.randomForest =  list( "_PA1_allRun" = RF.options, 
                                                                 "_PA2_allRun" = RF.options,
                                                                 "-allData_allRUn" = RF.options))

myOpt <- bm_ModelingOptions(data.type = 'binary',
                            models = c('RF','GBM'),
                            strategy = "user.defined",
                            user.val = user.val,
                            user.base = "bigboss",
                            bm.format = myBiomodData)
```
`BIOMOD_Modeling` will automatically give the options of "_PAx_allRun" to all run with PAx. 

If you give `calib.lines` to `bm_ModelingOptions`, you could also detail the parameters for each run ("_PA1_RUN1","_PA1_RUN2",..)

Don't hesitate if it's not clear !

Hélène

**Comment by HeleneBlt** [comment]
Hello,

Glad you found it useful! 

The print method for the options shows by default '_allData_allRun" options but you can choose which dataset you want to see : 
`print( (myOpt, dataset = '_PA1_allRun')`  for example

Hélène

**Comment by VDjianBiogeo** [comment]
Hello Hélène,

Again, so fast to reply! Thank you very much for everything :) I'll close the issue with this last comment, you answered all of my questions (for now!) and helped me a lot. Thank you again!

Until next time
Valentin
