### ISSUE TITLE
Error in BIOMOD2 - [Error task 1 failed]

### ISSUE THREAD

**Issue by federicalosacco** [biomodhub/biomod2#469]
**Error and context**

Hi,
 
I am working on a niche modeling of dung beetles endemic to Mauritius.
I am writing you to ask a quick question about your Biomod 2 package. I am currently using this package to generate Ensemble models, but a strange error appear, see attached image.
 
The error says: “Error in {: task 1 failed - "task 1 failed - "replacement has 34 rows, data has 1353""
Have you ever got this tipe of error? Is it directly releated to the package, on some technical issue of this version, a bug, or something that can be solved by changing some parameters in the analysis?
 
Thank you in advance for your help.
 
Regards,
Federica
 

**Session INFO**

> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_3.5.1        raster_3.6-26        sp_2.1-4             terra_1.7-78         xgboost_1.7.7.1      randomForest_4.7-1.1 maxnet_0.1.4        
 [8] earth_5.3.3          plotmo_3.6.3         plotrix_3.8-4        Formula_1.2-5        gbm_2.1.9            mgcv_1.9-1           nlme_3.1-164        
[15] gam_1.22-3           foreach_1.5.2        mda_0.5-4            class_7.3-22         rpart_4.1.23         nnet_7.3-19          biomod2_4.2-5 

loaded via a namespace (and not attached):
 [1] gtable_0.3.5           shape_1.4.6.1          xfun_0.44              lattice_0.22-6         vctrs_0.6.5            tools_4.4.0           
 [7] generics_0.1.3         proxy_0.4-27           tibble_3.2.1           PresenceAbsence_1.1.11 fansi_1.0.6            pkgconfig_2.0.3       
[13] KernSmooth_2.23-22     Matrix_1.7-0           data.table_1.15.4      lifecycle_1.0.4        compiler_4.4.0         farver_2.1.2          
[19] stringr_1.5.1          munsell_0.5.1          codetools_0.2-20       glmnet_4.1-8           tidyr_1.3.1            pillar_1.9.0          
[25] classInt_0.4-10        iterators_1.0.14       abind_1.4-5            commonmark_1.9.1       tidyselect_1.2.1       stringi_1.8.4         
[31] purrr_1.0.2            sf_1.0-16              dplyr_1.1.4            reshape2_1.4.4         labeling_0.4.3         grid_4.4.0            
[37] colorspace_2.1-0       cli_3.6.2              magrittr_2.0.3         survival_3.5-8         utf8_1.2.4             e1071_1.7-14          
[43] withr_3.0.0            scales_1.3.0           tidyterra_0.6.0        ggtext_0.1.2           viridisLite_0.4.2      markdown_1.12         
[49] rlang_1.1.3            gridtext_0.1.5         Rcpp_1.0.12            glue_1.7.0             DBI_1.2.2              xml2_1.3.6            
[55] pROC_1.18.5            reshape_0.8.9          jsonlite_1.8.8         R6_2.5.1               plyr_1.8.9             units_0.8-5    

**Code used to get the error**

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
+                                       models.chosen = 'all',
+                                       em.by = 'all',
+                                       em.algo = c('EMmean', 'EMcv', 'EMci', 'EMmedian', 'EMca', 'EMwmean'),
+                                       metric.select = c('TSS'),
+                                       metric.select.thresh = c(0.7),
+                                       metric.eval = c('TSS', 'ROC'),
+                                       var.import = 3,
+                                       EMci.alpha = 0.05,
+                                       EMwmean.decay = 'proportional')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Ensemble Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

   ! all models available will be included in ensemble.modeling
  ! Ensemble Models will be filtered and/or weighted using validation dataset (if possible). Please use `metric.select.dataset` for alternative options.
   > Evaluation & Weighting methods summary :
      TSS over 0.7

!!! Removed models using the Full dataset as ensemble models cannot merge repetition dataset (RUN1, RUN2, ...) with Full dataset unless em.by = 'PA+run'.

  > mergedData_mergedRun_mergedAlgo ensemble modeling
   ! Additional projection required for ensemble models merging several pseudo-absence dataset...
Error in { : task 1 failed - "task 1 failed - "replacement has 34 rows, data has 1251""

**Comment by federicalosacco** [comment]
Hi,

please find below the whole code I used:

### Load dataset and variables
# Load species occurrences (6 species available)
DataSpecies <- read.csv("Counting_Nesosisyphus.csv", sep = ";")

DataSpecies$loc <- paste(DataSpecies$long, DataSpecies$lat)

occur <- data.frame(matrix(ncol = length(unique(DataSpecies$Species))+2,
                           nrow = length(unique(DataSpecies$loc))))

colnames(occur) <- c("Lon", "Lat", unique(DataSpecies$Species))
for (i in 1:length(occur$Lon)){
  occur$Lon[i] <- DataSpecies$long[DataSpecies$loc == unique(DataSpecies$loc)[i]][1]
  occur$Lat[i] <- DataSpecies$lat[DataSpecies$loc == unique(DataSpecies$loc)[i]][1]
    
  occur[i,unique(DataSpecies$Species[DataSpecies$loc==unique(DataSpecies$loc)[i]])] <- 1
  
}

occur$`Nesosisyphus ` <- 1


# Select the name of the studied species
#Nesosisyphus rotundatus --> only 2 observation == too few
myRespName <- 'Nesosisyphus'

# Get corresponding presence/absence data
myResp <- as.numeric(occur[, myRespName])

# Get corresponding XY coordinates: X-longitude, Y-latitude
myRespXY <- occur[, c('Lon', 'Lat')]

# Load environmental variables extracted from BIOCLIM (bio1, bio5, bio6, bio12, bio16, bio17)

#BIO1 = Annual Mean Temperature
#BIO5 = Max Temperature of Warmest Month
#BIO6 = Min Temperature of Coldest Month
#BIO12 = Annual Precipitation
#BIO16 = Precipitation of Wettest Quarter
#BIO17 = Precipitation of Driest Quarter

fs <- list.files(path="./Mauritius_clim", pattern = "tif$", full.names = TRUE)
s <- raster::stack(fs)
clim <- raster::stackSave(s, "clim")

#myExpl <- rast(clim[[c(1, 15, 16, 4, 8, 9)]])
myExpl <- rast(clim[[c(1, 4)]])

#data("bioclim_current")
#myExpl <- rast(bioclim_current)
```

### Prepare data & parameters

#### Format data (observations & explanatory variables)

# # Format Data with true absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                      expl.var = myExpl,
                                      resp.xy = myRespXY,
                                      resp.name = myRespName)
myBiomodData
plot(myBiomodData)

#### Pseudo-absences extraction
Single or multiple set of pseudo-absences can be selected with the [`BIOMOD_FormatingData`](../reference/BIOMOD_FormatingData.html) function, which calls the [`bm_PseudoAbsences`](../reference/bm_PseudoAbsences.html) function to do so. More examples are presented on the [Secundary functions webpage](examples_2_secundaryFunctions.html).

# # Transform true absences into potential pseudo-absences
myResp.PA <- ifelse(myResp == 1, 1, NA)
# Format Data with pseudo-absences : random method
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 4,
                                       PA.nb.absences = 1000,
                                       PA.strategy = 'random')
myBiomodData.r
plot(myBiomodData.r)



# Select multiple sets of pseudo-absences

# Transform true absences into potential pseudo-absences
myResp.PA <- ifelse(myResp == 1, 1, NA)

# Format Data with pseudo-absences : random method
myBiomodData.multi <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                           expl.var = myExpl,
                                           resp.xy = myRespXY,
                                           resp.name = myRespName,
                                           PA.nb.rep = 4,
                                           PA.nb.absences = c(100, 100, 50, 50),
                                           PA.strategy = 'random')
myBiomodData.multi
summary(myBiomodData.multi)
plot(myBiomodData.multi)


#### Parameterize modeling options

# Create default modeling options

default_options_binary <- bm_ModelingOptions(data.type = "binary", strategy = "default")
print(default_options_binary)


# # Part (or totality) of the print can be copied and customized
# # Below is an example to compute quadratic GLM and select best model with 'BIC' criterium
myBiomodOptions <- BIOMOD_ModelingOptions(
   GLM = list(type = 'quadratic',
              interaction.level = 0,
              myFormula = NULL,
              test = 'BIC',
              family = 'binomial',
              control = glm.control(epsilon = 1e-08,
                                    maxit = 1000,
                                   trace = FALSE)))
myBiomodOptions

# 
# # It is also possible to give a specific GLM formula
# myForm <- 'Sp277 ~ bio3 + log(bio10) + poly(bio16, 2) + bio19 + bio3:bio19'
# myBiomodOptions <- BIOMOD_ModelingOptions(GLM = list(myFormula = formula(myForm)))
# myBiomodOptions

Error: object 'myBiomodOptions' not found


### Model parameters can also be automatically tuned for your specific 
### dataset with an optimization algorithm. The tuning can however 
### be quite long. Duration for tuning all models sequentially 
### with default optimization settings :
### on 1 x 2.5 GHz processor: approx. 45 min tuning all models 
### on 8 x 2.5 GHz processor: approx. 15 min tuning all models 

 library(doParallel)
 cl <- makeCluster(8)
 doParallel::registerDoParallel(cl)
# 
 time.seq <- system.time(
   bm.tuning <- BIOMOD_Tuning(bm.format = myBiomodData, ME.env = myExpl, ME.n.bg = ncell(myExpl)))
# 
 stopCluster(cl)
# 
# plot(bm.tuning$tune.CTA.rpart)
# plot(bm.tuning$tune.CTA.rpart2)
# plot(bm.tuning$tune.RF)
# plot(bm.tuning$tune.ANN)
# plot(bm.tuning$tune.MARS)
# plot(bm.tuning$tune.FDA)
# plot(bm.tuning$tune.GBM)
# plot(bm.tuning$tune.GAM)
# 
# # Get tuned modeling options
myBiomodOptions <- bm.tuning$models.options

Error in bm.tuning$models.options : 
  $ operator is invalid for atomic vectors


### Run modelisation

#### Single models

# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.multi,
                                    bm.options = default_options_binary,
                                    modeling.id = 'AllModels',
                                    CV.strategy = 'random',
                                    CV.nb.rep = 5,
                                    CV.perc = 0.8,
                                    var.import = 3,
                                    metric.eval = c('TSS','ROC'))
                                    # seed.val = 123)
                                    # nb.cpu = 8)
myBiomodModelOut

# Get evaluation scores & variables importance
get_evaluations(myBiomodModelOut)
get_variables_importance(myBiomodModelOut)

# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodModelOut)
bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'algo'))
#bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'run'))
#bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'algo'))
#bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'run'))
#bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'expl.var', 'run'))

# Represent response curves
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'min')
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[3],
                      fixed.var = 'median',
                      do.bivariate = TRUE)
```





How to get the output of print and summary of output from BIOMOD_FormatingData function?


Thank you for your precious help.

Federica

**Comment by MayaGueguen** [comment]
Thank you Federica.

Outputs and prints of the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) fonction can be obtained with the following commands : 
```
myBiomodData
summary(myBiomodData)
plot(myBiomodData)
```

⚠️  I'm not sure that you are using the last version of tutorial. Please have a look at the [main](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) and [secundary](https://biomodhub.github.io/biomod2/articles/examples_2_secundaryFunctions.html) fonctions exemples (_for exemple `BIOMOD_ModelingOptions` does not exist anymore and has been replaced by [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html)_)

Maya

**Comment by federicalosacco** [comment]
Here are the outputs and prints:



> myBiomodData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  Nesosisyphus

	 9 presences,  0 true absences and  25 undefined points in dataset


	 2 explanatory variables

 Mauritius_bio1_subset Mauritius_bio12_subset
 Min.   :18.75         Min.   :18.75         
 1st Qu.:20.18         1st Qu.:20.18         
 Median :20.88         Median :20.88         
 Mean   :21.01         Mean   :21.01         
 3rd Qu.:22.70         3rd Qu.:22.70         
 Max.   :22.87         Max.   :22.87         





> summary(myBiomodData)

  dataset run PA Presences True_Absences Pseudo_Absences Undefined
1 initial  NA NA         9             0               0        25




> plot(myBiomodData)

$data.vect
 class       : SpatVector 
 geometry    : points 
 dimensions  : 9, 2  (geometries, attributes)
 extent      : 57.67882, 57.70412, -20.45132, -20.43775  (xmin, xmax, ymin, ymax)
 coord. ref. :  

$data.label
                              9                              10                              11                              12 
                "**Presences**"       "Presences (calibration)"        "Presences (validation)"        "Presences (evaluation)" 
                             19                              20                              21                              22 
            "**True Absences**"   "True Absences (calibration)"    "True Absences (validation)"    "True Absences (evaluation)" 
                             29                              30                              31                               1 
          "**Pseudo-Absences**" "Pseudo-Absences (calibration)"  "Pseudo-Absences (validation)"                    "Background" 

$data.plot

**Comment by MayaGueguen** [comment]
Hello Federica,

I'm not able for now to reproduce your error or understand where it is coming from.

:warning: But it seems that your data is only containing 9 occurrences, and 25 other points, which is not enough points and too small study area. Just when defining when pseudo-absences, even if you are asking for only 100 or 50 points, it will only select the all 25 points of your environment.

Please, check your study area mask and resolution, to be sure that there is no problem with it :eyes: 

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

I explain you better my situation.

I attach the .csv file I am using for the analysis. I actually have 38 records (points) divided in 4 species plus subfossils records (2 real and 9 simulated) belonging to the same genus Nesosisyphus (roller dung beetles).

Having just two subfossil records from the lowland (SE Mauritius) was not enough for the model to take them into account in the final map. Indeed, we previously tried to run the analysis without the simulated data, and the map was not even showing the subfossil presence (see the attached image "Figure_5", box B - Nesosisyphus spp. + subfossils). 

We decided then to simulate their distribution with 9 extra records, to demonstrate their past distribution in the lowland habitats. But now we are not able to run the analysis because of those errors in the code...

Federica






￼￼

**Comment by MayaGueguen** [comment]
Hello Federica,

Thank you for the update.
Could you please answer through the website ? Via email, I don't see your files attached (csv and figure). :eyes: 
Here is the link of the issue : https://github.com/biomodhub/biomod2/issues/469

Could you also send one of your variable file please ?
It would help me visualise your study area and extent. 

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

ok. Here are is the .csv file 
[Counting_Nesosisyphus.csv](https://github.com/user-attachments/files/15792176/Counting_Nesosisyphus.csv)

and Figure_5 
<img width="479" alt="Figure_5" src="https://github.com/biomodhub/biomod2/assets/103060304/42e78539-febc-4a69-a7bb-cb0e0df2c7d2">


I actually have 38 records (points) divided in 4 species plus subfossils records (2 real and 9 simulated) belonging to the same genus Nesosisyphus (roller dung beetles).

Having just two subfossil records from the lowland (SE Mauritius) was not enough for the model to take them into account in the final map. Indeed, we previously tried to run the analysis without the simulated data, and the map was not even showing the subfossil presence (see the attached image "Figure_5", box B - Nesosisyphus spp. + subfossils).

We decided then to simulate their distribution with 9 extra records, to demonstrate their past distribution in the lowland habitats. But now we are not able to run the analysis because of those errors in the code...


The variable file is a list of .tif files describinf the climate of Mauritius. Unfortunately it doesn't let me upload the data on github... not sure why?

**Comment by MayaGueguen** [comment]
Hello Federica,

Thanks for the `.csv` file.

If I get this correctly, you would like to use biomod2 to model the distribution of all the genus _Nesosisyphus_, ie merging all your observations of _rotundatus + vicinus + regnardi + pygmaeus + subfossils_. Correct ?
This is what is modeled (I think) in your figure "Figure_5", box B - Nesosisyphus spp. + subfossils.

If so  : 
- your file contains 38 points, 34 if keeping only unique coordinates
- but your `myBiomodData` object contains only 9 points, which I thought were the subfossils records only, but you talk about 2 real observations and 9 simulated, which should be 11 points ?
- Also, I asked to see one your variable, because regarding the information you sent, it seems that your study area contains only 34 points, so did you give your explanatory variables to the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) as raster or as data.frame object ?
- If you gave it as data.frame, and then ask for selection of 100 or 50 pseudo-absences, the function will just select all your 34 points... which is not what you want.

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

yes, that's correct. We merge all the data to show the past distribution of these beetles prior to human colonization.

Given present results, it seems that lowland dung beetle species were especially sentitive to extinction. Only ‘highlanders’ survived. However, niche modeling does not handle the singleton lowland records as expected. Therefore, adding those pseudodata is, to certain extent, bypassing the shortcomings of current modelling methods. Ofc in the article we will discuss everything.

Given you are an expert in this, what's the pipeline in handling these situations? Are we doing it right? Are there maybe other niche modeling packeges that can better in handling these data?

Today I will go through your comments/inputs and let you know the results.

Federica

**Comment by federicalosacco** [comment]
Hi Maya,

I published my code and data (also the variables) to my Github ( https://github.com/federicalosacco/niche_modeling ) so it's easier to talk.

**Comment by MayaGueguen** [comment]
Hello Federica,

Thank you for the code and data :pray: 
Indeed, it helps.

Before going any further, here are things you must do : 

- **update your biomod2 version :** `BIOMOD_PresenceOnly` and `BIOMOD_ModelingOptions` functions do not exist anymore. You should work with the version 4.2-5-2.
```
install.packages("biomod2")
library(biomod2)
packageVersion("biomod2")
```
- as a consequence, use the [last version of the tutorial](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) to match new changes
- **check your data**, how you load them, and how you manipulate them : 
here in your `occur` table, you have 2 columns called respectively "Nesosisyphus " and "Nesosisyphus".
You fill the first one with `1` value, but use the second one when calling the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html).
This second column contains `NA` and `1` values (rather than only `1`), that's why the selection of pseudo-absences is not going as you expect, for as soon as you provide `NA` points, PA are selected only within those points which correspond to 25 of your occurrences here.

![image](https://github.com/biomodhub/biomod2/assets/16795576/75254139-1950-4ee3-8048-6bbf27b7bb4e)

Please, check all these steps carefully and see how it is going :eyes: 

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

thanks for the comments. 

I checked the function names and replaced them with the new ones.

Regarding the datasets, the second column is the one I should use, right? If so, I replaced the NA values with 1, and value 1 with NAs. 

Here is the results, do they make more sense to you now?
<img width="665" alt="Screenshot 2024-07-06 alle 00 03 50" src="https://github.com/biomodhub/biomod2/assets/103060304/c2876e7a-a404-4cc6-a130-2a54253ce891">

**Comment by MayaGueguen** [comment]
Hello Federica,

The graphic here tells you that : 
- :blue_square: blue points are presence points that will be used for calibration
- :brown_square: yellow/brownish points are pseudo-absences that will be used for calibration

I think this is not what you want. All those points (even if some are simulated...) are supposed to represent your presences, right ? If so, they all should be reported as 1 into your occurrence table.

Maya

**Comment by federicalosacco** [comment]
Hello Maya,

ok, so, if I understood correctly, in this phase, there is no need to prepare the data separately (real and simulated)?

**Comment by federicalosacco** [comment]
Hello Maya,

I set the format data section in this way:

#Format Data with true absences
# Generate pseudo-absences
myPA <- BIOMOD_FormatingData(resp.var = myResp,
                             expl.var = myExpl,
                             resp.xy = myRespXY,
                             resp.name = myRespName,
                             PA.nb.rep = 1,    # Number of pseudo-absence repetitions
                             PA.nb.absences = 1000)  # Number of pseudo-absences

# Format the data
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                     PA.strategy = 'random',    # Strategy to generate pseudo-absences
                                     PA.nb.rep = 1,    # Number of pseudo-absence repetitions
                                     PA.nb.absences = 1000)  # Number of pseudo-absences


Now extraction of Pseudo-absence data looks like that: 

<img width="562" alt="Screenshot 2024-07-09 alle 22 03 37" src="https://github.com/biomodhub/biomod2/assets/103060304/07b04825-a5c4-4deb-b11f-53fe3444a16f">


And "Transform true absences into potential pseudo-absences":
<img width="526" alt="Screenshot 2024-07-09 alle 22 04 40" src="https://github.com/biomodhub/biomod2/assets/103060304/18e5dfd5-90d7-44cf-b491-4a08fbf000a5">

**Comment by MayaGueguen** [comment]
Hello Federica,

Yes, it looks better now. 
Be careful though with the first screen shot you sent : you select too many pseudo-absences, and it may lead you to overfitting in your models. The second selection seems more appropriate, but you can check anyway once you get your results if the variability of your evaluation measures within and between PA repetitions is not too high.

You can carry on with your modeling now.

Maya

**Comment by federicalosacco** [comment]
Ok! 

I set to 100 the PA.nb.absences parameter in Pseudo-absences extraction:

#### Pseudo-absences extraction
# Format Data with pseudo-absences : random method
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 4,
                                        PA.nb.absences = 100,
                                       PA.strategy = 'random')


and the result is more appropriate:
<img width="531" alt="Screenshot 2024-07-12 alle 14 50 41" src="https://github.com/user-attachments/assets/08a5ea1a-3361-4d22-99a1-2bafd4d969eb">


Moving to "Single models" section, I got this results:

<img width="937" alt="Screenshot 2024-07-12 alle 15 45 57" src="https://github.com/user-attachments/assets/d76cc8c8-86f7-4f8f-9330-c00d6a5770ea">

Looks good to me, there are some signals for species presence also in the lowland. This is how should look like?

**Comment by MayaGueguen** [comment]
Hello Federica,

Well, according to your predictions plots, it seems that you have a bit of variability between your pseudo-absence sets / or repetitions / or algorithms (_see the all-yellow maps, compared to some with more blu-ish colors_).
You should check the values of your evaluation metrics between these different settings, using the [bm_PlotEvalBoxplot](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalBoxplot.html) function for example. And playing with `dataset` and `group.by` parameters.
Also, you can hav e a look at the [variability vignette](https://biomodhub.github.io/biomod2/articles/vignette_variability.html) and the [corresponding video (biomod2 specificities)](https://biomodhub.github.io/biomod2/articles/vignette_videos.html) (_code is no longer up to date, but it's just for you to have insights on how to check this variability theme within your results_).

Hope it helps,

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

sorry for slow reply, I've been busy lately and I resume this just now.

I followed your latest suggestions, playing with dataset and group.by parameters of the **bm_PlotEvalBoxplot** function, but the variability stays the same... not sure now how to solve it. Is there anything else that can be done for the single models? 

Federica

**Comment by MayaGueguen** [comment]
Hello Federica,

Could you send as `.csv` file the output of the `get_evaluations(myBiomodModelOut)` command please ?

Maya

**Comment by federicalosacco** [comment]
Hi Maya,

ok, here is the .csv file:

[evaluations_output.csv](https://github.com/user-attachments/files/17203385/evaluations_output.csv)

**Comment by MayaGueguen** [comment]
Hello Federica,

Thank you for the file :pray: 

Here is how your evaluation values look like : 
- for ROC on the left and TSS on the right,
- and calibration above and validation below.
```
library(ggplot2)
TT = read.table("evaluations_output.csv", header = TRUE, sep = ",")
ggplot(TT, aes(x = algo, y = calibration, color = PA)) + geom_boxplot() + facet_wrap(~ metric.eval)
ggplot(TT, aes(x = algo, y = validation, color = PA)) + geom_boxplot() + facet_wrap(~ metric.eval)
```
![image](https://github.com/user-attachments/assets/e2a7299f-48e9-4b55-9344-32755b87a472)

As you can see, for **calibration**, except for RF and XGBOOST, your evaluation values are quite bad.
And for **validation**, there is a lot of variability between all your algorithms and pseudo-absence datasets.

:arrow_right: to reduce the variability between your pseudo-absence datasets, try and increase your number of pseudo-absences

:warning: how do you divide your dataset for cross-validation ? with so few observations, you cannot expect not to have high variability in your results... as you need enough data to build your models, but enough also to be representative of your species niche and validate the models....

:warning: you have to keep in mind that your dataset might not be sufficient to obtain good results...

You can also try and compute an ensemble model, selecting by hand before the single models having reasonable evaluation values, both for calibration and validation datsets.

Hope it helps,
Maya
