### ISSUE TITLE
Tune "MAXENT" in the new version of biomod2

### ISSUE THREAD

**Issue by fdaccrombessi** [biomodhub/biomod2#471]
Hi everyone,
I apologize if I'm in the wrong place for my request.
I'm facing a challenge to tune "MAXENT" in the new version of biomod2.
Below is my code :
### read occurences 
thin_Cv_occurrences <- read.csv(file = "D:/Work_Space/SDM_Cv/thin_Cv_occurrences_thin1.csv", h=T)

##### convert occurrence data into a shapefile
Cv_occurrences.sp <- SpatialPoints(cbind(thin_Cv_occurrences$X, thin_Cv_occurrences$Y))
proj4string(Cv_occurrences.sp) <- "+proj=longlat +datum=WGS84 +no_defs"

### load selected ecological predictor variables
bioclim_var <- 
  raster::stack(
    c(
      bio1 = 'D:/Work_Space/SDM_Cv/Env_data/wc2.1_30s_bc_crop_asc/bio1_crop.asc',
      bio2 = 'D:/Work_Space/SDM_Cv/Env_data/wc2.1_30s_bc_crop_asc/bio2_crop.asc',
      bio3 = 'D:/Work_Space/SDM_Cv/Env_data/wc2.1_30s_bc_crop_asc/bio3_crop.asc',
      bio13 = 'D:/Work_Space/SDM_Cv/Env_data/wc2.1_30s_bc_crop_asc/bio13_crop.asc'
    )
  )

bioclim_var

## format the data ----
Cv_data <- BIOMOD_FormatingData(resp.name = "Cv.sdm",
                                          resp.var = Cv_occurrences.sp,
                                          expl.var = bioclim_var,
                                          PA.nb.rep = 2,
                                          PA.nb.absences = length(Cv_occurrences.sp),
                                          PA.strategy = 'disk',
                                          PA.dist.min = 5000,
                                          PA.dist.max = 35000,
                                          filter.raster = TRUE
                                          )

Cv_data

##setting up options for individual algorithms to be used for the modelling
myModels_opt <- bm_ModelingOptions(
  MAXENT = list(path_to_maxent.jar = "D:/Work_Space/SDM_Cv/maxent/maxent.jar",
                linear = TRUE,
                quadratic = FALSE,
                product = FALSE,
                threshold = FALSE,
                hinge = FALSE,
                betamultiplier = 2,
                clamp = TRUE
  ) # Other models will use default settings
)

##Computing the models
myModels_out <- BIOMOD_Modeling(
  Cv_data,
  models = c("MAXENT", "GLM", "GBM", "GAM", "CTA", "ANN", "SRE", "FDA", "MARS", "RF", "MAXNET"),
  bm.options = myModels_opt,
  CV.strategy = "random",
  CV.nb.rep = 5,
  CV.perc = 0.8,                   
  prevalence = 0.5,                    
  metric.eval = c("TSS", "ROC"),
  var.import = 3
)

The script doesn't work from the "bm_ModelingOptions" with the error message "unused arguments ".
My concern is to set up the "linear feature class", the regularisation multiplier (rm=2), and clamping = "ON" for only the maxent. The other models can run with default parameters.

Please, any help will be appreciated.
Thanks,

**Comment by HeleneBlt** [comment]
Hello there, 

Don't worry, these issues are the perfect place to ask for any problems related to Biomod2.
Indeed, there are some changes for the options in the new version. You can find more information [here](https://biomodhub.github.io/biomod2/articles/vignette_modelingOptions.html).

For your case, it will look like this:
```

MAXENTOptions <- list("_PA1_allRun" = list(path_to_maxent.jar = "D:/Work_Space/SDM_Cv/maxent/maxent.jar",
                                           linear = TRUE,
                                           quadratic = FALSE,
                                           product = FALSE,
                                           threshold = FALSE,
                                           hinge = FALSE,
                                           betamultiplier = 2,
                                           clamp = TRUE),
                      "_PA2_allRun" = list(path_to_maxent.jar = "D:/Work_Space/SDM_Cv/maxent/maxent.jar",
                                           linear = TRUE,
                                           quadratic = FALSE,
                                           product = FALSE,
                                           threshold = FALSE,
                                           hinge = FALSE,
                                           betamultiplier = 2,
                                           clamp = TRUE))

user.val <- list(MAXENT.binary.MAXENT.MAXENT = MAXENTOptions)

myModels_opt <- bm_ModelingOptions(data.type = 'binary',
                                   models = c("MAXENT", "GLM", "GBM", "GAM", "CTA", "ANN", "SRE", "FDA", "MARS", "RF", "MAXNET"),
                                   strategy = 'user.defined',
                                   user.val = user.val,
                                   user.base = "default",
                                   bm.format = Cv_data)
```


Hope it helps ! 

Hélène

**Comment by fdaccrombessi** [comment]
Hi Hélène,

Yes, the information you provided **was helpful**, and I was able to run the model. However, I had to remove the "clamp = TRUE" option from the MAXENTOptions before it worked. When I read through the modeling options page, I couldn't find the "ON" or "OFF" clamping possibility.

I know from the MESS analysis that there is a **need to turn on the clamping for the MAXENT model**, so I would appreciate any guidance on how to include this in the MAXENTOptions.

Thanks,

François

**Comment by MayaGueguen** [comment]
Hello François 👋 

Even if we do not give the clamp parameter accessible to users, we define `doClamp = TRUE` when calling the `ENMevaluate` function to tune MAXENT.

You can see below the extract of the code from our bm_Tuning function : 

```
try(tune.MAXENT <- ENMeval::ENMevaluate(occs = mySpExpl[mySpExpl[, 1] == 1 & !is.na(mySpExpl[, 1]), ],
                                                    bg = mySpExpl[mySpExpl[, 1] == 0 | is.na(mySpExpl[, 1]), ],
                                                    tune.args = list(rm = seq(0.5, 1, 0.5), fc = c("L")),
                                                    algorithm = params.train$MAXENT.algorithm,
                                                    partitions = "randomkfold",
                                                    partition.settings = list(kfolds = 10),
                                                    doClamp = TRUE, ## allow to change or not ?
                                                    parallel = params.train$MAXENT.parallel,
                                                    numCores = NULL, ## default to 1 or NULL (all available cores used then) ?
                                                    categoricals = NULL))
```

Maya

**Comment by fdaccrombessi** [comment]
Hi Maya,

That is good and it is okay then.
I'm satisfied.
Thank you!

**Comment by fdaccrombessi** [comment]
**Thank you, Hélène and Maya, for your help!**

**Comment by gretalolo** [comment]
Hi all,

reopening this thread as I'm learning the ins and outs of species distribution modelling! I have been using these comments to try to tune my MaxEnt model but keep encountering this error message that I do not know how to fix:

`MAXENTOptions <- list("_allData_allRun"=list(path_to_maxent.jar = "maxent.jar",
+                data.type='binary',
+                linear = TRUE,
+                quadratic = TRUE,
+                product = TRUE,
+                threshold = TRUE,
+                hinge = TRUE,
+                betamultiplier = 2,
+                memory_allocated=40000))

> user.val <- list(MAXENT.binary.MAXENT.MAXENT = MAXENTOptions)

> myModels_opt <- bm_ModelingOptions
+                                   (data.type = 'binary',
+                                    models = c("MAXENT"),
+                                    strategy = 'user.defined',
+                                    user.val = user.val,
+                                    user.base = "bigboss",
+                                    bm.format = biomoddata)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	>  MAXENT options (datatype: binary , package: MAXENT , function: MAXENT )...Error in { : task 1 failed - "task 1 failed - "
names(user.val[['_allData_allRun']]) must be 'path_to_maxent.jar', 'memory_allocated', 'initial_heap_size', 'max_heap_size', 'background_data_dir', 'visible', 'linear', 'quadratic', 'product', 'threshold', 'hinge', 'lq2lqptthreshold', 'l2lqthreshold', 'hingethreshold', 'beta_threshold', 'beta_categorical', 'beta_lqp', 'beta_hinge', 'betamultiplier' or 'defaultprevalence""`

Thank you for your help!

**Comment by gretalolo** [comment]
Hi, 

thank you for your quick response! The reason, why I had the data type specified was because I have been getting this error message if I do not specify it:
`
> MAXENTOptions <- list("_allData_allRun"=list(path_to_maxent.jar = "maxent.jar", 
                linear = TRUE,
               quadratic = TRUE,
                product = TRUE,
                threshold = TRUE,
                hinge = TRUE,
                betamultiplier = 2,
                memory_allocated=40000))

> user.val <- list(MAXENT.binary.MAXENT.MAXENT = MAXENTOptions)

> myModels_opt <- bm_ModelingOptions(models = c("MAXENT"),
                                    strategy = 'user.defined',
                                    user.val = user.val,
                                    user.base = "bigboss",
                                    bm.format = biomoddata)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Error in bm_ModelingOptions(models = c("MAXENT"), strategy = "user.defined",  : 
  argument "data.type" is missing, with no default
`

If I do define it within the bm_ModelingOptions, then I get this:

**Comment by HeleneBlt** [comment]
Hello Anna, 

You are right : `data.type` should be defined within `bm_ModelingOptions` 👇 

```
myModels_opt <- bm_ModelingOptions(models = c("MAXENT"),
                                   strategy = 'user.defined',
                                   user.val = user.val,
                                   user.base = "bigboss",
                                   data.type = 'binary')
```

However, there are several problems in your call of `bm_Tuning`. 

- As the message specified, you should give a 'BIOMOD.options.dataset' object, so here : 
`bm.options = myModels_opt@options$MAXENT.binary.MAXENT.MAXENT`

- `tuning.fun` should be the model function name to be called for tuning parameters (see [ModelsTable](https://biomodhub.github.io/biomod2/reference/ModelsTable.html) dataset) so here `"ENMevaluate"`

- `calib.lines` should be a Cross Validation table you can get by [get_calib_lines](https://biomodhub.github.io/biomod2/reference/getters.out.html) or [bm_CrossValidation](https://biomodhub.github.io/biomod2/reference/bm_CrossValidation.html) functions. 
If you don't want it, keep it to `NULL`. 

So your call becomes : 

```
tunedBTmodel1 = bm_Tuning(model = "MAXENT",
                          tuning.fun = "ENMevaluate",
                          calib.lines = NULL,
                          metric.AIC = "AIC",
                          metric.eval = "AICc",
                          bm.options = myModels_opt@options$MAXENT.binary.MAXENT.MAXENT,
                          bm.format = biomodata)
```

And it should work fine 🎉 
Hélène

**Comment by HeleneBlt** [comment]
Hello Anna, 

The problem comes from : 

```
myModels_opttuned <- bm_ModelingOptions(models = c("MAXENT"),
                                        strategy = 'tuned',
                                        user.val = user.valtuned,
                                        user.base = "bigboss",
                                        data.type = 'binary', bm.format = biomoddataLBR)
```
You put `strategy` to `'tuned'` so `user.val` and `user.base` gonna be ignored as they work with `strategy  = 'user.defined'`. 
So, the `path_to_maxent.jar` will be false. 
(By the way, it's the path to the directory where there is maxent.jar, not the path of maxent.jar, so here `"Z:/XXXX/BTData/TrialModels/BlackTern/models"`  😶 )

The correct way will be something like this 👇 
This may seem redundant, but it's not if you're using several algorithms. 

```
myModels_opttuned <- bm_ModelingOptions(models = c("MAXENT"),
                                        strategy = 'user.defined',
                                        user.val = user.valtuned,
                                        user.base = "bigboss",
                                        data.type = 'binary',
                                        bm.format = biomoddataLBR)

tunedBTmodelLBR = bm_Tuning(model = "MAXENT",
                            tuning.fun = "ENMevaluate",
                            metric.AIC = "AIC",
                            metric.eval = "AICc",
                            bm.options = myModels_opttuned@options$MAXENT.binary.MAXENT.MAXENT,
                            bm.format = biomoddataLBR))

myModels_opttuned <- bm_ModelingOptions(models = c("MAXENT"),
                                        strategy = 'user.defined',
                                        user.val = list(MAXENT.binary.MAXENT.MAXENT = tunedBTmodelLBR),
                                        user.base = "bigboss",
                                        data.type = 'binary', bm.format = biomoddataLBR)


BTmodel2tuned = BIOMOD_Modeling(
  biomoddataLBR,
  modeling.id = as.character(format(Sys.time(),"BTmodelLBRtuned")),
  models = c("MAXENT"),
  CV.strategy = "kfold",
  CV.k = 5,
  CV.nb.rep = 2,
  CV.perc = 0.80,
  CV.do.full.models = TRUE, 
  OPT.strategy = "user.defined",
  OPT.user = myModels_opttuned,
  metric.eval = c("TSS", "ROC", "KAPPA"),
  var.import = 2,
  do.progress = TRUE)
```

⚠  Be sure to update to the latest version of `biomod2` on Github with : 
`devtools::install_github("biomodhub/biomod2", dependencies = TRUE)`

Hope it's clearer and your tuning will work fine !
Hélène

**Comment by gretalolo** [comment]
Quick Update - after a restart and removing spaces from all folder names, the tuning works great now. Thank you for your help!

Best,
Anna
