### ISSUE TITLE
Help understanding parameter tuning in BIOMOD_Modeling

### ISSUE THREAD

**Issue by HRodenhizer** [biomodhub/biomod2#480]
I am trying to train a GBM using k-fold validation and parameter tuning and it has been running for nearly a week. I have previously trained the same model using the same data, except that I used the bigboss parameters, in less than an hour or two. I recognize that tuning the parameters will take longer, but I am beginning to question whether I should expect it to take as long as it is. Based on this general premise, I have a few questions about how the tuning works and whether there are any changes I could make to improve the speed of the process.

I have a dataset with approximately 21,000 rows (both presences and absences) and 30 predictor variables. The specific modeling options I am using are:

```r
rts_model = BIOMOD_Modeling(
  arts_biomod,
  modeling.id = "GBM 10 K-fold Validation Tuned",
  models = c("GBM"),
  CV.strategy = "kfold",
  CV.k = 10,
  OPT.strategy = 'tuned',
  metric.eval = c('TSS','ROC'),
  seed.val = 42,
  nb.cpu = 19
)
```

When I run this code, the "tuning parameters" section completes within a relatively short amount of time (maybe an hour or two?). Then, the "tuning formula" section begins, and as of 6 days later, it is still running.

1. What is the formula tuning step? I have never heard this terminology used before, so I am uncertain what is actually happening during this step. I think it seems to be related to parameter tuning, since I don't remember seeing this step when I ran the model with bigboss parameters, but other than that, I am clueless.
2. Is it expected that formula tuning should take orders of magnitude longer to run than parameter tuning?
3. Is there a way to select a range/specify the permutations to try when performing parameter tuning? E.g. could I speed up the process by selecting a smaller number of permutations to test?
4. Although I have set nb.cpu to 19, it appears that only one cpu is actually maxed out when I run this code. Is this the expected behavior?
5. I know I could speed up the process by not tuning the parameters (I've already tested this out), giving it more cpus (I think?, but see question 4), or reducing the CV.k (although I'm not sure if this would impact the time required for parameter tuning, or just later steps in model training). Is there anything else I could do to speed up this process?
6. Is there anything else about how I've set this up that could be problematic or that I should be considering to determine if everything is going well and if I just need to wait longer?

I'm including a screenshot of the output here, in case that is helpful:
![image](https://github.com/biomodhub/biomod2/assets/38510539/cdc68bff-1efa-4115-b04d-5001c65a92a2)

**Comment by HeleneBlt** [comment]
Hi ! 

Indeed, the tuning can be very long and GBM is one of the slowest algorithms. 

To have more possibility to customize your tuning process, you need to do it separately from the modeling : 

```
opt.d <- bm_ModelingOptions(data.type = 'binary',
                            models = "GBM",
                            strategy = 'default')


tuned.gbm <- bm_Tuning(model = "GBM",
                   tuning.fun = "gbm", ## see in ModelsTable
                   bm.options = opt.d@options$GBM.binary.gbm.gbm,
                   do.formula = T,
                   bm.format = arts_biomod)


opt.t <- bm_ModelingOptions(data.type = 'binary',
                            models = "GBM",
                            strategy = "user.defined",
                            user.val = list(GBM.binary.gbm.gbm = tuned.gbm),
                            user.base = "bigboss",
                            bm.format = arts_biomod,
                            calib.lines = cv_kfold)

rts_model <- BIOMOD_Modeling(arts_biomod,
                             modeling.id = "GBM 10 K-fold Validation Tuned",
                             models = c("GBM"),
                             CV.strategy = "user.defined",
                             CV.user.table = cv_kfold,
                             OPT.strategy = "user.defined",
                             OPT.user = opt.t,
                             metric.eval = c('TSS','ROC'),
                             seed.val = 42,
                             nb.cpu = 19)
```

With this script,  it will tune the parameters exactly the same way as into BIOMOD_Modeling (so it will take the same time but no longer: bm_ModelingOptions is really quick I promise ! ). 

So : 
1. The formula tuning step: It will try the four different types of formula `c('simple', 'quadratic', 'polynomial', 's_smoother')` (see [bm_MakeFormula](https://biomodhub.github.io/biomod2/reference/bm_MakeFormula.html)) with different interaction levels (1 to 3). In the same way as the parameters, we use caret for this tuning. And yes, it takes a lot of time! If it is not useful for you, you can remove this step with `do.formula = F`. 
2. Formula time: The formula takes usually longer than the parameters process. The parallelisation is less efficient and some algorithms can be very long but we don't have the latitude to change that. 
3. params.train : You can change the grid of the tuning parameters with the arguments `params.train` in [bm_Tuning](https://biomodhub.github.io/biomod2/reference/bm_Tuning.html). For GBM, you can tune `n.trees`, `interaction.depth`, `shrinkage` and `n.minobsinnode`. By default, you have : 
```
GBM.n.trees = c(500, 1000, 2500), GBM.interaction.depth = seq(2, 8, by = 3), GBM.shrinkage = c(0.001, 0.01, 0.1), GBM.n.minobsinnode = 10
``` 
but you can change like this for example : 

```
GBM.n.trees = c(500, 1000), GBM.interaction.depth = 3 , GBM.shrinkage = c(0.001, 0.01, 0.1), GBM.n.minobsinnode = c(5, 10)
``` 


4. CPU : see 2. It should work better during the parameters tuning step. But there are always just some parts that can be parallelised and if one part takes longer, it will slow down the entire process and use only one cpu. 
5. One thing, you can try first is to not give `calib.lines` to `bm_Tuning`. It will tune the parameters for all the PA datasets. For the modelling after, all the options of "_PA1_allRun" will be given to "_PA1_RUN1", "_PA1_RUN2", ... It will be faster and it can be a primary result to see if it is worth the shot to add the `calib.lines` or not ! 
6. if any of the solutions above (remove formula tuning, remove calib.lines and change the grid) doesn't reduce the calculation time, the problem must come from something else. Do you work with Windows? 


I hope I have answered to all your questions. 
Don't hesitate if it will not clear! 

Hélène

**Comment by HRodenhizer** [comment]
Thank you! This is all very helpful.

Do you know of a good resource that explains the different formula options or can you provide an overview? I don't know how those formula options are used in a GBM and a quick google search isn't proving helpful.

**Comment by HeleneBlt** [comment]
Hi ! 

You can consult the documentation on function [s](https://rdrr.io/cran/mgcv/man/s.html). 
If I remember correctly, GBM accepts all these types of formula but it can interact with `cv.fold`. For example, you can't have an s_smoother formula with `cv.fold` > 1. 

With 30 predictor variables, I would advise keeping the formula simple so that the result remains interpretable! 
(Note: I assume that you already do all the correlation checks with your variables, but reducing the number of predictor variables will also reduce the calculation time of the tuning, of course). 

Hélène

**Comment by HRodenhizer** [comment]
Thanks again! Yes, I have performed a PCA to get my predictor variables to take care of correlations, and I am also still considering reducing the number of predictors further.

Maybe I'm missing something basic, but the page for `s` is all about smoothing lines in GAM models, which is not the type of model I am using. It makes perfect sense to me that you would have to choose the formula for a GAM, but I still don't understand how or why that applies to a GBM.

**Comment by HeleneBlt** [comment]
Hello ! 

Indeed, in your case, I don't think it is useful. I'm not a specialist in GBM so I don't really know how it deals with it. However, we still let the possibility in biomod2 to use all the different formulas : if you want GAM in your models and you want the same formula for all of your models for example. 
The other is simpler to understand. With the quadratic type, you add the square of the variables and with the polynomial, you add the square and the cube of the variables.
Here an example with an interaction level at one: 

- simple :  response ~ 1 + var1 + var2 + var3 + var1:var2 + var1:var3 + var2:var3 + var1:var2:var3

- quadratic: response ~ 1 + var1 + I(var1^2) + var2 + I(var2^2) + var3 + I(var3^2) + var1:var2 + var1:var3 + var2:var3 + var1:var2:var3

- polynomial : response ~ 1 + var1 + I(var1^2) + I(var1^3) + var2 + I(var2^2) + I(var2^3) + var3 + I(var3^2) + I(var3^3) + var1:var2 + var1:var3 + var2:var3 + var1:var2:var3

- s_smoother: response ~ 1 + gam::s(var1) + gam::s(var2) + gam::s(var3) + var1:var2 + var1:var3 + var2:var3 + var1:var2:var3

For the cross-validation, you were really not that far: you just need to add "do.full.models = TRUE" . 

```
cv_kfold = bm_CrossValidation(
  arts_biomod,
  strategy = 'kfold',
  nb.rep = 1,
  k = 10,
  do.full.models = TRUE
)
```

Hélène

**Comment by HRodenhizer** [comment]
Thank you! Running it without the formula tuning seems to have gotten me nearly where I needed to be.

My only issue now is that no link for variables.importance was created (models.options, models.evaluation, etc. all appear to have been created as expected). Am I missing an argument for that somewhere?

**Comment by HeleneBlt** [comment]
Hi ! 

Glad to know there is progress ! 🏆 

In BIOMOD_Modeling, you need to add the number of permutations to evaluate the variable importance with the argument `var.import`. For example,

```
rts_model <- BIOMOD_Modeling(arts_biomod,
                             modeling.id = "GBM 10 K-fold Validation Tuned",
                             models = c("GBM"),
                             CV.strategy = "user.defined",
                             CV.user.table = cv_kfold,
                             OPT.strategy = "user.defined",
                             OPT.user = opt.t,
                             metric.eval = c('TSS','ROC'),
                             var.import = 3,
                             seed.val = 42,
                             nb.cpu = 19)

```

After you can get the results with [`get_variables_importance`](https://biomodhub.github.io/biomod2/reference/getters.out.html)`(rts_models)` and visualize them  with [`bm_PlotVarImpBoxplot`](https://biomodhub.github.io/biomod2/reference/bm_PlotVarImpBoxplot.html). 

Hélène

**Comment by HRodenhizer** [comment]
Great, that should do it. Thank you so much for all your support!
