### ISSUE TITLE
Question on cut-off value for binary transformation - How is calculated?

### ISSUE THREAD

**Issue by Cam-in** [biomodhub/biomod2#482]
Hi biomod community!
I am using biomod 3.5.1

In the binary transformation, there are different methods for setting the best threshold to transform continuous habitat suitability into binary data. There is the cut-off value in biomod2 available to get it from the evaluation table and Find.Optim.Stat function
But, I want to understand how the cut-off is calculated. Is the value that maximized Sensitivity+Specificity? Is there a formula that biomod2 displays on the background? Or which is exactly the process that is applied when we obtain from the Evaluation metrics the cut-off, sensibility and specificity?

E.g. I received from an ensemble model:

Sensitivity: 94.453
Specificity: 98.154
TSS: 0.927
Cutoff value: 586
But (94.453 + 98.154) -1 = 191,607 it is not the cutoff value.

Can somebody help me and teach me? Thanks =)
Cami

**Comment by HeleneBlt** [comment]
Hi Cami ! 

(Thanks for reposting here: it will be clearer 😄 )

Find.Optim.Stat have a new name bm_FindOptimStat but they are similar.
bm_FindOptimStat needs a number of thresholds to test. The default is 100. 
bm_FindOptimStat will create a sequence of 100 thresholds between the minimum and the maximum of your predicted data.

For each threshold, your predicted data will be transformed into binary :  
- under the threshold: 0
- above the threshold: 1
And it will be compared to your real data. 
So it can calculate the sensitivity, the specificity and the metric you want, here TSS.

We keep the threshold with the best TSS : this threshold becomes the cutoff.
And we return the sensitivity, the specificity and TSS for this cutoff.

So you have:
Sensitivity: 94.453
Specificity: 98.154
TSS: 0.927
Cutoff value: 586

This means that when your predicted values have been transformed in binary with a cutoff of 586. 
(above 586: 1, under 586: 0), you have the best TSS (0.927).

I hope it is clearer ! 
Hélène

**Comment by Cam-in** [comment]
Awesome! I needed this. 
Please Hélène help me with one extra: 

So I have:
Sensitivity: 94.453
Specificity: 98.154
Cutoff value: 586

If Sensitivity is defined as True Positive / (True Positive + False Negative) * 100; and Specificity is True Negative / (True Negative + False Positive) * 100, why if I sum Sensitivity and Specificity ( in my example 192,607) differently from the cut-off since the cut-off also evaluates it comparing with my real data.

Some authors used the Maximized Sensitivity and Specificity (sum of them) for binary conversion of habitat suitability, but I have seen that the cut-off is more conservative and I like it due to the multiple simulations it does for selecting the best threshold. 
How can I explain that using cut-off is better than others even when both account the error types I and II (false positive and false negative respectively) ? 

¡GRACIAS!
Cami

**Comment by HeleneBlt** [comment]
Hello Cami ! 

I confess I'm a little bit confuse: the cut-off is the threshold to separate the values in 0 and 1. So you cannot retrieve the cutoff with the sensitivity and specificity. However, you can find the TSS (here there is a factor 100 ). 
`TSS = 94.453/100 + 98.154/100 -1 =  0.92607` 

I'm not a specialist, but one of the main points of the cutoff method is you have the advantages and disadvantages of the metrics you choose. For example, with the Kappa metrics you will have a certain impact of prevalence that you will not have with TSS. So you can choose the metrics that are best suited to your data. 

Hope it helps ! 
Hélène
