### ISSUE TITLE
Help with BIOMOD_2-5-2 - Memory issue: Rstudio uses nearly all the memory, and is forced to stop (R4.4.1, RStudio: 2024.04.0, build 735)

### ISSUE THREAD

**Issue by zpmdal** [biomodhub/biomod2#485]
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id = 'AllModels',
                                    models = c('GAM', 'GLM', 'MAXENT', 'RF', 'MARS'),
                                    CV.strategy = 'random',
                                    CV.nb.rep = 2,
                                    CV.perc = 0.8,
                                    OPT.strategy = 'bigboss',
                                    #OPT.strategy = 'tuned',
                                    var.import = 3,
                                    #metric.eval = c('TSS','ROC', 'BOYCE', 'KAPPA')
                                    metric.eval = c('ROC', 'BOYCE', 'KAPPA')
                                    )

The above works fine. However when I started the following for projection:
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = TRUE)

I am using laptop with 32 GB of RAM memory, and 24 GB of swap, 1TB of HDD, installed with Linux (Fedora 40). The memory usage becomes overshoot, it could reach 30G. Then the Rstudio is forced to quit. This happens at the step of building TSS binary/fitered ... . 

The strange thing is that the same code run under the same version of R and RStudio on Windows 10 PC with 16 GB of RAM, and 500 GB of HDD run just fine. The memory usage reached around 10GB at most. I am not sure it's caused by Linux OS problem, or because of bugs in the code. 

Thanks!

Zhi-Ping

**Comment by HeleneBlt** [comment]
Hello Zhi-Ping ! 

Thanks for reporting 🙏 
Indeed, this is strange ! 

You can try to run it with some other arguments : 
```
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
proj.name = 'Current',
new.env = myExpl,
models.chosen = 'all',
metric.binary = 'all',
metric.filter = 'all',
build.clamping.mask = TRUE,
on_0_1000 = TRUE, #The probability will be multiplied by 1000 to have integer
do.stack = FALSE ) #You will have several spatRaster 
```

Could you also try to separate your projections : 

- one without any metrics 
- one with only filtered metrics 
- one with only binary metrics

So it will be easier to see whether the problem comes from biomod2 or more of the memory allowed by Linux to RStudio. 🤔 

Thanks ! 
Hélène

**Comment by zpmdal** [comment]
Thanks Helene for your quick response, 

do.stack = FALSE solved the problem. The number of metrics does not seem to matter.
