### ISSUE TITLE
Problem with BIOMOD_formatting

### ISSUE THREAD

**Issue by ShreePoudel0** [biomodhub/biomod2#486]
Hello. I am having trouble with loading presence points to formatted data. I have the required data but when I implement BIOMOD_formattingData, and i check the summary, there is 0 presence points. What might be the reason for this?

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

My points are in this format.
X | Y | Point
-- | -- | --
27.56389 | 84.74864 | 1
27.56239 | 84.75202 | 1
27.54495 | 84.76479 | 1
27.59262 | 84.77433 | 1
27.53144 | 84.81312 | 1
27.47743 | 84.88493 | 1
27.48401 | 84.88583 | 1
27.47725 | 84.88773 | 1
27.62368 | 84.90366 | 1
27.62217 | 84.90474 | 1
27.48124 | 84.90509 | 1
27.46634 | 84.91609 | 1
27.46246 | 84.92122 | 1
27.57798 | 84.92205 | 1

This is the code i used

myRespName <- 'Point'
myRespName

myResp <- as.numeric(data[,myRespName])

myRespXY <- data[,c("Y","X")]

myBiomodData <- 
  BIOMOD_FormatingData(         #Gathers all input data necessary to run biomod2 models.
    resp.var = myResp, #Response Variable ['Column containing presence points']
    resp.xy = myRespXY, #Response Variable ['Column containing Longitude and Latitude']
    expl.var = myExpl, #Predictor Variable
    resp.name = myRespName, #Name of the response variable
    PA.nb.rep = 2, #No. of replication for presence data
    PA.nb.absences = 1000,#No. of absence points to generate or background points
    PA.strategy = 'random',
    filter.raster = TRUE)

IThe coordinates were n UTM and i changed to Degree.

**Comment by HeleneBlt** [comment]
Hi Shree ! 

I will need a little more information. 
Could you share : 

- the output of `summary(myResp)`
- `summary(myExpl) `if it is a data.frame or `show(myExpl)` if it is a spatRaster 
- the output when you run `BIOMOD_FormatingData`
- the output of `myBiomodData`

Thanks a lot 🪷 
Hélène

**Comment by ShreePoudel0** [comment]
I have given the information below

> summary(myResp)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       1       1       1       1       1

> show(myExpl)
class      : RasterStack 
dimensions : 1330, 1832, 2436560, 8  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : 274025.3, 328985.3, 3027499, 3067399  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=45 +datum=WGS84 +units=m +no_defs 
names      :      elev_new,          road,         water,         ndvi, population_new, settlement_new,         slope,        aspect 
min values :  2.450803e+02, -1.600144e-01,  0.000000e+00,            ?,   3.782733e+01,   2.467471e-05,  0.000000e+00,  0.000000e+00 
max values :  2576.8479468,  6058.4252099,  7962.7260742,            ?,   2747.0148926,      0.1435017,     1.2961171,     6.2831853 


> myBiomodData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  Point

	 0 presences,  0 true absences and  1999 undefined points in dataset


	 8 explanatory variables

    elev_new           road             water             ndvi            population_new   
 Min.   : 257.1   Min.   :   0.00   Min.   :   0.0   Min.   :-0.0006628   Min.   :  48.85  
 1st Qu.: 642.5   1st Qu.:  41.04   1st Qu.: 150.0   1st Qu.: 0.1855760   1st Qu.:  92.32  
 Median :1075.4   Median : 118.50   Median : 369.1   Median : 0.2411554   Median : 127.71  
 Mean   :1152.9   Mean   : 259.51   Mean   : 642.4   Mean   : 0.2392612   Mean   : 180.79  
 3rd Qu.:1638.4   3rd Qu.: 275.15   3rd Qu.: 754.3   3rd Qu.: 0.2918932   3rd Qu.: 195.17  
 Max.   :2566.3   Max.   :5498.88   Max.   :7105.3   Max.   : 0.4552180   Max.   :2747.01  
 settlement_new         slope             aspect        
 Min.   :0.001566   Min.   :0.00109   Min.   :0.002627  
 1st Qu.:0.022367   1st Qu.:0.22304   1st Qu.:1.613287  
 Median :0.039106   Median :0.38269   Median :3.180709  
 Mean   :0.047372   Mean   :0.38311   Mean   :3.084141  
 3rd Qu.:0.067909   3rd Qu.:0.53328   3rd Qu.:4.447293  
 Max.   :0.138781   Max.   :1.01601   Max.   :6.281537  


 2 Pseudo Absences dataset available ( PA1, PA2 ) with  1000 (PA1, PA2) pseudo absences

myBiomodData <- 
+   BIOMOD_FormatingData(         #Gathers all input data necessary to run biomod2 models.
+     resp.var = myResp, #Response Variable ['Column containing presence points']
+     resp.xy = myRespXY, #Response Variable ['Column containing Longitude and Latitude']
+     expl.var = myExpl, #Predictor Variable
+     resp.name = myRespName, #Name of the response variable
+     PA.nb.rep = 2, #No. of replication for presence data
+     PA.nb.absences = 1000,#No. of absence points to generate or background points
+     PA.strategy = 'random',
+     filter.raster = TRUE)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Point Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation
 !!! Some data are located in the same raster cell. 
          Only the first data in each cell will be kept as `filter.raster = TRUE`.

Checking Pseudo-absence selection arguments...

      ! No data has been set aside for modeling evaluation
   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables

 ! Some NAs have been automatically removed from your data
      ! No data has been set aside for modeling evaluation
      ! No data has been set aside for modeling evaluation
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by HeleneBlt** [comment]
Hello again ! 

Your `myExpl` is not in the same coordinate reference system than your coordinates ! 
So `biomod2` cannot match the presences and the background and think all presences are in the same cells. 
I suggest you let your coordinates in UTM or change the crs of your `myExpl`. 

I will try to add a warning about that ! 
Hélène

**Comment by ShreePoudel0** [comment]
I changed the coordinates of each variables and then stacked them. this showed the points but now pseudo absence is not generated for some reason.
<html>
<body>

myBiomodData <-  +   BIOMOD_FormatingData(         #Gathers all input data necessary to run biomod2 models. +     resp.var = myResp, #Response Variable ['Column containing presence points'] +     resp.xy = myRespXY, #Response Variable ['Column containing Longitude and Latitude'] +     expl.var = myExpl, #Predictor Variable +     resp.name = myRespName, #Name of the response variable +     PA.nb.rep = 3, #No. of replication for presence data +     PA.nb.absences = 1000,#No. of absence points to generate or background points +     PA.strategy = 'random', +     filter.raster = FALSE)  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Pangolin Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=        ! No data has been set aside for modeling evaluation       ! No data has been set aside for modeling evaluation  !!! Some data are located in the same raster cell.            Please set `filter.raster = TRUE` if you want an automatic filtering.  Checking Pseudo-absence selection arguments...        ! No data has been set aside for modeling evaluation    > random pseudo absences selection    > All available cells have been selected ( 1 cells )   ! Some NAs have been automatically removed from your data       ! No data has been set aside for modeling evaluation  !!! Some data are located in the same raster cell.            Please set `filter.raster = TRUE` if you want an automatic filtering.       ! No data has been set aside for modeling evaluation -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= > myBiomodData  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  dir.name =  .  sp.name =  Pangolin  	 339 presences,  0 true absences and  1 undefined points in dataset   	 9 explanatory variables      elev_new          slope             aspect             ndvi         population_new     Min.   : 300.1   Min.   :0.04547   Min.   :0.04847   Min.   :0.07773   Min.   :  68.64    1st Qu.: 555.5   1st Qu.:0.18921   1st Qu.:2.34205   1st Qu.:0.24705   1st Qu.: 122.86    Median : 693.6   Median :0.29300   Median :3.35206   Median :0.28510   Median : 178.80    Mean   : 947.0   Mean   :0.31136   Mean   :3.35393   Mean   :0.27766   Mean   : 270.12    3rd Qu.:1300.0   3rd Qu.:0.43017   3rd Qu.:4.43302   3rd Qu.:0.32115   3rd Qu.: 342.97    Max.   :2396.6   Max.   :0.71978   Max.   :6.24239   Max.   :0.36171   Max.   :1178.36         road         settlement_new     vegetation_type_new     water          Min.   :   0.00   Min.   :0.004464   Min.   : 1.000      Min.   :  35.51    1st Qu.:  78.01   1st Qu.:0.015535   1st Qu.: 1.000      1st Qu.: 272.02    Median : 188.93   Median :0.024728   Median : 1.000      Median : 480.72    Mean   : 189.47   Mean   :0.036955   Mean   : 1.652      Mean   : 531.28    3rd Qu.: 254.43   3rd Qu.:0.039300   3rd Qu.: 2.000      3rd Qu.: 725.68    Max.   :1342.65   Max.   :0.127046   Max.   :18.000      Max.   :2628.83      1 Pseudo Absences dataset available ( PA1 ) with  0 (PA1) pseudo absences  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= > summary(myBiomodData)       dataset run   PA Presences True_Absences Pseudo_Absences Undefined 1     initial  NA <NA>       339             0               0         1 2 calibration  NA  PA1       339             0               0        NA
--
 
> | >
>


</body>
</html>
![image](https://github.com/user-attachments/assets/f7fbb2ca-f0b8-4893-a275-2a032b97b474)
