### ISSUE TITLE
strange error: unused argument (PA.NbRep = 2)

### ISSUE THREAD

**Issue by ninzyfb** [biomodhub/biomod2#49]
Hello biomod2 team,

Thank you for developing such a useful package. I have just been using the 4.0 version and came across an error i am not sure about. When i try and run the following code it keeps telling me:
`Error in .local(sp, env, ...) : unused argument (PA.NbRep = 2)`
This was working fine prior to the new package update.

biomod_obj =  BIOMOD_FormatingData(resp.var = pa, # presence/background data
                                                expl.var = exp, # environmental variables
                                                resp.xy = pa_xy, # response variable coordinates
                                                resp.name = target, # species name
                                   # this will pick the pseudo-absences from your NAs in pa
                                   PA.nb.absences = pseudoabsences,
                                   # two sets of pseudoabsences to be chosen
                                   PA.nb.rep = 2,
                                   # for high specificity pseudo-absences should be randomly selected 
                                   PA.strategy = 'random') 

However i don't see anything wrong with that line according to the documentation?
Thank you for your help,
Nina

**Comment by MayaGueguen** [comment]
Hi Nina,

Thank you for trying the new version, and for reporting !
Indeed, I forgot to change one `PA.NbRep` value... I just corrected it, could you try it again please ?
Sorry for the inconvenience.

Maya

**Comment by ninzyfb** [comment]
Thanks! It works now :)
