### ISSUE TITLE
bm_PlotRangeSize:output interpretation

### ISSUE THREAD

**Issue by NadiaVic** [biomodhub/biomod2#490]
Hi! 
I'm using the version of biomod2 4.2-4 and I want to understand the output generated in my R-console when I run the function bm_PlotRangeSize.
When I run
bm_PlotRangeSize(bm.range = myBiomodRangeSize_MRI_2060_585Ens, 
                                           do.count = TRUE,
                                           do.perc = TRUE,
                                           do.maps = TRUE,
                                           do.mean = TRUE,
                                           do.plot = TRUE,
                                           row.names = c("Species", "Dataset", "Run", "Algo"))

In the environment is generated a list with several components. Particularly I am interested in tab.ca1 and tab.ca2. I am wondering if
ta.ca1 represents the values of loss, stable and gain(-2,-1 and 1 given in the column value) that are plotted in the Community averaging between models, and ta.ca2 represents in its value column the percentage of model agreement. 

example of ta.ca2 table
         x         y                          variable value group.value group.level
1   -70.37083 -33.74583 Species_Ptorq     1       Ptorq     Species
2   -70.26250 -33.74583 Species_Ptorq     1       Ptorq     Species
3   -70.49583 -33.75417 Species_Ptorq     1       Ptorq     Species
4   -70.48750 -33.75417 Species_Ptorq     1       Ptorq     Species
5   -70.47917 -33.75417 Species_Ptorq     1       Ptorq     Species
6   -70.47083 -33.75417 Species_Ptorq     1       Ptorq     Species
7   -70.42083 -33.75417 Species_Ptorq     1       Ptorq     Species
8   -70.37917 -33.75417 Species_Ptorq     1       Ptorq     Species

Additionally, if I use:
bm_PlotRangeSize(bm.range = myBiomodRangeSize_MRI_2060_585Ens, 
                                           do.count = TRUE,
                                           do.perc = TRUE,
                                           do.maps = TRUE,
                                           do.mean = TRUE,
                                           do.plot = TRUE,
                                           row.names = c("Species"))

ta.ca2 column variable change to which.max it is ok?
            x         y                   variable value group.value group.level
1   -70.37083 -33.74583 which.max    -2                        
2   -70.26250 -33.74583 which.max    -2                        
3   -70.49583 -33.75417 which.max    -2                        
4   -70.48750 -33.75417 which.max    -2                        
5   -70.47917 -33.75417 which.max    -2                        
6   -70.47083 -33.75417 which.max    -2                        
7   -70.42083 -33.75417 which.max    -2                        

Thanks in advance!

**Comment by HeleneBlt** [comment]
Hello Nadia ! 

Thanks for your message 🪷 

> ta.ca1 represents the values of loss, stable and gain(-2,-1 and 1 given in the column value) that are plotted in the Community averaging between models, and ta.ca2 represents in its value column the percentage of model agreement.

It is exactly that! You have the plot of these two datasets and `biomod2` returns also the data of the plots so you are able to modify the plots if needed. 

Concerning the argument `row.names`, you should have a look at the rownames of `myBiomodRangeSize_MRI_2060_585Ens$Compt.By.Models` and give the information separate by "_". 
Usually, if you compare the projection of simple models, it will be `c("Species", "Dataset", "Run", "Algo")` or if you use projection of ensemble models (your case here ?), it will be `c("Species","EMmodel", "Dataset", "Run", "Algo")`. 

Hope it helps ! 
Don't hesitate if you have other questions. 

Hélène

**Comment by NadiaVic** [comment]
Thanks for your help!!!!

**Comment by NadiaVic** [comment]
:)
