### ISSUE TITLE
Help with biomod2 4.2-6-1 resample during projection

### ISSUE THREAD

**Issue by zpmdal** [biomodhub/biomod2#505]
After running the biomod_projection function, I try to plot the output from the projection, and it automatically resample the data. I found the resolution of in the object of "spatraster" decreased to half of the input. I am wondering if I can avoid resampling so that I can have original resolution as in input, so that I can compare with original raster layers?

Thanks!

Zhi-Ping

**Comment by HeleneBlt** [comment]
Hello Zhi-Ping, 

By default, the maximum number of cells, passed to `terra::plot`, is `5e5`. 
You could play with the argument `maxcell` available for the plot method with `biomod.projection.out` object. For example, 
`plot(myBiomodProj, maxcell = 5e6)`

Hope it helps 🙂 
Hélène

**Comment by zpmdal** [comment]
Thanks! That solved my problem.
