### ISSUE TITLE
Help with BIOMOD_FormatingData - [The function cannot form a database of species information and environmental information]

### ISSUE THREAD

**Issue by liushuhao-666** [biomodhub/biomod2#507]
Hi,

I'm using my own species information, including 0/1 and latitude and longitude, as well as environmental grids. I made sure that the species information was not duplicated and that the grid was fine. When I use the BIOMOD_FormatingData function, it doesn't work. See the result below.

I find this function does not work, I do not know why, please teach me how to solve it.

> myExpl
class       : SpatRaster 
dimensions  : 18, 15, 5  (nrow, ncol, nlyr)
resolution  : 0.5, 0.5  (x, y)
extent      : 119.75, 127.25, 26.25, 35.25  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
sources     : bs_mean.img  
              bt_mean.img  
              depth_mean.img  
              ... and 2 more source(s)
names       :      bs,        bt,  depth,      sss,      sst 
min values  : 30.2822,  9.984425,  16.00, 17.90484, 13.92985 
max values  : 34.8130, 25.676500, 138.25, 34.37285, 27.58349 

> # Format Data with true absences
> myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
+                                      expl.var = myExpl,
+                                      resp.xy = myRespXY,
+                                      resp.name =myRespName)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= aoguanbianxia Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 !!! Some data are located in the same raster cell. 
          Please set `filter.raster = TRUE` if you want an automatic filtering.
      ! No data has been set aside for modeling evaluation
 ! Some NAs have been automatically removed from your data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> myBiomodData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  aoguanbianxia

	 0 presences,  0 true absences and  0 undefined points in dataset

	 5 explanatory variables

       bs            bt          depth          sss           sst     
 Min.   : NA   Min.   : NA   Min.   : NA   Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA   1st Qu.: NA   1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA   Median : NA   Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN   Mean   :NaN   Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA   Max.   : NA   Max.   : NA   Max.   : NA  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> plot(myBiomodData)
错误于.plot.BIOMOD.formated.data.check.args(x = x, calib.lines = calib.lines, : 
  coordinates are required to plot BIOMOD.formated.data objects

**Comment by MayaGueguen** [comment]
Hello Mingmou,

Thank you for posting :pray:

That is strange indeed, as you both have no presences kept within your `BIOMOD.formated.data` object, nor values within your explanatory variables 👀 

Could you please send the output of the `sessionInfo()` command ?
Also, in order to check that both your explanatory variables and occurrence data are in the same projection system, could you try and plot them together ?
```
## For example with : 
plot(myExpl[[1]])
points(myRespXY, add = TRUE)

## But it might depend on the format of your object 
```

Maya

**Comment by liushuhao-666** [comment]
Thank you for your reply. I have output according to your suggestion. Please see the picture below and result.

> plot(myExpl[[1]])
> points(myRespXY, add = TRUE)
警告信息:
In plot.xy(xy.coords(x, y), type = type, ...) : "add"不是图形参数
> sessionInfo()
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8    LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                                LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_1.1.4          raster_3.6-26        sp_2.1-4             terra_1.7-78         xgboost_1.7.8.1      randomForest_4.7-1.1 maxnet_0.1.4        
 [8] earth_5.3.3          plotmo_3.6.4         plotrix_3.8-4        Formula_1.2-5        gbm_2.2.2            mgcv_1.9-1           nlme_3.1-164        
[15] gam_1.22-4           foreach_1.5.2        mda_0.5-4            class_7.3-22         rpart_4.1.23         nnet_7.3-19          biomod2_4.2-6-1     

loaded via a namespace (and not attached):
 [1] utf8_1.2.4             generics_0.1.3         stringi_1.8.4          lattice_0.22-6         magrittr_2.0.3         pROC_1.18.5           
 [7] grid_4.4.1             iterators_1.0.14       jsonlite_1.8.8         plyr_1.8.9             Matrix_1.7-0           reshape_0.8.9         
[13] survival_3.6-4         fansi_1.0.6            scales_1.3.0           codetools_0.2-20       PresenceAbsence_1.1.11 abind_1.4-8           
[19] cli_3.6.3              rlang_1.1.4            munsell_0.5.1          tools_4.4.1            reshape2_1.4.4         colorspace_2.1-0      
[25] ggplot2_3.5.1          vctrs_0.6.5            R6_2.5.1               lifecycle_1.0.4        stringr_1.5.1          pkgconfig_2.0.3       
[31] pillar_1.9.0           gtable_0.3.5           data.table_1.16.0      glue_1.7.0             dismo_1.3-14           Rcpp_1.0.12           
[37] tibble_3.2.1           tidyselect_1.2.1       rstudioapi_0.16.0      compiler_4.4.1         SDMtune_1.3.1         
警告信息:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  "add"不是图形参数
2: In doTryCatch(return(expr), name, parentenv, handler) :
  "add"不是图形参数




![QQ20240925-092321](https://github.com/user-attachments/assets/c922e2d6-e6ff-47e5-a5d6-10b635893804)

**Comment by MayaGueguen** [comment]
Hello,

Thank you for the informations :pray: 
I do not see any of your points on your raster plot.
Please check that coordinates of your `myRespXY` object are in the same projection system than your environmental variables.

Maya

**Comment by liushuhao-666** [comment]
Thank you very much for your reply. I have checked and found that the longitude range of the grid is 119.75, 127.25, 26.25, 35.25 (xmin, xmax, ymin, ymax), and the range of myRespXY is also in this range (please see myRespXY). I really don't know what to do next
![图片1](https://github.com/user-attachments/assets/679c58e4-4466-4e9a-88e0-ca587b6898fc)
![图片2](https://github.com/user-attachments/assets/d2f2350c-7240-401a-acc1-15d4f7f6944e)

**Comment by MayaGueguen** [comment]
Indeed it seems to be the same projection system.
However, could you try and switch the columns of your `myRespXY` ?
To have first the `lon` column and then the `lat` column. :eyes:

**Comment by liushuhao-666** [comment]
Wow, thank you so much. You're so smart. My problem is solved. Now, what else do I need to do? I think I need to talk about this conversation delete?

**Comment by MayaGueguen** [comment]
Glad to have been of help :slightly_smiling_face: 
You can now go on with your simulation and close this issue !
But do not hesitate to open a new one if you have other questions or issues :eyes: 

Maya
