### ISSUE TITLE
How does parallelization works?

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#508]
Hi,

I have non-coding question: I was trying to paralyze my code to speed up teh process. And i wonder about of number of cores to use.

For instance: if i have 3 models with 2 PAs : does it mean i can use 6 cores to paralyze it? will having >6 core be affective (or just extra cores wont be used)? I guess my questions is where the parallelization can be helpful and what determine the max number of cores i can use  (ig it will be number of models or number of runs?) so i do not over specify them.

**Comment by MayaGueguen** [comment]
Hello Yulia,

Well, here it depends on a few factors :eyes: 
- First, you have 3 models (algorithms I guess) and 2 PA : so you will have indeed at least 3 * 2 = 6 single models, but you might have more depending on how you set the cross-validation parameters.
For example, if you decide to use the `CV.strategy = 'random'` with `CV.nb.rep = 3` when calling the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function, it means that each of your PA dataset will be sampled 3 times, so 3 * 2 = 6 PA x CV datasets. And each of these will be used with each of your 3 algorithms leading to 3 * 6 = 18 single models.
If you keep `CV.do.full.models = TRUE`, then you will have 3 more single models (`_PA1_allRun`, `_PA2_allRun`, `_allData_allRun`) to add for each algorithms, leading to 3 * (6 + 3) = 54 single models.

- Now, which step is parallelized when you set the `nb.cpu` parameter to something > 1 
Well it will prepare all data for each single models, and run as many at the same time as you defined cores.
So if you set `nb.cpu = 6`, whether you have 6 or 18 or 54 single models to run, it will launch 6 at a time.
So indeed if you set `nb.cpu = 10` while you have only 6 single models to run, 4 threads will be open for nothing.

- :warning: BUT be cautious also in the other direction : the most efficient number of cores to use does not depend on how many single models you have to run but on your computer capacities.
For example, if you have 18 models to run, if you set `nb.cpu = 18` and your computer cannot handle it, it might overload your memory and crash the program.
This is why you have to understand both : 
1. the capacities of your computer (mainly : how many cores you have, and how much memory)
2. how much of these resources are used to run one single model

:arrow_right: You can use different tools to help you visualize that depending on your OS : `top` or `htop` command on linux / mac, task manager on windows / mac.

Hope it helps,
Maya

**Comment by yuliaUU** [comment]
Hi Maya,

Thank you for your explanations! I run on HPC: so, CPUs are the least concern. thank you for pointing out that the more models i run in parallel, the more memory i will need to have- that i think will be a bigger concern for me.
