### ISSUE TITLE
Question about scaling models 

### ISSUE THREAD

**Issue by amythor** [biomodhub/biomod2#509]
Hey biomod2 team, 

I am looking into producing an ensemble model, but am unsure about the scaling function for BIOMOD_Modelling. I see this is necessary for ANN and FDA, but at the same time is ill-advised. Should I set the scale.models function to TRUE as I as hoping to include these (as well as several of the other models), or would it be better to exclude them because of the warning. 

Thanks in advance, I have copied and pasted the warning I am referring to below. 

scale.models
"This parameter is quite experimental and it is recommended not to use it. It may lead to reduction in projection scale amplitude. Some categorical models always have to be scaled (FDA, ANN), but it may be interesting to scale all computed models to ensure comparable predictions (0-1000 range). It might be particularly useful when doing ensemble forecasting to remove the scale prediction effect (the more extended projections are, the more they influence ensemble forecasting results)."

**Comment by MayaGueguen** [comment]
Hello there :wave: 

Good question ! Actually, this parameter is quite old, as well as the documentation going with it...

:warning: Note that, whatever the value you give to `scale.models`, it will be set
- to `FALSE` for `SRE` models,
- and to `TRUE` for `ANN` and `FDA`.

So in your case, you can leave it to `FALSE` and still use `ANN` and `FDA` models in your analysis : they will be rescaled in any case :slightly_smiling_face: 

Maya

**Comment by amythor** [comment]
Awesome, thanks!
