### ISSUE TITLE
How can I define different pseudo-absence plots for each algorithm I'm using?

### ISSUE THREAD

**Issue by Oliveira-D-R** [biomodhub/biomod2#51]
I've read some examples of Biomod scripts but unfortunately I still can't understand how I can do this.

**Comment by MayaGueguen** [comment]
Hello,

It is actually not possible to define pseudo-absences for specific algorithm within one simulation command.
But then you just have to build different formating data object with the BIOMOD_FormatingData function, and give them to different BIOMOD_Modeling run, using each a different algorithm.

Hope it helps.

Maya

**Comment by Oliveira-D-R** [comment]
Many thanks for the reply. I will look for example scripts to try to apply this.
