### ISSUE TITLE
Question about variable importance - values of 1 or 0

### ISSUE THREAD

**Issue by amythor** [biomodhub/biomod2#510]
Hey biomod2 team, 

I have a question about the variable importance calculation output. I am running 6 algorithms (GAM, GLM, GBM, MARS, RF, and Maxent) and for a few variable importance scores I am getting a value of 1 or 0. I understand that values of 0 mean there is no influence on the model, and I guess 1 means complete correlation. 

My variables are bioclimatic variables chosen by first reducing the 32 available to 16 biologically relevant variables, and then I calculated VIF scores for these and were left with 6 least correlated variables (usdm package). 

Are these acceptable results or does this mean I should try do some tuning to these models returning these values? I don't want to remove these variables because in some of the other modelling algorithms they return high values, but if this is a big issue I guess I will have to rethink that.  Is it okay to move ahead to ensemble modelling?

In particular I am finding 1 or 0 in my GAM, GLM, MARS and MaxEnt models (usually only for one or two of the variables per algorithm, see attached output file). 

Any help is much appreciated!

[AllModels_PA1000_disk200km.csv](https://github.com/user-attachments/files/17247949/AllModels_PA1000_disk200km.csv)

**Comment by HeleneBlt** [comment]
Hello Amy, 

Your variable selection seems great! 💪 
Indeed, for the importance variables, the highest the value, the less reference and shuffled predictions are correlated, and the more influence the variable has on the model. A value of 0 assumes no influence of the variable on the model.
However, it seems that only the evaluation data was sent and not the variables importance. 

You can have a look at the responses curves with [bm_PlotResponseCurves](https://biomodhub.github.io/biomod2/reference/bm_PlotResponseCurves.html) to see the impact of the different variables on the response. It can help to understand what happened. 👀 
You can also look at the variable importance with an ensemble model: you will have a better idea of wich variable are more crucial. 

Hope it helps, 
Hélène

**Comment by amythor** [comment]
Thank you so much for the prompt response!

Oops yes I totally attached the wrong file, I have attached the variable importance file here instead. I have also attached the response curves for the 6 individual models, as well as the ensemble model, and the variable importance scores for the ensemble as well. 

Given these results I am just wondering if I need to better tune these models so that I am not getting these results, or if having values of 0 or 1 are acceptable? Or perhaps does it mean I should choose different variables?

Any help is appreciate, thanks so much!

Amy

[AllModels_PA1000_disk200km_var.csv](https://github.com/user-attachments/files/17285268/AllModels_PA1000_disk200km_var.csv)

![MODU_Ensemble_RC](https://github.com/user-attachments/assets/32e0c008-0031-44c9-91a3-0ec6d9d0276d)
![MODU_ensemble_varimp](https://github.com/user-attachments/assets/6126ee96-7bcc-49c8-8a51-7a4aecc62ccf)
![MODU_GAM_RC](https://github.com/user-attachments/assets/35e44ab1-8d0f-4e09-8eac-e53d8ce1bba4)
![MODU_GBM_RC](https://github.com/user-attachments/assets/897e536e-d2fb-4f87-a956-70bb73e74694)
![MODU_GLM_RC](https://github.com/user-attachments/assets/7c217597-96c4-40d2-b61e-203aa41111db)
![MODU_MARS_RC](https://github.com/user-attachments/assets/5ef2e3a0-141f-4afb-a211-f060a0c834fd)
![MODU_MaxEnt_RC](https://github.com/user-attachments/assets/7019a46d-5ccd-46f4-94f3-872f29a23479)
![MODU_RF_RC](https://github.com/user-attachments/assets/4c0a3653-b0c7-445a-9fa0-3dd67d4910eb)

**Comment by HeleneBlt** [comment]
Hi Amy, 

You have very good results so I don't think you really need to tune the models. 
The strange thing is that almost all your variables can be of great importance with some models and of little importance with others. 
In your case, I would use the response curves to select models for an ensemble model. For example, I would be sure to remove the RUN in red which often has a strange behaviour (see GBM). I will also consider removing Maxent models and maybe Mars models.  (You may already be doing this for your ensemble model. )
Remember you can have access to all the models names with [`get_built_models`](https://biomodhub.github.io/biomod2/reference/getters.out.html). 👀 

After, I would do an ensemble model with this selection and see the variables' importance. At this point, I will do a variable selection and remove the variable with an importance too weak. 

Hope it helps 🙂 
Hélène
