### ISSUE TITLE
Seeking advice on output from function  "bm_PlotEvalBoxplot " 

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#512]
Dear helpful biomod2 people
Please can you kindly help me understand the headings of the data table which is produced with this function.
As per the example biomod2 script we see the following.  
Please what does this represent, when the ROC and TSS values are themselves then provided with Sensitivity and Specificity values.
Also there are no validation or evaluation scores.   However in this example i think calibration is actually being produced as the evaluation value?
Thank you.   Best wishes, Carlos
```

> bm_PlotEvalBoxplot(bm.out = myBiomodEM, group.by = c('full.name', 'full.name'))
$tab
                                               full.name merged.by.PA merged.by.run merged.by.algo filtered.by     algo metric.eval cutoff sensitivity specificity calibration
1   GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS   EMmean         TSS  539.0      94.554      94.034       0.886
2   GuloGulo_EMmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS   EMmean         ROC  551.0      94.100      94.581       0.987
3 GuloGulo_EMmedianByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS EMmedian         TSS  587.0      93.192      94.089       0.872
4 GuloGulo_EMmedianByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS EMmedian         ROC  586.5      93.192      94.089       0.982
5     GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS     EMca         TSS  793.0      90.923      97.044       0.880
6     GuloGulo_EMcaByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS     EMca         ROC  794.5      90.923      97.044       0.989
7  GuloGulo_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS  EMwmean         TSS  537.0      94.705      94.198       0.889
8  GuloGulo_EMwmeanByTSS_mergedData_mergedRun_mergedAlgo   mergedData     mergedRun     mergedAlgo         TSS  EMwmean         ROC  540.5      94.705      94.362       0.988
  validation evaluation
1         NA         NA
2         NA         NA
3         NA         NA
4         NA         NA
5         NA         NA
6         NA         NA
7         NA         NA
8         NA         NA


```

**Comment by HeleneBlt** [comment]
Hi Carlos ! 

So if I detail the columns : 

- `full.name` : To know which models we are talking about. 
- `merged.by.PA`, `merged.by.run`, `merged.by.algo`: You create a Ensemble Model with `em.by = "all"` so here the dataset is always the same. 
- `filtered.by`: You select your models with "TSS"
- `algo` : the different EM you create

- `metric.eval`: your selected metrics
- `cutoff`: the optimized cutoff (under: 0, above: 1)
- `sensitivity`: the sensitivity obtained with this cutoff
- `specificity`: the specificity obtained with this cutoff
- `calibration`: the TSS value or ROC value with this cutoff

And finally, you don't have `validation` results because when you merge all your models, you also merge the different CV datasets so there is no longer a validation dataset.
 And you don't provide evaluation dataset at the beginning so there is neither an `evaluation` result. 

I hope it's clearer that way 🙂 . 
Don't hesitate if you need any further information. 
Hélène

**Comment by carlosbedson** [comment]
Thank you  Hélène   Merci beaucoups.   Yes this is all clear now.    I think where i had been unsure - which you might find thoughtful -was that when we consider a confusion matrix , the TSS value, is itself derived from calculations of true and false positives and negatives, as per the paper Fielding and Bell 1997 "A review of methods for the assessment of prediction errors in conservation presence/absence models".   However I can see now, how biomod2 is applying sensitivity and specificity to the various other metrics such as ROC, SR, ACCURACY and so on.   So thank you for clarifying.   I understand about not producing validation and evaluation values, i.e. reporting as NAs.  Ok. Great.  Thank you for taking the time with this.  Kind regards, Carlos

**Comment by MayaGueguen** [comment]
@carlosbedson 

If you want to have an illustration of biomod2 difference between _calibration_, _validation_ and _evaluation_ datasets, we just published a [new video](https://biomodhub.github.io/biomod2/articles/vignette_videos.html) :movie_camera: on our website. You might want to check the `02. Datasets` part, at 4:14 :eyes:

**Comment by carlosbedson** [comment]
Gosh Maya, thank you for thinking of me.    I just watched your video - It is one of the most helpful R / SDM videos i have ever seen.   There are a lot of new facilities in biomod2, which i am excited about.  eg multi size random sampling.     Thank you so much for thinking of me.   Best wishes to you and all the excellent biomod2 team.   Carlos
