### ISSUE TITLE
Variable response curve error -- 0%Error in { :    task 1 failed - "task 1 failed - "no applicable method for `@` applied to an object of class "list"""

### ISSUE THREAD

**Issue by carlosbedson** [biomodhub/biomod2#513]
Dear Helpful biomod2 team
please i am re-loading a previously run model - and i used to do this a lot and it all worked up to 2 months ago.
I am repeating this and receiving an error message.

`myBiomodEM<-get(load("D:/A_R_ANALYSIS_ENGLAND/BIOMOD.240520/OTTER/OTTER.1716219302.ensemble.models.out"))
`
This works and gets me to my models as shown.
```
myBiomodEM

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.ensemble.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

sp.name : OTTER

expl.var.names : BIO_1 BIO_2 BIO_3 BIO_4 BIO_6 BIO_8 BIO_12 BIO_15 LANDCOVER RIVERS ROADS SOILSCAPE TOPO_INDEX


models computed: 
OTTER_EMcaByROC_mergedData_mergedRun_mergedAlgo, OTTER_EMwmeanByROC_mergedData_mergedRun_mergedAlgo, OTTER_EMcvByROC_mergedData_mergedRun_mergedAlgo

models failed: none
```

Getting Variable Importance also works fine as follows and it plots the expected chart (not shown).
`bm_PlotVarImpBoxplot(bm.out = myBiomodEM, group.by = c('expl.var', 'full.name', 'full.name')) 
`
But the following makes an error.   

```
bm_PlotResponseCurves(bm.out = myBiomodEM, 
+                       models.chosen = get_built_models(myBiomodEM)[c(1, 2)],
+                       fixed.var = 'min')
  |                                                                                                        |   0%Error in { : 
  task 1 failed - "task 1 failed - "no applicable method for `@` applied to an object of class "list"""


```

I have separately set my working directory and my biomod2 output folders and my temp folders all lined up, but i cannot see what the error means.   
```
setwd("D:/A_R_ANALYSIS_ENGLAND/BIOMOD.240520")
terraOptions(tempdir="D:/A_R_ANALYSIS_ENGLAND/TEMP.FOLDER.240520")
```

Please can you offer any advice.  Thank you so much.   I really love using biomod2 and i hope this can get to work.  Best wishes Carlos

**Comment by HeleneBlt** [comment]
Hi Carlos !

Glad to know you still appreciate biomod2 ! 🎉 
It seems you have done this model with an old version. We had to modify some objects between the two versions, which led to this issue. 

If you know which version you used, you can reinstall it with the [archives](https://cran.r-project.org/src/contrib/Archive/biomod2/). 
Or if it was a short modelling, you can rerun it with the new version... 😬 

Hope it helps ! 
Hélène

**Comment by carlosbedson** [comment]
Hélène - merci beaucoups - again thank you - this has worked.  I had 15 models which had each taken 8 hours to run - so much preferable to use a roll-back of a previous biomod2 version.  Thank you again for your kind help.  Best wishes, Carlos
