### ISSUE TITLE
Presence data being removed in formatted data

### ISSUE THREAD

**Issue by kiaofen** [biomodhub/biomod2#52]
I have a presence only dataset with a single species. I tried used SpatialPoints as resp.var in BIOMOD_FormatingDATA:
`BS_2km<-read.csv("C:/Users/Danyang Shi/Desktop/Signature Work/Qilian/BS_2km.csv")`
`library("sp")`
`BS_SP<-SpatialPoints(BS_2km, proj4string=CRS("+proj=longlat +datum=WGS84"), bbox = NULL)`
`BSEnvPredProb90RF <- BIOMOD_FormatingData(resp.var = BS_SP,
                                        expl.var = envPredProb90m,
                                        resp.name = myRespName,
                                        PA.nb.rep = 1, PA.nb.absences = 1000, 
                                        PA.strategy = 'disk', PA.dist.min = 1000)`

and keep getting this error:

`Error in .BIOMOD_FormatingData.check.args(resp.name, resp.var, expl.var,  : 
  if given, resp.xy must be a 2 column matrix or data.frame`

So I tried following the example:
`BS_2km<-read.csv("C:/Users/Danyang Shi/Desktop/Signature Work/Qilian/BS_2km.csv")`
`>head(BS_2km)
 longitude latitude BS
1   97.7755  38.7906  1
2   97.7216  38.8065  1
3   97.5418  38.7942  1
4   97.6533  38.8536  1
5   97.6725  38.8393  1
6   97.6712  38.8367  1`
`myRespName <- 'BS'`
`BSpresence <- as.numeric(BS_2km[,myRespName])`
`BSXY<-BS_2km[,c("longitude","latitude")]`
`BSEnvPredProb300mRF <- BIOMOD_FormatingData(resp.var = BSpresence,
                                            expl.var = envPredProb300m,
                                            resp.name = myRespName, resp.xy = BSXY,
                                            PA.nb.rep = 1, PA.nb.absences = 1000, 
                                            PA.strategy = 'disk', PA.dist.min = 1000)`
`-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BS Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation

Checking Pseudo-absence selection arguments...

   > Disk pseudo absences selection
   > Pseudo absences are selected in explanatory variables
   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables
			! Some NAs have been automatically removed from your data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=`

The NAs that were removed are all the presence data from my original dataset. Because `> BSEnvPredProb300mRF@data.species` only has NAs, no 1s at all.

**Comment by MayaGueguen** [comment]
Hello there,

Could you please share with me your `csv` file, so I can reproduce the error and try to correct it ? :)

Maya

**Comment by jordanseider** [comment]
I, too, am having a similar issue. I am using `spatialPoints` as the `resp.var` and a `rasterStack` as my `expl.var`. Looks to remove all points from the response variable and deletes all data from the explanatory variable raster. I also get the same problem when using an independent evaluation set. 

```
# Summary of "resp.var"
> resp.var
class       : SpatialPointsDataFrame 
features    : 42 
extent      : -137.633, -132.0763, 68.00798, 69.4766  (xmin, xmax, ymin, ymax)
crs         : +proj=longlat +datum=WGS84 +no_defs 
variables   : 1
names       : PresAbs 
min values  :       1 
max values  :       1 

# Here is the summary of "current.clim" for reference
     bio1              bio2            bio3            bio4           bio11            bio15           bio18       
 Min.   :-14.404   Min.   :6.658   Min.   :13.64   Min.   :14.48   Min.   :-30.23   Min.   :45.19   Min.   : 46.00  
 1st Qu.:-10.088   1st Qu.:7.283   1st Qu.:15.66   1st Qu.:14.76   1st Qu.:-26.90   1st Qu.:48.93   1st Qu.: 66.00  
 Median : -9.679   Median :7.967   Median :16.62   Median :15.12   Median :-26.62   Median :58.14   Median : 85.00  
 Mean   :-10.389   Mean   :7.913   Mean   :16.40   Mean   :15.16   Mean   :-26.89   Mean   :56.66   Mean   : 83.82  
 3rd Qu.: -9.438   3rd Qu.:8.442   3rd Qu.:17.32   3rd Qu.:15.57   3rd Qu.:-25.98   3rd Qu.:62.28   3rd Qu.:102.00  
 Max.   : -8.529   Max.   :9.392   Max.   :18.13   Max.   :16.11   Max.   :-24.80   Max.   :67.32   Max.   :116.00  
      dem              slope               vrt           
 Min.   : -5.356   Min.   : 0.09048   Min.   :2.415e-06  
 1st Qu.: 13.444   1st Qu.: 0.41912   1st Qu.:1.820e-05  
 Median : 22.547   Median : 1.40161   Median :1.171e-04  
 Mean   : 65.613   Mean   : 3.58835   Mean   :2.409e-04  
 3rd Qu.: 73.402   3rd Qu.: 3.19652   3rd Qu.:2.172e-04  
 Max.   :430.563   Max.   :21.24728   Max.   :1.384e-03  

# Format data
> species.mod <- BIOMOD_FormatingData(resp.var = resp.var,
                                         expl.var = stack(current.clim),
                                         resp.name = modelname, # "Alnus.SDM"
                                         PA.nb.rep = 1,
                                         PA.nb.absences = nb.absences, # specified earlier in code; 195 in this example
                                         PA.strategy = "disk",
                                         PA.dist.min = 5000)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Alnus.SDM Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation

Checking Pseudo-absence selection arguments...

   > Disk pseudo absences selection
   > Pseudo absences are selected in explanatory variables
   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables
			! Some NAs have been automatically removed from your data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data.PA -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

sp.name =  Alnus.SDM

	 0 presences,  0 true absences and  195 undefined points in dataset


	 1 explanatory variables

     layer   
 Min.   :-1  
 1st Qu.:-1  
 Median :-1  
 Mean   :-1  
 3rd Qu.:-1  
 Max.   :-1  


 1 Pseudo Absences dataset available ( PA1 ) with  195 absences in each (true abs + pseudo abs)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by MayaGueguen** [comment]
Hello Jordan,

Could you provide me please your dataset, so I can reproduce the error and try to correct it ? :)

Maya

**Comment by MayaGueguen** [comment]
Hi Jordan,

Thank you so much for sharing your data and code ! 👌 
I think I was able to find the problem.
Please, update your `biomod2` version from the github and check and see if it all seems allright to you ? 👀 

Maya

**Comment by jordanseider** [comment]
Hi Maya, 

Looks much better now, thanks for taking a look!

Jordan
