### ISSUE TITLE
Help with BIOMOD 2-How could I save output raster in my hard disk?

### ISSUE THREAD

**Issue by Qingyiyaaa** [biomodhub/biomod2#520]
Hello,
My code run successfully while I am doing the ensemble modelling projection using BIOMOD_EnsembleForecasting, but after successfully running no ensemble raster file write in my hard disk. Can you please suggest me any suggestion?

The code are listed below:
myBiomodModelOut<-BIOMOD_Modeling(bm.format = myBiomodData,
                                  modeling.id = 'AllModels',
                                  models = c('XGBOOST','RF','MAXNET'),
                                  prevalence = 0.5, 
                                  CV.strategy = 'random', 
                                  CV.nb.rep = 30, 
                                  CV.perc = 0.8, 
                                  metric.eval = c('TSS','ROC'))
myBiomodModelOut

myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all',
                                      em.by = 'all',
                                      em.algo = c('EMwmean'),
                                      #metric.select = c('TSS'),
                                      #metric.select.thresh = c(0.85),
                                      metric.eval = c('TSS', 'ROC'),
                                      var.import = 3,
                                      seed.val = 42)
myBiomodEM
get_evaluations(myBiomodEM)
options(max.print=1000000) 
get_variables_importance(myBiomodEM)

myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')
myBiomodEMProj
plot(myBiomodEMProj)

Thank you very much!Looking for your reply!

**Comment by HeleneBlt** [comment]
Hello there, 

Could you help me by telling me whether a `your_species_name/CurrentEM` folder has been created? And if so, what files are is in this folder? 

Thanks a lot 
Hélène

**Comment by Qingyiyaaa** [comment]
hello,
There is a "proj_CurrentEM" folder. And there are "presence.CurrentEM.ensemble.projection""proj_CurrentEM_presence_ensemble"and a "individual_projections" folder in it. 
We would like to know if we can create our own folder and save the raster data results in our own folder.
Thank you very much!Looking for your reply!

**Comment by HeleneBlt** [comment]
Hi ! 

`biomod2` keeps everything in the same folder: `your_species_name`. You can change the localisation of this folder with the argument `dir.name` at the beginning with `BIOMOD_FormatingData`. 

However, you can move your raster after by hand or save your projection object somewhere else. If you need, you can also change the output format with `output.format` in [`BIOMOD_EnsembleForacsting`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html).  

Hope it helps 🙂 
Hélène
