### ISSUE TITLE
Help with BIOMOD_Error in { : task 20 failed - "无法打开链结" 此外: There were 50 or more warnings (use warnings() to see the first 50)

### ISSUE THREAD

**Issue by K0BE248** [biomodhub/biomod2#522]
hello，I've met some issues that i can‘t solve，need help plz.
**Context and question**
1: In .bm_ModelingOptions.check.args(data.type = data.type,  ... :
  Only one GAM model can be activated. 'GAM.mgcv.gam' has been set (other available : 'GAM.gam.gam' or 'GAM.mgcv.bam')
2: executing %dopar% sequentially: no parallel backend registered
3: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA1_RUN2_MAXENT_outputs/maxent.stderr': Permission denied
4: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA1_RUN3_MAXENT_outputs/maxent.stderr': Permission denied
5: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA1_RUN4_MAXENT_outputs/maxent.stderr': Permission denied
6: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA1_RUN5_MAXENT_outputs/maxent.stderr': Permission denied
7: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA1_allRun_MAXENT_outputs/maxent.stderr': Permission denied
8: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA2_RUN1_MAXENT_outputs/maxent.stderr': Permission denied
9: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA2_RUN2_MAXENT_outputs/maxent.stderr': Permission denied
10: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA2_RUN3_MAXENT_outputs/maxent.stderr': Permission denied
11: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA2_RUN4_MAXENT_outputs/maxent.stderr': Permission denied
12: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA2_RUN5_MAXENT_outputs/maxent.stderr': Permission denied
13: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA3_RUN2_MAXENT_outputs/maxent.stderr': Permission denied
14: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA3_RUN4_MAXENT_outputs/maxent.stderr': Permission denied
15: In file(con, "r") :
  无法打开文件'./aa/models/AllModels/aa_PA3_allRun_MAXENT_outputs/maxent.stderr': Permission denied
16: In forecast_0 * observed_0 : 整数上溢产生了NA
17: In forecast_0 * observed_0 : 整数上溢产生了NA
18: In forecast_0 * observed_0 : 整数上溢产生了NA
19: In forecast_0 * observed_0 : 整数上溢产生了NA
20: In forecast_0 * observed_0 : 整数上溢产生了NA
21: In forecast_0 * observed_0 : 整数上溢产生了NA
22: In forecast_0 * observed_0 : 整数上溢产生了NA
23: In forecast_0 * observed_0 : 整数上溢产生了NA
24: In forecast_0 * observed_0 : 整数上溢产生了NA
25: In forecast_0 * observed_0 : 整数上溢产生了NA
26: In forecast_0 * observed_0 : 整数上溢产生了NA
27: In forecast_0 * observed_0 : 整数上溢产生了NA
28: In forecast_0 * observed_0 : 整数上溢产生了NA
29: In forecast_0 * observed_0 : 整数上溢产生了NA
30: In forecast_0 * observed_0 : 整数上溢产生了NA
31: In forecast_0 * observed_0 : 整数上溢产生了NA
32: In forecast_0 * observed_0 : 整数上溢产生了NA
33: In forecast_0 * observed_0 : 整数上溢产生了NA
34: In forecast_0 * observed_0 : 整数上溢产生了NA
35: In forecast_0 * observed_0 : 整数上溢产生了NA
36: In forecast_0 * observed_0 : 整数上溢产生了NA
37: In forecast_0 * observed_0 : 整数上溢产生了NA
38: In forecast_0 * observed_0 : 整数上溢产生了NA
39: In forecast_0 * observed_0 : 整数上溢产生了NA
40: In forecast_0 * observed_0 : 整数上溢产生了NA
41: In forecast_0 * observed_0 : 整数上溢产生了NA
42: In forecast_0 * observed_0 : 整数上溢产生了NA
43: In forecast_0 * observed_0 : 整数上溢产生了NA
44: In forecast_0 * observed_0 : 整数上溢产生了NA
45: In forecast_0 * observed_0 : 整数上溢产生了NA
46: In forecast_0 * observed_0 : 整数上溢产生了NA
47: In forecast_0 * observed_0 : 整数上溢产生了NA
48: In forecast_0 * observed_0 : 整数上溢产生了NA
49: In forecast_0 * observed_0 : 整数上溢产生了NA
50: In forecast_0 * observed_0 : 整数上溢产生了NA.

**Code used**
biomod_data_aa <- BIOMOD_FormatingData(
  resp.var = resp_var_vect,  
  expl.var = env_stack,      
  resp.name = "aa",          
  PA.nb.rep = 3,             
  PA.nb.absences = 30000,   
  PA.strategy = 'disk',     
  PA.dist.min = 5000,       
  PA.dist.max = 10000        
)

models_to_run <- c("ANN", "CTA", "FDA", "GAM", "GBM", "GLM", "MARS", "RF", "SRE", "MAXENT")

aa_model_out <- BIOMOD_Modeling(
  bm.format = biomod_data_aa,
  modeling.id = 'AllModels',             
  models = models_to_run, 
  OPT.strategy = 'bigboss',
  CV.strategy = "kfold",
  CV.k = 5,
  CV.nb.rep = 1,                          
  CV.perc = 0.8,                           
  metric.eval = c('ROC', 'TSS', 'KAPPA'),  
  var.import = 2                         
)
```

**Comment by HeleneBlt** [comment]
Hi ! 

I see you already look at the other issues with the same message error. Does the Colin's solution help in any way ? 

Colin's solution: Run these lines of code before your modeling 
```
cl <- makeCluster(2)
on.exit(stopCluster(cl))
```

So I can help you, can you tell me which version of `biomod2` are you working with?

Thanks!
Hélène

**Comment by K0BE248** [comment]
Hi , Hélène !
Thank you so so so much for&nbsp; helping me this. I have tried Colin's solution yesterday,&nbsp; i&nbsp; added&nbsp;
###
&nbsp;cl <- makeCluster(2)
registerDoParallel(cl)
on.exit(stopCluster(cl))&nbsp;&nbsp;
&nbsp;then&nbsp; the "models_out"&nbsp; &nbsp;can successfully output .

&nbsp;My biomod2 version is 4.2-5-2. Actually, i have a problem all the time, the"bm.opt "thing, warning message show that&nbsp; n.trees&nbsp; need&nbsp; to adjust in GBM, but&nbsp; when i&nbsp; input code like this
###
bm.options <- bm_ModelingOptions(
&nbsp; GBM = list(n.trees = 500)
)

warning message&nbsp; came out "Error in bm_ModelingOptions(GBM = list(n.trees = 500)) : 
  参数没有用(GBM = list(n.trees = 500))" ,it shows that parameters don't work.


I 'm a new learner for R and BIOMOD2 package, these parameters that need to set&nbsp; are killing me . Most time , i&nbsp; ask chatgpt ,watch the biomod2 description file&nbsp; to modify mine,i don't how to&nbsp; adjust&nbsp; parameters&nbsp; accurately, i&nbsp;&nbsp;even&nbsp;don't know whether my code&nbsp; correct or not.&nbsp;


Thank you for answering me.I will add a "solved" label for my issue . NO KIDDING ,your reply like sunshine.&nbsp;
THANK U&nbsp; !!!
L.L


&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biomodhub/biomod2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biomodhub/biomod2] Help with BIOMOD_Error in { : task 20 failed - "无法打开链结" 此外: There were 50 or more warnings (use warnings() to see the first 50) (Issue #522)





 
Hi !
 
I see you already look at the other issues with the same message error. Does the Colin's solution help in any way ?
 
Colin's solution: Run these lines of code before your modeling
 cl <- makeCluster(2) on.exit(stopCluster(cl))  
So I can help you, can you tell me which version of biomod2 are you working with?
 
Thanks!
 Hélène

**Comment by HeleneBlt** [comment]
Hello again, 

Glad that it works ! 🎉 

Here some code to change the parameters for GBM
```
user.val <- list( GBM.binary.gbm.gbm = list(n.trees = 500))

myOpt <- bm_ModelingOptions(data.type = 'binary',
                            models = models_to_run,
                            strategy = "user.defined",
                            user.val = user.val,
                            user.base = "bigboss",
                            bm.format = biomod_data_aa)
```
You can give `myOpt` to `BIOMOD_Modeling` after with the argument `OPT.user`

Hope it helps!
Hélène

**Comment by K0BE248** [comment]
Thanks again ,Hélène
I'll try these code right now.Thanks for helping me!
Best wishes!!!

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biomodhub/biomod2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biomodhub/biomod2] Help with BIOMOD_Error in { : task 20 failed - "无法打开链结" 此外: There were 50 or more warnings (use warnings() to see the first 50) (Issue #522)





 
Hello again,
 
Glad that it works ! 🎉
 
Here some code to change the parameters for GBM
 user.val <- list( GBM.binary.gbm.gbm = list(n.trees = 500)) myOpt <- bm_ModelingOptions(data.type = 'binary',                             models = models_to_run,                             strategy = "user.defined",                             user.val = user.val,                             user.base = "bigboss",                             bm.format = biomod_data_aa)  
You can give myOpt to BIOMOD_Modeling after with the argument OPT.user
 
Hope it helps!
 Hélène
