### ISSUE TITLE
Error in validObject(.Object) :  invalid class “BIOMOD.models.options”

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#525]
I cant seem to be able to do modeling options:

```
myBiomodData <- BIOMOD_FormatingData(
    resp.name = name,
    resp.var = myResp,
    resp.xy = myRespXY,
    expl.var = myExpl,
    PA.nb.rep = 1,
    PA.nb.absences = nb,
    PA.strategy = PA.strategy,
    PA.dist.min = PA.dist.min,
    PA.dist.max = PA.dist.max,
    filter.raster = TRUE,
    dir.name = 'SDM'
  )
  # Do CV
  cv.k <- bm_CrossValidation(bm.format = myBiomodData,
                             strategy = 'kfold',
                             nb.rep = 2,
                             k = 3)
  ### Tune Models of the models ####
  myBiomodOptions <- bm_ModelingOptions(
    data.type = "binary.PA",
    models = c("GLM", "GAM.mgcv.bam", "ANN", "GBM", "CTA", "FDA", "RF", "MAXENT", "MAXNET", "XGBOOST"),
    strategy = "default",
    calib.lines = cv.k,
    bm.format = myBiomodData
  )
```
  
Error message: `Error in validObject(.Object) : 
  invalid class “BIOMOD.models.options” object: 1: invalid object for slot "models" in class "BIOMOD.models.options": got class "NULL", should be or extend class "character"
invalid class “BIOMOD.models.options” object: 2: invalid object for slot "options" in class "BIOMOD.models.options": got class "NULL", should be or extend class "list"`

but the code works with `data.type = "binary"`. I am not exactly sure why. My data has no 0s , just 1s and no NAs

**Comment by MayaGueguen** [comment]
Hello Yulia,

I'm sorry, we put extra documentation in prevision of future developments...
So in the version you use, `data.type` must always be fixed to `binary`.
Even if your data does not have 0, as you will sample some within your `NA` 🙂 

Could you please try again with this change ? 👀 
Maya

**Comment by yuliaUU** [comment]
yes, yes "binary" option always worked!
