### ISSUE TITLE
Help with BIOMOD_xxx - [I can not plot all layers of BIOMOD_EnsembleForecasting output]

### ISSUE THREAD

**Issue by zali37** [biomodhub/biomod2#530]
Hello there
**Context and question**
I tried to plot an ensemble forecasting output computed by EMmean, EMca, and EMcv but could not plot the last one, instead, I got a warning.

**Code used**
bibronii_ensemble_models <- BIOMOD_EnsembleModeling(
  bm.mod = bibronii_modelo,
  models.chosen = "all",
  em.by = "all",
  em.algo = c("EMmean", "EMca", "EMcv"),
  metric.select = c("TSS", "ROC"),
  metric.select.thresh = c(0.7, 0.7),
  metric.eval = c("TSS", "ROC"),
  var.import = 3
)
-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.ensemble.models.out -=-=-=-=-=-=-=-=-=-=-=-=

sp.name : bibronii

expl.var.names : clip_bio2 clip_bio5 clip_bio6 clip_bio15

models computed: 
bibronii_EMmeanByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMcaByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMcvByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMmeanByROC_mergedData_mergedRun_mergedAlgo, bibronii_EMcaByROC_mergedData_mergedRun_mergedAlgo, bibronii_EMcvByROC_mergedData_mergedRun_mergedAlgo

models failed: none

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

proj_scen <- c("stk_current",
               "stk_future_ssp370_2060",
               "stk_future_ssp370_2100",
               "stk_future_ssp585_2060",
               "stk_future_ssp585_2100")

for (scen in proj_scen) {
  cat("\n> projections of", scen)
  
  bibronii_proj <- BIOMOD_Projection(
    bm.mod = bibronii_modelo,
    proj.name = scen,
    new.env = get(scen),
    models.chosen = "all",
    metric.binary = "TSS",
    build.clamping.mask = FALSE,
    do.stack = FALSE,
    output.format = ".img"
  )
  
  bibronii_ens_proj <- BIOMOD_EnsembleForecasting(
    bm.em = bibronii_ensemble_models,
    bm.proj = bibronii_proj,
    proj.name = "ENMbibronii",
    models.chosen = 'all',
    metric.binary = 'TSS',
    metric.filter = 'all',
    do.stack = FALSE,
    output.format = ".img"
  )
}
-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.projection.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=

Projection directory : ./bibronii/stk_future_ssp585_2100

sp.name : bibronii

expl.var.names : clip_bio2 clip_bio5 clip_bio6 clip_bio15

modeling.id : solo_bibronii ( ./bibronii/bibronii.solo_bibronii.models.out 
)

models.projected : 
bibronii_allData_RUN1_SRE, bibronii_allData_RUN1_RF, bibronii_allData_RUN1_GAM, bibronii_allData_RUN1_ANN, bibronii_allData_RUN2_SRE, bibronii_allData_RUN2_RF, bibronii_allData_RUN2_GAM, bibronii_allData_RUN2_ANN, bibronii_allData_RUN3_SRE, bibronii_allData_RUN3_RF, bibronii_allData_RUN3_GAM, bibronii_allData_RUN3_ANN, bibronii_allData_RUN4_SRE, bibronii_allData_RUN4_RF, bibronii_allData_RUN4_GAM, bibronii_allData_RUN4_ANN, bibronii_allData_RUN5_SRE, bibronii_allData_RUN5_RF, bibronii_allData_RUN5_GAM, bibronii_allData_RUN5_ANN, bibronii_allData_allRun_SRE, bibronii_allData_allRun_RF, bibronii_allData_allRun_GAM, bibronii_allData_allRun_ANN

available binary projection : TSS

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.projection.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=

Projection directory : ./bibronii/ENMbibronii

sp.name : bibronii

expl.var.names : clip_bio2 clip_bio5 clip_bio6 clip_bio15

modeling.id : solo_bibronii ( 
./bibronii/bibronii.solo_bibronii.ensemble.models.out )

models.projected : 
bibronii_EMmeanByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMcaByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMcvByTSS_mergedData_mergedRun_mergedAlgo, bibronii_EMmeanByROC_mergedData_mergedRun_mergedAlgo, bibronii_EMcaByROC_mergedData_mergedRun_mergedAlgo, bibronii_EMcvByROC_mergedData_mergedRun_mergedAlgo

available binary projection : TSS

available filtered projection : TSS, ROC

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

plot(bibronii_ens_proj)
! Plotting only layer "bibronii_EMmeanByTSS_mergedData_mergedRun_mergedAlgo", "bibronii_EMcaByTSS_mergedData_mergedRun_mergedAlgo", "bibronii_EMmeanByROC_mergedData_mergedRun_mergedAlgo", and "bibronii_EMcaByROC_mergedData_mergedRun_mergedAlgo" of class <integer>
Warning message:
Mixed layer classes found in `tidyterra::geom_spat*()`. 

I do not know what the problem is.
Regards
Natalia

**Comment by HeleneBlt** [comment]
Hi Natalia, 

I will try to explain what happen here. 🙂  
To reduce the memory use, `biomod2` multiplies the predictions by 1000 to have integer. In this case, the created map will be save as integer. 
For `EMcv`, there is no sense to multiply by 1000 so it stay as a float and the created map will be save differently. 
So we have different classes, which leads to your warning. 

You have three solutions: 

- If you switch the `do.stack` argument to `TRUE`, all the projections will be save in the same way. But you will have only one raster for the different EM. 
- If you add the argument `on_0_1000 = FALSE` to `BIOMOD_Projection` and `BIOMOD_EnsembleForecasting`, you will avoid the multiplication by 1000 and all the map will be float. 
- If you don't want to change anything, you can still look at the EMcv projection manually. It will be in your folder `./bibronii/proj_ENMbibronii`

Hope it helps 🚀 
Don't hesitate if it's not clear. 
Hélène

**Comment by zali37** [comment]
Hello Helene
Thank you so much for your answer.
I don't want to change anything in the code. But I don't know how to look at the EMcv projection manually. Could you help me with that, please?

**Comment by HeleneBlt** [comment]
Hello Natalia, 

You can use the `terra` package:
```
predEMcv <- terra::rast("./bibronii/proj_CurrentENMbibronii/individual_projections/bibronii_EMcvByTSS_mergedData_mergedRun_mergedAlgo.img")
terra::plot(predEMcv)
```
Hope it will suit you! 🙂 
Hélène

**Comment by zali37** [comment]
Hi Helene
Thanks a lot, I could plot it
Regards
Natalia
