### ISSUE TITLE
Help with BIOMOD_4.2-5-2 - how to project only the ensemble model, without including each individual model

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#532]
Hi,
I use the codes "myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                             proj.name = 'CurrentEM',
                                             new.env = myExpl,
                                             models.chosen = 'all',
                                             metric.binary = 'ROC',
                                             metric.filter = 'ROC')
myBiomodEMProj2000".
I'm curious about how to project only the ensemble model, without including each individual model, as it is too time-consuming.

Best,
Ruiju

**Comment by HeleneBlt** [comment]
Hello Ruiju, 

`biomod2` needs the predictions of the individual models to be able to project the ensemble models. However when you plot `myBiomodEMProj`, you will see only the ensemble models.

If you want to reduce the number of individual models, you can do it with [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html).
You can ask for a higher threshold with the `metric.select.thresh` argument or you can select directly which models you want with the argument `models.chosen` and the function[`get_built_models`](https://biomodhub.github.io/biomod2/reference/getters.out.html). 

Don't hesitate if it's not clear 🙂 
Hélène

**Comment by tongruiju** [comment]
Hi Hélène，

Many thanks for your help.

"> myBiomodEMProj2000 <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
+                                              proj.name = 'CurrentEM',
+                                              new.env = myExpl,
+                                              models.chosen = 'all',
+                                              metric.binary = 'ROC',
+                                              metric.filter = 'ROC')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Creating suitable Workdir...

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Projecting SP_allData_RUN1_GBM ...
	> Projecting SP_allData_RUN2_GBM ...
	> Projecting SP_allData_RUN3_GBM ...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Projecting SP_EMwmeanByROC_mergedData_mergedRun_mergedAlgo ...

	> Building ROC binaries / filtered"

You can see that not only was the ensemble model projected, but also each individual model, which I did not want.

Best, 
Ruiju

**Comment by HeleneBlt** [comment]
Hi ! 

It's normal. To be able to calculate the mean prediction for a given pixel for example, `biomod2` needs first the prediction of the single models for this pixel. Maybe the term "projecting" is not the most adequate, we could have used "predicting" or "computing" 🙈 

Best, 
Hélène

**Comment by tongruiju** [comment]
Hi Hélène,
OK. Many thanks for your help.
Best, 
Ruiju
