### ISSUE TITLE
problems about  VALUEs of  AUC、TSS、KAPPA

### ISSUE THREAD

**Issue by K0BE248** [biomodhub/biomod2#540]
hello again,  some issues confuse me.
I have the  "model_evaluations"  by using  "get_evaluations", but  i  can't   know clearly all the  contents‘  meanings  in  this  dataframe. How to understand "calibration" and "validation"  , and which column stands for  the value of  "AUC" 、“TSS”、“KAPPA”？

```
actually，i want a dataframe or anything can clearly show all the values of AUC（tss 、kappa） about this model so that i can know whether the model good or not. How can i calculate them by  "model_evaluations" ? 
```
![屏幕截图 2024-11-11 164048](https://github.com/user-attachments/assets/dbd1ae1d-5ffa-4d7a-85e7-3dcc53fce722)

**Comment by MayaGueguen** [comment]
Hello L.L.

The `data.frame` you get when using the [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html) method returns you all values you need.
- The `metric.eval` column contains the different metrics you asked for through the `metric.eval` parameter within the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions.
If you look at your screenshot, you will see different lines for `TSS`, `ROC`, `KAPPA` within this column.
- You then have three columns at the end of the `data.frame`, each one corresponding to the dataset upon which the metric has been computed :
     + `calibration` : this is the part of your data used to calibrate your model, obtained from the cross-validation process
     (_see `CV.[...]` parameters within [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function or [bm_CrossValidation](https://biomodhub.github.io/biomod2/reference/bm_CrossValidation.html) function_)
     + `validation` : this is the remaining part
     + `evaluation` : this is an independant dataset, not used to build the models, that should contain both presences and absences and that you can provide to the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function through the `eval.[...]` parameters

:information_source: Note that you can also use the [bm_PlotEvalBoxplot](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalBoxplot.html) function to directly represent these values, and play with the `dataset` parameter.

Hope it helps,
Maya

**Comment by K0BE248** [comment]
I'm still confused. Can I consider the value of calibration to be the same as the values of AUC, TSS, or Kappa? For instance, the first row in my screenshot, metric.eval=TSS, calibration=0.584,  is TSS value of  aatest_PA1_RUN1_GBM equal  0.584?

**Comment by MayaGueguen** [comment]
This is a table. Each row gives you an information about one single model for which one evaluation metric has been calculated, over the 3 datasets (calibration, validation, evaluation) if available.

_For the first line, TSS has been computed for the `aatest_PA1_RUN1_GBM` model : it has a value of 0.584 over calibration dataset, and 0.599 over validation dataset._

If you search for the other lines for which `full.name = 'aatest_PA1_RUN1_GBM'`, you will find the other evaluation metrics computation.

Maya

**Comment by K0BE248** [comment]
i m clear this time, thank you again maya
