### ISSUE TITLE
biomod2 4.2-5-2--the error in bm_tunning

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#541]
Hi,

I would like to tune the parameters of GBM and MAXENT. Here is the error

**library(biomod2)
library(raster)
library(iterators)  
library(gam) 

# 读取物种分布数据
DataSpecies <- read.csv("E:\\paper11\\species\\DP.csv")

# 选择研究物种
attach(DataSpecies)
myRespName <- 'SP'
myResp <- as.numeric(DataSpecies[,myRespName])
myRespXY <- DataSpecies[,c("x", "y")]

# 读取环境变量
list <- list.files(path='E:\\paper11\\BioOracleTIFPJ\\ssp126\\EnVar2000', full.names=TRUE)
rasterData <- stack(list)
myExpl2000 <- raster::stack(rasterData)

# 格式化数据
myBiomodData <- BIOMOD_FormatingData(resp.var=myResp, expl.var=myExpl2000, resp.xy=myRespXY, resp.name=myRespName, na.rm=TRUE) 

# 10折交叉验证
cv.10 <- bm_CrossValidation(bm.format = myBiomodData, strategy = "kfold", k = 10, nb.rep = 1)
# 创建包含GBM和MAXENT模型的选项对象
> bm.options <- bm_ModelingOptions(data.type = 'binary', models = c('GBM', 'MAXENT'), strategy = 'default', bm.format = myBiomodData)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	>  GBM options (datatype: binary , package: gbm , function: gbm )...
	>  MAXENT options (datatype: binary , package: MAXENT , function: MAXENT )...

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> # 定义GBM模型的调参参数
> gbm.params <- list(
+     GBM.n.trees = seq(100, 5000, by = 500),
+     GBM.interaction.depth = seq(1, 10, by = 1),
+     GBM.shrinkage = seq(0.001, 0.1, by = 0.01),
+     GBM.n.minobsinnode = seq(10, 20, by = 2)
+ )
> 
> # 定义MAXENT模型的调参参数
> maxent.params <- list(
+     MAXENT.algorithm = "maxnet",
+     MAXENT.parallel = TRUE
+ )
> 
> # 使用bm_Tuning函数进行GBM模型的调参
> tuning.result.gbm <- bm_Tuning(
+     model = "GBM",
+     tuning.fun = "gbm",
+     do.formula = FALSE,
+     do.stepAIC = FALSE,
+     bm.options = bm.options, # 使用包含GBM和MAXENT的bm.options对象
+     bm.format = myBiomodData, 
+     calib.lines = NULL,
+     metric.eval = "TSS",
+     metric.AIC = "AIC",
+     weights = NULL,
+     ctrl.train = NULL,
+     params.train = gbm.params
+ )
Error in .fun_testIfInherits(TRUE, "bm.options", bm.options, c("BIOMOD.options.default",  : 
  
bm.options must be a 'BIOMOD.options.default' or 'BIOMOD.options.dataset' object** 

Best,
Ruiju

**Comment by HeleneBlt** [comment]
Hello Ruiju, 👋 

Thanks for reporting ! 
You just need a little change and give the `BIOMOD.options.default` of GBM instead of the all pack : 

```
tuning.result.gbm <- bm_Tuning(model = "GBM",
                               tuning.fun = "gbm",
                               do.formula = FALSE,
                               do.stepAIC = FALSE,
                               bm.options = bm.options@options$GBM.binary.gbm.gbm,
                               bm.format = myBiomodData, 
                               calib.lines = NULL,
                               metric.eval = "TSS",
                               metric.AIC = "AIC",
                               weights = NULL,
                               ctrl.train = NULL,
                               params.train = gbm.params)
```
The error message was probably not very helpful: we will find a way to improve it 💪 

Hope it helps,
Hélène

**Comment by tongruiju** [comment]
Hi Hélène,

Thank you very much. It works. And what about this one?
> tuning.result.maxent <- bm_Tuning(
+     model = "MAXENT",
+     tuning.fun = "maxnet",
+     do.formula = FALSE,
+     do.stepAIC = FALSE,
+     bm.options = bm.options@options$MAXENT.binary.maxnet.maxnet, # 使用单独的 MAXENT 选项对象
+     bm.format = myBiomodData, 
+     calib.lines = NULL,
+     metric.eval = "AICc",
+     metric.AIC = "AIC",
+     weights = NULL,
+     ctrl.train = NULL,
+     params.train = maxent.params
+ )
Error in .fun_testIfInherits(TRUE, "bm.options", bm.options, c("BIOMOD.options.default",  : 
  
bm.options must be a 'BIOMOD.options.default' or 'BIOMOD.options.dataset' object

Best, 
Ruiju

**Comment by HeleneBlt** [comment]
Hello again, 

All the different tuning functions, and other information, could be found in [ModelsTable](https://biomodhub.github.io/biomod2/reference/ModelsTable.html) 👀 
`data(ModelsTable) `

Here it will be : 
```
tuning.result.maxent <- bm_Tuning(model = "MAXENT",
                               tuning.fun = "ENMevaluate",
                               do.formula = FALSE,
                               do.stepAIC = FALSE,
                               bm.options = bm.options@options$MAXENT.binary.MAXENT.MAXENT,
                               bm.format = myBiomodData, 
                               calib.lines = NULL,
                               metric.eval = 'AICc',
                               metric.AIC = "AIC",
                               weights = NULL,
                               ctrl.train = NULL,
                               params.train = maxent.params)
```

Hope it helps, 
Hélène

**Comment by tongruiju** [comment]
Hi Hélène，

Thank you very much for your assistance. It works.

Best, 
Ruiju
