### ISSUE TITLE
Help with BIOMOD_4.2-5-2- How to utilize solely the hinge feature in MAXENT

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#544]
Hi,

I intended to utilize solely the hinge feature in MAXENT. Consequently, I set MAXENT.hinge = TRUE and assigned FALSE to the other four features. However, the tuning outcome remained unchanged. Did i miss anything?

Best, 
Ruiju

**> maxent.params <- list(MAXENT.algorithm = "maxnet", MAXENT.parallel = TRUE, MAXENT.linear = FALSE, MAXENT.quadratic = FALSE, MAXENT.product = FALSE, MAXENT.threshold = FALSE, MAXENT.hinge = TRUE)
> # 记录MAXENT模型调参开始时间
> start.time.maxent <- Sys.time()
> 
> # 使用 bm_Tuning 函数进行 MAXENT 模型的调参
> tuning.result.maxent <- bm_Tuning(
+     model = "MAXENT",
+     tuning.fun = "maxnet",
+     do.formula = FALSE,
+     do.stepAIC = FALSE,
+     bm.options = bm.options@options$MAXENT.binary.MAXENT.MAXENT, # 使用单独的 MAXENT 选项对象
+     bm.format = myBiomodData, 
+     calib.lines = NULL,
+     metric.eval = "AICc",
+     metric.AIC = "AIC",
+     weights = NULL,
+     ctrl.train = NULL,
+     params.train = maxent.params
+ )

		> Dataset _allData_allRun
			> Tuning parameters...Package ecospat is not installed, so Continuous Boyce Index (CBI) cannot be calculated.
*** Running initial checks... ***

* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Model evaluations with random 10-fold cross validation...

*** Running ENMeval v2.0.3 with maxnet from maxnet package v0.1.4 ***

  |                                                                                             |   0%
Of 32 total cores using 32...
Running in parallel using doSNOW...
  |=============================================================================================| 100%
ENMevaluate completed in 2 minutes 6 seconds.
> 
> # 记录MAXENT模型调参结束时间并计算时长
> end.time.maxent <- Sys.time()
> time.elapsed.maxent <- end.time.maxent - start.time.maxent
> print(paste("MAXENT tuning took", time.elapsed.maxent))
[1] "MAXENT tuning took 2.10924293200175"
> 
> print(tuning.result.maxent)
$`_allData_allRun`
$`_allData_allRun`$path_to_maxent.jar
[1] "E:/paper11/BioOracleTIFPJ/ssp126/DP"

$`_allData_allRun`$memory_allocated
[1] 512

$`_allData_allRun`$initial_heap_size
NULL

$`_allData_allRun`$max_heap_size
NULL

$`_allData_allRun`$background_data_dir
[1] "default"

$`_allData_allRun`$visible
[1] FALSE

$`_allData_allRun`$linear
[1] TRUE

$`_allData_allRun`$quadratic
[1] FALSE

$`_allData_allRun`$product
[1] FALSE

$`_allData_allRun`$threshold
[1] FALSE

$`_allData_allRun`$hinge
[1] FALSE

$`_allData_allRun`$lq2lqptthreshold
[1] 80

$`_allData_allRun`$l2lqthreshold
[1] 10

$`_allData_allRun`$hingethreshold
[1] 15

$`_allData_allRun`$beta_threshold
[1] -1

$`_allData_allRun`$beta_categorical
[1] -1

$`_allData_allRun`$beta_lqp
[1] -1

$`_allData_allRun`$beta_hinge
[1] -1

$`_allData_allRun`$betamultiplier
[1] 0.5
Levels: 0.5 1

$`_allData_allRun`$defaultprevalence
[1] 0.5
**

**Comment by HeleneBlt** [comment]
Hello there 👋 

The tuning of MAXENT is made by `ENMevaluate` of the package `ENMeval`. This function doesn't have an argument `MAXENT.hinge`.
To be able to choose your features, you will need to switch to the version 4.2-6-2  of Github with : 
```
library(devtools)
devtools::install_github("biomodhub/biomod2", dependencies = TRUE)
```
With this version, you can indicate your feature with `MAXENT.tune.args`. For example:
`maxent.params <- list(MAXENT.algorithm = "maxnet", MAXENT.parallel = TRUE, MAXENT.tune.args = list(fc = c("H") ))`

You can find more information in the documentation of [ENMevaluate](https://jamiemkass.github.io/ENMeval/reference/ENMevaluate.html).

Hope it helps,
Hélène

**Comment by tongruiju** [comment]
Hi Hélène，

I did as you suggested. It works.   

**
cv.10 <- bm_CrossValidation(bm.format = myBiomodData, strategy = "kfold", k = 10, nb.rep = 1)

bm.options <- bm_ModelingOptions(data.type = 'binary', models = c('GBM', 'MAXENT'), strategy = 'default', bm.format = myBiomodData)

gbm.params <- list(  
  GBM.n.trees = c(500, 1000, 2500),
  GBM.interaction.depth = 5,
  GBM.shrinkage = 0.01,
  GBM.n.minobsinnode = 10
)

 maxent.params <- list(
  MAXENT.algorithm = "maxnet",
  MAXENT.parallel = TRUE,
  MAXENT.tune.args = list(fc = c("H"), rm = c(1, 5, 10))
)

start.time.gbm <- Sys.time()

tuning.result.gbm <- bm_Tuning(model = "GBM",
                               tuning.fun = "gbm",
                               do.formula = FALSE,
                               do.stepAIC = FALSE,
                               bm.options = bm.options@options$GBM.binary.gbm.gbm,
                               bm.format = myBiomodData, 
                               calib.lines = NULL,
                               metric.eval = "TSS",
                               metric.AIC = "AIC",
                               weights = NULL,
                               ctrl.train = NULL,
                               params.train = gbm.params)

end.time.gbm <- Sys.time()
time.elapsed.gbm <- end.time.gbm - start.time.gbm
print(paste("GBM tuning took", time.elapsed.gbm))

start.time.maxent <- Sys.time()

 tuning.result.maxent <- bm_Tuning(model = "MAXENT",
                               tuning.fun = "ENMevaluate",
                               do.formula = FALSE,
                               do.stepAIC = FALSE,
                               bm.options = bm.options@options$MAXENT.binary.MAXENT.MAXENT,
                               bm.format = myBiomodData, 
                               calib.lines = NULL,
                               metric.eval = 'AICc',
                               metric.AIC = "AIC",
                               weights = NULL,
                               ctrl.train = NULL,
                               params.train = maxent.params)

end.time.maxent <- Sys.time()
time.elapsed.maxent <- end.time.maxent - start.time.maxent
print(paste("MAXENT tuning took", time.elapsed.maxent))

print(tuning.result.gbm)
print(tuning.result.maxent)

myBiomodModelOut <- BIOMOD_Modeling(
  bm.format = myBiomodData,
  models = c('GBM', 'MAXENT'),
  CV.strategy = 'kfold',
  CV.nb.rep = 1,
  CV.k = 10, 
  CV.perc = 0.8,
  var.import = 3,
  metric.eval = c('TSS', 'ROC', 'KAPPA'),
  OPT.strategy = "user.defined",
  OPT.user.val = list(
    MAXENT.binary.MAXENT.MAXENT = tuning.result.maxent,
    GBM.binary.gbm.gbm = tuning.result.gbm))**

 

 And i got the "Warning messages:**
1: In .BIOMOD.options.dataset.check.args(strategy = strategy, user.val = user.val,  :
  Options will be changed only for a subset of datasets (_allData_allRun) and not the others (_allData_RUN1, _allData_RUN2, _allData_RUN3, _allData_RUN4, _allData_RUN5, _allData_RUN6, _allData_RUN7, _allData_RUN8, _allData_RUN9, _allData_RUN10). 
Please update 'user.val' argument if this is not wanted.
2: In .BIOMOD.options.dataset.check.args(strategy = strategy, user.val = user.val,  :
  Options will be changed only for a subset of datasets (_allData_allRun) and not the others (_allData_RUN1, _allData_RUN2, _allData_RUN3, _allData_RUN4, _allData_RUN5, _allData_RUN6, _allData_RUN7, _allData_RUN8, _allData_RUN9, _allData_RUN10). 
Please update 'user.val' argument if this is not wanted."**

I do not require the models SP_allData_allRun_GBM and SP_allData_allRun_MAXENT, which utilize all species data for modeling. Additionally, these two models should not be included in the ensemble model. Instead, I need the OPT.user.val set for each of the remaining 20 models, which will serve as candidates for calculating the ensemble model. How should I configure this?

Best, 
Ruiju

**Comment by HeleneBlt** [comment]
Hello Ruiju, 


If you don't want the `_allData_allRun` models, you just have to set the arguments `CV.do.full.models` to `FALSE`. 🚀 

For the options, you have two possibilities : 
- if you want a tuning for each run, you can do : 
```
myBiomodModelOut <- BIOMOD_Modeling(
  bm.format = myBiomodData,
  models = c('GBM', 'MAXENT'),
  CV.strategy = 'kfold',
  CV.nb.rep = 1,
  CV.k = 3, 
  CV.perc = 0.8,
  var.import = 3,
  metric.eval = c('TSS','ROC', 'KAPPA'),
  OPT.strategy = "tuned",
  CV.do.full.models = F
)
```

- if you want the same parameters for each run, you can change the names of your parameters.

```
names(tuning.result.maxent) <- "for_all_datasets"
names(tuning.result.gbm) <- "for_all_datasets"
```

Best,
Hélène

**Comment by tongruiju** [comment]
Hi Hélène,

It works. Thank you very much. One more question please? For MAXNET, not MAXENT, can I set to use only hinge features?

Best, 
Ruiju

**
bm.options <- bm_ModelingOptions(data.type = 'binary', models = c('GBM', 'MAXNET'), strategy = 'default', bm.format = myBiomodData)

gbm.params <- list(  
  GBM.n.trees = c(500, 1000, 2500),
  GBM.interaction.depth = 5,
  GBM.shrinkage = 0.01,
  GBM.n.minobsinnode = 10
)

start.time.gbm <- Sys.time()

tuning.result.gbm <- bm_Tuning(model = "GBM",
                               tuning.fun = "gbm",
                               do.formula = FALSE,
                               do.stepAIC = FALSE,
                               bm.options = bm.options@options$GBM.binary.gbm.gbm,
                               bm.format = myBiomodData, 
                               calib.lines = NULL,
                               metric.eval = "TSS",
                               metric.AIC = "AIC",
                               weights = NULL,
                               ctrl.train = NULL,
                               params.train = gbm.params)

end.time.gbm <- Sys.time()
time.elapsed.gbm <- end.time.gbm - start.time.gbm
print(paste("GBM tuning took", time.elapsed.gbm))

names(tuning.result.gbm) <- "for_all_datasets"

myBiomodModelOut <- BIOMOD_Modeling(
  bm.format = myBiomodData,
  models = c('GBM', 'MAXNET'),
  CV.strategy = 'kfold',
  CV.nb.rep = 1,
  CV.k = 10, 
  CV.perc = 0.8,
  var.import = 3,
  metric.eval = c('TSS', 'ROC', 'KAPPA'),
  OPT.strategy = "user.defined",
  OPT.user.val = list(GBM.binary.gbm.gbm = tuning.result.gbm), CV.do.full.models = F)**

**Comment by HeleneBlt** [comment]
Hello again, 

You can have a look at the [documentation](https://cran.r-project.org/web/packages/maxnet/maxnet.pdf) of the package maxnet to see how it handle it. 

To incorporate it, you will have to add options to `maxnet`. It will look like this: 
```
OPT.user.val = list(GBM.binary.gbm.gbm = tuning.result.gbm, 
                    MAXNET.binary.maxnet.maxnet = list("for_all_datasets" = list(classes = "h")))
```

Best, 
Hélène

**Comment by tongruiju** [comment]
Hi Hélène,

It works. Thank you very much.
Best, 
Ruiju
