### ISSUE TITLE
Error in { : task 3 failed - "must have 'max' > 'min'"

### ISSUE THREAD

**Issue by ninzyfb** [biomodhub/biomod2#55]
I am getting this error when attempting to run BIOMOD_Modeling() on my usual datasets:

`Error in { : task 3 failed - "must have 'max' > 'min'"`

I have not changed the code and was not getting this error in the past so am not sure what it could be referring to? I have a dataset with 61 presences, 100 absences and 10 explanatory variables.

Thanks in advance for your help, Nina

**Comment by MayaGueguen** [comment]
Hi Nina,

I will need more informations to be able to help you.
Do you think you could share with me your data so I can try and check where the error comes from ? :)

Maya

**Comment by ninzyfb** [comment]
Hi Maya,

Sure, apologies i should've been more clear in my question.

The code which is failing is:
static_models <- BIOMOD_Modeling(
  data, # your biomod object
  models = c('GAM','GLM','MAXENT.Phillips'), # 3 modelling algorithms run for project
  bm.options  = mxtPh, # modified model parameters, unnecessary if you are happy with default biomod2 parameters
  nb.rep = 1, # 10-fold cross validation (number of evaluations to run)
  data.split.perc = 75, # 75% of data used for calibration, 25% for testing
  metric.eval  = c('TSS'), # evaluation method, TSS is True Statistics Skill
  save.output  = TRUE, # keep all results on hard drive 
  scale.models = FALSE, # if true, all model prediction will be scaled with a binomial GLM
  modeling.id = target, # name of model = species name (target)
  nb.cpu = 8,
  ) 
Here is a link to a folder which contains the data object: https://www.dropbox.com/sh/kfgcygj18rzk61b/AABHnihW8TYYwS7-thJRGDYba?dl=0 

Please let me know if you need anything else.

**Comment by MayaGueguen** [comment]
Thank you Nina ! I will look at that as soon as possible :eyes:

**Comment by ninzyfb** [comment]
Thanks Maya, any luck? I've tried running my data through the code in different ways to see if anything changes but i still keep getting the error.
