### ISSUE TITLE
Help with BIOMOD_Modeling - maxnet taking much longer than other models

### ISSUE THREAD

**Issue by joshc99** [biomodhub/biomod2#554]
Hi there,

I have loved using biomod so far! But I have run into an issue of efficiency and time when trying to include maxnet. (From this point, I will refer to MaxEnt and MaxNet so I will capitalise the 4th letter to make it a bit easier to distinguish). I've had to exclude MaxEnt from my current methods because the HPC I am using does not have java. With that in mind, I would really like to use MaxNet as it is a very similar method and would I feel it should be at least examined due to its (MaxEnt's) popularity. 

I have a large dataset (120,000 presence points, 120,000 pseudo-absences) but all other biomod model types (excluding MaxEnt and MaxNet) run very efficiently (less than 3 minutes with the specs I have been using on a HPC). With the same specs, MaxNet took 6+ hours. I am trying to evaluate model accuracy, and using 10 runs of CV on 4 different species, which then makes the 6 hours infeasible. I have tried using a smaller number of points and this helps significantly (100 points = 0.9 seconds, 1,000 points = 3.8 seconds, 10,000 points = 3.2 minutes, 120,000 points = 6.2 or 6.5 hours [I have tried twice]) but I am hoping to not need to use a smaller samplesize.

I have a few questions based on these details:
1) Is this expected? It seems odd for this method to be so much less efficient than other methods? Is there a reason MaxNet is so much less efficient or am I doing something wrong/there is a bug?

2) Is there a way to increase efficiency of using MaxNet? Can the model parameters be easily tweaked?

3) Is MaxEnt any more efficient? I cannot get Java on the HPC but could potentially get it on my laptop. I can run the other models on my local machine (the HPC was needed for raster manipulation and biomod formatting) so this could be an option. Could MaxEnt handle 100,000 points in a reasonable time on a normal laptop (16 gb ram, i7 processor)?

4) At the moment, I feel like my options are: 1) remove MaxNet, 2) try MaxEnt locally, or 3) reduce the CV reps/species/number of presences. Do you have any other suggestions?

I have added below the code from when I tested MaxNet on 120,000 presence and 120,000 pseudo-absence points.

Thank you for any assistance!
Kind regards,

```
> bmod_all

-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  species.effic.test

	 120801 presences,  0 true absences and  120801 undefined points in dataset


	 9 explanatory variables

 enviro_var_1      enviro_var_2      enviro_var_3      enviro_var_4      
 Min.   :     0.0   Min.   :     0   Min.   :     0   Min.   :     0.0  
 1st Qu.:     0.0   1st Qu.:  2900   1st Qu.:    50   1st Qu.:   982.3  
 Median :   223.6   Median :  7367   Median :   450   Median :  2707.4  
 Mean   :  2035.3   Mean   : 30057   Mean   :  2480   Mean   : 14571.2  
 3rd Qu.:  1274.8   3rd Qu.: 17580   3rd Qu.:  1776   3rd Qu.:  6788.0  
 Max.   :513419.9   Max.   :880214   Max.   :534951   Max.   :551188.2  
  enviro_var_5      enviro_var_6      enviro_var_7      enviro_var_8
 Min.   :     0   Min.   :     0   Min.   :     0   Min.   :     0  
 1st Qu.:   250   1st Qu.:  1756   1st Qu.: 24752   1st Qu.:   300  
 Median :  1470   Median :  4168   Median : 96058   Median :  1487  
 Mean   :  5572   Mean   : 11583   Mean   :139688   Mean   :  3980  
 3rd Qu.:  5202   3rd Qu.:  9949   3rd Qu.:204890   3rd Qu.:  4813  
 Max.   :516455   Max.   :540333   Max.   :930896   Max.   :536378  
 enviro_var_9      
 Min.   :     0.0  
 1st Qu.:   667.1  
 Median :  1555.6  
 Mean   :  5859.7  
 3rd Qu.:  3500.0  
 Max.   :567126.9  


 1 Pseudo Absences dataset available ( PA1 ) with  120801 (PA1) 
pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> time_start=Sys.time()
> 
> biomod_effic=BIOMOD_Modeling(modeling.id='testing.effic',
+                              bm.format=bmod_all,
+                              models="MAXNET", 
+                              CV.strategy='random',
+                              CV.nb.rep=1,
+                              CV.perc=0.8,
+                              CV.do.full.models=FALSE,
+                              metric.eval="ROC",
+                              nb.cpu=15)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...

	> Automatic weights creation to rise a 0.5 prevalence
Creating suitable Workdir...


Checking Cross-Validation arguments...

   > Random cross-validation selection

-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=

	>  MAXNET options (datatype: binary , package: maxnet , function: maxnet )...

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=



-=-=-=-=-=-=-=-=-=-= Aquila.audax.effic.test Modeling Summary -=-=-=-=-=-=-=-=-=-=

 9  environmental variables ( enviro_var_1 enviro_var_2 enviro_var_3 enviro_var_4 enviro_var_5 enviro_var_6 enviro_var_7 enviro_var_8 enviro_var_9 )
Number of evaluation repetitions : 1
Models selected : MAXNET 

Total number of model runs: 1 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=--=-=-=- species.effic.test_PA1_RUN1_MAXNET 

	Evaluating Model stuff...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> time_end=Sys.time()
> 
> time_end-time_start
Time difference of 6.249349 hours
```

**Comment by MayaGueguen** [comment]
Hello Josh :wave: 

Long time no see ! Glad to hear that you have been doing fine with biomod2 since then  :sun_with_face: 

Note that biomod2 is only gathering together and calling models developed in other packages (_except from the `SRE` model coded in our package, and `MAXENT` model which is calling the external executable file_).
You can check our last [tutorial video](https://biomodhub.github.io/biomod2/articles/vignette_videos.html) at time 19:49 introducing this.

It means that we don't necessary have thorough insights on how functions are coded.

But if you don't mind sharing you dataset and code, you can send them to me at maya.gueguen [at] univ-grenoble-alpes.fr so I can try and explore a bit what's going on. :pray: 

:eyes: Also, you are using 120801 presence points and 120801 PA points, which represent the whole remaining points of your study area. I guess it is a simulated dataset ? Is there a specific reason why you use these points as PA and not "real" absences ? Have you tried changing them in absences, to see if it makes a difference ?

Maya

**Comment by joshc99** [comment]
Dear Maya,

Thank you for your quick response! 

I understand that biomod is using an external package for the maxnet calculations. I was just wondering if it is known to be much less efficient than the other modelling methods - but I understand if this is not known :) 

I have now sent you the code and data used. I have just sent the biomod formatted data as my data points and raster layers are very large. Any assistance or insight you could provide would be greatly appreciated!

I will also attempt to use the points as true absences for maxnet and see if this changes the efficiency. I'll update this post once that has run.

A secondary question I had (hopefully I don't need to raise a new ticket) was when trying to use the 'bigboss' parameters that tweak the parameters to be more suited for most SDMs, is it sufficient to add the line strategy='bigboss' within the BIOMOD_Modeling() function, or do we need to first call the bm_ModelingOptions() function separately?

Thank you!

**Comment by MayaGueguen** [comment]
Hello Josh,

Thank you for your understanding, and for providing me your data :pray: 

I did some tests and here are the results : 
- 1000 pres + 1000 PA = 5 sec
- 10000 pres + 10000 PA = 5 min
- same times if I transform the PA into real absences
- 1000 pres + 10000 PA = 35 sec
- 10000 pres + 1000 PA = 39 sec

So it is really coming from how `maxnet` deals with an exponentially increasing number of points, no (big) matter whether it is the number of presences or pseudo-absences.

:information_source: I must say that 120 000 is a rather big number of points, whether of presences or PA. Is this a virtual species ? and/or a virtual study area ? I mean that it is not often that we have so many records, or that we use so many PA points without over-sampling all of our study area.

:eyes: Depending on your interest, you might want to try and test our development version in which abundance models are available ? All informations are contained in [this vignette](https://biomodhub.github.io/biomod2/articles/vignette_Abundance.html) on our documentation website.

:warning: I missed that in my first message, but beware that `nb.cpu` parameter allows to parallelize over single models... So in your case, even if you ask for 16 ressources, as you have only one `maxnet` model, you will use only 1 core on your computer :grimacing: 

As for your last question : yes, no need to go through the [bm_ModelingOptions](https://biomodhub.github.io/biomod2/reference/bm_ModelingOptions.html) function if you simply want to use biomod2 parameterization. You can directly set `OPT.strategy = 'bigboss'` when calling [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function :slightly_smiling_face: 

Hope it helps,
Maya

**Comment by joshc99** [comment]
Hi Maya,

Thanks for looking into this! I also did a test after your suggestion and I used (10,000 presence + 10,000 true absence) and (10,000 presence +  10,000 pseudo absences), and got very similar times. 

I realise this is quite a large data set but it was just surprising to me that the other models could handle it easily :)  The model is 10 years of citizen science observations across all of Australia for a pretty common species. I guess I could look at taking a sample of that (say 10-50,000). Otherwise, I will either try MaxEnt on my local machine, or reducing the number of PA reps and species I examine.

Noted about the nb.cpu - I did not notice a pickup in performance so that makes sense! Also noted about the bigboss, I'm glad that was being implemented correctly.

Thank you again for your help!
I love how much resources and assistance there is for using biomod!

Thanks,
Kind regards

**Comment by joshc99** [comment]
Sorry unsure how to mark this resolved. I hope "close with comment" is the correct option :)

**Comment by MayaGueguen** [comment]
"_Close with comment_" works perfectly fine :slightly_smiling_face: 

Actually, just had another look at your data. Indeed, I see Australia when plotting the coordinates :eyes: 
And when looking only at your presence points (120801 points), and doing a `unique` over your variables values, I reduce the set to 49556 points.
I did not think of it at first, as you are giving your data as `data.frame` to [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function, but a common practice is to keep only one releve per grid cell, when working with raster files. We actually add the `filter.raster` parameter to the function to do so.

Maya

**Comment by joshc99** [comment]
Hi Maya, that’s a good point also. 

I had considered filtering during the formatting but I wasn’t sure if it was the right choice. Since it’s citizen science data, I thought multiple sightings in the same spot should be weighted more than a single sighting in one spot (because I assume that spot is more conducive to a sighting) so I figured that leaving the data without filtering would achieve this. Does that make sense?

Thank you for the follow up!
