### ISSUE TITLE
ensemble modeling error message

### ISSUE THREAD

**Issue by K0BE248** [biomodhub/biomod2#559]
hi，biomod2 team ！ I am in trouble with the ensemble modeling function.
![屏幕截图 2024-12-17 224953](https://github.com/user-attachments/assets/74601934-7721-445e-9325-a67f88238aa4)
please help me check codes and parameters, seems like there is something wrong with my map/environment raster? 
and that warning message about   em.by = 'PA+run', i don't know what happend

**Comment by HeleneBlt** [comment]
Hello there, 

Thanks for reporting! 
Could you avoid sharing your code with a screenshot, but instead copy and paste it, which would help us recreate the error? Thanks ! 🙂 

To help you, could you share the output of : 
- your environment raster 
-  `show(your_biomod_formatted_data)`
- `show(aa_rm_out)`

Thanks !
Hélène

**Comment by K0BE248** [comment]
> env_stack <- rast("D:/Biomod2/env_stack.tif")
> View(env_stack)
> show(env_stack)
class       : SpatRaster 
dimensions  : 4320, 8640, 26  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : env_stack.tif 
names       : bio13, bio14,    bio15, bio18, bio19,   bio2, ... 
min values  :     0,     0,   0.0000,     0,     0,  1.000, ... 
max values  :  2768,   507, 230.6915,  5608,  5230, 21.973, ...

**Comment by K0BE248** [comment]
Sry about that screenshot, i won't do that again and I paste codes below.

> env_stack <- rast("D:/Biomod2/env_stack.tif")
> View(env_stack)
> show(env_stack)
class       : SpatRaster 
dimensions  : 4320, 8640, 26  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : env_stack.tif 
names       : bio13, bio14,    bio15, bio18, bio19,   bio2, ... 
min values  :     0,     0,   0.0000,     0,     0,  1.000, ... 
max values  :  2768,   507, 230.6915,  5608,  5230, 21.973, ...


> show(aa_rm)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  aa

	 9163 presences,  0 true absences and  27000 undefined points in dataset


	 26 explanatory variables

     bio13            bio14           bio15            bio18          bio19             bio2             bio3              bio8             bio9        
 Min.   :   0.0   Min.   :  0.0   Min.   :  0.00   Min.   :   0   Min.   :   0.0   Min.   : 1.000   Min.   :  9.417   Min.   :-37.49   Min.   :-40.676  
 1st Qu.:  58.0   1st Qu.:  3.0   1st Qu.: 38.30   1st Qu.: 106   1st Qu.:  29.0   1st Qu.: 9.048   1st Qu.: 25.661   1st Qu.: 12.29   1st Qu.: -7.811  
 Median : 111.0   Median : 12.0   Median : 61.04   Median : 206   Median :  70.0   Median :11.226   Median : 45.300   Median : 21.25   Median : 17.005  
 Mean   : 150.9   Mean   : 22.9   Mean   : 64.40   Mean   : 262   Mean   : 157.7   Mean   :11.138   Mean   : 45.761   Mean   : 18.01   Mean   :  8.423  
 3rd Qu.: 223.0   3rd Qu.: 28.0   3rd Qu.: 85.62   3rd Qu.: 359   3rd Qu.: 170.0   3rd Qu.:13.075   3rd Qu.: 63.835   3rd Qu.: 25.52   3rd Qu.: 23.822  
 Max.   :2103.0   Max.   :456.0   Max.   :219.92   Max.   :4616   Max.   :2727.0   Max.   :20.091   Max.   :100.000   Max.   : 37.29   Max.   : 37.093  
 wc2.1_2.5m_elev  slope_degree_plannar   asp_planar     c3ann_his_avg      c3nfx_his_avg      c3per_his_avg       c4ann_his_avg      c4per_his_avg      
 Min.   : -83.0   Min.   : 0.00000     Min.   : -1.00   Min.   :0.000000   Min.   :0.000000   Min.   :0.0000000   Min.   :0.000000   Min.   :0.0000000  
 1st Qu.: 141.0   1st Qu.: 0.09698     1st Qu.: 85.35   1st Qu.:0.000000   1st Qu.:0.000000   1st Qu.:0.0000000   1st Qu.:0.000000   1st Qu.:0.0000000  
 Median : 355.0   Median : 0.25193     Median :175.91   Median :0.006847   Median :0.001304   Median :0.0002151   Median :0.001312   Median :0.0000000  
 Mean   : 597.6   Mean   : 0.62143     Mean   :176.81   Mean   :0.060555   Mean   :0.018557   Mean   :0.0143876   Mean   :0.022968   Mean   :0.0059668  
 3rd Qu.: 751.0   3rd Qu.: 0.70176     3rd Qu.:267.95   3rd Qu.:0.053462   3rd Qu.:0.015422   3rd Qu.:0.0107984   3rd Qu.:0.022171   3rd Qu.:0.0002902  
 Max.   :6185.0   Max.   :12.98324     Max.   :359.90   Max.   :0.803801   Max.   :0.548776   Max.   :0.5552350   Max.   :0.619374   Max.   :0.3438889  
 pastr_his_avg       primf_his_avg    primn_his_avg     range_his_avg      secdf_his_avg     secdn_his_avg       secma_his_avg     secmb_his_avg    
 Min.   :0.0000000   Min.   :0.0000   Min.   :0.00000   Min.   :0.000000   Min.   :0.00000   Min.   :0.0000000   Min.   :   1.00   Min.   : 0.0000  
 1st Qu.:0.0000000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.000000   1st Qu.:0.00000   1st Qu.:0.0000000   1st Qu.:  10.46   1st Qu.: 0.2105  
 Median :0.0003602   Median :0.0000   Median :0.02372   Median :0.004786   Median :0.00000   Median :0.0000066   Median :  32.93   Median : 0.9184  
 Mean   :0.0771469   Mean   :0.1793   Mean   :0.22209   Mean   :0.146650   Mean   :0.09477   Mean   :0.0766528   Mean   :  90.09   Mean   : 2.4845  
 3rd Qu.:0.1091018   3rd Qu.:0.2135   3rd Qu.:0.36254   3rd Qu.:0.171871   3rd Qu.:0.06830   3rd Qu.:0.0642699   3rd Qu.: 123.96   3rd Qu.: 3.0063  
 Max.   :0.8890629   Max.   :1.0000   Max.   :1.00000   Max.   :1.000000   Max.   :0.99856   Max.   :1.0000000   Max.   :1032.73   Max.   :17.6427  
 urban_his_avg      
 Min.   :0.0000000  
 1st Qu.:0.0000000  
 Median :0.0000098  
 Mean   :0.0121025  
 3rd Qu.:0.0026161  
 Max.   :0.8637319  


 1 Pseudo Absences dataset available ( PA1 ) with  27000 (PA1) pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


> show(aa_rm_out) 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  Modeling folder : .  Species modeled : aa  Modeling id : Models  Considered variables : bio13 bio14 bio15 bio18 bio19 bio2 bio3 bio8 bio9 wc2.1_2.5m_elev slope_degree_plannar asp_planar c3ann_his_avg c3nfx_his_avg  c3per_his_avg c4ann_his_avg c4per_his_avg pastr_his_avg primf_his_avg primn_his_avg range_his_avg secdf_his_avg secdn_his_avg secma_his_avg secmb_his_avg  urban_his_avg   Computed Models :  aa_PA1_RUN1_RF aa_PA1_RUN1_MAXENT aa_PA1_RUN1_GAM aa_PA1_RUN1_GBM aa_PA1_RUN1_GLM aa_PA1_RUN1_FDA aa_PA1_RUN1_CTA aa_PA1_RUN1_SRE  aa_PA1_RUN1_ANN aa_PA1_RUN2_RF aa_PA1_RUN2_MAXENT aa_PA1_RUN2_GAM aa_PA1_RUN2_GBM aa_PA1_RUN2_GLM aa_PA1_RUN2_FDA aa_PA1_RUN2_CTA aa_PA1_RUN2_SRE  aa_PA1_RUN2_ANN aa_PA1_RUN3_RF aa_PA1_RUN3_MAXENT aa_PA1_RUN3_GAM aa_PA1_RUN3_GBM aa_PA1_RUN3_GLM aa_PA1_RUN3_FDA aa_PA1_RUN3_CTA aa_PA1_RUN3_SRE  aa_PA1_RUN3_ANN aa_PA1_RUN4_RF aa_PA1_RUN4_MAXENT aa_PA1_RUN4_GAM aa_PA1_RUN4_GBM aa_PA1_RUN4_GLM aa_PA1_RUN4_FDA aa_PA1_RUN4_CTA aa_PA1_RUN4_SRE  aa_PA1_RUN4_ANN aa_PA1_RUN5_RF aa_PA1_RUN5_MAXENT aa_PA1_RUN5_GAM aa_PA1_RUN5_GBM aa_PA1_RUN5_GLM aa_PA1_RUN5_FDA aa_PA1_RUN5_CTA aa_PA1_RUN5_SRE  aa_PA1_RUN5_ANN aa_PA1_RUN6_RF aa_PA1_RUN6_MAXENT aa_PA1_RUN6_GAM aa_PA1_RUN6_GBM aa_PA1_RUN6_GLM aa_PA1_RUN6_FDA aa_PA1_RUN6_CTA aa_PA1_RUN6_SRE  aa_PA1_RUN6_ANN aa_PA1_RUN7_RF aa_PA1_RUN7_MAXENT aa_PA1_RUN7_GAM aa_PA1_RUN7_GBM aa_PA1_RUN7_GLM aa_PA1_RUN7_FDA aa_PA1_RUN7_CTA aa_PA1_RUN7_SRE  aa_PA1_RUN7_ANN aa_PA1_RUN8_RF aa_PA1_RUN8_MAXENT aa_PA1_RUN8_GAM aa_PA1_RUN8_GBM aa_PA1_RUN8_GLM aa_PA1_RUN8_FDA aa_PA1_RUN8_CTA aa_PA1_RUN8_SRE  aa_PA1_RUN8_ANN aa_PA1_RUN9_RF aa_PA1_RUN9_MAXENT aa_PA1_RUN9_GAM aa_PA1_RUN9_GBM aa_PA1_RUN9_GLM aa_PA1_RUN9_FDA aa_PA1_RUN9_CTA aa_PA1_RUN9_SRE  aa_PA1_RUN9_ANN aa_PA1_RUN10_RF aa_PA1_RUN10_MAXENT aa_PA1_RUN10_GAM aa_PA1_RUN10_GBM aa_PA1_RUN10_GLM aa_PA1_RUN10_FDA aa_PA1_RUN10_CTA aa_PA1_RUN10_SRE  aa_PA1_RUN10_ANN aa_PA1_RUN11_RF aa_PA1_RUN11_MAXENT aa_PA1_RUN11_GAM aa_PA1_RUN11_GBM aa_PA1_RUN11_GLM aa_PA1_RUN11_FDA aa_PA1_RUN11_CTA aa_PA1_RUN11_SRE  aa_PA1_RUN11_ANN aa_PA1_RUN12_RF aa_PA1_RUN12_MAXENT aa_PA1_RUN12_GAM aa_PA1_RUN12_GBM aa_PA1_RUN12_GLM aa_PA1_RUN12_FDA aa_PA1_RUN12_CTA aa_PA1_RUN12_SRE  aa_PA1_RUN12_ANN aa_PA1_RUN13_RF aa_PA1_RUN13_MAXENT aa_PA1_RUN13_GAM aa_PA1_RUN13_GBM aa_PA1_RUN13_GLM aa_PA1_RUN13_FDA aa_PA1_RUN13_CTA aa_PA1_RUN13_SRE  aa_PA1_RUN13_ANN aa_PA1_RUN14_RF aa_PA1_RUN14_MAXENT aa_PA1_RUN14_GAM aa_PA1_RUN14_GBM aa_PA1_RUN14_GLM aa_PA1_RUN14_FDA aa_PA1_RUN14_CTA aa_PA1_RUN14_SRE  aa_PA1_RUN14_ANN aa_PA1_RUN15_RF aa_PA1_RUN15_GAM aa_PA1_RUN15_GBM aa_PA1_RUN15_GLM aa_PA1_RUN15_FDA aa_PA1_RUN15_CTA aa_PA1_RUN15_SRE aa_PA1_RUN15_ANN  aa_PA1_allRun_RF aa_PA1_allRun_MAXENT aa_PA1_allRun_GAM aa_PA1_allRun_GBM aa_PA1_allRun_GLM aa_PA1_allRun_FDA aa_PA1_allRun_CTA aa_PA1_allRun_SRE  aa_PA1_allRun_ANN aa_allData_allRun_RF aa_allData_allRun_MAXENT aa_allData_allRun_GAM aa_allData_allRun_GBM aa_allData_allRun_GLM aa_allData_allRun_FDA  aa_allData_allRun_CTA aa_allData_allRun_SRE aa_allData_allRun_ANN   Failed Models :  aa_PA1_RUN15_MAXENT  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 
 Shoul i provide any other output  results?

**Comment by HeleneBlt** [comment]
Hello, 

With this information, my first guess is that it is a memory issue! You have a large dataset and a lot of variables! 
Maybe you can try reducing your number of variables. With 26 variables, I wouldn't be surprised some of them are correlated. 
You can also check whether you have the latest version of `terra` and update it if necessary. 

(Please note that the biomod2 team is going on winter vacation starting tonight. ❄️ So we won't be able to answer you for a few weeks! Sorry... ) 

Best,
Hélène

**Comment by K0BE248** [comment]
Thank you, I'll try to fix it.
And i wish you have a good vacation！
