### ISSUE TITLE
Error in nrow(newdata) : argument "newdata" is missing, with no default

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#56]
Hello, 
When I started learning, through the sample code, I am getting this error when attempting to run BIOMOD_Modeling() on my usual datasets:
Error in nrow(newdata) : argument "newdata" is missing, with no default
Error in { : task 1 failed - "object 'seedval' not found"
![error](https://user-images.githubusercontent.com/55433348/166097105-e9b274f6-38e0-4fbe-a94c-d68aff32444f.png)

I have not changed the code.
Thanks in advance for your help, Weicheng

**Comment by MayaGueguen** [comment]
Hello there,
Sorry, my fault, I did some corrections last week without rechecking all examples.
It should be corrected now, but please tell me if you encounter new errors.
Maya

**Comment by 675979649** [comment]
Dear Maya,
&nbsp;&nbsp;Thank you very much for your reply.&nbsp;I don't know if it's a problem with my version or the code, this situation still exists.
Here is the code:
library(biomod2)
library(raster)
library(sp)
library(rasterVis)
library(lattice)


setwd("E:/")
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)


myRespName <- 'GuloGulo'


myResp <- as.numeric(DataSpecies[, myRespName])


myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]


myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))


#-------------------------------------------------------------------------------
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;expl.var = myExpl,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;resp.xy = myRespXY,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;resp.name = myRespName)
myBiomodData
plot(myBiomodData)


myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; modeling.id = 'AllModels',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bm.options = myBiomodOptions,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nb.rep = 2,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; data.split.perc = 80,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; metric.eval = c('TSS','ROC'),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var.import = 3,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; do.full.models = FALSE)



Here are the results:
R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)


R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.


R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.


Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


[Workspace loaded from ~/.RData]


&gt; library(biomod2)
&gt; library(raster)
&gt; library(sp)
&gt; library(rasterVis)
&gt; library(lattice)


&gt; setwd("E:/")
&gt; myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
&gt; DataSpecies <- read.csv(myFile, row.names = 1)


&gt; myRespName <- 'GuloGulo'


&gt; myResp <- as.numeric(DataSpecies[, myRespName])


&gt; myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]


&gt; myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
&gt; myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))


&gt; myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; expl.var = myExpl,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; resp.xy = myRespXY,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; resp.name = myRespName)


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


&gt; No pseudo absences selection !
&nbsp; &nbsp; &nbsp; ! No data has been set aside for modeling evaluation
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
&gt; myBiomodData


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


sp.name =&nbsp; GuloGulo


	 661 presences,&nbsp; 1827 true absences and&nbsp; 0 undefined points in dataset




	 5 explanatory variables


&nbsp; &nbsp; &nbsp; bio3&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bio4&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bio7&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bio11&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bio12&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp;Min.&nbsp; &nbsp;:10.19&nbsp; &nbsp;Min.&nbsp; &nbsp;:&nbsp; &nbsp;72&nbsp; &nbsp;Min.&nbsp; &nbsp;: 54.5&nbsp; &nbsp;Min.&nbsp; &nbsp;:-447.75&nbsp; &nbsp;Min.&nbsp; &nbsp;:&nbsp; &nbsp;0.028&nbsp;&nbsp;
&nbsp;1st Qu.:21.22&nbsp; &nbsp;1st Qu.: 2641&nbsp; &nbsp;1st Qu.:186.0&nbsp; &nbsp;1st Qu.:-184.32&nbsp; &nbsp;1st Qu.: 276.493&nbsp;&nbsp;
&nbsp;Median :35.00&nbsp; &nbsp;Median : 6682&nbsp; &nbsp;Median :306.2&nbsp; &nbsp;Median :&nbsp; 24.23&nbsp; &nbsp;Median : 562.931&nbsp;&nbsp;
&nbsp;Mean&nbsp; &nbsp;:40.29&nbsp; &nbsp;Mean&nbsp; &nbsp;: 7358&nbsp; &nbsp;Mean&nbsp; &nbsp;:310.9&nbsp; &nbsp;Mean&nbsp; &nbsp;:&nbsp; -2.64&nbsp; &nbsp;Mean&nbsp; &nbsp;: 853.516&nbsp;&nbsp;
&nbsp;3rd Qu.:56.35&nbsp; &nbsp;3rd Qu.:11752&nbsp; &nbsp;3rd Qu.:424.6&nbsp; &nbsp;3rd Qu.: 196.30&nbsp; &nbsp;3rd Qu.:1200.592&nbsp;&nbsp;
&nbsp;Max.&nbsp; &nbsp;:92.00&nbsp; &nbsp;Max.&nbsp; &nbsp;:22314&nbsp; &nbsp;Max.&nbsp; &nbsp;:718.0&nbsp; &nbsp;Max.&nbsp; &nbsp;: 283.00&nbsp; &nbsp;Max.&nbsp; &nbsp;:5431.002&nbsp;&nbsp;


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
&gt; plot(myBiomodData)


&gt; myBiomodOptions <- BIOMOD_ModelingOptions()
&gt; myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;modeling.id = 'AllModels',
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bm.options = myBiomodOptions,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nb.rep = 2,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;data.split.perc = 80,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;metric.eval = c('TSS','ROC'),
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;var.import = 3,
+&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;do.full.models = FALSE)


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=




Checking Models arguments...


Creating suitable Workdir...


	&gt; Automatic weights creation to rise a 0.5 prevalence




-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


&nbsp;5&nbsp; environmental variables ( bio3 bio4 bio7 bio11 bio12 )
Number of evaluation repetitions : 2
Models selected : GLM GBM GAM CTA ANN SRE FDA MARS RF MAXENT.Phillips MAXENT.Phillips.2&nbsp;


Total number of model runs: 22&nbsp;


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=




-=-=-=- Run :&nbsp; GuloGulo_AllData&nbsp;




-=-=-=--=-=-=- GuloGulo_AllData_RUN1&nbsp;


Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
Model=Generalised Boosting Regression&nbsp;
	 2500 maximum different trees and&nbsp; 3&nbsp; Fold Cross-Validation
	&gt; GBM modeling...CV: 1&nbsp;
CV: 2&nbsp;
CV: 3&nbsp;


	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default


Model=GAM
	 GAM_mgcv algorithm chosen
	Automatic formula generation...
	&gt; GAM (mgcv) modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default


Model=Classification tree&nbsp;
	 5 Fold Cross-Validation
	&gt; CTA modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default


Model=Artificial Neural Network&nbsp;
	 5 Fold Cross Validation + 3 Repetitions
	&gt; ANN modeling...
	Model scaling...
*** single value predicted
&nbsp; &nbsp;! Note :&nbsp; GuloGulo_AllData_RUN1_ANN failed!


Model=Surface Range Envelop
Model=Flexible Discriminant Analysis
Model=Multiple Adaptive Regression Splines ( simple with no interaction )


Model=Breiman and Cutler's random forests for classification and regression
	&gt; RF modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default


Model=MAXENT.Phillips
Model=MAXENT.Phillips (maxnet)Error in { : task 1 failed - "object 'seedval' not found"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biomodhub/biomod2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biomodhub/biomod2] Error in nrow(newdata) : argument "newdata" is missing, with no default (Issue #56)





 
Hello there,
 Sorry, my fault, I did some corrections last week without rechecking all examples.
 It should be corrected now, but please tell me if you encounter new errors.
 Maya

**Comment by MayaGueguen** [comment]
Hello Weicheng,

Did you try and install the new `biomod2` version ?
You can do it with the following commands : 
```
library(devtools)
devtools::install_github("biomodhub/biomod2", dependencies = TRUE)
```

Maya

**Comment by 675979649** [comment]
I am willing to try the new version and hope it can model better.
I will timely feedback if there is any problem.
Best wishes
