### ISSUE TITLE
.Error in nrow(newdata) : argument "newdata" is missing, with no default

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#57]
Hello, there
I ran the latest code. But there are still mistakes
Here is the code:
library(biomod2)
library(raster)
library(sp)
library(rasterVis)
library(lattice)

setwd("E:/")
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)

myRespName <- 'GuloGulo'

myResp <- as.numeric(DataSpecies[, myRespName])

myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

#-------------------------------------------------------------------------------
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)
myBiomodData
plot(myBiomodData)

myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    modeling.id = 'AllModels',
                                    bm.options = myBiomodOptions,
                                    nb.rep = 2,
                                    data.split.perc = 80,
                                    metric.eval = c('TSS','ROC'),
                                    var.import = 3,
                                    do.full.models = FALSE)

Here are the results:
R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> library(biomod2)
> library(raster)
> library(sp)
> library(rasterVis)
> library(lattice)

> setwd("E:/")
> myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
> DataSpecies <- read.csv(myFile, row.names = 1)

> myRespName <- 'GuloGulo'

> myResp <- as.numeric(DataSpecies[, myRespName])

> myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

> myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
> myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

> myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
+                                      expl.var = myExpl,
+                                      resp.xy = myRespXY,
+                                      resp.name = myRespName)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> **No pseudo absences selection !
      ! No data has been set aside for modeling evaluation**
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> myBiomodData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

sp.name =  GuloGulo

	 661 presences,  1827 true absences and  0 undefined points in dataset

	 5 explanatory variables

      bio3            bio4            bio7           bio11             bio12         
 Min.   :10.19   Min.   :   72   Min.   : 54.5   Min.   :-447.75   Min.   :   0.028 
 1st Qu.:21.22   1st Qu.: 2641   1st Qu.:186.0   1st Qu.:-184.32   1st Qu.: 276.493 
 Median :35.00   Median : 6682   Median :306.2   Median :  24.23   Median : 562.931 
 Mean   :40.29   Mean   : 7358   Mean   :310.9   Mean   :  -2.64   Mean   : 853.516 
 3rd Qu.:56.35   3rd Qu.:11752   3rd Qu.:424.6   3rd Qu.: 196.30   3rd Qu.:1200.592 
 Max.   :92.00   Max.   :22314   Max.   :718.0   Max.   : 283.00   Max.   :5431.002 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> plot(myBiomodData)

> myBiomodOptions <- BIOMOD_ModelingOptions()
> myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
+                                     modeling.id = 'AllModels',
+                                     bm.options = myBiomodOptions,
+                                     nb.rep = 2,
+                                     data.split.perc = 80,
+                                     metric.eval = c('TSS','ROC'),
+                                     var.import = 3,
+                                     do.full.models = FALSE)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Checking Models arguments...

Creating suitable Workdir...

	> Automatic weights creation to rise a 0.5 prevalence

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 5  environmental variables ( bio3 bio4 bio7 bio11 bio12 )
Number of evaluation repetitions : 2
Models selected : GLM GBM GAM CTA ANN SRE FDA MARS RF MAXENT.Phillips MAXENT.Phillips.2

Total number of model runs: 22

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

-=-=-=- Run :  GuloGulo_AllData

-=-=-=--=-=-=- GuloGulo_AllData_RUN1

Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
Model=Generalised Boosting Regression
	 2500 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...CV: 1
CV: 2
CV: 3

	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default

Model=GAM
	 GAM_mgcv algorithm chosen
	Automatic formula generation...
	> GAM (mgcv) modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default

Model=Classification tree
	 5 Fold Cross-Validation
	> CTA modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...Error in nrow(newdata) : argument "newdata" is missing, with no default

Model=Artificial Neural Network
	 5 Fold Cross Validation + 3 Repetitions
	> ANN modeling...
	Model scaling...
*** single value predicted
   ! Note :  GuloGulo_AllData_RUN1_ANN failed!

Model=Surface Range Envelop
Model=Flexible Discriminant Analysis
Model=Multiple Adaptive Regression Splines ( simple with no interaction )

Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions..**.Error in nrow(newdata) : argument "newdata" is missing, with no default**

Model=MAXENT.Phillips
Model=MAXENT.Phillips (maxnet)Error in { : task 1 failed - "object 'seedval' not found"

Thanks in advance for your help, Weicheng

**Comment by MayaGueguen** [comment]
Hello,

I'm really sorry but I ran exactly the code you gave and I do not have any errors anymore..
Could you please try reinstalling the package once again please ? :pray: 
So sorry for the bothering

Maya
