### ISSUE TITLE
Unable to plot response curves

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#58]
Hello，
When I simulated with the sample code, I had problems modeling single model and plotting the corresponding curve.

**model single model：**
Warning messages:
1: executing %dopar% sequentially: no parallel backend registered 
2: glm.fit:算法没有聚合 
3: glm.fit:拟合機率算出来是数值零或一 
4: the glm algorithm did not converge for response "GuloGulo" 
5: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Fitting terminated with step failure - check results carefully
6: glm.fit:算法没有聚合 
7: glm.fit:拟合機率算出来是数值零或一 
8: the glm algorithm did not converge for response "GuloGulo" 

**Represent response curves：**
> bm_PlotEvalMean(bm.out = myBiomodModelOut)
> bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
+ models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
+ fixed.var = 'median')
  |                                                                                                              |   0%Error in { : 
  task 1 failed - "task 1 failed - "argument "newdata" is missing, with no default""

I tried to change the code but it didn't work. When I try to ensemble models, part of the response curve can be plotted.

**Comment by MayaGueguen** [comment]
Hello there,

This bug should be fixed. You can check it by re installing the github version of the package.

Sorry for the inconvenience
Maya

**Comment by 675979649** [comment]
> Hello there,
> 
> This bug should be fixed. You can check it by re installing the github version of the package.
> 
> Sorry for the inconvenience Maya

Thanks for your reply.
The response curve seems to work fine, but then you get the following message：
> bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
+                       models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
+                       fixed.var = 'median')
  |================================================================================================================| 100%
**No id variables; using all as measure variables**
I don't know if this will affect the accuracy of the results.

In addition，I found that the following warning messages occur when plotting evaluation socres and variable importance:
> bm_PlotEvalMean(bm.out = myBiomodEM, group.by = 'model')
Warning messages:
1: Removed 1 rows containing missing values (geom_point). 
2: Removed 7 rows containing missing values (geom_errorbarh). 
> bm_PlotEvalBoxplot(bm.out = myBiomodEM, group.by = c('model', 'model'))
Warning message:
Removed 2 rows containing non-finite values (stat_boxplot).

**Comment by MayaGueguen** [comment]
Cool that it is fixed !

Concerning the warning message : `No id variables; using all as measure variables`
It will not impact the results, it is only that you can give a subset of the explanatory variables to be plotted, if you don't fill this parameter, it calculates response curves for all initial explanatory variables.

Concerning the warning messages from `bm_PlotEvalBoxplot`, it only means that some evaluation scores (or variables importance) were `NA`, and have been removed from the plot. No incidence either.

Hope it helps
Maya

**Comment by 675979649** [comment]
That should be all right. Thanks again for your help.
Best,
Weicheng

**Comment by 675979649** [comment]
> Cool that it is fixed !
> 
> Concerning the warning message : `No id variables; using all as measure variables` It will not impact the results, it is only that you can give a subset of the explanatory variables to be plotted, if you don't fill this parameter, it calculates response curves for all initial explanatory variables.
> 
> Concerning the warning messages from `bm_PlotEvalBoxplot`, it only means that some evaluation scores (or variables importance) were `NA`, and have been removed from the plot. No incidence either.
> 
> Hope it helps Maya

Hello Maya，
When I was ready to start using my own data, I encountered the following error while importing raster data：
> myFiles <- paste0('external/bioclim/current/bio', c(1:19), '.asc')
> myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  provide a valid filename
I think it is my own problem, can you help me solve it？
Best.

**Comment by 675979649** [comment]
If my own data is in TIF format, do I need to convert to GRD format to continue building the model, or can I use a similar method in Biomod2 version 3.5.1？

**Comment by MayaGueguen** [comment]
The builiding of raster stack is independent of `biomod2`.
You can use whatever format you want, it's just that here it is loading example files available with the `biomod2` package, and `.grd` is their extension.
For information, you should use the latest version, as the 3.5.1 is no longer sustained.

**Comment by 675979649** [comment]
Maybe I didn't express myself clearly. When I use biomod 4.0, I need to use tif files to fit my own species distribution data, but it reports an error：
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))
**Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) :**

**Comment by 675979649** [comment]
I'm sorry, it's my problem. I changed the code and it works fine now. Thank you for your reply!
