### ISSUE TITLE
BIOMOD_cv error: missing values and NaN's not allowed if 'na.rm' is FALSE

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#60]
Hi,

I am trying to run some model cross-validations to test overfitting.
I keep coming across this error:

"Error in quantile.default(data@coord[balance, 2], probs = seq(0, 100,  :
  missing values and NaN's not allowed if 'na.rm' is FALSE"

It turns out, my data is of the presence-only type and, thus, I create
pseudo-absences:

"deer2010_formatdata <- BIOMOD_FormatingData(resp.var =
deerPoints2010['Presence'],
                                            resp.xy =
coordinates(deerPoints2010_LonLat),
                                            expl.var = deerVariables.2010,
                                            [resp.name](http://resp.name/) = "Mazama 10",
                                            PA.nb.rep = 1,
                                            PA.nb.absences =
nrow(deerPoints2010)*100,
                                            PA.strategy = 'random')"

As far as I understand, during the data formatting step, several NAs are added.
When I run data2010_formatdata@data.species, I can see that those NAs are where
the pseudoabsences should be.

I tried to unlist it and reclassify it as numeric, as well as using adding na.rm
= TRUE, but these haven't worked.

Does anybody know how to solve this?
Thanks in advance,

Luís

**Comment by MayaGueguen** [comment]
Hello Luis,

Which version of the biomod2 package are you using ?
The `BIOMOD_cv` function has been replaced by the [`BIOMOD_CrossValidation` function](https://biomodhub.github.io/biomod2/reference/BIOMOD_CrossValidation.html), is it the one you are trying to use ?

Maya

**Comment by luispedrosantiago** [comment]
Hi Maya,
I am using the most recent version of the package with the function I am using is BIOMOD_CrossValidation

**Comment by MayaGueguen** [comment]
Hellos Luis,

Thanks for the information.
Could you provide me please your data so I can replicate your error ? :pray: 
(`deerPoints2010`, `deerPoints2010_LonLat` and `deerVariables.2010` objects)

However for information, it is normal that you have `NA` created by the `BIOMOD_FormatingData`, they correspond indeed to the pseudo-absence points (to be differentiated from real absences that are coded with `0`).

Maya

**Comment by maxwesemeyer** [comment]
Hi Maya,
I am using the most recent version of the package with the function I am using is BIOMOD_CrossValidation and I have a similar problem. 
This is the error I get, sorry for the German:
Error in quantile.default(bm.format@coord[balance, 1], probs = seq(0,  :
  fehlende Werte und NaNs sind nicht erlaubt, wenn 'na.rm' = FALSE

Best
Max

**Comment by MayaGueguen** [comment]
Hello there,

I have understood what's going on, and corrected it :heavy_check_mark: 
Could you please reinstall the last `biomod2` version on github to test if it is okay on your side ? :pray: 

Sorry for the inconvenience
Maya

**Comment by maxwesemeyer** [comment]
Hi Maya, 

thank you it works now. 

Best 
Max
