### ISSUE TITLE
The problem of plotting response curves

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#62]
Hi, Maya
  Today when I was running the model I found that there was a problem plotting the response curve.
  When the following two codes are run, the drawing works properly：
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'min')

However, when the following code is used, an error message appears：
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[3],
                      fixed.var = 'median',
                      do.bivariate = TRUE)
------------------------------------------------------------------------------------------
> bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
+                       models.chosen = get_built_models(myBiomodModelOut)[3],
+                       fixed.var = 'median',
+                       do.bivariate = TRUE)
  |================================================================================================================| 100%
Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): x and fill
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): x and fill
---
Backtrace:
  1. biomod2::bm_PlotResponseCurves(...)
  3. ggplot2:::print.ggplot(gg)
  5. ggplot2:::ggplot_build.ggplot(x)
  6. ggplot2 by_layer(function(l, d) l$compute_aesthetics(d, plot))
  7. ggplot2 f(l = layers[[i]], d = data[[i]])
  8. l$compute_aesthetics(d, plot)
  9. ggplot2 f(..., self = self)
 10. ggplot2:::check_aesthetics(evaled, n)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): x and fill
---
Backtrace:
     ▆
  1. └─biomod2::bm_PlotResponseCurves(...)
  2.   ├─base::print(gg)
  3.   └─ggplot2:::print.ggplot(gg)
  4.     ├─ggplot2::ggplot_build(x)
  5.     └─ggplot2:::ggplot_build.ggplot(x)
  6.       └─ggplot2 by_layer(function(l, d) l$compute_aesthetics(d, plot))
  7.         └─ggplot2 f(l = layers[[i]], d = data[[i]])
  8.           └─l$compute_aesthetics(d, plot)
  9.             └─ggplot2 f(..., self = self)
 10.               └─ggplot2:::check_aesthetics(evaled, n)
 11.                 └─rlang::abort(...)

**Comment by MayaGueguen** [comment]
Hello there,

I'm really sorry, but the function is running fine with the example data on my side...
![image](https://user-images.githubusercontent.com/16795576/168023575-1502fbec-dc21-4469-ae42-850aeb56251c.png)

Are you getting this with the example data ? Or are you using your own data ?
I would need some more details or files to be able to reproduce the error to be able to help you...

Sorry for the inconvenience
Maya

**Comment by 675979649** [comment]
Hi, Maya
Thanks for your reply.
I am running personal data. My raster data is tif and not grd.
I used the following code to read the tif:
bio_3 <- raster('E:/test/clim/bio_3.tif')
bio_8 <- raster('E:/test/clim/bio_8.tif')
bio_9 <- raster('E:/test/clim/bio_9.tif')
bio_10 <- raster('E:/test/clim/bio_10.tif')
bio_11 <- raster('E:/test/clim/bio_11.tif')
myExpl <- stack(bio_3 ,  bio_8 , bio_9 , bio_10 , bio_11 )

Here is my data: https://github.com/675979649/biomod2test.git

**Comment by MayaGueguen** [comment]
Thank you for providing me your data :)
Could you also send me your `myBiomodModelOut` object please ?

**Comment by 675979649** [comment]
Hi,
Here is my code:
library(biomod2)
library(ggplot2)
library(gridExtra)
library(raster)
library(rasterVis)
library(lattice)
library(sp)

setwd("D:/bio")

DataSpecies <- read.csv('D:/bio/Species/Ailanthus altissima.csv')
head(DataSpecies)

myRespName <- 'altissima'

myResp <- as.numeric(DataSpecies[, myRespName])

myRespXY <- DataSpecies[, c('long', 'lat')]

bio_3<- raster('D:/bio/bioclim/current/bio_3.tif')
bio_8<- raster('D:/bio/bioclim/current/bio_8.tif')
bio_9<- raster('D:/bio/bioclim/current/bio_9.tif')
bio_10<- raster('D:/bio/bioclim/current/bio_10.tif')
bio_11<- raster('D:/bio/bioclim/current/bio_11.tif')

myExpl <- stack(bio_3 , bio_8 , bio_9 , bio_10 , bio_11)

plot(myExpl)

# Format Data with true absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)
myBiomodData
plot(myBiomodData)     


myResp.PA <- ifelse(myResp == 1, 1, NA)


myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences = 500,
                                       PA.strategy = 'random')
plot(myBiomodData.r)


myBiomodOptions <- BIOMOD_ModelingOptions() 


myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.r,
                                    modeling.id = 'AllModels',
                                    bm.options = myBiomodOptions,
                                    nb.rep = 2,
                                    data.split.perc = 80,
                                    metric.eval = c('TSS','ROC'),
                                    var.import = 3,
                                    do.full.models = FALSE,
                                    nb.cpu = 8)
myBiomodModelOut


get_evaluations(myBiomodModelOut)
get_variables_importance(myBiomodModelOut, as.data.frame = TRUE)


bm_PlotEvalMean(bm.out = myBiomodModelOut)
bm_PlotEvalBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'run'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'algo'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'dataset'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'expl.var', 'dataset'))

bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                      fixed.var = 'min')
bm_PlotResponseCurves(bm.out = myBiomodModelOut, 
                      models.chosen = get_built_models(myBiomodModelOut)[3],
                      fixed.var = 'median',
                      do.bivariate = TRUE)

**Comment by MayaGueguen** [comment]
Thank you for your code !
I found the problem and corrected it, it should be fine now.

Thank you for your patience :pray: 
Maya

**Comment by 675979649** [comment]
Hi，Maya
The previous problem is well solved. Thanks a lot！
But when I use the same data to execute the following code, there is a problem：
> # Represent main results 
> gg = bm_PlotRangeSize(bm.range = myBiomodRangeSize, 
+                       do.count = TRUE,
+                       do.perc = TRUE,
+                       do.maps = TRUE,
+                       do.mean = TRUE,
+                       do.plot = TRUE,
+                       row.names = c("Species", "Dataset", "Run", "Algo"))
载入需要的名字空间：ggpubr
Error in ggarrange(gg.ca1, gg.ca2, ncol = 2) : 
  could not find function "ggarrange"
In addition: Warning messages:
1: In bm_PlotRangeSize(bm.range = myBiomodRangeSize, do.count = TRUE,  :
  Please check that rownames(bm.range$Compt.By.Models) match 'row.names' argument :
	altissima : Species
	PA1 : Dataset
	RUN1 : Run
	GLM : Algo
2: In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Warning: 无法在貯藏處https://cran.rstudio.com/src/contrib中读写索引:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'

**Comment by MayaGueguen** [comment]
I forgot to add the warning message within the `bm_PlotRangeSize` function, but it's just that it needs the `ggpubr` package to be loaded. I will do the modification soon.

Maya
