### ISSUE TITLE
error in BIOMOD_FormattingData function

### ISSUE THREAD

**Issue by brasilbrasil** [biomodhub/biomod2#65]
A stackoverflow user has recently posted a reproduceable example of an unexpected error when formatting data to run biomod2. I can confirm I am receiving the same exact error on my biomod2 code. Weirdly enough, I have tried my own biomod2 code on the same version of biomod2 (v 3.5.1) on a windows and ubuntu machines. The code runs fine on my windows machine, but I get the same error as described in the stackoverflow issue on ubuntu. 
I have checked the data inputs and they are exactly the same in both machines, and they match the specified input formats for the function. 
[https://stackoverflow.com/questions/72135255/broken-function-biomod-formatingdata-from-biomod2-package](https://stackoverflow.com/questions/72135255/broken-function-biomod-formatingdata-from-biomod2-package)
Traceback was not particularly useful (see below). Thanks for your help!
Lucas

5: stop(gettextf("unable to find an inherited method for function %s for signature %s", 
       sQuote(fdef@generic), sQuote(cnames)), domain = NA)
4: (function (classes, fdef, mtable) 
   {
       methods <- .findInheritedMethods(classes, fdef, mtable)
       if (length(methods) == 1L) 
           return(methods[[1L]])
       else if (length(methods) == 0L) {
           cnames <- paste0("\"", vapply(classes, as.character, 
               ""), "\"", collapse = ", ")
           stop(gettextf("unable to find an inherited method for function %s for signature %s", 
               sQuote(fdef@generic), sQuote(cnames)), domain = NA)
       }
       else stop("Internal error in finding inherited methods; didn't return a unique method", 
           domain = NA)
   })(list("list", "data.frame"), new("nonstandardGenericFunction", 
       .Data = function (sp, env, ...) 
       {
           standardGeneric("BIOMOD.formated.data")
       }, generic = structure("BIOMOD.formated.data", package = "biomod2"), 
       package = "biomod2", group = list(), valueClass = character(0), 
       signature = c("sp", "env"), default = NULL, skeleton = (function (sp, 
    ...
3: BIOMOD.formated.data(sp = pa.data.tmp$sp, env = pa.data.tmp$env, 
       xy = as.data.frame(pa.data.tmp$xy), sp.name = sp.name, eval.sp = eval.sp, 
       eval.env = eval.env, eval.xy = eval.xy, na.rm = na.rm)
2: BIOMOD.formated.data.PA(sp = resp.var, xy = resp.xy, env = expl.var, 
       sp.name = resp.name, eval.sp = eval.resp.var, eval.env = eval.expl.var, 
       eval.xy = eval.resp.xy, PA.NbRep = PA.nb.rep, PA.strategy = PA.strategy, 
       PA.nb.absences = PA.nb.absences, PA.dist.min = PA.dist.min, 
       PA.dist.max = PA.dist.max, PA.sre.quant = PA.sre.quant, PA.table = PA.table, 
       na.rm = na.rm)
1: BIOMOD_FormatingData(resp.name = sp_nm, resp.var = myResp, expl.var = myExpl, 
       resp.xy = myRespXY, PA.nb.rep = PA.nb.rep, PA.nb.absences = n_PA_pts, 
       PA.strategy = PA.strategy, PA.dist.min = PA.dist.min)

**Comment by brasilbrasil** [comment]
Sorry I just saw the other recently raised issue and am trying some of the options discussed (update to 4.0 or try a pred raster stack). Nevertheless, the fact the bug happens in one machine and not another is quite unexpected.

**Comment by MayaGueguen** [comment]
Hello there,

I do not remember exactly, but I think : 
1. the error was first coming from the transformation of explanatory variables into `SpatialPointsDataFrame` object
2. and then it led to another error within `biomod2 v4.0`, that I think I fixed.

Could you tell me if you are still getting an error with the last `biomod2` version ?
Thanks in advance,
Maya
