### ISSUE TITLE
model scores graphical outputs are not opening with the biomod wrapper

### ISSUE THREAD

**Issue by elisap117** [biomodhub/biomod2#68]
Hello, I am currently doing a multiple species distribution modeling using the biomod wrapper.
However, when it comes to saving the model scores in pdf format, there is no file that is saved. The error when I try opening the pdf files is "the file could not be opened"

 pdf(paste0(sp, "/", sp , "_models_scores.pdf"))
  try(gg1 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'models', plot = FALSE))
  try(gg2 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'data_set', plot = FALSE))
  try(gg3 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'cv_run', plot = FALSE))
  try(grid.arrange(gg1, gg2, gg3))
  dev.off()
That is the code that should help me get the model scores.

Kindly help me.

**Comment by elisap117** [comment]
Anyone with a solution to this? 
Kindly?

**Comment by MayaGueguen** [comment]
Hello Elisa,

Sorry for the response delay, I was on holidays :parasol_on_ground: 

As for your question, are you using the last `biomod2` version ?
The function `models_scores_graph` does not exist anymore, and has been replaced by [`bm_PlotEvalMean`](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalMean.html).

Hope it helps,
Maya
