### ISSUE TITLE
issue with BIOMOD_Projection, argument on_0_1000 = FALSE 

### ISSUE THREAD

**Issue by jehfenker** [biomodhub/biomod2#72]
Hey Biomod team,

When I ran an experiment with the default argument (on_0_1000 = TRUE), everything seems to run OK. However, when I set it as FALSE and load the '.grd' with `terra` (using terra::rast, terra::plot) it converts the result to binary (presence/absence). Even more weird is when I load it with `raster` (raster::raster, raster::plot), where the scale seems to be continuous from 0 to 1, but the plot is binary. Can you help, please?

on_0_1000 = FALSE 
<img width="681" alt="Screen Shot 2022-06-16 at 2 54 31 pm" src="https://user-images.githubusercontent.com/11275799/173995407-37951178-88fb-438b-829f-88b2e0bb4dcb.png">

on_0_1000 = TRUE, loading with `terra`
<img width="620" alt="Screen Shot 2022-06-16 at 3 08 13 pm" src="https://user-images.githubusercontent.com/11275799/173995628-3005a176-6af9-4998-b164-fa4607af2e27.png">

on_0_1000 = TRUE, loading with `raster`
<img width="733" alt="Screen Shot 2022-06-16 at 2 53 41 pm" src="https://user-images.githubusercontent.com/11275799/173995576-a7f2117c-6801-4d1f-a24f-6d0496a5972e.png">

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for reporting :pray: 

1. I will check indeed what is supposed to be done when `on_0_1000 = FALSE`, if getting binary values is the correct expected output :eyes: 
2. however, concerning the graphical representation, with either `terra` or `raster` packages, I don't see anything particularly suspicious. I think, as there is only 2 values (0 or 1), the `terra` package classifies the raster directly as categorical, while the `raster` package by default represents always values on a continuous scale, even if there is only 2 values as it is the case on your last graphic.

Maya

**Comment by jehfenker** [comment]
Hi Maya,

Thank you for your comment. I agree that there's no issue with the graphical representation.

Did you check if the binary value is the expected output? I believe it should be continuous. 

Thanks.

**Comment by basille** [comment]
Jumping in on this issue, it seems that `BIOMOD_Modeling()` did not like that commit very much. I get a series of:

```
Error in predict(model.bm, Data[, expl_var_names, drop = FALSE], on_0_1000 = on_0_1000,  : 
  object 'on_0_1000' not found
```

with the current `biomod2` version. As far as I can tell, this comes from the call to `bm_RunModelsLoop()` from within `BIOMOD_Modeling()`.

**Comment by MayaGueguen** [comment]
Erf, sorry, I should not push commits at the end of the day, not checking correctly...

@jehfenker : could you tell me which function you used with `on_0_1000 = FALSE` to still obtained projected values between 0 and 1000 please ?

**Comment by jehfenker** [comment]
Hi Maya,
Sorry for taking long to reply. Using the last dev version, when I ran 
```
model_proj <-
    biomod2::BIOMOD_Projection(modeling.output     = model_sdm,
                               new.env             = constrained_climate,
                               proj.name           = model_options_algorithm$projection_name,
                               xy.new.env          = model_options_algorithm$xy_new_env,
                               selected.models     = model_options_algorithm$selected_models,
                               binary.meth         = model_options_algorithm$binary_method,
                               filtered.meth       = model_options_algorithm$filtered.method,
                               build.clamping.mask = model_options_algorithm$build_clamping_mask,
                               silent              = model_options_algorithm$silent,
                               do.stack            = model_options_algorithm$stack,
                               keep.in.memory      = model_options_algorithm$keep_in_memory,
                               output.format       = model_options_algorithm$output_format,
                               on_0_1000           = TRUE)
plot(model_proj)
```
![Proj_current_Koala_ANN](https://user-images.githubusercontent.com/11275799/183331529-aa7189fd-5c80-4481-b49a-2649e6b9a85b.png)

It works well, but when I ran with `on_0_1000 = FALSE`, it gave me an empty map.
![Proj_current_Koala_ANN](https://user-images.githubusercontent.com/11275799/183331384-5ab38d3e-a4a4-4a62-a00a-bd7c4e3ab45c.png)
 
 I guess it is an easy fix (multiply by 0.001), but wanted to report the bug to you.

**Comment by MayaGueguen** [comment]
Hello there,

Sorry for the holiday delay :beach_umbrella: ...

You're totally right, it was the scale rendering within the plot function that was inacurrate, thanks for spotting that :pray: 
I did the correction, it seems to work correctly now :heavy_check_mark: 

Maya

**Comment by jehfenker** [comment]
Hi Maya,

I hope you had a great holiday!
Thank you for the fix. The scale is rendering correctly now, but the map outline disappeared, e.g. the Australia outline here: 
<img width="637" alt="Screen Shot 2022-08-29 at 10 41 22 am" src="https://user-images.githubusercontent.com/11275799/187104908-2a995278-f724-44cb-b5c4-3dda3a0a1c06.png">

I hope it's an easy fix!

Cheers,
Jess

**Comment by MayaGueguen** [comment]
Hello Jess,

Map is rendering only cells with projection values.
But I really only modified the labels on scale values, so this is not coming from the modification of the function.

What is it exactly you would like to have ?
Maya

**Comment by jehfenker** [comment]
Hi Maya,

previously, it was showing the Australian map outline, just that. I didn't modify anything in my code, so I thought it was on your part, but I will check here, sorry.

Returning to the first issue, the fix of the binary value when producing the map worked, but the *.grd that is created when running `BIOMOD_Projection` is still transforming the result into a binary value.

```
  model_proj <-
    biomod2::BIOMOD_Projection(bm.mod              = model_sdm,
                               new.env             = constrained_climate,
                               proj.name           = model_options_algorithm$projection_name,
                               new.env.xy          = model_options_algorithm$xy_new_env,
                               models.chosen       = model_options_algorithm$selected_models,
                               metric.binary       = model_options_algorithm$binary_method,
                               metric.filter       = model_options_algorithm$filtered.method,
                               build.clamping.mask = model_options_algorithm$build_clamping_mask,
                               do.stack            = model_options_algorithm$stack,
                               keep.in.memory      = model_options_algorithm$keep_in_memory,
                               output.format       = model_options_algorithm$output_format,
                               on_0_1000           = FALSE)
biomod2::plot(model_proj)
```
<img width="490" alt="Screen Shot 2022-08-31 at 10 29 51 am" src="https://user-images.githubusercontent.com/11275799/187567882-2fa46c22-cdbf-4ff8-b1d1-8ffba4d06fea.png">

`raster::plot(raster(paste0(path_dir, "/proj_current_Koala.grd")))`
![Rplot](https://user-images.githubusercontent.com/11275799/187568105-14380e54-e4bd-474b-adbe-815e70e03b3e.png)

**Comment by MayaGueguen** [comment]
Hello Jess,

Sorry for that, you're entirely right. I missed to change the condition on writing datatype in one place...
It is corrected now :heavy_check_mark: 

Maya

**Comment by basille** [comment]
Hey @MayaGueguen, I'm reviving this thread again as I think this bug belongs here. Since your last commit on the scale issue, plotting fails for me on a `BIOMOD.projection.out` object. Specifically, it fails [on these 2 lines](https://github.com/biomodhub/biomod2/blob/8121c59da91e3c1f27f08768549279774bed144d/R/biomod2_classes_3.R#L667-L670) with the `maxi` object:

```
              maxi <- try(cellStats(get_predictions(x, full.name = models_selected), max))
              maxi <- ifelse(maxi < 1, 1, ifelse(maxi < 1000, 1000, maxi))
```

In the GuloGulo example, `maxi` returns:

```
 [1] 1000  928 1000  985  886 1000  998 1000 1000  678 1000  927 1000  976  969 1000  998 1000 1000  680
```

which fails in the next line:

```
              my.at <- seq(0, maxi, by = 100 * maxi / 1000) ## breaks of color key
```

since `seq` expect a single number in the attributes `to` and `by`.

**Comment by rpatin** [comment]
Hello Mathieu,
Thank you for spotting the bug. I just pushed a commit that should solve the issue.
Rémi

**Comment by basille** [comment]
Thank @rpatin, so far so good, it seems to work.
