### ISSUE TITLE
Variables used in GLM runs

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#73]
Hi Maya,

I have got a set of presence points for this deer species (n = 126) and am running GLM to produce distribution maps. To do this, I have got a total of 9 raster variables and the number of runs was 100. It turns out when I run the modelling, in nearly all the runs, the selected formula includes one particular variable (which sometimes is the only variable in the formula, really) - WPDA_AmazonBiome_bin, which corresponds to PA in the rasterstack object. On the other hand, some of the variables are seldom picked (or not even picked at all), which results in variable importance values being near 0 (or actually 0), and do not make sense as I know they are biologically important. 

I am attaching the code I used and corresponding output (a part of it due to the high number of runs). On the bottom of the attachment, I added the output of the variable importance.

Is this selection made exclusively based on deltaAIC??

Thank you very much.
Luís
[Biomod2.txt](https://github.com/biomodhub/biomod2/files/8939148/Biomod2.txt)

**Comment by luispedrosantiago** [comment]
It also occurred to me that the fact that it is always pretty much the same variable being picked up may be due to the level of model support (deltaAIC)

**Comment by MayaGueguen** [comment]
Hello Luis,

When you say "_PA_", do you mean "_Pseudo-Absences_" ?
If that is, why do you put it as an explanatory variable ? It is a bit like trying to model the presence of a species and giving the absence points as a variable, it is normal that only this is selected. You should remove it.

Maya
