### ISSUE TITLE
Error in checkForRemoteErrors(val) :    3 nodes produced errors; first error: attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by KamnaPokhariya** [biomodhub/biomod2#74]
Hey, 
I am a newbie to R.  I am trying to model multiple species using BioMod2.  Initially the code is running well, creating species wise folders containing the model output. But at the end the error comes as follows. I have checked my dataset multiple times but there are no null values. please guide me where I am doing it wrong. 

Thanks
Kamna

"Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: attempt to set an attribute on NULL"

the code I am using is given following 

## launch the spiecies modelling wrapper over species list ----
if(require(snowfall)){ ## parallel computation
  ## start the cluster
  sfInit(parallel = TRUE, cpus = 5) ## here we only require 4 cpus
  sfExportAll()
  sfLibrary(biomod2)
  ## launch our wrapper in parallel
  sf_out <- sfLapply(spp_to_model, biomod2_wrapper)
  ## stop the cluster
  sfStop()
} else { ## sequencial computation
  for (sp in spp_to_model){
    biomod2_wrapper(sp)
  }
  ## or with a lapply function in sequential model
  ## all_species_bm <- lapply(spp_to_model, biomod2_wrapper)
}

### load binary projections
f_em_wmean_bin_current <- 
  paste0(
    spp_to_model,
    "/proj_current/individual_projections/", 
    spp_to_model, "_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData_TSSbin.img"
  )

####sum all projections
if(length(f_em_wmean_bin_current) >= 2){
  ## initialisation
  taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
  for(f in f_em_wmean_bin_current[-1]){
    taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
  }
}

## plot the alpha-div maps
levelplot(
  stack(
    c(
      current = taxo_alpha_div_current
    )
  ),
  main = expression(paste("Vegetation ", alpha, "-diversity")),
  par.settings = BuRdTheme
)

writeRaster(taxo_alpha_div_current, "Veg_alpha", format = "GTiff", overwrite = TRUE)

[Error.txt](https://github.com/biomodhub/biomod2/files/8940046/Error.txt)

**Comment by MayaGueguen** [comment]
Hello Kamna,

Thank you for reporting your error and providing your code.
However, your error for now, as you are parallelising your code, is only telling us : _something went wrong within several nodes_.
To have more details, could you please try running your code for one species at a time, and running step by step your `biomod2_wrapper` function ? :pray: 
This way, I would be much more able to help you :eyes: 

Thanks in advance,
Maya

**Comment by KamnaPokhariya** [comment]
Hi Maya,
Thanks for the quick response!
I did tried running the model with the single species in the same code. The code did not show any error and the output files can be seen in the working directory but I cannot plot it on R. I am copying the process below. 

Also my goal is to do the multispecies distribution modeling. how can I get that done. where I am doing wrong? 

and once again thanks a lot for your time and effort. 



> ## setup environment ----
> setwd('C:/Users/LEVL-Rhino/Desktop/Birds test')
Error in setwd("C:/Users/LEVL-Rhino/Desktop/Birds test") : 
  cannot change working directory
> ## setup environment ----
> setwd('C:/Users/LEVL-Rhino/Desktop/Bird test')
> ## read data ----
> ## species occurences data
> data <- read.csv("birds_data.csv", stringsAsFactors = FALSE)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'birds_data.csv': No such file or directory
> ## read data ----
> ## species occurences data
> data <- read.csv("birds test.csv", stringsAsFactors = FALSE)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'birds test.csv': No such file or directory
> ## read data ----
> ## species occurences data
> data <- read.csv("bird test.csv", stringsAsFactors = FALSE)
> head(data)
          species     long      lat
1 RedventedBulbul 79.98755 24.56649
2 RedventedBulbul 79.99348 24.68541
3 RedventedBulbul 79.97386 24.46844
4 RedventedBulbul 79.95859 24.47465
5 RedventedBulbul 79.89923 24.43934
6 RedventedBulbul 79.88405 24.43720
> table(data$species)

   RedventedBulbul  RedwattledLapwing RoseringedParakeet 
                47                  7                 46 
> spp_to_model <- unique(data$species)
> ## curent climatic variables
> stk_current <- 
+   raster::stack(
+     c(
+       dem =  "ddem_slope.img",
+       lst = "lst winter_slope.img",
+       ndvi =  "ndvi_winter_slope.img",
+       ndwi =  "ndwi_winter_slope.img",
+       slope =  "sslope_slope.img"
+     ),
+     RAT = FALSE
+   )
> ## build species modelling wrapper ----
> biomod2_wrapper <- function(sp){
+   cat("\n> species : ", sp)
+   
+   ## get occurrences points
+   sp_dat <- data[data$species == sp, ]
+   
+   ## formating the data
+   sp_format <- 
+     BIOMOD_FormatingData(
+       resp.var = rep(1, nrow(sp_dat)), 
+       expl.var = stk_current,
+       resp.xy = sp_dat[, c("long", "lat")],
+       resp.name = sp,
+       PA.strategy = "random", 
+       PA.nb.rep = 2, 
+       PA.nb.absences = 1000
+     )
+   
+   
+   ## print formatting summary
+   sp_format
+   
+   ## save image of input data summary
+   if(!exists(sp)) dir.create(sp)
+   pdf(paste(sp, "/", sp ,"_data_formated.pdf", sep="" ))
+   try(plot(sp_format))
+   dev.off()
+   
+   ## define models options
+   sp_opt <- BIOMOD_ModelingOptions()
+   
+   ## model species
+   sp_model <- BIOMOD_Modeling( 
+     sp_format, 
+     models = c('GLM', 'FDA', 'RF'), 
+     models.options = sp_opt, 
+     NbRunEval = 2, 
+     DataSplit = 70, 
+     Yweights = NULL, 
+     VarImport = 3, 
+     models.eval.meth = c('TSS', 'ROC'),
+     SaveObj = TRUE,
+     rescal.all.models = FALSE,
+     do.full.models = FALSE,
+     modeling.id = "demo2"
+   )
+   
+   ## save some graphical outputs
+   #### models scores
+   pdf(paste0(sp, "/", sp , "_models_scores.pdf"))
+   try(gg1 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'models', plot = TRUE))
+   try(gg2 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'data_set', plot = TRUE))
+   try(gg3 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'cv_run', plot = TRUE))
+   try(grid.arrange(gg1, gg2, gg3))
+   dev.off()
+   
+   ## build ensemble models
+   sp_ens_model <- 
+     BIOMOD_EnsembleModeling(
+       modeling.output = sp_model,
+       em.by = 'all',
+       eval.metric = 'TSS',
+       eval.metric.quality.threshold = 0.4,
+       models.eval.meth = c('TSS','ROC'),
+       prob.mean = FALSE,
+       prob.mean.weight = TRUE,
+       VarImport = 0
+     )
+   
+   ## do projections
+   proj_scen <-('current')
+   
+   for(scen in proj_scen){
+     cat("\n> projections of ", scen)
+     
+     ## single model projections
+     sp_proj <- 
+       BIOMOD_Projection(
+         modeling.output = sp_model,
+         new.env = get(paste0("stk_", scen)),
+         proj.name = scen,
+         selected.models = 'all',
+         binary.meth = "TSS",
+         filtered.meth = NULL,
+         compress = TRUE,
+         build.clamping.mask = FALSE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+     
+     ## ensemble model projections
+     sp_ens_proj <- 
+       BIOMOD_EnsembleForecasting(
+         EM.output = sp_ens_model,
+         projection.output = sp_proj,
+         binary.meth = "TSS",
+         compress = TRUE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+   }
+   
+   return(paste0(sp," modelling completed !"))
+ }
> ## launch the spiecies modelling wrapper over species list ----
> if(require(snowfall)){ ## parallel computation
+   ## start the cluster
+   sfInit(parallel = TRUE, cpus = 5) ## here we only require 4 cpus
+   sfExportAll()
+   sfLibrary(biomod2)
+   ## launch our wrapper in parallel
+   sf_out <- sfLapply(spp_to_model, biomod2_wrapper)
+   ## stop the cluster
+   sfStop()
+ } else { ## sequencial computation
+   for (sp in spp_to_model){
+     biomod2_wrapper(sp)
+   }
+   ## or with a lapply function in sequential model
+   ## all_species_bm <- lapply(spp_to_model, biomod2_wrapper)
+ }
Loading required package: snowfall
Loading required package: snow
R Version:  R version 4.2.0 (2022-04-22 ucrt) 

snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 5 CPUs.

Library biomod2 loaded.
Library biomod2 loaded in cluster.

biomod2 3.5.1 loaded.

Type browseVignettes(package='biomod2') to access directly biomod2 vignettes.
Error in checkForRemoteErrors(val) : 
  one node produced an error: attempt to set an attribute on NULL
> ## current conditons
> ### load binary projections
> f_em_wmean_bin_current <- 
+   paste0(
+     spp_to_model,
+     "/proj_current/individual_projections/", 
+     spp_to_model, "_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData_TSSbin.img"
+   )
> ####sum all projections
> if(length(f_em_wmean_bin_current) >= 2){
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
+ }
Error in raster(f_em_wmean_bin_current[1]) : 
  could not find function "raster"
> ####sum all projections
> if(length(f_em_wmean_bin_current) >= 2){
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
+ }
Error in raster(f_em_wmean_bin_current[1]) : 
  could not find function "raster"
>   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
Error in taxo_alpha_div_current : 
  object 'taxo_alpha_div_current' not found
> ## plot the alpha-div maps
> levelplot(
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+ if
Error: unexpected 'if' in:
"  taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
if"
> ## current conditons
> ### load binary projections
> f_em_wmean_bin_current <- 
+   paste0(
+     spp_to_model,
+     "/proj_current/individual_projections/", 
+     spp_to_model, "_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData_TSSbin.img"
+   )
> ####sum all projections
> if(length(f_em_wmean_bin_current) >= 2){
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
+ }
Error in raster(f_em_wmean_bin_current[1]) : 
  could not find function "raster"
> ## setup environment ----
> setwd('C:/Users/LEVL-Rhino/Desktop/Bird test')
> ## read data ----
> ## species occurences data
> data <- read.csv("bird test.csv", stringsAsFactors = FALSE)
> head(data)
             species     long      lat
1 RoseringedParakeet 80.01527 24.63211
2 RoseringedParakeet 80.00181 24.62873
3 RoseringedParakeet 80.00259 24.61622
4 RoseringedParakeet 80.00594 24.60370
5 RoseringedParakeet 79.97606 24.61738
6 RoseringedParakeet 79.95696 24.61000
> table(data$species)

RoseringedParakeet 
                46 
> spp_to_model <- unique(data$species)
> ## curent climatic variables
> stk_current <- 
+   raster::stack(
+     c(
+       dem =  "ddem_slope.img",
+       lst = "lst winter_slope.img",
+       ndvi =  "ndvi_winter_slope.img",
+       ndwi =  "ndwi_winter_slope.img",
+       slope =  "sslope_slope.img"
+     ),
+     RAT = FALSE
+   )
> ## build species modelling wrapper ----
> biomod2_wrapper <- function(sp){
+   cat("\n> species : ", sp)
+   
+   ## get occurrences points
+   sp_dat <- data[data$species == sp, ]
+   
+   ## formating the data
+   sp_format <- 
+     BIOMOD_FormatingData(
+       resp.var = rep(1, nrow(sp_dat)), 
+       expl.var = stk_current,
+       resp.xy = sp_dat[, c("long", "lat")],
+       resp.name = sp,
+       PA.strategy = "random", 
+       PA.nb.rep = 2, 
+       PA.nb.absences = 1000
+     )
+   
+   
+   ## print formatting summary
+   sp_format
+   
+   ## save image of input data summary
+   if(!exists(sp)) dir.create(sp)
+   pdf(paste(sp, "/", sp ,"_data_formated.pdf", sep="" ))
+   try(plot(sp_format))
+   dev.off()
+   
+   ## define models options
+   sp_opt <- BIOMOD_ModelingOptions()
+   
+   ## model species
+   sp_model <- BIOMOD_Modeling( 
+     sp_format, 
+     models = c('GLM', 'FDA', 'RF'), 
+     models.options = sp_opt, 
+     NbRunEval = 2, 
+     DataSplit = 70, 
+     Yweights = NULL, 
+     VarImport = 3, 
+     models.eval.meth = c('TSS', 'ROC'),
+     SaveObj = TRUE,
+     rescal.all.models = FALSE,
+     do.full.models = FALSE,
+     modeling.id = "demo2"
+   )
+   
+   ## save some graphical outputs
+   #### models scores
+   pdf(paste0(sp, "/", sp , "_models_scores.pdf"))
+   try(gg1 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'models', plot = TRUE))
+   try(gg2 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'data_set', plot = TRUE))
+   try(gg3 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'cv_run', plot = TRUE))
+   try(grid.arrange(gg1, gg2, gg3))
+   dev.off()
+   
+   ## build ensemble models
+   sp_ens_model <- 
+     BIOMOD_EnsembleModeling(
+       modeling.output = sp_model,
+       em.by = 'all',
+       eval.metric = 'TSS',
+       eval.metric.quality.threshold = 0.4,
+       models.eval.meth = c('TSS','ROC'),
+       prob.mean = FALSE,
+       prob.mean.weight = TRUE,
+       VarImport = 0
+     )
+   
+   ## do projections
+   proj_scen <-('current')
+   
+   for(scen in proj_scen){
+     cat("\n> projections of ", scen)
+     
+     ## single model projections
+     sp_proj <- 
+       BIOMOD_Projection(
+         modeling.output = sp_model,
+         new.env = get(paste0("stk_", scen)),
+         proj.name = scen,
+         selected.models = 'all',
+         binary.meth = "TSS",
+         filtered.meth = NULL,
+         compress = TRUE,
+         build.clamping.mask = FALSE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+     
+     ## ensemble model projections
+     sp_ens_proj <- 
+       BIOMOD_EnsembleForecasting(
+         EM.output = sp_ens_model,
+         projection.output = sp_proj,
+         binary.meth = "TSS",
+         compress = TRUE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+   }
+   
+   return(paste0(sp," modelling completed !"))
+ }
> ## launch the spiecies modelling wrapper over species list ----
> if(require(snowfall)){ ## parallel computation
+   ## start the cluster
+   sfInit(parallel = TRUE, cpus = 5) ## here we only require 4 cpus
+   sfExportAll()
+   sfLibrary(biomod2)
+   ## launch our wrapper in parallel
+   sf_out <- sfLapply(spp_to_model, biomod2_wrapper)
+   ## stop the cluster
+   sfStop()
+ } else { ## sequencial computation
+   for (sp in spp_to_model){
+     biomod2_wrapper(sp)
+   }
+   ## or with a lapply function in sequential model
+   ## all_species_bm <- lapply(spp_to_model, biomod2_wrapper)
+ }
Explicit sfStop() is missing: stop now.

Stopping cluster

snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 5 CPUs.

Library biomod2 loaded.
Library biomod2 loaded in cluster.


Stopping cluster

> ## current conditons
> ### load binary projections
> f_em_wmean_bin_current <- 
+   paste0(
+     spp_to_model,
+     "/proj_current/individual_projections/", 
+     spp_to_model, "_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData_TSSbin.img"
+   )
> ####sum all projections
> if(length(f_em_wmean_bin_current) >= 2){
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
+ }
> ## plot the alpha-div maps
> levelplot(
+ writeRaster(taxo_alpha_div_current, "Bird_alpha", form = "GTiff", overwrite = TRUE)
+ ## read data ----
+ ## species occurences data
+ data <- read.csv("bird test.csv", stringsAsFactors = FALSE)
Error: unexpected symbol in:
"## species occurences data
data"
> ## setup environment ----
> setwd('C:/Users/LEVL-Rhino/Desktop/Bird test')
> ## read data ----
> ## species occurences data
> data <- read.csv("bird test.csv", stringsAsFactors = FALSE)
> table(data$species)

   RedventedBulbul  RedwattledLapwing RoseringedParakeet 
                46                  7                 46 
> ## setup environment ----
> setwd('C:/Users/LEVL-Rhino/Desktop/Bird test')
> ## read data ----
> ## species occurences data
> data <- read.csv("bird test.csv", stringsAsFactors = FALSE)
> head(data)
             species     long      lat
1 RoseringedParakeet 80.01527 24.63211
2 RoseringedParakeet 80.00181 24.62873
3 RoseringedParakeet 80.00259 24.61622
4 RoseringedParakeet 80.00594 24.60370
5 RoseringedParakeet 79.97606 24.61738
6 RoseringedParakeet 79.95696 24.61000
> table(data$species)

RoseringedParakeet 
                46 
> spp_to_model <- unique(data$species)
> ## curent climatic variables
> stk_current <- 
+   raster::stack(
+     c(
+       dem =  "ddem_slope.img",
+       lst = "lst winter_slope.img",
+       ndvi =  "ndvi_winter_slope.img",
+       ndwi =  "ndwi_winter_slope.img",
+       slope =  "sslope_slope.img"
+     ),
+     RAT = FALSE
+   )
> ## build species modelling wrapper ----
> biomod2_wrapper <- function(sp){
+   cat("\n> species : ", sp)
+   
+   ## get occurrences points
+   sp_dat <- data[data$species == sp, ]
+   
+   ## formating the data
+   sp_format <- 
+     BIOMOD_FormatingData(
+       resp.var = rep(1, nrow(sp_dat)), 
+       expl.var = stk_current,
+       resp.xy = sp_dat[, c("long", "lat")],
+       resp.name = sp,
+       PA.strategy = "random", 
+       PA.nb.rep = 2, 
+       PA.nb.absences = 1000
+     )
+   
+   
+   ## print formatting summary
+   sp_format
+   
+   ## save image of input data summary
+   if(!exists(sp)) dir.create(sp)
+   pdf(paste(sp, "/", sp ,"_data_formated.pdf", sep="" ))
+   try(plot(sp_format))
+   dev.off()
+   
+   ## define models options
+   sp_opt <- BIOMOD_ModelingOptions()
+   
+   ## model species
+   sp_model <- BIOMOD_Modeling( 
+     sp_format, 
+     models = c('GLM', 'FDA', 'RF'), 
+     models.options = sp_opt, 
+     NbRunEval = 2, 
+     DataSplit = 70, 
+     Yweights = NULL, 
+     VarImport = 3, 
+     models.eval.meth = c('TSS', 'ROC'),
+     SaveObj = TRUE,
+     rescal.all.models = FALSE,
+     do.full.models = FALSE,
+     modeling.id = "demo2"
+   )
+   
+   ## save some graphical outputs
+   #### models scores
+   pdf(paste0(sp, "/", sp , "_models_scores.pdf"))
+   try(gg1 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'models', plot = TRUE))
+   try(gg2 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'data_set', plot = TRUE))
+   try(gg3 <- models_scores_graph(sp_model, metrics = c("TSS", "ROC"), by = 'cv_run', plot = TRUE))
+   try(grid.arrange(gg1, gg2, gg3))
+   dev.off()
+   
+   ## build ensemble models
+   sp_ens_model <- 
+     BIOMOD_EnsembleModeling(
+       modeling.output = sp_model,
+       em.by = 'all',
+       eval.metric = 'TSS',
+       eval.metric.quality.threshold = 0.4,
+       models.eval.meth = c('TSS','ROC'),
+       prob.mean = FALSE,
+       prob.mean.weight = TRUE,
+       VarImport = 0
+     )
+   
+   ## do projections
+   proj_scen <-('current')
+   
+   for(scen in proj_scen){
+     cat("\n> projections of ", scen)
+     
+     ## single model projections
+     sp_proj <- 
+       BIOMOD_Projection(
+         modeling.output = sp_model,
+         new.env = get(paste0("stk_", scen)),
+         proj.name = scen,
+         selected.models = 'all',
+         binary.meth = "TSS",
+         filtered.meth = NULL,
+         compress = TRUE,
+         build.clamping.mask = FALSE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+     
+     ## ensemble model projections
+     sp_ens_proj <- 
+       BIOMOD_EnsembleForecasting(
+         EM.output = sp_ens_model,
+         projection.output = sp_proj,
+         binary.meth = "TSS",
+         compress = TRUE,
+         do.stack = FALSE,
+         output.format = ".img"
+       )
+   }
+   
+   return(paste0(sp," modelling completed !"))
+ }
> ## launch the spiecies modelling wrapper over species list ----
> if(require(snowfall)){ ## parallel computation
+   ## start the cluster
+   sfInit(parallel = TRUE, cpus = 5) ## here we only require 4 cpus
+   sfExportAll()
+   sfLibrary(biomod2)
+   ## launch our wrapper in parallel
+   sf_out <- sfLapply(spp_to_model, biomod2_wrapper)
+   ## stop the cluster
+   sfStop()
+ } else { ## sequencial computation
+   for (sp in spp_to_model){
+     biomod2_wrapper(sp)
+   }
+   ## or with a lapply function in sequential model
+   ## all_species_bm <- lapply(spp_to_model, biomod2_wrapper)
+ }
snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 5 CPUs.

Library biomod2 loaded.
Library biomod2 loaded in cluster.


Stopping cluster

> ## current conditons
> ### load binary projections
> f_em_wmean_bin_current <- 
+   paste0(
+     spp_to_model,
+     "/proj_current/individual_projections/", 
+     spp_to_model, "_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData_TSSbin.img"
+   )
> ####sum all projections
> if(length(f_em_wmean_bin_current) >= 2){
+   ## initialisation
+   taxo_alpha_div_current <- raster(f_em_wmean_bin_current[1]) 
+   for(f in f_em_wmean_bin_current[-1]){
+     taxo_alpha_div_current <- taxo_alpha_div_current + raster(f)
+   }
+ }
> ## plot the alpha-div maps
+ levelplot(
+   stack(
+     c(
+       current = taxo_alpha_div_current
+     )
+   ),
+   main = expression(paste("Bird" ", alpha, "-diversity")),
Error: unexpected string constant in:
"  ),
  main = expression(paste("Bird" ", alpha, ""
>   par.settings = BuRdTheme
Error: object 'BuRdTheme' not found
> )
Error: unexpected ')' in ")"
>

**Comment by MayaGueguen** [comment]
Hello Kamna,

Thank you for taking time testing step by step :pray: 
Unfortunately, if indeed you do not have any errors when running step by step the process, then the problem must come from the parallellisation, and not from `biomod2`...
For information, if you want to speed up a bit things, there is a `nb.cpu` parameter within [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) and [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) to parallelise the computation of single and ensemble models respectively, and also in [`BIOMOD_Projection`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [`BIOMOD_EnsembleForecasting`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) to parallelise projections.

Hope it helps,
Maya

**Comment by KamnaPokhariya** [comment]
Thanks once again Maya!!
although the code worked for single species but I could not plot the output of ensemble modeling. so again I was stuck with something. And thanks for clarifying where the error is coming from. 
Since I am new to R, I am not able to perceive much from the information you provided but I will definitely look into it & try to understand!!

Many Thanks 
Kamna
