### ISSUE TITLE
Error in BIOMOD_Modeling step

### ISSUE THREAD

**Issue by karolceron** [biomodhub/biomod2#76]
Hi folks, 

I am getting the error: Error in { : task 1 failed - "argument is of length zero" when modeling with Maxent, MARS or FDA in BIOMOD_Modeling step. 

------------------
models <- 
  BIOMOD_Modeling(
    bm.format=data,
    models = c("GLM", "GBM", "RF", "GAM", "CTA", "SRE", "FDA", "MARS"),
    bm.options = opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = NULL,
    modeling.id = "demo",
    metric.eval = c("KAPPA", "TSS"))

Model=MAXENT.Phillips
	> MAXENT.Phillips modeling...
		Creating Maxent Temp Proj Data...
 Getting predictions...
Error in { : task 1 failed - "argument is of length zero" 

-----------------------------

My data:
sp.name =  Tquadri

73 presences,  0 true absences and  1000 undefined points in dataset

8 explanatory variables

  bio_13          bio_15           bio_18           bio_19           bio_2       
 Min.   :  0.0   Min.   :  0.00   Min.   :   0.0   Min.   :   0.0   Min.   : 4.643  
 1st Qu.:145.0   1st Qu.: 41.24   1st Qu.: 178.0   1st Qu.:  49.0   1st Qu.: 9.558  
 Median :248.0   Median : 61.73   Median : 337.0   Median : 153.0   Median :11.138  
 Mean   :230.8   Mean   : 61.19   Mean   : 343.6   Mean   : 332.9   Mean   :11.196  
 3rd Qu.:320.0   3rd Qu.: 80.20   3rd Qu.: 484.0   3rd Qu.: 621.0   3rd Qu.:12.367  
 Max.   :604.0   Max.   :204.61   Max.   :1321.0   Max.   :1359.0   Max.   :18.805  
     bio_3           bio_4            bio_8       
 Min.   :34.32   Min.   : 16.51   Min.   :-11.89  
 1st Qu.:61.45   1st Qu.: 56.27   1st Qu.: 21.79  
 Median :70.12   Median :109.09   Median : 24.99  
 Mean   :68.68   Mean   :190.14   Mean   : 21.94  
 3rd Qu.:78.83   3rd Qu.:288.32   3rd Qu.: 25.92  
 Max.   :91.94   Max.   :645.43   Max.   : 29.21  

 2 Pseudo Absences dataset available ( PA1 PA2 ) with  500 
absences in each (true abs + pseudo abs)

> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie 

Could you help me?

**Comment by karolceron** [comment]
Hey Maya, thank you for the response! 

I tried to run the code with another dataset (>100 presences) and get the same error

Here the code: 

`library(biomod2)
library(ggplot2)
library(gridExtra)
library(raster)
library(rasterVis)
library(sf)
library(rgdal)
library(ncdf4)
library(spThin)
library(usdm)

## read data ----
ProLau_occ<-read.table("Tquadrilineatus.txt", sep=",", header = T)
#ProLau_occ<-read.table(file.choose(), sep=",", header = T)
summary(ProLau_occ)

#thinning
occ_thin<-thin(ProLau_occ, verbose=T, 
               long.col= "long", 
               lat.col="lat", 
               spec.col= "Tupinambis_quadrilineatus", 
               thin.par= 2, 
               reps=1,
               locs.thinned.list.return=T,
               write.files=F)

occ_thin1<-data.frame(occ_thin)
occ_thin<-data.frame(occ_thin)
occ_thin$sp1<-1

# read Bioclim files
files <- list.files('./5m/', pattern='.tif$', full.names=TRUE)
predictors <- stack(files)

# crop predictors
e <- extent(-90,-30,-50,15)
layers <- crop(predictors,  e)

#Visualizando layers
plot(layers$elev)
points(occ_thin[,1:2])
      
      
spx<-extract(layers, occ_thin1)
spx<-data.frame(spx)
v<-vifstep(spx, th=5) 
v 
bioclim_ZA_sub<-exclude(layers, v)
bioclim_ZA_sub <- stack(bioclim_ZA_sub)
   

## format the data ----
ProLau_data <- 
BIOMOD_FormatingData(
resp.var = occ_thin['sp1'],
resp.xy = occ_thin[, c('Longitude','Latitude')],
expl.var = bioclim_ZA_sub,
resp.name = "Tquadri",
PA.nb.rep = 2,
PA.nb.absences = 500,
PA.strategy = 'random')
      
## formatted object summary
ProLau_data
      

myBiomodOption <- BIOMOD_ModelingOptions(MAXENT.Phillips 
 = list(path_to_maxent.jar = 'C:/Users/karol/Documents/Amazonia/maxent.jar'))

 
## define individual models options ---- 
ProLau_opt <- BIOMOD_ModelingOptions(
    GLM = list(type = 'quadratic', interaction.level = 1),
    GBM = list(n.trees = 1000),
    GAM = list(algo = 'GAM_mgcv'),
    CTA = ,
    SRE = ,
    FDA = ,
    MARS = list(interaction.level = 1),
    RF=,
    MAXENT.Phillips =
  )
      
## run the individual models ----
ProLau_models <- 
  BIOMOD_Modeling(
    bm.format=ProLau_data,
    models = c("GLM", "GBM", "RF", "GAM", "CTA", "SRE", "FDA", "MARS", "MAXENT.Phillips"),
    bm.options = ProLau_opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = NULL,
    modeling.id = "demo",
    metric.eval = c("KAPPA", "TSS"))
   `
[Tquadrilineatus.txt](https://github.com/biomodhub/biomod2/files/9009971/Tquadrilineatus.txt)

**Comment by MayaGueguen** [comment]
Thank you so much for the code and data :pray: 
Do you think you could also send me the environmental raster files, or a stack of them ?

**Comment by karolceron** [comment]
Oh, sorry

Here the code modified to obtain bioclim data

`library(biomod2)
library(ggplot2)
library(gridExtra)
library(raster)
library(rasterVis)
library(sf)
library(rgdal)
library(ncdf4)
library(spThin)
library(usdm)

## read data ----
ProLau_occ<-read.table("Tquadrilineatus.txt", sep=",", header = T)
#ProLau_occ<-read.table(file.choose(), sep=",", header = T)
summary(ProLau_occ)

#thinning
occ_thin<-thin(ProLau_occ, verbose=T, 
               long.col= "long", 
               lat.col="lat", 
               spec.col= "Tupinambis_quadrilineatus", #nome esspécie
               thin.par= 2, #remover pontos mais proximos do que 3km
               reps=1,
               locs.thinned.list.return=T,
               write.files=F)

occ_thin1<-data.frame(occ_thin)
occ_thin<-data.frame(occ_thin)
occ_thin$sp1<-1
#coordinates(occ_thin)<- ~Longitude + Latitude

# get Bioclim data
files=getData('worldclim', var='bio',res=5) 
#files <- list.files('./5m/', pattern='.tif$', full.names=TRUE)
predictors <- stack(files)

# crop predictors
e <- extent(-90,-30,-50,15)
layers <- crop(predictors,  e)

layers$bio19
#Visualizando layers
plot(layers$bio19)
#plot(layers$elev)
points(occ_thin[,1:2])
      
      
# selecao de variáveis (por colinearidade e fator de inflação)
spx<-extract(layers, occ_thin1)
spx<-data.frame(spx)
v<-vifstep(spx, th=5) #vif até 5 é aceitavel
v #variaveis selecionadas p a especie
bioclim_ZA_sub<-exclude(layers, v)
bioclim_ZA_sub <- stack(bioclim_ZA_sub)
   

## format the data ----
ProLau_data <- 
BIOMOD_FormatingData(
resp.var = occ_thin['sp1'],
resp.xy = occ_thin[, c('Longitude','Latitude')],
expl.var = bioclim_ZA_sub,
resp.name = "Tquadri",
PA.nb.rep = 2,
PA.nb.absences = 500,
PA.strategy = 'random')
      
## formatted object summary
ProLau_data
      

myBiomodOption <- BIOMOD_ModelingOptions(MAXENT.Phillips 
 = list(path_to_maxent.jar = 'C:/Users/karol/Documents/Amazonia/maxent.jar'))

 
## define individual models options ---- 
ProLau_opt <- BIOMOD_ModelingOptions(
    GLM = list(type = 'quadratic', interaction.level = 1),
    GBM = list(n.trees = 1000),
    GAM = list(algo = 'GAM_mgcv'),
    CTA = ,
    SRE = ,
    FDA = ,
    MARS = list(interaction.level = 1),
    RF=,
    MAXENT.Phillips =
  )
      
## run the individual models ----
ProLau_models <- 
  BIOMOD_Modeling(
    bm.format=ProLau_data,
    models = c("GLM", "GBM", "RF", "GAM", "CTA", "SRE", "FDA", "MARS", "MAXENT.Phillips"),
    bm.options = ProLau_opt,
    nb.rep = 2,
    data.split.perc = 80,
    var.import = NULL,
    modeling.id = "demo",
    metric.eval = c("KAPPA", "TSS"))
   `

**Comment by MayaGueguen** [comment]
Thank you so much Karoline :pray: 
I think I found the problem : could you try running your code with `var.import = 0` instead of `var.import = NULL` ?

**Comment by karolceron** [comment]
Oh god, sorry about it! 

Now it is working! 

Thank you!

**Comment by MayaGueguen** [comment]
No worries :)
A check was missing when `var.import = NULL`. I corrected it in passing. :heavy_check_mark: 

Maya
