### ISSUE TITLE
what is a new function name for models_scores_graph?

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#78]
Hi! 

I noticed that the function `models_scores_graph` https://www.rdocumentation.org/packages/biomod2/versions/3.5.1/topics/models_scores_graph is not available in version 4.0
Is there an alternative function that does similar thing?

**Comment by MayaGueguen** [comment]
Hello Yulia,

The new function doing a similar job is [`bm_PlotEvalMean`](https://biomodhub.github.io/biomod2/reference/bm_PlotEvalMean.html) :eyes: 

Maya

**Comment by yuliaUU** [comment]
thank you ! sorry- such big shifts in names, makes it hard to find. is there any hints how to quickly find the needed function when converting past codes to biomod version 4 syntax? ie I have several plotting functions like ` multiple.plot` and none of the description of a new function matches

**Comment by MayaGueguen** [comment]
Most of deprecated functions are supposed to be redirected, but it doesn't seem to work, I have to check why.
You can have a look here to find potential redirection :
https://github.com/biomodhub/biomod2/blob/master/R/DEPRECATED.R

Maya

**Comment by yuliaUU** [comment]
oh! thanks a ton! ahhaa I wish I have asked you earlier before I spent hours trying to update all my functions lol
