### ISSUE TITLE
Plot issues in biomod 4

### ISSUE THREAD

**Issue by EPSG4326** [biomodhub/biomod2#79]
Hi there,

I hope you're well, I have been using biomod2 for a year now and found it super useful. Now I'm trying to get familiar with the new version:)
I'm having an issue when trying to plot projection objects from biomod2. In previous versions, I had no issue with that but now I can't seem to fix this issue while using plot():

Error in seq.default(level.range[1], level.range[2], length.out = 101) : 
  'from' must be a finite number

It works perfectly fine with my formatted data output but not with projections. Since I'm working with a dataframe of explanatory variables, I thought the issue might be with that?

I'm attaching my files for clarity 

I would really appreciate your help
[Anabolia_nervosa.zip](https://github.com/biomodhub/biomod2/files/9047791/Anabolia_nervosa.zip)

**Comment by MayaGueguen** [comment]
Hello Graciela,

Thank you for reporting, and providing your code and data :pray: 

I just had a look at it, and indeed got the same error than you.
I also found the problem : your explanatory table has some `NA`, causing `NA` propagation and error when trying to calculate min and max values for each variable. The important point is : I solved it :heavy_check_mark: 

I just made the update onto the github, please try and reinstall the package to check if it works.
Maya

**Comment by EPSG4326** [comment]
Hi Maya, thanks for your help!!! Very appreciated.

I'll try again this weekend and let you know how it goes
G

**Comment by EPSG4326** [comment]
Hi again Maya, I completely forgot to update my experience, plotting now works perfectly fine. 

G
