### ISSUE TITLE
Biomod2 - FormatingData issue with presence data file

### ISSUE THREAD

**Issue by walternotwhite** [biomodhub/biomod2#82]
Hi BIOMODers

To start off, I am quite new to Biomod2 modeling. I used the tool to test distribution modelling for some insect species. However, with a new occurence data set I started to struggle. I am facing (most probably) a rather basic issue when  running FormatingData() with presence only data. It seems that I am missing out on something, since the formatted data spits out "0 presences,  0 true absences and 1666 undifined points in dataset". It would be great if you could give me a hint, where my coding is wrong. 

Thanks in advance for the help, very much appreciated!!

Attached below the code that gives me the error. In addition, you can find the .csv with the species data stored at the end of the console output.

**--------------------- Code ----------------------------------**
sp <- "Pyrgus alveus"
  cat("\n> species : ", sp)
  
  #species_dat <- occurence_subsample_data[occurence_subsample_data$species == sp, ]
  species_dat <- read.csv("Species_subsample_table.csv")
  species_dat <- species_dat[species_dat$species == sp, ]
  head(species_dat)
  
  species_format  <-
    BIOMOD_FormatingData(
      resp.var = rep(1,nrow(species_dat)),
      expl.var = climate_current$bio1, 
      resp.xy = species_dat[,  c("longitude","latitude")],
      resp.name = sp,
      PA.strategy = "random",
      PA.nb.rep = 2,
      PA.nb.absences = 1000
    )
  
  species_format

**Console spits out the following....**

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= 'BIOMOD.formated.data.PA' -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

sp.name =  Pyrgus.alveus

0 presences,  0 true absences and  1979 undifined points in dataset

1 explanatory variables

 bio1         
 Min.   :-12.7318  
 1st Qu.:  0.5789  
 Median :  6.2625  
 Mean   :  4.7461  
 3rd Qu.:  9.4621  
 Max.   : 12.8657  

 2 Pseudo Absences dataset available ( PA1 PA2 ) with  1000 absences in each (true abs + pseudo abs)
[Species_subsample_table.csv](https://github.com/biomodhub/biomod2/files/9085137/Species_subsample_table.csv)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by MayaGueguen** [comment]
Hello Benjamin,

Thank you for your data :pray: 
The projection system of your variable map :world_map: does not match the one of your coordinate points :1234: , that's why your Formating data object does not contain any presence points.

You should either reproject your raster into longitude/latitude projection, or your points into your raster's projection.

Maya

**Comment by walternotwhite** [comment]
Hey Maya

Amazing, thanks for the feedback. I'll direct test the projection in the evening!

Have a nice rest of the week.

Best Benjamin
