### ISSUE TITLE
How can I find the treshold that maximizes TSS for making binary projections using presence-only data?

### ISSUE THREAD

**Issue by janinepdasilva** [biomodhub/biomod2#88]
Hey all,
I'm modelling the current and future distribution of some fish species using ensemble modelling in biomod2 (presence-only data). I've already built the models and projected them for current and future conditions, but I would like to know exactly which is the threshold that maximizes TSS for binary projections. I've used the BIOMOD_Projection function with the argument binary.meth = 'TSS' but this binary projection for some species just does not make sense (e.g some species get 1 everywhere the probability of occurrence is > 0). For that reason I would lilke to manually find the threshold but I was not able to use the Find.Optim.Stat funciton with presence-only data. Can anyone help me with this?
Cheers

**Comment by MayaGueguen** [comment]
Hello there,

Here are some elements that might help you with your trouble : 

- when using the `binary.meth = TSS` argument within the [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function, it means that it will provide you a binary map of your predictions transformed into 0/1 values **by choosing a transformation threshold that maximizes the TSS value**. Hence, even if predictions are between 0 and 1, the threshold chosen will not be necessary 0.5 but any number between 0 and These thresholds can be accessed through the [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html) function.
If you would like to set this threshold by yourself, then you should refer to the [bm_BinaryTransformation](https://biomodhub.github.io/biomod2/reference/bm_BinaryTransformation.html) function.

- as your data is presence-only, you can use the [BIOMOD_PresenceOnly](https://biomodhub.github.io/biomod2/reference/BIOMOD_PresenceOnly.html) function which calculates evaluation index specific to this type of data. (_You will have though to reinstall the package from github, I just made a correction to the function_)

- finally, the Find.Optim.Stat function has been renamed as [bm_FindOptimStat](https://biomodhub.github.io/biomod2/reference/bm_FindOptimStat.html). You can find the list of all re-named functions : https://github.com/biomodhub/biomod2/blob/master/R/DEPRECATED.R.

Hope it helps,
Maya

**Comment by janinepdasilva** [comment]
Hello there,

Thank you so much for your help. Following your suggestions I was able to solve my problem!

Cheers,
Janine
