### ISSUE TITLE
Error in Ensemble Forecasting part

### ISSUE THREAD

**Issue by nihalk84** [biomodhub/biomod2#89]
Hello,
I am trying to perform ensemble modeling, I have not received any error message until establishing the ensemble model for the future. 
When I run "Biomod_EnsembleForcasting" function, I get this message : Error in .BIOMOD_EnsembleForecasting.check.args(EM.output, projection.output,  : 
  projection.output must be a 'BIOMOD.projection.out' object

I am not sure where I made a mistake in scripts. All scripts are below:

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = current_bioclim,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName,
                                     PA.nb.rep = 1,
                                     PA.nb.absences = 350,
                                     PA.strategy = 'random',
                                     na.rm = TRUE)

myBiomodData

myBiomodOption <- BIOMOD_ModelingOptions()
myBiomodModelOut <- BIOMOD_Modeling(
  myBiomodData,
  models = c('GLM','GAM','RF','GBM','SRE','ANN','CTA','MARS','FDA','MAXENT.Phillips'),
  models.options = myBiomodOption,
  NbRunEval=3,
  DataSplit=70,
  Prevalence=0.5,
  VarImport=3,
  models.eval.meth = c('TSS','ROC'),
  SaveObj = TRUE,
  rescal.all.models = TRUE,
  do.full.models = FALSE,
  modeling.id = paste('F.aurea',"FirstModeling",sep=""))
myBiomodModelOut

myBiomodEM <- BIOMOD_EnsembleModeling(
  modeling.output = myBiomodModelOut,
  chosen.models = 'all',
  em.by='all',
  eval.metric = c('TSS'),
  eval.metric.quality.threshold = c(0.8),
  prob.mean = T,
  prob.cv = T,
  prob.ci = T,
  prob.ci.alpha = 0.05,
  prob.median = T,
  committee.averaging = T,
  prob.mean.weight = T,
  prob.mean.weight.decay = 'proportional' )
myBiomodEM

myBiomodProj <- BIOMOD_Projection(
  modeling.output = myBiomodModelOut,
  new.env = current_bioclim,
  proj.name = 'current',
  selected.models = 'all',
  binary.meth = 'TSS',
  compress = 'xz',
  clamping.mask = F,
  output.format = '.grd')
myBiomodProj

myBiomodEF <- BIOMOD_EnsembleForecasting(
  EM.output = myBiomodEM,
  projection.output = myBiomodProj)

myBiomodFutureProj<- BIOMOD_Projection(
  modeling.output = myBiomodModelOut,
  new.env = mpi26_1140bioclim,
  proj.name = 'MPI_11_40_126',
  selected.models = 'all',
  binary.meth = 'TSS',
  compress = 'xz',
  clamping.mask = F,
  output.format = '.grd')
myBiomodFutureProj<-get_predictions(myBiomodFutureProj)
myBiomodFutureProj

.....The scripts are working till here.....

myBiomod1140_126_EF <- BIOMOD_EnsembleForecasting(
  EM.output = myBiomodEM,
  projection.output = myBiomodFutureProj)

.....I got this error message here:
Error in .BIOMOD_EnsembleForecasting.check.args(EM.output, projection.output,  : 
  projection.output must be a 'BIOMOD.projection.out' object

How can I solve this? Thanks.

**Comment by MayaGueguen** [comment]
Hello there,

Here is what is going wrong within your script : 

The [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function requires as `bm.proj` parameter (formerly called `projection.output`) a `BIOMOD.projection.out` as returned by the [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function.

For the first Ensemble Forecasting, you do the job right : 
```
myBiomodProj <- BIOMOD_Projection(
modeling.output = myBiomodModelOut,
new.env = current_bioclim,
proj.name = 'current',
selected.models = 'all',
binary.meth = 'TSS',
compress = 'xz',
clamping.mask = F,
output.format = '.grd')
myBiomodProj

myBiomodEF <- BIOMOD_EnsembleForecasting(
EM.output = myBiomodEM,
projection.output = myBiomodProj)
```

But for the second, you modify the `myBiomodFutureProj` object, which is no longer the direct output of the `BIOMOD_Projection` function : 
```
myBiomodFutureProj<- BIOMOD_Projection(
modeling.output = myBiomodModelOut,
new.env = mpi26_1140bioclim,
proj.name = 'MPI_11_40_126',
selected.models = 'all',
binary.meth = 'TSS',
compress = 'xz',
clamping.mask = F,
output.format = '.grd')

myBiomodFutureProj<-get_predictions(myBiomodFutureProj) ## /!\ MODIFICATION HERE /!\
myBiomodFutureProj

myBiomod1140_126_EF <- BIOMOD_EnsembleForecasting(
EM.output = myBiomodEM,
projection.output = myBiomodFutureProj)
```

You need to remove this line, and your second Ensemble Forecasting should work fine :heavy_check_mark: 
Maya

**Comment by nihalk84** [comment]
Thank you! It works!
I will pay attention while writing the naming of the in the scripts next time :)
