### ISSUE TITLE
Error in modOut[[d1]][[d2]][[d3]][["ModelName"]] : subscript out of bounds 

### ISSUE THREAD

**Issue by zoeyzuo20** [biomodhub/biomod2#9]
I am working on a SDM model with one environmental factor and Present-Only data based on the example of BIOMOD2 Simple_species_modelling.pdf

myRespName <- 'Aedes_aegypti'
a<-Aedes_aegypti_CoordinateswithXY[,myRespName]
myResp <- as.numeric(unlist(a))
myRespXY <- Aedes_aegypti_CoordinateswithXY[,c("POINT_X","POINT_Y")]

myExpl = stack( ("environmental/CHELSA/CHELSA_Annual_values/CHELSA_annual_mean_temp_Colombia.tif")) 

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp, 
                                     expl.var = myExpl, 
                                     resp.xy = myRespXY, 
                                     resp.name = myRespName)

myBiomodData

#something is wrong is this graph

plot(myBiomodData)

myBiomodOption <- BIOMOD_ModelingOptions()

#states<-as.data.frame(ModelName[,c(4)])

myBiomodModelOut <- BIOMOD_Modeling( 

  myBiomodData, 
  models = c('SRE','CTA','RF','MARS','FDA'), 
  models.options = myBiomodOption, 
  NbRunEval=3, 
  DataSplit=80, 
  Prevalence=0.5, 
  VarImport=3,
  models.eval.meth = c('TSS','ROC'),
  SaveObj = TRUE,
  rescal.all.models = TRUE,
  do.full.models = FALSE,
  modeling.id = paste(myRespName,"FirstModeling",sep=""))

myBiomodModelOut 
Error in modOut[[d1]][[d2]][[d3]][["ModelName"]] : subscript out of bounds****

Can someone tell me what should I do to fix this? I checked the previous record just saying that because this is a present - only data. :(
Someone post a solution :
myBiomodOption <- BIOMOD_ModelingOptions(
MAXENT = list( path_to_maxent.jar = getwd())
)
But it's not working for my case, this code will only make mine back to system files GuloGulo

**Comment by LLeiSong** [comment]
The same issue happened to me as well. When I set the MAXENT.Phillips modeling option to use the full background, it gave me the error 'Error in colnames(Back_swd) : object 'Back_swd' not found`. Then I use the default models.options, it gave me the same error mentioned in this issue. 

I checked the raw code, it seems that the function `Prepare.Maxent.WorkDir` fails to get the user defined `background_data_dir` parameter. 

Then I tried to update the package from CRAN and biomodhub both, but it said the dependency `maxent` is not available (for R version 3.5.0). I am not sure which maxent package this is. Is there anyway to solve this without downgrading back to older version of R.

I am using macOS. maybe this could be a problem? I know it is hard to keep updating a package. Any help would be appreciated.

**Comment by DamienGeorges** [comment]
@LLeiSong @zoeyzuo20 do you still have the problem?

Do you have any reproducible exemple?

**Comment by Abson-dev** [comment]
#DamienGeorges I have the same problem

**Comment by DamienGeorges** [comment]
any reproducible example?
