### ISSUE TITLE
Error when installing biomod2 4.1

### ISSUE THREAD

**Issue by egoberville** [biomodhub/biomod2#90]
Dear,

I am trying to install the lastest version of Biomod2, using github and `devtools::install_github("biomodhub/biomod2", dependencies = TRUE)`

However, I have a warning message: `In i.p(...) :   l'installation du package ‘C:/Users/ericg/AppData/Local/Temp/Rtmp8MUhzN/file44204d1523d1/biomod2_4.1.tar.gz’ a eu un statut de sortie non nul` and biomod 3.5.1 is the only version I can install. 

I am using R version 4.2.1, RTools 4.2 and all packages are up-to-date (since yesterday).

Thank you for your help,
Eric

**Comment by MayaGueguen** [comment]
Hello Eric,

I'm sorry that you were not able to install the latest version...
Have you managed since then ? If not, do you have any more specifications, error messages that could help me understand what's going on ?

Thanks in advance,
Maya

**Comment by egoberville** [comment]
Hello Maya,

Thank you for your kind reply. I am still unable to install the latest version. Please find the complete message, after running the installation with devtools.

`> devtools::install_github("biomodhub/biomod2", dependencies = TRUE)
Downloading GitHub repo biomodhub/biomod2@HEAD
✔  checking for file 'C:\Users\ericg\AppData\Local\Temp\Rtmpwxzl64\remotesb2d41b757712\biomodhub-biomod2-d24f851/DESCRIPTION' ... 
─  preparing 'biomod2':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'biomod2_4.1.tar.gz'
   
Installation du package dans ‘D:/R/win-library/4.0’
(car ‘lib’ n'est pas spécifié)
* installing *source* package 'biomod2' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package 'biomod2'
* removing 'D:/R/win-library/4.0/biomod2'
* restoring previous 'D:/R/win-library/4.0/biomod2'
Warning message:
In i.p(...) :
  l'installation du package ‘C:/Users/ericg/AppData/Local/Temp/Rtmpwxzl64/fileb2d44f887cbb/biomod2_4.1.tar.gz’ a eu un statut de sortie non nul`

Thanks in advance,
Eric

**Comment by MayaGueguen** [comment]
Thanks Eric for the details :pray: 

Not sure here what's going on, but it might have to do with your "_working environment_" rather than the package itself.
Here are some things to try : 

- update your R version. I can see that you're still at version 4.0 (I'm having the 4.2.1 actually) and some important changes have been made I think, at least between the 4.0 and 4.1 version
- if this does not solve it, check that you have `Rtools` package installed

Please, tell me if this installation still happens.
Maya

**Comment by egoberville** [comment]
Hi Maya,

Thank you for your quick reply. 
I already updated my R version (4.2.1), but I kept the previous package folder (4.0); and I already have the latest version of Rtools (4.2). But I can try to reinstall R to avoid a potential (unknown) issue. i also think that the problem is linked to my working environment (even if I have no issue with other packages, including installation from GithHub).

I keep you updated,
Thank you!
Eric

**Comment by egoberville** [comment]
Dear Maya,

A quick update. After having completely uninstalled R, RStudio, RTools, and associated folders, and a deep cleaning of my computer.... and a complete reinstallation, I finally managed to add the latest version of biomod! So the problem was related to my global environment and not a particular incompatibility. 

... I can now explore the new possibilities and functions offered by this new version of biomod.
Thanks again for your quick answers and your assistance,
Best,
Eric
