### ISSUE TITLE
Problem with `bm_SampleFactorLevels.raster()`

### ISSUE THREAD

**Issue by mjwestgate** [biomodhub/biomod2#92]
I'm working on the EcoCommons project, and when we use the development version `biomod2` (i.e. from the master branch of this repo) to build an ANN via [this test file](https://gitlab.com/ecocommons-australia/ecocommons-platform/ecocommons/-/blob/main/tests/testthat/test-EC_modelling_ann.R) (among others), we get the following error:
```
── Error (test-EC_modelling_ann.R:78:3): EC_modelling_ann outputs correctly for categorical data ──
Error in `sample.int(length(x), size, replace, prob)`: invalid first argument
```

Looking a little closer, this refers to a problem with `biomod2/R/bm_SampleFactorLevels.R` at lines 177-179 ([here](https://github.com/biomodhub/biomod2/blob/b6d8db34883ff2cc9a070129c25dfd1fae66e49c/R/bm_SampleFactorLevels.R#L177)):
```
selected.cells <- c(selected.cells, sapply(fact.level, function(fl) {
  sample(which(subset(expl.var, f)[] == fl), 1)
}))
```
It appears to be failing when `which(subset(expl.var, f)[] == fl)` returns an object of length zero (i.e. no matches found), because it then resolves to `sample(c(), 1)`, which gives the same error as above. Further, we only get this error when using R 4.2.0 or above, apparently because of changes to `sample` in that version (listed [here](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html)):

> sample() and sample.int() have additional sanity checks on their size and n arguments.

I tried a workaround of assigning `NULL` to avoid this error, i.e.
```
selected.cells <- c(selected.cells, sapply(fact.level, function(fl) {
  available_cells <- which(subset(expl.var, f)[] == fl)
  if(length(available_cells) > 0){
    sample(available_cells, 1)
 }else{
   NULL
  }
}))
```
...which appears to work, but then leads to later breakages, specifically failures in `bm_PlotResponseCurves()`.

Because of where this code sites in `biomod2`, it's a little difficult to provide a reprex; but let me know if you have trouble reproducing the error and I'll see what I can do.

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for reporting, and for the active search of the bug :pray: 
I did the corrections :heavy_check_mark: and also some into the `bm_PlotResponseCurves` function, but please tell me if you still encounter failures once the new version installed.

Maya

**Comment by mjwestgate** [comment]
Hi Maya, thanks heaps for following this up! That's a huge help. I'll check it out an let you know if there are any further issues, or if this can be closed :)

**Comment by MayaGueguen** [comment]
Hello Jess,

Thanks for reporting, and sorry that it's still giving an error...
I'm a bit uncertain here, as I indeed added only one line, concerning the `expl.val` column into the plot table. But I really don't see why this might give such error... And I do not get your error.
You would have a small reproducible example you could send me ? :pray: 

Maya
