### ISSUE TITLE
How can I get individual model response plots with the BIOMOD2 version 4.1?

### ISSUE THREAD

**Issue by andreslrc200983** [biomodhub/biomod2#93]
I am trying to switch to the new BIOMOD2 version 4.1. 

In a previous version, I was able to load individual models with the function "BIOMOD_LoadModels" and then be able to see the response plots for the individual model using the "biomod2::response.plot2" function.

In the current version, the function ""biomod2::response.plot2"  or the "response.plot2" is not an exported object from namespace::biomod2. (that is the error I get)

How can I plot the individual models that I obtained using the "BIOMOD_LoadModels"?

So far, by using the following code, I was able to see the response curves for specific selected models (1:3):
**bm_PlotResponseCurves(bm.out = Cy_models, 
                      models.chosen = get_built_models(Cy_models)[c(1:3)],
                      fixed.var = 'mean')**

but I cannot plot them grouping them by algorithms.

Is there a way that the response curves can be obtained individually by algorithms (for example, response curves plots for ANN, GLM, etc? (similar to the way that in the previous version was possible to make using the "biomod2::response.plot2" function)

Thank you very much for your time and help. 

Andres Rodriguez

**Comment by MayaGueguen** [comment]
Hello Andres,

Thank you for taking time and trying the new package version :pray: 

I'm not sure I understood what it is that you want and do not obtain yet with the `bm_PlotResponseCurves`.
Here below is an extract of the example code from the [bm_PlotResponseCurves](https://biomodhub.github.io/biomod2/reference/bm_PlotResponseCurves.html) : 

```
# Load species occurrences (6 species available)
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)
head(DataSpecies)

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7, 11, 12), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))


# ---------------------------------------------------------------
file.out <- paste0(myRespName, "/", myRespName, ".AllModels.models.out")
if (file.exists(file.out)) {
  myBiomodModelOut <- get(load(file.out))
} else {

  # Format Data with true absences
  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName)

  # Create default modeling options
  myBiomodOptions <- BIOMOD_ModelingOptions()

  # Model single models
  myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                      modeling.id = 'AllModels',
                                      bm.options = myBiomodOptions,
                                      nb.rep = 2,
                                      data.split.perc = 80,
                                      metric.eval = c('TSS','ROC'),
                                      var.import = 3,
                                      do.full.models = FALSE)
}


# ---------------------------------------------------------------
# Represent response curves
OUT = bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                            models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                            fixed.var = 'median')
```

The `OUT` object will contain 2 elements : 

- the plot object, rendering for each variable a line for each algorithm
![image](https://user-images.githubusercontent.com/16795576/187379359-a4c92b82-7c23-4b6a-a12f-ce8ff2008acf.png)

- and the table used to produce this plot, and that can be used to create your own customized plot : 
![image](https://user-images.githubusercontent.com/16795576/187380262-985ddfe9-f85e-4193-b32e-942d69607318.png)


Hope it helps.
Maya

**Comment by andreslrc200983** [comment]
Dear Maya:

Thank you so much for your reply. The information you have me helped me understand the creation of response curves. I was trying to obtain response curves individually by an algorithm (for example, just GLM models). Therefore, based on the code you gave me:

# ---------------------------------------------------------------
# Represent response curves
OUT = bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                            models.chosen = get_built_models(myBiomodModelOut)[c(1:3, 12:14)],
                            fixed.var = 'median')

I realized that you can do that simply by changing the numbers in the "get_built_models" function.

So if I just want to see the response curves with only a subset that includes the "GLM" models (RUN1, RUN2, and FULL), I would simply need to change the code to:

# Represent response curves
OUT = bm_PlotResponseCurves(bm.out = myBiomodModelOut,
                            models.chosen = get_built_models(myBiomodModelOut)[c(1,11,21)], 
                            fixed.var = 'median')

 
Thank you so much for your time and help in this matter. It might be a simple and basic question but I am trying to get familiarized with the new version of BIOMOD2.

Thank you again for your help.

Respectfully,

Andres Rodriguez
