### ISSUE TITLE
PA are not selected randomly

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#95]
Hi,

I have set up my biomod object:
```
myBiomodData <- BIOMOD_FormatingData(
  resp.var = SpatialPointsDataFrame(df[, 1:2], df[,3], proj4string = CRS("+proj=longlat +datum=WGS84")),
  expl.var = SpatialPointsDataFrame(df[, 1:2], df[, -c(1:3)],  proj4string = CRS("+proj=longlat +datum=WGS84")),
  resp.name ="test",
  PA.nb.rep = 2,
  PA.nb.absences =38,
  PA.strategy = 'random'
)
```

I use random selection of PA: but when I extract the coordinates where PA were taken from :
`cbind(myBiomodData@coord,myBiomodData@PA.table)`
![image](https://user-images.githubusercontent.com/54612866/187801694-7b7a9ed3-2cbd-4106-9a48-75edd495b52e.png)
exactly same set of coordinates being selected for both runs

**Comment by MayaGueguen** [comment]
Hello Yulia,

Thanks for reporting. Could you please send me your `df` object sor I can check by myself and try to understand what's going wrong ? :pray: 

Maya

**Comment by Farewe** [comment]
I think this is because the PA.table slot does contain the information of both presences and pseudoabsences for each PA set.

The first rows correspond to coordinates of presences, so yes they are supposed to be the same for all PA sets. But if you go down the table you should get to the coordinates of pseudoabsences which will most likely be different between PA1 and PA2.

**Comment by yuliaUU** [comment]
here is my `df` object : https://github.com/yuliaUU/data/blob/main/dataset.csv

**Comment by yuliaUU** [comment]
@Farewe  in column PA1 there are only TRUE and FALSE values, so only the first 38 rows are TRUE- the rest are false

**Comment by MayaGueguen** [comment]
Thank you Yulia :pray: 

I think everything is going fine, here are some insights : 

- as @Farewe mentioned, the `PA.table` contains `TRUE` or `FALSE` values, `TRUE` attributed to both presence points and selected pseudo-absence points. So the 93 first points into the `PA1` and `PA2` columns are your presence points. And then, you have 38 `TRUE` values assigned in each column, but that correspond to different points :

```
tt = cbind(myBiomodData@coord,myBiomodData@PA.table)
head(tt)
table(tt$PA1)
table(tt$PA2)
which(tt$PA1 == TRUE)
which(tt$PA1 == TRUE)
```

- however, 38 pseudo-absence points seems to me a rather low number... You can check [here](https://biomodhub.github.io/biomod2/articles/vignette_pseudoAbsences.html) for more documentation about how to select your pseudo-absences.

Hope it helps
Maya
