### ISSUE TITLE
Error when Modelling GLM with categorical variables

### ISSUE THREAD

**Issue by HoytHe** [biomodhub/biomod2#96]
Dear all,

Does anyone know how to model GLM with both continuous and categorical variables? I have 7 continuous variables (bio_*) and 1 categorical variable (sq_1, which has 8 levels from 0 to 7). The tuned options by `BIOMOD_Tuning` function showed as follows:

type = 'polynomial',
interaction.level = 0,
myFormula = Potato.Cyst.Nematode ~ I(bio_12^2) + I(bio_12^3) + bio_15 + I(bio_15^2) + I(bio_15^3) + bio_17 + I(bio_17^2) + bio_19 + I(bio_19^2) + I(bio_19^3) + bio_2 + I(bio_2^2) + I(bio_2^3) + bio_7 + I(bio_7^2) + I(bio_7^3) + bio_8 + I(bio_8^2) + I(bio_8^3) + sq_11 + sq_12 + sq_13,
test = 'none',
family = binomial(link = 'logit'),
mustart = 0.5,
control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE) 

However, when I was trying to run `BIOMOD_Modeling`, an error occurred: **Error in eval(predvars, data, env) : object 'sq_11' not found. Error in h(simpleError(msg, call)) :   error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found.**

Why these functions are not consistent? Does anyone know how to deal with this error?
Thank you so much!

Cheers,
Hoyt

**Comment by MayaGueguen** [comment]
Hello Hoyt,

Thanks for reporting.
Could you send me your data and code so I can reproduce the error please ? :pray: 

Maya

**Comment by HoytHe** [comment]
Hi Maya,

Sorry, I didn't find the port to attach the data file in this communication chunk. I can share the data summary. Maybe you can generate a data form with the following summary:
The summary of 'sq_1' is:
1: 764
6: 651
2: 512
3: 357
0: 104
4: 80
class: factor
The other bioclimate variables were downloaded from Worldclim.

My codes are as follows:
cl <- makeCluster(8)
doParallel::registerDoParallel(cl) 
trControl_5CV2<- caret::trainControl(method = 'repeatedcv', number = 5, repeats = 2, p = 0.8, summaryFunction = caret::twoClassSummary, classProbs = T, seeds = NULL)
time.seq <- system.time(tuningROC_5CV <- BIOMOD_Tuning(bm.format = BioData, models = c("GLM", "GBM", "ANN", "FDA", "RF", "MAXENT.Phillips"), metric.eval = "ROC", ctrl.train = trControl_5CV))
stopCluster(cl)
BiomodOptionsROC_5CV<- tuningROC_5CV$models.options
5CVSplit<- BIOMOD_CrossValidation(BioData, k=5, nb.rep = 2, do.full.models = FALSE)
ModelOut_Opt1_5CV <- BIOMOD_Modeling(bm.format = BioData, bm.options = BiomodOptionsROC_5CV,                                     models = c("GLM", "GBM", "ANN", "FDA", "RF", "MAXENT.Phillips"),  data.split.table = 5CVSplit, var.import = 3, metric.eval = c('TSS','ROC','KAPPA'),  do.full.models = FALSE, prevalence = 0.5)

Thanks for your help!
Cheers,
Hoyt

**Comment by rpatin** [comment]
Hello Hoyt,
Unfortunately the `glm` formula that `BIOMOD_Tuning` proposed is generated by `caret` package and not readily usable by `BIOMOD_Modeling`. You can see it with the `sq_11 + sq_12 + sq_13` in the formula, which represent the first 3 levels for your factor.  `caret` transform your 7-levels factors variable into 6 0/1 variables and then select the different variables. Unfortunately I did not find how to disable that in `caret` to make that usable by `BIOMOD_Modeling`.

To circumvent that problem, you can :
1. Forego using `BIOMOD_Tuning`
2. Use `BIOMOD_Tuning` but manually change the formula for GLM before feeding it in `BIOMOD_Modeling`. I am sorry this may not very practical, but you would need to call `BIOMOD_ModelingOptions` to manually set all required options to the output of `BIOMOD_Tunin`, except the GLM formula for which you have to change sq11+sq12+sq13 into sq1 as follows:
```
myFormula = Potato.Cyst.Nematode ~ I(bio_12^2) + I(bio_12^3) + bio_15 + I(bio_15^2) + I(bio_15^3) + bio_17 +
 I(bio_17^2) + bio_19 + I(bio_19^2) + I(bio_19^3) + bio_2 + I(bio_2^2) + 
I(bio_2^3) + bio_7 + I(bio_7^2) + I(bio_7^3) + bio_8 + I(bio_8^2) +
 I(bio_8^3) + sq_1
```

3. Do the transformation of your categorical variables before calling `BIOMOD_Tuning`, i.e., creating 7 variables 0/1 for each factor level. Then you can call the tuning and afterwards, the call to `BIOMOD_Modeling` should work properly.

Let us know if you encounter further problems or need additional informations.
Cheers,
Rémi
