### ISSUE TITLE
Error in .BIOMOD_RangeSize.check.args(CurrentPred, FutureProj, SpChange.Save) :    CurrentPred & FutureProj dimensions mismatched!

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#97]
Dear sir：
     When I run this code to find the range change, it is error as follows.Could you please tell me how to solve it?

 SRC_current_2070_BC85 <- BIOMOD_RangeSize(rapeseed_bin_proj_current, rapeseed_bin_proj_2070_BC85,SpChange.Save=NULL)

thanks!

**Comment by MayaGueguen** [comment]
Hello there,

Thanks for reporting :pray: 
I actually don't see any errors reported ... Maybe you forgot to link a file ?
I need as much information as possible to be able to help you : if possible your data and code, which version of the package you are using, and the error messages you get :eyes: 

Maya
