### ISSUE TITLE
how to load the biomod object from a repos?

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#98]
Hi!
I wonder if you can help me with the following task:
I have run several species models. The output was saved in the folders shown below:
![image](https://user-images.githubusercontent.com/54612866/188678527-76f9169b-4799-4337-b652-53555a620496.png)
is there a way to load back the object that was produced by `BIOMOD_FormatingData`,`BIOMOD_Modeling`,`BIOMOD_EnsembleModeling`,`BIOMOD_Projection`, `BIOMOD_EnsembleForecasting`?

**Comment by MayaGueguen** [comment]
Hello Yulia,

Yes, you can access normally each element you built with `biomod2` functions :

- `BIOMOD_Modeling` : you should find in `Gennadas.valens/` folder an object called something like `Gennadas.valens.mod1.models.out` with _mod1_ being the value given to the `modeling.id` parameter in the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.
You can `load` this object into your Rsession (but might have to rename it).

- `BIOMOD_EnsembleModeling` : you should find in `Gennadas.valens/` folder an object called something like `Gennadas.valens.mod1.ensemble.models.out` with _mod1_ being the value given to the `modeling.id` parameter in the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.
You can `load` this object into your Rsession (but might have to rename it).

- `BIOMOD_FormatingData` : you can either access it directly within the hidden folder `Gennadas.valens/.BIOMOD_DATA/mod1/formated.input.data` using the `load` function, or through the [get_formal_data](https://biomodhub.github.io/biomod2/reference/getters.out.html) function giving it your object obtained from the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function.

- `BIOMOD_Projection` and `BIOMOD_EnsembleForecasting` : you should find in `Gennadas.valens/proj_projname/` folder (with _projname_ being the value given to the `proj.name` parameter of [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) or [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function,) an object called something like   `Gennadas.valens.projname.projection.out` or `Gennadas.valens.projname.ensemble.projection.out`.
You can `load` this object into your Rsession (but might have to rename it).


Hope it helps
Maya

**Comment by yuliaUU** [comment]
Thank you ! that works! I was using the wrong function to do it ( not `load()`)!
