### ISSUE TITLE
Unable to plot projections

### ISSUE THREAD

**Issue by yisug** [biomodhub/biomod2#99]
I'm a student with limited experience in R, attempting to use this package for my thesis. I started out using the 3.5.1 version of biomod, but since I noticed the new function to plot a comparison between range sized I wanted to try out 4.1

Ever since I started loading my data (downloaded from WorldClim) I have had problems plotting projections. On a different machine I did a fresh install of R, Rstudio and biomod2 4.1. Without loading in any data I followed the tutorial with the GuloGulo species and the same error occurred as when using my own data. I copy pasted my output below, please let me know if I am doing something wrong or if I need to add anything.

# Project single models
 myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
                                              proj.name = 'CurrentEM',
                                              new.env = myExpl2,
                                              models.chosen = 'all',
                                              metric.binary = 'all',
                                              metric.filter = 'all')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Ensemble Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Creating suitable Workdir...

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Projecting GuloGulo_AllData_RUN1_GLM ...
	> Projecting GuloGulo_AllData_RUN1_GBM ...
	> Projecting GuloGulo_AllData_RUN1_GAM ...
	> Projecting GuloGulo_AllData_RUN1_CTA ...
	> Projecting GuloGulo_AllData_RUN1_SRE ...
	> Projecting GuloGulo_AllData_RUN1_FDA ...
	> Projecting GuloGulo_AllData_RUN1_MARS ...
	> Projecting GuloGulo_AllData_RUN1_RF ...
	> Projecting GuloGulo_AllData_RUN1_MAXENT.Phillips.2 ...
	> Projecting GuloGulo_AllData_RUN2_GLM ...
	> Projecting GuloGulo_AllData_RUN2_GBM ...
	> Projecting GuloGulo_AllData_RUN2_GAM ...
	> Projecting GuloGulo_AllData_RUN2_CTA ...
	> Projecting GuloGulo_AllData_RUN2_ANN ...
	> Projecting GuloGulo_AllData_RUN2_SRE ...
	> Projecting GuloGulo_AllData_RUN2_FDA ...
	> Projecting GuloGulo_AllData_RUN2_MARS ...
	> Projecting GuloGulo_AllData_RUN2_RF ...
	> Projecting GuloGulo_AllData_RUN2_MAXENT.Phillips.2 ...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	> Projecting GuloGulo_EMmeanByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMcvByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMciInfByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMciSupByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMmedianByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMcaByTSS_mergedAlgo_mergedRun_mergedData ...
	> Projecting GuloGulo_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData ...

	> Building KAPPA binaries
	> Building TSS binaries
	> Building ROC binaries
	> Building KAPPA filtered
	> Building TSS filtered
	> Building ROC filtered

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
myBiomodEMProj

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.projection.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Projection directory : ./GuloGulo/CurrentEM

sp.name : GuloGulo

expl.var.names : bio3 bio4 bio7 bio11 bio12

modeling.id : all (  )

models.projected : 
GuloGulo_EMmeanByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMcvByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMciInfByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMciSupByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMmedianByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMcaByTSS_mergedAlgo_mergedRun_mergedData, GuloGulo_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
plot(myBiomodEMProj)
Error in seq.default(0, maxi, by = 100 * maxi/1000) : 
  'to' must be of length 1

**Comment by rpatin** [comment]
Hello @yisug,
Thank you for reporting. We just updated the package to solve this bug.
To update to the newest version you can use : 
`library(devtools)
devtools::install_github("biomodhub/biomod2", dependencies = TRUE)`
and hopefully this should solve your problem. But please let us know if that is not the case.

**Comment by yisug** [comment]
Hi @rpatin,
Thank you for your reply. I updated the package with your code, but I keep running into the same problem. Both with my own data and with the tutorial data.

**Comment by rpatin** [comment]
Hi @yisug,
I did not manage to reproduce the bug, so could you load the `biomod2` package and copy-paste the output of : 
`sessionInfo() `
as well as :
`findMethods("plot", classes = "BIOMOD.projection.out")`
this should help us to identify what might be going wrong.

**Comment by yisug** [comment]
Hi @rpatin,

After reïnstalling the package with your code and rebooting my PC I can plot the projections again. Since then I haven't run into any problems. Thank you for taking a look at my error!
